{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/startbitratekbps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/startbitratekbps"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)MCBitrateSettings(py)startBitrateKbps","role":"symbol","symbolKind":"property","title":"startBitrateKbps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startBitrateKbps"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"startBitrateKbps","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/startBitrateKbps","interfaceLanguage":"swift"},"abstract":[{"text":"The start bitrate, in kilobits per second.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startBitrateKbps"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings/startBitrateKbps":{"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcbitratesettings\/startbitratekbps","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"startBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[{"text":"The start bitrate, in kilobits per second.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/startBitrateKbps","title":"startBitrateKbps","navigatorTitle":[{"text":"startBitrateKbps","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings":{"abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"type":"topic","title":"MCBitrateSettings","url":"\/documentation\/millicastsdk\/mcbitratesettings","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings","navigatorTitle":[{"kind":"identifier","text":"MCBitrateSettings"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCBitrateSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"startBitrateKbps"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"startBitrateKbps","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"startBitrateKbps"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1startBitrateKbps\/title","value":"startBitrateKbps","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"startBitrateKbps"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1startBitrateKbps\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/title","value":"MCBitrateSettings"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","value":[{"text":"MCBitrateSettings","kind":"identifier"}]}]}]}