{"primaryContentSections":[{"declarations":[{"tokens":[{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"reason","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsignalingerror\/reason-c.ivar"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError\/reason-c.ivar"},"metadata":{"role":"symbol","fragments":[{"text":"reason","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Variable","symbolKind":"ivar","title":"reason","navigatorTitle":[{"kind":"identifier","text":"reason"}],"externalID":"c:objc(cs)MCSignalingError@reason"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSignalingError/reason-c.ivar":{"fragments":[{"kind":"identifier","text":"reason"}],"kind":"symbol","role":"symbol","type":"topic","title":"reason","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError\/reason-c.ivar","abstract":[],"url":"\/documentation\/millicastsdk\/mcsignalingerror\/reason-c.ivar"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSignalingError":{"role":"symbol","title":"MCSignalingError","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsignalingerror","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSignalingError"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError","abstract":[{"text":"Container class for Signaling errors that occur during","type":"text"},{"text":" ","type":"text"},{"text":"signaling\/configuration of the peer connection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCSignalingError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCSignalingError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/title","op":"replace"},{"value":[{"text":"MCSignalingError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/fragments","op":"replace"},{"value":[{"text":"MCSignalingError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/navigatorTitle","op":"replace"}]}]}