{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFrameMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"withLength"},{"kind":"text","text":" "},{"kind":"internalParam","text":"length"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ssrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of metadata coming from the publisher."}]}]},{"name":"length","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Length of the metadata array"}]}]},{"name":"ssrc","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Synchronization source of the frame"}]}]},{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Timestamp of the frame"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onframemetadata(_:withlength:withssrc:withtimestamp:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onframemetadata(_:withlength:withssrc:withtimestamp:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a frame is received and not yet decoded."},{"type":"text","text":" "},{"type":"text","text":"Provide extracted metadata embedded in a frame if any."},{"type":"text","text":" "},{"type":"text","text":"Any data provided by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)"},{"type":"text","text":" "},{"type":"text","text":"can be accessed here."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}],"role":"symbol","title":"onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFrameMetadata"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"withLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCSubscriberDelegate(im)onFrameMetadata:withLength:withSsrc:withTimestamp:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onTransformableFrame(_:withSsrc:withTimestamp:)":{"navigatorTitle":[{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}],"role":"symbol","title":"onTransformableFrame(_:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after a frame has been encoded if you need to add data"},{"type":"text","text":" "},{"type":"text","text":"to this frame before the frame is passed to the RTP packetizer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)":{"navigatorTitle":[{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}],"role":"symbol","title":"onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFrameMetadata"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"withLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a frame is received and not yet decoded."},{"type":"text","text":" "},{"type":"text","text":"Provide extracted metadata embedded in a frame if any."},{"type":"text","text":" "},{"type":"text","text":"Any data provided by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)"},{"type":"text","text":" "},{"type":"text","text":"can be accessed here."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onframemetadata(_:withlength:withssrc:withtimestamp:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onFrameMetadata:withLength:withSsrc:withTimestamp:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onFrameMetadata:"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"withLength:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"length"},{"kind":"text","text":" "},{"kind":"identifier","text":"withSsrc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"ssrc"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/title","value":"onTransformableFrame:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onFrameMetadata(_:withLength:withSsrc:withTimestamp:)\/title","value":"onFrameMetadata:withLength:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onFrameMetadata(_:withLength:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}