{"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCLogLevel@MCLogLevelLog","title":"MCLogLevel.log","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"MCLogLevelLog","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"General info about what happens and which steps are performed.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/log"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"log","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcloglevel\/log"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcloglevel\/log"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel/log":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/log","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel\/log","role":"symbol","title":"MCLogLevel.log","abstract":[{"type":"text","text":"General info about what happens and which steps are performed."}],"type":"topic","navigatorTitle":[{"text":"MCLogLevelLog","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogLevel","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcloglevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","role":"symbol","abstract":[{"type":"text","text":"The log message’s level"}],"title":"MCLogLevel","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MCLogLevelLog","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCLogLevelLog"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCLogLevelLog","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1log\/title","value":"MCLogLevelLog","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1log\/fragments","value":[{"kind":"identifier","text":"MCLogLevelLog"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel"},{"op":"replace","value":[{"kind":"identifier","text":"MCLogLevel"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/fragments"}]}]}