{"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"MillicastSDK"}],"title":"MCAudioTrack","navigatorTitle":[{"text":"MCAudioTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioTrack","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)MCAudioTrack"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Manages and plays a single audio resource."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioTrack","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/remove(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/setVolume(_:)"]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiotrack"]}],"references":{"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/add(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCAudioRenderer","text":"MCAudioRenderer","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","role":"symbol","type":"topic","title":"add(_:)","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)","abstract":[{"type":"text","text":"Adds an audio renderer to render this track."},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}]},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/remove(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCAudioRenderer","kind":"typeIdentifier","text":"MCAudioRenderer"},{"kind":"text","text":")!)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/remove(_:)","role":"symbol","type":"topic","title":"remove(_:)","navigatorTitle":[{"text":"removeRenderer:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudiotrack\/remove(_:)","abstract":[{"type":"text","text":"Removes a renderer from the list."}]},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCTrack"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrack"}],"type":"topic","url":"\/documentation\/millicastsdk\/mctrack","abstract":[{"text":"Represents a captured instance of a media source.","type":"text"}],"title":"MCTrack"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/setVolume(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setVolume:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVolume"},{"text":"(","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Sets the volume of the remote audio track."}],"title":"setVolume(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/setVolume(_:)","url":"\/documentation\/millicastsdk\/mcaudiotrack\/setvolume(_:)"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack":{"type":"topic","abstract":[{"type":"text","text":"Manages and plays a single audio resource."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioTrack"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCAudioTrack","kind":"identifier"}],"title":"MCAudioTrack","url":"\/documentation\/millicastsdk\/mcaudiotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"MCAudioTrack","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MCAudioTrack","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCAudioTrack","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/remove(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/setVolume(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MCAudioTrack","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier","text":"MCTrack"}]}]},"op":"replace"},{"op":"replace","value":"addRenderer:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addRenderer:","kind":"identifier"}]},{"op":"replace","value":"removeRenderer:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1remove(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1remove(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","value":"MCTrack"},{"value":[{"kind":"identifier","text":"MCTrack"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1setVolume(_:)\/title","value":"setVolume:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1setVolume(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolume:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/title","value":"MCAudioTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/fragments","value":[{"text":"MCAudioTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}