{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMedia"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmedia"]},{"paths":["\/documentation\/millicastsdk\/mcmedia"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getAudioSources()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getPlaybackDevices()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedAudioCodecs()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedVideoCodecs()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getVideoSources()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/isNdiAvailable()"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"externalID":"c:objc(cs)MCMedia","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCMedia","kind":"identifier"}],"navigatorTitle":[{"text":"MCMedia","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","symbolKind":"class","title":"MCMedia"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Class  used  for managing media sources."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getSupportedAudioCodecs()":{"url":"\/documentation\/millicastsdk\/mcmedia\/getsupportedaudiocodecs()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getSupportedAudioCodecs","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"getSupportedAudioCodecs"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedAudioCodecs()","type":"topic","abstract":[{"type":"text","text":"Query a list of all the supported audio codecs"}],"kind":"symbol","title":"getSupportedAudioCodecs()"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getAudioSources()":{"navigatorTitle":[{"kind":"identifier","text":"getAudioSources"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcmedia\/getaudiosources()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAudioSources","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","abstract":[{"text":"Query all available audio sources.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getAudioSources()","title":"getAudioSources()"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getVideoSources()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVideoSources","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoSource","text":"MCVideoSource"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getVideoSources()","role":"symbol","type":"topic","title":"getVideoSources()","navigatorTitle":[{"text":"getVideoSources","kind":"identifier"}],"abstract":[{"type":"text","text":"Query all available video sources."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcmedia\/getvideosources()"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/isNdiAvailable()":{"role":"symbol","title":"isNdiAvailable()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/isNdiAvailable()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNdiAvailable"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether NDI support is enabled in the SDK."}],"navigatorTitle":[{"text":"isNdiAvailable","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcmedia\/isndiavailable()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getPlaybackDevices()":{"abstract":[{"type":"text","text":"Query available audio playback devices and plugins."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getPlaybackDevices()","type":"topic","navigatorTitle":[{"text":"getPlaybackDevices","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getPlaybackDevices"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioPlayback","text":"MCAudioPlayback"},{"text":"]","kind":"text"}],"role":"symbol","title":"getPlaybackDevices()","url":"\/documentation\/millicastsdk\/mcmedia\/getplaybackdevices()","kind":"symbol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MCMedia","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcmedia","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCMedia","kind":"identifier"}],"title":"MCMedia","abstract":[{"type":"text","text":"Class  used  for managing media sources."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getSupportedVideoCodecs()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedVideoCodecs()","role":"symbol","abstract":[{"type":"text","text":"Query a list of the supported video codecs."}],"title":"getSupportedVideoCodecs()","url":"\/documentation\/millicastsdk\/mcmedia\/getsupportedvideocodecs()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSupportedVideoCodecs"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSupportedVideoCodecs"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"MCMedia","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"MCMedia","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCMedia","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getAudioSources()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getPlaybackDevices()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedAudioCodecs()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedVideoCodecs()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getVideoSources()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/isNdiAvailable()"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCMedia"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedAudioCodecs()\/title","value":"getSupportedAudioCodecs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedAudioCodecs()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getSupportedAudioCodecs","kind":"identifier"}]},{"value":"getAudioSources","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getAudioSources()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getAudioSources()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getAudioSources","kind":"identifier"}]},{"value":"getVideoSources","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getVideoSources()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getVideoSources"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getVideoSources()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1isNdiAvailable()\/title","op":"replace","value":"isNdiAvailable"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isNdiAvailable"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1isNdiAvailable()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getPlaybackDevices()\/title","value":"getPlaybackDevices"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getPlaybackDevices()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getPlaybackDevices","kind":"identifier"}]},{"value":"MCMedia","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title"},{"op":"replace","value":[{"text":"MCMedia","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments"},{"value":"getSupportedVideoCodecs","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedVideoCodecs()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedVideoCodecs()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getSupportedVideoCodecs"}]}]}]}