{"abstract":[{"type":"text","text":"The MCMediaSourceStats class gathers statistics details."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMediaSourceStats"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Class","title":"MCMediaSourceStats","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCMediaSourceStats","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCMediaSourceStats","symbolKind":"class","navigatorTitle":[{"text":"MCMediaSourceStats","kind":"identifier"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/kind","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/track_identifier"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/get_type()"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcmediasourcestats-kind":{"titleInlineContent":[{"type":"text","text":"kind"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind","title":"kind","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudiosourcestats","title":"MCAudioSourceStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","type":"topic","navigatorTitle":[{"text":"MCAudioSourceStats","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSourceStats"}],"role":"symbol","abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}]},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStats"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"url":"\/documentation\/millicastsdk\/mcstats","navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","title":"MCStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats/kind":{"abstract":[{"type":"text","text":"The track type. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind"}],"title":"kind","url":"\/documentation\/millicastsdk\/mcmediasourcestats\/kind","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/kind","navigatorTitle":[{"text":"kind","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats":{"type":"topic","navigatorTitle":[{"text":"MCMediaSourceStats","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMediaSourceStats"}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats","abstract":[{"type":"text","text":"The MCMediaSourceStats class gathers statistics details."}],"title":"MCMediaSourceStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#introduction":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","type":"link","titleInlineContent":[{"text":"WebRTC standard","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"https://w3c.github.io/webrtc-stats/#dom-rtcmediasourcestats-trackidentifier":{"type":"link","title":"trackIdentifier","titleInlineContent":[{"text":"trackIdentifier","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats/get_type()":{"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"title":"get_type()","url":"\/documentation\/millicastsdk\/mcmediasourcestats\/get_type()","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier","text":"MCStatsType"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"kind":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceStats":{"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"title":"MCVideoSourceStats","url":"\/documentation\/millicastsdk\/mcvideosourcestats","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCVideoSourceStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceStats"}],"kind":"symbol"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats/track_identifier":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"track_identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats\/track_identifier","abstract":[{"type":"text","text":"The identifier of the track. see "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","isActive":true}],"title":"track_identifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/track_identifier","kind":"symbol"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MCMediaSourceStats","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"MCMediaSourceStats"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCMediaSourceStats","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/kind","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/track_identifier"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/get_type()"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"kind":"relationships","type":"inheritsFrom"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCMediaSourceStats"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","text":"MCStats","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","op":"replace","value":"MCAudioSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","value":[{"kind":"identifier","text":"MCAudioSourceStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","value":"MCStats","op":"replace"},{"value":[{"kind":"identifier","text":"MCStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1kind\/title","value":"kind","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1kind\/fragments","op":"replace","value":[{"text":"kind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","value":"MCMediaSourceStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments","value":[{"text":"MCMediaSourceStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1get_type()\/title","value":"get_type","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1get_type()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"get_type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/title","value":"MCVideoSourceStats"},{"value":[{"text":"MCVideoSourceStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1track_identifier\/title","op":"replace","value":"track_identifier"},{"value":[{"text":"track_identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1track_identifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}