{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"},"abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/frames_dropped","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/jitter","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_lost","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_received"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/get_type()"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"externalID":"c:objc(cs)MCReceivedRtpStreamStats","symbolKind":"class","title":"MCReceivedRtpStreamStats","roleHeading":"Class"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-jitter":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","title":"jitter","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","type":"link","titleInlineContent":[{"type":"text","text":"jitter"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/packets_lost":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_lost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_lost"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"packets_lost","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_lost","abstract":[{"type":"text","text":"The number of RTP packets lost during transmission or due to network issues. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost","isActive":true,"type":"reference"}],"kind":"symbol","title":"packets_lost"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesdropped":{"type":"link","title":"framesDropped","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped","titleInlineContent":[{"text":"framesDropped","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"title":"MCRtpStreamStats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics for an RTP stream."}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtpstreamstats","navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}]},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/frames_dropped":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/frames_dropped","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frames_dropped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"kind":"identifier","text":"frames_dropped"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/frames_dropped","abstract":[{"text":"The number of frames dropped during playback or processing. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped","isActive":true}],"kind":"symbol","title":"frames_dropped"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","navigatorTitle":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"kind":"symbol","abstract":[{"type":"text","text":"Statistics about an incoming remote RTP stream."}],"title":"MCRemoteInboundRtpStreamStats","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/packets_received":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_received","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_received"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"packets_received","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_received","abstract":[{"text":"The number of RTP packets received since the start of streaming. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","isActive":true}],"kind":"symbol","title":"packets_received"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","type":"topic","title":"MCReceivedRtpStreamStats","abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetsreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","title":"packetsReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","type":"link","titleInlineContent":[{"text":"packetsReceived","type":"text"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetslost":{"title":"packetsLost","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost","titleInlineContent":[{"type":"text","text":"packetsLost"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/jitter":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/jitter","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"jitter"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/jitter","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The variation in packet arrival times, indicating network congestion and latency issues. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","isActive":true,"type":"reference"}],"title":"jitter"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/get_type()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/get_type()","role":"symbol","type":"topic","title":"get_type()","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of statistics."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/get_type()"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"MCReceivedRtpStreamStats","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/frames_dropped","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/jitter","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_lost","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_received"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/get_type()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Inherited By","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"],"kind":"relationships","type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCReceivedRtpStreamStats"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","text":"MCRtpStreamStats","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"packets_lost","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_lost\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_lost\/fragments","value":[{"text":"packets_lost","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title","value":"MCRtpStreamStats"},{"value":[{"text":"MCRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1frames_dropped\/title","value":"frames_dropped"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1frames_dropped\/fragments","value":[{"kind":"identifier","text":"frames_dropped"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","value":"MCRemoteInboundRtpStreamStats"},{"op":"replace","value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments"},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_received\/title","op":"replace","value":"packets_received"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_received\/fragments","op":"replace","value":[{"kind":"identifier","text":"packets_received"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","op":"replace","value":"MCReceivedRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1jitter\/title","value":"jitter","op":"replace"},{"value":[{"kind":"identifier","text":"jitter"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1jitter\/fragments"},{"op":"replace","value":"get_type","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1get_type()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}]}]}]}