{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"type":"text","text":"The layers update event. Note that if the RtsTrack is projected"},{"text":" ","type":"text"},{"text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"so the RTS track will get multiple layer events."},{"type":"text","text":" "},{"text":"No debouncing\/deduplication is implemented.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayers"]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/active","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/inactive"],"title":"Instance Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"role":"symbol","externalID":"c:objc(cs)MCRTSRemoteTrackLayers","symbolKind":"class","title":"MCRTSRemoteTrackLayers","roleHeading":"Class"},"sections":[],"references":{"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers":{"navigatorTitle":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"abstract":[{"type":"text","text":"The layers update event. Note that if the RtsTrack is projected"},{"text":" ","type":"text"},{"text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,","type":"text"},{"type":"text","text":" "},{"text":"so the RTS track will get multiple layer events.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"No debouncing\/deduplication is implemented."}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","type":"topic","title":"MCRTSRemoteTrackLayers"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers/active":{"navigatorTitle":[{"text":"active","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer","kind":"typeIdentifier","text":"MCRTSRemoteTrackLayer"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Currently active layers in the event"}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers\/active","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/active","type":"topic","title":"active"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/encodingId":{"navigatorTitle":[{"text":"encodingId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/encodingid","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/encodingId","title":"encodingId"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers/inactive":{"navigatorTitle":[{"text":"inactive","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inactive"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"text":"Currently inactive layers in the event, where each element is the","type":"text"},{"type":"text","text":" "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/encodingId","isActive":true,"type":"reference"},{"type":"text","text":" of the inactive layer"}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers\/inactive","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/inactive","title":"inactive"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCRTSRemoteTrackLayers"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/active","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/inactive"],"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayers"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/title","value":"MCRTSRemoteTrackLayers"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/fragments","value":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"op":"replace"},{"value":"active","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1active\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1active\/fragments","value":[{"kind":"identifier","text":"active"}]},{"op":"replace","value":"encodingId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1encodingId\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1encodingId\/fragments","value":[{"kind":"identifier","text":"encodingId"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1inactive\/title","value":"inactive","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1inactive\/fragments","value":[{"text":"inactive","kind":"identifier"}]}]}]}