{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","title":"MCSentRtpStreamStats","navigatorTitle":[{"text":"MCSentRtpStreamStats","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","externalID":"c:objc(cs)MCSentRtpStreamStats","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/bytes_sent","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/packets_sent"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/get_type()"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"],"title":"Inherited By"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSentRtpStreamStats"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"type":"text","text":"Statistics related to an outgoing RTP stream."}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/bytes_sent":{"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/bytes_sent","abstract":[{"type":"text","text":"The number of bytes sent in RTP packets over the network. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","type":"reference"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/bytes_sent","title":"bytes_sent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes_sent","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"bytes_sent","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/get_type()":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/get_type()","abstract":[{"type":"text","text":"Returns the type of statistics."}],"title":"get_type()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/get_type()"},"https://w3c.github.io/webrtc-stats/#dom-rtcsentrtpstreamstats-packetssent":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent","titleInlineContent":[{"type":"text","text":"packetsSent"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent","title":"packetsSent","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcsentrtpstreamstats-bytessent":{"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","title":"bytesSent","titleInlineContent":[{"type":"text","text":"bytesSent"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/packets_sent":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/packets_sent","abstract":[{"type":"text","text":"The number of RTP packets successfully sent over the network. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/packets_sent","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"packets_sent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","kind":"symbol","title":"packets_sent","navigatorTitle":[{"text":"packets_sent","kind":"identifier"}]},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics related to an outgoing remote RTP stream."}],"type":"topic","title":"MCRemoteOutboundRtpStreamStats"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"}],"type":"topic","title":"MCSentRtpStreamStats","url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","abstract":[{"text":"Statistics related to an outgoing RTP stream.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"title":"MCRtpStreamStats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics for an RTP stream."}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtpstreamstats","navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"title":"MCOutboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","abstract":[{"text":"Statistics about the outbound RTP streams","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCSentRtpStreamStats"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/bytes_sent","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/packets_sent"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/get_type()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"],"type":"inheritedBy"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)MCRtpStreamStats","kind":"typeIdentifier","text":"MCRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1bytes_sent\/title","value":"bytes_sent","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"bytes_sent"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1bytes_sent\/fragments"},{"op":"replace","value":"get_type","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1get_type()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1get_type()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1packets_sent\/title","value":"packets_sent"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1packets_sent\/fragments","value":[{"kind":"identifier","text":"packets_sent"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title","value":"MCRemoteOutboundRtpStreamStats"},{"op":"replace","value":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"},{"value":"MCSentRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments","op":"replace","value":[{"text":"MCSentRtpStreamStats","kind":"identifier"}]},{"value":"MCRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"op":"replace"}]}]}