{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"type":"text","text":"A type erased stream details class. A holder"},{"text":" ","type":"text"},{"text":"For either Stream Publish Details or Stream View Details.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class contains the current streaming"},{"text":" ","type":"text"},{"text":"session identifying information. Used to correlate","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"debugging info with a particular streaming session."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCStreamDetails","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstreamdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstreamdetails"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"class","externalID":"c:objc(cs)MCStreamDetails","roleHeading":"Class","title":"MCStreamDetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStreamDetails","kind":"identifier"}],"navigatorTitle":[{"text":"MCStreamDetails","kind":"identifier"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asPublishDetails()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asViewDetails()"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails/asPublishDetails()":{"navigatorTitle":[{"text":"asPublishDetails","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asPublishDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStreamPublishDetails","preciseIdentifier":"c:objc(cs)MCStreamPublishDetails"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asPublishDetails()","url":"\/documentation\/millicastsdk\/mcstreamdetails\/aspublishdetails()","kind":"symbol","type":"topic","title":"asPublishDetails()","role":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails/asViewDetails()":{"title":"asViewDetails()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asViewDetails","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamViewDetails","text":"MCStreamViewDetails"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcstreamdetails\/asviewdetails()","abstract":[],"navigatorTitle":[{"text":"asViewDetails","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asViewDetails()"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStreamDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcstreamdetails","title":"MCStreamDetails","abstract":[{"type":"text","text":"A type erased stream details class. A holder"},{"text":" ","type":"text"},{"text":"For either Stream Publish Details or Stream View Details.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class contains the current streaming"},{"text":" ","type":"text"},{"type":"text","text":"session identifying information. Used to correlate"},{"text":" ","type":"text"},{"text":"debugging info with a particular streaming session.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCStreamDetails"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCStreamDetails"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCStreamDetails","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MCStreamDetails","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asPublishDetails()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asViewDetails()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStreamDetails"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asPublishDetails()\/title","value":"asPublishDetails"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asPublishDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asPublishDetails()\/fragments"},{"value":"asViewDetails","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asViewDetails()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asViewDetails"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asViewDetails()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/title","value":"MCStreamDetails"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStreamDetails"}]}]}]}