{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder","interfaceLanguage":"swift"},"abstract":[{"text":"Responsible for building a video source object.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"MCVideoSourceBuilder","symbolKind":"class","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoSourceBuilder","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)MCVideoSourceBuilder"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/build()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/setCapabilities(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"title":"MCSourceBuilder","url":"\/documentation\/millicastsdk\/mcsourcebuilder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","abstract":[{"text":"Responsible for building a source object.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder/setCapabilities(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/setCapabilities(_:)","type":"topic","abstract":[{"type":"text","text":"Sets capabilities for the video source."}],"title":"setCapabilities(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCapabilities","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:objc(cs)MCVideoCapabilities","kind":"typeIdentifier","text":"MCVideoCapabilities"},{"kind":"text","text":"]!)"}],"navigatorTitle":[{"text":"setCapabilities:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideosourcebuilder\/setcapabilities(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder/build()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"text":"!","kind":"text"}],"title":"build()","role":"symbol","navigatorTitle":[{"text":"build","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideosourcebuilder\/build()","kind":"symbol","abstract":[{"text":"Builds the VideoSource class.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/build()","type":"topic"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"title":"MCVideoSourceBuilder","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceBuilder"}],"url":"\/documentation\/millicastsdk\/mcvideosourcebuilder","kind":"symbol","abstract":[{"text":"Responsible for building a video source object.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MCVideoSourceBuilder"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/build()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/setCapabilities(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoSourceBuilder"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","text":"MCSourceBuilder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSourceBuilder"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title","op":"replace","value":"MCSourceBuilder"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments","value":[{"kind":"identifier","text":"MCSourceBuilder"}],"op":"replace"},{"op":"replace","value":"setCapabilities:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1setCapabilities(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"setCapabilities:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1setCapabilities(_:)\/fragments","op":"replace"},{"op":"replace","value":"build","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1build()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1build()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}],"op":"replace"},{"value":"MCVideoSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/title"},{"value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/fragments"}]}]}