{"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/format","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/fps","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/width"],"title":"Instance Properties"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/formatAsString()"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideocapabilities"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideocapabilities"]}],"abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities"},"metadata":{"navigatorTitle":[{"text":"MCVideoCapabilities","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCVideoCapabilities","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCVideoCapabilities","role":"symbol","roleHeading":"Class","title":"MCVideoCapabilities"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCVideoCapabilities","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/fps":{"title":"fps","abstract":[{"type":"text","text":"The frame rate that defines the number of frames per second that the video track should be capable of delivering or receiving."}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities\/fps","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/fps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fps"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fps"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/format":{"url":"\/documentation\/millicastsdk\/mcvideocapabilities\/format","abstract":[{"type":"text","text":"The pixel format to use for the capture."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier","text":"MCVideoType"}],"type":"topic","role":"symbol","title":"format","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/format","navigatorTitle":[{"text":"format","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/height":{"abstract":[{"type":"text","text":"The height of the captured video frame."}],"kind":"symbol","type":"topic","title":"height","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/height","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities\/height"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/width":{"navigatorTitle":[{"kind":"identifier","text":"width"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideocapabilities\/width","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/width","abstract":[{"type":"text","text":"The width of the captured video frame."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"width","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/formatAsString()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"formatAsString"}],"title":"formatAsString()","kind":"symbol","abstract":[{"text":"Gets the pixel format as a string","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcvideocapabilities\/formatasstring()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formatAsString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/formatAsString()"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities":{"kind":"symbol","abstract":[{"text":"This VideoCapabilities class represents the video capabilities of a video track.","type":"text"}],"navigatorTitle":[{"text":"MCVideoCapabilities","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCVideoCapabilities","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities","title":"MCVideoCapabilities","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCVideoCapabilities"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCVideoCapabilities","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoCapabilities"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/format","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/fps","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/width"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/formatAsString()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoCapabilities"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1fps\/title","value":"fps"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1fps\/fragments","value":[{"kind":"identifier","text":"fps"}]},{"value":"format","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1format\/title","op":"replace"},{"value":[{"text":"format","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1format\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1height\/title","value":"height","op":"replace"},{"value":[{"text":"height","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1height\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"value":"formatAsString","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1formatAsString()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1formatAsString()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatAsString"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/title","value":"MCVideoCapabilities"},{"value":[{"kind":"identifier","text":"MCVideoCapabilities"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments"}]}]}