{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class represents a remote track which was requested by the application"},{"text":" ","type":"text"},{"text":"for the purpose of implementing advanced projection schemes (like keeping the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"RTS media projected when they go inactive, or projecting the same RTS media"},{"type":"text","text":" "},{"type":"text","text":"onto multiple tracks)."},{"text":" ","type":"text"},{"type":"text","text":"Once obtained, the track remains valid as long as the viewer is not"},{"type":"text","text":" "},{"type":"text","text":"destroyed."}]}]}],"abstract":[{"type":"text","text":"The webrtc logical track."}],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/cName","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/currentMID","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/kind"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asAudio()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asVideo()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/mid()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/midPublisher()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabled()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabledPublisher()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/unproject(completionHandler:)"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"roleHeading":"Class","role":"symbol","title":"MCWebrtcRemoteTrack","externalID":"c:objc(cs)MCWebrtcRemoteTrack","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/delegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/delegate","abstract":[{"text":"Delegate to receive track related events.","type":"text"}],"title":"delegate","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrackDelegate","preciseIdentifier":"c:objc(pl)MCWebrtcRemoteTrackDelegate"},{"kind":"text","text":")?"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"type":"topic","title":"MCWebrtcRemoteVideoTrack"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/trackDisabled()":{"title":"trackDisabled()","abstract":[{"type":"text","text":"Create an AsyncStream that is invoked whenever the track gets disabled."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabled()","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabled()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackDisabled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/midPublisher()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/midPublisher()","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/midpublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"midPublisher"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"midPublisher()","abstract":[{"text":"Create a Combine based publisher that is invoked whenever the underlying mid gets","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"updated."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/asAudio()":{"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asAudio()","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asaudio()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asAudio"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"asAudio","kind":"identifier"}],"title":"asAudio()"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/trackDisabledPublisher()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackDisabledPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"title":"trackDisabledPublisher()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabledPublisher()","abstract":[{"text":"Create a Combine based publisher that is invoked whenever the track gets disabled.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabledpublisher()","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/currentMID":{"type":"topic","abstract":[{"type":"text","text":"The current MID of this track."}],"role":"symbol","navigatorTitle":[{"text":"currentMID","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/currentMID","kind":"symbol","title":"currentMID","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentMID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/currentmid"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","navigatorTitle":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The webrtc logical track’s audio interface."}],"title":"MCWebrtcRemoteAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/asVideo()":{"abstract":[{"text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asVideo()","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asvideo()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asVideo","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCWebrtcRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteVideoTrack","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asVideo"}],"title":"asVideo()"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/cName":{"role":"symbol","abstract":[{"text":"The cname of the track. Cname represents a grouping for synchronization purposes.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/cName","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/cname","navigatorTitle":[{"text":"cName","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"cName","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/unproject(completionHandler:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unproject"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unproject this webrtc track."},{"type":"text","text":" "},{"text":"After unprojection, the service no longer streams media to this track.","type":"text"}],"title":"unproject(completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/unproject(completionHandler:)","navigatorTitle":[{"text":"unprojectWithCompletionHandler:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/unproject(completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/mid()":{"kind":"symbol","title":"mid()","abstract":[{"type":"text","text":"Create an AsyncStream that is invoked whenever the underlying mid gets"},{"type":"text","text":" "},{"text":"updated.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/mid()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mid"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?>","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/mid()"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/kind":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/kind","navigatorTitle":[{"text":"kind","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Either an Audio or Video track."}],"type":"topic","title":"kind","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/kind","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCWebrtcRemoteTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/cName","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/currentMID","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/kind"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asAudio()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asVideo()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/unproject(completionHandler:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCWebrtcRemoteTrack"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"delegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1delegate\/fragments","op":"replace"},{"op":"replace","value":"MCWebrtcRemoteVideoTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asAudio()\/title","op":"replace","value":"asAudio"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asAudio"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asAudio()\/fragments","op":"replace"},{"value":"currentMID","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1currentMID\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1currentMID\/fragments","value":[{"kind":"identifier","text":"currentMID"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title","value":"MCWebrtcRemoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asVideo()\/title","value":"asVideo"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asVideo()\/fragments","value":[{"kind":"text","text":"- "},{"text":"asVideo","kind":"identifier"}]},{"value":"cName","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1cName\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1cName\/fragments","value":[{"kind":"identifier","text":"cName"}]},{"op":"replace","value":"MCWebrtcRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1unproject(completionHandler:)\/title","value":"unprojectWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1unproject(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unprojectWithCompletionHandler:"}],"op":"replace"},{"value":"kind","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1kind\/title","op":"replace"},{"value":[{"kind":"identifier","text":"kind"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1kind\/fragments"}]}]}