{"abstract":[{"text":"Query whether the source is currently capturing.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/iscapturing()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/iscapturing()"]}],"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCCustomAudioSource(im)isCapturing","title":"isCapturing()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCapturing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/isCapturing()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the application is capturing, false otherwise."}]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/isCapturing()":{"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/iscapturing()","type":"topic","abstract":[{"type":"text","text":"Query whether the source is currently capturing."}],"navigatorTitle":[{"kind":"identifier","text":"isCapturing"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/isCapturing()","title":"isCapturing()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isCapturing","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","title":"MCCustomAudioSource","navigatorTitle":[{"text":"MCCustomAudioSource","kind":"identifier"}],"abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"type":"topic","url":"\/documentation\/millicastsdk\/mccustomaudiosource","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCCustomAudioSource","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isCapturing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"isCapturing","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"kind":"text","text":") "},{"kind":"identifier","text":"isCapturing"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"isCapturing","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1isCapturing()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isCapturing"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1isCapturing()\/fragments","op":"replace"},{"value":"MCCustomAudioSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments","value":[{"text":"MCCustomAudioSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}