{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/current_round_trip_time"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"current_round_trip_time","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats"]]},"metadata":{"role":"symbol","title":"current_round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"current_round_trip_time"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"current_round_trip_time"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCIceCandidatePairStats(py)current_round_trip_time","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/current_round_trip_time"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/current_round_trip_time"]}],"abstract":[{"type":"text","text":"Represents the latest round trip time measured in seconds. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","type":"reference","isActive":true}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime":{"titleInlineContent":[{"type":"text","text":"currentroundtriptime"}],"type":"link","title":"currentroundtriptime","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats":{"abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","role":"symbol","title":"MCIceCandidatePairStats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIceCandidatePairStats"}],"navigatorTitle":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/current_round_trip_time":{"role":"symbol","title":"current_round_trip_time","type":"topic","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/current_round_trip_time","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/current_round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"current_round_trip_time"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"current_round_trip_time"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents the latest round trip time measured in seconds. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","type":"reference","isActive":true}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"current_round_trip_time","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"current_round_trip_time"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"current_round_trip_time"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title","op":"replace","value":"MCIceCandidatePairStats"},{"value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1current_round_trip_time\/title","value":"current_round_trip_time"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1current_round_trip_time\/fragments","value":[{"kind":"identifier","text":"current_round_trip_time"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}