{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCSourceType","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType","preciseIdentifier":"c:@E@MCSourceType"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType","type":"reference"},{"text":" source type.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource\/getType()"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getType"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCSourceType","preciseIdentifier":"c:@E@MCSourceType"}],"role":"symbol","externalID":"c:objc(cs)MCSource(im)getType","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","title":"getType()","navigatorTitle":[{"kind":"identifier","text":"getType"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"]]},"abstract":[{"text":"Gets the source type.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsource\/gettype()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsource\/gettype()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSource":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource","url":"\/documentation\/millicastsdk\/mcsource","title":"MCSource","abstract":[{"text":"Gathers information about the source.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"abstract":[{"text":"The Source type","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType","title":"MCSourceType","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSource/getType()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCSourceType","text":"MCSourceType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getType","kind":"identifier"}],"role":"symbol","title":"getType()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource\/getType()","url":"\/documentation\/millicastsdk\/mcsource\/gettype()","abstract":[{"text":"Gets the source type.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"getType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"MCSourceType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCSourceType"},{"text":") ","kind":"text"},{"text":"getType","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType"},{"type":"text","text":" source type."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"kind":"identifier","text":"MCSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/navigatorTitle","value":[{"text":"MCSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/navigatorTitle","value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource~1getType()\/title","value":"getType","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource~1getType()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getType"}],"op":"replace"}]}]}