{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t1","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t1"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"MCScalabilityMode.l3t1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t1"}],"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL3T1","symbolKind":"case","navigatorTitle":[{"text":"MCScalabilityModeL3T1","kind":"identifier"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t1"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t1"]}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"type":"text","text":" to understand where these values come from"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t1":{"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t1","type":"topic","abstract":[],"navigatorTitle":[{"text":"MCScalabilityModeL3T1","kind":"identifier"}],"title":"MCScalabilityMode.l3t1","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l3t1","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t1","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"title":"the WebRTC standard"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCScalabilityModeL3T1"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeL3T1","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeL3T1"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"kind":"identifier","text":"MCScalabilityMode"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t1\/title","value":"MCScalabilityModeL3T1"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t1\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeL3T1"}]}]}]}