{"sections":[],"metadata":{"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS2T1h","title":"MCScalabilityMode.s2t1h","role":"symbol","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t1h","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T1h"}],"roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1h","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s2t1h"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1h"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1h"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"references":{"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"type":"text","text":" to understand where these values come from"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t1h":{"navigatorTitle":[{"text":"MCScalabilityModeS2T1h","kind":"identifier"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t1h","kind":"identifier"}],"title":"MCScalabilityMode.s2t1h","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1h","kind":"symbol","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCScalabilityModeS2T1h","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCScalabilityModeS2T1h","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCScalabilityModeS2T1h"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCScalabilityMode","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCScalabilityMode"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","op":"replace"},{"value":"MCScalabilityModeS2T1h","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1h\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCScalabilityModeS2T1h"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1h\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}