{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T3h"}],"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS3T3h","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t3h"}],"roleHeading":"Case","symbolKind":"case","title":"MCScalabilityMode.s3t3h","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3h"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s3t3h","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s3t3h"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s3t3h"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"type":"text","text":" to understand where these values come from"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t3h":{"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t3h","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t3h"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T3h"}],"title":"MCScalabilityMode.s3t3h","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCScalabilityModeS3T3h","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeS3T3h"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeS3T3h"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3h\/title","value":"MCScalabilityModeS3T3h","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3h\/fragments","value":[{"text":"MCScalabilityModeS3T3h","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}