{"abstract":[{"text":"The current audio level. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel","isActive":true}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"audio_level","externalID":"c:objc(cs)MCAudioSourceStats(py)audio_level","symbolKind":"property","navigatorTitle":[{"text":"audio_level","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/audio_level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/audio_level"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio_level","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/audio_level"},"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats":{"navigatorTitle":[{"text":"MCAudioSourceStats","kind":"identifier"}],"title":"MCAudioSourceStats","url":"\/documentation\/millicastsdk\/mcaudiosourcestats","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSourceStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stastistics representing an audio track that is attached to one or more senders."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats/audio_level":{"url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/audio_level","title":"audio_level","navigatorTitle":[{"kind":"identifier","text":"audio_level"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/audio_level","role":"symbol","abstract":[{"type":"text","text":"The current audio level. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio_level","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-audiolevel":{"title":"audioLevel","type":"link","titleInlineContent":[{"type":"text","text":"audioLevel"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audio_level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"audio_level","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"audio_level","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","op":"replace","value":"MCAudioSourceStats"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","op":"replace","value":[{"text":"MCAudioSourceStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1audio_level\/title","op":"replace","value":"audio_level"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1audio_level\/fragments","op":"replace","value":[{"text":"audio_level","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}