{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"abstract":[{"text":"Excluded sources that you do not wish to receive. Refer to ","type":"text"},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","isActive":true,"type":"reference"},{"type":"text","text":" to learn more about this. This is a subscriber only option."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/excludedsourceid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/excludedsourceid"]}],"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/excludedSourceId","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"excludedSourceId"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"excludedSourceId","kind":"identifier"}],"role":"symbol","title":"excludedSourceId","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCClientOptions(py)excludedSourceId","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"excludedSourceId","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}]},"references":{"https://docs.dolby.io/streaming-apis/docs/multiview":{"title":" The Multiview Guide","titleInlineContent":[{"text":" The Multiview Guide","type":"text"}],"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"url":"\/documentation\/millicastsdk\/mcclientoptions","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","kind":"symbol","type":"topic","title":"MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCClientOptions","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/excludedSourceId":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/excludedSourceId","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"excludedSourceId"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedSourceId"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"title":"excludedSourceId","abstract":[{"text":"Excluded sources that you do not wish to receive. Refer to ","type":"text"},{"type":"reference","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","isActive":true},{"text":" to learn more about this. This is a subscriber only option.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/excludedsourceid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"excludedSourceId","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"excludedSourceId","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"excludedSourceId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MCClientOptions","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1excludedSourceId\/title","value":"excludedSourceId"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1excludedSourceId\/fragments","op":"replace","value":[{"text":"excludedSourceId","kind":"identifier"}]}]}]}