{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:renderer:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frameRect","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"frameRect","content":[{"type":"paragraph","inlineContent":[{"text":"A rectangle representing the frame.","type":"text"}]}]},{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The sample buffer video renderer. This renderer would have to be attached to"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack"},{"type":"text","text":" "},{"type":"text","text":"to receive the track content."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"init","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:12MillicastSDK25MCSampleBufferVideoUIViewC5frame8rendererACSo6CGRectV_So010MCCMSampledE8RendererCtcfc","roleHeading":"Initializer","title":"init(frame:renderer:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:renderer:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","url":"\/documentation\/millicastsdk\/mcvideoframe","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference","isActive":true},{"text":" for playback.","type":"text"}],"role":"symbol","title":"MCVideoFrame","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/init(frame:renderer:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:renderer:)","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:renderer:)","role":"symbol","title":"init(frame:renderer:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Initializes the view with the given frame.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"role":"symbol","title":"MCCMSampleBufferVideoRenderer","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","abstract":[{"text":"This class is responsible for converting ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"text":"  into renderable ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"text":" frames.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack":{"title":"MCVideoTrack","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","url":"\/documentation\/millicastsdk\/mcvideotrack","navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoTrack","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","type":"topic","kind":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"title":"MCSampleBufferVideoUIView","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","title":"MCWebrtcRemoteVideoTrack","role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"MCVideoFrame","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"value":"MCCMSampleBufferVideoRenderer","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title"},{"value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments"},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"value":[{"text":"MCVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/fragments"},{"value":"MCSampleBufferVideoUIView","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"},{"value":"MCWebrtcRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments"},{"value":"MCRTSRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","op":"replace","value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}