{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"},"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"MCCMSampleBufferVideoRendererDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didChange(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didReceive(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/didReceive(_:)":{"type":"topic","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didreceive(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didReceiveSampleBuffer:"}],"abstract":[],"title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didReceive(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/didChange(_:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didChange(_:)","abstract":[],"title":"didChange(_:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didchange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didChangeSize:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","type":"topic","kind":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"title":"MCSampleBufferVideoUIView","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didChange(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didReceive(_:)"],"generated":true}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"didReceiveSampleBuffer:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didReceive(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveSampleBuffer:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didReceive(_:)\/fragments"},{"op":"replace","value":"didChangeSize:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didChange(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didChangeSize:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didChange(_:)\/fragments"},{"op":"replace","value":"MCSampleBufferVideoUIView","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}