{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreateOffer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreateoffer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreateoffer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreateOffer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Can not create PeerConnection offer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreateOffer"}],"title":"MCGenericError.Code.peerConnectionCreateOffer","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCGenericError@MCGenericErrorPeerConnectionCreateOffer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"role":"symbol","title":"MCGenericError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionCreateOffer":{"role":"symbol","title":"MCGenericError.Code.peerConnectionCreateOffer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreateOffer"}],"abstract":[{"type":"text","text":"Can not create PeerConnection offer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreateOffer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreateoffer"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct":{"role":"symbol","title":"MCGenericError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCGenericError"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCGenericError"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCGenericErrorPeerConnectionCreateOffer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","value":"MCGenericError"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCGenericError"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreateOffer\/title","value":"MCGenericErrorPeerConnectionCreateOffer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreateOffer\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}