{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/sourceId"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/sourceid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/sourceid"]}],"metadata":{"externalID":"c:objc(cs)MCClientOptions(py)sourceId","roleHeading":"Instance Property","title":"sourceId","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"sourceId","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"The ID of the source to publish. This option is related to the multisource feature of the millicast service. For more information refer to ","type":"text"},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting","isActive":true,"type":"reference"},{"text":". This is a publisher only option.","type":"text"}],"sections":[],"references":{"https://docs.dolby.io/streaming-apis/docs/multi-source-broadcasting":{"url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting","type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting","title":"The Multisource Broadcasting Guide","titleInlineContent":[{"text":"The Multisource Broadcasting Guide","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions","url":"\/documentation\/millicastsdk\/mcclientoptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"title":"MCClientOptions","kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/sourceId":{"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions\/sourceid","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/sourceId","title":"sourceId","abstract":[{"text":"The ID of the source to publish. This option is related to the multisource feature of the millicast service. For more information refer to ","type":"text"},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting","isActive":true,"type":"reference"},{"text":". This is a publisher only option.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceId"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sourceId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"sourceId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCClientOptions","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"op":"replace","value":[{"text":"MCClientOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments"},{"op":"replace","value":"sourceId","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1sourceId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"sourceId"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1sourceId\/fragments"}]}]}