{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionLocalDesc","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionLocalDesc","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Can not set PeerConnection local description.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionlocaldesc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionlocaldesc"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","title":"MCGenericError.Code.peerConnectionLocalDesc","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"peerConnectionLocalDesc","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MCGenericError@MCGenericErrorPeerConnectionLocalDesc","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCGenericErrorPeerConnectionLocalDesc","kind":"identifier"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionLocalDesc":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionLocalDesc","title":"MCGenericError.Code.peerConnectionLocalDesc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Can not set PeerConnection local description."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionlocaldesc","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionLocalDesc"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peerConnectionLocalDesc"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","title":"MCGenericError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCGenericErrorPeerConnectionLocalDesc"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCGenericErrorPeerConnectionLocalDesc","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionLocalDesc"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionLocalDesc\/title","value":"MCGenericErrorPeerConnectionLocalDesc","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionLocalDesc\/fragments","value":[{"text":"MCGenericErrorPeerConnectionLocalDesc","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","op":"replace","value":"MCGenericError"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MCGenericError","kind":"identifier"}]}]}]}