{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLayers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData","text":"MCLayerData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"inactiveLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"mid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mid associated to the track."}]}]},{"name":"activeLayers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Active simulcast\/SVC layers"}]}]},{"name":"inactiveLayers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"inactive simulcast\/SVC layers"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onlayers(_:activelayers:inactivelayers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onlayers(_:activelayers:inactivelayers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onLayers(_:activeLayers:inactiveLayers:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when simulcast\/svc layers are available"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}],"role":"symbol","title":"onLayers(_:activeLayers:inactiveLayers:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLayers"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"inactiveLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:objc(pl)MCSubscriberDelegate(im)onLayers:activeLayers:inactiveLayers:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onLayers(_:activeLayers:inactiveLayers:)":{"navigatorTitle":[{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}],"role":"symbol","title":"onLayers(_:activeLayers:inactiveLayers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLayers"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"inactiveLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when simulcast\/svc layers are available"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onLayers(_:activeLayers:inactiveLayers:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onlayers(_:activelayers:inactivelayers:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData":{"role":"symbol","title":"MCLayerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}],"url":"\/documentation\/millicastsdk\/mclayerdata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onLayers:activeLayers:inactiveLayers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onLayers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mid"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeLayers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MCLayerData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"activeLayers"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactiveLayers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inactiveLayers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onLayers(_:activeLayers:inactiveLayers:)\/title","value":"onLayers:activeLayers:inactiveLayers:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onLayers(_:activeLayers:inactiveLayers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/title","value":"MCLayerData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}