{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource\/change(_:_:)"},"metadata":{"externalID":"c:objc(cs)MCVideoSource(im)changeVideoSource::","navigatorTitle":[{"kind":"identifier","text":"changeVideoSource::"}],"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"change"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!)"}],"title":"change(_:_:)","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosource\/change(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosource\/change(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ascending"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"deviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ascending","content":[{"type":"paragraph","inlineContent":[{"text":"The direction in which to switch the sources.","type":"text"}]}]},{"name":"deviceId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device ID."}]}]}]}],"abstract":[{"type":"text","text":"Changes the current video source to a new source based on the provided device ID, for example"},{"type":"text","text":" "},{"type":"text","text":"if there is an external camera connected and a device ID is known."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource/change(_:_:)":{"title":"change(_:_:)","role":"symbol","abstract":[{"text":"Changes the current video source to a new source based on the provided device ID, for example","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if there is an external camera connected and a device ID is known."}],"navigatorTitle":[{"text":"changeVideoSource::","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideosource\/change(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"change","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource\/change(_:_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource":{"url":"\/documentation\/millicastsdk\/mcvideosource","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoSource"}],"type":"topic","title":"MCVideoSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Responsible for managing video sources."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"changeVideoSource::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"changeVideoSource::"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"changeVideoSource:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"ascending"},{"kind":"text","text":" "},{"text":":","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"deviceId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource~1change(_:_:)\/title","value":"changeVideoSource::","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource~1change(_:_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"changeVideoSource::","kind":"identifier"}]},{"op":"replace","value":"MCVideoSource","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/fragments","value":[{"kind":"identifier","text":"MCVideoSource"}]}]}]}