{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/accountid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/accountid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/accountId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Your Millicast account ID."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"accountId","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCSubscriberCredentials(py)accountId","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"accountId"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials/accountId":{"role":"symbol","title":"accountId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Your Millicast account ID."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/accountId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accountId"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/accountid"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"role":"symbol","title":"MCSubscriberCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberCredentials"}],"abstract":[{"type":"text","text":"The Credentials interface represent the credentials required for"},{"type":"text","text":" "},{"type":"text","text":"connecting and subscribing to a Millicast stream. See the "},{"type":"reference","isActive":true,"identifier":"https:\/\/dash.millicast.com\/docs.html"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberCredentials"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials"},"https://dash.millicast.com/docs.html":{"title":"Streaming Dashboard","titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"type":"link","identifier":"https:\/\/dash.millicast.com\/docs.html","url":"https:\/\/dash.millicast.com\/docs.html"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accountId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1accountId\/title","value":"accountId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1accountId\/fragments","value":[{"kind":"identifier","text":"accountId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","value":[{"kind":"identifier","text":"MCSubscriberCredentials"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}