{"abstract":[{"type":"text","text":"The number of frames dropped during playback or processing. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/frames_dropped"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/frames_dropped"]}],"metadata":{"externalID":"c:objc(cs)MCReceivedRtpStreamStats(py)frames_dropped","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_dropped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"frames_dropped"}],"role":"symbol","symbolKind":"property","title":"frames_dropped"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/frames_dropped"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames_dropped","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"]]},"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesdropped":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped","type":"link","title":"framesDropped","titleInlineContent":[{"type":"text","text":"framesDropped"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCReceivedRtpStreamStats/frames_dropped":{"title":"frames_dropped","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_dropped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/frames_dropped","abstract":[{"text":"The number of frames dropped during playback or processing. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdropped"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/frames_dropped","navigatorTitle":[{"kind":"identifier","text":"frames_dropped"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","kind":"symbol","title":"MCReceivedRtpStreamStats","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"navigatorTitle":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"frames_dropped"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"frames_dropped","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:k","text":"unsigned long long","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"frames_dropped","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1frames_dropped\/title","value":"frames_dropped"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1frames_dropped\/fragments","value":[{"text":"frames_dropped","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","value":"MCReceivedRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/navigatorTitle","value":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}