{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_TRACK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/audio_track"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/audio_track"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/AUDIO_TRACK","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_TRACK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"title":"AUDIO_TRACK","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@E@MCStatsType@AUDIO_TRACK","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AUDIO_TRACK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"abstract":[{"type":"text","text":"Different types of statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"url":"\/documentation\/millicastsdk\/mcstatstype"},"doc://MillicastSDK/documentation/MillicastSDK/AUDIO_TRACK":{"role":"symbol","title":"AUDIO_TRACK","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUDIO_TRACK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/AUDIO_TRACK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AUDIO_TRACK"}],"url":"\/documentation\/millicastsdk\/audio_track"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AUDIO_TRACK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AUDIO_TRACK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AUDIO_TRACK"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"kind":"identifier","text":"MCStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1AUDIO_TRACK\/title","value":"AUDIO_TRACK"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1AUDIO_TRACK\/fragments","value":[{"kind":"identifier","text":"AUDIO_TRACK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}