{"abstract":[{"text":"No credentials are set.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/noCredentials"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"kind":"symbol","metadata":{"title":"MCGenericError.Code.noCredentials","externalID":"c:@E@MCGenericError@MCGenericErrorNoCredentials","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noCredentials","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"MCGenericErrorNoCredentials","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"MillicastSDK"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/nocredentials"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/nocredentials"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/noCredentials":{"kind":"symbol","role":"symbol","title":"MCGenericError.Code.noCredentials","type":"topic","abstract":[{"type":"text","text":"No credentials are set."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noCredentials"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/nocredentials","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorNoCredentials"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/noCredentials"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","title":"MCGenericError.Code","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCGenericErrorNoCredentials"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorNoCredentials"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCGenericErrorNoCredentials","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1noCredentials\/title","op":"replace","value":"MCGenericErrorNoCredentials"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1noCredentials\/fragments","op":"replace","value":[{"text":"MCGenericErrorNoCredentials","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","op":"replace","value":"MCGenericError"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericError"}]}]}]}