{"metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCGenericError@MCGenericErrorPeerConnectionNotEstablished","roleHeading":"Case","navigatorTitle":[{"text":"MCGenericErrorPeerConnectionNotEstablished","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionNotEstablished","kind":"identifier"}],"title":"MCGenericError.Code.peerConnectionNotEstablished"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionNotEstablished","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionNotEstablished"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionnotestablished"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionnotestablished"]}],"kind":"symbol","abstract":[{"text":"PeerConnection was not established.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionNotEstablished":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionNotEstablished","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionnotestablished","abstract":[{"type":"text","text":"PeerConnection was not established."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionNotEstablished","title":"MCGenericError.Code.peerConnectionNotEstablished","role":"symbol","navigatorTitle":[{"text":"MCGenericErrorPeerConnectionNotEstablished","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","title":"MCGenericError.Code","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCGenericErrorPeerConnectionNotEstablished","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCGenericErrorPeerConnectionNotEstablished","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MCGenericErrorPeerConnectionNotEstablished","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCGenericErrorPeerConnectionNotEstablished","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionNotEstablished\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionNotEstablished"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionNotEstablished\/fragments"},{"op":"replace","value":"MCGenericError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"op":"replace","value":[{"text":"MCGenericError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments"}]}]}