{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Websocket not connected.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorWebsocketHasFailed"}],"externalID":"c:@E@MCGenericError@MCGenericErrorWebsocketHasFailed","roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketHasFailed"}],"role":"symbol","title":"MCGenericError.Code.websocketHasFailed"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/websocketHasFailed","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/websockethasfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/websockethasfailed"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketHasFailed","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","title":"MCGenericError.Code","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/websocketHasFailed":{"abstract":[{"text":"Websocket not connected.","type":"text"}],"title":"MCGenericError.Code.websocketHasFailed","type":"topic","navigatorTitle":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/websockethasfailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketHasFailed","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/websocketHasFailed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCGenericErrorWebsocketHasFailed","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCGenericError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"op":"replace","value":[{"text":"MCGenericError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments"},{"value":"MCGenericErrorWebsocketHasFailed","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1websocketHasFailed\/title","op":"replace"},{"value":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1websocketHasFailed\/fragments","op":"replace"}]}]}