{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onPixelBuffer"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pixelBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ACVPixelBufferRef reference. The reference will be retained\/decremented internally."}],"type":"paragraph"}],"name":"pixelBuffer"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onPixelBuffer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"onPixelBuffer:"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)MCCoreVideoSource(im)onPixelBuffer:","title":"onPixelBuffer(_:)","symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source."},{"text":" ","type":"text"},{"text":"This API does not copy the CVPixelBuffer if using H.264, which is hardware accelerated on Apple platforms.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If using codecs other than H.264, an internal copy of the frame will occur."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/onPixelBuffer(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onPixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"onPixelBuffer:"}],"role":"symbol","abstract":[{"type":"text","text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source."},{"type":"text","text":" "},{"type":"text","text":"This API does not copy the CVPixelBuffer if using H.264, which is hardware accelerated on Apple platforms."},{"text":" ","type":"text"},{"text":"If using codecs other than H.264, an internal copy of the frame will occur.","type":"text"}],"kind":"symbol","type":"topic","title":"onPixelBuffer(_:)","url":"\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mccorevideosource","title":"MCCoreVideoSource","navigatorTitle":[{"text":"MCCoreVideoSource","kind":"identifier"}],"abstract":[{"text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCoreVideoSource"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onPixelBuffer:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onPixelBuffer:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onPixelBuffer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"__CVBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pixelBuffer"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:)\/title","value":"onPixelBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onPixelBuffer:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title","value":"MCCoreVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}