{"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"]]},"abstract":[{"text":"Sets the type of media source to be created, either video or audio.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MCSourceBuilder(im)setType:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCSourceType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setType:","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"setType(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setType","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSourceType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","preciseIdentifier":"c:@E@MCSourceType"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The type of the source you are building."}],"type":"paragraph"}]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setType(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/settype(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/settype(_:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsourcetype","title":"MCSourceType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSourceType"}],"kind":"symbol","abstract":[{"type":"text","text":"The Source type"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setType(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setType","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCSourceType","preciseIdentifier":"c:@E@MCSourceType"},{"kind":"text","text":")"}],"title":"setType(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setType:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setType(_:)","url":"\/documentation\/millicastsdk\/mcsourcebuilder\/settype(_:)","type":"topic","abstract":[{"type":"text","text":"Sets the type of media source to be created, either video or audio."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceBuilder"}],"title":"MCSourceBuilder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","url":"\/documentation\/millicastsdk\/mcsourcebuilder","type":"topic","abstract":[{"type":"text","text":"Responsible for building a source object."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"setType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setType:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCSourceType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","preciseIdentifier":"c:@E@MCSourceType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType"},{"op":"replace","value":[{"text":"MCSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setType(_:)\/title","op":"replace","value":"setType:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setType:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setType(_:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title","op":"replace","value":"MCSourceBuilder"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments","value":[{"text":"MCSourceBuilder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}