{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCIceCandidatePairStats(py)total_round_trip_time","role":"symbol","title":"total_round_trip_time","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"total_round_trip_time","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"total_round_trip_time"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/total_round_trip_time"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/total_round_trip_time"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/total_round_trip_time","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats"]]},"abstract":[{"type":"text","text":"Represents the sum of all round trip time measurements in seconds since the beginning of the session. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/total_round_trip_time":{"type":"topic","title":"total_round_trip_time","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/total_round_trip_time","navigatorTitle":[{"kind":"identifier","text":"total_round_trip_time"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/total_round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Represents the sum of all round trip time measurements in seconds since the beginning of the session. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime","isActive":true}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats":{"navigatorTitle":[{"kind":"identifier","text":"MCIceCandidatePairStats"}],"role":"symbol","title":"MCIceCandidatePairStats","abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCIceCandidatePairStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcicecandidatepairstats"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-totalroundtriptime":{"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime","titleInlineContent":[{"type":"text","text":"totalroundtriptime"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime","title":"totalroundtriptime"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"total_round_trip_time","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"total_round_trip_time"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"total_round_trip_time","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1total_round_trip_time\/title","op":"replace"},{"value":[{"text":"total_round_trip_time","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1total_round_trip_time\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title","value":"MCIceCandidatePairStats","op":"replace"},{"value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments","op":"replace"}]}]}