{"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives connection state changes for the websocket connection."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"websocketState","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A new async stream reporting websocket connection state changes.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/websocketstate()"]}],"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/websocketState()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketState"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","kind":"typeIdentifier"},{"kind":"text","text":">"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"extendedModule":"MillicastSDK","role":"symbol","externalID":"s:So11MCPublisherC12MillicastSDKE14websocketStateScSySo012MCConnectionE0VGyF","title":"websocketState()"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCConnectionState"}],"navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"type":"topic","title":"MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","role":"symbol","kind":"symbol","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/websocketState()":{"title":"websocketState()","url":"\/documentation\/millicastsdk\/mcpublisher\/websocketstate()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives connection state changes for the websocket connection."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketState","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"kind":"text","text":"<"},{"text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState","kind":"typeIdentifier"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/websocketState()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","value":[{"kind":"identifier","text":"MCPublisher"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title","value":"MCConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments","value":[{"text":"MCConnectionState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}