{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error category for errors triggered when the operation failed because"},{"type":"text","text":" "},{"type":"text","text":"it was abandoned for various reasons."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"MCAsyncOperationCancelledError.Code","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@MCAsyncOperationCancelledError","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/abandoned","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/aborted","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/actorShutdown","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/multipleResolve","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/timeout"]},{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/abandoned":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code.abandoned","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"abandoned"}],"abstract":[{"type":"text","text":"Operation was cancelled for unspecified reasons."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/abandoned","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAbandoned"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/abandoned"},"doc://MillicastSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/MillicastSDK\/SY"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/actorShutdown":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code.actorShutdown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"actorShutdown"}],"abstract":[{"type":"text","text":"Operation was cancelled because shutdown or disconnection in progress."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/actorShutdown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorActorShutdown"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/actorshutdown"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/timeout":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code.timeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"abstract":[{"type":"text","text":"Operation was cancelled due to a timeout."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/timeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorTimeout"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/timeout"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/aborted":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code.aborted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aborted"}],"abstract":[{"type":"text","text":"Operation was cancelled because a newer request made it"},{"type":"text","text":" "},{"type":"text","text":"obsolete."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/aborted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAborted"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/aborted"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct":{"role":"symbol","title":"MCAsyncOperationCancelledError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/rawrepresentable-implementations"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error category for errors triggered when the operation failed because"},{"type":"text","text":" "},{"type":"text","text":"it was abandoned for various reasons."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/equatable-implementations"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MillicastSDK\/s8SendableP"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/init(rawvalue:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/multipleResolve":{"role":"symbol","title":"MCAsyncOperationCancelledError.Code.multipleResolve","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleResolve"}],"abstract":[{"type":"text","text":"Internal SDK logic error."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/multipleResolve","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorMultipleResolve"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/multipleresolve"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MCAsyncOperationCancelledError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/abandoned","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/aborted","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/actorShutdown","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/multipleResolve","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/timeout"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAsyncOperationCancelledError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1abandoned\/title","value":"MCAsyncOperationCancelledErrorAbandoned"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1abandoned\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAbandoned"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1actorShutdown\/title","value":"MCAsyncOperationCancelledErrorActorShutdown"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1actorShutdown\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorActorShutdown"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1timeout\/title","value":"MCAsyncOperationCancelledErrorTimeout"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1timeout\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1aborted\/title","value":"MCAsyncOperationCancelledErrorAborted"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1aborted\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAborted"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title","value":"MCAsyncOperationCancelledError"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1multipleResolve\/title","value":"MCAsyncOperationCancelledErrorMultipleResolve"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1multipleResolve\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorMultipleResolve"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}