{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer\/setName(_:)"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}]}]},{"parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"text":"The name that will be displayed to other NDI applications","type":"text"},{"text":" ","type":"text"},{"text":"when they search for NDI sources.","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Sets the name of the NDI source."}],"sections":[],"metadata":{"externalID":"c:objc(cs)MCNdiRenderer(im)setName:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setName:"}],"role":"symbol","roleHeading":"Instance Method","title":"setName(_:)","modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcndirenderer\/setname(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcndirenderer\/setname(_:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayback":{"navigatorTitle":[{"text":"MCAudioPlayback","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"text":" ","type":"text"},{"text":"This class inherits the Source class, however this is not","type":"text"},{"text":" ","type":"text"},{"text":"a capture source.","type":"text"}],"type":"topic","title":"MCAudioPlayback","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayback","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback","url":"\/documentation\/millicastsdk\/mcaudioplayback"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCNdiRenderer/setName(_:)":{"type":"topic","title":"setName(_:)","role":"symbol","abstract":[{"type":"text","text":"Sets the name of the NDI source."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer\/setName(_:)","url":"\/documentation\/millicastsdk\/mcndirenderer\/setname(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"setName:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCNdiRenderer":{"kind":"symbol","navigatorTitle":[{"text":"MCNdiRenderer","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The  class is responsible for rendering video as an NDI source. To render audio with NDI, use"},{"type":"text","text":" "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback","isActive":true,"type":"reference"},{"type":"text","text":" with the NDI output instead."}],"url":"\/documentation\/millicastsdk\/mcndirenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer","title":"MCNdiRenderer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCNdiRenderer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer~1setName(_:)\/title","value":"setName:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer~1setName(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer\/title","value":"MCNdiRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer\/fragments","value":[{"text":"MCNdiRenderer","kind":"identifier"}]}]}]}