{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","text":"MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMid"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"track","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote audio track."}]}]},{"name":"mid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The associated transceiver mid. Can be nil if there is none."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onaudiotrack(_:withmid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/onaudiotrack(_:withmid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onAudioTrack(_:withMid:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a remote audio track has been added."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onAudioTrack:withMid:"}],"role":"symbol","title":"onAudioTrack(_:withMid:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCSubscriberDelegate(im)onAudioTrack:withMid:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack":{"role":"symbol","title":"MCAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioTrack"}],"abstract":[{"type":"text","text":"Manages and plays a single audio resource."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioTrack"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onAudioTrack(_:withMid:)":{"navigatorTitle":[{"kind":"identifier","text":"onAudioTrack:withMid:"}],"role":"symbol","title":"onAudioTrack(_:withMid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a remote audio track has been added."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onAudioTrack(_:withMid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onaudiotrack(_:withmid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onAudioTrack:withMid:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioTrack:withMid:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onAudioTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","text":"MCAudioTrack"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"track"},{"kind":"text","text":" "},{"kind":"identifier","text":"withMid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mid"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/title","value":"MCAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/fragments","value":[{"kind":"identifier","text":"MCAudioTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onAudioTrack(_:withMid:)\/title","value":"onAudioTrack:withMid:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onAudioTrack(_:withMid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioTrack:withMid:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}