{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mediaSource","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"MCStatsTypeMediaSource","kind":"identifier"}],"title":"MCStatsType.mediaSource","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCStatsType@MCStatsTypeMediaSource"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaSource"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/mediasource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/mediasource"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mediaSource","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/mediaSource":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaSource"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeMediaSource"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaSource","url":"\/documentation\/millicastsdk\/mcstatstype\/mediasource","title":"MCStatsType.mediaSource","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Different types of statistics."}],"navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"title":"MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"MCStatsTypeMediaSource","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCStatsTypeMediaSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MCStatsTypeMediaSource","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaSource\/title","value":"MCStatsTypeMediaSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaSource\/fragments","value":[{"kind":"identifier","text":"MCStatsTypeMediaSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}