{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate","text":"MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/removedelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/removedelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/removeDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the delegate from the list of delegates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":")"}],"title":"removeDelegate(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCCMSampleBufferVideoRenderer(im)removeDelegate:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"role":"symbol","title":"MCCMSampleBufferVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"abstract":[{"type":"text","text":"Delegate for  receiving raw video "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" ready for rendering"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/removeDelegate(_:)":{"role":"symbol","title":"removeDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the delegate from the list of delegates."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/removeDelegate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/removedelegate(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"role":"symbol","title":"MCVideoFrame","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},{"type":"text","text":" for playback."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}],"url":"\/documentation\/millicastsdk\/mcvideoframe"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"role":"symbol","title":"MCCMSampleBufferVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"abstract":[{"type":"text","text":"This class is responsible for converting "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"},{"type":"text","text":"  into renderable "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" frames."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MCCMSampleBufferVideoRendererDelegate>","preciseIdentifier":"c:Qoobjc(pl)MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","value":"MCCMSampleBufferVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1removeDelegate(_:)\/title","value":"removeDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1removeDelegate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}