{"abstract":[{"text":"Whether these stastics are for the encoder or the decoder.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codec_type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCCodecStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCCodecStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats\/codec_type","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/codec_type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/codec_type"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codec_type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCCodecStatsType","text":"MCCodecStatsType","kind":"typeIdentifier"}],"title":"codec_type","symbolKind":"property","navigatorTitle":[{"text":"codec_type","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCCodecsStats(py)codec_type"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecsStats":{"navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats","url":"\/documentation\/millicastsdk\/mccodecsstats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"kind":"symbol","title":"MCCodecsStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecsStats/codec_type":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/codec_type","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats\/codec_type","role":"symbol","title":"codec_type","abstract":[{"text":"Whether these stastics are for the encoder or the decoder.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec_type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCCodecStatsType","preciseIdentifier":"c:@E@MCCodecStatsType"}],"navigatorTitle":[{"kind":"identifier","text":"codec_type"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType":{"type":"topic","abstract":[{"type":"text","text":"Different types of codec statistics."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecStatsType"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType","navigatorTitle":[{"text":"MCCodecStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype","role":"symbol","title":"MCCodecStatsType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"codec_type","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"codec_type"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MCCodecStatsType","preciseIdentifier":"c:@E@MCCodecStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec_type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCCodecsStats","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats\/title"},{"value":[{"text":"MCCodecsStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats\/fragments"},{"value":"codec_type","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats~1codec_type\/title"},{"value":[{"text":"codec_type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats~1codec_type\/fragments"},{"value":"MCCodecStatsType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType\/title"},{"value":[{"text":"MCCodecStatsType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType\/fragments"}]}]}