{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True to enable color range expansion. Disabled by default."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/init(colorrangeexpansion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/init(colorrangeexpansion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes with the option of expanding limited color range to the full range upon rendering."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(colorRangeExpansion:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MCIosVideoRenderer(im)initWithColorRangeExpansion:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithColorRangeExpansion:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer":{"role":"symbol","title":"MCIosVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/init(colorRangeExpansion:)":{"role":"symbol","title":"init(colorRangeExpansion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes with the option of expanding limited color range to the full range upon rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithColorRangeExpansion:"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/init(colorrangeexpansion:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithColorRangeExpansion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithColorRangeExpansion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithColorRangeExpansion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"enable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(colorRangeExpansion:)\/title","value":"initWithColorRangeExpansion:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(colorRangeExpansion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithColorRangeExpansion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}