{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(pl)MCWebrtcRemoteTrackDelegate(im)webrtcRemoteTrack:didUpdateMID:","roleHeading":"Instance Method","title":"webrtcRemoteTrack(_:didUpdateMID:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webrtcRemoteTrack"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateMID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"webrtcRemoteTrack:didUpdateMID:"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The event for updating the MID of the internal webrtc track."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webrtcRemoteTrack"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},{"text":", ","kind":"text"},{"text":"didUpdateMID","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mid"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The MID can be updated many times during the WebrtcRemoteTrack’s life. When"},{"type":"text","text":" "},{"text":"the track is being first enabled, the MID is set, and when the peer","type":"text"},{"type":"text","text":" "},{"text":"connection disconnects, the MID is reset to empty value. After reconnection","type":"text"},{"type":"text","text":" "},{"text":"or migration the MID may be set again, possibly to a different value.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The MID value should only be used by the application when interpreting the"},{"text":" ","type":"text"},{"type":"text","text":"webrtc stats, the exact MID value at any time is not needed for any other"},{"text":" ","type":"text"},{"text":"functionality.","type":"text"}]},{"inlineContent":[{"type":"text","text":"All tracks after their creation, before attempting to enable them, have"},{"type":"text","text":" "},{"type":"text","text":"empty MID."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrack(_:didUpdateMID:)":{"kind":"symbol","navigatorTitle":[{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"title":"webrtcRemoteTrack(_:didUpdateMID:)","abstract":[{"text":"The event for updating the MID of the internal webrtc track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webrtcRemoteTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateMID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteTrackDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrackDelegate","kind":"identifier"}],"title":"MCWebrtcRemoteTrackDelegate","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate","role":"symbol","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"webrtcRemoteTrack:didUpdateMID:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"webrtcRemoteTrack:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},{"text":" *) ","kind":"text"},{"text":"webrtcRemoteTrack","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didUpdateMID:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"mid","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/title","op":"replace","value":"webrtcRemoteTrack:didUpdateMID:"},{"value":[{"kind":"text","text":"- "},{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace","value":"MCWebrtcRemoteTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/title","op":"replace","value":"MCWebrtcRemoteTrackDelegate"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}