{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/delegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/delegate"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"delegate","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCRTSRemoteTrackDelegate","text":"MCRTSRemoteTrackDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","externalID":"c:objc(cs)MCRTSRemoteTrack(py)delegate"},"abstract":[{"text":"Delegate to receive track related events.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","preciseIdentifier":"c:objc(pl)MCRTSRemoteTrackDelegate","kind":"typeIdentifier","text":"MCRTSRemoteTrackDelegate"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/delegate":{"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/delegate","role":"symbol","title":"delegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/delegate","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MCRTSRemoteTrackDelegate","text":"MCRTSRemoteTrackDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"abstract":[{"text":"Delegate to receive track related events.","type":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"type":"topic","navigatorTitle":[{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"kind":"symbol","title":"MCRTSRemoteTrackDelegate","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"type":"topic","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"type":"text","text":" "},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","title":"MCRTSRemoteTrack","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"text":"id<MCRTSRemoteTrackDelegate>","preciseIdentifier":"c:Qoobjc(pl)MCRTSRemoteTrackDelegate","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1delegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"value":"MCRTSRemoteTrackDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}]},{"op":"replace","value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"op":"replace","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}