{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layersPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","text":"MCRTSRemoteTrackLayers"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"an AnyPublisher to receive track layer updates","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/layerspublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE15layersPublisher7Combine03AnyF0VySo0aB6LayersCs5NeverOGyF","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","title":"layersPublisher()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layersPublisher","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"extendedModule":"MillicastSDK","symbolKind":"method"},"abstract":[{"type":"text","text":"Get a Combine based layers publisher."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layersPublisher()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"type":"topic","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"type":"text","text":" "},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","title":"MCRTSRemoteTrack","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/layersPublisher()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layersPublisher()","abstract":[{"type":"text","text":"Get a Combine based layers publisher."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layersPublisher","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"title":"layersPublisher()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/layerspublisher()","role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","abstract":[{"type":"text","text":"The layers update event. Note that if the RtsTrack is projected"},{"type":"text","text":" "},{"type":"text","text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,"},{"type":"text","text":" "},{"text":"so the RTS track will get multiple layer events.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"No debouncing\/deduplication is implemented."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers","title":"MCRTSRemoteTrackLayers","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}]},{"op":"replace","value":"MCRTSRemoteTrackLayers","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}