{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Code"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"MCInternalSDKError.Code","externalID":"c:@E@MCInternalSDKError","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Error category for unidentified errors. Usually representing a bug."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/unkown"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/s15BitwiseCopyableP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"],"type":"conformsTo"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInternalSDKError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCInternalSDKError","kind":"identifier"}],"abstract":[],"title":"MCInternalSDKError","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error category for unidentified errors. Usually representing a bug."}],"title":"MCInternalSDKError.Code","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/s15BitwiseCopyableP":{"type":"unresolvable","title":"Swift.BitwiseCopyable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s15BitwiseCopyableP"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/unkown":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/unkown","abstract":[{"type":"text","text":"Uknown error."}],"kind":"symbol","title":"MCInternalSDKError.Code.unkown","type":"topic","navigatorTitle":[{"text":"MCInternalSDKErrorUnkown","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/unkown"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/init(rawValue:)":{"type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/Equatable-Implementations":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/Equatable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"Equatable Implementations","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/equatable-implementations","kind":"article"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/RawRepresentable-Implementations":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/rawrepresentable-implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MCInternalSDKError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKError"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCInternalSDKError","kind":"identifier"}],"op":"replace"},{"path":"\/hierarchy","value":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/unkown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInternalSDKError","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/title","value":"MCInternalSDKError","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKError"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MCInternalSDKError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code~1unkown\/title","value":"MCInternalSDKErrorUnkown","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code~1unkown\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKErrorUnkown"}],"op":"replace"}]}]}