{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/canhandlemoreframes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/canhandlemoreframes()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/canHandleMoreFrames()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MCCMSampleBufferVideoRendererDelegate.canHandleMoreFrames()"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"canHandleMoreFrames"}],"role":"symbol","title":"canHandleMoreFrames()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@CM@MillicastSDK@objc(cs)MCSampleBufferVideoUIView(im)canHandleMoreFrames","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/MCCMSampleBufferVideoRendererDelegate-Implementations":{"role":"collectionGroup","title":"MCCMSampleBufferVideoRendererDelegate Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/canHandleMoreFrames()":{"role":"symbol","title":"canHandleMoreFrames()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/canHandleMoreFrames()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canHandleMoreFrames"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/canhandlemoreframes()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"role":"symbol","title":"MCSampleBufferVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canHandleMoreFrames"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canHandleMoreFrames"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1canHandleMoreFrames()\/title","value":"canHandleMoreFrames"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1canHandleMoreFrames()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canHandleMoreFrames"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}