{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"internalParam","text":"frameRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"frameRect","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A rectangle representing the frame."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@MillicastSDK@objc(cs)MCSampleBufferVideoUIView(im)initWithFrame:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"role":"symbol","title":"MCSampleBufferVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"frameRect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}