{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","preciseIdentifier":"c:objc(cs)MCCoreVideoSource","text":"MCCoreVideoSource"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new core video source."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccorevideosourcebuilder\/build()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccorevideosourcebuilder\/build()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder\/build()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Builds the CoreVideoSource class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCCoreVideoSource","preciseIdentifier":"c:objc(cs)MCCoreVideoSource"},{"kind":"text","text":"!"}],"title":"build()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCCoreVideoSourceBuilder(im)build","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"build"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"role":"symbol","title":"MCCoreVideoSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSource"}],"url":"\/documentation\/millicastsdk\/mccorevideosource"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSourceBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCCoreVideoSource","preciseIdentifier":"c:objc(cs)MCCoreVideoSource"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Builds the CoreVideoSource class."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/millicastsdk\/mccorevideosourcebuilder\/build()"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSourceBuilder":{"role":"symbol","title":"MCCoreVideoSourceBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"abstract":[{"type":"text","text":"Responsible for building a CoreVideoSource."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"url":"\/documentation\/millicastsdk\/mccorevideosourcebuilder"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"build"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","preciseIdentifier":"c:objc(cs)MCCoreVideoSource","text":"MCCoreVideoSource"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title","value":"MCCoreVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/title","value":"MCCoreVideoSourceBuilder"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}