{"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@E@MCVideoType@MCVideoTypeYV12","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"yv12","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoTypeYV12","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCVideoType.yv12"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/yv12","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"yv12","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideotype\/yv12"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/yv12"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType/yv12":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/yv12","url":"\/documentation\/millicastsdk\/mcvideotype\/yv12","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"yv12","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeYV12"}],"title":"MCVideoType.yv12"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"role":"symbol","type":"topic","title":"MCVideoType","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MCVideoTypeYV12","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCVideoTypeYV12","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MCVideoTypeYV12","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1yv12\/title","value":"MCVideoTypeYV12"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1yv12\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoTypeYV12"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoType"}]}]}]}