{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoSources"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource","text":"MCVideoSource"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of all available "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcmedia\/getvideosources()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcmedia\/getvideosources()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getVideoSources()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Query all available video sources."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoSources"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"kind":"text","text":"]!"}],"title":"getVideoSources()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCMedia(cm)getVideoSources","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getVideoSources"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getVideoSources()":{"role":"symbol","title":"getVideoSources()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVideoSources"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Query all available video sources."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getVideoSources()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getVideoSources"}],"url":"\/documentation\/millicastsdk\/mcmedia\/getvideosources()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource":{"role":"symbol","title":"MCVideoSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSource"}],"abstract":[{"type":"text","text":"Responsible for managing video sources."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoSource"}],"url":"\/documentation\/millicastsdk\/mcvideosource"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"role":"symbol","title":"MCMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMedia"}],"abstract":[{"type":"text","text":"Class  used  for managing media sources."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCMedia"}],"url":"\/documentation\/millicastsdk\/mcmedia"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getVideoSources"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getVideoSources"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<MCVideoSource *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getVideoSources"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getVideoSources()\/title","value":"getVideoSources"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getVideoSources()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getVideoSources"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/title","value":"MCVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/fragments","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title","value":"MCMedia"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments","value":[{"kind":"identifier","text":"MCMedia"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}