{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requeststop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requeststop()"]}],"abstract":[{"type":"text","text":"Request the AVAudioPlayerNode to stop playback and receiving audio."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestStop()"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestStop"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"The playback will have stopped when ","type":"text"},{"code":"audioPlayerNodeDidStopPlaying:","type":"codeVoice"},{"text":" is invoked.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"required":true,"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestStop"},{"kind":"text","text":"()"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestStop"}],"title":"requestStop()","externalID":"c:objc(pl)MCAudioPlayerNodePlaybackController(im)requestStop"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController/requestStop()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestStop()","title":"requestStop()","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestStop"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestStop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Request the AVAudioPlayerNode to stop playback and receiving audio."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requeststop()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController":{"navigatorTitle":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"abstract":[{"type":"text","text":"This playback controller allows you to modify the state of the player node that is provided through the delegate."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller","title":"MCAudioPlayerNodePlaybackController","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requestStop","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestStop"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestStop"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"requestStop","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestStop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestStop"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestStop()\/fragments","op":"replace"},{"value":"MCAudioPlayerNodePlaybackController","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/title","op":"replace"},{"value":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/fragments","op":"replace"}]}]}