{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Called when an error message from Millicast in the response of a websocket command is received.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivesignalingerror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivesignalingerror:)"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDelegate"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCDelegate(im)client:didReceiveSignalingError:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"client:didReceiveSignalingError:"}],"title":"client(_:didReceiveSignalingError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"MCClient","preciseIdentifier":"c:objc(pl)MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSignalingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","required":true},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveSignalingError:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"client"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient","text":"MCClient","preciseIdentifier":"c:objc(pl)MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSignalingError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCSignalingError","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError","text":"MCSignalingError"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"text":"The Millicast client","type":"text"}]}]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"title":"MCPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisherDelegate":{"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a delegate."},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisherDelegate","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","type":"topic","title":"MCPublisherDelegate","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","kind":"symbol","type":"topic","title":"MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcdelegate","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDelegate","abstract":[{"type":"text","text":"The "},{"code":"MCDelegate","type":"codeVoice"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate","type":"reference","isActive":true},{"type":"text","text":", which are the main ones to implement."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDelegate/client(_:didReceiveSignalingError:)":{"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient","text":"MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveSignalingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSignalingError","text":"MCSignalingError"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveSignalingError:)","abstract":[{"text":"Called when an error message from Millicast in the response of a websocket command is received.","type":"text"}],"title":"client(_:didReceiveSignalingError:)","url":"\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivesignalingerror:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"client:didReceiveSignalingError:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"text":" ","type":"text"},{"text":"events.","type":"text"}],"title":"MCSubscriberDelegate","navigatorTitle":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient":{"abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCClient"}],"kind":"symbol","title":"MCClient","url":"\/documentation\/millicastsdk\/mcclient","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSignalingError":{"role":"symbol","title":"MCSignalingError","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsignalingerror","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSignalingError"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError","abstract":[{"text":"Container class for Signaling errors that occur during","type":"text"},{"text":" ","type":"text"},{"text":"signaling\/configuration of the peer connection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCSignalingError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"client:didReceiveSignalingError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveSignalingError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"client:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCClient","text":"id<MCClient>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"client"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveSignalingError:"},{"kind":"text","text":"("},{"text":"MCSignalingError","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast client"}]}],"name":"client"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/navigatorTitle","value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"text":"MCPublisherDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate\/navigatorTitle","value":[{"text":"MCPublisherDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/navigatorTitle","value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"text":"MCDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDelegate\/navigatorTitle","value":[{"text":"MCDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveSignalingError:)\/title","value":"client:didReceiveSignalingError:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveSignalingError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveSignalingError:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/title","value":"MCClient","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/fragments","value":[{"kind":"identifier","text":"MCClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/navigatorTitle","value":[{"text":"MCClient","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/title","value":"MCSignalingError","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/fragments","value":[{"text":"MCSignalingError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSignalingError\/navigatorTitle","value":[{"kind":"identifier","text":"MCSignalingError"}],"op":"replace"}]}]}