{"kind":"symbol","abstract":[{"type":"text","text":"A delegate method that will receive CMSampleBufferRef that contain raw video ready for rendering."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"buffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"buffer","content":[{"type":"paragraph","inlineContent":[{"text":"A reference to a CMSampleBuffer.","type":"text"}]}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didreceive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didReceive(_:)","interfaceLanguage":"swift"},"metadata":{"required":true,"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate(im)didReceiveSampleBuffer:","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didReceiveSampleBuffer:"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"4.0","beta":false}],"roleHeading":"Instance Method","title":"didReceive(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"abstract":[{"type":"text","text":"Delegate for  receiving raw video "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"text":" ready for rendering","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","title":"MCCMSampleBufferVideoRendererDelegate","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate/didReceive(_:)":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didReceive(_:)","required":true,"abstract":[{"type":"text","text":"A delegate method that will receive CMSampleBufferRef that contain raw video ready for rendering."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"title":"didReceive(_:)","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didreceive(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"didReceiveSampleBuffer:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveSampleBuffer:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"didReceiveSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@opaqueCMSampleBuffer","text":"opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","value":"MCCMSampleBufferVideoRendererDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didReceive(_:)\/title","op":"replace","value":"didReceiveSampleBuffer:"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didReceive(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}