{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoJitterMinimumDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/videojitterminimumdelayms"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/videojitterminimumdelayms"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/videoJitterMinimumDelayMs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The minimum video jitter buffer delay, in milliseconds. The default value is 0. For more information, refer to "},{"type":"reference","isActive":true,"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay"},{"type":"text","text":" to understand more about what this field does. This is only for subscribing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoJitterMinimumDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"videoJitterMinimumDelayMs","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCClientOptions(py)videoJitterMinimumDelayMs","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"videoJitterMinimumDelayMs"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/videoJitterMinimumDelayMs":{"role":"symbol","title":"videoJitterMinimumDelayMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoJitterMinimumDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The minimum video jitter buffer delay, in milliseconds. The default value is 0. For more information, refer to "},{"type":"reference","isActive":true,"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay"},{"type":"text","text":" to understand more about what this field does. This is only for subscribing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/videoJitterMinimumDelayMs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoJitterMinimumDelayMs"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/videojitterminimumdelayms"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/playout-delay":{"title":"this document","titleInlineContent":[{"type":"text","text":"this document"}],"type":"link","identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","url":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","title":"MCClientOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"url":"\/documentation\/millicastsdk\/mcclientoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoJitterMinimumDelayMs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoJitterMinimumDelayMs"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoJitterMinimumDelayMs"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1videoJitterMinimumDelayMs\/title","value":"videoJitterMinimumDelayMs"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1videoJitterMinimumDelayMs\/fragments","value":[{"kind":"identifier","text":"videoJitterMinimumDelayMs"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"kind":"identifier","text":"MCClientOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}