{"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCSentRtpStreamStats(cm)get_type","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"symbolKind":"method","title":"get_type()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/get_type()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/get_type()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/get_type()"},"abstract":[{"type":"text","text":"Returns the type of statistics."}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats":{"kind":"symbol","title":"MCSentRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics related to an outgoing RTP stream."}],"role":"symbol","navigatorTitle":[{"text":"MCSentRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/get_type()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/get_type()","abstract":[{"text":"Returns the type of statistics.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/get_type()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"title":"get_type()"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstatstype","abstract":[{"text":"Different types of statistics.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"get_type","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType"},{"kind":"text","text":") "},{"text":"get_type","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title","value":"MCSentRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1get_type()\/title","value":"get_type"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"text":"MCStatsType","kind":"identifier"}]}]}]}