{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel\/full"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/full","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains the full report which serializes"},{"text":" ","type":"text"},{"type":"text","text":"All the fields in provided in MCSubscriberStats"},{"type":"text","text":" "},{"text":"and MCTrackStats","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCSubscriberStatsLevelFull","kind":"identifier"}],"externalID":"c:@E@MCSubscriberStatsLevel@MCSubscriberStatsLevelFull","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"roleHeading":"Case","title":"MCSubscriberStatsLevel.full","symbolKind":"case","role":"symbol"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel":{"abstract":[{"type":"text","text":"Enum specifying the level of verbosity for stats."}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel","kind":"symbol","title":"MCSubscriberStatsLevel","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"navigatorTitle":[{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/full":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"full","kind":"identifier"}],"abstract":[{"text":"Contains the full report which serializes","type":"text"},{"text":" ","type":"text"},{"text":"All the fields in provided in MCSubscriberStats","type":"text"},{"type":"text","text":" "},{"text":"and MCTrackStats","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/full","title":"MCSubscriberStatsLevel.full","role":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/full","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevelFull"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCSubscriberStatsLevelFull","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCSubscriberStatsLevelFull","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCSubscriberStatsLevelFull","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/title","op":"replace","value":"MCSubscriberStatsLevel"},{"value":[{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1full\/title","value":"MCSubscriberStatsLevelFull","op":"replace"},{"value":[{"kind":"identifier","text":"MCSubscriberStatsLevelFull"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1full\/fragments"}]}]}