{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame\/init(sampleBuffer:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame"},"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for initializing a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"},{"text":"  from a ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"}],"metadata":{"symbolKind":"class","modules":[{"name":"MillicastSDK"}],"title":"MCCMSampleBufferFrame","role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)MCCMSampleBufferFrame","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferFrame"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebufferframe"]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebufferframe"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferFrame":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"role":"symbol","title":"MCCMSampleBufferFrame","url":"\/documentation\/millicastsdk\/mccmsamplebufferframe","navigatorTitle":[{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for initializing a "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","isActive":true},{"type":"text","text":"  from a "},{"code":"CMSampleBuffer","type":"codeVoice"}]},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onAudioFrame:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","title":"onAudioFrame(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAudioFrame"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferFrame/init(sampleBuffer:)":{"title":"init(sampleBuffer:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithSampleBuffer:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame\/init(sampleBuffer:)","abstract":[{"text":"Initialize with a ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"}],"url":"\/documentation\/millicastsdk\/mccmsamplebufferframe\/init(samplebuffer:)","fragments":[{"kind":"identifier","text":"init"},{"text":"!(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"text":"!)","kind":"text"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame":{"navigatorTitle":[{"kind":"identifier","text":"MCAudioFrame"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","title":"MCAudioFrame","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioFrame"}],"abstract":[{"text":"Audio frame that contains audio data. Used with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","type":"reference"},{"type":"text","text":" "},{"text":"to feed custom audio frames into source used by a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioframe"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MCCMSampleBufferFrame","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame\/init(sampleBuffer:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferFrame"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","text":"MCAudioFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioFrame"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/title","value":"MCCMSampleBufferFrame"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/fragments","value":[{"text":"MCCMSampleBufferFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","value":"onAudioFrame:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioFrame:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments"},{"value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame~1init(sampleBuffer:)\/title","op":"replace","value":"initWithSampleBuffer:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithSampleBuffer:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame~1init(sampleBuffer:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/title","value":"MCAudioFrame"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/fragments","value":[{"kind":"identifier","text":"MCAudioFrame"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}