{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder\/build()"]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)MCCoreVideoSourceBuilder","title":"MCCoreVideoSourceBuilder","symbolKind":"class","modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCCoreVideoSourceBuilder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mccorevideosourcebuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccorevideosourcebuilder"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","interfaceLanguage":"swift"},"abstract":[{"text":"Responsible for building a CoreVideoSource.","type":"text"}],"sections":[],"references":{"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"url":"\/documentation\/millicastsdk\/mcsourcebuilder","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"abstract":[{"type":"text","text":"Responsible for building a source object."}],"title":"MCSourceBuilder","kind":"symbol","navigatorTitle":[{"text":"MCSourceBuilder","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSourceBuilder":{"url":"\/documentation\/millicastsdk\/mccorevideosourcebuilder","navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCoreVideoSourceBuilder","kind":"identifier"}],"title":"MCCoreVideoSourceBuilder","abstract":[{"text":"Responsible for building a CoreVideoSource.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","role":"symbol","type":"topic"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSourceBuilder/build()":{"kind":"symbol","abstract":[{"type":"text","text":"Builds the CoreVideoSource class."}],"url":"\/documentation\/millicastsdk\/mccorevideosourcebuilder\/build()","role":"symbol","title":"build()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"text":"MCCoreVideoSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCoreVideoSource"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"build"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder\/build()","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"MCCoreVideoSourceBuilder","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCCoreVideoSourceBuilder","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder\/build()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCoreVideoSourceBuilder"},{"text":" : ","kind":"text"},{"text":"MCSourceBuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSourceBuilder"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title","value":"MCSourceBuilder","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCSourceBuilder"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/title","value":"MCCoreVideoSourceBuilder","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/fragments","value":[{"text":"MCCoreVideoSourceBuilder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder~1build()\/title","op":"replace","value":"build"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"build"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder~1build()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}