{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"kind":"relationships"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"}],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connected","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connecting","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/disconnecting","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/failed","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/idle","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/reconnecting"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCConnectionState"}],"modules":[{"name":"MillicastSDK"}],"title":"MCConnectionState","symbolKind":"enum","externalID":"c:@E@MCConnectionState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate"]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/reconnecting":{"abstract":[{"text":"The socket has entered reconnection state.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"navigatorTitle":[{"text":"MCConnectionStateReconnecting","kind":"identifier"}],"role":"symbol","title":"MCConnectionState.reconnecting","url":"\/documentation\/millicastsdk\/mcconnectionstate\/reconnecting","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/reconnecting"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/failed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"abstract":[{"type":"text","text":"The socket has entered a failed state."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCConnectionStateFailed","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcconnectionstate\/failed","title":"MCConnectionState.failed","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/failed"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/millicastsdk\/mcconnectionstate\/init(rawvalue:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/init(rawValue:)","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/idle":{"navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateIdle"}],"kind":"symbol","title":"MCConnectionState.idle","url":"\/documentation\/millicastsdk\/mcconnectionstate\/idle","type":"topic","abstract":[{"type":"text","text":"The initial state of the socket. This state will be entered after graceful close."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idle"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/idle","role":"symbol"},"doc://MillicastSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/MillicastSDK\/SY","type":"unresolvable"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable"},"doc://MillicastSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/MillicastSDK\/s8SendableP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/disconnecting":{"type":"topic","url":"\/documentation\/millicastsdk\/mcconnectionstate\/disconnecting","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/disconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"navigatorTitle":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}],"title":"MCConnectionState.disconnecting","role":"symbol","abstract":[{"type":"text","text":"The socket is now in disconnecting state."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","role":"symbol","navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","title":"MCConnectionState"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","url":"\/documentation\/millicastsdk\/mcconnectionstate\/equatable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/Equatable-Implementations","role":"collectionGroup"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/connecting":{"navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateConnecting"}],"kind":"symbol","title":"MCConnectionState.connecting","url":"\/documentation\/millicastsdk\/mcconnectionstate\/connecting","type":"topic","abstract":[{"text":"The socket is in the process of connecting.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connecting","role":"symbol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/connected":{"navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateConnected"}],"kind":"symbol","title":"MCConnectionState.connected","url":"\/documentation\/millicastsdk\/mcconnectionstate\/connected","type":"topic","abstract":[{"type":"text","text":"The socket has now established a connection."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connected"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connected","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/RawRepresentable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcconnectionstate\/rawrepresentable-implementations","role":"collectionGroup"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"MCConnectionState","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCConnectionState"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MCConnectionState"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connected","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connecting","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/disconnecting","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/failed","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/idle","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/reconnecting"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCConnectionStateReconnecting","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1reconnecting\/title","op":"replace"},{"value":[{"text":"MCConnectionStateReconnecting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1reconnecting\/fragments"},{"op":"replace","value":"MCConnectionStateFailed","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1failed\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1failed\/fragments","op":"replace","value":[{"text":"MCConnectionStateFailed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1idle\/title","value":"MCConnectionStateIdle"},{"value":[{"kind":"identifier","text":"MCConnectionStateIdle"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1idle\/fragments"},{"value":"MCConnectionStateDisconnecting","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1disconnecting\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1disconnecting\/fragments","value":[{"kind":"identifier","text":"MCConnectionStateDisconnecting"}]},{"op":"replace","value":"MCConnectionState","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"value":[{"text":"MCConnectionState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connecting\/title","value":"MCConnectionStateConnecting","op":"replace"},{"value":[{"text":"MCConnectionStateConnecting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connecting\/fragments"},{"op":"replace","value":"MCConnectionStateConnected","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connected\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connected\/fragments","value":[{"kind":"identifier","text":"MCConnectionStateConnected"}],"op":"replace"}]}]}