{"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"title":"MCRTSRemoteTrackLayer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)MCRTSRemoteTrackLayer"},"sections":[],"abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/resolution","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetBitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetFps","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetHeight","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetWidth","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/temporalLayerId"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"},"references":{"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/encodingId":{"abstract":[],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/encodingid","title":"encodingId","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/encodingId","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodingId"}]},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/maxTemporalLayerId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxTemporalLayerId","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","title":"maxTemporalLayerId","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxTemporalLayerId","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/maxtemporallayerid","kind":"symbol","navigatorTitle":[{"text":"maxTemporalLayerId","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/spatialLayerId":{"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/spatiallayerid","title":"spatialLayerId","navigatorTitle":[{"kind":"identifier","text":"spatialLayerId"}],"abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/spatialLayerId","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spatialLayerId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/targetBitrate":{"navigatorTitle":[{"text":"targetBitrate","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetbitrate","type":"topic","title":"targetBitrate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"targetBitrate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetBitrate","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"title":"MCRTSRemoteTrackLayer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"type":"topic","abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/temporalLayerId":{"kind":"symbol","title":"temporalLayerId","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"temporalLayerId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/temporalLayerId","abstract":[],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/temporallayerid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"temporalLayerId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/targetWidth":{"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetWidth","abstract":[],"title":"targetWidth","navigatorTitle":[{"text":"targetWidth","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"targetWidth","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetwidth"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/targetFps":{"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetfps","title":"targetFps","navigatorTitle":[{"kind":"identifier","text":"targetFps"}],"abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetFps","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"targetFps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/maxSpatialLayerId":{"type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/maxspatiallayerid","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxSpatialLayerId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"maxSpatialLayerId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxSpatialLayerId","title":"maxSpatialLayerId"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/bitrate":{"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/bitrate","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/bitrate","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"title":"bitrate"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/targetHeight":{"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetheight","abstract":[],"role":"symbol","title":"targetHeight","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"targetHeight","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetHeight","kind":"symbol"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/resolution":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/resolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolution"},{"kind":"text","text":": "},{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"resolution","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/resolution","title":"resolution"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCRTSRemoteTrackLayer"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/resolution","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetBitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetFps","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetHeight","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetWidth","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/temporalLayerId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteTrackLayer"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"encodingId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1encodingId\/title"},{"op":"replace","value":[{"text":"encodingId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1encodingId\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxTemporalLayerId\/title","op":"replace","value":"maxTemporalLayerId"},{"value":[{"text":"maxTemporalLayerId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxTemporalLayerId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1spatialLayerId\/title","value":"spatialLayerId"},{"value":[{"kind":"identifier","text":"spatialLayerId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1spatialLayerId\/fragments","op":"replace"},{"op":"replace","value":"targetBitrate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetBitrate\/title"},{"value":[{"text":"targetBitrate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetBitrate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title","value":"MCRTSRemoteTrackLayer","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1temporalLayerId\/title","op":"replace","value":"temporalLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1temporalLayerId\/fragments","value":[{"text":"temporalLayerId","kind":"identifier"}]},{"value":"targetWidth","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetWidth\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetWidth\/fragments","value":[{"kind":"identifier","text":"targetWidth"}],"op":"replace"},{"value":"targetFps","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetFps\/title"},{"value":[{"text":"targetFps","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetFps\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxSpatialLayerId\/title","op":"replace","value":"maxSpatialLayerId"},{"op":"replace","value":[{"text":"maxSpatialLayerId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxSpatialLayerId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1bitrate\/title","value":"bitrate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1bitrate\/fragments","value":[{"kind":"identifier","text":"bitrate"}]},{"value":"targetHeight","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetHeight\/title"},{"value":[{"text":"targetHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetHeight\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1resolution\/title","value":"resolution"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1resolution\/fragments","value":[{"kind":"identifier","text":"resolution"}],"op":"replace"}]}]}