{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setName(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setType(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setUniqueId(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"roleHeading":"Class","externalID":"c:objc(cs)MCSourceBuilder","navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"class","title":"MCSourceBuilder"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder"]},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","abstract":[{"type":"text","text":"Responsible for building a source object."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceBuilder":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudiosourcebuilder","role":"symbol","navigatorTitle":[{"text":"MCAudioSourceBuilder","kind":"identifier"}],"title":"MCAudioSourceBuilder","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder","abstract":[{"type":"text","text":"Responsible for building AudioSource."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioSourceBuilder"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setType(_:)":{"url":"\/documentation\/millicastsdk\/mcsourcebuilder\/settype(_:)","navigatorTitle":[{"text":"setType:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MCSourceType","text":"MCSourceType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setType(_:)","abstract":[{"text":"Sets the type of media source to be created, either video or audio.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setType(_:)","role":"symbol","type":"topic"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSourceBuilder":{"url":"\/documentation\/millicastsdk\/mccustomaudiosourcebuilder","navigatorTitle":[{"text":"MCCustomAudioSourceBuilder","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"title":"MCCustomAudioSourceBuilder","abstract":[{"type":"text","text":"Responsible for building MCCustomAudioSource."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"url":"\/documentation\/millicastsdk\/mcsourcebuilder","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"abstract":[{"type":"text","text":"Responsible for building a source object."}],"title":"MCSourceBuilder","kind":"symbol","navigatorTitle":[{"text":"MCSourceBuilder","kind":"identifier"}]},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSourceBuilder":{"url":"\/documentation\/millicastsdk\/mccorevideosourcebuilder","navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCoreVideoSourceBuilder","kind":"identifier"}],"title":"MCCoreVideoSourceBuilder","abstract":[{"text":"Responsible for building a CoreVideoSource.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlaybackBuilder":{"url":"\/documentation\/millicastsdk\/mcaudioplaybackbuilder","role":"symbol","title":"MCAudioPlaybackBuilder","abstract":[{"type":"text","text":"Responsible for building AudioPlayback."}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"navigatorTitle":[{"text":"MCAudioPlaybackBuilder","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setName(_:)":{"url":"\/documentation\/millicastsdk\/mcsourcebuilder\/setname(_:)","navigatorTitle":[{"text":"setName:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"title":"setName(_:)","abstract":[{"type":"text","text":"Set a name to the media source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setName(_:)","role":"symbol","type":"topic"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setUniqueId(_:)":{"url":"\/documentation\/millicastsdk\/mcsourcebuilder\/setuniqueid(_:)","navigatorTitle":[{"kind":"identifier","text":"setUniqueId:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUniqueId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"title":"setUniqueId(_:)","abstract":[{"type":"text","text":"Set a unique identifier to the source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setUniqueId(_:)","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder","url":"\/documentation\/millicastsdk\/mcvideosourcebuilder","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCVideoSourceBuilder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"title":"MCVideoSourceBuilder","abstract":[{"type":"text","text":"Responsible for building a video source object."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCSourceBuilder"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCSourceBuilder"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MCSourceBuilder","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setName(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setType(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setUniqueId(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MCSourceBuilder","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder\/title","value":"MCAudioSourceBuilder"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder\/fragments","value":[{"text":"MCAudioSourceBuilder","kind":"identifier"}],"op":"replace"},{"value":"setType:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setType(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setType:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setType(_:)\/fragments"},{"op":"replace","value":"MCCustomAudioSourceBuilder","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/title"},{"value":[{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/fragments"},{"value":"MCSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title"},{"op":"replace","value":[{"text":"MCSourceBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments"},{"op":"replace","value":"MCCoreVideoSourceBuilder","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/title"},{"value":[{"kind":"identifier","text":"MCCoreVideoSourceBuilder"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSourceBuilder\/fragments","op":"replace"},{"op":"replace","value":"MCAudioPlaybackBuilder","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/fragments","value":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"op":"replace"},{"value":"setName:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setName(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setName(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setName:","kind":"identifier"}]},{"op":"replace","value":"setUniqueId:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setUniqueId(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setUniqueId(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setUniqueId:","kind":"identifier"}]},{"value":"MCVideoSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/fragments","value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}]}]}]}