{"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatsreport"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatsreport"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStatsReport","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Interface is a container for various different statistics.","type":"text"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsReport","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCStatsReport","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCStatsReport","roleHeading":"Class","symbolKind":"class","title":"MCStatsReport"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/get(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStreamDetails()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/size()"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/get(_:)":{"url":"\/documentation\/millicastsdk\/mcstatsreport\/get(_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"MCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"get:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/get(_:)","abstract":[{"text":"Retrieves a specific MCStats object from the report based on its unique identifier.","type":"text"}],"type":"topic","title":"get(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/size()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The number of MCStats objects stored in the stats report."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"title":"size()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/size()","url":"\/documentation\/millicastsdk\/mcstatsreport\/size()"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStatsOf(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStatsOf"},{"text":"(","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStats","text":"MCStats","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getStatsOfType:"}],"title":"getStatsOf(_:)","abstract":[{"text":"Retrieves an array of MCStats objects from the report that match a specified MCStatsType.","type":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","kind":"symbol"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStreamDetails()":{"abstract":[{"type":"text","text":"Get the stream details of the session the stats belong to."}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/getstreamdetails()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStreamDetails"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStreamDetails()","title":"getStreamDetails()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStreamDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamDetails","text":"MCStreamDetails"}],"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"url":"\/documentation\/millicastsdk\/mcstatsreport","navigatorTitle":[{"text":"MCStatsReport","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStatsReport","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"title":"MCStatsReport","kind":"symbol","type":"topic"},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MCStatsReport","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCStatsReport","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/get(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStreamDetails()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/size()"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsReport"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"get:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1get(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"get:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1get(_:)\/fragments"},{"value":"size","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1size()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1size()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"size","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/title","op":"replace","value":"getStatsOfType:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getStatsOfType:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStreamDetails()\/title","op":"replace","value":"getStreamDetails"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStreamDetails()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getStreamDetails","kind":"identifier"}]},{"value":"MCStatsReport","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsReport"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments"}]}]}