{"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/sid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/type"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"]},{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MCStats"}],"externalID":"c:objc(cs)MCStats","role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"MCStats","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCStats","kind":"identifier"}],"symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCStats","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstats"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstats"]}],"abstract":[{"text":"A container of various different stats. To make sense of such statistics, please refer to the ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","type":"reference","isActive":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"},"references":{"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRtpStreamStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCRtpStreamStats"}],"abstract":[{"text":"Statistics for an RTP stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","title":"MCRtpStreamStats","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtpstreamstats"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats","role":"symbol","navigatorTitle":[{"text":"MCCodecsStats","kind":"identifier"}],"abstract":[{"text":"Gathers audio\/video codec statistics.","type":"text"}],"title":"MCCodecsStats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"url":"\/documentation\/millicastsdk\/mcstats","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStats","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"type":"topic","title":"MCStats"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats/sid":{"abstract":[{"text":"The unique identifier.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sid"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/sid","url":"\/documentation\/millicastsdk\/mcstats\/sid","type":"topic","title":"sid"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats/timestamp":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/timestamp","title":"timestamp","abstract":[{"text":"The timestamp in milliseconds since Unix epoch (Jan 1, 1970 00:00:00 UTC) at which the statistical data was recorded.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcstats\/timestamp"},"https://w3c.github.io/webrtc-stats/#introduction":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","type":"link","titleInlineContent":[{"text":"WebRTC standard","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats/type":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"abstract":[{"text":"The type of statistics.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","url":"\/documentation\/millicastsdk\/mcstats\/type","role":"symbol"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIceCandidatePairStats"}],"abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","kind":"symbol","title":"MCIceCandidatePairStats","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats","navigatorTitle":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats":{"type":"topic","abstract":[{"text":"The MCMediaSourceStats class gathers statistics details.","type":"text"}],"navigatorTitle":[{"text":"MCMediaSourceStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","kind":"symbol","url":"\/documentation\/millicastsdk\/mcmediasourcestats","title":"MCMediaSourceStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCMediaSourceStats","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MCStats"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCStats"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCStats","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/sid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/type"],"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"],"title":"Inherited By"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MCStats","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title","value":"MCRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCRtpStreamStats"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats"},{"op":"replace","value":[{"kind":"identifier","text":"MCCodecsStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments"},{"op":"replace","value":"MCStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments","value":[{"kind":"identifier","text":"MCStats"}],"op":"replace"},{"value":"sid","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1sid\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"sid"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1sid\/fragments"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1timestamp\/title"},{"value":[{"text":"timestamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1timestamp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1type\/title","value":"type"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title","op":"replace","value":"MCIceCandidatePairStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments","value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","value":"MCMediaSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments","value":[{"text":"MCMediaSourceStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}