{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberstats"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstats"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats"},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/currentRoundTripTime","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamViewId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/subscriberId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/totalRoundTripTime","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/trackStats"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/toJSON(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberStats"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStats"}],"externalID":"c:objc(cs)MCSubscriberStats","role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"MCSubscriberStats","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStats"}],"symbolKind":"class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/streamId":{"role":"symbol","kind":"symbol","title":"streamId","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstats\/streamid","navigatorTitle":[{"text":"streamId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamId","abstract":[]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/streamViewId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamViewId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"streamViewId","navigatorTitle":[{"kind":"identifier","text":"streamViewId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamViewId","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/streamviewid"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/subscriberId":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriberId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"subscriberId","navigatorTitle":[{"text":"subscriberId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/subscriberId","abstract":[],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/subscriberid"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/clusterId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clusterId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"clusterId","navigatorTitle":[{"kind":"identifier","text":"clusterId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/clusterId","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/clusterid"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats","role":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mcsubscriberstats","title":"MCSubscriberStats","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStats"}]},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/toJSON(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJSON"},{"text":"(","kind":"text"},{"text":"MCSubscriberStatsLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCSubscriberStatsLevel"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"toJSON:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstats\/tojson(_:)","type":"topic","title":"toJSON(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/toJSON(_:)","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/currentRoundTripTime":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentRoundTripTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"title":"currentRoundTripTime","navigatorTitle":[{"kind":"identifier","text":"currentRoundTripTime"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/currentRoundTripTime","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/currentroundtriptime"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/trackStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/trackStats","type":"topic","abstract":[],"title":"trackStats","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/trackstats","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackStats"},{"text":": [","kind":"text"},{"text":"MCTrackStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"trackStats"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/totalRoundTripTime":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalRoundTripTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"totalRoundTripTime","navigatorTitle":[{"kind":"identifier","text":"totalRoundTripTime"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/totalRoundTripTime","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/totalroundtriptime"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/timestamp":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/timestamp","role":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mcsubscriberstats\/timestamp","title":"timestamp","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"timestamp"}]},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCSubscriberStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"MCSubscriberStats","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MCSubscriberStats","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/currentRoundTripTime","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/streamViewId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/subscriberId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/totalRoundTripTime","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/trackStats"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/toJSON(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStats"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"streamId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1streamId\/title","op":"replace"},{"op":"replace","value":[{"text":"streamId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1streamId\/fragments"},{"op":"replace","value":"streamViewId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1streamViewId\/title"},{"value":[{"text":"streamViewId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1streamViewId\/fragments","op":"replace"},{"op":"replace","value":"subscriberId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1subscriberId\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1subscriberId\/fragments","value":[{"text":"subscriberId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1clusterId\/title","op":"replace","value":"clusterId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1clusterId\/fragments","value":[{"text":"clusterId","kind":"identifier"}]},{"value":"MCSubscriberStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/title"},{"value":[{"text":"MCSubscriberStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/fragments","op":"replace"},{"value":"toJSON:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1toJSON(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1toJSON(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJSON:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1currentRoundTripTime\/title","op":"replace","value":"currentRoundTripTime"},{"value":[{"text":"currentRoundTripTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1currentRoundTripTime\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1trackStats\/title","op":"replace","value":"trackStats"},{"value":[{"text":"trackStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1trackStats\/fragments","op":"replace"},{"value":"totalRoundTripTime","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1totalRoundTripTime\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1totalRoundTripTime\/fragments","value":[{"text":"totalRoundTripTime","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1timestamp\/title","value":"timestamp"},{"op":"replace","value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1timestamp\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}