{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriber"}],"externalID":"c:objc(cs)MCSubscriber","title":"MCSubscriber","symbolKind":"class"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/credentials","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isConnected","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isSubscribed","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAddedPublisher","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsPublisher","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsReportPublisher","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/streamStoppedPublisher","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/viewerCountPublisher"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/addWebrtcRemoteTrack(kind:cname:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/audioTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/getCredentialsWithCompletionHandler(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpError()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpErrorPublisher()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isSubscribed(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionState()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionStatePublisher()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAdded()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/setCredentials(_:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingError()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingErrorPublisher()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/stats()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsReport()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/streamStopped()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(with:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/unsubscribe(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/videoTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/viewerCount()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcAudioTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcVideoTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketState()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketStatePublisher()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSubscriber","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/setCredentials(_:completionHandler:)":{"type":"topic","title":"setCredentials(_:completionHandler:)","abstract":[{"type":"text","text":"Sets the credentials, providing authentication information required for connecting to the streaming platform."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCredentials","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/setcredentials(_:completionhandler:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/setCredentials(_:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"setCredentials:completionHandler:"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/isSubscribed(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/issubscribed(completionhandler:)","abstract":[{"type":"text","text":"Checks whether the subscriber is currently subscribing to any media."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isSubscribed(completionHandler:)","title":"isSubscribed(completionHandler:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isSubscribed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"isSubscribedWithCompletionHandler:","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/subscribe(with:completionHandler:)":{"title":"subscribe(with:completionHandler:)","type":"topic","abstract":[{"text":"Subscribes to a stream with options.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/subscribe(with:completionhandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(with:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subscribe","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCClientOptions","kind":"typeIdentifier","text":"MCClientOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"subscribeWithOptions:completionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"title":"MCSubscriber","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","kind":"symbol","abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/statsReportPublisher":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/statsreportpublisher","role":"symbol","title":"statsReportPublisher","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsReportPublisher","type":"topic","abstract":[{"text":"Get a Combine based publisher that can be used to receive stats reports.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statsReportPublisher","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/webrtcAudioTracks(completionHandler:)":{"title":"webrtcAudioTracks(completionHandler:)","abstract":[{"type":"text","text":"List all available webrtc remote audio tracks created so far."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webrtcAudioTracks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": ([","kind":"text"},{"kind":"typeIdentifier","text":"MCWebrtcRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"]?, (any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/webrtcaudiotracks(completionhandler:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcAudioTracks(completionHandler:)","navigatorTitle":[{"text":"webrtcAudioTracksWithCompletionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/webrtcVideoTracks(completionHandler:)":{"type":"topic","title":"webrtcVideoTracks(completionHandler:)","abstract":[{"type":"text","text":"List all available webrtc remote video tracks created so far."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"webrtcVideoTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","text":"MCWebrtcRemoteAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":"]?, (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/webrtcvideotracks(completionhandler:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcVideoTracks(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"webrtcVideoTracksWithCompletionHandler:"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/viewerCount()":{"title":"viewerCount()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewerCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":">"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/viewercount()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/viewerCount()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives viewer count updates."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/statsPublisher":{"title":"statsPublisher","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive subscriber stats events"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsPublisher"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MCSubscriberStats","preciseIdentifier":"c:objc(cs)MCSubscriberStats"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/statspublisher","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsPublisher"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/signalingError()":{"title":"signalingError()","abstract":[{"text":"Create an AsyncStream that receives signaling errors.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingError"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSignalingError","kind":"typeIdentifier","text":"MCSignalingError"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/signalingerror()","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingError()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/isSubscribed":{"title":"isSubscribed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSubscribed"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Asynchronously query whether the subscriber is currently subscribed to a stream or not.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/issubscribed","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isSubscribed"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/websocketStatePublisher()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketStatePublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive connection state changes for the websocket"},{"type":"text","text":" "},{"type":"text","text":"connection."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketStatePublisher"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/websocketstatepublisher()","kind":"symbol","role":"symbol","title":"websocketStatePublisher()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/viewerCountPublisher":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/viewercountpublisher","kind":"symbol","type":"topic","title":"viewerCountPublisher","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/viewerCountPublisher","abstract":[{"text":"Get a Combine based publisher that can be used to receive viewer count events","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewerCountPublisher","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/delegate":{"title":"delegate","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MCSubscriberDelegate","text":"MCSubscriberDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/delegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/isConnected":{"title":"isConnected","abstract":[{"type":"text","text":"Asynchronously query whether the subscriber is connected or not."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/isconnected","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isConnected","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isConnected","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/httpErrorPublisher()":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/httperrorpublisher()","title":"httpErrorPublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive http errors"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"httpErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCHTTPConnectionError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpErrorPublisher()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/addWebrtcRemoteTrack(kind:cname:completionHandler:)":{"role":"symbol","kind":"symbol","title":"addWebrtcRemoteTrack(kind:cname:completionHandler:)","url":"\/documentation\/millicastsdk\/mcsubscriber\/addwebrtcremotetrack(kind:cname:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addWebrtcRemoteTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"kind"},{"kind":"text","text":": "},{"text":"MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/addWebrtcRemoteTrack(kind:cname:completionHandler:)","abstract":[{"type":"text","text":"Create a webrtc remote track that can be used for advanced projection use cases"}]},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/audioTracks(completionHandler:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioTracks"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"audioTracks(completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/audioTracks(completionHandler:)","abstract":[{"text":"List all available rts remote audio tracks received so far.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/audiotracks(completionhandler:)","navigatorTitle":[{"text":"audioTracksWithCompletionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/rtsRemoteTrackAddedPublisher":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrackAddedPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"text":">","kind":"text"}],"title":"rtsRemoteTrackAddedPublisher","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAddedPublisher","url":"\/documentation\/millicastsdk\/mcsubscriber\/rtsremotetrackaddedpublisher","abstract":[{"type":"text","text":"Get a Combine based publisher that receives rts remote tracks when they are available."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/connect(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcclient\/connect(completionhandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"connectWithCompletionHandler:"}],"abstract":[{"text":"Connects and opens a websocket connection with the Millicast platform.  You must set valid credentials before using this method.","type":"text"}],"title":"connect(completionHandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","required":true,"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/signalingErrorPublisher()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingErrorPublisher"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"signalingErrorPublisher()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingErrorPublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive signaling errors"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/signalingerrorpublisher()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/rtsRemoteTrackAdded()":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/rtsremotetrackadded()","title":"rtsRemoteTrackAdded()","abstract":[{"text":"Creates a new AsyncStream that receives rts remote tracks when they are available.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackAdded","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":">","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAdded()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/stats()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stats"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSubscriberStats","text":"MCSubscriberStats","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"stats()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/stats()","url":"\/documentation\/millicastsdk\/mcsubscriber\/stats()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives subscriber stats updates."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/websocketState()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"websocketState","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"websocketState()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketState()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives connection state changes for the websocket connection."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/websocketstate()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/credentials":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"}],"title":"credentials","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/credentials","url":"\/documentation\/millicastsdk\/mcsubscriber\/credentials","abstract":[{"type":"text","text":"Asynchronously query the currently set credentials."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/getCredentialsWithCompletionHandler(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/getcredentialswithcompletionhandler(_:)","abstract":[{"type":"text","text":"Get the current viewer’s credentials."}],"title":"getCredentialsWithCompletionHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCredentialsWithCompletionHandler","kind":"identifier"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/getCredentialsWithCompletionHandler(_:)","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/videoTracks(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/videotracks(completionhandler:)","role":"symbol","title":"videoTracks(completionHandler:)","abstract":[{"text":"List all available rts remote video tracks received so far.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/videoTracks(completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTracks"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":"]?, (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"videoTracksWithCompletionHandler:"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/unsubscribe(completionHandler:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"unsubscribe(completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/unsubscribe(completionHandler:)","abstract":[{"type":"text","text":"Stops the subscription process indicating to the streaming server that the subscriber"},{"type":"text","text":" "},{"type":"text","text":"is no longer interested in receiving audio and video content."},{"type":"text","text":" "},{"type":"text","text":"After calling this method, the SDK automatically terminates the connection between"},{"text":" ","type":"text"},{"text":"the subscriber and the streaming platform.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/unsubscribe(completionhandler:)","navigatorTitle":[{"text":"unsubscribeWithCompletionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/subscribe(completionHandler:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"subscribe(completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(completionHandler:)","url":"\/documentation\/millicastsdk\/mcsubscriber\/subscribe(completionhandler:)","abstract":[{"text":"Initiates the subscription process from the Millicast platform.","type":"text"},{"text":" ","type":"text"},{"text":"Prior to calling this method, you must use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","isActive":true},{"type":"text","text":" or similar to"},{"type":"text","text":" "},{"type":"text","text":"connect the subscriber to the platform."},{"type":"text","text":" "},{"text":"Successful subscription results in calling the onSubscribed method of the Listener.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"subscribeWithCompletionHandler:"}]},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/httpError()":{"title":"httpError()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"httpError","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier","text":"MCHTTPConnectionError"},{"kind":"text","text":">"}],"abstract":[{"text":"Create an AsyncStream that receives http connection errors.","type":"text"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpError()","url":"\/documentation\/millicastsdk\/mcsubscriber\/httperror()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/streamStopped()":{"abstract":[{"text":"Creates a new AsyncStream that receives stream stopped events","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"streamStopped","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MCStreamStoppedEvent","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent"},{"text":">","kind":"text"}],"role":"symbol","title":"streamStopped()","url":"\/documentation\/millicastsdk\/mcsubscriber\/streamstopped()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/streamStopped()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/peerConnectionState()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peerConnectionState"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"text":">","kind":"text"}],"title":"peerConnectionState()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionState()","url":"\/documentation\/millicastsdk\/mcsubscriber\/peerconnectionstate()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives connection state changes for the peer connection."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","url":"\/documentation\/millicastsdk\/mcclient","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MCClient","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":" and "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"MCClient","navigatorTitle":[{"text":"MCClient","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/statsReport()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"statsReport","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"text":"MCStatsReport","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"text":">","kind":"text"}],"title":"statsReport()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsReport()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stats reports."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/statsreport()"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/peerConnectionStatePublisher()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"peerConnectionStatePublisher()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionStatePublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive connection state changes for the peer"},{"text":" ","type":"text"},{"type":"text","text":"connection."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/peerconnectionstatepublisher()"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/streamStoppedPublisher":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamStoppedPublisher"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"text":"MCStreamStoppedEvent","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"kind":"text","text":">"}],"title":"streamStoppedPublisher","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/streamStoppedPublisher","url":"\/documentation\/millicastsdk\/mcsubscriber\/streamstoppedpublisher","abstract":[{"type":"text","text":"Get a Combine based publisher that receives  publisher stream stopped events"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"type":"topic","abstract":[{"type":"text","text":"Initialize a subscriber."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCSubscriberDelegate","kind":"typeIdentifier","text":"MCSubscriberDelegate"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"title":"init(delegate:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCSubscriber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/addWebrtcRemoteTrack(kind:cname:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/audioTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/getCredentialsWithCompletionHandler(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/isSubscribed(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/setCredentials(_:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/subscribe(with:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/unsubscribe(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/videoTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcAudioTracks(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcVideoTracks(completionHandler:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient"],"kind":"relationships","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSubscriber","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"setCredentials:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1setCredentials(_:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1setCredentials(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setCredentials:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1isSubscribed(completionHandler:)\/title","op":"replace","value":"isSubscribedWithCompletionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isSubscribedWithCompletionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1isSubscribed(completionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1subscribe(with:completionHandler:)\/title","value":"subscribeWithOptions:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1subscribe(with:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"subscribeWithOptions:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"value":"webrtcAudioTracksWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcAudioTracks(completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"webrtcAudioTracksWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcAudioTracks(completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcVideoTracks(completionHandler:)\/title","op":"replace","value":"webrtcVideoTracksWithCompletionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"webrtcVideoTracksWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcVideoTracks(completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1delegate\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1addWebrtcRemoteTrack(kind:cname:completionHandler:)\/title","op":"replace","value":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1addWebrtcRemoteTrack(kind:cname:completionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1audioTracks(completionHandler:)\/title","op":"replace","value":"audioTracksWithCompletionHandler:"},{"value":[{"text":"- ","kind":"text"},{"text":"audioTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1audioTracks(completionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace","value":"MCPublisher"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/title","value":"connectWithCompletionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"connectWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1getCredentialsWithCompletionHandler(_:)\/title","value":"getCredentialsWithCompletionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1getCredentialsWithCompletionHandler(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"value":"videoTracksWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1videoTracks(completionHandler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"videoTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1videoTracks(completionHandler:)\/fragments","op":"replace"},{"op":"replace","value":"unsubscribeWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1unsubscribe(completionHandler:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1unsubscribe(completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unsubscribeWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1subscribe(completionHandler:)\/title","value":"subscribeWithCompletionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"subscribeWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1subscribe(completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title","value":"MCClient"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments","op":"replace","value":[{"text":"MCClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments"}]}]}