{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/addRenderer(_:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/currentProjection(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/removeRenderer(_:completionHandler:)"],"title":"Instance Methods"}],"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack"]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack","navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"title":"MCWebrtcRemoteVideoTrack","symbolKind":"class","roleHeading":"Class"},"references":{"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"kind":"symbol","title":"MCWebrtcRemoteTrack","abstract":[{"text":"The webrtc logical track.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/addRenderer(_:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/addrenderer(_:completionhandler:)","abstract":[{"type":"text","text":"Attach a renderer to this track so it receives frames when projected."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addRenderer"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addRenderer:completionHandler:"}],"type":"topic","title":"addRenderer(_:completionHandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/addRenderer(_:completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:promote:completionhandler:)","abstract":[{"type":"text","text":"Enable the track and project from given RTS track."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"project","kind":"identifier"},{"kind":"text","text":"("},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"promote"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:"}],"title":"project(rtsRemoteVideoTrack:layer:promote:completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:layer:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:completionhandler:)","abstract":[{"type":"text","text":"Enable the track and project from given RTS track, with default promote behaviour, which is false."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rtsRemoteVideoTrack"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:"}],"type":"topic","title":"project(rtsRemoteVideoTrack:layer:completionHandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:completionHandler:)"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/removeRenderer(_:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/removerenderer(_:completionhandler:)","abstract":[{"type":"text","text":"Remove a previously attached video renderer."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeRenderer","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"removeRenderer:completionHandler:","kind":"identifier"}],"type":"topic","title":"removeRenderer(_:completionHandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/removeRenderer(_:completionHandler:)"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"title":"MCWebrtcRemoteVideoTrack","abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:completionhandler:)","abstract":[{"text":"Enable the track and project from given RTS track, with default promote and layer behaviour.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rtsRemoteVideoTrack"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"projectWithRTSRemoteVideoTrack:completionHandler:","kind":"identifier"}],"title":"project(rtsRemoteVideoTrack:completionHandler:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:completionHandler:)"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/currentProjection(completionHandler:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"currentProjection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"currentProjectionWithCompletionHandler:","kind":"identifier"}],"title":"currentProjection(completionHandler:)","abstract":[{"type":"text","text":"Get the RTS track which is currently projected onto this webrtc track."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/currentprojection(completionhandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/currentProjection(completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCWebrtcRemoteVideoTrack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/addRenderer(_:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/currentProjection(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/removeRenderer(_:completionHandler:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MCWebrtcRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},{"value":"addRenderer:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1addRenderer(_:completionHandler:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1addRenderer(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addRenderer:completionHandler:","kind":"identifier"}]},{"value":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:promote:completionHandler:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:promote:completionHandler:)\/fragments"},{"value":"projectWithRTSRemoteVideoTrack:layer:completionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:completionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1removeRenderer(_:completionHandler:)\/title","op":"replace","value":"removeRenderer:completionHandler:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeRenderer:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1removeRenderer(_:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","value":"MCWebrtcRemoteVideoTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:completionHandler:)\/title","op":"replace","value":"projectWithRTSRemoteVideoTrack:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"projectWithRTSRemoteVideoTrack:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1currentProjection(completionHandler:)\/title","value":"currentProjectionWithCompletionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1currentProjection(completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"currentProjectionWithCompletionHandler:"}]}]}]}