{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/toJSON(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberstats\/tojson(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberstats\/tojson(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toJSON","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"level"},{"kind":"text","text":": "},{"text":"MCSubscriberStatsLevel","preciseIdentifier":"c:@E@MCSubscriberStatsLevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toJSON"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MCSubscriberStatsLevel","kind":"typeIdentifier","text":"MCSubscriberStatsLevel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"toJSON:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)MCSubscriberStats(im)toJSON:","title":"toJSON(_:)","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel":{"title":"MCSubscriberStatsLevel","abstract":[{"type":"text","text":"Enum specifying the level of verbosity for stats."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/toJSON(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJSON"},{"text":"(","kind":"text"},{"text":"MCSubscriberStatsLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCSubscriberStatsLevel"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"toJSON:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstats\/tojson(_:)","type":"topic","title":"toJSON(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/toJSON(_:)","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats","role":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mcsubscriberstats","title":"MCSubscriberStats","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStats"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"toJSON:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toJSON:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"toJSON:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","text":"MCSubscriberStatsLevel","preciseIdentifier":"c:@E@MCSubscriberStatsLevel"},{"kind":"text","text":") "},{"text":"level","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/title","value":"MCSubscriberStatsLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/fragments","value":[{"text":"MCSubscriberStatsLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1toJSON(_:)\/title","value":"toJSON:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1toJSON(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toJSON:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/title","value":"MCSubscriberStats"},{"value":[{"text":"MCSubscriberStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}