{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/audioCodec","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"The audio codec to use for publishing. This is only available for the publisher.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioCodec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/audiocodec"]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/audiocodec"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"audioCodec","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"audioCodec"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCClientOptions(py)audioCodec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"audioCodec","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcclientoptions","title":"MCClientOptions","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","role":"symbol","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCClientOptions","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/audioCodec":{"url":"\/documentation\/millicastsdk\/mcclientoptions\/audiocodec","kind":"symbol","title":"audioCodec","type":"topic","role":"symbol","navigatorTitle":[{"text":"audioCodec","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/audioCodec","abstract":[{"type":"text","text":"The audio codec to use for publishing. This is only available for the publisher."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioCodec"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"audioCodec"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"audioCodec"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"audioCodec","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCClientOptions"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1audioCodec\/title","value":"audioCodec","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1audioCodec\/fragments","value":[{"kind":"identifier","text":"audioCodec"}]}]}]}