{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"MCTrackStatsTypeAudio","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCTrackStatsType@MCTrackStatsTypeAudio","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audio"}],"title":"MCTrackStatsType.audio"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrackstatstype\/audio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrackstatstype\/audio"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/audio","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/audio":{"navigatorTitle":[{"kind":"identifier","text":"MCTrackStatsTypeAudio"}],"title":"MCTrackStatsType.audio","url":"\/documentation\/millicastsdk\/mctrackstatstype\/audio","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/audio","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audio"}],"abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType":{"navigatorTitle":[{"kind":"identifier","text":"MCTrackStatsType"}],"title":"MCTrackStatsType","url":"\/documentation\/millicastsdk\/mctrackstatstype","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrackStatsType"}],"abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MCTrackStatsTypeAudio","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCTrackStatsTypeAudio"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MCTrackStatsTypeAudio","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1audio\/title","value":"MCTrackStatsTypeAudio"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1audio\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCTrackStatsTypeAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType\/title","value":"MCTrackStatsType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType\/fragments","value":[{"kind":"identifier","text":"MCTrackStatsType"}],"op":"replace"}]}]}