{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pli_count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/pli_count","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)pli_count","roleHeading":"Instance Property","symbolKind":"property","title":"pli_count","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pli_count","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"pli_count"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The number of Picture Loss Indication (PLI) messages sent. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","isActive":true,"type":"reference"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/pli_count"]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/pli_count"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-plicount":{"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","titleInlineContent":[{"text":"pliCount","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","title":"pliCount"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","type":"topic","title":"MCOutboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"abstract":[{"text":"Statistics about the outbound RTP streams","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/pli_count":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/pli_count","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/pli_count","type":"topic","title":"pli_count","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pli_count","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pli_count","kind":"identifier"}],"abstract":[{"text":"The number of Picture Loss Indication (PLI) messages sent. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","isActive":true,"type":"reference"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pli_count"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"pli_count","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"text":"unsigned long","preciseIdentifier":"c:l","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"pli_count","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1pli_count\/title","value":"pli_count"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1pli_count\/fragments","value":[{"kind":"identifier","text":"pli_count"}],"op":"replace"}]}]}