{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The target bitrate. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","isActive":true}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/target_bitrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/target_bitrate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"target_bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/target_bitrate","interfaceLanguage":"swift"},"metadata":{"title":"target_bitrate","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"target_bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"target_bitrate"}],"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)target_bitrate"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/target_bitrate":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/target_bitrate","title":"target_bitrate","navigatorTitle":[{"kind":"identifier","text":"target_bitrate"}],"abstract":[{"text":"The target bitrate. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"target_bitrate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/target_bitrate","kind":"symbol","type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-targetbitrate":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","title":"targetBitrate","titleInlineContent":[{"text":"targetBitrate","type":"text"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","type":"topic","title":"MCOutboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"abstract":[{"text":"Statistics about the outbound RTP streams","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"target_bitrate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"target_bitrate","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"target_bitrate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1target_bitrate\/title","value":"target_bitrate"},{"op":"replace","value":[{"kind":"identifier","text":"target_bitrate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1target_bitrate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats","op":"replace"},{"op":"replace","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments"}]}]}