{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Logs disabled. This is only used with ","type":"text"},{"type":"codeVoice","code":"MCLogger\/setDelegate"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcloglevel\/off"]},{"paths":["\/documentation\/millicastsdk\/mcloglevel\/off"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/off","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","symbolKind":"case","title":"MCLogLevel.off","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}],"externalID":"c:@E@MCLogLevel@MCLogLevelOff","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelOff"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel/off":{"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel\/off","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/off","title":"MCLogLevel.off","kind":"symbol","abstract":[{"type":"text","text":"Logs disabled. This is only used with "},{"type":"codeVoice","code":"MCLogger\/setDelegate"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"off","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCLogLevelOff"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel":{"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","kind":"symbol","title":"MCLogLevel","abstract":[{"type":"text","text":"The log message’s level"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCLogLevel"}],"navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCLogLevelOff"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MCLogLevelOff"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"MCLogLevelOff","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MCLogLevelOff","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1off\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1off\/fragments","value":[{"kind":"identifier","text":"MCLogLevelOff"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel","op":"replace"},{"value":[{"kind":"identifier","text":"MCLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/fragments"}]}]}