{"abstract":[{"type":"text","text":"Checks whether the playback device is currently playing media (true) or not (false)."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource\/isPlaying()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"symbolKind":"method","title":"isPlaying()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isPlaying","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)PlaybackSource(im)isPlaying","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/playbacksource\/isplaying()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/playbacksource\/isplaying()"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaying"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"True if playing. False otherwise.","type":"text"}]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/PlaybackSource/isPlaying()":{"role":"symbol","required":true,"title":"isPlaying()","url":"\/documentation\/millicastsdk\/playbacksource\/isplaying()","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource\/isPlaying()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaying"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"type":"topic","abstract":[{"text":"Checks whether the playback device is currently playing media (true) or not (false).","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/PlaybackSource":{"role":"symbol","title":"PlaybackSource","url":"\/documentation\/millicastsdk\/playbacksource","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaybackSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlaybackSource"}],"type":"topic","abstract":[{"text":"Responsible for managing playback devices.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isPlaying"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isPlaying","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:b","text":"_Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isPlaying","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isPlaying","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource~1isPlaying()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isPlaying","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource~1isPlaying()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/title","value":"PlaybackSource"},{"value":[{"kind":"identifier","text":"PlaybackSource"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/fragments","op":"replace"}]}]}