{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/token"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/token"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/token"]}],"metadata":{"title":"token","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"token"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:objc(cs)MCPublisherCredentials(py)token"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The publishing token.","type":"text"}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials/token":{"title":"token","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"token"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/token","abstract":[{"type":"text","text":"The publishing token."}],"url":"\/documentation\/millicastsdk\/mcpublishercredentials\/token","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"abstract":[{"text":"The Credentials interface represents the credentials required for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"connecting the publisher to the streaming platform and publishing a stream."},{"type":"text","text":" "},{"text":"Refer to the ","type":"text"},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"},{"type":"text","text":" for this information."}],"navigatorTitle":[{"text":"MCPublisherCredentials","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","kind":"symbol","title":"MCPublisherCredentials","type":"topic","url":"\/documentation\/millicastsdk\/mcpublishercredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCPublisherCredentials","kind":"identifier"}],"role":"symbol"},"https://dash.millicast.com/docs.html":{"type":"link","title":"streaming dashboard","url":"https:\/\/dash.millicast.com\/docs.html","identifier":"https:\/\/dash.millicast.com\/docs.html","titleInlineContent":[{"type":"text","text":"streaming dashboard"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"token"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"token"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"token","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"token","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1token\/title"},{"value":[{"kind":"identifier","text":"token"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1token\/fragments","op":"replace"},{"value":"MCPublisherCredentials","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title"},{"value":[{"kind":"identifier","text":"MCPublisherCredentials"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}