{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStatsReport"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"report"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"report","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Stats report object. Contains various different stats. Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)"},{"type":"text","text":" to extract statistics of different types like "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"},{"type":"text","text":" for example."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcdelegate\/onstatsreport(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdelegate\/onstatsreport(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onStatsReport(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a new RTC statistics report has been collected. You must enable statistics via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)"},{"type":"text","text":" "},{"type":"text","text":"to start receiving this handler."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onStatsReport:"}],"role":"symbol","title":"onStatsReport(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStatsReport"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCDelegate(im)onStatsReport:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"enableStats:completionHandler:"}],"role":"symbol","title":"enableStats(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables or disables the collection and reporting of real-time"},{"type":"text","text":" "},{"type":"text","text":"statistics associated with streaming sessions."},{"type":"text","text":" "},{"type":"text","text":"The statistics are collected once the client is either publishing or subscribed."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"role":"symbol","title":"MCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsReport"}],"abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"url":"\/documentation\/millicastsdk\/mcstatsreport"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"url":"\/documentation\/millicastsdk\/mcdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStatsOf(_:)":{"role":"symbol","title":"getStatsOf(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStatsOf"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Retrieves an array of MCStats objects from the report that match a specified MCStatsType."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStatsOfType:"}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onStatsReport(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onStatsReport:"}],"role":"symbol","title":"onStatsReport(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStatsReport"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a new RTC statistics report has been collected. You must enable statistics via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)"},{"type":"text","text":" "},{"type":"text","text":"to start receiving this handler."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onStatsReport(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onstatsreport(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"role":"symbol","title":"MCCodecsStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecsStats"}],"abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"url":"\/documentation\/millicastsdk\/mccodecsstats"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onStatsReport:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStatsReport:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onStatsReport:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"report"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","value":"enableStats:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableStats:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","value":"MCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/title","value":"getStatsOfType:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStatsOfType:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onStatsReport(_:)\/title","value":"onStatsReport:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onStatsReport(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStatsReport:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","value":[{"kind":"identifier","text":"MCCodecsStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}