{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstats\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstats\/type"]}],"abstract":[{"type":"text","text":"The type of statistics."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/type"},"sections":[],"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"type","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"externalID":"c:objc(cs)MCStats(py)type"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStats/type":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The type of statistics."}],"url":"\/documentation\/millicastsdk\/mcstats\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/type","title":"type"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Different types of statistics."}],"url":"\/documentation\/millicastsdk\/mcstatstype","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","title":"MCStatsType"},"https://w3c.github.io/webrtc-stats/#introduction":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","type":"link","titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStats"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"url":"\/documentation\/millicastsdk\/mcstats","navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","title":"MCStats"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"type","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","text":"MCStatsType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MCStatsType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"kind":"identifier","text":"MCStatsType"}],"op":"replace"},{"op":"replace","value":"MCStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments","value":[{"text":"MCStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}