{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccorevideosource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccorevideosource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"title":"MCCoreVideoSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCCoreVideoSource","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSource"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:withTimestamp:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/stopCapture()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/stopCapture()":{"role":"symbol","title":"stopCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops capturing video."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/stopCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/stopcapture()"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/startCapture()":{"role":"symbol","title":"startCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Starts capture. Effectively creates a video track that can be added to the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/startCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/startcapture()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource":{"role":"symbol","title":"MCSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}],"abstract":[{"type":"text","text":"Gathers information about the source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"url":"\/documentation\/millicastsdk\/mcsource"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/isCapturing()":{"role":"symbol","title":"isCapturing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Query whether the source is currently capturing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/isCapturing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCapturing"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/iscapturing()"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/onPixelBuffer(_:withTimestamp:)":{"role":"symbol","title":"onPixelBuffer(_:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPixelBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source along with a timestamp."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:withTimestamp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPixelBuffer:withTimestamp:"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"role":"symbol","title":"MCCoreVideoSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCoreVideoSource"}],"url":"\/documentation\/millicastsdk\/mccorevideosource"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/onPixelBuffer(_:)":{"role":"symbol","title":"onPixelBuffer(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPixelBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CVPixelBuffer","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source."},{"type":"text","text":" "},{"type":"text","text":"This API does not copy the CVPixelBuffer if using H.264, which is hardware accelerated on Apple platforms."},{"type":"text","text":" "},{"type":"text","text":"If using codecs other than H.264, an internal copy of the frame will occur."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onPixelBuffer:"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:)"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCCoreVideoSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCCoreVideoSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:withTimestamp:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/stopCapture()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","preciseIdentifier":"c:objc(cs)MCSource","text":"MCSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1stopCapture()\/title","value":"stopCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1stopCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1startCapture()\/title","value":"startCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1startCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"kind":"identifier","text":"MCSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1isCapturing()\/title","value":"isCapturing"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1isCapturing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCapturing"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:withTimestamp:)\/title","value":"onPixelBuffer:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPixelBuffer:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title","value":"MCCoreVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","value":[{"kind":"identifier","text":"MCCoreVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:)\/title","value":"onPixelBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPixelBuffer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}