{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCustomAudioSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccustomaudiosource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccustomaudiosource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCustomAudioSource"}],"title":"MCCustomAudioSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCCustomAudioSource","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCCustomAudioSource"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/stopCapture()"]}],"references":{"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"role":"symbol","title":"MCCustomAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCustomAudioSource"}],"abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCustomAudioSource"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"role":"symbol","title":"onAudioFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAudioFrame:"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource":{"role":"symbol","title":"MCSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}],"abstract":[{"type":"text","text":"Gathers information about the source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"url":"\/documentation\/millicastsdk\/mcsource"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/startCapture()":{"role":"symbol","title":"startCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Starts capture. Effectively creates an audio track that can be added to the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/startCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/startcapture()"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/stopCapture()":{"role":"symbol","title":"stopCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the underlying audio tracks and informs the SDK to stop any pending operations related to this custom source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/stopCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/stopcapture()"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/isCapturing()":{"role":"symbol","title":"isCapturing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Query whether the source is currently capturing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/isCapturing()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isCapturing"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/iscapturing()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCCustomAudioSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCCustomAudioSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCCustomAudioSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/stopCapture()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCustomAudioSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","preciseIdentifier":"c:objc(cs)MCSource","text":"MCSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title","value":"MCCustomAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments","value":[{"kind":"identifier","text":"MCCustomAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","value":"onAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"kind":"identifier","text":"MCSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1startCapture()\/title","value":"startCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1startCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1stopCapture()\/title","value":"stopCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1stopCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1isCapturing()\/title","value":"isCapturing"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1isCapturing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCapturing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}