{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mclayerdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mclayerdata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"title":"MCLayerData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCLayerData","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/layerResolution","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/temporalLayerId"]}],"references":{"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/temporalLayerId":{"role":"symbol","title":"temporalLayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"temporalLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The temporal layer id of the SVC layer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/temporalLayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"temporalLayerId"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/temporallayerid"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/layerResolution":{"role":"symbol","title":"layerResolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerResolution","preciseIdentifier":"c:objc(cs)MCLayerResolution"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The resolution of frames in the layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/layerResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerResolution"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/layerresolution"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/spatialLayerId":{"role":"symbol","title":"spatialLayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spatialLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The spatial layer id of a SVC layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/spatialLayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"spatialLayerId"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/spatiallayerid"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/encodingId":{"role":"symbol","title":"encodingId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodingId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The encoding id of the simulcast\/SVC layer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/encodingId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodingId"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/encodingid"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData":{"role":"symbol","title":"MCLayerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}],"url":"\/documentation\/millicastsdk\/mclayerdata"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/maxSpatialLayerId":{"role":"symbol","title":"maxSpatialLayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSpatialLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The maximum spatial layer to be used. Set by app."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxSpatialLayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxSpatialLayerId"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/maxspatiallayerid"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/bitrate":{"role":"symbol","title":"bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The bitrate of the SVC layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/bitrate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/bitrate"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/maxTemporalLayerId":{"role":"symbol","title":"maxTemporalLayerId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxTemporalLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The maximum temporal layer to be used. Set by app."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxTemporalLayerId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxTemporalLayerId"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/maxtemporallayerid"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCLayerData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/layerResolution","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/temporalLayerId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1temporalLayerId\/title","value":"temporalLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1temporalLayerId\/fragments","value":[{"kind":"identifier","text":"temporalLayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1layerResolution\/title","value":"layerResolution"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1layerResolution\/fragments","value":[{"kind":"identifier","text":"layerResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1spatialLayerId\/title","value":"spatialLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1spatialLayerId\/fragments","value":[{"kind":"identifier","text":"spatialLayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1encodingId\/title","value":"encodingId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1encodingId\/fragments","value":[{"kind":"identifier","text":"encodingId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/title","value":"MCLayerData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1maxSpatialLayerId\/title","value":"maxSpatialLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1maxSpatialLayerId\/fragments","value":[{"kind":"identifier","text":"maxSpatialLayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1bitrate\/title","value":"bitrate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1bitrate\/fragments","value":[{"kind":"identifier","text":"bitrate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1maxTemporalLayerId\/title","value":"maxTemporalLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1maxTemporalLayerId\/fragments","value":[{"kind":"identifier","text":"maxTemporalLayerId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}