{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","preciseIdentifier":"c:objc(pl)MCDelegate","text":"MCDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MCPublisherDelegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onActive()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onInactive()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onPublishing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onInactive()":{"navigatorTitle":[{"kind":"identifier","text":"onInactive"}],"role":"symbol","title":"onInactive()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInactive"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the last viewer stops viewing the stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onInactive()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/oninactive()"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"url":"\/documentation\/millicastsdk\/mcdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onTransformableFrame(_:withSsrc:withTimestamp:)":{"navigatorTitle":[{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}],"role":"symbol","title":"onTransformableFrame(_:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after a frame has been encoded if you need to add data"},{"type":"text","text":" "},{"type":"text","text":"to this frame before the frame is passed to the RTP packetizer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onPublishing()":{"navigatorTitle":[{"kind":"identifier","text":"onPublishing"}],"role":"symbol","title":"onPublishing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onPublishing"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the stream is currently publishing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onPublishing()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/onpublishing()"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onActive()":{"navigatorTitle":[{"kind":"identifier","text":"onActive"}],"role":"symbol","title":"onActive()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onActive"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the first viewer is viewing the stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onActive()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/onactive()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onActive()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onInactive()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onPublishing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"MCDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onInactive()\/title","value":"onInactive"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onInactive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInactive"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/title","value":"onTransformableFrame:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onPublishing()\/title","value":"onPublishing"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onPublishing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPublishing"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onActive()\/title","value":"onActive"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onActive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onActive"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}