{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"getCredentialsWithCompletionHandler(_:)","navigatorTitle":[{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCredentialsWithCompletionHandler","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCPublisherCredentials","kind":"typeIdentifier","text":"MCPublisherCredentials"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(cs)MCPublisher(im)getCredentialsWithCompletionHandler:","role":"symbol"},"abstract":[{"type":"text","text":"Returns the current publisher credentials."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/getCredentialsWithCompletionHandler(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/getcredentialswithcompletionhandler(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/getcredentialswithcompletionhandler(_:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCredentialsWithCompletionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisherCredentials","text":"MCPublisherCredentials"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the result is ready."}]}],"name":"completionHandler"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/getCredentialsWithCompletionHandler(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/getCredentialsWithCompletionHandler(_:)","title":"getCredentialsWithCompletionHandler(_:)","abstract":[{"type":"text","text":"Returns the current publisher credentials."}],"role":"symbol","navigatorTitle":[{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCredentialsWithCompletionHandler","kind":"identifier"},{"text":"((","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCPublisherCredentials","text":"MCPublisherCredentials","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/getcredentialswithcompletionhandler(_:)","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","title":"MCPublisherCredentials","abstract":[{"text":"The Credentials interface represents the credentials required for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connecting the publisher to the streaming platform and publishing a stream."},{"type":"text","text":" "},{"type":"text","text":"Refer to the "},{"isActive":true,"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html"},{"text":" for this information.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisherCredentials"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherCredentials"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublishercredentials","kind":"symbol"},"https://dash.millicast.com/docs.html":{"identifier":"https:\/\/dash.millicast.com\/docs.html","title":"streaming dashboard","url":"https:\/\/dash.millicast.com\/docs.html","type":"link","titleInlineContent":[{"type":"text","text":"streaming dashboard"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"getCredentialsWithCompletionHandler:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials","text":"MCPublisherCredentials","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"getCredentialsWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1getCredentialsWithCompletionHandler(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1getCredentialsWithCompletionHandler(_:)\/fragments","op":"replace"},{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title","value":"MCPublisherCredentials","op":"replace"},{"value":[{"kind":"identifier","text":"MCPublisherCredentials"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments","op":"replace"}]}]}