{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publishWithCompletionHandler:"}],"externalID":"c:objc(cs)MCPublisher(im)publishWithCompletionHandler:","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publish"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"publish(completionHandler:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/publish(completionhandler:)"]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/publish(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/publish(completionHandler:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"abstract":[{"text":"Initiates the process of publishing streams to the streaming platform.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Prior to calling this method, you must use the "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","type":"reference","isActive":true},{"text":"or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","type":"reference"},{"type":"text","text":" method to connect the publisher to the platform."},{"text":" ","type":"text"},{"type":"text","text":"When publishing, the SDK sets the AVAudioSession to the playAndRecord"},{"type":"text","text":" "},{"text":"category, with voiceChat mode and allowBluetooth option. If desired, the application","type":"text"},{"type":"text","text":" "},{"type":"text","text":"can configure the AVAudioSession with its own settings."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"publish","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Invoked when the result is ready.","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/publish(completionHandler:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Initiates the process of publishing streams to the streaming platform."},{"type":"text","text":" "},{"type":"text","text":"Prior to calling this method, you must use the "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","isActive":true,"type":"reference"},{"type":"text","text":"or "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","type":"reference","isActive":true},{"text":" method to connect the publisher to the platform.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When publishing, the SDK sets the AVAudioSession to the playAndRecord"},{"text":" ","type":"text"},{"text":"category, with voiceChat mode and allowBluetooth option. If desired, the application","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"can configure the AVAudioSession with its own settings."}],"navigatorTitle":[{"text":"publishWithCompletionHandler:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/publish(completionHandler:)","role":"symbol","title":"publish(completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/publish(completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/connect(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcclient\/connect(completionhandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connect"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"connectWithCompletionHandler:"}],"abstract":[{"text":"Connects and opens a websocket connection with the Millicast platform.  You must set valid credentials before using this method.","type":"text"}],"title":"connect(completionHandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","required":true,"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/connect(withWebsocketUrl:jwt:completionHandler:)":{"kind":"symbol","abstract":[{"text":"Connects to the media server directly using the websocket URL and the JSON Web Token.","type":"text"}],"type":"topic","required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:completionHandler:"}],"title":"connect(withWebsocketUrl:jwt:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withWebsocketUrl","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"jwt","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"publishWithCompletionHandler:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"publishWithCompletionHandler:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"publishWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"publishWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1publish(completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publishWithCompletionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1publish(completionHandler:)\/fragments","op":"replace"},{"value":"connectWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"connectWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/title","value":"connectWithWebsocketUrl:jwt:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace","value":"MCPublisher"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}