{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/setCredentials(_:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCredentials"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"credentials"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","text":"MCSubscriberCredentials","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"credentials","content":[{"inlineContent":[{"type":"text","text":"The credentials."}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Handler invoked when the result is ready."}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"role":"symbol","title":"setCredentials(_:completionHandler:)","roleHeading":"Instance Method","externalID":"c:objc(cs)MCSubscriber(im)setCredentials:completionHandler:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setCredentials:completionHandler:"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCredentials"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/setcredentials(_:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/setcredentials(_:completionhandler:)"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"kind":"symbol","abstract":[{"type":"text","text":"Sets the credentials, providing authentication information required for connecting to the streaming platform."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/setCredentials(_:completionHandler:)":{"type":"topic","title":"setCredentials(_:completionHandler:)","abstract":[{"type":"text","text":"Sets the credentials, providing authentication information required for connecting to the streaming platform."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCredentials","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/setcredentials(_:completionhandler:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/setCredentials(_:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"setCredentials:completionHandler:"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","kind":"symbol","abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"type":"text","text":" "},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberCredentials","kind":"identifier"}],"title":"MCSubscriberCredentials","url":"\/documentation\/millicastsdk\/mcsubscribercredentials","navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"title":"MCSubscriber","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","kind":"symbol","abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"https://dash.millicast.com/docs.html":{"title":"Streaming Dashboard","identifier":"https:\/\/dash.millicast.com\/docs.html","type":"link","titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"url":"https:\/\/dash.millicast.com\/docs.html"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setCredentials:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCredentials:completionHandler:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setCredentials:"},{"text":"(","kind":"text"},{"text":"MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"setCredentials:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1setCredentials(_:completionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1setCredentials(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCredentials:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCSubscriberCredentials"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}