{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/nv12"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nv12","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"]]},"metadata":{"title":"MCVideoType.nv12","symbolKind":"case","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"MCVideoTypeNV12","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCVideoType@MCVideoTypeNV12","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nv12","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideotype\/nv12"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/nv12"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType/nv12":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeNV12"}],"title":"MCVideoType.nv12","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/nv12","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype\/nv12","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nv12","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"title":"MCVideoType","type":"topic","url":"\/documentation\/millicastsdk\/mcvideotype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MCVideoTypeNV12","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MCVideoTypeNV12","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCVideoTypeNV12","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1nv12\/title","value":"MCVideoTypeNV12","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1nv12\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeNV12"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments","op":"replace","value":[{"text":"MCVideoType","kind":"identifier"}]}]}]}