{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pixelBuffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CVPixelBufferRef","text":"CVPixelBuffer","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withTimestamp","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"pixelBuffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A CVPixelBufferRef. The reference will be retained\/decremented internally."}]}]},{"name":"timestamp","content":[{"inlineContent":[{"text":"The timestamp to the given frame. Will act as a capture timestamp.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source along with a timestamp.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:withtimestamp:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:withtimestamp:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCoreVideoSource"]]},"metadata":{"symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"onPixelBuffer:withTimestamp:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CVPixelBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"text":"!, ","kind":"text"},{"text":"withTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"text":")","kind":"text"}],"title":"onPixelBuffer(_:withTimestamp:)","role":"symbol","externalID":"c:objc(cs)MCCoreVideoSource(im)onPixelBuffer:withTimestamp:"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:withTimestamp:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCoreVideoSource":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCoreVideoSource","kind":"identifier"}],"title":"MCCoreVideoSource","url":"\/documentation\/millicastsdk\/mccorevideosource","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCCoreVideoSource","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCoreVideoSource","kind":"symbol","abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCoreVideoSource/onPixelBuffer(_:withTimestamp:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCoreVideoSource\/onPixelBuffer(_:withTimestamp:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onPixelBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CVPixelBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CVPixelBufferRef"},{"text":"!, ","kind":"text"},{"text":"withTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMTime","kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/onpixelbuffer(_:withtimestamp:)","type":"topic","navigatorTitle":[{"text":"onPixelBuffer:withTimestamp:","kind":"identifier"}],"kind":"symbol","title":"onPixelBuffer(_:withTimestamp:)","role":"symbol","abstract":[{"text":"To be called whenever the application wishes to feed a CVPixelBuffer to the source along with a timestamp.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onPixelBuffer:withTimestamp:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onPixelBuffer:withTimestamp:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onPixelBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__CVBuffer","preciseIdentifier":"c:@S@__CVBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pixelBuffer"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCoreVideoSource\/title","value":"MCCoreVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","value":[{"text":"MCCoreVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:withTimestamp:)\/title","value":"onPixelBuffer:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCoreVideoSource~1onPixelBuffer(_:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onPixelBuffer:withTimestamp:"}]}]}]}