{"kind":"symbol","abstract":[{"type":"text","text":"Ndi sources (input and output)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/ndi"]},{"paths":["\/documentation\/millicastsdk\/mcsourcetype\/ndi"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/NDI","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NDI","kind":"identifier"}],"role":"symbol","title":"MCSourceType.NDI","symbolKind":"case","externalID":"c:@E@MCSourceType@MCSourceTypeNDI","roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeNDI"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NDI"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceType"}],"title":"MCSourceType","url":"\/documentation\/millicastsdk\/mcsourcetype","abstract":[{"text":"The Source type","type":"text"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/NDI":{"title":"MCSourceType.NDI","abstract":[{"text":"Ndi sources (input and output).","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/NDI","type":"topic","navigatorTitle":[{"text":"MCSourceTypeNDI","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"NDI","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsourcetype\/ndi"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCSourceTypeNDI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSourceTypeNDI"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCSourceTypeNDI","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1NDI\/title","value":"MCSourceTypeNDI","op":"replace"},{"value":[{"text":"MCSourceTypeNDI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1NDI\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}