{"abstract":[{"type":"text","text":"Get the stream details of the session the stats belong to."}],"metadata":{"navigatorTitle":[{"text":"getStreamDetails","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStreamDetails","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCStreamDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamDetails"}],"role":"symbol","externalID":"c:objc(cs)MCStatsReport(im)getStreamDetails","title":"getStreamDetails()","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatsreport\/getstreamdetails()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstatsreport\/getstreamdetails()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStreamDetails()"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStreamDetails"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","preciseIdentifier":"c:objc(cs)MCStreamDetails","kind":"typeIdentifier","text":"MCStreamDetails"}]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This information helps correlate logs between different"},{"type":"text","text":" "},{"type":"text","text":"components (Media Server, Publisher, and Viewer) that"},{"type":"text","text":" "},{"text":"operate on the current stream session.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStreamDetails()":{"abstract":[{"type":"text","text":"Get the stream details of the session the stats belong to."}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/getstreamdetails()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getStreamDetails"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStreamDetails()","title":"getStreamDetails()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStreamDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamDetails","text":"MCStreamDetails"}],"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"url":"\/documentation\/millicastsdk\/mcstatsreport","navigatorTitle":[{"text":"MCStatsReport","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStatsReport","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"title":"MCStatsReport","kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails":{"abstract":[{"type":"text","text":"A type erased stream details class. A holder"},{"type":"text","text":" "},{"type":"text","text":"For either Stream Publish Details or Stream View Details."},{"text":" ","type":"text"},{"text":"This class contains the current streaming","type":"text"},{"type":"text","text":" "},{"type":"text","text":"session identifying information. Used to correlate"},{"type":"text","text":" "},{"text":"debugging info with a particular streaming session.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcstreamdetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStreamDetails"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","title":"MCStreamDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStreamDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getStreamDetails"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"getStreamDetails","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","preciseIdentifier":"c:objc(cs)MCStreamDetails","kind":"typeIdentifier","text":"MCStreamDetails"},{"kind":"text","text":" *) "},{"text":"getStreamDetails","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getStreamDetails","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStreamDetails()\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStreamDetails()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getStreamDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","value":"MCStatsReport"},{"value":[{"text":"MCStatsReport","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/title","value":"MCStreamDetails","op":"replace"},{"op":"replace","value":[{"text":"MCStreamDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/fragments"}]}]}