{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive http errors"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/httperrorpublisher()"]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpErrorPublisher()","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","title":"httpErrorPublisher()","symbolKind":"method","externalID":"s:So11MCPublisherC12MillicastSDKE18httpErrorPublisher7Combine03AnyF0VySo016MCHTTPConnectionE0Cs5NeverOGyF","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"title":"MCPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCHTTPConnectionError":{"navigatorTitle":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"type":"text","text":" "},{"type":"text","text":"connection to the millicast service"}],"title":"MCHTTPConnectionError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCHTTPConnectionError","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mchttpconnectionerror","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCHTTPConnectionError","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/httpErrorPublisher()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCHTTPConnectionError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/httperrorpublisher()","abstract":[{"text":"Get a Combine based publisher that can be used to receive http errors","type":"text"}],"role":"symbol","title":"httpErrorPublisher()","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpErrorPublisher()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title"},{"op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCPublisher"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/navigatorTitle"},{"op":"replace","value":"MCHTTPConnectionError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title"},{"op":"replace","value":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCHTTPConnectionError\/navigatorTitle"}]}]}