{"abstract":[{"text":"Gets the unique identifier of the source.","type":"text"}],"metadata":{"title":"getUniqueId()","navigatorTitle":[{"kind":"identifier","text":"getUniqueId"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUniqueId","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"symbolKind":"method","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCSource(im)getUniqueId","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsource\/getuniqueid()"]},{"paths":["\/documentation\/millicastsdk\/mcsource\/getuniqueid()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getUniqueId()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getUniqueId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the source.","type":"text"}]}],"kind":"content"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSource/getUniqueId()":{"abstract":[{"text":"Gets the unique identifier of the source.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUniqueId","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"url":"\/documentation\/millicastsdk\/mcsource\/getuniqueid()","role":"symbol","navigatorTitle":[{"text":"getUniqueId","kind":"identifier"}],"title":"getUniqueId()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getUniqueId()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource":{"url":"\/documentation\/millicastsdk\/mcsource","role":"symbol","title":"MCSource","abstract":[{"type":"text","text":"Gathers information about the source."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSource","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MCSource","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getUniqueId","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getUniqueId","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"getUniqueId","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getUniqueId()\/title","op":"replace","value":"getUniqueId"},{"value":[{"text":"- ","kind":"text"},{"text":"getUniqueId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getUniqueId()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"text":"MCSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}