{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"echo_return_loss_enhancement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"echo_return_loss_enhancement","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"title":"echo_return_loss_enhancement","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"echo_return_loss_enhancement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCAudioSourceStats(py)echo_return_loss_enhancement","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss_enhancement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss_enhancement"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss_enhancement"},"sections":[],"abstract":[{"text":"The improvement in echo cancellation performance. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats":{"type":"topic","title":"MCAudioSourceStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSourceStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcestats","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MCAudioSourceStats","kind":"identifier"}],"abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats/echo_return_loss_enhancement":{"title":"echo_return_loss_enhancement","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"echo_return_loss_enhancement","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss_enhancement","abstract":[{"text":"The improvement in echo cancellation performance. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"echo_return_loss_enhancement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss_enhancement"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-echoreturnlossenhancement":{"title":"echoReturnLossEnhancement","titleInlineContent":[{"text":"echoReturnLossEnhancement","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement","type":"link"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"echo_return_loss_enhancement","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"echo_return_loss_enhancement","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"echo_return_loss_enhancement"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCAudioSourceStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioSourceStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","op":"replace"},{"value":[{"text":"MCAudioSourceStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/navigatorTitle","op":"replace"},{"value":"echo_return_loss_enhancement","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss_enhancement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"echo_return_loss_enhancement"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss_enhancement\/fragments","op":"replace"}]}]}