{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_samples_duration"},"metadata":{"title":"total_samples_duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_samples_duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"total_samples_duration","kind":"identifier"}],"externalID":"c:objc(cs)MCAudioSourceStats(py)total_samples_duration"},"abstract":[{"text":"The total duration of audio samples processed. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/total_samples_duration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/total_samples_duration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_samples_duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats":{"type":"topic","title":"MCAudioSourceStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSourceStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcestats","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MCAudioSourceStats","kind":"identifier"}],"abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-totalsamplesduration":{"title":"totalSamplesDuration","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration","type":"link","titleInlineContent":[{"type":"text","text":"totalSamplesDuration"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats/total_samples_duration":{"title":"total_samples_duration","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_samples_duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"total_samples_duration","kind":"identifier"}],"abstract":[{"text":"The total duration of audio samples processed. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration","isActive":true,"type":"reference"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_samples_duration","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/total_samples_duration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"total_samples_duration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"total_samples_duration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_samples_duration"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","value":"MCAudioSourceStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","value":[{"kind":"identifier","text":"MCAudioSourceStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/navigatorTitle","value":[{"text":"MCAudioSourceStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_samples_duration\/title","value":"total_samples_duration","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_samples_duration\/fragments","value":[{"kind":"identifier","text":"total_samples_duration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}