{"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code"]]},"abstract":[{"text":"Allow one to match an error code against an arbitrary error.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/~=(_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/~=(_:_:)"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"MillicastSDK","relatedModules":["Foundation"]}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"~=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"extendedModule":"Foundation","roleHeading":"Operator","title":"~=(_:_:)","externalID":"s:10Foundation18_ErrorCodeProtocolPAAE2teoiySbx_s0B0_ptFZ::SYNTHESIZED::c:@E@MCInternalSDKError","symbolKind":"op","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.10","deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"introducedAt":"9.0","deprecated":false},{"name":"watchOS","unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"~="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"match"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInternalSDKError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCInternalSDKError","kind":"identifier"}],"abstract":[],"title":"MCInternalSDKError","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/~=(_:_:)":{"url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/~=(_:_:)","title":"~=(_:_:)","abstract":[{"type":"text","text":"Allow one to match an error code against an arbitrary error."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/~=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"~=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error category for unidentified errors. Usually representing a bug."}],"title":"MCInternalSDKError.Code","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCInternalSDKError","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/title"},{"value":[{"kind":"identifier","text":"MCInternalSDKError"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/fragments"},{"value":[{"text":"MCInternalSDKError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/navigatorTitle"}]}]}