{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReportPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/statsreportpublisher"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/statsReportPublisher","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get Combine based publisher that can be used to receive stats reports."}],"kind":"symbol","metadata":{"role":"symbol","title":"statsReportPublisher","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReportPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"symbolKind":"property","externalID":"s:So11MCPublisherC12MillicastSDKE20statsReportPublisher7Combine03AnyF0VySo07MCStatsE0Cs5NeverOGvp","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/statsReportPublisher":{"role":"symbol","title":"statsReportPublisher","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReportPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Get Combine based publisher that can be used to receive stats reports."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/statsReportPublisher","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/statsreportpublisher"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"role":"symbol","title":"MCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsReport"}],"abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"url":"\/documentation\/millicastsdk\/mcstatsreport"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"role":"symbol","title":"MCPublisher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"url":"\/documentation\/millicastsdk\/mcpublisher"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","value":"MCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}