{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MCAudioPlayback","kind":"typeIdentifier","text":"MCAudioPlayback"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"build","kind":"identifier"}],"externalID":"c:objc(cs)MCAudioPlaybackBuilder(im)build","title":"build()","role":"symbol","symbolKind":"method"},"abstract":[{"type":"text","text":"Builds the AudioPlayback class."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplaybackbuilder\/build()"]},{"paths":["\/documentation\/millicastsdk\/mcaudioplaybackbuilder\/build()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCAudioPlayback","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","preciseIdentifier":"c:objc(cs)MCAudioPlayback","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Returns a new audio playback device."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder\/build()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlaybackBuilder/build()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCAudioPlayback","text":"MCAudioPlayback","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"build"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplaybackbuilder\/build()","abstract":[{"type":"text","text":"Builds the AudioPlayback class."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder\/build()","role":"symbol","title":"build()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlaybackBuilder":{"title":"MCAudioPlaybackBuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioPlaybackBuilder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplaybackbuilder","abstract":[{"type":"text","text":"Responsible for building AudioPlayback."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayback","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","type":"topic","role":"symbol","abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"type":"text","text":" "},{"text":"This class inherits the Source class, however this is not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayback","kind":"identifier"}],"title":"MCAudioPlayback"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"build","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"typeIdentifier","text":"MCAudioPlayback","preciseIdentifier":"c:objc(cs)MCAudioPlayback"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder~1build()\/title","value":"build","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder~1build()\/fragments"},{"op":"replace","value":"MCAudioPlaybackBuilder","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/fragments","value":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"op":"replace"},{"value":"MCAudioPlayback","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","op":"replace","value":[{"text":"MCAudioPlayback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}