{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/midpublisher()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"midPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"an AnyPublisher","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Refer to ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"for more information","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"Create a Combine based publisher that is invoked whenever the underlying mid gets","type":"text"},{"text":" ","type":"text"},{"text":"updated.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/midPublisher()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"midPublisher()","externalID":"s:So19MCWebrtcRemoteTrackC12MillicastSDKE12midPublisher7Combine03AnyG0VySSSgs5NeverOGyF","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","extendedModule":"MillicastSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"midPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"abstract":[{"type":"text","text":"The webrtc logical track."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","role":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack/midPublisher()":{"role":"symbol","type":"topic","title":"midPublisher()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/midPublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"midPublisher"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Create a Combine based publisher that is invoked whenever the underlying mid gets"},{"type":"text","text":" "},{"type":"text","text":"updated."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/midpublisher()","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrack(_:didUpdateMID:)":{"role":"symbol","kind":"symbol","type":"topic","title":"webrtcRemoteTrack(_:didUpdateMID:)","abstract":[{"text":"The event for updating the MID of the internal webrtc track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)","required":true,"navigatorTitle":[{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webrtcRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"text":", ","kind":"text"},{"text":"didUpdateMID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","value":"MCWebrtcRemoteTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/title","value":"webrtcRemoteTrack:didUpdateMID:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}]}]}]}