{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"audioTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"videoTrack","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video track to add."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the result is ready."}]}]}]}],"abstract":[{"type":"text","text":"Adds an audio track to the publisher. See "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","isActive":true},{"type":"text","text":" as an example"},{"type":"text","text":" "},{"type":"text","text":"for capturing an audio device track."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCPublisher(im)addTrackWithAudioTrack:completionHandler:","roleHeading":"Instance Method","symbolKind":"method","title":"addTrack(with:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCAudioTrack","text":"MCAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioTrack":{"kind":"symbol","navigatorTitle":[{"text":"MCAudioTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack","title":"MCAudioTrack","role":"symbol","abstract":[{"text":"Manages and plays a single audio resource.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioTrack","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-340my":{"navigatorTitle":[{"text":"addTrackWithAudioTrack:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","kind":"symbol","title":"addTrack(with:completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my","abstract":[{"text":"Adds an audio track to the publisher. See ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","isActive":true,"type":"reference"},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing an audio device track.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource/startCapture()":{"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()","abstract":[{"type":"text","text":"Initiates the audio capture process from the current source."}],"role":"symbol","title":"startCapture()","navigatorTitle":[{"text":"startCapture","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"title":"MCPublisher","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addTrackWithAudioTrack:completionHandler:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addTrackWithAudioTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack","text":"MCAudioTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"audioTrack"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCAudioTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack\/fragments"},{"op":"replace","value":"addTrackWithAudioTrack:completionHandler:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithAudioTrack:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/fragments"},{"op":"replace","value":"startCapture","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments"},{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title"},{"op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}