{"abstract":[{"type":"text","text":"Set the stereo pan if applicable. This property will apply panning if"},{"text":" ","type":"text"},{"text":"the played audio is in stereo. Valid values are -1 to 1","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration\/pan"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration\/pan"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)MCAudioConfiguration(py)pan","modules":[{"name":"MillicastSDK"}],"title":"pan","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pan"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"pan"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pan","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration\/pan","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioConfiguration/pan":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pan"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pan"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"deprecated":true,"title":"pan","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration\/pan","kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioconfiguration\/pan","type":"topic","abstract":[{"type":"text","text":"Set the stereo pan if applicable. This property will apply panning if"},{"type":"text","text":" "},{"type":"text","text":"the played audio is in stereo. Valid values are -1 to 1"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"MCAudioConfiguration"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioConfiguration"}],"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioconfiguration","abstract":[{"type":"text","text":"Global Audio Configuration object."}],"role":"symbol","title":"MCAudioConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"pan"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"pan"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"pan"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration~1pan\/title","value":"pan","op":"replace"},{"value":[{"text":"pan","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration~1pan\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration\/title","op":"replace","value":"MCAudioConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioConfiguration"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration\/fragments"}]}]}