{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/statsDelayMs","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The rate at which you want to receive reports with statistics in milliseconds. Defaults to 1 second."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/statsdelayms"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/statsdelayms"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"statsDelayMs"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsDelayMs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"externalID":"c:objc(cs)MCClientOptions(py)statsDelayMs","title":"statsDelayMs","symbolKind":"property"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"url":"\/documentation\/millicastsdk\/mcclientoptions","kind":"symbol","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"type":"topic","title":"MCClientOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/statsDelayMs":{"kind":"symbol","abstract":[{"type":"text","text":"The rate at which you want to receive reports with statistics in milliseconds. Defaults to 1 second."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/statsDelayMs","type":"topic","title":"statsDelayMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/statsdelayms","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsDelayMs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"statsDelayMs","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"statsDelayMs","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"statsDelayMs"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsDelayMs"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1statsDelayMs\/title","value":"statsDelayMs","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1statsDelayMs\/fragments","value":[{"text":"statsDelayMs","kind":"identifier"}],"op":"replace"}]}]}