{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/activity()"]}],"abstract":[{"type":"text","text":"Create an AsyncStream to receive track activity events"}],"kind":"symbol","metadata":{"title":"activity()","roleHeading":"Instance Method","extendedModule":"MillicastSDK","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE8activityScSyAbCE13ActivityEventOGyF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activity"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:So16MCRTSRemoteTrackC12MillicastSDKE13ActivityEventO","text":"ActivityEvent"},{"text":">","kind":"text"}],"role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activity()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/ActivityEvent","text":"ActivityEvent","preciseIdentifier":"s:So16MCRTSRemoteTrackC12MillicastSDKE13ActivityEventO"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a new AsyncStream that receives track activity."}]}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Refer to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)"},{"type":"text","text":" "},{"type":"text","text":"and "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)","type":"reference"},{"type":"text","text":" "},{"type":"text","text":"for more information."}],"type":"paragraph"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/activity()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:So16MCRTSRemoteTrackC12MillicastSDKE13ActivityEventO","text":"ActivityEvent"},{"text":">","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/activity()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activity()","title":"activity()","role":"symbol","abstract":[{"type":"text","text":"Create an AsyncStream to receive track activity events"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackActive(_:)":{"navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrackActive:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","type":"topic","kind":"symbol","required":true,"abstract":[{"text":"Event received when the track, i.e. it’s publishing source, has become active.","type":"text"},{"text":" ","type":"text"},{"text":"In other words the stream is being sent to the server and is viable on the viewing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"client. The track is not enabled by default. The application can still call"},{"type":"text","text":" "},{"text":"disable() on this track to prevent it from being played. If the track","type":"text"},{"text":" ","type":"text"},{"text":"was previously disabled, the application must call enable() for the track","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to be renderable. If the track was previously enabled by the application and is not"},{"text":" ","type":"text"},{"text":"disabled by the application it will automatically start playing once it becomes","type":"text"},{"type":"text","text":" "},{"text":"active.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackActive","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackactive(_:)","title":"rtsRemoteTrackActive(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"type":"text","text":" "},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/ActivityEvent":{"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/activityevent","type":"topic","abstract":[{"text":"Track activity event","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/ActivityEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActivityEvent","kind":"identifier"}],"title":"MCRTSRemoteTrack.ActivityEvent","navigatorTitle":[{"kind":"identifier","text":"ActivityEvent"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackInactive(_:)":{"navigatorTitle":[{"text":"rtsRemoteTrackInactive:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Event received when the track, i.e. it’s publishing source, has become inactive."},{"text":" ","type":"text"},{"text":"In other words the publishers stream is no longer being sent to the server and is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"thus no longer viewable on the viewing client. The track is not disabled by the SDK"},{"type":"text","text":" "},{"text":"when this event occurs. If the application wants to ensure the track will not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"automatically be played once the source becomes active it should call disable() when"},{"text":" ","type":"text"},{"text":"receiving this event. Then it is responsible for calling enable() on the Active event.","type":"text"},{"text":" ","type":"text"},{"text":"If the application does not disable on Inactive event, the track will automatically start","type":"text"},{"type":"text","text":" "},{"text":"playing when the remote source becomes Active.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrackInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackinactive(_:)","title":"rtsRemoteTrackInactive(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"rtsRemoteTrackActive:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrackActive:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","value":"MCRTSRemoteTrack","op":"replace"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/title","op":"replace","value":"rtsRemoteTrackInactive:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrackInactive:","kind":"identifier"}]}]}]}