{"sections":[],"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned."}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"asAudio","kind":"identifier"}],"title":"asAudio()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asAudio"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","kind":"typeIdentifier","text":"MCRTSRemoteAudioTrack"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)MCRTSRemoteTrack(im)asAudio"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asAudio()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/asaudio()"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/asaudio()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asAudio"},{"text":"() -> ","kind":"text"},{"text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"Nil if the track is not of an audio type","type":"text"}]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"type":"text","text":" "},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/asAudio()":{"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/asaudio()","abstract":[{"type":"text","text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"asAudio"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asAudio()","title":"asAudio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asAudio"},{"text":"() -> ","kind":"text"},{"text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteAudioTrack":{"title":"MCRTSRemoteAudioTrack","url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","abstract":[{"text":"The RTS logical track’s audio interface.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"asAudio","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asAudio"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"asAudio"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","value":"MCRTSRemoteTrack","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asAudio()\/title","value":"asAudio","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asAudio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asAudio"}],"op":"replace"},{"value":"MCRTSRemoteAudioTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}