{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disable"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"text":"Invoked when the asynchronous operation finishes.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCRTSRemoteTrack(im)disableWithCompletionHandler:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disable"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"disable(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"disableWithCompletionHandler:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/disable(completionHandler:)"},"abstract":[{"text":"Disable the track. This makes the track stop receiving events\/media.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/disable(completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/disable(completionhandler:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/disable(completionHandler:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disable","kind":"identifier"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/disable(completionhandler:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/disable(completionHandler:)","abstract":[{"type":"text","text":"Disable the track. This makes the track stop receiving events\/media."}],"kind":"symbol","title":"disable(completionHandler:)","navigatorTitle":[{"text":"disableWithCompletionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"type":"text","text":" "},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"disableWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disableWithCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableWithCompletionHandler:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1disable(completionHandler:)\/title","value":"disableWithCompletionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1disable(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"disableWithCompletionHandler:"}],"op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}