{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isActive"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","title":"isActive","role":"symbol","externalID":"c:objc(cs)MCRTSRemoteTrack(py)isActive","navigatorTitle":[{"kind":"identifier","text":"isActive"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isActive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/isactive"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/isactive"]}],"abstract":[{"text":"Whether the track is currently active.","type":"text"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/isActive","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/isActive":{"title":"isActive","role":"symbol","kind":"symbol","abstract":[{"text":"Whether the track is currently active.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/isActive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isActive","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/isactive","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"type":"text","text":" "},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"isActive","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"isActive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isActive","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"isActive","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1isActive\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1isActive\/fragments","value":[{"text":"isActive","kind":"identifier"}],"op":"replace"},{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}]}]}]}