{"metadata":{"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE5statsScSySo12MCTrackStatsCGyF","extendedModule":"MillicastSDK","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stats"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCTrackStats","kind":"typeIdentifier","text":"MCTrackStats"},{"kind":"text","text":">"}],"modules":[{"name":"MillicastSDK"}],"title":"stats()","roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stats"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCTrackStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","kind":"typeIdentifier","text":"MCTrackStats"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a new AsyncStream to receive track level stats information."}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)"},{"type":"text","text":" "},{"type":"text","text":"for more information."}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/stats()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Create an AsyncStream to receive track stats."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/stats()"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats":{"role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCTrackStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCTrackStats"}],"title":"MCTrackStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","type":"topic","abstract":[],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","title":"MCRTSRemoteTrack","abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/stats()":{"role":"symbol","title":"stats()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/stats()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/stats()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stats","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCTrackStats","text":"MCTrackStats","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[{"text":"Create an AsyncStream to receive track stats.","type":"text"}],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didReceiveTrackStats:)":{"kind":"symbol","abstract":[{"text":"Event received when a new Track statistics report is available.","type":"text"}],"role":"symbol","title":"rtsRemoteTrack(_:didReceiveTrackStats:)","navigatorTitle":[{"text":"rtsRemoteTrack:didReceiveTrackStats:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTrackStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCTrackStats","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didreceivetrackstats:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"MCTrackStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCTrackStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/fragments","op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"},{"value":"rtsRemoteTrack:didReceiveTrackStats:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didReceiveTrackStats:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}