{"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"MillicastSDK"}],"role":"collectionGroup"},"topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/!=(_:_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel\/equatable-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/Equatable-Implementations"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel"]]},"kind":"article","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberStatsLevel":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"abstract":[{"text":"Enum specifying the level of verbosity for stats.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","type":"topic","title":"MCSubscriberStatsLevel"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberStatsLevel/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/!=(_:_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/!=(_:_:)","type":"topic","abstract":[],"title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/title","op":"replace","value":"MCSubscriberStatsLevel"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/fragments","op":"replace","value":[{"text":"MCSubscriberStatsLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}