{"metadata":{"title":"add(_:)","externalID":"c:objc(cs)MCAudioTrack(im)addRenderer:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","text":"MCAudioRenderer","preciseIdentifier":"c:objc(pl)MCAudioRenderer"},{"kind":"text","text":")!)"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer","text":"MCAudioRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer"},{"text":")!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio renderer to add."}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)"},"abstract":[{"text":"Adds an audio renderer to render this track.","type":"text"},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioTrack/add(_:)":{"type":"topic","title":"add(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","role":"symbol","navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Adds an audio renderer to render this track.","type":"text"},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"MCAudioRenderer","preciseIdentifier":"c:objc(pl)MCAudioRenderer","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioTrack":{"title":"MCAudioTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiotrack","navigatorTitle":[{"text":"MCAudioTrack","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Manages and plays a single audio resource.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioRenderer":{"navigatorTitle":[{"text":"MCAudioRenderer","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer","abstract":[{"type":"text","text":"This protocol can be implemented to receive audio frames from audio tracks. However,"},{"type":"text","text":" "},{"type":"text","text":"The recommended method to render audio is to use "},{"code":"MCAudioPlaback","type":"codeVoice"},{"type":"text","text":" instead."},{"type":"text","text":" "},{"type":"text","text":"See "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","type":"reference","isActive":true},{"type":"text","text":" to attach an audio renderer."}],"title":"MCAudioRenderer","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudiorenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioRenderer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addRenderer:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"addRenderer:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)MCAudioRenderer","kind":"typeIdentifier","text":"id<MCAudioRenderer>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"renderer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"renderer","content":[{"inlineContent":[{"text":"The audio renderer to add.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"addRenderer:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/fragments","op":"replace"},{"value":"MCAudioTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack\/fragments","op":"replace"},{"value":[{"text":"MCAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack\/navigatorTitle","op":"replace"},{"value":"MCAudioRenderer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer\/title","op":"replace"},{"value":[{"text":"MCAudioRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioRenderer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer\/navigatorTitle","op":"replace"}]}]}