{"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(pl)MCAudioControl(im)isMuted","title":"isMuted()","required":true,"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isMuted","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isMuted"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/isMuted()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks whether the microphone or speaker is muted or not."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isMuted","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"A boolean indicating whether the audio source is muted (true) or not (false).","type":"text"}],"type":"paragraph"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/ismuted()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/ismuted()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","kind":"symbol","abstract":[{"type":"text","text":"Manages audio settings."}],"role":"symbol","title":"MCAudioControl","navigatorTitle":[{"kind":"identifier","text":"MCAudioControl"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/isMuted()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isMuted"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"required":true,"title":"isMuted()","abstract":[{"type":"text","text":"Checks whether the microphone or speaker is muted or not."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/isMuted()","kind":"symbol","navigatorTitle":[{"text":"isMuted","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudiocontrol\/ismuted()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isMuted"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isMuted"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isMuted"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/title","value":"MCAudioControl","op":"replace"},{"value":[{"text":"MCAudioControl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1isMuted()\/title","value":"isMuted"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1isMuted()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isMuted","kind":"identifier"}]}]}]}