{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Called when the RTC Peer Connection state has changed."}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivertcpeerconnectionstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivertcpeerconnectionstate:)"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveRTCPeerConnectionState:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"client","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"client"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient","text":"MCClient","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRTCPeerConnectionState"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCConnectionState","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","text":"MCConnectionState"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast client"}]}]},{"name":"didReceiveRTCPeerConnectionState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current RTC Peer Connection state"}]}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"client:didReceiveRTCPeerConnectionState:"}],"externalID":"c:objc(pl)MCDelegate(im)client:didReceiveRTCPeerConnectionState:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)MCClient","kind":"typeIdentifier","text":"MCClient"},{"kind":"text","text":", "},{"text":"didReceiveRTCPeerConnectionState","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"client(_:didReceiveRTCPeerConnectionState:)","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","required":true,"role":"symbol","symbolKind":"method"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","role":"symbol","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"type":"text","text":" "},{"text":"events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberDelegate"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"title":"MCSubscriberDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","title":"MCClient","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcclient","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","isActive":true},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"navigatorTitle":[{"text":"MCClient","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","type":"topic","title":"MCConnectionState","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","role":"symbol","abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"text":" ","type":"text"},{"type":"text","text":"You must implement this protocol and set a delegate."},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","type":"topic","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"title":"MCPublisherDelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/client(_:didReceiveRTCPeerConnectionState:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient","text":"MCClient"},{"kind":"text","text":", "},{"text":"didReceiveRTCPeerConnectionState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":")"}],"title":"client(_:didReceiveRTCPeerConnectionState:)","required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveRTCPeerConnectionState:)","url":"\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivertcpeerconnectionstate:)","abstract":[{"type":"text","text":"Called when the RTC Peer Connection state has changed."}],"navigatorTitle":[{"kind":"identifier","text":"client:didReceiveRTCPeerConnectionState:"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"text":" ","type":"text"},{"type":"text","text":"subclassed by "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","isActive":true},{"type":"text","text":", which are the main ones to implement."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"title":"MCDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"client:didReceiveRTCPeerConnectionState:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveRTCPeerConnectionState:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<MCClient>","preciseIdentifier":"c:Qoobjc(pl)MCClient"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"client"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRTCPeerConnectionState:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","op":"replace","value":"MCSubscriberDelegate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MCClient","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title"},{"value":[{"kind":"identifier","text":"MCClient"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments"},{"value":"MCConnectionState","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"value":[{"kind":"identifier","text":"MCConnectionState"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"text":"MCPublisherDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveRTCPeerConnectionState:)\/title","op":"replace","value":"client:didReceiveRTCPeerConnectionState:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveRTCPeerConnectionState:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveRTCPeerConnectionState:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"}]}]}