{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channels","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)MCCodecsStats(py)channels","navigatorTitle":[{"text":"channels","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","title":"channels","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channels","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/channels"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/channels"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"When present, indicates the number of channels (mono=1, stereo=2). See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats\/channels"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecsStats/channels":{"type":"topic","title":"channels","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats\/channels","abstract":[{"type":"text","text":"When present, indicates the number of channels (mono=1, stereo=2). See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels","isActive":true}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/channels","navigatorTitle":[{"text":"channels","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channels","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-channels":{"titleInlineContent":[{"type":"text","text":"channels"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels","title":"channels"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecsStats":{"url":"\/documentation\/millicastsdk\/mccodecsstats","kind":"symbol","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecsStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCCodecsStats","kind":"identifier"}],"type":"topic","role":"symbol","title":"MCCodecsStats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"channels","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"channels","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:l","text":"unsigned long"},{"kind":"text","text":" "},{"kind":"identifier","text":"channels"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"channels","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats~1channels\/title"},{"op":"replace","value":[{"kind":"identifier","text":"channels"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats~1channels\/fragments"},{"value":"MCCodecsStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCCodecsStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","op":"replace"}]}]}