{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack","text":"MCVideoTrack"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"track","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track to be displayed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/attach(videotrack:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/attach(videoTrack:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the track to be displayed in this view."}],"kind":"symbol","metadata":{"role":"symbol","title":"attach(videoTrack:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12MillicastSDK17MCVideoUIViewTypePAAE6attach10videoTrackySo0cH0C_tF::SYNTHESIZED::c:@M@MillicastSDK@objc(cs)MCSampleBufferVideoUIView","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCVideoUIViewType-Implementations"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"role":"symbol","title":"MCVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoTrack"}],"abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcvideotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"role":"symbol","title":"MCSampleBufferVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/attach(videoTrack:)":{"role":"symbol","title":"attach(videoTrack:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the track to be displayed in this view."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/attach(videoTrack:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/attach(videotrack:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/MCVideoUIViewType-Implementations":{"role":"collectionGroup","title":"MCVideoUIViewType Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCVideoUIViewType-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mcvideouiviewtype-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title","value":"MCVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}