{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCustomAudioSource"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/stopcapture()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/stopcapture()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCustomAudioSource\/stopCapture()"},"abstract":[{"type":"text","text":"Stops the underlying audio tracks and informs the SDK to stop any pending operations related to this custom source."}],"metadata":{"symbolKind":"method","title":"stopCapture()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:objc(cs)MCCustomAudioSource(im)stopCapture","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"modules":[{"name":"MillicastSDK"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCustomAudioSource":{"url":"\/documentation\/millicastsdk\/mccustomaudiosource","abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"navigatorTitle":[{"text":"MCCustomAudioSource","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCustomAudioSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCustomAudioSource","kind":"identifier"}],"title":"MCCustomAudioSource","kind":"symbol","role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCustomAudioSource/stopCapture()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"abstract":[{"type":"text","text":"Stops the underlying audio tracks and informs the SDK to stop any pending operations related to this custom source."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/stopcapture()","title":"stopCapture()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCustomAudioSource\/stopCapture()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"stopCapture","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopCapture","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCCustomAudioSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCustomAudioSource\/title"},{"op":"replace","value":[{"text":"MCCustomAudioSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments"},{"op":"replace","value":"stopCapture","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCustomAudioSource~1stopCapture()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCustomAudioSource~1stopCapture()\/fragments"}]}]}