{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didreceivetrackstats:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didreceivetrackstats:)"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate"]]},"abstract":[{"type":"text","text":"Event received when a new Track statistics report is available."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveTrackStats","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"stats","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","preciseIdentifier":"c:objc(cs)MCTrackStats","text":"MCTrackStats","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote track for which a new stats is available."}]}],"name":"rtsRemoteTrack"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"You must enable statistics via ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)"},{"text":" ","type":"text"},{"text":"to start receiving this handler.","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","interfaceLanguage":"swift"},"metadata":{"title":"rtsRemoteTrack(_:didReceiveTrackStats:)","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTrackStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats","text":"MCTrackStats"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCRTSRemoteTrackDelegate(im)rtsRemoteTrack:didReceiveTrackStats:","navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didReceiveTrackStats:"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats":{"title":"MCTrackStats","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCTrackStats"}],"type":"topic","url":"\/documentation\/millicastsdk\/mctrackstats","navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"role":"symbol","title":"MCRTSRemoteTrackDelegate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didReceiveTrackStats:)":{"navigatorTitle":[{"text":"rtsRemoteTrack:didReceiveTrackStats:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"rtsRemoteTrack(_:didReceiveTrackStats:)","abstract":[{"text":"Event received when a new Track statistics report is available.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didreceivetrackstats:)","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":", ","kind":"text"},{"text":"didReceiveTrackStats","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCTrackStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"abstract":[{"text":"Enables or disables the collection and reporting of real-time","type":"text"},{"text":" ","type":"text"},{"text":"statistics associated with streaming sessions.","type":"text"},{"text":" ","type":"text"},{"text":"The statistics are collected once the client is either publishing or subscribed.","type":"text"}],"type":"topic","required":true,"kind":"symbol","title":"enableStats(_:completionHandler:)","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)","navigatorTitle":[{"text":"enableStats:completionHandler:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enableStats","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"type":"topic","abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","title":"MCRTSRemoteTrack"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"rtsRemoteTrack:didReceiveTrackStats:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrack:didReceiveTrackStats:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rtsRemoteTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveTrackStats:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCTrackStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","preciseIdentifier":"c:objc(cs)MCTrackStats","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stats","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The remote track for which a new stats is available.","type":"text"}]}],"name":"rtsRemoteTrack"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/title","value":"MCTrackStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/fragments","value":[{"text":"MCTrackStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/navigatorTitle","value":[{"kind":"identifier","text":"MCTrackStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title","value":"MCRTSRemoteTrackDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/title","value":"rtsRemoteTrack:didReceiveTrackStats:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didReceiveTrackStats:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","value":"enableStats:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableStats:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","value":"MCRTSRemoteTrack","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/navigatorTitle","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"op":"replace"}]}]}