{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ssrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":" "},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user data containing NSNumber with the unsignedChar value."}]}]},{"name":"ssrc","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The synchronization source of the frame."}]}]},{"name":"timestamp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The timestamp of the frame."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called after a frame has been encoded if you need to add data"},{"type":"text","text":" "},{"type":"text","text":"to this frame before the frame is passed to the RTP packetizer."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}],"role":"symbol","title":"onTransformableFrame(_:withSsrc:withTimestamp:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCPublisherDelegate(im)onTransformableFrame:withSsrc:withTimestamp:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onTransformableFrame(_:withSsrc:withTimestamp:)":{"navigatorTitle":[{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}],"role":"symbol","title":"onTransformableFrame(_:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after a frame has been encoded if you need to add data"},{"type":"text","text":" "},{"type":"text","text":"to this frame before the frame is passed to the RTP packetizer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onTransformableFrame:withSsrc:withTimestamp:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onTransformableFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSMutableArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"withSsrc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"ssrc"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTimestamp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":")"},{"kind":"internalParam","text":"timestamp"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/title","value":"onTransformableFrame:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}