{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"credentials","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCPublisherCredentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"async"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/credentials"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Asynchronously queries the currently set publisher credentials.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/credentials"},"sections":[],"metadata":{"extendedModule":"MillicastSDK","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"credentials","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credentials"},{"text":": ","kind":"text"},{"text":"MCPublisherCredentials","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"}],"externalID":"s:So11MCPublisherC12MillicastSDKE11credentialsSo0A11CredentialsCvp","modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"title":"MCPublisherCredentials","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCPublisherCredentials","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The Credentials interface represents the credentials required for"},{"type":"text","text":" "},{"text":"connecting the publisher to the streaming platform and publishing a stream.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Refer to the "},{"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true},{"text":" for this information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherCredentials"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","url":"\/documentation\/millicastsdk\/mcpublishercredentials"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://dash.millicast.com/docs.html":{"identifier":"https:\/\/dash.millicast.com\/docs.html","title":"streaming dashboard","titleInlineContent":[{"text":"streaming dashboard","type":"text"}],"url":"https:\/\/dash.millicast.com\/docs.html","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/credentials":{"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/credentials","title":"credentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/credentials","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"credentials","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCPublisherCredentials","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"}],"abstract":[{"text":"Asynchronously queries the currently set publisher credentials.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title","value":"MCPublisherCredentials"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments","value":[{"text":"MCPublisherCredentials","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace"}]}]}