{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithDelegate:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"MCPublisherDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCPublisherDelegate"},{"kind":"text","text":")?)"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"MillicastSDK"}],"title":"init(delegate:)","externalID":"c:objc(cs)MCPublisher(im)initWithDelegate:"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/init(delegate:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"MCPublisherDelegate","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","preciseIdentifier":"c:objc(pl)MCPublisherDelegate"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The publisher delegate to receive events related to publishing"}],"type":"paragraph"}],"name":"delegate"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Initializes a publisher.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/init(delegate:)"]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/init(delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"text":"You must implement this protocol and set a delegate.","type":"text"},{"text":" ","type":"text"},{"text":"to receive events from the publisher.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/init(delegate:)":{"abstract":[{"type":"text","text":"Initializes a publisher."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"MCPublisherDelegate","preciseIdentifier":"c:objc(pl)MCPublisherDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","title":"init(delegate:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/init(delegate:)","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/init(delegate:)","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithDelegate:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithDelegate:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDelegate:"},{"kind":"text","text":"("},{"text":"id<MCPublisherDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCPublisherDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","op":"replace","value":"MCPublisherDelegate"},{"value":[{"text":"MCPublisherDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCPublisher"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1init(delegate:)\/title","value":"initWithDelegate:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1init(delegate:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}