{"metadata":{"title":"publish(with:completionHandler:)","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"publishWithOptions:completionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCPublisher(im)publishWithOptions:completionHandler:","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCClientOptions","text":"MCClientOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/publish(with:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/publish(with:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/publish(with:completionhandler:)"]}],"abstract":[{"text":"Publish a stream with configuration options.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"options","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","text":"MCClientOptions","preciseIdentifier":"c:objc(cs)MCClientOptions"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"options","content":[{"inlineContent":[{"text":"Options to configure the publishing session. For example, audio\/video codec selection.","type":"text"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the result is ready.","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/publish(with:completionHandler:)":{"title":"publish(with:completionHandler:)","abstract":[{"type":"text","text":"Publish a stream with configuration options."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/publish(with:completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/publish(with:completionhandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publishWithOptions:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"publish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCClientOptions","preciseIdentifier":"c:objc(cs)MCClientOptions"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"kind":"symbol","type":"topic","title":"MCClientOptions","url":"\/documentation\/millicastsdk\/mcclientoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"publishWithOptions:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"publishWithOptions:completionHandler:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"publishWithOptions:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","kind":"typeIdentifier","text":"MCClientOptions","preciseIdentifier":"c:objc(cs)MCClientOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1publish(with:completionHandler:)\/title","value":"publishWithOptions:completionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"publishWithOptions:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1publish(with:completionHandler:)\/fragments","op":"replace"},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCClientOptions"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"}]}]}