{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/statsReport()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"metadata":{"symbolKind":"method","title":"statsReport()","extendedModule":"MillicastSDK","role":"symbol","externalID":"s:So11MCPublisherC12MillicastSDKE11statsReportScSySo07MCStatsE0CGyF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsReport","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"MCStatsReport","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"text":">","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stats reports."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/statsreport()"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"statsReport","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A new async stream reporting stream statistics.","type":"text"}]}],"kind":"content"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"title":"MCStatsReport","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsReport"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"role":"symbol","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatsreport"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/statsReport()":{"url":"\/documentation\/millicastsdk\/mcpublisher\/statsreport()","title":"statsReport()","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/statsReport()","role":"symbol","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stats reports."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"statsReport","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport","kind":"typeIdentifier"},{"kind":"text","text":">"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCStatsReport","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace"},{"value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"}]}]}