{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ssrc"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The synchronization source identifier for the stream. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/ssrc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/ssrc"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/ssrc","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"]]},"kind":"symbol","metadata":{"title":"ssrc","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ssrc","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ssrc"}],"role":"symbol","externalID":"c:objc(cs)MCRtpStreamStats(py)ssrc"},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/ssrc":{"title":"ssrc","url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/ssrc","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/ssrc","type":"topic","navigatorTitle":[{"text":"ssrc","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ssrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The synchronization source identifier for the stream. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-ssrc":{"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc","title":"ssrc","titleInlineContent":[{"text":"ssrc","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"title":"MCRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRtpStreamStats"}],"navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats","type":"topic","abstract":[{"text":"Statistics for an RTP stream.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ssrc"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ssrc"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"unsigned long","preciseIdentifier":"c:l"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ssrc"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1ssrc\/title","value":"ssrc"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1ssrc\/fragments","op":"replace","value":[{"kind":"identifier","text":"ssrc"}]},{"value":"MCRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title","op":"replace"},{"value":[{"text":"MCRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","op":"replace"}]}]}