{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/multipleresolve"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/multipleresolve"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"multipleResolve","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorMultipleResolve","kind":"identifier"}],"title":"MCAsyncOperationCancelledError.Code.multipleResolve","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCAsyncOperationCancelledError@MCAsyncOperationCancelledErrorMultipleResolve"},"sections":[],"abstract":[{"type":"text","text":"Internal SDK logic error."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"multipleResolve","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/multipleResolve","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCAsyncOperationCancelledError","kind":"identifier"}],"abstract":[],"title":"MCAsyncOperationCancelledError","navigatorTitle":[{"text":"MCAsyncOperationCancelledError","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/multipleResolve":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multipleResolve"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/multipleResolve","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorMultipleResolve"}],"type":"topic","abstract":[{"type":"text","text":"Internal SDK logic error."}],"role":"symbol","title":"MCAsyncOperationCancelledError.Code.multipleResolve","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/multipleresolve"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","type":"topic","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"abstract":[{"text":"Error category for errors triggered when the operation failed because","type":"text"},{"type":"text","text":" "},{"type":"text","text":"it was abandoned for various reasons."}],"title":"MCAsyncOperationCancelledError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCAsyncOperationCancelledErrorMultipleResolve"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"MCAsyncOperationCancelledErrorMultipleResolve","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"MCAsyncOperationCancelledErrorMultipleResolve","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1multipleResolve\/title","op":"replace","value":"MCAsyncOperationCancelledErrorMultipleResolve"},{"value":[{"text":"MCAsyncOperationCancelledErrorMultipleResolve","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1multipleResolve\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title","value":"MCAsyncOperationCancelledError"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}