{"kind":"symbol","abstract":[{"text":"Called when an attempt to connect to Millicast fails.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveHTTPConnectionError:)"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivehttpconnectionerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivehttpconnectionerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"client"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MCClient","text":"MCClient","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveHTTPConnectionError"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"client","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast client"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The HTTP error received","type":"text"}]}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"MCClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveHTTPConnectionError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"kind":"text","text":")"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","title":"client(_:didReceiveHTTPConnectionError:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)MCDelegate(im)client:didReceiveHTTPConnectionError:","navigatorTitle":[{"text":"client:didReceiveHTTPConnectionError:","kind":"identifier"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHTTPConnectionError"}],"abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"text":" ","type":"text"},{"text":"connection to the millicast service","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","role":"symbol","url":"\/documentation\/millicastsdk\/mchttpconnectionerror","navigatorTitle":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"type":"topic","title":"MCHTTPConnectionError"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"url":"\/documentation\/millicastsdk\/mcdelegate","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"MCDelegate","type":"codeVoice"},{"text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"subclassed by "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","type":"reference"},{"type":"text","text":" and "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","isActive":true,"type":"reference"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCDelegate"}],"title":"MCDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/client(_:didReceiveHTTPConnectionError:)":{"url":"\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivehttpconnectionerror:)","kind":"symbol","abstract":[{"text":"Called when an attempt to connect to Millicast fails.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"client","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient","text":"MCClient"},{"text":", ","kind":"text"},{"text":"didReceiveHTTPConnectionError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier","text":"MCHTTPConnectionError"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"client:didReceiveHTTPConnectionError:","kind":"identifier"}],"type":"topic","required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveHTTPConnectionError:)","role":"symbol","title":"client(_:didReceiveHTTPConnectionError:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"type":"topic","title":"MCSubscriber","role":"symbol","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","role":"symbol","kind":"symbol","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"type":"text","text":" "},{"text":"events.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","navigatorTitle":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSubscriberDelegate","kind":"identifier"}],"title":"MCSubscriberDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"url":"\/documentation\/millicastsdk\/mcpublisherdelegate","role":"symbol","kind":"symbol","abstract":[{"text":"This delegate  acts as a listener for the Publisher class.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You must implement this protocol and set a delegate."},{"text":" ","type":"text"},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"title":"MCClient","url":"\/documentation\/millicastsdk\/mcclient","navigatorTitle":[{"kind":"identifier","text":"MCClient"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"abstract":[{"type":"text","text":"The Client base that contains common methods between "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","type":"reference"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"client:didReceiveHTTPConnectionError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"client:didReceiveHTTPConnectionError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MCClient>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCClient"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveHTTPConnectionError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title","op":"replace","value":"MCHTTPConnectionError"},{"value":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","value":[{"text":"MCDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace"},{"value":"client:didReceiveHTTPConnectionError:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveHTTPConnectionError:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"client:didReceiveHTTPConnectionError:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveHTTPConnectionError:)\/fragments"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"text":"MCSubscriber","kind":"identifier"}]},{"value":"MCSubscriberDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title"},{"op":"replace","value":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments"},{"op":"replace","value":"MCPublisherDelegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"value":"MCClient","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments","value":[{"text":"MCClient","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}