{"abstract":[{"type":"text","text":"The current set of capabilities configured for the video source."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideosource\/getcapabilities()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosource\/getcapabilities()"]}],"metadata":{"externalID":"c:objc(cs)MCVideoSource(im)getCapabilities","navigatorTitle":[{"kind":"identifier","text":"getCapabilities"}],"title":"getCapabilities()","modules":[{"name":"MillicastSDK"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCapabilities","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"MCVideoCapabilities","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoCapabilities"},{"text":"]!","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/getCapabilities()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCapabilities","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCVideoCapabilities","text":"MCVideoCapabilities","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities"},{"text":"]!","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of video capabilities of the video device."}]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/getCapabilities()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/getCapabilities()","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideosource\/getcapabilities()","navigatorTitle":[{"text":"getCapabilities","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The current set of capabilities configured for the video source."}],"title":"getCapabilities()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCapabilities","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities","kind":"typeIdentifier"},{"text":"]!","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource":{"role":"symbol","navigatorTitle":[{"text":"MCVideoSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource","title":"MCVideoSource","url":"\/documentation\/millicastsdk\/mcvideosource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSource","kind":"identifier"}],"abstract":[{"text":"Responsible for managing video sources.","type":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoCapabilities":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoCapabilities"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoCapabilities"}],"abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities","role":"symbol","type":"topic","kind":"symbol","title":"MCVideoCapabilities","url":"\/documentation\/millicastsdk\/mcvideocapabilities"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"getCapabilities"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCapabilities"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MCVideoCapabilities *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getCapabilities","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of video capabilities of the video device.","type":"text"}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1getCapabilities()\/title","value":"getCapabilities"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1getCapabilities()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getCapabilities","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/title","value":"MCVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/fragments","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/title","value":"MCVideoCapabilities"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments","value":[{"kind":"identifier","text":"MCVideoCapabilities"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoCapabilities"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}