{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionStatePublisher()"},"metadata":{"title":"peerConnectionStatePublisher()","role":"symbol","extendedModule":"MillicastSDK","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"externalID":"s:So11MCPublisherC12MillicastSDKE28peerConnectionStatePublisher7Combine03AnyG0VySo012MCConnectionF0Vs5NeverOGyF"},"abstract":[{"text":"Get a Combine based publisher that can be used to receive connection state changes  for the peer","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"connection."}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/peerconnectionstatepublisher()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@E@MCConnectionState","kind":"typeIdentifier","text":"MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":">"}],"languages":["swift"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/peerConnectionStatePublisher()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"peerConnectionStatePublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState"},{"text":", ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive connection state changes  for the peer"},{"type":"text","text":" "},{"text":"connection.","type":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionStatePublisher()","role":"symbol","title":"peerConnectionStatePublisher()","url":"\/documentation\/millicastsdk\/mcpublisher\/peerconnectionstatepublisher()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","type":"topic","title":"MCConnectionState","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]},{"op":"replace","value":"MCConnectionState","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments","value":[{"text":"MCConnectionState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}