{"variants":[{"paths":["\/documentation\/millicastsdk\/mctrackstats\/trackidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrackstats\/trackidentifier"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"trackIdentifier","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(cs)MCTrackStats(py)trackIdentifier","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"trackIdentifier","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/trackIdentifier"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats":{"url":"\/documentation\/millicastsdk\/mctrackstats","title":"MCTrackStats","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrackStats"}],"navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats/trackIdentifier":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/trackIdentifier","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"trackIdentifier"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/trackidentifier","title":"trackIdentifier","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"trackIdentifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"trackIdentifier","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"trackIdentifier","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/title","value":"MCTrackStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/fragments","value":[{"kind":"identifier","text":"MCTrackStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1trackIdentifier\/title","value":"trackIdentifier"},{"op":"replace","value":[{"text":"trackIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1trackIdentifier\/fragments"}]}]}