{"kind":"symbol","abstract":[{"type":"text","text":"Set the maximum temporal layer ID."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxtemporallayerid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxtemporallayerid(_:)"]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxTemporalLayerId(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"setMaxTemporalLayerId(_:)","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)setMaxTemporalLayerId:","navigatorTitle":[{"text":"setMaxTemporalLayerId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMaxTemporalLayerId","kind":"identifier"},{"kind":"text","text":"("},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMaxTemporalLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"maxTemporalLayerId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Selected from the RTS remote track layer event","type":"text"}]}],"name":"maxTemporalLayerId"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setMaxTemporalLayerId(_:)":{"abstract":[{"type":"text","text":"Set the maximum temporal layer ID."}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxtemporallayerid(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxTemporalLayerId(_:)","title":"setMaxTemporalLayerId(_:)","navigatorTitle":[{"kind":"identifier","text":"setMaxTemporalLayerId:"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaxTemporalLayerId"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":")","kind":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"title":"MCRTSRemoteVideoTrackLayer","role":"symbol","abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"setMaxTemporalLayerId:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"setMaxTemporalLayerId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMaxTemporalLayerId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maxTemporalLayerId"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxTemporalLayerId(_:)\/title","op":"replace","value":"setMaxTemporalLayerId:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxTemporalLayerId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMaxTemporalLayerId:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer"},{"op":"replace","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments"}]}]}