{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The remote track that has become active.","type":"text"}],"type":"paragraph"}],"name":"rtsRemoteTrack"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackactive(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackactive(_:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"rtsRemoteTrackActive:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCRTSRemoteTrackDelegate(im)rtsRemoteTrackActive:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":")","kind":"text"}],"title":"rtsRemoteTrackActive(_:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"text":"Event received when the track, i.e. it’s publishing source, has become active.","type":"text"},{"text":" ","type":"text"},{"text":"In other words the stream is being sent to the server and is viable on the viewing","type":"text"},{"text":" ","type":"text"},{"text":"client. The track is not enabled by default. The application can still call","type":"text"},{"text":" ","type":"text"},{"text":"disable() on this track to prevent it from being played. If the track","type":"text"},{"text":" ","type":"text"},{"text":"was previously disabled, the application must call enable() for the track","type":"text"},{"text":" ","type":"text"},{"text":"to be renderable. If the track was previously enabled by the application and is not","type":"text"},{"text":" ","type":"text"},{"text":"disabled by the application it will automatically start playing once it becomes","type":"text"},{"text":" ","type":"text"},{"text":"active.","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackActive(_:)":{"title":"rtsRemoteTrackActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrackActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Event received when the track, i.e. it’s publishing source, has become active."},{"type":"text","text":" "},{"type":"text","text":"In other words the stream is being sent to the server and is viable on the viewing"},{"type":"text","text":" "},{"type":"text","text":"client. The track is not enabled by default. The application can still call"},{"type":"text","text":" "},{"type":"text","text":"disable() on this track to prevent it from being played. If the track"},{"type":"text","text":" "},{"type":"text","text":"was previously disabled, the application must call enable() for the track"},{"type":"text","text":" "},{"type":"text","text":"to be renderable. If the track was previously enabled by the application and is not"},{"type":"text","text":" "},{"type":"text","text":"disabled by the application it will automatically start playing once it becomes"},{"type":"text","text":" "},{"type":"text","text":"active."}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackactive(_:)","navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrackActive:"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"title":"MCRTSRemoteTrackDelegate","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","kind":"symbol","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rtsRemoteTrackActive:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrackActive:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtsRemoteTrackActive:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rtsRemoteTrack"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"rtsRemoteTrackActive:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrackActive:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/fragments"},{"value":"MCRTSRemoteTrackDelegate","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments"},{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"}]}]}