{"abstract":[{"text":"Contains only information about the stream, like bitrate","type":"text"},{"text":" ","type":"text"},{"text":"resolution, frames dropped etc.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simplified","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"MCSubscriberStatsLevel.simplified","externalID":"c:@E@MCSubscriberStatsLevel@MCSubscriberStatsLevelSimplified","modules":[{"name":"MillicastSDK"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simplified","kind":"identifier"}],"navigatorTitle":[{"text":"MCSubscriberStatsLevelSimplified","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel\/simplified"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel\/simplified"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/simplified","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberStatsLevel":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel","type":"topic","title":"MCSubscriberStatsLevel","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Enum specifying the level of verbosity for stats.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberStatsLevel"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberStatsLevel/simplified":{"title":"MCSubscriberStatsLevel.simplified","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCSubscriberStatsLevelSimplified","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/simplified","abstract":[{"type":"text","text":"Contains only information about the stream, like bitrate"},{"type":"text","text":" "},{"type":"text","text":"resolution, frames dropped etc."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"simplified","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/simplified"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCSubscriberStatsLevelSimplified"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCSubscriberStatsLevelSimplified","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCSubscriberStatsLevelSimplified","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/title","op":"replace","value":"MCSubscriberStatsLevel"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1simplified\/title","value":"MCSubscriberStatsLevelSimplified","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1simplified\/fragments","value":[{"text":"MCSubscriberStatsLevelSimplified","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}