{"abstract":[{"text":"The socket has entered reconnection state.","type":"text"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/reconnecting","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"MCConnectionStateReconnecting","kind":"identifier"}],"externalID":"c:@E@MCConnectionState@MCConnectionStateReconnecting","title":"MCConnectionState.reconnecting","symbolKind":"case","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnecting","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"]]},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"title":"MCConnectionState","abstract":[],"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCConnectionState"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/reconnecting":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reconnecting","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionStateReconnecting","kind":"identifier"}],"kind":"symbol","title":"MCConnectionState.reconnecting","url":"\/documentation\/millicastsdk\/mcconnectionstate\/reconnecting","abstract":[{"text":"The socket has entered reconnection state.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/reconnecting"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCConnectionStateReconnecting","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCConnectionStateReconnecting"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCConnectionStateReconnecting"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title","value":"MCConnectionState"},{"value":[{"kind":"identifier","text":"MCConnectionState"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1reconnecting\/title","value":"MCConnectionStateReconnecting","op":"replace"},{"value":[{"text":"MCConnectionStateReconnecting","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1reconnecting\/fragments","op":"replace"}]}]}