{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveViewerCount:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"client","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"client","kind":"internalParam"},{"kind":"text","text":": any "},{"text":"MCClient","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","preciseIdentifier":"c:objc(pl)MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveViewerCount"},{"text":" ","kind":"text"},{"text":"viewerCount","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"client","content":[{"inlineContent":[{"text":"The Millicast client","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current number of viewers connected to the stream."}]}],"name":"didReceiveViewerCount"}]}],"kind":"symbol","abstract":[{"text":"Called whenever a new viewer joins or leaves the stream.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"(any "},{"text":"MCClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveViewerCount"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"required":true,"role":"symbol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"client:didReceiveViewerCount:","kind":"identifier"}],"title":"client(_:didReceiveViewerCount:)","externalID":"c:objc(pl)MCDelegate(im)client:didReceiveViewerCount:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceiveviewercount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceiveviewercount:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"title":"MCPublisher"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","role":"symbol","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate","type":"topic","abstract":[{"text":"This delegate  acts as a listener for the Publisher class.","type":"text"},{"text":" ","type":"text"},{"text":"You must implement this protocol and set a delegate.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"navigatorTitle":[{"text":"MCDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"MCDelegate","type":"codeVoice"},{"text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly","type":"text"},{"type":"text","text":" "},{"text":"subclassed by ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","isActive":true},{"type":"text","text":", which are the main ones to implement."}],"title":"MCDelegate","url":"\/documentation\/millicastsdk\/mcdelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCDelegate"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"title":"MCSubscriber","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"navigatorTitle":[{"text":"MCClient","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","title":"MCClient","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClient"}],"url":"\/documentation\/millicastsdk\/mcclient","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","type":"reference","isActive":true},{"text":" and ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","isActive":true},{"type":"text","text":"."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/client(_:didReceiveViewerCount:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveViewerCount:)","kind":"symbol","abstract":[{"text":"Called whenever a new viewer joins or leaves the stream.","type":"text"}],"type":"topic","title":"client(_:didReceiveViewerCount:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceiveviewercount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"client","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"MCClient","preciseIdentifier":"c:objc(pl)MCClient","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveViewerCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"client:didReceiveViewerCount:","kind":"identifier"}],"required":true},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MCSubscriberDelegate","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"text":" ","type":"text"},{"text":"events.","type":"text"}],"title":"MCSubscriberDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"client:didReceiveViewerCount:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveViewerCount:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"client:"},{"text":"(","kind":"text"},{"text":"id<MCClient>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCClient"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveViewerCount:"},{"kind":"text","text":"("},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"kind":"text","text":") "},{"text":"viewerCount","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"value":"MCPublisherDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title"},{"value":[{"text":"MCPublisherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"text":"MCDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title","value":"MCClient","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments","op":"replace","value":[{"text":"MCClient","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveViewerCount:)\/title","value":"client:didReceiveViewerCount:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"client:didReceiveViewerCount:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveViewerCount:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]}]}]}