{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:completionhandler:)"]}],"kind":"symbol","abstract":[{"text":"Enable the track and project from given RTS track, with default promote and layer behaviour.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"projectWithRTSRemoteVideoTrack:completionHandler:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack(im)projectWithRTSRemoteVideoTrack:completionHandler:","title":"project(rtsRemoteVideoTrack:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"rtsRemoteVideoTrack","content":[{"type":"paragraph","inlineContent":[{"text":"the RTS track which will be projected onto this webrtc","type":"text"},{"text":" ","type":"text"},{"text":"track.","type":"text"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the asynchronous operation is finished","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"role":"symbol","abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","title":"MCRTSRemoteVideoTrack","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"title":"MCWebrtcRemoteVideoTrack","navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:completionHandler:)":{"kind":"symbol","abstract":[{"text":"Enable the track and project from given RTS track, with default promote and layer behaviour.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:completionhandler:)","role":"symbol","title":"project(rtsRemoteVideoTrack:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:completionHandler:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:completionHandler:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtsRemoteVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"projectWithRTSRemoteVideoTrack:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"projectWithRTSRemoteVideoTrack:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rtsRemoteVideoTrack"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","value":"MCWebrtcRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:completionHandler:)\/title","value":"projectWithRTSRemoteVideoTrack:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:completionHandler:"}]}]}]}