{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource\/stopCapture()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"()","kind":"text"}],"required":true,"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"stopCapture","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)CaptureSource(im)stopCapture","title":"stopCapture()","modules":[{"name":"MillicastSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}]}]}],"abstract":[{"text":"Stops a capture and releases the track and the underlying devices.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/capturesource\/stopcapture()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/capturesource\/stopcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/CaptureSource/stopCapture()":{"navigatorTitle":[{"text":"stopCapture","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource\/stopCapture()","url":"\/documentation\/millicastsdk\/capturesource\/stopcapture()","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stopCapture()","abstract":[{"type":"text","text":"Stops a capture and releases the track and the underlying devices."}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/CaptureSource":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","url":"\/documentation\/millicastsdk\/capturesource","abstract":[{"type":"text","text":"Manages the process of capturing the source by input sources, such as a microphone or a camera."}],"kind":"symbol","navigatorTitle":[{"text":"CaptureSource","kind":"identifier"}],"title":"CaptureSource"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"stopCapture","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"stopCapture","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource~1stopCapture()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource~1stopCapture()\/fragments"},{"op":"replace","value":"CaptureSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/title"},{"op":"replace","value":[{"text":"CaptureSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}