{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/unkown"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/unkown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/unkown"]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeUnkown"}],"title":"MCVideoType.unkown","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unkown"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCVideoType@MCVideoTypeUnkown","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unkown","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype","title":"MCVideoType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoType"}],"navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType/unkown":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeUnkown"}],"title":"MCVideoType.unkown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/unkown","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/unkown","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCVideoTypeUnkown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MCVideoTypeUnkown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCVideoTypeUnkown"}]}],"kind":"declarations"}},{"op":"replace","value":"MCVideoType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title"},{"value":[{"kind":"identifier","text":"MCVideoType"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments"},{"op":"replace","value":"MCVideoTypeUnkown","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1unkown\/title"},{"op":"replace","value":[{"text":"MCVideoTypeUnkown","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1unkown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}