{"kind":"symbol","metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"didReceiveFrame:"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","title":"didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"kind":"text","text":"!)"}],"role":"symbol","externalID":"c:objc(pl)MCAudioRenderer(im)didReceiveFrame:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiorenderer\/didreceive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiorenderer\/didreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"This handler is called when a new audio frame is available."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A raw audio frame."}]}],"name":"frame"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer\/didReceive(_:)","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame":{"title":"MCAudioFrame","url":"\/documentation\/millicastsdk\/mcaudioframe","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","abstract":[{"type":"text","text":"Audio frame that contains audio data. Used with "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"to feed custom audio frames into source used by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioFrame"}],"navigatorTitle":[{"text":"MCAudioFrame","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/add(_:)":{"title":"add(_:)","role":"symbol","kind":"symbol","abstract":[{"text":"Adds an audio renderer to render this track.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCAudioRenderer","kind":"typeIdentifier","text":"MCAudioRenderer"},{"text":")!)","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioRenderer/didReceive(_:)":{"title":"didReceive(_:)","role":"symbol","required":true,"kind":"symbol","abstract":[{"type":"text","text":"This handler is called when a new audio frame is available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer\/didReceive(_:)","navigatorTitle":[{"text":"didReceiveFrame:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioFrame","text":"MCAudioFrame"},{"kind":"text","text":"!)"}],"url":"\/documentation\/millicastsdk\/mcaudiorenderer\/didreceive(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioRenderer":{"url":"\/documentation\/millicastsdk\/mcaudiorenderer","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This protocol can be implemented to receive audio frames from audio tracks. However,"},{"type":"text","text":" "},{"type":"text","text":"The recommended method to render audio is to use "},{"type":"codeVoice","code":"MCAudioPlaback"},{"type":"text","text":" instead."},{"text":" ","type":"text"},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)"},{"text":" to attach an audio renderer.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer","navigatorTitle":[{"text":"MCAudioRenderer","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MCAudioRenderer","kind":"identifier"}],"title":"MCAudioRenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"title":"onAudioFrame(_:)","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioFrame"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"text":"!)","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","navigatorTitle":[{"kind":"identifier","text":"onAudioFrame:"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"didReceiveFrame:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveFrame:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveFrame:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","text":"MCAudioFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/title","value":"MCAudioFrame"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioFrame"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/title","value":"addRenderer:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer~1didReceive(_:)\/title","value":"didReceiveFrame:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer~1didReceive(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didReceiveFrame:","kind":"identifier"}]},{"value":"MCAudioRenderer","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer\/title"},{"op":"replace","value":[{"text":"MCAudioRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","op":"replace","value":"onAudioFrame:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onAudioFrame:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}