{"metadata":{"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:objc(cs)MCStreamStoppedEvent(py)description","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent\/description-swift.property"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"More information about the event."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-swift.property"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStreamStoppedEvent/description-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-swift.property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent\/description-swift.property","role":"symbol","abstract":[{"type":"text","text":"More information about the event."}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamStoppedEvent":{"abstract":[{"type":"text","text":"Container for the stream stopped event. This happens"},{"type":"text","text":" "},{"type":"text","text":"when the last publisher has stopped sending a stream"},{"type":"text","text":" "},{"type":"text","text":"and no more media is available"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStreamStoppedEvent","kind":"identifier"}],"navigatorTitle":[{"text":"MCStreamStoppedEvent","kind":"identifier"}],"role":"symbol","title":"MCStreamStoppedEvent","url":"\/documentation\/millicastsdk\/mcstreamstoppedevent","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent~1description-swift.property\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent~1description-swift.property\/fragments","op":"replace"},{"op":"replace","value":"MCStreamStoppedEvent","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/fragments","value":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}