{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetTemporalLayerId","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"resetTemporalLayerId()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetTemporalLayerId","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"resetTemporalLayerId","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)resetTemporalLayerId","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Reset the temporal layer ID."}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetTemporalLayerId()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resettemporallayerid()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resettemporallayerid()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"kind":"symbol","role":"symbol","type":"topic","title":"MCRTSRemoteVideoTrackLayer","navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetTemporalLayerId()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resetTemporalLayerId"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetTemporalLayerId"},{"kind":"text","text":"()"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resettemporallayerid()","title":"resetTemporalLayerId()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetTemporalLayerId()","kind":"symbol","abstract":[{"text":"Reset the temporal layer ID.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"resetTemporalLayerId","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetTemporalLayerId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"resetTemporalLayerId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCRTSRemoteVideoTrackLayer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments"},{"op":"replace","value":"resetTemporalLayerId","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetTemporalLayerId()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resetTemporalLayerId","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetTemporalLayerId()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}