{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxSpatialLayerId(_:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)setMaxSpatialLayerId:","role":"symbol","title":"setMaxSpatialLayerId(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMaxSpatialLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"setMaxSpatialLayerId:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMaxSpatialLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"maxSpatialLayerId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Selected from the RTS remote track layer event"}],"type":"paragraph"}],"name":"maxSpatialLayerId"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxspatiallayerid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxspatiallayerid(_:)"]}],"abstract":[{"text":"Set the maximum spatial layer ID.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"kind":"symbol","role":"symbol","type":"topic","title":"MCRTSRemoteVideoTrackLayer","navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setMaxSpatialLayerId(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxSpatialLayerId(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMaxSpatialLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setMaxSpatialLayerId:"}],"abstract":[{"type":"text","text":"Set the maximum spatial layer ID."}],"title":"setMaxSpatialLayerId(_:)","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxspatiallayerid(_:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setMaxSpatialLayerId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setMaxSpatialLayerId:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMaxSpatialLayerId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxSpatialLayerId"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCRTSRemoteVideoTrackLayer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","op":"replace"},{"value":"setMaxSpatialLayerId:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxSpatialLayerId(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setMaxSpatialLayerId:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxSpatialLayerId(_:)\/fragments","op":"replace"}]}]}