{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSupportedVideoCodecs"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of all available video codecs on the platforms."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcmedia\/getsupportedvideocodecs()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcmedia\/getsupportedvideocodecs()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedVideoCodecs()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Query a list of the supported video codecs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSupportedVideoCodecs"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"title":"getSupportedVideoCodecs()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCMedia(cm)getSupportedVideoCodecs","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getSupportedVideoCodecs"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"role":"symbol","title":"MCMedia","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMedia"}],"abstract":[{"type":"text","text":"Class  used  for managing media sources."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCMedia"}],"url":"\/documentation\/millicastsdk\/mcmedia"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getSupportedVideoCodecs()":{"role":"symbol","title":"getSupportedVideoCodecs()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSupportedVideoCodecs"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"Query a list of the supported video codecs."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getSupportedVideoCodecs()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getSupportedVideoCodecs"}],"url":"\/documentation\/millicastsdk\/mcmedia\/getsupportedvideocodecs()"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getSupportedVideoCodecs"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSupportedVideoCodecs"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getSupportedVideoCodecs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title","value":"MCMedia"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments","value":[{"kind":"identifier","text":"MCMedia"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedVideoCodecs()\/title","value":"getSupportedVideoCodecs"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getSupportedVideoCodecs()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSupportedVideoCodecs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}