{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/addWebrtcRemoteTrack(kind:cname:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"metadata":{"roleHeading":"Instance Method","title":"addWebrtcRemoteTrack(kind:cname:completionHandler:)","externalID":"c:objc(cs)MCSubscriber(im)addWebrtcRemoteTrackWithKind:cname:completionHandler:","navigatorTitle":[{"kind":"identifier","text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addWebrtcRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"kind","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cname","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"MillicastSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addWebrtcRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"kind","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind","text":"MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind"},{"text":", ","kind":"text"},{"text":"cname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addWebrtcRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"kind","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRemoteTrackKind","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind"},{"text":", ","kind":"text"},{"text":"cname","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"MCWebrtcRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"kind","content":[{"type":"paragraph","inlineContent":[{"text":"The kind of the track, either audio or video.","type":"text"}]}]},{"name":"cname","content":[{"inlineContent":[{"type":"text","text":"RTCP CNAME. Allows to play different tracks with the same cname in"},{"type":"text","text":" "},{"type":"text","text":"a synchronized manner."}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes,"},{"type":"text","text":" "},{"type":"text","text":"with a newly created webrtc remote track."}]}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Create a webrtc remote track that can be used for advanced projection use cases"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/addwebrtcremotetrack(kind:cname:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/addwebrtcremotetrack(kind:cname:completionhandler:)"]}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","kind":"symbol","type":"topic","title":"MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/addWebrtcRemoteTrack(kind:cname:completionHandler:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/addWebrtcRemoteTrack(kind:cname:completionHandler:)","title":"addWebrtcRemoteTrack(kind:cname:completionHandler:)","role":"symbol","abstract":[{"text":"Create a webrtc remote track that can be used for advanced projection use cases","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/addwebrtcremotetrack(kind:cname:completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addWebrtcRemoteTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRemoteTrackKind","preciseIdentifier":"c:@E@MCRemoteTrackKind"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cname"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"kind":"text","text":"?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind":{"title":"MCRemoteTrackKind","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enum specifying the type of the remote track."}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteTrackKind","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"symbol","abstract":[{"type":"text","text":"The webrtc logical track."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","title":"MCWebrtcRemoteTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addWebrtcRemoteTrackWithKind:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind"},{"text":") ","kind":"text"},{"text":"kind","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cname:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cname","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"kind","content":[{"inlineContent":[{"type":"text","text":"The kind of the track, either audio or video."}],"type":"paragraph"}]},{"name":"cname","content":[{"type":"paragraph","inlineContent":[{"text":"RTCP CNAME. Allows to play different tracks with the same cname in","type":"text"},{"text":" ","type":"text"},{"text":"a synchronized manner.","type":"text"}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"text":"Invoked when the asynchronous operation completes,","type":"text"},{"text":" ","type":"text"},{"text":"with a newly created webrtc remote track.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/navigatorTitle","value":[{"text":"MCSubscriber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1addWebrtcRemoteTrack(kind:cname:completionHandler:)\/title","value":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1addWebrtcRemoteTrack(kind:cname:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addWebrtcRemoteTrackWithKind:cname:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title","value":"MCRemoteTrackKind"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/navigatorTitle","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","value":"MCWebrtcRemoteTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/navigatorTitle","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}