{"kind":"symbol","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stream stopped events"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamStopped","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStreamStoppedEvent","text":"MCStreamStoppedEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"A new async stream reporting stream stopped events.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamStopped","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","text":"MCStreamStoppedEvent","kind":"typeIdentifier"},{"text":">","kind":"text"}],"externalID":"s:So12MCSubscriberC12MillicastSDKE13streamStoppedScSySo08MCStreamE5EventCGyF","title":"streamStopped()","extendedModule":"MillicastSDK","role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/streamstopped()"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/streamStopped()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/streamStopped()":{"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stream stopped events"}],"kind":"symbol","title":"streamStopped()","url":"\/documentation\/millicastsdk\/mcsubscriber\/streamstopped()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamStopped","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","text":"MCStreamStoppedEvent","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/streamStopped()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStreamStoppedEvent":{"type":"topic","title":"MCStreamStoppedEvent","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStreamStoppedEvent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStreamStoppedEvent","kind":"identifier"}],"abstract":[{"text":"Container for the stream stopped event. This happens","type":"text"},{"text":" ","type":"text"},{"text":"when the last publisher has stopped sending a stream","type":"text"},{"text":" ","type":"text"},{"text":"and no more media is available","type":"text"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent","navigatorTitle":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","kind":"symbol","type":"topic","title":"MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCStreamStoppedEvent","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/title"},{"value":[{"text":"MCStreamStoppedEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/fragments"},{"value":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/navigatorTitle"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/navigatorTitle"}]}]}