{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/webrtcAudioTracks(completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCSubscriber(im)webrtcAudioTracksWithCompletionHandler:","navigatorTitle":[{"kind":"identifier","text":"webrtcAudioTracksWithCompletionHandler:"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webrtcAudioTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"text":"]?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"webrtcAudioTracks(completionHandler:)"},"sections":[],"abstract":[{"type":"text","text":"List all available webrtc remote audio tracks created so far."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/webrtcaudiotracks(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/webrtcaudiotracks(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcAudioTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","text":"MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcAudioTracks"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the asynchronous operation completes, with a","type":"text"},{"text":" ","type":"text"},{"text":"list of webrtc remote audio tracks.","type":"text"}]}],"name":"completionHandler"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","kind":"symbol","title":"MCWebrtcRemoteAudioTrack","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","abstract":[{"text":"The webrtc logical track’s audio interface.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/webrtcAudioTracks(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/webrtcaudiotracks(completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcAudioTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"]?, (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"webrtcAudioTracksWithCompletionHandler:"}],"kind":"symbol","abstract":[{"text":"List all available webrtc remote audio tracks created so far.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/webrtcAudioTracks(completionHandler:)","role":"symbol","title":"webrtcAudioTracks(completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","kind":"symbol","type":"topic","title":"MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"webrtcAudioTracksWithCompletionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcAudioTracksWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webrtcAudioTracksWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MCWebrtcRemoteAudioTrack *>"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes, with a"},{"type":"text","text":" "},{"type":"text","text":"list of webrtc remote audio tracks."}],"type":"paragraph"}],"name":"completionHandler"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"MCWebrtcRemoteAudioTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/navigatorTitle"},{"value":"webrtcAudioTracksWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1webrtcAudioTracks(completionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcAudioTracksWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1webrtcAudioTracks(completionHandler:)\/fragments"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}