{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layer"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"the RTS track which will be projected onto this webrtc"},{"type":"text","text":" "},{"text":"track.","type":"text"}],"type":"paragraph"}],"name":"rtsRemoteVideoTrack"},{"name":"layer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"layer information. If the default value is passed, the service"},{"type":"text","text":" "},{"type":"text","text":"will allocate layers automatically depending on bandwidth estimation and"},{"text":" ","type":"text"},{"text":"the priority","type":"text"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation is finished"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:completionhandler:)"]}],"metadata":{"title":"project(rtsRemoteVideoTrack:layer:completionHandler:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"project","kind":"identifier"},{"kind":"text","text":"("},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack(im)projectWithRTSRemoteVideoTrack:layer:completionHandler:","role":"symbol","navigatorTitle":[{"text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:","kind":"identifier"}]},"kind":"symbol","sections":[],"abstract":[{"text":"Enable the track and project from given RTS track, with default promote behaviour, which is false.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:completionHandler:)"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"title":"MCWebrtcRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","role":"symbol","abstract":[{"text":"The webrtc logical track’s video interface.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","title":"MCRTSRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:layer:completionHandler:)":{"abstract":[{"type":"text","text":"Enable the track and project from given RTS track, with default promote behaviour, which is false."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:completionHandler:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:completionhandler:)","title":"project(rtsRemoteVideoTrack:layer:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtsRemoteVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"text":", ","kind":"text"},{"text":"layer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"symbol","abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"type":"text","text":" "},{"text":"the client wants to inform the media server to select.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","type":"topic","title":"MCRTSRemoteVideoTrackLayer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"projectWithRTSRemoteVideoTrack:layer:completionHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"projectWithRTSRemoteVideoTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":" *) "},{"text":"rtsRemoteVideoTrack","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer:"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"layer"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"MCWebrtcRemoteVideoTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:completionHandler:)\/title","value":"projectWithRTSRemoteVideoTrack:layer:completionHandler:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer","op":"replace"},{"value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","op":"replace"}]}]}