{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/mime_type"},"metadata":{"title":"mime_type","externalID":"c:objc(cs)MCCodecsStats(py)mime_type","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mime_type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mime_type"}],"role":"symbol","roleHeading":"Instance Property"},"sections":[],"abstract":[{"type":"text","text":"The Multipurpose Internet Mail Extensions (MIME) type associated with the codec. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype","isActive":true,"type":"reference"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/mime_type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/mime_type"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mime_type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/mime_type":{"type":"topic","title":"mime_type","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/mime_type","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/mime_type","abstract":[{"text":"The Multipurpose Internet Mail Extensions (MIME) type associated with the codec. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype","isActive":true}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mime_type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"mime_type","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"title":"MCCodecsStats","abstract":[{"text":"Gathers audio\/video codec statistics.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-mimetype":{"titleInlineContent":[{"type":"text","text":"mimeType"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype","title":"mimeType","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"mime_type"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"mime_type","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mime_type"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"mime_type","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1mime_type\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1mime_type\/fragments","value":[{"text":"mime_type","kind":"identifier"}]},{"value":"MCCodecsStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCCodecsStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments"}]}]}