{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType\/custom","interfaceLanguage":"swift"},"abstract":[{"text":"Custom audio source.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/custom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/custom"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"MCSourceTypeCustom","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCSourceType@MCSourceTypeCustom","title":"MCSourceType.custom","symbolKind":"case"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"abstract":[{"text":"The Source type","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType","title":"MCSourceType","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSourceType/custom":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/custom","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSourceType\/custom","navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeCustom"}],"abstract":[{"type":"text","text":"Custom audio source."}],"type":"topic","kind":"symbol","title":"MCSourceType.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCSourceTypeCustom","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCSourceTypeCustom"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCSourceTypeCustom"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"text":"MCSourceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType\/navigatorTitle","value":[{"text":"MCSourceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType~1custom\/title","value":"MCSourceTypeCustom"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSourceType~1custom\/fragments","value":[{"kind":"identifier","text":"MCSourceTypeCustom"}]}]}]}