{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleBuffer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"MCVideoSwiftUIView.Renderer.sampleBuffer(_:)","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","externalID":"s:12MillicastSDK18MCVideoSwiftUIViewV8RendererO12sampleBufferyAESo010MCCMSampleh5VideoF0CcAEmF","role":"symbol","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView\/Renderer\/sampleBuffer(_:)"},"abstract":[{"text":"Uses a AVSampleBufferDisplayLayer for rendering.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoswiftuiview\/renderer\/samplebuffer(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView\/Renderer"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sampleBuffer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"title":"MCVideoFrame","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe","abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoFrame","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSwiftUIView":{"navigatorTitle":[{"text":"MCVideoSwiftUIView","kind":"identifier"}],"title":"MCVideoSwiftUIView","abstract":[{"type":"text","text":"Swift UI View that can use either Metal or a sample buffer to render a track."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoswiftuiview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSwiftUIView"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSwiftUIView/Renderer":{"url":"\/documentation\/millicastsdk\/mcvideoswiftuiview\/renderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView\/Renderer","type":"topic","kind":"symbol","title":"MCVideoSwiftUIView.Renderer","navigatorTitle":[{"kind":"identifier","text":"Renderer"}],"abstract":[{"text":"Describes the rendering backend.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Renderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSwiftUIView/Renderer/sampleBuffer(_:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Uses a AVSampleBufferDisplayLayer for rendering."}],"url":"\/documentation\/millicastsdk\/mcvideoswiftuiview\/renderer\/samplebuffer(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView\/Renderer\/sampleBuffer(_:)","type":"topic","title":"MCVideoSwiftUIView.Renderer.sampleBuffer(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sampleBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCCMSampleBufferVideoRenderer","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"title":"MCCMSampleBufferVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","kind":"symbol","abstract":[{"type":"text","text":"This class is responsible for converting "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","isActive":true,"type":"reference"},{"text":"  into renderable ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"text":" frames.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}