{"metadata":{"title":"enable(renderer:promote:completionHandler:)","role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(cs)MCRTSRemoteVideoTrack(im)enableWithRenderer:promote:completionHandler:","navigatorTitle":[{"text":"enableWithRenderer:promote:completionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"promote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The renderer to receive video frames."}]}]},{"name":"promote","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"set this track to be the main video track. The main video"},{"type":"text","text":" "},{"type":"text","text":"track has highest priority for bandwidth assignment when SVC layers are"},{"type":"text","text":" "},{"type":"text","text":"managed by the service."}]}]},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:promote:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:promote:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:promote:completionhandler:)"]}],"abstract":[{"text":"Enable the track with default layer behaviour","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"symbol","role":"symbol","title":"MCRTSRemoteVideoTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":")!)"}],"title":"add(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:promote:completionHandler:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:promote:completionHandler:)","title":"enable(renderer:promote:completionHandler:)","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:promote:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Enable the track with default layer behaviour","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"enableWithRenderer:promote:completionHandler:","kind":"identifier"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer","title":"MCVideoRenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"enableWithRenderer:promote:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"enableWithRenderer:promote:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableWithRenderer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MCVideoRenderer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer"},{"text":") ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"promote:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"promote","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCRTSRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments"},{"value":"addRenderer:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addRenderer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments"},{"value":"enableWithRenderer:promote:completionHandler:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:promote:completionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"enableWithRenderer:promote:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:promote:completionHandler:)\/fragments"},{"value":"MCVideoRenderer","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title"},{"value":[{"kind":"identifier","text":"MCVideoRenderer"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}