{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"]]},"abstract":[{"type":"text","text":"The variation in packet arrival times, indicating network congestion and latency issues. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","type":"reference","isActive":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"jitter","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/jitter","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)MCReceivedRtpStreamStats(py)jitter","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"jitter","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"jitter"}],"title":"jitter","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/jitter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/jitter"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/jitter":{"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/jitter","abstract":[{"text":"The variation in packet arrival times, indicating network congestion and latency issues. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jitter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/jitter","type":"topic","title":"jitter","navigatorTitle":[{"kind":"identifier","text":"jitter"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-jitter":{"title":"jitter","titleInlineContent":[{"text":"jitter","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-jitter"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","abstract":[{"type":"text","text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream."}],"role":"symbol","navigatorTitle":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","kind":"symbol","type":"topic","title":"MCReceivedRtpStreamStats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"jitter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"jitter","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"jitter","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"jitter","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1jitter\/title"},{"value":[{"text":"jitter","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1jitter\/fragments","op":"replace"},{"op":"replace","value":"MCReceivedRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title"},{"op":"replace","value":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments"}]}]}