{"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideotype\/iyuv"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/iyuv"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/iyuv"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"]]},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"iyuv"}],"navigatorTitle":[{"text":"MCVideoTypeIYUV","kind":"identifier"}],"title":"MCVideoType.iyuv","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@MCVideoType@MCVideoTypeIYUV"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"iyuv","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"kind":"symbol","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"title":"MCVideoType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoType","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","url":"\/documentation\/millicastsdk\/mcvideotype"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType/iyuv":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"iyuv","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoTypeIYUV","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType\/iyuv","title":"MCVideoType.iyuv","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype\/iyuv"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MCVideoTypeIYUV","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MCVideoTypeIYUV","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCVideoTypeIYUV"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"},{"op":"replace","value":[{"text":"MCVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1iyuv\/title","value":"MCVideoTypeIYUV","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType~1iyuv\/fragments","op":"replace","value":[{"text":"MCVideoTypeIYUV","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}