{"abstract":[{"type":"text","text":"Add a delegate to receive "},{"type":"codeVoice","code":"MCCMSampleBufferVideoRendererDelegate"},{"type":"text","text":" events, supports multiple delegates."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/addDelegate(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDelegate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","text":"MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/adddelegate(_:)"]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/adddelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addDelegate"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate","text":"MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":")"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"addDelegate:","kind":"identifier"}],"role":"symbol","title":"addDelegate(_:)","externalID":"c:objc(cs)MCCMSampleBufferVideoRenderer(im)addDelegate:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/addDelegate(_:)":{"title":"addDelegate(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addDelegate","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/addDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"addDelegate:"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/adddelegate(_:)","abstract":[{"type":"text","text":"Add a delegate to receive "},{"code":"MCCMSampleBufferVideoRendererDelegate","type":"codeVoice"},{"text":" events, supports multiple delegates.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe","title":"MCVideoFrame","abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true,"type":"reference"},{"text":" for playback.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"abstract":[{"text":"Delegate for  receiving raw video ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"type":"text","text":" ready for rendering"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","title":"MCCMSampleBufferVideoRendererDelegate","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"type":"topic","navigatorTitle":[{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"kind":"symbol","title":"MCCMSampleBufferVideoRenderer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"abstract":[{"text":"This class is responsible for converting ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","isActive":true},{"type":"text","text":"  into renderable "},{"code":"CMSampleBufferRef","type":"codeVoice"},{"type":"text","text":" frames."}],"navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"type":"topic","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"addDelegate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addDelegate:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCCMSampleBufferVideoRendererDelegate","text":"id<MCCMSampleBufferVideoRendererDelegate>"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"addDelegate:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1addDelegate(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1addDelegate(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","value":"MCCMSampleBufferVideoRendererDelegate"},{"value":[{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments"},{"value":"MCCMSampleBufferVideoRenderer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}