{"metadata":{"externalID":"c:objc(cs)MCSourceBuilder(im)setName:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setName"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!)","kind":"text"}],"role":"symbol","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"setName:"}],"title":"setName(_:)","roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setName","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"text":"Name of the source.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/setname(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/setname(_:)"]}],"abstract":[{"type":"text","text":"Set a name to the media source."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setName(_:)"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setName(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcebuilder\/setname(_:)","abstract":[{"type":"text","text":"Set a name to the media source."}],"navigatorTitle":[{"kind":"identifier","text":"setName:"}],"title":"setName(_:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setName(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"title":"MCSourceBuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceBuilder"}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsourcebuilder","abstract":[{"text":"Responsible for building a source object.","type":"text"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"setName:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setName:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setName(_:)\/title","op":"replace","value":"setName:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setName(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setName:"}],"op":"replace"},{"value":"MCSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title"},{"value":[{"kind":"identifier","text":"MCSourceBuilder"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments"}]}]}