{"variants":[{"paths":["\/documentation\/millicastsdk\/mcmedia\/getplaybackdevices()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcmedia\/getplaybackdevices()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getPlaybackDevices()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getPlaybackDevices","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"MCAudioPlayback","preciseIdentifier":"c:objc(cs)MCAudioPlayback","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An array of all available ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback"},{"type":"text","text":" devices."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Type Method","title":"getPlaybackDevices()","symbolKind":"method","externalID":"c:objc(cs)MCMedia(cm)getPlaybackDevices","navigatorTitle":[{"kind":"identifier","text":"getPlaybackDevices"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getPlaybackDevices","kind":"identifier"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:objc(cs)MCAudioPlayback","text":"MCAudioPlayback","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"abstract":[{"type":"text","text":"Query available audio playback devices and plugins."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"title":"MCMedia","url":"\/documentation\/millicastsdk\/mcmedia","abstract":[{"type":"text","text":"Class  used  for managing media sources."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMedia"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCMedia"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getPlaybackDevices()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getPlaybackDevices()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPlaybackDevices"},{"kind":"text","text":"() -> ["},{"text":"MCAudioPlayback","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioPlayback"},{"text":"]","kind":"text"}],"kind":"symbol","title":"getPlaybackDevices()","url":"\/documentation\/millicastsdk\/mcmedia\/getplaybackdevices()","type":"topic","navigatorTitle":[{"text":"getPlaybackDevices","kind":"identifier"}],"abstract":[{"type":"text","text":"Query available audio playback devices and plugins."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayback","title":"MCAudioPlayback","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"navigatorTitle":[{"text":"MCAudioPlayback","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"getPlaybackDevices","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getPlaybackDevices","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MCAudioPlayback *>"},{"text":" *) ","kind":"text"},{"text":"getPlaybackDevices","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title","value":"MCMedia","op":"replace"},{"value":[{"kind":"identifier","text":"MCMedia"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getPlaybackDevices()\/title","value":"getPlaybackDevices"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"getPlaybackDevices","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getPlaybackDevices()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioPlayback"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments"}]}]}