{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"case","navigatorTitle":[{"text":"MCInternalSDKErrorUnkown","kind":"identifier"}],"externalID":"c:@E@MCInternalSDKError@MCInternalSDKErrorUnkown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}],"title":"MCInternalSDKError.Code.unkown","roleHeading":"Case","role":"symbol"},"abstract":[{"text":"Uknown error.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/unkown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/unkown"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/unkown","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInternalSDKError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct","title":"MCInternalSDKError","abstract":[],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct","navigatorTitle":[{"text":"MCInternalSDKError","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code/unkown":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code\/unkown","title":"MCInternalSDKError.Code.unkown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code\/unkown","abstract":[{"type":"text","text":"Uknown error."}],"role":"symbol","navigatorTitle":[{"text":"MCInternalSDKErrorUnkown","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInternalSDKError-swift.struct/Code":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInternalSDKError-swift.struct\/Code","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinternalsdkerror-swift.struct\/code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"MCInternalSDKError.Code","abstract":[{"text":"Error category for unidentified errors. Usually representing a bug.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCInternalSDKErrorUnkown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKErrorUnkown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MCInternalSDKErrorUnkown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code~1unkown\/title","value":"MCInternalSDKErrorUnkown"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code~1unkown\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKErrorUnkown"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/title","value":"MCInternalSDKError"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInternalSDKError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCInternalSDKError"}]}]}]}