{"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"metadata":{"externalID":"c:objc(cs)MCWebrtcRemoteTrack(im)asVideo","navigatorTitle":[{"kind":"identifier","text":"asVideo"}],"title":"asVideo()","role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asVideo"},{"text":"() -> ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteVideoTrack"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asVideo()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asVideo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCWebrtcRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteVideoTrack"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"Nil if the track is not of a video type","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asvideo()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asvideo()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","type":"topic","role":"symbol","kind":"symbol","title":"MCWebrtcRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/asVideo()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"asVideo"}],"title":"asVideo()","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asVideo()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asVideo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteVideoTrack","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asvideo()","abstract":[{"type":"text","text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"title":"MCWebrtcRemoteVideoTrack","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"asVideo","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asVideo"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","text":"MCWebrtcRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteVideoTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"asVideo"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCWebrtcRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","op":"replace","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asVideo()\/title","value":"asVideo"},{"value":[{"text":"- ","kind":"text"},{"text":"asVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asVideo()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","value":"MCWebrtcRemoteVideoTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]}]}]}