{"abstract":[{"type":"text","text":"Delegate to receive track related events."}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/delegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/delegate"]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCWebrtcRemoteTrackDelegate","kind":"typeIdentifier","text":"MCWebrtcRemoteTrackDelegate"},{"text":")?","kind":"text"}],"title":"delegate","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","externalID":"c:objc(cs)MCWebrtcRemoteTrack(py)delegate"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"MCWebrtcRemoteTrackDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","preciseIdentifier":"c:objc(pl)MCWebrtcRemoteTrackDelegate","kind":"typeIdentifier"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/delegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/delegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/delegate","abstract":[{"text":"Delegate to receive track related events.","type":"text"}],"title":"delegate","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrackDelegate","preciseIdentifier":"c:objc(pl)MCWebrtcRemoteTrackDelegate"},{"kind":"text","text":")?"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteTrackDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrackDelegate","kind":"identifier"}],"title":"MCWebrtcRemoteTrackDelegate","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate","role":"symbol","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"delegate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<MCWebrtcRemoteTrackDelegate>","preciseIdentifier":"c:Qoobjc(pl)MCWebrtcRemoteTrackDelegate","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/title","value":"MCWebrtcRemoteTrackDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","value":"MCWebrtcRemoteTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","op":"replace","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}