{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/mid()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?>","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"a new AsyncStream","type":"text"}]}],"kind":"content"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)"},{"text":" ","type":"text"},{"type":"text","text":"for more information"}]}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/mid()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","title":"mid()","modules":[{"name":"MillicastSDK"}],"extendedModule":"MillicastSDK","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?>"}],"externalID":"s:So19MCWebrtcRemoteTrackC12MillicastSDKE3midScSySSSgGyF","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Create an AsyncStream that is invoked whenever the underlying mid gets"},{"type":"text","text":" "},{"type":"text","text":"updated."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"kind":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/mid()":{"kind":"symbol","title":"mid()","abstract":[{"type":"text","text":"Create an AsyncStream that is invoked whenever the underlying mid gets"},{"type":"text","text":" "},{"text":"updated.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/mid()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mid"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?>","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/mid()"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrack(_:didUpdateMID:)":{"kind":"symbol","navigatorTitle":[{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"title":"webrtcRemoteTrack(_:didUpdateMID:)","abstract":[{"text":"The event for updating the MID of the internal webrtc track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webrtcRemoteTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateMID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)"}},"variantOverrides":[{"patch":[{"value":"MCWebrtcRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/title","op":"replace","value":"webrtcRemoteTrack:didUpdateMID:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"webrtcRemoteTrack:didUpdateMID:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}