{"sections":[],"abstract":[{"type":"text","text":"The timestamp of the remote endpoint related to the stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","isActive":true,"type":"reference"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"remote_timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)remote_timestamp","roleHeading":"Instance Property","symbolKind":"property","title":"remote_timestamp","navigatorTitle":[{"text":"remote_timestamp","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"remote_timestamp","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_timestamp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_timestamp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_timestamp"]}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp":{"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","title":"remoteTimestamp","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","titleInlineContent":[{"type":"text","text":"remoteTimestamp"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics related to an outgoing remote RTP stream."}],"type":"topic","title":"MCRemoteOutboundRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/remote_timestamp":{"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_timestamp","abstract":[{"type":"text","text":"The timestamp of the remote endpoint related to the stream. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","type":"reference"}],"title":"remote_timestamp","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_timestamp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remote_timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"navigatorTitle":[{"text":"remote_timestamp","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"remote_timestamp","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"remote_timestamp","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:K","text":"long long"},{"text":" ","kind":"text"},{"text":"remote_timestamp","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"MCRemoteOutboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"},{"value":"remote_timestamp","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_timestamp\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_timestamp\/fragments","op":"replace","value":[{"text":"remote_timestamp","kind":"identifier"}]}]}]}