{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferFrame\/init(sampleBuffer:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","title":"init(sampleBuffer:)","externalID":"c:objc(cs)MCCMSampleBufferFrame(im)initWithSampleBuffer:","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:"}],"symbolKind":"init","role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebufferframe\/init(samplebuffer:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebufferframe\/init(samplebuffer:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"!(","kind":"text"},{"text":"sampleBuffer","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"codeListing","code":["let sampleBuffer: CMSampleBuffer = ...","let source = MCCustomAudioSourceBuilder().build()","source.onAudioFrame(MCCMSampleBufferFrame(sampleBuffer))"],"syntax":null}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferFrame"]]},"abstract":[{"type":"text","text":"Initialize with a "},{"type":"codeVoice","code":"CMSampleBuffer"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioFrame":{"role":"symbol","title":"MCAudioFrame","navigatorTitle":[{"kind":"identifier","text":"MCAudioFrame"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioFrame","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioFrame"}],"abstract":[{"type":"text","text":"Audio frame that contains audio data. Used with "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to feed custom audio frames into source used by a "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioframe"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferFrame":{"role":"symbol","kind":"symbol","title":"MCCMSampleBufferFrame","url":"\/documentation\/millicastsdk\/mccmsamplebufferframe","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"abstract":[{"type":"text","text":"Class responsible for initializing a "},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioFrame","type":"reference"},{"text":"  from a ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferFrame"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferFrame/init(sampleBuffer:)":{"url":"\/documentation\/millicastsdk\/mccmsamplebufferframe\/init(samplebuffer:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferFrame\/init(sampleBuffer:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSampleBuffer:"}],"kind":"symbol","abstract":[{"text":"Initialize with a ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"}],"type":"topic","title":"init(sampleBuffer:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSampleBuffer:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSampleBuffer:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSampleBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCAudioFrame","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioFrame\/title"},{"value":[{"kind":"identifier","text":"MCAudioFrame"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioFrame\/fragments"},{"value":"MCCMSampleBufferFrame","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/title"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/fragments"},{"value":"initWithSampleBuffer:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferFrame~1init(sampleBuffer:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSampleBuffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferFrame~1init(sampleBuffer:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}