{"abstract":[{"type":"text","text":"This handler is called when a new video frame becomes available, either captured or received."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer\/didReceive(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideorenderer\/didreceive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideorenderer\/didreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoFrame","text":"MCVideoFrame","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A raw video frame."}]}],"name":"frame"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didReceiveFrame:"}],"symbolKind":"method","required":true,"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"didReceive(_:)","externalID":"c:objc(pl)MCVideoRenderer(im)didReceiveFrame:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCVideoFrame","text":"MCVideoFrame","kind":"typeIdentifier"},{"kind":"text","text":")!)"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"text":" ","type":"text"},{"type":"text","text":"with "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true,"type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoFrame"}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","title":"MCVideoFrame"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer/didReceive(_:)":{"url":"\/documentation\/millicastsdk\/mcvideorenderer\/didreceive(_:)","navigatorTitle":[{"text":"didReceiveFrame:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"This handler is called when a new video frame becomes available, either captured or received."}],"type":"topic","title":"didReceive(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer\/didReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","text":"MCVideoFrame","preciseIdentifier":"c:objc(pl)MCVideoFrame"},{"kind":"text","text":")!)"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"role":"symbol","title":"add(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"didReceiveFrame:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didReceiveFrame:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"didReceiveFrame:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MCVideoFrame>","preciseIdentifier":"c:Qoobjc(pl)MCVideoFrame"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace","value":"MCVideoRenderer"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","value":"MCVideoFrame","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer~1didReceive(_:)\/title","value":"didReceiveFrame:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didReceiveFrame:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer~1didReceive(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"addRenderer:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}