{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStatsType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStatsType\/video","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"case","title":"MCTrackStatsType.video","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"navigatorTitle":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","externalID":"c:@E@MCTrackStatsType@MCTrackStatsTypeVideo"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrackstatstype\/video"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrackstatstype\/video"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStatsType":{"title":"MCTrackStatsType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCTrackStatsType"}],"url":"\/documentation\/millicastsdk\/mctrackstatstype","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStatsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCTrackStatsType"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStatsType/video":{"title":"MCTrackStatsType.video","type":"topic","navigatorTitle":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mctrackstatstype\/video","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStatsType\/video","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCTrackStatsTypeVideo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCTrackStatsTypeVideo"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStatsType\/title","value":"MCTrackStatsType","op":"replace"},{"value":[{"kind":"identifier","text":"MCTrackStatsType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStatsType\/fragments"},{"value":[{"kind":"identifier","text":"MCTrackStatsType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStatsType\/navigatorTitle"},{"value":"MCTrackStatsTypeVideo","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStatsType~1video\/title"},{"value":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStatsType~1video\/fragments"}]}]}