{"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/frames"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/frames"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"frames"}],"symbolKind":"property","title":"frames","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"frames","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCVideoSourceStats(py)frames"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats"]]},"sections":[],"abstract":[{"type":"text","text":"The number of frames. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames"}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-frames":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames","type":"link","title":"frames","titleInlineContent":[{"text":"frames","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceStats":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceStats"}],"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideosourcestats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoSourceStats","kind":"identifier"}],"title":"MCVideoSourceStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceStats/frames":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames","title":"frames","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frames"}],"kind":"symbol","abstract":[{"type":"text","text":"The number of frames. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/frames"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"frames","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"frames","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","text":"unsigned long","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frames"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/title","value":"MCVideoSourceStats","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/fragments","value":[{"kind":"identifier","text":"MCVideoSourceStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames\/title","op":"replace","value":"frames"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames\/fragments","value":[{"text":"frames","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}