{"sections":[],"abstract":[{"type":"text","text":"No degradation preference, lets the SDK decide how to handle over-utilization."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"MCDegradationPreferencesDefault","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"title":"MCDegradationPreferences.default","roleHeading":"Case","externalID":"c:@E@MCDegradationPreferences@MCDegradationPreferencesDefault","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/default"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/default"]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/default","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/default":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/default","role":"symbol","abstract":[{"type":"text","text":"No degradation preference, lets the SDK decide how to handle over-utilization."}],"navigatorTitle":[{"text":"MCDegradationPreferencesDefault","kind":"identifier"}],"kind":"symbol","title":"MCDegradationPreferences.default","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/default","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}]},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","title":"the WebRTC standard","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences","role":"symbol","navigatorTitle":[{"text":"MCDegradationPreferences","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"}],"title":"MCDegradationPreferences","abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true,"type":"reference"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCDegradationPreferencesDefault","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MCDegradationPreferencesDefault"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCDegradationPreferencesDefault","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MCDegradationPreferencesDefault","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1default\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1default\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferencesDefault"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","op":"replace","value":"MCDegradationPreferences"},{"value":[{"kind":"identifier","text":"MCDegradationPreferences"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}