{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The subscribing token.","type":"text"}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/token","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"token","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCSubscriberCredentials(py)token","roleHeading":"Instance Property","navigatorTitle":[{"text":"token","kind":"identifier"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/token"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/token"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"https://dash.millicast.com/docs.html":{"titleInlineContent":[{"text":"Streaming Dashboard","type":"text"}],"url":"https:\/\/dash.millicast.com\/docs.html","type":"link","identifier":"https:\/\/dash.millicast.com\/docs.html","title":"Streaming Dashboard"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberCredentials","kind":"identifier"}],"title":"MCSubscriberCredentials","abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"text":" ","type":"text"},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscribercredentials","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials/token":{"title":"token","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/token","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/token","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"token","kind":"identifier"}],"abstract":[{"text":"The subscribing token.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"token","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"token"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"token","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCSubscriberCredentials","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title"},{"value":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments"},{"value":"token","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1token\/title"},{"value":[{"text":"token","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1token\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}