{"sections":[],"abstract":[{"type":"text","text":"Connects to the media server directly using the websocket URL and the JSON Web Token."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:connectionoptions:completionhandler:)"]},{"paths":["\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:connectionoptions:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWebsocketUrl"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"connectionOptions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCConnectionOptions","text":"MCConnectionOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"symbolKind":"method","title":"connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"}],"externalID":"c:objc(pl)MCClient(im)connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"kind":"text","text":"("},{"text":"withWebsocketUrl","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"websocketUrl","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"connectionOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCConnectionOptions","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions","preciseIdentifier":"c:objc(cs)MCConnectionOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Connection options. Can be used for example to disable ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"connectionOptions"},{"name":"websocketUrl","content":[{"type":"paragraph","inlineContent":[{"text":"The websocket URL returned by the Director API.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON Web Token returned by the Director API."}]}],"name":"jwt"},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Handler invoked when the result is ready."}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"type":"topic","title":"MCSubscriber","role":"symbol","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"title":"MCClient","url":"\/documentation\/millicastsdk\/mcclient","navigatorTitle":[{"kind":"identifier","text":"MCClient"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"abstract":[{"type":"text","text":"The Client base that contains common methods between "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","type":"reference"},{"type":"text","text":"."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionOptions/autoReconnect":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"autoReconnect","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoReconnect"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"autoReconnect","abstract":[{"text":"Attempts to reconnect by default in case of connection error or network dropout. Enabled by default","type":"text"}],"url":"\/documentation\/millicastsdk\/mcconnectionoptions\/autoreconnect"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)":{"required":true,"title":"connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","url":"\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:connectionoptions:completionhandler:)","navigatorTitle":[{"text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"connect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWebsocketUrl"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"jwt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionOptions"},{"kind":"text","text":": "},{"text":"MCConnectionOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCConnectionOptions"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Connects to the media server directly using the websocket URL and the JSON Web Token."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCConnectionOptions","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions","title":"MCConnectionOptions","abstract":[{"text":"The MCConnectionOptions class gathers connection options.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MCConnectionOptions","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcconnectionoptions"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"connectWithWebsocketUrl:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"websocketUrl"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jwt:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"jwt"},{"kind":"text","text":" "},{"text":"connectionOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCConnectionOptions","text":"MCConnectionOptions","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions"},{"text":" *) ","kind":"text"},{"text":"connectionOptions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"text":"MCSubscriber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title","value":"MCClient","op":"replace"},{"value":[{"text":"MCClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/title","value":"autoReconnect","op":"replace"},{"value":[{"kind":"identifier","text":"autoReconnect"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/fragments"},{"op":"replace","value":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions\/title","value":"MCConnectionOptions","op":"replace"},{"value":[{"text":"MCConnectionOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}