{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmedia\/isndiavailable()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcmedia\/isndiavailable()"]}],"abstract":[{"text":"Checks whether NDI support is enabled in the SDK.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/isNdiAvailable()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNdiAvailable"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:objc(cs)MCMedia(cm)isNdiAvailable","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Type Method","title":"isNdiAvailable()","navigatorTitle":[{"kind":"identifier","text":"isNdiAvailable"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isNdiAvailable","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Whether NDI is available (true) or not (false).","type":"text"}]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/isNdiAvailable()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/isNdiAvailable()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcmedia\/isndiavailable()","navigatorTitle":[{"text":"isNdiAvailable","kind":"identifier"}],"role":"symbol","title":"isNdiAvailable()","abstract":[{"type":"text","text":"Checks whether NDI support is enabled in the SDK."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNdiAvailable"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"title":"MCMedia","url":"\/documentation\/millicastsdk\/mcmedia","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCMedia","kind":"identifier"}],"type":"topic","abstract":[{"text":"Class  used  for managing media sources.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia","kind":"symbol","navigatorTitle":[{"text":"MCMedia","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"isNdiAvailable","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"isNdiAvailable"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"kind":"text","text":") "},{"text":"isNdiAvailable","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1isNdiAvailable()\/title","value":"isNdiAvailable"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1isNdiAvailable()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"isNdiAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title","value":"MCMedia"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments","value":[{"kind":"identifier","text":"MCMedia"}]}]}]}