{"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t2"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T2"}],"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL3T2","title":"MCScalabilityMode.l3t2"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t2"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t2"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t2"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t2"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true},{"text":" to understand where these values come from","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCScalabilityMode","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","title":"MCScalabilityMode"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","type":"link","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l3t2":{"abstract":[],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t2","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T2"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"l3t2","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t2","title":"MCScalabilityMode.l3t2","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCScalabilityModeL3T2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL3T2","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCScalabilityModeL3T2"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCScalabilityMode","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t2\/title","value":"MCScalabilityModeL3T2"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t2\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeL3T2"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}