{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"s2t1"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1"]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"MCScalabilityModeS2T1","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS2T1","modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Case","title":"MCScalabilityMode.s2t1","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t1","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true},{"text":" to understand where these values come from","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCScalabilityMode","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","title":"MCScalabilityMode"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/s2t1":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T1"}],"role":"symbol","type":"topic","kind":"symbol","title":"MCScalabilityMode.s2t1","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"s2t1"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCScalabilityModeS2T1"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MCScalabilityModeS2T1","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MCScalabilityModeS2T1","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCScalabilityMode","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title"},{"value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1\/title","value":"MCScalabilityModeS2T1"},{"value":[{"text":"MCScalabilityModeS2T1","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1\/fragments","op":"replace"}]}]}