{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCIosVideoRendererDelegate","text":"MCIosVideoRendererDelegate"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCIosVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCIosVideoRendererDelegate"},{"kind":"text","text":"!"}],"title":"delegate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCIosVideoRenderer(py)delegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer":{"role":"symbol","title":"MCIosVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCIosVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCIosVideoRendererDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/delegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRendererDelegate":{"role":"symbol","title":"MCIosVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRendererDelegate"}],"abstract":[{"type":"text","text":"Protocol that allows subscribing to callbacks that inform about rendering video frame size changes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRendererDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRendererDelegate"}],"url":"\/documentation\/millicastsdk\/mciosvideorendererdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MCIosVideoRendererDelegate>","preciseIdentifier":"c:Qoobjc(pl)MCIosVideoRendererDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRendererDelegate\/title","value":"MCIosVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRendererDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}