{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)MCCodecsStats(cm)get_type","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"get_type","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"}],"modules":[{"name":"MillicastSDK"}],"title":"get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"roleHeading":"Type Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/get_type()","interfaceLanguage":"swift"},"abstract":[{"text":"The type of statistics.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"the type of statistics.","type":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/get_type()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/get_type()"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Different types of statistics."}],"navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"title":"MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/get_type()":{"url":"\/documentation\/millicastsdk\/mccodecsstats\/get_type()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/get_type()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"abstract":[{"text":"The type of statistics.","type":"text"}],"title":"get_type()","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","type":"topic","navigatorTitle":[{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats","kind":"symbol","title":"MCCodecsStats"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"get_type"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"get_type"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"value":[{"text":"MCStatsType","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1get_type()\/title","op":"replace","value":"get_type"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","value":[{"kind":"identifier","text":"MCCodecsStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}