{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The maximum bitrate, in kilobits per second.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/maxbitratekbps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/maxbitratekbps"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/maxBitrateKbps","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCBitrateSettings(py)maxBitrateKbps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"maxBitrateKbps","navigatorTitle":[{"text":"maxBitrateKbps","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings/maxBitrateKbps":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/maxBitrateKbps","abstract":[{"type":"text","text":"The maximum bitrate, in kilobits per second."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrateKbps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"maxBitrateKbps","url":"\/documentation\/millicastsdk\/mcbitratesettings\/maxbitratekbps","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxBitrateKbps"}],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","navigatorTitle":[{"kind":"identifier","text":"MCBitrateSettings"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcbitratesettings","role":"symbol","title":"MCBitrateSettings","abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCBitrateSettings"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maxBitrateKbps"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"maxBitrateKbps","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"maxBitrateKbps","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1maxBitrateKbps\/title","value":"maxBitrateKbps","op":"replace"},{"value":[{"text":"maxBitrateKbps","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1maxBitrateKbps\/fragments","op":"replace"},{"value":"MCBitrateSettings","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCBitrateSettings"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCBitrateSettings"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}