{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/currentProjection(completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Get the RTS track which is currently projected onto this webrtc track."}],"metadata":{"externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack(im)currentProjectionWithCompletionHandler:","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentProjection"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"currentProjectionWithCompletionHandler:"}],"title":"currentProjection(completionHandler:)","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/currentprojection(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/currentprojection(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentProjection"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ("},{"text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"kind":"text","text":"?, (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the asynchronous operation completes.","type":"text"},{"text":" ","type":"text"},{"text":"On error, the track returned will be nil and the error parameter will be set appropriately.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Otherwise, a non-nulll remote track will be returned if the current track is projected. Otherwise,"},{"type":"text","text":" "},{"text":"nil is returned.","type":"text"}]}],"name":"completionHandler"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Note: properly written applicatioprojectWithRTSRemoteVideoTrack:layer:promote:completionHandler:nous status","type":"text"},{"type":"text","text":" "},{"text":"of the ","type":"text"},{"type":"codeVoice","code":"MCWebrtcRemoteVideoTrack\/projectWithRTSRemoteVideoTrack"},{"text":" operation only.","type":"text"}]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/currentProjection(completionHandler:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"currentProjection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"currentProjectionWithCompletionHandler:","kind":"identifier"}],"title":"currentProjection(completionHandler:)","abstract":[{"type":"text","text":"Get the RTS track which is currently projected onto this webrtc track."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/currentprojection(completionhandler:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/currentProjection(completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"title":"MCRTSRemoteVideoTrack","abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"title":"MCWebrtcRemoteVideoTrack","abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"currentProjectionWithCompletionHandler:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"currentProjectionWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"currentProjectionWithCompletionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"MCRTSRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1currentProjection(completionHandler:)\/title","op":"replace","value":"currentProjectionWithCompletionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1currentProjection(completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"currentProjectionWithCompletionHandler:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack","op":"replace"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments"},{"value":"MCWebrtcRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}]}]}]}