{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource\/init(recorder:)"]},{"paths":["\/documentation\/millicastsdk\/mcappsharesource\/init(recorder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initializes the source with a recorder.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)RPScreenRecorder","kind":"typeIdentifier","text":"RPScreenRecorder"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithRecorder:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"init","externalID":"c:objc(cs)MCAppShareSource(im)initWithRecorder:","title":"init(recorder:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RPScreenRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)RPScreenRecorder"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A ReplayKit recorder.","type":"text"}]}],"name":"recorder"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource\/init(recorder:)","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAppShareSource/init(recorder:)":{"type":"topic","title":"init(recorder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)RPScreenRecorder","text":"RPScreenRecorder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Initializes the source with a recorder.","type":"text"}],"navigatorTitle":[{"text":"initWithRecorder:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcappsharesource\/init(recorder:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource\/init(recorder:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAppShareSource":{"navigatorTitle":[{"text":"MCAppShareSource","kind":"identifier"}],"kind":"symbol","title":"MCAppShareSource","abstract":[{"text":"Uses Replaykit to capture the screen of the application.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource","type":"topic","url":"\/documentation\/millicastsdk\/mcappsharesource","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithRecorder:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRecorder:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithRecorder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)RPScreenRecorder","text":"RPScreenRecorder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"recorder"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithRecorder:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource~1init(recorder:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithRecorder:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource~1init(recorder:)\/fragments"},{"value":"MCAppShareSource","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCAppShareSource"}]}]}]}