{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/codec_id","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/codec_id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/codec_id"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec_id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The identifier of the codec used for encoding media carried by the stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid","isActive":true,"type":"reference"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:objc(cs)MCRtpStreamStats(py)codec_id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"codec_id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"codec_id","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"codec_id"}],"symbolKind":"property","role":"symbol","modules":[{"name":"MillicastSDK"}]},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/codec_id":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"codec_id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/codec_id","title":"codec_id","type":"topic","abstract":[{"text":"The identifier of the codec used for encoding media carried by the stream. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid","isActive":true}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/codec_id","navigatorTitle":[{"text":"codec_id","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRtpStreamStats","kind":"identifier"}],"title":"MCRtpStreamStats","kind":"symbol","type":"topic","abstract":[{"text":"Statistics for an RTP stream.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-codecid":{"titleInlineContent":[{"type":"text","text":"codecId"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid","type":"link","title":"codecId","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"codec_id"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"codec_id"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"codec_id"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"codec_id","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1codec_id\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1codec_id\/fragments","value":[{"text":"codec_id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title","value":"MCRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCRtpStreamStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}