{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats"]]},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoderImplementation"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"decoderImplementation","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"decoderImplementation","kind":"identifier"}],"externalID":"c:objc(cs)MCTrackStats(py)decoderImplementation"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/decoderImplementation","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decoderImplementation"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrackstats\/decoderimplementation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrackstats\/decoderimplementation"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats/decoderImplementation":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/decoderImplementation","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"decoderImplementation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"decoderImplementation"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/decoderimplementation","title":"decoderImplementation","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats":{"url":"\/documentation\/millicastsdk\/mctrackstats","title":"MCTrackStats","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrackStats"}],"navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"decoderImplementation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"decoderImplementation"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"decoderImplementation"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1decoderImplementation\/title","op":"replace","value":"decoderImplementation"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1decoderImplementation\/fragments","op":"replace","value":[{"text":"decoderImplementation","kind":"identifier"}]},{"value":"MCTrackStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/title","op":"replace"},{"value":[{"text":"MCTrackStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}