{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledErrorDomain","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"roleHeading":"Global Variable","title":"MCAsyncOperationCancelledErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","externalID":"c:@MCAsyncOperationCancelledErrorDomain","modules":[{"name":"MillicastSDK"}],"symbolKind":"var","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederrordomain"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederrordomain"]}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledErrorDomain":{"title":"MCAsyncOperationCancelledErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAsyncOperationCancelledErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederrordomain","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledErrorDomain","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCAsyncOperationCancelledErrorDomain","path":"\/metadata\/title"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledErrorDomain\/title","value":"MCAsyncOperationCancelledErrorDomain","op":"replace"},{"value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorDomain"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledErrorDomain\/fragments"}]}]}