{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Gathers audio\/video codec statistics.","type":"text"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecsStats"}],"roleHeading":"Class","symbolKind":"class","title":"MCCodecsStats","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCCodecsStats"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/channels","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/clock_rate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/codec_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/mime_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/payload_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/sdp_fmtp_line","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/transport_id"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/get_type()"]}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-sdpfmtpline":{"titleInlineContent":[{"type":"text","text":"sdpFmtpLine"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline","title":"sdpFmtpLine","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-payloadtype":{"titleInlineContent":[{"type":"text","text":"payloadType"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","title":"payloadType","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/transport_id":{"title":"transport_id","abstract":[{"type":"text","text":"See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-transportid","isActive":true}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"transport_id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/transport_id","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/transport_id","navigatorTitle":[{"kind":"identifier","text":"transport_id"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/clock_rate":{"title":"clock_rate","abstract":[{"text":"The clock rate of the codec, indicating the frequency at which samples are generated or processed. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clock_rate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/clock_rate","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/clock_rate","navigatorTitle":[{"kind":"identifier","text":"clock_rate"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/codec_type":{"title":"codec_type","abstract":[{"type":"text","text":"Whether these stastics are for the encoder or the decoder."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"codec_type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCCodecStatsType","kind":"typeIdentifier","text":"MCCodecStatsType"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/codec_type","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/codec_type","navigatorTitle":[{"text":"codec_type","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/get_type()":{"title":"get_type()","abstract":[{"text":"The type of statistics.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/get_type()","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/get_type()","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"role":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-channels":{"titleInlineContent":[{"text":"channels","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels","title":"channels","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels"},"https://w3c.github.io/webrtc-stats/#introduction":{"titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/sdp_fmtp_line":{"title":"sdp_fmtp_line","abstract":[{"type":"text","text":"The Session Description Protocol (SDP) line associated with the codec. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline","type":"reference","isActive":true}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdp_fmtp_line"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/sdp_fmtp_line","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/sdp_fmtp_line","navigatorTitle":[{"text":"sdp_fmtp_line","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"title":"MCCodecsStats","abstract":[{"text":"Gathers audio\/video codec statistics.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstats","title":"MCStats"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/channels":{"title":"channels","abstract":[{"type":"text","text":"When present, indicates the number of channels (mono=1, stereo=2). See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-channels","isActive":true,"type":"reference"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"channels","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/channels","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/channels","navigatorTitle":[{"kind":"identifier","text":"channels"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/mime_type":{"type":"topic","title":"mime_type","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/mime_type","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/mime_type","abstract":[{"text":"The Multipurpose Internet Mail Extensions (MIME) type associated with the codec. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype","isActive":true}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mime_type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"mime_type","kind":"identifier"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-transportid":{"titleInlineContent":[{"type":"text","text":"transportId"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-transportid","title":"transportId","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-transportid"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/payload_type":{"type":"topic","title":"payload_type","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/payload_type","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecsstats\/payload_type","abstract":[{"type":"text","text":"The unique identifier for the codec payload type. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payload_type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"payload_type"}]},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-mimetype":{"titleInlineContent":[{"type":"text","text":"mimeType"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype","title":"mimeType","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-mimetype"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-clockrate":{"titleInlineContent":[{"type":"text","text":"clockRate"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate","title":"clockRate","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MCCodecsStats","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"MCCodecsStats","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCCodecsStats","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/channels","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/clock_rate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/codec_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/mime_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/payload_type","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/sdp_fmtp_line","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/transport_id"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/get_type()"]}]},{"op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MCCodecsStats","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"MCStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","preciseIdentifier":"c:objc(cs)MCStats"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"transport_id","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1transport_id\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1transport_id\/fragments","value":[{"kind":"identifier","text":"transport_id"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1clock_rate\/title","op":"replace","value":"clock_rate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1clock_rate\/fragments","value":[{"kind":"identifier","text":"clock_rate"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1codec_type\/title","value":"codec_type","op":"replace"},{"op":"replace","value":[{"text":"codec_type","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1codec_type\/fragments"},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1get_type()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1get_type()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"get_type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1sdp_fmtp_line\/title","value":"sdp_fmtp_line"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1sdp_fmtp_line\/fragments","op":"replace","value":[{"text":"sdp_fmtp_line","kind":"identifier"}]},{"value":"MCCodecsStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","op":"replace","value":[{"text":"MCCodecsStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","value":"MCStats","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments","op":"replace","value":[{"text":"MCStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1channels\/title","value":"channels","op":"replace"},{"value":[{"kind":"identifier","text":"channels"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1channels\/fragments"},{"value":"mime_type","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1mime_type\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"mime_type"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1mime_type\/fragments"},{"value":"payload_type","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1payload_type\/title"},{"value":[{"kind":"identifier","text":"payload_type"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1payload_type\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}