{"metadata":{"role":"symbol","title":"MCDegradationPreferences","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCDegradationPreferences"}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCDegradationPreferences","roleHeading":"Enumeration","symbolKind":"enum"},"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/balanced","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/default","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/disabled","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainFrameRate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainResolution"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/RawRepresentable-Implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"text":"The DegradationPreferences enum. Based on ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDegradationPreferences"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/default":{"role":"symbol","kind":"symbol","title":"MCDegradationPreferences.default","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/default","type":"topic","abstract":[{"text":"No degradation preference, lets the SDK decide how to handle over-utilization.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesDefault"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/default"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"type":"link","title":"the WebRTC standard","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/RawRepresentable-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/rawrepresentable-implementations"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/maintainResolution":{"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainresolution","abstract":[{"type":"text","text":"On over-use, requests lower frame rate, possibly causing frame drops."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"maintainResolution","kind":"identifier"}],"role":"symbol","type":"topic","title":"MCDegradationPreferences.maintainResolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainResolution","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainResolution"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/Equatable-Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/equatable-implementations","title":"Equatable Implementations","kind":"article"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDegradationPreferences"}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"title":"MCDegradationPreferences","abstract":[{"text":"The DegradationPreferences enum. Based on ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true,"type":"reference"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences","role":"symbol","type":"topic"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/maintainFrameRate":{"title":"MCDegradationPreferences.maintainFrameRate","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainFrameRate","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainframerate","abstract":[{"text":"On over-use, requests lower resolution, possibly causing down-scaling.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maintainFrameRate"}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainFrameRate"}]},"doc://MillicastSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/MillicastSDK\/SY","type":"unresolvable"},"doc://MillicastSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/MillicastSDK\/s8SendableP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/disabled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabled"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesDisabled"}],"title":"MCDegradationPreferences.disabled","type":"topic","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/disabled","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/disabled","abstract":[{"text":"Does not take any actions based on over-utilization signals.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/init(rawvalue:)","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/init(rawValue:)","title":"init(rawValue:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/balanced":{"navigatorTitle":[{"text":"MCDegradationPreferencesBalanced","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/balanced","abstract":[{"text":"Tries to strike a pleasing balance between frame rate or resolution.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/balanced","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"balanced","kind":"identifier"}],"role":"symbol","title":"MCDegradationPreferences.balanced","type":"topic"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"MCDegradationPreferences","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCDegradationPreferences","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MCDegradationPreferences"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/balanced","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/default","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/disabled","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainFrameRate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainResolution"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1default\/title","value":"MCDegradationPreferencesDefault"},{"value":[{"kind":"identifier","text":"MCDegradationPreferencesDefault"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1default\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainResolution\/title","value":"MCDegradationPreferencesMaintainResolution"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainResolution\/fragments","value":[{"text":"MCDegradationPreferencesMaintainResolution","kind":"identifier"}],"op":"replace"},{"value":"MCDegradationPreferences","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/title"},{"value":[{"text":"MCDegradationPreferences","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","op":"replace"},{"value":"MCDegradationPreferencesMaintainFrameRate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainFrameRate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainFrameRate\/fragments","value":[{"text":"MCDegradationPreferencesMaintainFrameRate","kind":"identifier"}]},{"value":"MCDegradationPreferencesDisabled","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1disabled\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1disabled\/fragments","value":[{"text":"MCDegradationPreferencesDisabled","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MCDegradationPreferencesBalanced","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1balanced\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1balanced\/fragments","value":[{"text":"MCDegradationPreferencesBalanced","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}