{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHTTPConnectionError"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mchttpconnectionerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mchttpconnectionerror"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","type":"conformsTo"}],"abstract":[{"text":"Container class for HTTP errors that occur during","type":"text"},{"type":"text","text":" "},{"text":"connection to the millicast service","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"kind":"symbol","metadata":{"role":"symbol","title":"MCHTTPConnectionError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHTTPConnectionError"}],"navigatorTitle":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCHTTPConnectionError","roleHeading":"Class","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/code-c.property","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/reason-c.property"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError/code-c.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[{"type":"text","text":"The HTTP error code."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/code-c.property","title":"code","role":"symbol","url":"\/documentation\/millicastsdk\/mchttpconnectionerror\/code-c.property","navigatorTitle":[{"text":"code","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError/reason-c.property":{"abstract":[{"text":"The HTTP error reason.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mchttpconnectionerror\/reason-c.property","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/reason-c.property","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"reason","navigatorTitle":[{"kind":"identifier","text":"reason"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError/code-c.ivar":{"url":"\/documentation\/millicastsdk\/mchttpconnectionerror\/code-c.ivar","title":"code","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/code-c.ivar","kind":"symbol","fragments":[{"text":"code","kind":"identifier"}]},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError/reason-c.ivar":{"url":"\/documentation\/millicastsdk\/mchttpconnectionerror\/reason-c.ivar","title":"reason","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/reason-c.ivar","kind":"symbol","fragments":[{"text":"reason","kind":"identifier"}]},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHTTPConnectionError"}],"abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"text":" ","type":"text"},{"text":"connection to the millicast service","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","role":"symbol","url":"\/documentation\/millicastsdk\/mchttpconnectionerror","navigatorTitle":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"type":"topic","title":"MCHTTPConnectionError"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"MCHTTPConnectionError","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/code-c.ivar","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/reason-c.ivar"],"title":"Instance Variables"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/code-c.property","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError\/reason-c.property"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCHTTPConnectionError","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError~1code-c.property\/title","value":"code"},{"value":[{"kind":"identifier","text":"code"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError~1code-c.property\/fragments"},{"value":"reason","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError~1reason-c.property\/title"},{"op":"replace","value":[{"kind":"identifier","text":"reason"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError~1reason-c.property\/fragments"},{"op":"replace","value":"MCHTTPConnectionError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title"},{"op":"replace","value":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}