{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Represents resolution of a video frame.","type":"text"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/width"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"roleHeading":"Class","role":"symbol","title":"MCRTSRemoteVideoTrackLayerResolution","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represents resolution of a video frame."}],"title":"MCRTSRemoteVideoTrackLayerResolution","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution/width":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"Width in pixels"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/width","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution\/width"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution/height":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/height","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Height in pixels"}],"title":"height","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution\/height","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"height"}]},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCRTSRemoteVideoTrackLayerResolution","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/width"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/title","op":"replace","value":"MCRTSRemoteVideoTrackLayerResolution"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1width\/title","op":"replace","value":"width"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1width\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1height\/fragments","value":[{"kind":"identifier","text":"height"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}