{"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/feedId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/publisherId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/uuid"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStreamPublishDetails","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstreampublishdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstreampublishdetails"]}],"metadata":{"title":"MCStreamPublishDetails","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStreamPublishDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCStreamPublishDetails"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCStreamPublishDetails","role":"symbol","roleHeading":"Class"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails/streamId":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"streamId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails\/streamid","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"streamId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/streamId","title":"streamId"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails/publisherId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publisherId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails\/publisherid","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publisherId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/publisherId","title":"publisherId"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails/feedId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"feedId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails\/feedid","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"feedId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/feedId","title":"feedId"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails/uuid":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uuid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails\/uuid","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"uuid","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/uuid","title":"uuid"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails/clusterId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clusterId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails\/clusterid","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"clusterId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/clusterId","title":"clusterId"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStreamPublishDetails","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstreampublishdetails","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCStreamPublishDetails","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails","title":"MCStreamPublishDetails"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCStreamPublishDetails","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCStreamPublishDetails","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCStreamPublishDetails"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/feedId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/publisherId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails\/uuid"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MCStreamPublishDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1streamId\/title","value":"streamId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1streamId\/fragments","value":[{"kind":"identifier","text":"streamId"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1publisherId\/title","value":"publisherId","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"publisherId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1publisherId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1feedId\/title","value":"feedId"},{"op":"replace","value":[{"kind":"identifier","text":"feedId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1feedId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1uuid\/title","value":"uuid"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1uuid\/fragments","value":[{"kind":"identifier","text":"uuid"}]},{"value":"clusterId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1clusterId\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails~1clusterId\/fragments","op":"replace","value":[{"kind":"identifier","text":"clusterId"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails\/title","value":"MCStreamPublishDetails","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails\/fragments","op":"replace","value":[{"text":"MCStreamPublishDetails","kind":"identifier"}]}]}]}