{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentRoundTripTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/currentRoundTripTime","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstats\/currentroundtriptime"]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberstats\/currentroundtriptime"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"currentRoundTripTime","externalID":"c:objc(cs)MCSubscriberStats(py)currentRoundTripTime","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentRoundTripTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currentRoundTripTime","kind":"identifier"}],"roleHeading":"Instance Property"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats":{"title":"MCSubscriberStats","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStats"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberStats"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats/currentRoundTripTime":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats\/currentRoundTripTime","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"currentRoundTripTime"}],"title":"currentRoundTripTime","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstats\/currentroundtriptime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentRoundTripTime"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"currentRoundTripTime","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"currentRoundTripTime","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"currentRoundTripTime"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/title","op":"replace","value":"MCSubscriberStats"},{"op":"replace","value":[{"text":"MCSubscriberStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1currentRoundTripTime\/title","value":"currentRoundTripTime","op":"replace"},{"value":[{"kind":"identifier","text":"currentRoundTripTime"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats~1currentRoundTripTime\/fragments"}]}]}