{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivertsremotetrack:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivertsremotetrack:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCSubscriber","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveRTSRemoteTrack","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast subscriber."}]}],"name":"subscriber"},{"content":[{"inlineContent":[{"text":"A remote published track.","type":"text"}],"type":"paragraph"}],"name":"didReceiveRtsRemoteTrack"}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"text":"subscriber:didReceiveRTSRemoteTrack:","kind":"identifier"}],"externalID":"c:objc(pl)MCSubscriberDelegate(im)subscriber:didReceiveRTSRemoteTrack:","title":"subscriber(_:didReceiveRTSRemoteTrack:)","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"text":", ","kind":"text"},{"text":"didReceiveRTSRemoteTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveRTSRemoteTrack:)","interfaceLanguage":"swift"},"abstract":[{"text":"Called when a new remote track has been added","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"title":"MCSubscriber"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberDelegate":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"role":"symbol","title":"MCSubscriberDelegate","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberDelegate/subscriber(_:didReceiveRTSRemoteTrack:)":{"abstract":[{"type":"text","text":"Called when a new remote track has been added"}],"role":"symbol","kind":"symbol","title":"subscriber(_:didReceiveRTSRemoteTrack:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveRTSRemoteTrack:)","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivertsremotetrack:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriber"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRTSRemoteTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscriber:didReceiveRTSRemoteTrack:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"subscriber:didReceiveRTSRemoteTrack:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"subscriber:didReceiveRTSRemoteTrack:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"subscriber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCSubscriber","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"subscriber"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRTSRemoteTrack:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rtsRemoteTrack"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCSubscriber","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace"},{"value":"MCSubscriberDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","op":"replace"},{"value":"subscriber:didReceiveRTSRemoteTrack:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveRTSRemoteTrack:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscriber:didReceiveRTSRemoteTrack:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveRTSRemoteTrack:)\/fragments","op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}