{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/canhandlemoreframes()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/canhandlemoreframes()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/canHandleMoreFrames()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implement this method and return true to accept a sample buffer. Otherwise, the frame is dropped."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"canHandleMoreFrames"}],"role":"symbol","title":"canHandleMoreFrames()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate(im)canHandleMoreFrames","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"role":"symbol","title":"MCCMSampleBufferVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"abstract":[{"type":"text","text":"Delegate for  receiving raw video "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" ready for rendering"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate/canHandleMoreFrames()":{"navigatorTitle":[{"kind":"identifier","text":"canHandleMoreFrames"}],"role":"symbol","title":"canHandleMoreFrames()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Implement this method and return true to accept a sample buffer. Otherwise, the frame is dropped."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/canHandleMoreFrames()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/canhandlemoreframes()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canHandleMoreFrames"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canHandleMoreFrames"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"_Bool","preciseIdentifier":"c:b"},{"kind":"text","text":") "},{"kind":"identifier","text":"canHandleMoreFrames"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","value":"MCCMSampleBufferVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1canHandleMoreFrames()\/title","value":"canHandleMoreFrames"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1canHandleMoreFrames()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canHandleMoreFrames"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}