{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxSpatialLayerId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/maxspatiallayerid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/maxspatiallayerid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxSpatialLayerId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxSpatialLayerId","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"maxSpatialLayerId","externalID":"c:objc(cs)MCRTSRemoteTrackLayer(py)maxSpatialLayerId","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"maxSpatialLayerId"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/maxSpatialLayerId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxSpatialLayerId"}],"title":"maxSpatialLayerId","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/maxspatiallayerid","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/maxSpatialLayerId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxSpatialLayerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}],"title":"MCRTSRemoteTrackLayer","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"maxSpatialLayerId","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maxSpatialLayerId","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"maxSpatialLayerId"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"maxSpatialLayerId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxSpatialLayerId\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1maxSpatialLayerId\/fragments","op":"replace","value":[{"kind":"identifier","text":"maxSpatialLayerId"}]},{"value":"MCRTSRemoteTrackLayer","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"op":"replace"}]}]}