{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisherDidReceiveFirstViewerActive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"publisher"},{"kind":"text","text":": "},{"text":"MCPublisher","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast publisher."}]}],"name":"publisher"}]}],"metadata":{"title":"publisherDidReceiveFirstViewerActive(_:)","externalID":"c:objc(pl)MCPublisherDelegate(im)publisherDidReceiveFirstViewerActive:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publisherDidReceiveFirstViewerActive","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCPublisher","text":"MCPublisher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"publisherDidReceiveFirstViewerActive:","kind":"identifier"}],"required":true,"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivefirstvieweractive(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivefirstvieweractive(_:)"]}],"abstract":[{"type":"text","text":"Called when the first viewer is viewing the stream."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/publisherDidReceiveFirstViewerActive(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"]]},"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"url":"\/documentation\/millicastsdk\/mcpublisherdelegate","role":"symbol","kind":"symbol","abstract":[{"text":"This delegate  acts as a listener for the Publisher class.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You must implement this protocol and set a delegate."},{"text":" ","type":"text"},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/publisherDidReceiveFirstViewerActive(_:)":{"abstract":[{"type":"text","text":"Called when the first viewer is viewing the stream."}],"title":"publisherDidReceiveFirstViewerActive(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"publisherDidReceiveFirstViewerActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCPublisher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisher"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"publisherDidReceiveFirstViewerActive:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/publisherDidReceiveFirstViewerActive(_:)","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivefirstvieweractive(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"publisherDidReceiveFirstViewerActive:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"publisherDidReceiveFirstViewerActive:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"publisherDidReceiveFirstViewerActive:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","text":"MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"publisher","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"MCPublisherDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"text":"MCPublisherDelegate","kind":"identifier"}]},{"value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1publisherDidReceiveFirstViewerActive(_:)\/title","value":"publisherDidReceiveFirstViewerActive:","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1publisherDidReceiveFirstViewerActive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publisherDidReceiveFirstViewerActive:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}