{"abstract":[{"type":"text","text":"The local identifier associated with the outbound RTP stream. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"local_id","kind":"identifier"}],"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)local_id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"local_id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"local_id"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/local_id","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"local_id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/local_id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/local_id"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/local_id":{"kind":"symbol","role":"symbol","title":"local_id","navigatorTitle":[{"text":"local_id","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"local_id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/local_id","type":"topic","abstract":[{"text":"The local identifier associated with the outbound RTP stream. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid","isActive":true}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/local_id"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"role":"symbol","title":"MCRemoteOutboundRtpStreamStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics related to an outgoing remote RTP stream."}],"navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-localid":{"title":"localId","titleInlineContent":[{"text":"localId","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"local_id","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"local_id","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"local_id"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1local_id\/title","op":"replace","value":"local_id"},{"value":[{"text":"local_id","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1local_id\/fragments","op":"replace"},{"value":"MCRemoteOutboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}]}]}]}