{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The socket has now established a connection."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"title":"MCConnectionState.connected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCConnectionState@MCConnectionStateConnected","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateConnected"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"role":"symbol","title":"MCConnectionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCConnectionState"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCConnectionState"}],"url":"\/documentation\/millicastsdk\/mcconnectionstate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/connected":{"role":"symbol","title":"MCConnectionState.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"The socket has now established a connection."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateConnected"}],"url":"\/documentation\/millicastsdk\/mcconnectionstate\/connected"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCConnectionStateConnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCConnectionStateConnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCConnectionStateConnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title","value":"MCConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments","value":[{"kind":"identifier","text":"MCConnectionState"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connected\/title","value":"MCConnectionStateConnected"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connected\/fragments","value":[{"kind":"identifier","text":"MCConnectionStateConnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}