{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"MCDegradationPreferencesBalanced","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"balanced","kind":"identifier"}],"title":"MCDegradationPreferences.balanced","role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCDegradationPreferences@MCDegradationPreferencesBalanced","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/balanced"]},{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/balanced"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"balanced"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Tries to strike a pleasing balance between frame rate or resolution."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/balanced"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/balanced":{"kind":"symbol","abstract":[{"type":"text","text":"Tries to strike a pleasing balance between frame rate or resolution."}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesBalanced"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/balanced","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"balanced"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/balanced","title":"MCDegradationPreferences.balanced","type":"topic"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","type":"link","title":"the WebRTC standard","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences":{"role":"symbol","abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"}],"type":"topic","title":"MCDegradationPreferences","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCDegradationPreferencesBalanced","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCDegradationPreferencesBalanced"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCDegradationPreferencesBalanced","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1balanced\/title","value":"MCDegradationPreferencesBalanced"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1balanced\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferencesBalanced"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","value":"MCDegradationPreferences"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferences"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}