{"abstract":[{"type":"text","text":"On over-use, requests lower resolution, possibly causing down-scaling."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainframerate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainframerate"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"maintainFrameRate","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@E@MCDegradationPreferences@MCDegradationPreferencesMaintainFrameRate","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"maintainFrameRate","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","title":"MCDegradationPreferences.maintainFrameRate","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainFrameRate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainFrameRate"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","title":"the WebRTC standard","type":"link","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/maintainFrameRate":{"type":"topic","abstract":[{"text":"On over-use, requests lower resolution, possibly causing down-scaling.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainframerate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maintainFrameRate"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainFrameRate","kind":"symbol","title":"MCDegradationPreferences.maintainFrameRate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainFrameRate"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences":{"role":"symbol","abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"}],"type":"topic","title":"MCDegradationPreferences","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MCDegradationPreferencesMaintainFrameRate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainFrameRate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCDegradationPreferencesMaintainFrameRate","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainFrameRate\/title","op":"replace","value":"MCDegradationPreferencesMaintainFrameRate"},{"value":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainFrameRate"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainFrameRate\/fragments"},{"value":"MCDegradationPreferences","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","op":"replace"},{"value":[{"text":"MCDegradationPreferences","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}