{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"signalingErrorPublisher()","symbolKind":"method","role":"symbol","extendedModule":"MillicastSDK","externalID":"s:So12MCSubscriberC12MillicastSDKE23signalingErrorPublisher7Combine03AnyF0VySo011MCSignalingE0Cs5NeverOGyF","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingErrorPublisher"},{"kind":"text","text":"() -> "},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCSignalingError","kind":"typeIdentifier","text":"MCSignalingError"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive signaling errors"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signalingErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSignalingError","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","text":"MCSignalingError"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/signalingerrorpublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingErrorPublisher()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"title":"MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/signalingErrorPublisher()":{"title":"signalingErrorPublisher()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingErrorPublisher()","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Get a Combine based publisher that can be used to receive signaling errors","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/signalingerrorpublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"signalingErrorPublisher","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCSignalingError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSignalingError":{"abstract":[{"text":"Container class for Signaling errors that occur during","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"signaling\/configuration of the peer connection."}],"url":"\/documentation\/millicastsdk\/mcsignalingerror","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCSignalingError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSignalingError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","title":"MCSignalingError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"op":"replace","value":"MCSignalingError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/fragments","value":[{"text":"MCSignalingError","kind":"identifier"}]}]}]}