{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"title":"statsPublisher","externalID":"s:So12MCSubscriberC12MillicastSDKE14statsPublisher7Combine03AnyE0VySo0A5StatsCs5NeverOGvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"statsPublisher","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"text":"<","kind":"text"},{"text":"MCSubscriberStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberStats"},{"kind":"text","text":", "},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"extendedModule":"MillicastSDK"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsPublisher"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsPublisher"},{"text":": ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSubscriberStats","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats","text":"MCSubscriberStats"},{"kind":"text","text":", "},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":"> { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/statspublisher"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Get a Combine based publisher that can be used to receive subscriber stats events","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/statsPublisher":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/statsPublisher","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive subscriber stats events"}],"title":"statsPublisher","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"statsPublisher","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSubscriberStats","kind":"typeIdentifier","text":"MCSubscriberStats"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/statspublisher"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"title":"MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStats":{"title":"MCSubscriberStats","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStats"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberStats"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace"},{"op":"replace","value":"MCSubscriberStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStats\/fragments","value":[{"text":"MCSubscriberStats","kind":"identifier"}],"op":"replace"}]}]}