{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerResolution","preciseIdentifier":"c:objc(cs)MCLayerResolution","text":"MCLayerResolution"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mclayerdata\/layerresolution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mclayerdata\/layerresolution"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/layerResolution","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The resolution of frames in the layer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerResolution","preciseIdentifier":"c:objc(cs)MCLayerResolution"},{"kind":"text","text":"?"}],"title":"layerResolution","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCLayerData(py)layerResolution","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"layerResolution"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData/layerResolution":{"role":"symbol","title":"layerResolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerResolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerResolution","preciseIdentifier":"c:objc(cs)MCLayerResolution"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The resolution of frames in the layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData\/layerResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerResolution"}],"url":"\/documentation\/millicastsdk\/mclayerdata\/layerresolution"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/layers()":{"role":"symbol","title":"layers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layers"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"LayersEvent","preciseIdentifier":"s:12MillicastSDK11LayersEventV"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives layers events."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/layers()","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/layers()"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData":{"role":"symbol","title":"MCLayerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}],"url":"\/documentation\/millicastsdk\/mclayerdata"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerResolution":{"role":"symbol","title":"MCLayerResolution","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerResolution"}],"abstract":[{"type":"text","text":"Simulcast\/SVC layer resolution information. Received as part in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData"},{"type":"text","text":" "},{"type":"text","text":"in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/layers()"},{"type":"text","text":" event."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerResolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerResolution"}],"url":"\/documentation\/millicastsdk\/mclayerresolution"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"layerResolution"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layerResolution"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerResolution","preciseIdentifier":"c:objc(cs)MCLayerResolution","text":"MCLayerResolution"},{"kind":"text","text":" * "},{"kind":"identifier","text":"layerResolution"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1layerResolution\/title","value":"layerResolution"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData~1layerResolution\/fragments","value":[{"kind":"identifier","text":"layerResolution"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/title","value":"MCLayerData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerResolution\/title","value":"MCLayerResolution"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerResolution\/fragments","value":[{"kind":"identifier","text":"MCLayerResolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}