{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"abstract":[{"type":"text","text":"The width of video frames. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","isActive":true}],"metadata":{"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)frame_width","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frame_width"}],"roleHeading":"Instance Property","title":"frame_width","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frame_width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_width","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame_width"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frame_width"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frame_width"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framewidth":{"titleInlineContent":[{"text":"frameWidth","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","type":"link","title":"frameWidth"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","role":"symbol","title":"MCInboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frame_width":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frame_width","type":"topic","abstract":[{"type":"text","text":"The width of video frames. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","type":"reference"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame_width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"text":"frame_width","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_width","title":"frame_width"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"frame_width"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frame_width"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:l","text":"unsigned long"},{"kind":"text","text":" "},{"text":"frame_width","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]},{"op":"replace","value":"frame_width","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_width\/title"},{"value":[{"kind":"identifier","text":"frame_width"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_width\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}