{"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jitter_buffer_emitted_count","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"symbolKind":"property","title":"jitter_buffer_emitted_count","navigatorTitle":[{"text":"jitter_buffer_emitted_count","kind":"identifier"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)jitter_buffer_emitted_count"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_emitted_count","interfaceLanguage":"swift"},"abstract":[{"text":"The number of packets emitted from the jitter buffer. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount","isActive":true,"type":"reference"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"jitter_buffer_emitted_count","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_emitted_count"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_emitted_count"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_emitted_count":{"kind":"symbol","type":"topic","abstract":[{"text":"The number of packets emitted from the jitter buffer. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_emitted_count","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitter_buffer_emitted_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"jitter_buffer_emitted_count"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_emitted_count","title":"jitter_buffer_emitted_count"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount","title":"jitterBufferEmittedCount","titleInlineContent":[{"type":"text","text":"jitterBufferEmittedCount"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","role":"symbol","title":"MCInboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"jitter_buffer_emitted_count"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"jitter_buffer_emitted_count"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"unsigned long","preciseIdentifier":"c:l"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitter_buffer_emitted_count"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"jitter_buffer_emitted_count","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_emitted_count\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_emitted_count\/fragments","value":[{"text":"jitter_buffer_emitted_count","kind":"identifier"}]},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}