{"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)nack_count","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nack_count","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"nack_count","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"nack_count"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nack_count","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/nack_count"]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/nack_count"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/nack_count","interfaceLanguage":"swift"},"abstract":[{"text":"The number of Negative Acknowledgment (NACK) packets. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount"}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","role":"symbol","title":"MCInboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/nack_count":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/nack_count","type":"topic","title":"nack_count","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nack_count"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/nack_count","role":"symbol","kind":"symbol","abstract":[{"text":"The number of Negative Acknowledgment (NACK) packets. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount"}],"navigatorTitle":[{"text":"nack_count","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-nackcount":{"titleInlineContent":[{"text":"nackCount","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount","title":"nackCount","type":"link"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"nack_count"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"nack_count","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsigned long","kind":"typeIdentifier","preciseIdentifier":"c:l"},{"kind":"text","text":" "},{"text":"nack_count","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats"},{"op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"},{"value":"nack_count","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1nack_count\/title","op":"replace"},{"value":[{"text":"nack_count","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1nack_count\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}