{"kind":"symbol","abstract":[{"text":"The number of silent concealed audio samples. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples","isActive":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silent_concealed_samples"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/silent_concealed_samples","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)silent_concealed_samples","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silent_concealed_samples"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"title":"silent_concealed_samples","symbolKind":"property","role":"symbol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"silent_concealed_samples"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/silent_concealed_samples"]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/silent_concealed_samples"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/silent_concealed_samples":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/silent_concealed_samples","type":"topic","title":"silent_concealed_samples","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"silent_concealed_samples"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/silent_concealed_samples","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The number of silent concealed audio samples. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples"}],"navigatorTitle":[{"kind":"identifier","text":"silent_concealed_samples"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","role":"symbol","title":"MCInboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-silentconcealedsamples":{"titleInlineContent":[{"type":"text","text":"silentConcealedSamples"}],"title":"silentConcealedSamples","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"silent_concealed_samples"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"silent_concealed_samples","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","text":"unsigned long","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"silent_concealed_samples"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1silent_concealed_samples\/title","value":"silent_concealed_samples","op":"replace"},{"op":"replace","value":[{"text":"silent_concealed_samples","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1silent_concealed_samples\/fragments"},{"value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}