{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","modules":[{"name":"MillicastSDK"}],"title":"MCGenericError.Code.invalidOptions","navigatorTitle":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidOptions"}],"externalID":"c:@E@MCGenericError@MCGenericErrorInvalidOptions","roleHeading":"Case"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidOptions"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"abstract":[{"type":"text","text":"Invalid options set for the request."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidOptions"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidoptions"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidOptions":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidOptions"}],"type":"topic","navigatorTitle":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}],"title":"MCGenericError.Code.invalidOptions","role":"symbol","abstract":[{"text":"Invalid options set for the request.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidOptions","kind":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidoptions"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","type":"topic","title":"MCGenericError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCGenericErrorInvalidOptions","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidOptions\/title","value":"MCGenericErrorInvalidOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidOptions\/fragments","value":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","value":"MCGenericError"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","value":[{"text":"MCGenericError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}