{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweMonitorDurationUs"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/bwemonitordurationus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/bwemonitordurationus"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Overrides the duration of time over which bandwidth-estimate-calculations occur in usec. By default this is 150msec, increasing this may smooth out transitions a little at the cost of NOT reacting to changes in the network as fast."},{"text":" ","type":"text"},{"text":"Expects an unsigned integer value.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"bweMonitorDurationUs","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bweMonitorDurationUs"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"bweMonitorDurationUs","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)MCClientOptions(py)bweMonitorDurationUs"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bweMonitorDurationUs"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCClientOptions","kind":"identifier"}],"title":"MCClientOptions","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/bweMonitorDurationUs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweMonitorDurationUs","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcclientoptions\/bwemonitordurationus","role":"symbol","title":"bweMonitorDurationUs","abstract":[{"type":"text","text":"Overrides the duration of time over which bandwidth-estimate-calculations occur in usec. By default this is 150msec, increasing this may smooth out transitions a little at the cost of NOT reacting to changes in the network as fast."},{"type":"text","text":" "},{"type":"text","text":"Expects an unsigned integer value."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bweMonitorDurationUs"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bweMonitorDurationUs"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bweMonitorDurationUs","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"bweMonitorDurationUs","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bweMonitorDurationUs","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}]},{"op":"replace","value":"bweMonitorDurationUs","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweMonitorDurationUs\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweMonitorDurationUs\/fragments","op":"replace","value":[{"text":"bweMonitorDurationUs","kind":"identifier"}]}]}]}