{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"forceSmooth","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"forceSmooth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:objc(cs)MCClientOptions(py)forceSmooth","navigatorTitle":[{"text":"forceSmooth","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"abstract":[{"type":"text","text":"Forces video to be sent on downlink when switching from higher quality layers"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forceSmooth"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"forceSmooth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"If true, smooth transitions will be enabled when changing from a higher"},{"text":" ","type":"text"},{"type":"text","text":"rate to a lower rate, this may cause congested use cases to take longer to"},{"type":"text","text":" "},{"type":"text","text":"recover If false, then when switching from a higher rate to lower rate (due"},{"type":"text","text":" "},{"type":"text","text":"to congestion) we will stop sending video packets until the next I frame"},{"type":"text","text":" "},{"text":"arrives at the new lower rate causing a pause but improving the impacts of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"congestion and recovering quicker."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/forcesmooth"]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/forcesmooth"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCClientOptions","kind":"identifier"}],"title":"MCClientOptions","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/forceSmooth":{"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions\/forcesmooth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"forceSmooth","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Forces video to be sent on downlink when switching from higher quality layers"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forceSmooth","kind":"symbol","title":"forceSmooth","navigatorTitle":[{"text":"forceSmooth","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"forceSmooth"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"forceSmooth"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceSmooth"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace"},{"value":"forceSmooth","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forceSmooth\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forceSmooth\/fragments","op":"replace","value":[{"text":"forceSmooth","kind":"identifier"}]}]}]}