{"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCAudioPlayerNodeDelegate(im)audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"8.0","deprecated":false}],"title":"audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDidBecomeAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"audioFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioFormat","text":"AVAudioFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCAudioPlayerNodePlaybackController","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodePlaybackController"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeavailable(_:audioformat:controller:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeavailable(_:audioformat:controller:)"]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"node"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioFormat"},{"kind":"text","text":" "},{"kind":"internalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioFormat","preciseIdentifier":"c:objc(cs)AVAudioFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"MCAudioPlayerNodePlaybackController","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodePlaybackController","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Notifies when the SDK creates an AVAudioPlayerNode that will be used for receiving audio","type":"text"},{"text":" ","type":"text"},{"text":"-Parameters:","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)":{"required":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeavailable(_:audioformat:controller:)","abstract":[{"text":"Notifies when the SDK creates an AVAudioPlayerNode that will be used for receiving audio","type":"text"},{"text":" ","type":"text"},{"text":"-Parameters:","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioFormat","preciseIdentifier":"c:objc(cs)AVAudioFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"MCAudioPlayerNodePlaybackController","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodePlaybackController"},{"kind":"text","text":")"}],"title":"audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController":{"title":"MCAudioPlayerNodePlaybackController","navigatorTitle":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController","role":"symbol","abstract":[{"text":"This playback controller allows you to modify the state of the player node that is provided through the delegate.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"title":"MCAudioPlayerNodeDelegate","kind":"symbol","abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","navigatorTitle":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"audioPlayerNodeDidBecomeAvailable:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAudioPlayerNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"text":" *) ","kind":"text"},{"text":"node","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"audioFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioFormat","kind":"typeIdentifier","text":"AVAudioFormat"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"format"},{"kind":"text","text":" "},{"kind":"identifier","text":"controller:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)MCAudioPlayerNodePlaybackController","kind":"typeIdentifier","text":"id<MCAudioPlayerNodePlaybackController>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)\/title","value":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:"}],"op":"replace"},{"value":"MCAudioPlayerNodePlaybackController","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/title"},{"value":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/fragments"},{"value":"MCAudioPlayerNodeDelegate","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title"},{"value":[{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}