{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDidStartPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"node","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVAudioPlayerNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStartPlaying(_:error:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstartplaying(_:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstartplaying(_:error:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}],"symbolKind":"method","roleHeading":"Instance Method","required":true,"modules":[{"name":"MillicastSDK"}],"role":"symbol","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"8.0"}],"externalID":"c:objc(pl)MCAudioPlayerNodeDelegate(im)audioPlayerNodeDidStartPlaying:error:","title":"audioPlayerNodeDidStartPlaying(_:error:)","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying:error:"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidStartPlaying(_:error:)":{"navigatorTitle":[{"text":"audioPlayerNodeDidStartPlaying:error:","kind":"identifier"}],"role":"symbol","required":true,"title":"audioPlayerNodeDidStartPlaying(_:error:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStartPlaying(_:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstartplaying(_:error:)","type":"topic","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"title":"MCAudioPlayerNodeDelegate","kind":"symbol","abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","navigatorTitle":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerNodeDidStartPlaying:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioPlayerNodeDidStartPlaying:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"audioPlayerNodeDidStartPlaying:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"node","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStartPlaying(_:error:)\/title","value":"audioPlayerNodeDidStartPlaying:error:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStartPlaying(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title","value":"MCAudioPlayerNodeDelegate"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments","value":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}