{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/disconnecting"]},{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/disconnecting"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@E@MCConnectionState@MCConnectionStateDisconnecting","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"disconnecting","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCConnectionState.disconnecting","navigatorTitle":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/disconnecting"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"]]},"abstract":[{"type":"text","text":"The socket is now in disconnecting state."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnecting","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","role":"symbol","navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","title":"MCConnectionState"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/disconnecting":{"type":"topic","url":"\/documentation\/millicastsdk\/mcconnectionstate\/disconnecting","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/disconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnecting"}],"navigatorTitle":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}],"title":"MCConnectionState.disconnecting","role":"symbol","abstract":[{"type":"text","text":"The socket is now in disconnecting state."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MCConnectionStateDisconnecting","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"MCConnectionState","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCConnectionState"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1disconnecting\/title","value":"MCConnectionStateDisconnecting","op":"replace"},{"value":[{"text":"MCConnectionStateDisconnecting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1disconnecting\/fragments"}]}]}