{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/failed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"The socket has entered a failed state.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/failed"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"MCConnectionStateFailed","kind":"identifier"}],"title":"MCConnectionState.failed","externalID":"c:@E@MCConnectionState@MCConnectionStateFailed","roleHeading":"Case"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/failed":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"abstract":[{"type":"text","text":"The socket has entered a failed state."}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCConnectionStateFailed","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcconnectionstate\/failed","title":"MCConnectionState.failed","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/failed"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","role":"symbol","navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","title":"MCConnectionState"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCConnectionStateFailed","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"MCConnectionStateFailed"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCConnectionStateFailed"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1failed\/title","value":"MCConnectionStateFailed","op":"replace"},{"value":[{"text":"MCConnectionStateFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1failed\/fragments"},{"op":"replace","value":"MCConnectionState","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"value":[{"text":"MCConnectionState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}