{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"client"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","text":"MCClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveStatsReport"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"report"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStatsReport","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","text":"MCStatsReport","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The Millicast client","type":"text"}],"type":"paragraph"}],"name":"client"},{"name":"didReceiveStatsReport","content":[{"inlineContent":[{"type":"text","text":"A Stats report object. Contains various different stats."},{"type":"text","text":" "},{"text":"Use ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","isActive":true,"type":"reference"},{"type":"text","text":" to extract statistics of"},{"text":" ","type":"text"},{"type":"text","text":"different types like "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","isActive":true,"type":"reference"},{"text":" for example.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"You must enable statistics via ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","isActive":true},{"text":" ","type":"text"},{"type":"text","text":"to start receiving this handler."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Called when a new RTC statistics report has been collected."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveStatsReport:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivestatsreport:)"]},{"paths":["\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivestatsreport:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"client:didReceiveStatsReport:","kind":"identifier"}],"externalID":"c:objc(pl)MCDelegate(im)client:didReceiveStatsReport:","role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","title":"client(_:didReceiveStatsReport:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"client"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"MCClient","preciseIdentifier":"c:objc(pl)MCClient"},{"text":", ","kind":"text"},{"text":"didReceiveStatsReport","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStatsOf(_:)":{"title":"getStatsOf(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getStatsOf","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getStatsOfType:"}],"role":"symbol","abstract":[{"type":"text","text":"Retrieves an array of MCStats objects from the report that match a specified MCStatsType."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol","title":"MCCodecsStats","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCDelegate"}],"navigatorTitle":[{"text":"MCDelegate","kind":"identifier"}],"title":"MCDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","abstract":[{"text":"The ","type":"text"},{"code":"MCDelegate","type":"codeVoice"},{"text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly","type":"text"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","isActive":true,"type":"reference"},{"text":", which are the main ones to implement.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"enableStats:completionHandler:"}],"title":"enableStats(_:completionHandler:)","abstract":[{"text":"Enables or disables the collection and reporting of real-time","type":"text"},{"type":"text","text":" "},{"type":"text","text":"statistics associated with streaming sessions."},{"text":" ","type":"text"},{"type":"text","text":"The statistics are collected once the client is either publishing or subscribed."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableStats","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)","required":true},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/client(_:didReceiveStatsReport:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"client"},{"text":"(any ","kind":"text"},{"text":"MCClient","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCClient"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceiveStatsReport"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"client:didReceiveStatsReport:","kind":"identifier"}],"title":"client(_:didReceiveStatsReport:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/client(_:didReceiveStatsReport:)","abstract":[{"text":"Called when a new RTC statistics report has been collected.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/client(_:didreceivestatsreport:)","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"title":"MCSubscriberDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"type":"text","text":" "},{"text":"events.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"text":"You must implement this protocol and set a delegate.","type":"text"},{"text":" ","type":"text"},{"text":"to receive events from the publisher.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClient"}],"url":"\/documentation\/millicastsdk\/mcclient","title":"MCClient","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCClient","kind":"identifier"}],"abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"title":"MCStatsReport","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsReport"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"role":"symbol","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatsreport"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriber"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","title":"MCSubscriber","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"client:didReceiveStatsReport:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"client:didReceiveStatsReport:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"client:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCClient","text":"id<MCClient>"},{"text":") ","kind":"text"},{"text":"client","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveStatsReport:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStatsReport","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","text":"MCStatsReport"},{"text":" *) ","kind":"text"},{"text":"report","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"getStatsOfType:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getStatsOfType:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","value":[{"kind":"identifier","text":"MCCodecsStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","value":"enableStats:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableStats:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveStatsReport:)\/title","value":"client:didReceiveStatsReport:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"client:didReceiveStatsReport:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1client(_:didReceiveStatsReport:)\/fragments"},{"value":"MCSubscriberDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title"},{"value":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments"},{"value":"MCPublisherDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"value":"MCClient","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments","op":"replace","value":[{"text":"MCClient","kind":"identifier"}]},{"value":"MCStatsReport","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","op":"replace"},{"op":"replace","value":[{"text":"MCStatsReport","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}