{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nack_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/nack_count"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/nack_count"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/nack_count","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The number of Negative Acknowledgment (NACK) messages sent. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nack_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"nack_count","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)nack_count","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"nack_count"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/nack_count":{"role":"symbol","title":"nack_count","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nack_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The number of Negative Acknowledgment (NACK) messages sent. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/nack_count","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nack_count"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/nack_count"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"role":"symbol","title":"MCOutboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-nackcount":{"title":"nackCount","titleInlineContent":[{"type":"text","text":"nackCount"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nack_count"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nack_count"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"unsigned long","preciseIdentifier":"c:l"},{"kind":"text","text":" "},{"kind":"identifier","text":"nack_count"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1nack_count\/title","value":"nack_count"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1nack_count\/fragments","value":[{"kind":"identifier","text":"nack_count"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}