{"metadata":{"navigatorTitle":[{"text":"disableBWE","kind":"identifier"}],"symbolKind":"property","title":"disableBWE","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCBitrateSettings(py)disableBWE","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disableBWE","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings"]]},"abstract":[{"text":"Disable built-in bandwidth estimation algorithm that forces sending the maximum bitrate without any congestion control.","type":"text"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/disableBWE","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disableBWE","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/disablebwe"]},{"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/disablebwe"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings/disableBWE":{"title":"disableBWE","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcbitratesettings\/disablebwe","navigatorTitle":[{"kind":"identifier","text":"disableBWE"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/disableBWE","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disableBWE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Disable built-in bandwidth estimation algorithm that forces sending the maximum bitrate without any congestion control."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCBitrateSettings","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCBitrateSettings"}],"title":"MCBitrateSettings","type":"topic","url":"\/documentation\/millicastsdk\/mcbitratesettings","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings","abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"disableBWE","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"disableBWE"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"text":"disableBWE","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1disableBWE\/title","value":"disableBWE","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1disableBWE\/fragments","value":[{"text":"disableBWE","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/title","value":"MCBitrateSettings"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCBitrateSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}