{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/disabled"]},{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@E@MCDegradationPreferences@MCDegradationPreferencesDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesDisabled"}],"modules":[{"name":"MillicastSDK"}],"title":"MCDegradationPreferences.disabled"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"abstract":[{"type":"text","text":"Does not take any actions based on over-utilization signals."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences\/disabled"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDegradationPreferences/disabled":{"navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferencesDisabled"}],"abstract":[{"type":"text","text":"Does not take any actions based on over-utilization signals."}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/disabled","role":"symbol","type":"topic","title":"MCDegradationPreferences.disabled","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences\/disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDegradationPreferences":{"type":"topic","title":"MCDegradationPreferences","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences","abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true}],"kind":"symbol","navigatorTitle":[{"text":"MCDegradationPreferences","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCDegradationPreferencesDisabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferencesDisabled"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCDegradationPreferencesDisabled","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences~1disabled\/title","value":"MCDegradationPreferencesDisabled","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences~1disabled\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferencesDisabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","value":"MCDegradationPreferences","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferences"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}