{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/audioTracks(completionHandler:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","text":"MCRTSRemoteAudioTrack"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes, with a"},{"type":"text","text":" "},{"type":"text","text":"list of remote audio tracks."}]}]}]}],"sections":[],"abstract":[{"text":"List all available rts remote audio tracks received so far.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/audiotracks(completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/audiotracks(completionhandler:)"]}],"metadata":{"symbolKind":"method","title":"audioTracks(completionHandler:)","externalID":"c:objc(cs)MCSubscriber(im)audioTracksWithCompletionHandler:","role":"symbol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"audioTracksWithCompletionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"text":"]?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteAudioTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","title":"MCRTSRemoteAudioTrack","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack","abstract":[{"text":"The RTS logical track’s audio interface.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/audioTracks(completionHandler:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioTracksWithCompletionHandler:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/audiotracks(completionhandler:)","title":"audioTracks(completionHandler:)","abstract":[{"text":"List all available rts remote audio tracks received so far.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","text":"MCRTSRemoteAudioTrack"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/audioTracks(completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","title":"MCSubscriber","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"audioTracksWithCompletionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioTracksWithCompletionHandler:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioTracksWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MCRTSRemoteAudioTrack *>"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCRTSRemoteAudioTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/fragments","op":"replace"},{"value":"audioTracksWithCompletionHandler:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1audioTracks(completionHandler:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioTracksWithCompletionHandler:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber~1audioTracks(completionHandler:)\/fragments","op":"replace"},{"value":"MCSubscriber","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace"}]}]}