{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamStoppedPublisher"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","kind":"typeIdentifier","text":"MCStreamStoppedEvent","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStreamStoppedEvent"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:So12MCSubscriberC12MillicastSDKE22streamStoppedPublisher7Combine03AnyF0VySo08MCStreamE5EventCs5NeverOGvp","title":"streamStoppedPublisher","modules":[{"name":"MillicastSDK"}],"extendedModule":"MillicastSDK","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamStoppedPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","text":"MCStreamStoppedEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/streamstoppedpublisher"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Get a Combine based publisher that receives  publisher stream stopped events","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/streamStoppedPublisher","interfaceLanguage":"swift"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStreamStoppedEvent":{"navigatorTitle":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStreamStoppedEvent","type":"topic","title":"MCStreamStoppedEvent","role":"symbol","abstract":[{"text":"Container for the stream stopped event. This happens","type":"text"},{"text":" ","type":"text"},{"text":"when the last publisher has stopped sending a stream","type":"text"},{"text":" ","type":"text"},{"text":"and no more media is available","type":"text"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamStoppedEvent"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","title":"MCSubscriber","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/streamStoppedPublisher":{"abstract":[{"text":"Get a Combine based publisher that receives  publisher stream stopped events","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/streamStoppedPublisher","title":"streamStoppedPublisher","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/streamstoppedpublisher","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"streamStoppedPublisher","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCStreamStoppedEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCStreamStoppedEvent","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/title"},{"value":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/fragments"},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments"}]}]}