{"sections":[],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)"],"anchor":"Instance-Methods"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"collectionGroup","title":"MCAcceleratedVideoRendererDelegate Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mcacceleratedvideorendererdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mcacceleratedvideorendererdelegate-implementations"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView/didChangeVideoSize(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeVideoSize"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"title":"didChangeVideoSize(_:)","abstract":[],"type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/didchangevideosize(_:)","navigatorTitle":[{"kind":"identifier","text":"didChangeVideoSize:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","type":"topic","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal as a backend for rendering."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"didChangeVideoSize:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeVideoSize:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/fragments"},{"value":"MCAcceleratedVideoUIView","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title"},{"value":[{"text":"MCAcceleratedVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments"},{"value":[{"text":"MCAcceleratedVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}