{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcremotetrackkind\/video"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcremotetrackkind\/video"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MCRemoteTrackKind@MCRemoteTrackKindVideo","roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"title":"MCRemoteTrackKind.video","symbolKind":"case","navigatorTitle":[{"text":"MCRemoteTrackKindVideo","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/video","interfaceLanguage":"swift"},"abstract":[{"text":"Track is a video track.","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/video":{"navigatorTitle":[{"kind":"identifier","text":"MCRemoteTrackKindVideo"}],"abstract":[{"type":"text","text":"Track is a video track."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/video","url":"\/documentation\/millicastsdk\/mcremotetrackkind\/video","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"type":"topic","role":"symbol","title":"MCRemoteTrackKind.video"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind":{"title":"MCRemoteTrackKind","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enum specifying the type of the remote track."}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteTrackKind","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCRemoteTrackKindVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCRemoteTrackKindVideo","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCRemoteTrackKindVideo"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1video\/title","value":"MCRemoteTrackKindVideo"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1video\/fragments","value":[{"text":"MCRemoteTrackKindVideo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title","value":"MCRemoteTrackKind"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/navigatorTitle","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}]}]}]}