{"abstract":[{"text":"The cumulative energy of the audio signal over a period. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy","type":"reference"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/total_audio_energy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/total_audio_energy"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_audio_energy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_audio_energy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"total_audio_energy"}],"externalID":"c:objc(cs)MCAudioSourceStats(py)total_audio_energy","role":"symbol","roleHeading":"Instance Property","title":"total_audio_energy"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_audio_energy"},"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats":{"abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}],"title":"MCAudioSourceStats","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioSourceStats"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats","url":"\/documentation\/millicastsdk\/mcaudiosourcestats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSourceStats"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSourceStats/total_audio_energy":{"role":"symbol","abstract":[{"text":"The cumulative energy of the audio signal over a period. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy","type":"reference"}],"navigatorTitle":[{"text":"total_audio_energy","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_audio_energy","kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/total_audio_energy","title":"total_audio_energy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_audio_energy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-totalaudioenergy":{"title":"totalAudioEnergy","titleInlineContent":[{"text":"totalAudioEnergy","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"total_audio_energy","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"total_audio_energy"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"total_audio_energy","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCAudioSourceStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","op":"replace"},{"value":[{"text":"MCAudioSourceStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_audio_energy\/title","op":"replace","value":"total_audio_energy"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_audio_energy\/fragments","op":"replace","value":[{"text":"total_audio_energy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}