{"abstract":[{"text":"Error category for errors triggered when audio related errors occur.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/avAudioPlayerNodeNotAttachedToAVAudioEngine"]},{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code"]},{"paths":["\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@E@MCAudioError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"title":"MCAudioError.Code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code/init(rawValue:)":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/init(rawValue:)","type":"topic","title":"init(rawValue:)","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code/RawRepresentable-Implementations":{"url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SY","title":"Swift.RawRepresentable"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s8SendableP","title":"Swift.Sendable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code/avAudioPlayerNodeNotAttachedToAVAudioEngine":{"abstract":[{"type":"text","text":"AVAudioPlayerNode is not attached to an audio engine."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/avAudioPlayerNodeNotAttachedToAVAudioEngine","type":"topic","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/avaudioplayernodenotattachedtoavaudioengine","title":"MCAudioError.Code.avAudioPlayerNodeNotAttachedToAVAudioEngine","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"avAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/equatable-implementations","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/Equatable-Implementations","kind":"article"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code","title":"MCAudioError.Code","kind":"symbol","abstract":[{"text":"Error category for errors triggered when audio related errors occur.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MCAudioError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCAudioError","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MCAudioError"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/avAudioPlayerNodeNotAttachedToAVAudioEngine"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code~1avAudioPlayerNodeNotAttachedToAVAudioEngine\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code~1avAudioPlayerNodeNotAttachedToAVAudioEngine\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/title","value":"MCAudioError"},{"op":"replace","value":[{"text":"MCAudioError","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}