{"metadata":{"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"streamName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"streamName","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"streamName","externalID":"c:objc(cs)MCSubscriberCredentials(py)streamName"},"abstract":[{"text":"The name of the stream you want to subscribe to.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/streamname"]},{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/streamname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"streamName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/streamName"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","title":"MCSubscriberCredentials","navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCSubscriberCredentials","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials","kind":"symbol","abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connecting and subscribing to a Millicast stream. See the "},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"}],"type":"topic","role":"symbol"},"https://dash.millicast.com/docs.html":{"identifier":"https:\/\/dash.millicast.com\/docs.html","titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"title":"Streaming Dashboard","url":"https:\/\/dash.millicast.com\/docs.html","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials/streamName":{"url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/streamname","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name of the stream you want to subscribe to."}],"title":"streamName","type":"topic","navigatorTitle":[{"text":"streamName","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/streamName"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"streamName","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"streamName","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"streamName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","value":[{"kind":"identifier","text":"MCSubscriberCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1streamName\/title","value":"streamName"},{"value":[{"text":"streamName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1streamName\/fragments"}]}]}