{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(name:recorder:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(recorder:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/name"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/startCapture(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/stopCapture(completionHandler:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource"},"abstract":[{"text":"Uses Replaykit to capture the screen of the application.","type":"text"}],"metadata":{"title":"MCAppShareSource","roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}],"navigatorTitle":[{"text":"MCAppShareSource","kind":"identifier"}],"externalID":"c:objc(cs)MCAppShareSource"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/init(recorder:)":{"navigatorTitle":[{"text":"initWithRecorder:","kind":"identifier"}],"abstract":[{"text":"Initializes the source with a recorder.","type":"text"}],"title":"init(recorder:)","url":"\/documentation\/millicastsdk\/mcappsharesource\/init(recorder:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(recorder:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RPScreenRecorder","preciseIdentifier":"c:objc(cs)RPScreenRecorder","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/name":{"title":"name","abstract":[],"url":"\/documentation\/millicastsdk\/mcappsharesource\/name","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/name","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/init(name:recorder:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RPScreenRecorder","preciseIdentifier":"c:objc(cs)RPScreenRecorder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcappsharesource\/init(name:recorder:)","abstract":[{"type":"text","text":"Initializes the source with a name to identify the source."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(name:recorder:)","title":"init(name:recorder:)","role":"symbol","navigatorTitle":[{"text":"initWithName:recorder:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAppShareSource"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}],"title":"MCAppShareSource","url":"\/documentation\/millicastsdk\/mcappsharesource","abstract":[{"text":"Uses Replaykit to capture the screen of the application.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/startCapture(completionHandler:)":{"type":"topic","url":"\/documentation\/millicastsdk\/mcappsharesource\/startcapture(completionhandler:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Start capturing the application screen."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MCAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"text":"?, ","kind":"text"},{"text":"MCVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"startCapture(completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/startCapture(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"startCaptureWithCompletionHandler:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/stopCapture(completionHandler:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/stopCapture(completionHandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Stops capturing the application screen."}],"type":"topic","title":"stopCapture(completionHandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopCaptureWithCompletionHandler:"}],"url":"\/documentation\/millicastsdk\/mcappsharesource\/stopcapture(completionhandler:)"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCAppShareSource","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MCAppShareSource"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCAppShareSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/name"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(name:recorder:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(recorder:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/startCapture(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/stopCapture(completionHandler:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(recorder:)\/title","value":"initWithRecorder:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(recorder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRecorder:"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(name:recorder:)\/title","value":"initWithName:recorder:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:recorder:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(name:recorder:)\/fragments"},{"value":"MCAppShareSource","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/title"},{"value":[{"kind":"identifier","text":"MCAppShareSource"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/fragments"},{"value":[{"kind":"identifier","text":"MCAppShareSource"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/navigatorTitle"},{"value":"startCaptureWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1startCapture(completionHandler:)\/title"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1startCapture(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startCaptureWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1stopCapture(completionHandler:)\/title","value":"stopCaptureWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1stopCapture(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCaptureWithCompletionHandler:"}],"op":"replace"}]}]}