{"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/isCapturing()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/stopCapture()"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiosource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiosource"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl","doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"metadata":{"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"MCAudioSource","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCAudioSource","symbolKind":"class","externalID":"c:objc(cs)MCAudioSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSource","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSource","kind":"identifier"}]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSource":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource","url":"\/documentation\/millicastsdk\/mcsource","title":"MCSource","abstract":[{"text":"Gathers information about the source.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}]},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioControl":{"url":"\/documentation\/millicastsdk\/mcaudiocontrol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioControl"}],"abstract":[{"type":"text","text":"Manages audio settings."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"}],"title":"MCAudioControl","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource/isCapturing()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCapturing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"isCapturing()","abstract":[{"type":"text","text":"Checks whether the AudioSource instance is currently actively capturing audio."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/isCapturing()","url":"\/documentation\/millicastsdk\/mcaudiosource\/iscapturing()","role":"symbol","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource/stopCapture()":{"navigatorTitle":[{"text":"stopCapture","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/stopCapture()","url":"\/documentation\/millicastsdk\/mcaudiosource\/stopcapture()","title":"stopCapture()","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Stops the audio capture process.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource":{"abstract":[{"text":"Manages the audio capture functionality.","type":"text"}],"kind":"symbol","title":"MCAudioSource","navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"url":"\/documentation\/millicastsdk\/mcaudiosource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSource"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/CaptureSource":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureSource"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureSource"}],"title":"CaptureSource","role":"symbol","abstract":[{"text":"Manages the process of capturing the source by input sources, such as a microphone or a camera.","type":"text"}],"url":"\/documentation\/millicastsdk\/capturesource","kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource/startCapture()":{"title":"startCapture()","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"startCapture","kind":"identifier"}],"abstract":[{"text":"Initiates the audio capture process from the current source.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCAudioSource","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioSource"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MCAudioSource","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/isCapturing()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/stopCapture()"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSource","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSource","text":"MCSource","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSource"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/fragments"},{"op":"replace","value":[{"text":"MCSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/navigatorTitle"},{"op":"replace","value":"MCAudioControl","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioControl"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioControl"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/navigatorTitle"},{"op":"replace","value":"isCapturing","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1isCapturing()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isCapturing","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1isCapturing()\/fragments"},{"op":"replace","value":"stopCapture","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1stopCapture()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1stopCapture()\/fragments"},{"op":"replace","value":"MCAudioSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource\/title"},{"op":"replace","value":[{"text":"MCAudioSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource\/fragments"},{"op":"replace","value":[{"text":"MCAudioSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource\/navigatorTitle"},{"op":"replace","value":"CaptureSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CaptureSource"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/fragments"},{"op":"replace","value":[{"text":"CaptureSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/navigatorTitle"},{"op":"replace","value":"startCapture","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments"}]}]}