{"metadata":{"title":"MCAudioConfiguration","role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCAudioConfiguration","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"MCAudioConfiguration","kind":"identifier"}]},"abstract":[{"type":"text","text":"Global Audio Configuration object."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/audioPlayerNodeDelegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/pan"],"title":"Instance Properties","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioConfiguration":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration","abstract":[{"type":"text","text":"Global Audio Configuration object."}],"kind":"symbol","type":"topic","title":"MCAudioConfiguration","url":"\/documentation\/millicastsdk\/mcaudioconfiguration","navigatorTitle":[{"text":"MCAudioConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioConfiguration","kind":"identifier"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioConfiguration/audioPlayerNodeDelegate":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioconfiguration\/audioplayernodedelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDelegate"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/audioPlayerNodeDelegate","type":"topic","abstract":[{"text":"Delegate for receiving AVAudioPlayerNode updates.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"MCAudioPlayerNodeDelegate","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodeDelegate"},{"kind":"text","text":")?"}],"title":"audioPlayerNodeDelegate"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioConfiguration/pan":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/pan","abstract":[{"text":"Set the stereo pan if applicable. This property will apply panning if","type":"text"},{"text":" ","type":"text"},{"text":"the played audio is in stereo. Valid values are -1 to 1","type":"text"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/millicastsdk\/mcaudioconfiguration\/pan","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"navigatorTitle":[{"kind":"identifier","text":"pan"}],"title":"pan"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCAudioConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCAudioConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MCAudioConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/audioPlayerNodeDelegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/pan"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCAudioConfiguration","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration\/title","op":"replace"},{"value":[{"text":"MCAudioConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration\/fragments","op":"replace"},{"value":[{"text":"MCAudioConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration\/navigatorTitle","op":"replace"},{"value":"audioPlayerNodeDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1audioPlayerNodeDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"audioPlayerNodeDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1audioPlayerNodeDelegate\/fragments","op":"replace"},{"value":"pan","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1pan\/title","op":"replace"},{"value":[{"kind":"identifier","text":"pan"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1pan\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}