{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Protocol","externalID":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"modules":[{"name":"MillicastSDK"}],"title":"MCCMSampleBufferVideoRendererDelegate","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"role":"symbol"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didChange(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didReceive(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"Delegate for  receiving raw video "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" ready for rendering"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate/didChange(_:)":{"type":"topic","role":"symbol","title":"didChange(_:)","navigatorTitle":[{"kind":"identifier","text":"didChangeSize:"}],"abstract":[{"text":"A delegate method that will be called when the size of the incoming video frames has changed.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didChange(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didchange(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate/didReceive(_:)":{"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didreceive(_:)","abstract":[{"text":"A delegate method that will receive CMSampleBufferRef that contain raw video ready for rendering.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didReceive(_:)","role":"symbol","title":"didReceive(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","text":"CMSampleBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"required":true},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"kind":"symbol","abstract":[{"text":"Delegate for  receiving raw video ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"text":" ready for rendering","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","title":"MCCMSampleBufferVideoRendererDelegate","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"title":"MCSampleBufferVideoUIView","role":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCCMSampleBufferVideoRendererDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didChange(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didReceive(_:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"conformingTypes","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"],"kind":"relationships","title":"Conforming Types"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"didChangeSize:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didChange(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeSize:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didChange(_:)\/fragments"},{"value":"didReceiveSampleBuffer:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didReceive(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didReceive(_:)\/fragments"},{"value":"MCCMSampleBufferVideoRendererDelegate","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/navigatorTitle"},{"value":"MCSampleBufferVideoUIView","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/navigatorTitle"}]}]}