{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/init()"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/videoSize"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/addDelegate(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/removeDelegate(_:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This class works in union with ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","isActive":true},{"text":", ","type":"text"},{"code":"MCSampleBufferVideoNSView","type":"codeVoice"},{"text":" ","type":"text"},{"text":"which contain ","type":"text"},{"code":"AVSampleBufferDisplayLayer","type":"codeVoice"},{"text":" for rendering.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Attach this class to an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"},{"type":"text","text":", "},{"type":"codeVoice","code":"MCSampleBufferVideoNSView"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSwiftUIView"},{"type":"text","text":" to render onto a View."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class being an "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"type":"text","text":" can be attached"},{"type":"text","text":" "},{"type":"text","text":"to a "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","isActive":true},{"type":"text","text":" or "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to receive video frames."}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This class is responsible for converting ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"text":"  into renderable ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"text":" frames.","type":"text"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"externalID":"c:objc(cs)MCCMSampleBufferVideoRenderer","symbolKind":"class","role":"symbol","roleHeading":"Class","title":"MCCMSampleBufferVideoRenderer","navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"role":"symbol","abstract":[{"text":"This class is responsible for converting ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"type":"text","text":"  into renderable "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"text":" frames.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"title":"MCCMSampleBufferVideoRenderer","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"title":"MCWebrtcRemoteVideoTrack","type":"topic","abstract":[{"text":"The webrtc logical track’s video interface.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"title":"MCSampleBufferVideoUIView","role":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack":{"abstract":[{"text":"Responsible for managing video capture session from a video source.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideotrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","navigatorTitle":[{"kind":"identifier","text":"MCVideoTrack"}],"title":"MCVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoTrack"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/addDelegate(_:)":{"title":"addDelegate(_:)","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/adddelegate(_:)","type":"topic","abstract":[{"type":"text","text":"Add a delegate to receive "},{"type":"codeVoice","code":"MCCMSampleBufferVideoRendererDelegate"},{"type":"text","text":" events, supports multiple delegates."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addDelegate:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/addDelegate(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideorenderer","title":"MCVideoRenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/removeDelegate(_:)":{"title":"removeDelegate(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/removeDelegate(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeDelegate"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"MCCMSampleBufferVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"removeDelegate:"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/removedelegate(_:)","kind":"symbol","abstract":[{"text":"Removes the delegate from the list of delegates.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSwiftUIView":{"url":"\/documentation\/millicastsdk\/mcvideoswiftuiview","kind":"symbol","abstract":[{"type":"text","text":"Swift UI View that can use either Metal or a sample buffer to render a track."}],"title":"MCVideoSwiftUIView","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSwiftUIView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoSwiftUIView"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSwiftUIView"}]},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe","title":"MCVideoFrame","abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"type":"text","text":" for playback."}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/init()":{"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize the renderer."}],"title":"init()","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/init()"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","abstract":[{"text":"The RTS logical track’s video interface.","type":"text"}],"title":"MCRTSRemoteVideoTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/videoSize":{"abstract":[{"type":"text","text":"The size of the last video frame received."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"role":"symbol","title":"videoSize","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/videoSize","navigatorTitle":[{"kind":"identifier","text":"videoSize"}],"type":"topic","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/videosize"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","title":"add(_:)","abstract":[{"text":"Adds a VideoRenderer to render this video track.","type":"text"},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCCMSampleBufferVideoRenderer","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/videoSize"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/addDelegate(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/init()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/removeDelegate(_:)"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCCMSampleBufferVideoRenderer","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title"},{"value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments"},{"value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/navigatorTitle"},{"value":"MCWebrtcRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments"},{"value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/navigatorTitle"},{"value":"MCSampleBufferVideoUIView","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title"},{"value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"},{"value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/navigatorTitle"},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"value":[{"kind":"identifier","text":"MCVideoTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/fragments"},{"value":[{"kind":"identifier","text":"MCVideoTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/navigatorTitle"},{"value":"addDelegate:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1addDelegate(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1addDelegate(_:)\/fragments"},{"value":"MCVideoRenderer","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title"},{"value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"},{"value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/navigatorTitle"},{"value":"removeDelegate:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1removeDelegate(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1removeDelegate(_:)\/fragments"},{"value":"MCVideoFrame","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1init()\/fragments"},{"value":"MCRTSRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/navigatorTitle"},{"value":"videoSize","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1videoSize\/title"},{"value":[{"text":"videoSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1videoSize\/fragments"},{"value":"addRenderer:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}