{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogger","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mclogger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mclogger"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo"}],"abstract":[{"text":"Class that is responsible for managing SDK logs.","type":"text"}],"topicSections":[{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getVersion()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getWebrtcVersion()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setDelegate(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setLogLevelWithSdk(_:webrtc:websocket:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger","interfaceLanguage":"swift"},"metadata":{"title":"MCLogger","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}],"externalID":"c:objc(cs)MCLogger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogger","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/setLogLevelWithSdk(_:webrtc:websocket:)":{"navigatorTitle":[{"text":"setLogLevelWithSdk:Webrtc:Websocket:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setLogLevelWithSdk(_:webrtc:websocket:)","url":"\/documentation\/millicastsdk\/mclogger\/setloglevelwithsdk(_:webrtc:websocket:)","abstract":[{"text":"Set the LogLevel for the SDK\/Webrtc\/Websocket modules","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setLogLevelWithSdk"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCLogLevel","text":"MCLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webrtc"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCLogLevel","text":"MCLogLevel"},{"text":", ","kind":"text"},{"text":"websocket","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCLogLevel","text":"MCLogLevel","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"setLogLevelWithSdk(_:webrtc:websocket:)"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/setDelegate(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCLoggerDelegate","text":"MCLoggerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mclogger\/setdelegate(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setDelegate(_:)","title":"setDelegate(_:)","abstract":[{"type":"text","text":"Set a delegate that receives log messages."}],"role":"symbol","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/getWebrtcVersion()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWebrtcVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","title":"getWebrtcVersion()","navigatorTitle":[{"kind":"identifier","text":"getWebrtcVersion"}],"url":"\/documentation\/millicastsdk\/mclogger\/getwebrtcversion()","abstract":[{"type":"text","text":"Get the current WebRTC version used."}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getWebrtcVersion()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/getVersion()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVersion","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getVersion","kind":"identifier"}],"title":"getVersion()","abstract":[{"type":"text","text":"Get the current SDK version"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getVersion()","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mclogger\/getversion()","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger":{"title":"MCLogger","role":"symbol","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mclogger","abstract":[{"type":"text","text":"Class that is responsible for managing SDK logs."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogger","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MCLogger"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCLogger","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCLogger","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getVersion()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/getWebrtcVersion()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setDelegate(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setLogLevelWithSdk(_:webrtc:websocket:)"],"generated":true,"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogger"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"setLogLevelWithSdk:Webrtc:Websocket:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setLogLevelWithSdk(_:webrtc:websocket:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setLogLevelWithSdk:Webrtc:Websocket:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setLogLevelWithSdk(_:webrtc:websocket:)\/fragments"},{"value":"setDelegate:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setDelegate(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setDelegate(_:)\/fragments"},{"value":"getWebrtcVersion","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1getWebrtcVersion()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getWebrtcVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1getWebrtcVersion()\/fragments"},{"value":"getVersion","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1getVersion()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"getVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1getVersion()\/fragments"},{"value":"MCLogger","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/title"},{"value":[{"text":"MCLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/fragments"},{"value":[{"text":"MCLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/navigatorTitle"}]}]}