{"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/currentMID","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/delegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/isActive","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/kind","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/sourceID"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activity()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activityPublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asAudio()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asVideo()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/disable(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layers()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layersPublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/mid()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/midPublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/stats()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/statsPublisher()"]},{"generated":true,"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/ActivityEvent"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","title":"MCRTSRemoteTrack","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"symbolKind":"class","externalID":"c:objc(cs)MCRTSRemoteTrack"},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"type":"text","text":" "},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"type":"text","text":" "},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"type":"text","text":" "},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"type":"text","text":" "},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/layersPublisher()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layersPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layersPublisher()","abstract":[{"type":"text","text":"Get a Combine based layers publisher."}],"title":"layersPublisher()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/layerspublisher()","kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/mid()":{"abstract":[{"text":"Create an AsyncStream to receive track mid updates.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/mid()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?>","kind":"text"}],"kind":"symbol","title":"mid()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/mid()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/activityPublisher()":{"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activityPublisher()","title":"activityPublisher()","kind":"symbol","abstract":[{"text":"Get a Combine based activity publisher","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/activitypublisher()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activityPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:So16MCRTSRemoteTrackC12MillicastSDKE13ActivityEventO","text":"ActivityEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"type":"topic","abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","title":"MCRTSRemoteTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","abstract":[{"text":"The RTS logical track’s video interface.","type":"text"}],"title":"MCRTSRemoteVideoTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/ActivityEvent":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/ActivityEvent","title":"MCRTSRemoteTrack.ActivityEvent","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/activityevent","type":"topic","abstract":[{"text":"Track activity event","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ActivityEvent","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityEvent","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/isActive":{"title":"isActive","navigatorTitle":[{"text":"isActive","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether the track is currently active."}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/isactive","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/isActive","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/sourceID":{"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/sourceid","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"sourceID","type":"topic","role":"symbol","navigatorTitle":[{"text":"sourceID","kind":"identifier"}],"abstract":[{"type":"text","text":"The source ID of the track’s publisher."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/sourceID"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/activity()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activity","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:So16MCRTSRemoteTrackC12MillicastSDKE13ActivityEventO","text":"ActivityEvent","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/activity()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/activity()","abstract":[{"type":"text","text":"Create an AsyncStream to receive track activity events"}],"title":"activity()","kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/midPublisher()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/midPublisher()","type":"topic","role":"symbol","title":"midPublisher()","abstract":[{"type":"text","text":"Get a Combine based layers publisher."}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/midpublisher()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"midPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/layers()":{"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/layers()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layers()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrackLayers","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Create an AsyncStream to receive track simulcast\/SVC layers when they are available","type":"text"}],"title":"layers()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/statsPublisher()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/statsPublisher()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCTrackStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/statspublisher()","abstract":[{"text":"Get a Combine based stats publisher.","type":"text"}],"role":"symbol","title":"statsPublisher()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteAudioTrack":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack","title":"MCRTSRemoteAudioTrack","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","abstract":[{"text":"The RTS logical track’s audio interface.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/currentMID":{"kind":"symbol","role":"symbol","title":"currentMID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"currentMID"}],"abstract":[{"type":"text","text":"The current MID of the track. Useful to parse statistics based on the mid."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/currentMID","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/currentmid"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/disable(completionHandler:)":{"kind":"symbol","title":"disable(completionHandler:)","abstract":[{"text":"Disable the track. This makes the track stop receiving events\/media.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/disable(completionhandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/disable(completionHandler:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"disableWithCompletionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/delegate":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/delegate","title":"delegate","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/delegate","abstract":[{"type":"text","text":"Delegate to receive track related events."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"MCRTSRemoteTrackDelegate","preciseIdentifier":"c:objc(pl)MCRTSRemoteTrackDelegate"},{"kind":"text","text":")?"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/asVideo()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asVideo()","navigatorTitle":[{"kind":"identifier","text":"asVideo"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/asvideo()","role":"symbol","title":"asVideo()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asVideo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned."}]},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/stats()":{"role":"symbol","kind":"symbol","title":"stats()","abstract":[{"type":"text","text":"Create an AsyncStream to receive track stats."}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/stats()","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/stats()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stats","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"text":"MCTrackStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"text":">","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/asAudio()":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"asAudio","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asAudio()","title":"asAudio()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asAudio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCRTSRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned."}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/asaudio()","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/kind":{"navigatorTitle":[{"text":"kind","kind":"identifier"}],"title":"kind","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/kind","type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/kind","abstract":[{"type":"text","text":"Either an Audio or Video track."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/currentMID","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/delegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/isActive","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/kind","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/sourceID"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asAudio()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asVideo()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/disable(completionHandler:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/navigatorTitle","op":"replace"},{"value":"MCRTSRemoteVideoTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","op":"replace"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/navigatorTitle","op":"replace"},{"value":"isActive","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1isActive\/title","op":"replace"},{"value":[{"text":"isActive","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1isActive\/fragments","op":"replace"},{"value":"sourceID","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1sourceID\/title","op":"replace"},{"value":[{"text":"sourceID","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1sourceID\/fragments","op":"replace"},{"value":"MCRTSRemoteAudioTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/title","op":"replace"},{"value":[{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/fragments","op":"replace"},{"value":[{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/navigatorTitle","op":"replace"},{"value":"currentMID","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1currentMID\/title","op":"replace"},{"value":[{"kind":"identifier","text":"currentMID"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1currentMID\/fragments","op":"replace"},{"value":"disableWithCompletionHandler:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1disable(completionHandler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"disableWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1disable(completionHandler:)\/fragments","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1delegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1delegate\/fragments","op":"replace"},{"value":"asVideo","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asVideo()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"asVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asVideo()\/fragments","op":"replace"},{"value":"asAudio","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asAudio()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"asAudio","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asAudio()\/fragments","op":"replace"},{"value":"kind","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1kind\/title","op":"replace"},{"value":[{"text":"kind","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1kind\/fragments","op":"replace"}]}]}