{"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSDKConfiguration","kind":"identifier"}],"externalID":"c:objc(cs)MCSDKConfiguration","modules":[{"name":"MillicastSDK"}],"title":"MCSDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"MCSDKConfiguration"}],"roleHeading":"Class","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSDKConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"name":"Remark","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be called before any SDK objects are instantiated. This API can only be called once."},{"type":"text","text":" "},{"type":"text","text":"Further calls are ignored."}]}]}]}],"abstract":[{"type":"text","text":"Global SDK Configuration. Use this class to modify"},{"type":"text","text":" "},{"type":"text","text":"global behaviour in the SDK."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsdkconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsdkconfiguration"]}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSDKConfiguration\/configure(_:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSDKConfiguration","interfaceLanguage":"swift"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSDKConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSDKConfiguration","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsdkconfiguration","abstract":[{"text":"Global SDK Configuration. Use this class to modify","type":"text"},{"text":" ","type":"text"},{"text":"global behaviour in the SDK.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MCSDKConfiguration","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSDKConfiguration","title":"MCSDKConfiguration"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/SH":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSDKConfiguration/configure(_:)":{"navigatorTitle":[{"text":"configure:","kind":"identifier"}],"title":"configure(_:)","url":"\/documentation\/millicastsdk\/mcsdkconfiguration\/configure(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCAudioConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioConfiguration"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSDKConfiguration\/configure(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCSDKConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCSDKConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCSDKConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSDKConfiguration\/configure(_:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSDKConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCSDKConfiguration","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSDKConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCSDKConfiguration"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSDKConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCSDKConfiguration"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSDKConfiguration\/navigatorTitle","op":"replace"},{"value":"configure:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSDKConfiguration~1configure(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"configure:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSDKConfiguration~1configure(_:)\/fragments","op":"replace"}]}]}