{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/getCapabilities()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/setCapability(_:)"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSource","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideosource"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSource"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MCVideoSource"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCVideoSource","symbolKind":"class","title":"MCVideoSource"},"abstract":[{"type":"text","text":"Responsible for managing video sources."}],"references":{"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/setCapability(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCapability"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoCapabilities","text":"MCVideoCapabilities"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Enable a specific video capability on the video source."}],"title":"setCapability(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/setCapability(_:)","url":"\/documentation\/millicastsdk\/mcvideosource\/setcapability(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCapability:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSource":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource","url":"\/documentation\/millicastsdk\/mcsource","title":"MCSource","abstract":[{"text":"Gathers information about the source.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/CaptureSource":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureSource"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureSource"}],"title":"CaptureSource","role":"symbol","abstract":[{"text":"Manages the process of capturing the source by input sources, such as a microphone or a camera.","type":"text"}],"url":"\/documentation\/millicastsdk\/capturesource","kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/change(_:)":{"title":"change(_:)","abstract":[{"text":"Change the underlying video source. For example in the case of a Camera, switch","type":"text"},{"text":" ","type":"text"},{"text":"between front\/rear camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:)","url":"\/documentation\/millicastsdk\/mcvideosource\/change(_:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"changeVideoSource:"}]},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/getCapabilities()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/getCapabilities()","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideosource\/getcapabilities()","navigatorTitle":[{"text":"getCapabilities","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The current set of capabilities configured for the video source."}],"title":"getCapabilities()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCapabilities","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities","kind":"typeIdentifier"},{"text":"]!","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource":{"role":"symbol","navigatorTitle":[{"text":"MCVideoSource","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource","title":"MCVideoSource","url":"\/documentation\/millicastsdk\/mcvideosource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSource","kind":"identifier"}],"abstract":[{"text":"Responsible for managing video sources.","type":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/change(_:_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:_:)","abstract":[{"type":"text","text":"Changes the current video source to a new source based on the provided device ID, for example"},{"type":"text","text":" "},{"type":"text","text":"if there is an external camera connected and a device ID is known."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideosource\/change(_:_:)","title":"change(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"change","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"changeVideoSource::","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MCVideoSource"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/change(_:_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/getCapabilities()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/setCapability(_:)"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/CaptureSource"],"title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSource"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)MCSource","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSource","text":"MCSource"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1setCapability(_:)\/title","value":"setCapability:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1setCapability(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCapability:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"text":"MCSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSource\/navigatorTitle","value":[{"text":"MCSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/title","value":"CaptureSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/fragments","value":[{"kind":"identifier","text":"CaptureSource"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1CaptureSource\/navigatorTitle","value":[{"text":"CaptureSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1change(_:)\/title","value":"changeVideoSource:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1change(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"changeVideoSource:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1getCapabilities()\/title","value":"getCapabilities"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1getCapabilities()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getCapabilities","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/title","value":"MCVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/fragments","value":[{"text":"MCVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1change(_:_:)\/title","value":"changeVideoSource::"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1change(_:_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"changeVideoSource::","kind":"identifier"}]}]}]}