{"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/delegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/mirror","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/scalingMode"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoViewType"}],"symbolKind":"protocol","externalID":"s:12MillicastSDK15MCVideoViewTypeP","roleHeading":"Protocol","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCVideoViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoViewType"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoViewType"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"],"kind":"relationships","type":"conformingTypes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Common properties among the Views provided"},{"type":"text","text":" "},{"type":"text","text":"in the SDK."}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoViewType/scalingMode":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scalingMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO","text":"MCVideoViewScalingMode","kind":"typeIdentifier"}],"required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcvideoviewtype\/scalingmode","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/scalingMode","kind":"symbol","title":"scalingMode","abstract":[{"text":"ScalingMode for video.","type":"text"},{"text":" ","type":"text"},{"text":"Use this to decide how the video is displayed within the bounds of the UIView.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoViewType/mirror":{"required":true,"abstract":[{"text":"Mirroring the content of the View.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/mirror","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirror","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"mirror","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoviewtype\/mirror","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoViewType":{"type":"topic","url":"\/documentation\/millicastsdk\/mcvideoviewtype","abstract":[{"type":"text","text":"Common properties among the Views provided"},{"type":"text","text":" "},{"type":"text","text":"in the SDK."}],"role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoViewType","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType","title":"MCVideoViewType","navigatorTitle":[{"text":"MCVideoViewType","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","type":"topic","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal as a backend for rendering."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"title":"MCSampleBufferVideoUIView","role":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoViewType/delegate":{"required":true,"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MillicastSDK19MCVideoViewDelegateP","text":"MCVideoViewDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the delegate to receive view events"}],"role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewType\/delegate","url":"\/documentation\/millicastsdk\/mcvideoviewtype\/delegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","op":"replace","value":"MCAcceleratedVideoUIView"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","op":"replace","value":"MCSampleBufferVideoUIView"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]}]}]}