{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideorenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideorenderer"]}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer\/didReceive(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","type":"reference","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer"],"type":"conformingTypes","title":"Conforming Types"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCVideoRenderer","title":"MCVideoRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayback":{"role":"symbol","title":"MCAudioPlayback","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback","type":"topic","abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"type":"text","text":" "},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCNdiRenderer":{"role":"symbol","title":"MCNdiRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCNdiRenderer"}],"url":"\/documentation\/millicastsdk\/mcndirenderer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCNdiRenderer"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer","abstract":[{"text":"The  class is responsible for rendering video as an NDI source. To render audio with NDI, use","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback","type":"reference"},{"text":" with the NDI output instead.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe","title":"MCVideoFrame","abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"type":"text","text":" for playback."}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","title":"add(_:)","abstract":[{"text":"Adds a VideoRenderer to render this video track.","type":"text"},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"role":"symbol","abstract":[{"text":"This class is responsible for converting ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"type":"text","text":"  into renderable "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"text":" frames.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"title":"MCCMSampleBufferVideoRenderer","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer/didReceive(_:)":{"abstract":[{"text":"This handler is called when a new video frame becomes available, either captured or received.","type":"text"}],"required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcvideorenderer\/didreceive(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoFrame","text":"MCVideoFrame","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer\/didReceive(_:)","kind":"symbol","title":"didReceive(_:)","role":"symbol","navigatorTitle":[{"text":"didReceiveFrame:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideorenderer","title":"MCVideoRenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"kind":"symbol","title":"MCAcceleratedVideoRenderer","role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"MCVideoRenderer"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer\/didReceive(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"title":"Inherits From"},{"type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCNdiRenderer"],"title":"Conforming Types"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoRenderer","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"MCAudioPlayback","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioPlayback"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments"},{"op":"replace","value":[{"text":"MCAudioPlayback","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/navigatorTitle"},{"op":"replace","value":"MCNdiRenderer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCNdiRenderer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCNdiRenderer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCNdiRenderer\/navigatorTitle"},{"op":"replace","value":"MCVideoFrame","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"op":"replace","value":[{"text":"MCVideoFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/navigatorTitle","value":[{"text":"MCVideoFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/navigatorTitle","value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer~1didReceive(_:)\/title","value":"didReceiveFrame:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer~1didReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/navigatorTitle","value":[{"text":"MCVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/navigatorTitle","value":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}