{"abstract":[{"type":"text","text":"It is calculated by the underlying congestion control by combining the available bitrate for all the outgoing RTP streams using this candidate pair. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_outgoing_bitrate","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"available_outgoing_bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"available_outgoing_bitrate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"available_outgoing_bitrate"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCIceCandidatePairStats(py)available_outgoing_bitrate"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_outgoing_bitrate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_outgoing_bitrate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"available_outgoing_bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats":{"navigatorTitle":[{"kind":"identifier","text":"MCIceCandidatePairStats"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats","abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","title":"MCIceCandidatePairStats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCIceCandidatePairStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/available_outgoing_bitrate":{"role":"symbol","title":"available_outgoing_bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"available_outgoing_bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"available_outgoing_bitrate"}],"url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_outgoing_bitrate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_outgoing_bitrate","abstract":[{"text":"It is calculated by the underlying congestion control by combining the available bitrate for all the outgoing RTP streams using this candidate pair. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate","isActive":true,"type":"reference"}],"type":"topic","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-availableoutgoingbitrate":{"title":"availableoutgoingbitrate","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate","type":"link","titleInlineContent":[{"text":"availableoutgoingbitrate","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"available_outgoing_bitrate","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"available_outgoing_bitrate"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"available_outgoing_bitrate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"MCIceCandidatePairStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title"},{"op":"replace","value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments"},{"value":"available_outgoing_bitrate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_outgoing_bitrate\/title","op":"replace"},{"op":"replace","value":[{"text":"available_outgoing_bitrate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_outgoing_bitrate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}