{"sections":[],"abstract":[{"type":"text","text":"Adjust the bitrate settings. This is only available for publishing."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateSettings"},{"kind":"text","text":": "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","preciseIdentifier":"c:objc(cs)MCBitrateSettings","kind":"typeIdentifier","text":"MCBitrateSettings"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/bitrateSettings"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/bitratesettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/bitratesettings"]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitrateSettings","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCBitrateSettings","preciseIdentifier":"c:objc(cs)MCBitrateSettings","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"bitrateSettings","kind":"identifier"}],"title":"bitrateSettings","externalID":"c:objc(cs)MCClientOptions(py)bitrateSettings","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"url":"\/documentation\/millicastsdk\/mcclientoptions","title":"MCClientOptions","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/bitrateSettings":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/bitrateSettings","type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions\/bitratesettings","abstract":[{"type":"text","text":"Adjust the bitrate settings. This is only available for publishing."}],"role":"symbol","navigatorTitle":[{"text":"bitrateSettings","kind":"identifier"}],"title":"bitrateSettings","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCBitrateSettings","text":"MCBitrateSettings"},{"text":"?","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","navigatorTitle":[{"kind":"identifier","text":"MCBitrateSettings"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcbitratesettings","role":"symbol","title":"MCBitrateSettings","abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCBitrateSettings"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bitrateSettings","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bitrateSettings"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)MCBitrateSettings","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","kind":"typeIdentifier","text":"MCBitrateSettings"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bitrateSettings"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCClientOptions","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title","op":"replace"},{"value":[{"text":"MCClientOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments","op":"replace"},{"value":[{"text":"MCClientOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/navigatorTitle","op":"replace"},{"value":"bitrateSettings","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1bitrateSettings\/title","op":"replace"},{"value":[{"text":"bitrateSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1bitrateSettings\/fragments","op":"replace"},{"value":"MCBitrateSettings","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCBitrateSettings"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","op":"replace"},{"value":[{"text":"MCBitrateSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/navigatorTitle","op":"replace"}]}]}