{"metadata":{"externalID":"c:objc(cs)MCRTSRemoteTrack(py)kind","navigatorTitle":[{"kind":"identifier","text":"kind"}],"roleHeading":"Instance Property","title":"kind","role":"symbol","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind"}],"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/kind","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Either an Audio or Video track."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/kind"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/kind"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/kind":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"text":"MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind"}],"navigatorTitle":[{"kind":"identifier","text":"kind"}],"title":"kind","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/kind","abstract":[{"text":"Either an Audio or Video track.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/kind","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteTrackKind":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","title":"MCRemoteTrackKind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRemoteTrackKind","kind":"identifier"}],"abstract":[{"text":"Enum specifying the type of the remote track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","navigatorTitle":[{"kind":"identifier","text":"MCRemoteTrackKind"}],"type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrack"}],"navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"text":" ","type":"text"},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"text":" ","type":"text"},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"type":"text","text":" "},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"title":"MCRTSRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"kind","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"kind","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kind"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1kind\/title","value":"kind"},{"op":"replace","value":[{"text":"kind","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1kind\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title","value":"MCRemoteTrackKind"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}]},{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}]}]}]}