{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mid","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?>"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"a new AsyncStream that receives mid updates","type":"text"}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"Refer to "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"for more information."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"metadata":{"roleHeading":"Instance Method","extendedModule":"MillicastSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mid"},{"kind":"text","text":"() -> "},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?>","kind":"text"}],"role":"symbol","symbolKind":"method","title":"mid()","modules":[{"name":"MillicastSDK"}],"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE3midScSySSSgGyF"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/mid()"},"abstract":[{"type":"text","text":"Create an AsyncStream to receive track mid updates."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/mid()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrack"}],"navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"text":" ","type":"text"},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"text":" ","type":"text"},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"type":"text","text":" "},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"title":"MCRTSRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateMID:)":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatemid:)","navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didUpdateMID:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateMID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","title":"rtsRemoteTrack(_:didUpdateMID:)","abstract":[{"text":"Event received when the underlying WebRTC MID has changed. This can happen","type":"text"},{"type":"text","text":" "},{"text":"in cases of network dropouts or in general when the underlying peer connection has","type":"text"},{"type":"text","text":" "},{"text":"been torn down. In general, keeping the MID handy is useful when parsing ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"},{"type":"text","text":" "},{"type":"text","text":"based on the mid, since each mid corresponds to one track."}],"role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/mid()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?>"}],"title":"mid()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/mid()","abstract":[{"text":"Create an AsyncStream to receive track mid updates.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/mid()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/title","op":"replace","value":"rtsRemoteTrack:didUpdateMID:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrack:didUpdateMID:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/fragments"},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace"}]}]}