{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"~=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"internalParam","text":"match"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"error","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/~=(_:_:)"]}],"metadata":{"externalID":"s:10Foundation18_ErrorCodeProtocolPAAE2teoiySbx_s0B0_ptFZ::SYNTHESIZED::c:@E@MCAsyncOperationCancelledError","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"~="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"relatedModules":["Foundation"],"name":"MillicastSDK"}],"title":"~=(_:_:)","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"8.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"8.0","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"10.10","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0","beta":false},{"deprecated":false,"unavailable":false,"name":"watchOS","introducedAt":"2.0","beta":false}],"extendedModule":"Foundation","roleHeading":"Operator","symbolKind":"op","role":"symbol"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/~=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Allow one to match an error code against an arbitrary error."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/~=(_:_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/~=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"~=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Allow one to match an error code against an arbitrary error.","type":"text"}],"kind":"symbol","title":"~=(_:_:)","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/~=(_:_:)","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","kind":"symbol","title":"MCAsyncOperationCancelledError.Code","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"text":"Error category for errors triggered when the operation failed because","type":"text"},{"text":" ","type":"text"},{"text":"it was abandoned for various reasons.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct":{"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"abstract":[],"kind":"symbol","title":"MCAsyncOperationCancelledError","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCAsyncOperationCancelledError","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title"},{"value":[{"text":"MCAsyncOperationCancelledError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments"},{"value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/navigatorTitle"}]}]}