{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"If the frame was an I444 frame, then this will return size of the frame in bytes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeI444"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The actual size if it was an I444 frame, 0 otherwise.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizei444()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizei444()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"externalID":"c:objc(pl)MCVideoFrame(im)sizeI444","symbolKind":"method","navigatorTitle":[{"text":"sizeI444","kind":"identifier"}],"role":"symbol","title":"sizeI444()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeI444","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI444()"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"title":"MCVideoRenderer","type":"topic","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"text":" ","type":"text"},{"type":"text","text":"applications. Used in "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true,"type":"reference"},{"type":"text","text":" to start receiving"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoRenderer"}],"navigatorTitle":[{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"title":"MCVideoFrame","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe","abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoFrame","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/sizeI444()":{"type":"topic","title":"sizeI444()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeI444","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"sizeI444"}],"role":"symbol","abstract":[{"type":"text","text":"If the frame was an I444 frame, then this will return size of the frame in bytes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI444()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizei444()"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sizeI444"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sizeI444","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sizeI444"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace","value":"MCVideoRenderer"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace"},{"value":"MCVideoFrame","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI444()\/title","op":"replace","value":"sizeI444"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeI444"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI444()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}