{"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","title":"MCLogLevel.verbose","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelVerbose"}],"externalID":"c:@E@MCLogLevel@MCLogLevelVerbose"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcloglevel\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcloglevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Very verbose log message.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/verbose","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel":{"type":"topic","kind":"symbol","abstract":[{"text":"The log message’s level","type":"text"}],"navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}],"title":"MCLogLevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogLevel","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","url":"\/documentation\/millicastsdk\/mcloglevel"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/verbose":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/verbose","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelVerbose"}],"type":"topic","abstract":[{"text":"Very verbose log message.","type":"text"}],"kind":"symbol","title":"MCLogLevel.verbose","url":"\/documentation\/millicastsdk\/mcloglevel\/verbose"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCLogLevelVerbose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCLogLevelVerbose","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MCLogLevelVerbose","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/fragments","value":[{"text":"MCLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1verbose\/title","value":"MCLogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1verbose\/fragments","value":[{"text":"MCLogLevelVerbose","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}