{"sections":[],"abstract":[{"text":"Warn the user about something, but does not prevent a normal utilisation.","type":"text"}],"metadata":{"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCLogLevelWarning","kind":"identifier"}],"externalID":"c:@E@MCLogLevel@MCLogLevelWarning","title":"MCLogLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcloglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcloglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/warning","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/warning":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/warning","abstract":[{"type":"text","text":"Warn the user about something, but does not prevent a normal utilisation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelWarning"}],"type":"topic","title":"MCLogLevel.warning","kind":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel":{"type":"topic","kind":"symbol","abstract":[{"text":"The log message’s level","type":"text"}],"navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}],"title":"MCLogLevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogLevel","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","url":"\/documentation\/millicastsdk\/mcloglevel"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCLogLevelWarning","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCLogLevelWarning","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"MCLogLevelWarning","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCLogLevelWarning","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1warning\/title","op":"replace"},{"value":[{"text":"MCLogLevelWarning","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1warning\/fragments","op":"replace"},{"value":"MCLogLevel","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/title","op":"replace"},{"value":[{"text":"MCLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/fragments","op":"replace"}]}]}