{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionStatePublisher()"},"abstract":[{"text":"Get a Combine based publisher that can be used to receive connection state changes for the peer","type":"text"},{"text":" ","type":"text"},{"text":"connection.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionStatePublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"MCConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/peerconnectionstatepublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"metadata":{"extendedModule":"MillicastSDK","role":"symbol","externalID":"s:So12MCSubscriberC12MillicastSDKE28peerConnectionStatePublisher7Combine03AnyG0VySo012MCConnectionF0Vs5NeverOGyF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"kind":"text","text":">"}],"roleHeading":"Instance Method","symbolKind":"method","title":"peerConnectionStatePublisher()","modules":[{"name":"MillicastSDK"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/peerConnectionStatePublisher()":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/peerConnectionStatePublisher()","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/peerconnectionstatepublisher()","abstract":[{"text":"Get a Combine based publisher that can be used to receive connection state changes for the peer","type":"text"},{"text":" ","type":"text"},{"text":"connection.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"title":"peerConnectionStatePublisher()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"title":"MCSubscriber","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCConnectionState":{"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState","kind":"symbol","url":"\/documentation\/millicastsdk\/mcconnectionstate","navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"}],"abstract":[],"title":"MCConnectionState"}},"variantOverrides":[{"patch":[{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"value":"MCConnectionState","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState\/title"},{"value":[{"text":"MCConnectionState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}