{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Exception was thrown and not handled.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionThrown"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/exceptionthrown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/exceptionthrown"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorExceptionThrown"}],"symbolKind":"case","role":"symbol","title":"MCGenericError.Code.exceptionThrown","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exceptionThrown","kind":"identifier"}],"externalID":"c:@E@MCGenericError@MCGenericErrorExceptionThrown"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/exceptionThrown","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/exceptionThrown":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/exceptionthrown","abstract":[{"type":"text","text":"Exception was thrown and not handled."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorExceptionThrown"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionThrown"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/exceptionThrown","title":"MCGenericError.Code.exceptionThrown"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","kind":"symbol","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","title":"MCGenericError.Code"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCGenericErrorExceptionThrown","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCGenericErrorExceptionThrown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCGenericErrorExceptionThrown","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCGenericErrorExceptionThrown","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1exceptionThrown\/title"},{"value":[{"kind":"identifier","text":"MCGenericErrorExceptionThrown"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1exceptionThrown\/fragments"},{"op":"replace","value":"MCGenericError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"op":"replace","value":[{"text":"MCGenericError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}