{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreate"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCGenericErrorPeerConnectionCreate","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MCGenericError@MCGenericErrorPeerConnectionCreate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreate"}],"symbolKind":"case","role":"symbol","title":"MCGenericError.Code.peerConnectionCreate"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"kind":"symbol","abstract":[{"text":"Can not create PeerConnection.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreate"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","kind":"symbol","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","title":"MCGenericError.Code"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionCreate":{"kind":"symbol","title":"MCGenericError.Code.peerConnectionCreate","role":"symbol","abstract":[{"text":"Can not create PeerConnection.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreate","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreate"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreate"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCGenericErrorPeerConnectionCreate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCGenericErrorPeerConnectionCreate","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","value":"MCGenericError"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCGenericError"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreate\/title","value":"MCGenericErrorPeerConnectionCreate"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreate\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}