{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/bgra"},"metadata":{"externalID":"c:@E@MCVideoType@MCVideoTypeBGRA","modules":[{"name":"MillicastSDK"}],"symbolKind":"case","role":"symbol","title":"MCVideoType.bgra","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgra","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoTypeBGRA","kind":"identifier"}],"roleHeading":"Case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgra","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/bgra"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/bgra"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"url":"\/documentation\/millicastsdk\/mcvideotype","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"title":"MCVideoType"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/bgra":{"url":"\/documentation\/millicastsdk\/mcvideotype\/bgra","title":"MCVideoType.bgra","type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/bgra","navigatorTitle":[{"text":"MCVideoTypeBGRA","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgra","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCVideoTypeBGRA","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCVideoTypeBGRA","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MCVideoTypeBGRA","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCVideoType","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCVideoType"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments"},{"op":"replace","value":"MCVideoTypeBGRA","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1bgra\/title"},{"op":"replace","value":[{"text":"MCVideoTypeBGRA","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1bgra\/fragments"}]}]}