{"metadata":{"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCVideoType@MCVideoTypeMJPEG","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mjpeg","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeMJPEG"}],"symbolKind":"case","role":"symbol","title":"MCVideoType.mjpeg"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mjpeg"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/mjpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/mjpeg"]}],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/mjpeg","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/mjpeg":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/mjpeg","url":"\/documentation\/millicastsdk\/mcvideotype\/mjpeg","type":"topic","title":"MCVideoType.mjpeg","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mjpeg","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoTypeMJPEG","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"url":"\/documentation\/millicastsdk\/mcvideotype","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"title":"MCVideoType"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCVideoTypeMJPEG","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoTypeMJPEG"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCVideoTypeMJPEG"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCVideoTypeMJPEG","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1mjpeg\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoTypeMJPEG"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1mjpeg\/fragments","op":"replace"},{"value":"MCVideoType","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title","op":"replace"},{"value":[{"text":"MCVideoType","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}