{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asPublishDetails"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MCStreamPublishDetails","kind":"typeIdentifier","text":"MCStreamPublishDetails","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asPublishDetails","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStreamPublishDetails","preciseIdentifier":"c:objc(cs)MCStreamPublishDetails"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)MCStreamDetails(im)asPublishDetails","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asPublishDetails"}],"title":"asPublishDetails()","modules":[{"name":"MillicastSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asPublishDetails()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstreamdetails\/aspublishdetails()"]},{"paths":["\/documentation\/millicastsdk\/mcstreamdetails\/aspublishdetails()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails/asPublishDetails()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asPublishDetails()","url":"\/documentation\/millicastsdk\/mcstreamdetails\/aspublishdetails()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asPublishDetails"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStreamPublishDetails","preciseIdentifier":"c:objc(cs)MCStreamPublishDetails"},{"kind":"text","text":"?"}],"title":"asPublishDetails()","abstract":[],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"asPublishDetails"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamPublishDetails":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStreamPublishDetails","kind":"identifier"}],"title":"MCStreamPublishDetails","navigatorTitle":[{"text":"MCStreamPublishDetails","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails","type":"topic","url":"\/documentation\/millicastsdk\/mcstreampublishdetails"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails":{"abstract":[{"type":"text","text":"A type erased stream details class. A holder"},{"type":"text","text":" "},{"type":"text","text":"For either Stream Publish Details or Stream View Details."},{"text":" ","type":"text"},{"text":"This class contains the current streaming","type":"text"},{"type":"text","text":" "},{"type":"text","text":"session identifying information. Used to correlate"},{"type":"text","text":" "},{"text":"debugging info with a particular streaming session.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcstreamdetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStreamDetails"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","title":"MCStreamDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStreamDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"asPublishDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asPublishDetails"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamPublishDetails","text":"MCStreamPublishDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamPublishDetails"},{"kind":"text","text":" *) "},{"text":"asPublishDetails","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asPublishDetails()\/title","value":"asPublishDetails","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asPublishDetails"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asPublishDetails()\/fragments"},{"op":"replace","value":"MCStreamPublishDetails","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamPublishDetails\/fragments","value":[{"text":"MCStreamPublishDetails","kind":"identifier"}]},{"op":"replace","value":"MCStreamDetails","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/fragments","value":[{"text":"MCStreamDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}