{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"True if the audio source is capturing. False otherwise.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/isCapturing()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks whether the AudioSource instance is currently actively capturing audio."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiosource\/iscapturing()"]},{"paths":["\/documentation\/millicastsdk\/mcaudiosource\/iscapturing()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"isCapturing()","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCAudioSource(im)isCapturing","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"navigatorTitle":[{"text":"MCAudioSource","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcaudiosource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","abstract":[{"text":"Manages the audio capture functionality.","type":"text"}],"kind":"symbol","title":"MCAudioSource","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource/isCapturing()":{"title":"isCapturing()","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/isCapturing()","abstract":[{"type":"text","text":"Checks whether the AudioSource instance is currently actively capturing audio."}],"url":"\/documentation\/millicastsdk\/mcaudiosource\/iscapturing()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isCapturing","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"isCapturing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isCapturing"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:b","text":"_Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isCapturing"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title","value":"MCAudioSource"},{"value":[{"text":"MCAudioSource","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","op":"replace"},{"value":"isCapturing","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1isCapturing()\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1isCapturing()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isCapturing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}