{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"abstract":[{"text":"Information about the encoder used for stream encoding. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoder_implementation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/encoder_implementation"},"sections":[],"metadata":{"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)encoder_implementation","title":"encoder_implementation","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encoder_implementation"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"encoder_implementation","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/encoder_implementation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/encoder_implementation"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/encoder_implementation":{"role":"symbol","navigatorTitle":[{"text":"encoder_implementation","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/encoder_implementation","type":"topic","kind":"symbol","title":"encoder_implementation","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/encoder_implementation","abstract":[{"text":"Information about the encoder used for stream encoding. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encoder_implementation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"title":"MCOutboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","abstract":[{"text":"Statistics about the outbound RTP streams","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-encoderimplementation":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation","title":"encoderImplementation","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation","titleInlineContent":[{"text":"encoderImplementation","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"encoder_implementation"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"encoder_implementation"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"encoder_implementation","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1encoder_implementation\/title","value":"encoder_implementation"},{"op":"replace","value":[{"text":"encoder_implementation","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1encoder_implementation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]}]}]}