{"metadata":{"roleHeading":"Instance Property","title":"quality_limitation_resolution_changes","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)quality_limitation_resolution_changes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"quality_limitation_resolution_changes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"navigatorTitle":[{"text":"quality_limitation_resolution_changes","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_resolution_changes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_resolution_changes"]}],"abstract":[{"type":"text","text":"The number of resolution changes due to quality limitations. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","type":"reference","isActive":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality_limitation_resolution_changes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_resolution_changes","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"title":"MCOutboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","abstract":[{"text":"Statistics about the outbound RTP streams","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/quality_limitation_resolution_changes":{"role":"symbol","navigatorTitle":[{"text":"quality_limitation_resolution_changes","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_resolution_changes","type":"topic","title":"quality_limitation_resolution_changes","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_resolution_changes","abstract":[{"type":"text","text":"The number of resolution changes due to quality limitations. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","type":"reference","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quality_limitation_resolution_changes"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges":{"type":"link","title":"qualityLimitationResolutionChanges","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","titleInlineContent":[{"type":"text","text":"qualityLimitationResolutionChanges"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"quality_limitation_resolution_changes"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"quality_limitation_resolution_changes"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned long","kind":"typeIdentifier","preciseIdentifier":"c:l"},{"text":" ","kind":"text"},{"text":"quality_limitation_resolution_changes","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"MCOutboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_resolution_changes\/title","op":"replace","value":"quality_limitation_resolution_changes"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_resolution_changes\/fragments","op":"replace","value":[{"kind":"identifier","text":"quality_limitation_resolution_changes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}