{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Request the AVAudioPlayerNode to start playback and receive audio.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestPlay()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requestplay()"]},{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requestplay()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPlay"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The playback will have started when "},{"code":"audioPlayerNodeDidStartPlaying:","type":"codeVoice"},{"type":"text","text":" is invoked."}]}],"kind":"content"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestPlay","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:objc(pl)MCAudioPlayerNodePlaybackController(im)requestPlay","title":"requestPlay()","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"requestPlay"}],"symbolKind":"method"},"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"}],"title":"MCAudioPlayerNodePlaybackController","abstract":[{"type":"text","text":"This playback controller allows you to modify the state of the player node that is provided through the delegate."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController/requestPlay()":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestPlay()","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requestplay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPlay"},{"text":"()","kind":"text"}],"title":"requestPlay()","abstract":[{"type":"text","text":"Request the AVAudioPlayerNode to start playback and receive audio."}],"required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestPlay"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"requestPlay","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestPlay","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"requestPlay"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/title","value":"MCAudioPlayerNodePlaybackController"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"}],"op":"replace"},{"value":"requestPlay","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestPlay()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestPlay"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestPlay()\/fragments"}]}]}