{"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"]}],"abstract":[{"text":"Adds a VideoRenderer to render this video track.","type":"text"},{"type":"text","text":" "},{"text":"Several renderers can be added to the track.","type":"text"},{"type":"text","text":" "},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"metadata":{"symbolKind":"method","externalID":"c:objc(cs)MCVideoTrack(im)addRenderer:","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"role":"symbol","title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"text":"((any ","kind":"text"},{"text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"renderer"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","text":"MCVideoRenderer"},{"text":")!)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video renderer that will receive captured video frames."}]}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"title":"MCVideoTrack","url":"\/documentation\/millicastsdk\/mcvideotrack","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","kind":"symbol","abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoTrack"}],"navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideorenderer","title":"MCVideoRenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true,"type":"reference"},{"text":" to start receiving","type":"text"},{"type":"text","text":" "},{"text":"video frames from that video track.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoRenderer"}],"navigatorTitle":[{"text":"MCVideoRenderer","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"title":"add(_:)","abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"text":" ","type":"text"},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"addRenderer:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addRenderer:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addRenderer:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MCVideoRenderer>","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","op":"replace","value":[{"text":"MCVideoTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"},{"value":"addRenderer:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"addRenderer:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}