{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveStreamStoppedEvent:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Emitted when the stream has been stopped via a request from the subscriber to unview.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestreamstoppedevent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestreamstoppedevent:)"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"subscriber","kind":"identifier"},{"kind":"text","text":"("},{"text":"MCSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"kind":"text","text":", "},{"text":"didReceiveStreamStoppedEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","text":"MCStreamStoppedEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCSubscriberDelegate(im)subscriber:didReceiveStreamStoppedEvent:","title":"subscriber(_:didReceiveStreamStoppedEvent:)","role":"symbol","navigatorTitle":[{"text":"subscriber:didReceiveStreamStoppedEvent:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"subscriber","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCSubscriber","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","text":"MCSubscriber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveStreamStoppedEvent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","text":"MCStreamStoppedEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Millicast subscriber."}],"type":"paragraph"}],"name":"subscriber"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Event information.","type":"text"}]}],"name":"didReceiveStreamStopped"}]}],"sections":[],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","role":"symbol","abstract":[{"text":"Delegate protocol that can be implemented to receive subscriber specific","type":"text"},{"type":"text","text":" "},{"text":"events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberDelegate"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"title":"MCSubscriberDelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamStoppedEvent":{"kind":"symbol","title":"MCStreamStoppedEvent","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent","type":"topic","abstract":[{"type":"text","text":"Container for the stream stopped event. This happens"},{"type":"text","text":" "},{"text":"when the last publisher has stopped sending a stream","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no more media is available"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamStoppedEvent"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent","navigatorTitle":[{"kind":"identifier","text":"MCStreamStoppedEvent"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/subscriber(_:didReceiveStreamStoppedEvent:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveStreamStoppedEvent:)","role":"symbol","abstract":[{"text":"Emitted when the stream has been stopped via a request from the subscriber to unview.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriber","text":"MCSubscriber"},{"kind":"text","text":", "},{"text":"didReceiveStreamStoppedEvent","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCStreamStoppedEvent","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestreamstoppedevent:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscriber:didReceiveStreamStoppedEvent:"}],"title":"subscriber(_:didReceiveStreamStoppedEvent:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"subscriber:didReceiveStreamStoppedEvent:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"subscriber:didReceiveStreamStoppedEvent:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"subscriber:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MCSubscriber","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"text":" *) ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveStreamStoppedEvent:"},{"kind":"text","text":"("},{"text":"MCStreamStoppedEvent","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent","preciseIdentifier":"c:objc(cs)MCStreamStoppedEvent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCSubscriberDelegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title"},{"op":"replace","value":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace","value":"MCSubscriber"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"text":"MCSubscriber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/title","op":"replace","value":"MCStreamStoppedEvent"},{"value":[{"kind":"identifier","text":"MCStreamStoppedEvent"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveStreamStoppedEvent:)\/title","value":"subscriber:didReceiveStreamStoppedEvent:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subscriber:didReceiveStreamStoppedEvent:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveStreamStoppedEvent:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}