{"sections":[],"metadata":{"roleHeading":"Type Method","role":"symbol","title":"get_type()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"symbolKind":"method","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(cm)get_type","modules":[{"name":"MillicastSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/get_type()","interfaceLanguage":"swift"},"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/get_type()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/get_type()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"title":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"abstract":[{"text":"Different types of statistics.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","role":"symbol","title":"MCRemoteOutboundRtpStreamStats","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","navigatorTitle":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistics related to an outgoing remote RTP stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/get_type()":{"title":"get_type()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"abstract":[{"type":"text","text":"Returns the type of statistics."}],"kind":"symbol","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/get_type()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/get_type()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"get_type"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"},{"text":") ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MCStatsType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}]},{"value":"MCRemoteOutboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1get_type()\/title","value":"get_type"},{"value":[{"kind":"text","text":"+ "},{"text":"get_type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1get_type()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}