{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"round_trip_time","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/round_trip_time"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/round_trip_time"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"round_trip_time","kind":"identifier"}],"title":"round_trip_time","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"round_trip_time"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)round_trip_time","role":"symbol","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime","type":"reference","isActive":true}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/round_trip_time":{"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/round_trip_time","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"round_trip_time"}],"abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime","type":"reference","isActive":true}],"title":"round_trip_time","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"round_trip_time","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime":{"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime","title":"roundTripTime","titleInlineContent":[{"type":"text","text":"roundTripTime"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","role":"symbol","title":"MCRemoteOutboundRtpStreamStats","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","navigatorTitle":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistics related to an outgoing remote RTP stream.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"round_trip_time","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"round_trip_time","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time"},{"text":";","kind":"text"}]}]}},{"value":"round_trip_time","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time\/title"},{"value":[{"text":"round_trip_time","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time\/fragments","op":"replace"},{"op":"replace","value":"MCRemoteOutboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title"},{"value":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"}]}]}