{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The sum of round-trip times for packets sent between endpoints. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/total_round_trip_time"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/total_round_trip_time"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"sections":[],"metadata":{"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)total_round_trip_time","title":"total_round_trip_time","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"total_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"total_round_trip_time","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"total_round_trip_time"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/total_round_trip_time","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","role":"symbol","title":"MCRemoteOutboundRtpStreamStats","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","navigatorTitle":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistics related to an outgoing remote RTP stream.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/total_round_trip_time":{"abstract":[{"type":"text","text":"The sum of round-trip times for packets sent between endpoints. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime"}],"kind":"symbol","type":"topic","title":"total_round_trip_time","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/total_round_trip_time","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/total_round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"total_round_trip_time"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime","titleInlineContent":[{"text":"totalRoundTripTime","type":"text"}],"type":"link","title":"totalRoundTripTime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"total_round_trip_time"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"total_round_trip_time","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCRemoteOutboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title"},{"op":"replace","value":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"},{"value":"total_round_trip_time","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1total_round_trip_time\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1total_round_trip_time\/fragments","value":[{"text":"total_round_trip_time","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}