{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/decoder_implementation"},"abstract":[{"text":"The implementation details of the decoder. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation","isActive":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoder_implementation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoder_implementation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"decoder_implementation","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)decoder_implementation","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"decoder_implementation","kind":"identifier"}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/decoder_implementation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/decoder_implementation"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"role":"symbol","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","title":"MCInboundRtpStreamStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-decoderimplementation":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation","titleInlineContent":[{"type":"text","text":"decoderImplementation"}],"title":"decoderImplementation","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats/decoder_implementation":{"navigatorTitle":[{"text":"decoder_implementation","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/decoder_implementation","title":"decoder_implementation","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoder_implementation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/decoder_implementation","abstract":[{"type":"text","text":"The implementation details of the decoder. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation","type":"reference","isActive":true}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"decoder_implementation","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"decoder_implementation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"decoder_implementation"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace"},{"value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace"},{"value":"decoder_implementation","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1decoder_implementation\/title","op":"replace"},{"value":[{"text":"decoder_implementation","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1decoder_implementation\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}