{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/audioCodec","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bitrateSettings","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweMonitorDurationUs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweRateChangePercentage","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/degradationPreferences","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/disableAudio","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/dtx","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/excludedSourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forcePlayoutDelay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forceSmooth","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/jitterMinimumDelayMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/maximumBitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/multiplexedAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/pinnedSourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/priority","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/recordStream","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/rtcEventLogOutputPath","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/simulcast","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/sourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/statsDelayMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/stereo","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/svcMode","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/upwardsLayerWaitTimeMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/videoCodec"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"metadata":{"externalID":"c:objc(cs)MCClientOptions","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCClientOptions","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCClientOptions","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/playout-delay":{"titleInlineContent":[{"text":"this document","type":"text"}],"url":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","type":"link","title":"this document"},"https://docs.dolby.io/streaming-apis/docs/redundant-ingest#4-set-priorities":{"title":"Redundant Ingest Guide","titleInlineContent":[{"text":"Redundant Ingest Guide","type":"text"}],"type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/jitterMinimumDelayMs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/jitterMinimumDelayMs","abstract":[{"text":"The minimum jitter delay that packets of incoming audio\/video streams will experience before being played out. This can be tuned to help with networks with higher latency, but be careful using it as it will introduce this delay. For more information, refer to ","type":"text"},{"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","type":"reference","isActive":true},{"type":"text","text":" to understand more about what this field does. This is only for subscribing."}],"type":"topic","title":"jitterMinimumDelayMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/jitterminimumdelayms","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitterMinimumDelayMs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"jitterMinimumDelayMs"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/multiplexedAudioTrack":{"type":"topic","abstract":[{"text":"The number of multiplxed audio tracks to receive. This is only available for the subscriber","type":"text"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/multiplexedaudiotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/multiplexedAudioTrack","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"multiplexedAudioTrack","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"multiplexedAudioTrack","kind":"identifier"}],"title":"multiplexedAudioTrack","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/priority":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/priority","abstract":[{"type":"text","text":"The priority of redundant streams that indicates the order in which backup streams should be broadcasted in the case of any problems with the primary stream. Refer to the "},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities","type":"reference","isActive":true},{"type":"text","text":" to understand more."}],"type":"topic","title":"priority","url":"\/documentation\/millicastsdk\/mcclientoptions\/priority","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"priority","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"priority","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/dtx":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/dtx","abstract":[{"type":"text","text":"Enables discontinuous transmission on the publishing side, so audio data is only sent when a user’s voice is detected."}],"type":"topic","title":"dtx","url":"\/documentation\/millicastsdk\/mcclientoptions\/dtx","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dtx"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"dtx"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/excludedSourceId":{"title":"excludedSourceId","url":"\/documentation\/millicastsdk\/mcclientoptions\/excludedsourceid","abstract":[{"text":"Excluded sources that you do not wish to receive. Refer to ","type":"text"},{"type":"reference","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","isActive":true},{"type":"text","text":" to learn more about this. This is a subscriber only option."}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"excludedSourceId"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"excludedSourceId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/excludedSourceId"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/stereo":{"url":"\/documentation\/millicastsdk\/mcclientoptions\/stereo","abstract":[{"text":"A boolean indicating whether the SDK should enable stereo audio. True enables stereo, false disables it. This is only available for publishing.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"stereo","navigatorTitle":[{"text":"stereo","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/stereo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stereo"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/pinnedSourceId":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/pinnedSourceId","abstract":[{"type":"text","text":"The receiving source to pin. Refer to "},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","type":"reference","isActive":true},{"text":" to learn more about this. This is a subscriber only option.","type":"text"}],"type":"topic","title":"pinnedSourceId","url":"\/documentation\/millicastsdk\/mcclientoptions\/pinnedsourceid","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pinnedSourceId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pinnedSourceId"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/upwardsLayerWaitTimeMs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/upwardsLayerWaitTimeMs","abstract":[{"type":"text","text":"Duration the Transponder will wait before switching back to a higher layer in msec. Expects an unsigned integer value."}],"type":"topic","title":"upwardsLayerWaitTimeMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/upwardslayerwaittimems","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"upwardsLayerWaitTimeMs","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"upwardsLayerWaitTimeMs","kind":"identifier"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"https://www.w3.org/TR/mst-content-hint/#degradation-preference-when-encoding":{"title":"the WebRTC standard","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"type":"link","identifier":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding","url":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/sourceId":{"type":"topic","title":"sourceId","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcclientoptions\/sourceid","navigatorTitle":[{"text":"sourceId","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/sourceId","abstract":[{"type":"text","text":"The ID of the source to publish. This option is related to the multisource feature of the millicast service. For more information refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting"},{"type":"text","text":". This is a publisher only option."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/disableAudio":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/disableAudio","abstract":[{"text":"Determines whether audio playback should be completely disabled. Disabling unnecessary audio helps reduce audio-to-video synchronization delays. This is only available on the subscriber.","type":"text"}],"type":"topic","title":"disableAudio","url":"\/documentation\/millicastsdk\/mcclientoptions\/disableaudio","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disableAudio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"disableAudio","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/audioCodec":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/audioCodec","abstract":[{"type":"text","text":"The audio codec to use for publishing. This is only available for the publisher."}],"type":"topic","title":"audioCodec","url":"\/documentation\/millicastsdk\/mcclientoptions\/audiocodec","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"audioCodec","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"audioCodec"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"kind":"symbol","type":"topic","title":"MCClientOptions","url":"\/documentation\/millicastsdk\/mcclientoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/bweMonitorDurationUs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweMonitorDurationUs","abstract":[{"type":"text","text":"Overrides the duration of time over which bandwidth-estimate-calculations occur in usec. By default this is 150msec, increasing this may smooth out transitions a little at the cost of NOT reacting to changes in the network as fast."},{"text":" ","type":"text"},{"type":"text","text":"Expects an unsigned integer value."}],"type":"topic","title":"bweMonitorDurationUs","url":"\/documentation\/millicastsdk\/mcclientoptions\/bwemonitordurationus","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bweMonitorDurationUs","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bweMonitorDurationUs"}]},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"title":"WebRTC standard","titleInlineContent":[{"text":"WebRTC standard","type":"text"}],"type":"link","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/bweRateChangePercentage":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweRateChangePercentage","abstract":[{"text":"What percentage of the estimated larger bitrate will we increase by when we think the network is good. So if the previous estimate was 1mbps and the new estimate is 10mbps, and bweRateChangePercentage is 0.05, then 0.05*10mbps = 0.5mbps, so the new target at the end of the tick will be 1 + 0.5 = 1.5mbps. This value can be reduced to increase more slowly under good conditions. Expects a double value.","type":"text"}],"type":"topic","title":"bweRateChangePercentage","url":"\/documentation\/millicastsdk\/mcclientoptions\/bweratechangepercentage","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bweRateChangePercentage"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bweRateChangePercentage"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/statsDelayMs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/statsDelayMs","abstract":[{"type":"text","text":"The rate at which you want to receive reports with statistics in milliseconds. Defaults to 1 second."}],"type":"topic","title":"statsDelayMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/statsdelayms","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"statsDelayMs","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"statsDelayMs"}]},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/svcMode":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/svcMode","abstract":[{"type":"text","text":"Enables Scalable Video Coding selection. Refer to the "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true},{"type":"text","text":" to learn which modes are supported by which codecs. This is only available when publishing."}],"type":"topic","title":"svcMode","url":"\/documentation\/millicastsdk\/mcclientoptions\/svcmode","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"svcMode"},{"kind":"text","text":": "},{"text":"MCScalabilityMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCScalabilityMode"}],"navigatorTitle":[{"text":"svcMode","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/bitrateSettings":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bitrateSettings","abstract":[{"text":"Adjust the bitrate settings. This is only available for publishing.","type":"text"}],"type":"topic","title":"bitrateSettings","url":"\/documentation\/millicastsdk\/mcclientoptions\/bitratesettings","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateSettings"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCBitrateSettings","text":"MCBitrateSettings","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bitrateSettings"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/maximumBitrate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/maximumBitrate","abstract":[{"type":"text","text":"Set the maximum bitrate in KBps that can be used by the viewer."}],"type":"topic","title":"maximumBitrate","url":"\/documentation\/millicastsdk\/mcclientoptions\/maximumbitrate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumBitrate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"maximumBitrate","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/recordStream":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/recordStream","abstract":[{"text":"Indicates whether the SDK should enable stream recording immediately after publishing. Make sure the recording feature is enabled for the publisher token. Recordings can then be viewed on the dashboard.","type":"text"}],"type":"topic","title":"recordStream","url":"\/documentation\/millicastsdk\/mcclientoptions\/recordstream","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordStream"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"recordStream"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/degradationPreferences":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/degradationPreferences","abstract":[{"type":"text","text":"The strategy the use in order to limit the bandwidth usage. Refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding"}],"type":"topic","title":"degradationPreferences","url":"\/documentation\/millicastsdk\/mcclientoptions\/degradationpreferences","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreferences"},{"text":": ","kind":"text"},{"text":"MCDegradationPreferences","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCDegradationPreferences"}],"navigatorTitle":[{"kind":"identifier","text":"degradationPreferences"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/simulcast":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/simulcast","abstract":[{"type":"text","text":"Determines whether Simulcast should be enabled (true) or not (false). This is only available for VP8 and H264 codecs, and is "},{"code":"false","type":"codeVoice"},{"text":" by default. This is only available for publishing. Enabling this will send out 3 simulcast streams (low, medium and high).","type":"text"}],"type":"topic","title":"simulcast","url":"\/documentation\/millicastsdk\/mcclientoptions\/simulcast","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"simulcast","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"simulcast","kind":"identifier"}]},"https://docs.dolby.io/streaming-apis/docs/multiview":{"title":" The Multiview Guide","titleInlineContent":[{"type":"text","text":" The Multiview Guide"}],"type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/forceSmooth":{"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions\/forcesmooth","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forceSmooth","kind":"symbol","abstract":[{"text":"Forces video to be sent on downlink when switching from higher quality layers","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"forceSmooth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"forceSmooth","kind":"identifier"}],"title":"forceSmooth"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"https://docs.dolby.io/streaming-apis/docs/multi-source-broadcasting":{"title":"The Multisource Broadcasting Guide","titleInlineContent":[{"type":"text","text":"The Multisource Broadcasting Guide"}],"type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multi-source-broadcasting"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/forcePlayoutDelay":{"role":"symbol","abstract":[{"type":"text","text":"Sets the minimum\/maximum playout delays for the incoming streams."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forcePlayoutDelay","title":"forcePlayoutDelay","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions\/forceplayoutdelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forcePlayoutDelay"},{"kind":"text","text":": "},{"text":"MCForcePlayoutDelay","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCForcePlayoutDelay"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"forcePlayoutDelay"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/rtcEventLogOutputPath":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/rtcEventLogOutputPath","abstract":[{"type":"text","text":"Enables logging RTC event log into a custom file path."}],"type":"topic","title":"rtcEventLogOutputPath","url":"\/documentation\/millicastsdk\/mcclientoptions\/rtceventlogoutputpath","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rtcEventLogOutputPath","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"rtcEventLogOutputPath","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/videoCodec":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/videoCodec","abstract":[{"text":"The video codec to use for publishing. This is only available for the publisher.","type":"text"}],"type":"topic","title":"videoCodec","url":"\/documentation\/millicastsdk\/mcclientoptions\/videocodec","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoCodec"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"videoCodec","kind":"identifier"}]},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCClientOptions","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MCClientOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/audioCodec","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bitrateSettings","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweMonitorDurationUs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/bweRateChangePercentage","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/degradationPreferences","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/disableAudio","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/dtx","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/excludedSourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forcePlayoutDelay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/forceSmooth","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/jitterMinimumDelayMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/maximumBitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/multiplexedAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/pinnedSourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/priority","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/recordStream","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/rtcEventLogOutputPath","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/simulcast","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/sourceId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/statsDelayMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/stereo","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/svcMode","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/upwardsLayerWaitTimeMs","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/videoCodec"],"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1jitterMinimumDelayMs\/title","value":"jitterMinimumDelayMs","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1jitterMinimumDelayMs\/fragments","value":[{"kind":"identifier","text":"jitterMinimumDelayMs"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1multiplexedAudioTrack\/title","op":"replace","value":"multiplexedAudioTrack"},{"op":"replace","value":[{"kind":"identifier","text":"multiplexedAudioTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1multiplexedAudioTrack\/fragments"},{"value":"priority","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1priority\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1priority\/fragments","value":[{"text":"priority","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1dtx\/title","value":"dtx"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1dtx\/fragments","value":[{"kind":"identifier","text":"dtx"}]},{"op":"replace","value":"excludedSourceId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1excludedSourceId\/title"},{"value":[{"kind":"identifier","text":"excludedSourceId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1excludedSourceId\/fragments","op":"replace"},{"op":"replace","value":"stereo","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1stereo\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1stereo\/fragments","value":[{"kind":"identifier","text":"stereo"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1pinnedSourceId\/title","value":"pinnedSourceId"},{"op":"replace","value":[{"kind":"identifier","text":"pinnedSourceId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1pinnedSourceId\/fragments"},{"value":"upwardsLayerWaitTimeMs","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1upwardsLayerWaitTimeMs\/title"},{"value":[{"kind":"identifier","text":"upwardsLayerWaitTimeMs"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1upwardsLayerWaitTimeMs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1sourceId\/title","value":"sourceId"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1sourceId\/fragments","value":[{"text":"sourceId","kind":"identifier"}],"op":"replace"},{"value":"disableAudio","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1disableAudio\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1disableAudio\/fragments","value":[{"kind":"identifier","text":"disableAudio"}]},{"op":"replace","value":"audioCodec","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1audioCodec\/title"},{"value":[{"kind":"identifier","text":"audioCodec"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1audioCodec\/fragments"},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCClientOptions"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweMonitorDurationUs\/title","value":"bweMonitorDurationUs","op":"replace"},{"value":[{"kind":"identifier","text":"bweMonitorDurationUs"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweMonitorDurationUs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweRateChangePercentage\/title","value":"bweRateChangePercentage"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bweRateChangePercentage\/fragments","value":[{"kind":"identifier","text":"bweRateChangePercentage"}]},{"op":"replace","value":"statsDelayMs","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1statsDelayMs\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1statsDelayMs\/fragments","value":[{"kind":"identifier","text":"statsDelayMs"}]},{"value":"svcMode","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1svcMode\/title"},{"value":[{"text":"svcMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1svcMode\/fragments"},{"op":"replace","value":"bitrateSettings","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bitrateSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1bitrateSettings\/fragments","value":[{"kind":"identifier","text":"bitrateSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1maximumBitrate\/title","value":"maximumBitrate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1maximumBitrate\/fragments","op":"replace","value":[{"text":"maximumBitrate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1recordStream\/title","op":"replace","value":"recordStream"},{"op":"replace","value":[{"text":"recordStream","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1recordStream\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1degradationPreferences\/title","op":"replace","value":"degradationPreferences"},{"value":[{"kind":"identifier","text":"degradationPreferences"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1degradationPreferences\/fragments"},{"value":"simulcast","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1simulcast\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1simulcast\/fragments","value":[{"text":"simulcast","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forceSmooth\/title","op":"replace","value":"forceSmooth"},{"value":[{"kind":"identifier","text":"forceSmooth"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forceSmooth\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forcePlayoutDelay\/title","op":"replace","value":"forcePlayoutDelay"},{"value":[{"kind":"identifier","text":"forcePlayoutDelay"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1forcePlayoutDelay\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1rtcEventLogOutputPath\/title","value":"rtcEventLogOutputPath","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1rtcEventLogOutputPath\/fragments","op":"replace","value":[{"kind":"identifier","text":"rtcEventLogOutputPath"}]},{"value":"videoCodec","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1videoCodec\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1videoCodec\/fragments","value":[{"kind":"identifier","text":"videoCodec"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}