{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCIceCandidatePairStats","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Class","title":"MCIceCandidatePairStats","navigatorTitle":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCIceCandidatePairStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCIceCandidatePairStats"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"class"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_incoming_bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_outgoing_bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/current_round_trip_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/total_round_trip_time"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/get_type()"],"title":"Type Methods"}],"references":{"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"role":"symbol","title":"MCStats","abstract":[{"text":"A container of various different stats. To make sense of such statistics, please refer to the ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","isActive":true,"type":"reference"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStats"}],"url":"\/documentation\/millicastsdk\/mcstats"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/available_outgoing_bitrate":{"type":"topic","title":"available_outgoing_bitrate","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_outgoing_bitrate","navigatorTitle":[{"kind":"identifier","text":"available_outgoing_bitrate"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_outgoing_bitrate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"available_outgoing_bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"It is calculated by the underlying congestion control by combining the available bitrate for all the outgoing RTP streams using this candidate pair. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate","type":"reference"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/get_type()":{"type":"topic","title":"get_type()","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/get_type()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"}],"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/total_round_trip_time":{"type":"topic","title":"total_round_trip_time","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/total_round_trip_time","navigatorTitle":[{"kind":"identifier","text":"total_round_trip_time"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/total_round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Represents the sum of all round trip time measurements in seconds since the beginning of the session. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime","isActive":true}],"kind":"symbol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-availableincomingbitrate":{"titleInlineContent":[{"type":"text","text":"availableincomingbitrate"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate","type":"link","title":"availableincomingbitrate","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/current_round_trip_time":{"type":"topic","title":"current_round_trip_time","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/current_round_trip_time","navigatorTitle":[{"kind":"identifier","text":"current_round_trip_time"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/current_round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"current_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"type":"text","text":"Represents the latest round trip time measured in seconds. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","type":"reference"}],"kind":"symbol"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#introduction":{"titleInlineContent":[{"text":"WebRTC standard","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","type":"link","title":"WebRTC standard","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-currentroundtriptime":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","title":"currentroundtriptime","titleInlineContent":[{"type":"text","text":"currentroundtriptime"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-currentroundtriptime","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-availableoutgoingbitrate":{"titleInlineContent":[{"text":"availableoutgoingbitrate","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate","type":"link","title":"availableoutgoingbitrate","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableoutgoingbitrate"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats":{"navigatorTitle":[{"kind":"identifier","text":"MCIceCandidatePairStats"}],"role":"symbol","title":"MCIceCandidatePairStats","abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCIceCandidatePairStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcicecandidatepairstats"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-totalroundtriptime":{"titleInlineContent":[{"type":"text","text":"totalroundtriptime"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime","type":"link","title":"totalroundtriptime","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-totalroundtriptime"},"doc://MillicastSDK/documentation/MillicastSDK/MCIceCandidatePairStats/available_incoming_bitrate":{"type":"topic","title":"available_incoming_bitrate","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_incoming_bitrate","navigatorTitle":[{"kind":"identifier","text":"available_incoming_bitrate"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_incoming_bitrate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"available_incoming_bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"It is calculated by the underlying congestion control by combining the available bitrate for all the incoming RTP streams using this candidate pair. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate","type":"reference"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MCIceCandidatePairStats","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MCIceCandidatePairStats"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_incoming_bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_outgoing_bitrate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/current_round_trip_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/total_round_trip_time"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/get_type()"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCIceCandidatePairStats","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCStats","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","text":"MCStats"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MCStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title"},{"value":[{"text":"MCStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_outgoing_bitrate\/title","value":"available_outgoing_bitrate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"available_outgoing_bitrate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_outgoing_bitrate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1get_type()\/title","op":"replace","value":"get_type"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1total_round_trip_time\/title","op":"replace","value":"total_round_trip_time"},{"value":[{"text":"total_round_trip_time","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1total_round_trip_time\/fragments","op":"replace"},{"value":"current_round_trip_time","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1current_round_trip_time\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1current_round_trip_time\/fragments","value":[{"kind":"identifier","text":"current_round_trip_time"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title","value":"MCIceCandidatePairStats","op":"replace"},{"value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_incoming_bitrate\/title","value":"available_incoming_bitrate","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_incoming_bitrate\/fragments","op":"replace","value":[{"text":"available_incoming_bitrate","kind":"identifier"}]}]}]}