{"kind":"symbol","abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"text":" for playback.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoFrame"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/frameType()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI420Buffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI444Buffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getRgbBuffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/height()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI444()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/width()"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoframe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe"]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"metadata":{"externalID":"c:objc(pl)MCVideoFrame","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCVideoFrame","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MCVideoFrame","kind":"identifier"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/sizeRgb()":{"navigatorTitle":[{"kind":"identifier","text":"sizeRgb"}],"type":"topic","required":true,"abstract":[{"text":"If the frame was an RGB frame, then this will return size of the frame in bytes.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizergb()","title":"sizeRgb()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeRgb"},{"kind":"text","text":"() -> "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"title":"MCVideoFrame","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe","abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoFrame","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"title":"MCVideoRenderer","type":"topic","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"text":" ","type":"text"},{"type":"text","text":"applications. Used in "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true,"type":"reference"},{"type":"text","text":" to start receiving"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoRenderer"}],"navigatorTitle":[{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/width()":{"navigatorTitle":[{"kind":"identifier","text":"width"}],"type":"topic","required":true,"abstract":[{"text":"The width of the video frame.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/width()","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe\/width()","title":"width()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"text":"() -> ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/height()":{"role":"symbol","kind":"symbol","title":"height()","navigatorTitle":[{"kind":"identifier","text":"height"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":"() -> "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"url":"\/documentation\/millicastsdk\/mcvideoframe\/height()","abstract":[{"text":"The height of the video frame.","type":"text"}],"required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/height()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/sizeI444()":{"type":"topic","title":"sizeI444()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeI444","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"sizeI444"}],"role":"symbol","abstract":[{"type":"text","text":"If the frame was an I444 frame, then this will return size of the frame in bytes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI444()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizei444()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/sizeI420()":{"role":"symbol","kind":"symbol","title":"sizeI420()","navigatorTitle":[{"text":"sizeI420","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sizeI420","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"url":"\/documentation\/millicastsdk\/mcvideoframe\/sizei420()","abstract":[{"type":"text","text":"If the frame was an I420 frame, then this will return size of the frame in bytes."}],"required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/frameType()":{"role":"symbol","kind":"symbol","title":"frameType()","navigatorTitle":[{"kind":"identifier","text":"frameType"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameType"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@MCVideoType","text":"MCVideoType","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcvideoframe\/frametype()","abstract":[{"type":"text","text":"The pixel format. For example, can be an I420 or a I444 frame."}],"required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/frameType()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/getI420Buffer(_:)":{"required":true,"type":"topic","title":"getI420Buffer(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI420Buffer(_:)","url":"\/documentation\/millicastsdk\/mcvideoframe\/geti420buffer(_:)","abstract":[{"type":"text","text":"Get the video frame buffer as an I420 frame. Performs the necessary conversion."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getI420Buffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!)"}],"navigatorTitle":[{"text":"getI420Buffer:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/getRgbBuffer(_:)":{"required":true,"type":"topic","title":"getRgbBuffer(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getRgbBuffer(_:)","url":"\/documentation\/millicastsdk\/mcvideoframe\/getrgbbuffer(_:)","abstract":[{"text":"Get the video frame buffer as an RGB frame. Performs the necessary conversion.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getRgbBuffer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!)"}],"navigatorTitle":[{"text":"getRgbBuffer:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/getI444Buffer(_:)":{"required":true,"type":"topic","title":"getI444Buffer(_:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI444Buffer(_:)","url":"\/documentation\/millicastsdk\/mcvideoframe\/geti444buffer(_:)","abstract":[{"type":"text","text":"Get the video frame buffer as an I444 frame. Performs the necessary conversion."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getI444Buffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!)"}],"navigatorTitle":[{"text":"getI444Buffer:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","title":"add(_:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","kind":"symbol","navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","text":"MCVideoRenderer"},{"kind":"text","text":")!)"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCVideoFrame"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/frameType()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI420Buffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getI444Buffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/getRgbBuffer(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/height()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI444()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/width()"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"MCVideoFrame","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/title","value":"sizeRgb","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeRgb"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","op":"replace"},{"op":"replace","value":"MCVideoRenderer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","value":"width","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1width()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1width()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1height()\/title","value":"height"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"height"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1height()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI444()\/title","value":"sizeI444"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI444()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeI444"}],"op":"replace"},{"value":"sizeI420","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sizeI420"}]},{"value":"frameType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1frameType()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1frameType()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"frameType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getI420Buffer(_:)\/title","value":"getI420Buffer:"},{"value":[{"kind":"text","text":"- "},{"text":"getI420Buffer:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getI420Buffer(_:)\/fragments"},{"value":"getRgbBuffer:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getRgbBuffer(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getRgbBuffer(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getRgbBuffer:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getI444Buffer(_:)\/title","value":"getI444Buffer:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getI444Buffer:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1getI444Buffer(_:)\/fragments","op":"replace"},{"op":"replace","value":"addRenderer:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addRenderer:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}