{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DECODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType","preciseIdentifier":"c:@E@MCCodecStatsType","text":"MCCodecStatsType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/decode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/decode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/DECODE","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DECODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCCodecStatsType","preciseIdentifier":"c:@E@MCCodecStatsType"}],"title":"DECODE","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@E@MCCodecStatsType@DECODE","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"DECODE"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecStatsType":{"role":"symbol","title":"MCCodecStatsType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecStatsType"}],"abstract":[{"type":"text","text":"Different types of codec statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsType"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype"},"doc://MillicastSDK/documentation/MillicastSDK/DECODE":{"role":"symbol","title":"DECODE","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"DECODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCCodecStatsType","preciseIdentifier":"c:@E@MCCodecStatsType"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/DECODE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DECODE"}],"url":"\/documentation\/millicastsdk\/decode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DECODE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DECODE"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DECODE"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/title","value":"MCCodecStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1DECODE\/title","value":"DECODE"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1DECODE\/fragments","value":[{"kind":"identifier","text":"DECODE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}