{"kind":"symbol","abstract":[{"type":"text","text":"The type of statistics."}],"metadata":{"title":"get_type()","role":"symbol","externalID":"c:objc(cs)MCReceivedRtpStreamStats(cm)get_type","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","text":"MCStatsType"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/get_type()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/get_type()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/get_type()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","type":"topic","title":"MCReceivedRtpStreamStats","abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/get_type()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/get_type()","role":"symbol","type":"topic","title":"get_type()","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of statistics."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/get_type()"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Different types of statistics."}],"url":"\/documentation\/millicastsdk\/mcstatstype","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","title":"MCStatsType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"get_type"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"get_type","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"MCReceivedRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}]},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1get_type()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}]},{"value":"MCStatsType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}]}]}]}