{"abstract":[{"type":"text","text":"The number of RTP packets lost during transmission or due to network issues. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_lost"]},{"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_lost"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_lost"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_lost"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"]]},"metadata":{"title":"packets_lost","externalID":"c:objc(cs)MCReceivedRtpStreamStats(py)packets_lost","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"packets_lost"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"navigatorTitle":[{"text":"packets_lost","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","type":"topic","title":"MCReceivedRtpStreamStats","abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats/packets_lost":{"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_lost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_lost"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"packets_lost","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_lost","abstract":[{"type":"text","text":"The number of RTP packets lost during transmission or due to network issues. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost","isActive":true,"type":"reference"}],"kind":"symbol","title":"packets_lost"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetslost":{"titleInlineContent":[{"type":"text","text":"packetsLost"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost","title":"packetsLost","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetslost"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"packets_lost","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"packets_lost"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"text":"long long","kind":"typeIdentifier","preciseIdentifier":"c:K"},{"text":" ","kind":"text"},{"kind":"identifier","text":"packets_lost"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"MCReceivedRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","value":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"op":"replace"},{"value":"packets_lost","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_lost\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_lost\/fragments","value":[{"kind":"identifier","text":"packets_lost"}],"op":"replace"}]}]}