{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Attach this class to an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"},{"type":"text","text":", "},{"type":"codeVoice","code":"MCAcceleratedVideoNSView"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView"},{"type":"text","text":" to render onto a View."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This class being an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},{"type":"text","text":" can be attached"},{"type":"text","text":" "},{"type":"text","text":"to a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"},{"type":"text","text":" "},{"type":"text","text":"to receive video frames."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"title":"MCAcceleratedVideoRenderer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCAcceleratedVideoRenderer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init(colorRangeExpansion:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/videoSize"]}],"references":{"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/videoSize":{"role":"symbol","title":"videoSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of the last video frame received."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/videoSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoSize"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/videosize"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAcceleratedVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCAcceleratedVideoRendererDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/delegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"role":"symbol","title":"MCRTSRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initializes the accelerated video renderer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/init()"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","title":"MCVideoRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"role":"symbol","title":"MCAcceleratedVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"role":"symbol","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/init(colorRangeExpansion:)":{"role":"symbol","title":"init(colorRangeExpansion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes with the option of expanding limited color range to the full range upon rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init(colorRangeExpansion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithColorRangeExpansion:"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/init(colorrangeexpansion:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSwiftUIView":{"role":"symbol","title":"MCVideoSwiftUIView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSwiftUIView"}],"abstract":[{"type":"text","text":"Swift UI View that can use either Metal or a sample buffer to render a track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSwiftUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoSwiftUIView"}],"url":"\/documentation\/millicastsdk\/mcvideoswiftuiview"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"role":"symbol","title":"MCWebrtcRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"role":"symbol","title":"MCVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoTrack"}],"abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcvideotrack"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/videoSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init(colorRangeExpansion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1videoSize\/title","value":"videoSize"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1videoSize\/fragments","value":[{"kind":"identifier","text":"videoSize"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","value":"MCAcceleratedVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init(colorRangeExpansion:)\/title","value":"initWithColorRangeExpansion:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init(colorRangeExpansion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithColorRangeExpansion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","value":"MCWebrtcRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title","value":"MCVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCVideoTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}