{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamViewDetails"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstreamviewdetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstreamviewdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamViewId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/subscriberId"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamViewDetails"}],"title":"MCStreamViewDetails","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCStreamViewDetails","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCStreamViewDetails"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails/streamViewId":{"role":"symbol","title":"streamViewId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamViewId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamViewId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamViewId"}],"url":"\/documentation\/millicastsdk\/mcstreamviewdetails\/streamviewid"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails/streamId":{"role":"symbol","title":"streamId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"streamId"}],"url":"\/documentation\/millicastsdk\/mcstreamviewdetails\/streamid"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails":{"role":"symbol","title":"MCStreamViewDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamViewDetails"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStreamViewDetails"}],"url":"\/documentation\/millicastsdk\/mcstreamviewdetails"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails/subscriberId":{"role":"symbol","title":"subscriberId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriberId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/subscriberId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subscriberId"}],"url":"\/documentation\/millicastsdk\/mcstreamviewdetails\/subscriberid"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails/clusterId":{"role":"symbol","title":"clusterId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clusterId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/clusterId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clusterId"}],"url":"\/documentation\/millicastsdk\/mcstreamviewdetails\/clusterid"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCStreamViewDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCStreamViewDetails"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCStreamViewDetails"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/clusterId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/streamViewId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails\/subscriberId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamViewDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1streamViewId\/title","value":"streamViewId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1streamViewId\/fragments","value":[{"kind":"identifier","text":"streamViewId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1streamId\/title","value":"streamId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1streamId\/fragments","value":[{"kind":"identifier","text":"streamId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails\/title","value":"MCStreamViewDetails"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails\/fragments","value":[{"kind":"identifier","text":"MCStreamViewDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1subscriberId\/title","value":"subscriberId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1subscriberId\/fragments","value":[{"kind":"identifier","text":"subscriberId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1clusterId\/title","value":"clusterId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails~1clusterId\/fragments","value":[{"kind":"identifier","text":"clusterId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}