{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mctrackstatstype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrackstatstype"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCTrackStatsType","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/audio","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/video"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"MCTrackStatsType","symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCTrackStatsType","kind":"identifier"}],"navigatorTitle":[{"text":"MCTrackStatsType","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MCTrackStatsType"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/audio":{"title":"MCTrackStatsType.audio","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/audio","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"}],"url":"\/documentation\/millicastsdk\/mctrackstatstype\/audio","navigatorTitle":[{"text":"MCTrackStatsTypeAudio","kind":"identifier"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/Equatable-Implementations":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/millicastsdk\/mctrackstatstype\/equatable-implementations"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/video":{"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/video","navigatorTitle":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mctrackstatstype\/video","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"title":"MCTrackStatsType.video","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType","abstract":[],"title":"MCTrackStatsType","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstatstype","navigatorTitle":[{"text":"MCTrackStatsType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCTrackStatsType","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/RawRepresentable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/millicastsdk\/mctrackstatstype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/RawRepresentable-Implementations"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStatsType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mctrackstatstype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic"},"doc://MillicastSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SY","title":"Swift.RawRepresentable"},"doc://MillicastSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"MCTrackStatsType","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCTrackStatsType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCTrackStatsType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/audio","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStatsType\/video"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCTrackStatsType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"MCTrackStatsTypeAudio","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1audio\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1audio\/fragments","value":[{"text":"MCTrackStatsTypeAudio","kind":"identifier"}]},{"value":"MCTrackStatsTypeVideo","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1video\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType~1video\/fragments","value":[{"text":"MCTrackStatsTypeVideo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType\/title","value":"MCTrackStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStatsType\/fragments","value":[{"text":"MCTrackStatsType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}