{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":" "},{"kind":"internalParam","text":"projectionData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData","preciseIdentifier":"c:objc(cs)MCProjectionData","text":"MCProjectionData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"sourceId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source id you want to receive"}]}]},{"name":"projectionData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration of the track you want to receive."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handler invoked when the result is ready."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/project(_:withdata:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/project(_:withdata:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/project(_:withData:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specify the source you want to receive."},{"type":"text","text":" "},{"type":"text","text":"With the project method you can select and switch sources from the Millicast server"},{"type":"text","text":" "},{"type":"text","text":"and then forward the selected media to the subscriber, for each audio and video track."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCProjectionData","preciseIdentifier":"c:objc(cs)MCProjectionData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"project(_:withData:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCSubscriber(im)project:withData:completionHandler:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"project:withData:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/project(_:withData:completionHandler:)":{"role":"symbol","title":"project(_:withData:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCProjectionData","preciseIdentifier":"c:objc(cs)MCProjectionData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Specify the source you want to receive."},{"type":"text","text":" "},{"type":"text","text":"With the project method you can select and switch sources from the Millicast server"},{"type":"text","text":" "},{"type":"text","text":"and then forward the selected media to the subscriber, for each audio and video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/project(_:withData:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"project:withData:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/project(_:withdata:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData":{"role":"symbol","title":"MCProjectionData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"}],"abstract":[{"type":"text","text":"The projection data is used to project a video\/audio track into a specific transceiver."},{"type":"text","text":" "},{"type":"text","text":"We send a command to the media server using the project method to choose which track to"},{"type":"text","text":" "},{"type":"text","text":"project"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCProjectionData"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"role":"symbol","title":"MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"url":"\/documentation\/millicastsdk\/mcsubscriber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"project:withData:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"project:withData:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"project:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":" "},{"kind":"identifier","text":"withData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<MCProjectionData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"projectionData"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1project(_:withData:completionHandler:)\/title","value":"project:withData:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1project(_:withData:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"project:withData:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/title","value":"MCProjectionData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/fragments","value":[{"kind":"identifier","text":"MCProjectionData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}