{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)MCClientOptions(py)degradationPreferences","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"degradationPreferences","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreferences"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCDegradationPreferences","text":"MCDegradationPreferences"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"degradationPreferences"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/degradationpreferences"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/degradationpreferences"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"degradationPreferences"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCDegradationPreferences","preciseIdentifier":"c:@E@MCDegradationPreferences","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/degradationPreferences"},"abstract":[{"text":"The strategy the use in order to limit the bandwidth usage. Refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding","isActive":true,"type":"reference"}],"sections":[],"references":{"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"type":"link","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","title":"the WebRTC standard","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcclientoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","title":"MCClientOptions"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/degradationPreferences":{"kind":"symbol","abstract":[{"text":"The strategy the use in order to limit the bandwidth usage. Refer to ","type":"text"},{"isActive":true,"identifier":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding","type":"reference"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/degradationPreferences","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"degradationPreferences","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCDegradationPreferences","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCDegradationPreferences"}],"navigatorTitle":[{"text":"degradationPreferences","kind":"identifier"}],"title":"degradationPreferences","url":"\/documentation\/millicastsdk\/mcclientoptions\/degradationpreferences","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDegradationPreferences":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences","title":"MCDegradationPreferences","abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","type":"reference"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDegradationPreferences"}],"role":"symbol"},"https://www.w3.org/TR/mst-content-hint/#degradation-preference-when-encoding":{"type":"link","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"identifier":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/mst-content-hint\/#degradation-preference-when-encoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"degradationPreferences"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"degradationPreferences"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MCDegradationPreferences","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCDegradationPreferences","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences"},{"text":" ","kind":"text"},{"text":"degradationPreferences","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1degradationPreferences\/title","value":"degradationPreferences"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1degradationPreferences\/fragments","value":[{"text":"degradationPreferences","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","value":"MCDegradationPreferences"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","value":[{"text":"MCDegradationPreferences","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}