{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Sets the minimum\/maximum playout delays for the incoming streams.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forcePlayoutDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCForcePlayoutDelay","text":"MCForcePlayoutDelay","preciseIdentifier":"c:objc(cs)MCForcePlayoutDelay"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/forceplayoutdelay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/forceplayoutdelay"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/forcePlayoutDelay","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)MCClientOptions(py)forcePlayoutDelay","navigatorTitle":[{"text":"forcePlayoutDelay","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forcePlayoutDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCForcePlayoutDelay","text":"MCForcePlayoutDelay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"forcePlayoutDelay","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"MillicastSDK"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCForcePlayoutDelay":{"navigatorTitle":[{"kind":"identifier","text":"MCForcePlayoutDelay"}],"abstract":[{"text":"An option to tell the media server to","type":"text"},{"text":" ","type":"text"},{"text":"send hints about the range of","type":"text"},{"text":" ","type":"text"},{"text":"playout delays that the RTP receiver should","type":"text"},{"text":" ","type":"text"},{"text":"follow, which effectively sets the delay","type":"text"},{"text":" ","type":"text"},{"text":"for each frame before it is rendered.","type":"text"},{"text":" ","type":"text"},{"text":"Use this if you want to compensate","type":"text"},{"text":" ","type":"text"},{"text":"for unpredictable network behaviour","type":"text"},{"text":" ","type":"text"},{"text":"allowing for smooth playback at the cost","type":"text"},{"text":" ","type":"text"},{"text":"of increasing latency.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay","role":"symbol","type":"topic","title":"MCForcePlayoutDelay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCForcePlayoutDelay"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcclientoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","title":"MCClientOptions"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/forcePlayoutDelay":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/forcePlayoutDelay","abstract":[{"type":"text","text":"Sets the minimum\/maximum playout delays for the incoming streams."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forcePlayoutDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCForcePlayoutDelay","text":"MCForcePlayoutDelay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/forceplayoutdelay","navigatorTitle":[{"text":"forcePlayoutDelay","kind":"identifier"}],"title":"forcePlayoutDelay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"forcePlayoutDelay","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"forcePlayoutDelay","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCForcePlayoutDelay","preciseIdentifier":"c:objc(cs)MCForcePlayoutDelay","text":"MCForcePlayoutDelay"},{"kind":"text","text":" * "},{"kind":"identifier","text":"forcePlayoutDelay"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCForcePlayoutDelay","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/title"},{"value":[{"kind":"identifier","text":"MCForcePlayoutDelay"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/fragments"},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"value":[{"kind":"identifier","text":"MCClientOptions"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments"},{"value":"forcePlayoutDelay","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1forcePlayoutDelay\/title"},{"value":[{"text":"forcePlayoutDelay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1forcePlayoutDelay\/fragments"}]}]}