{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"jitterMinimumDelayMs","kind":"identifier"}],"title":"jitterMinimumDelayMs","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jitterMinimumDelayMs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCClientOptions(py)jitterMinimumDelayMs"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterMinimumDelayMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/jitterMinimumDelayMs"},"kind":"symbol","sections":[],"abstract":[{"text":"The minimum jitter delay that packets of incoming audio\/video streams will experience before being played out. This can be tuned to help with networks with higher latency, but be careful using it as it will introduce this delay. For more information, refer to ","type":"text"},{"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","isActive":true,"type":"reference"},{"text":" to understand more about what this field does. This is only for subscribing.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/jitterminimumdelayms"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/jitterminimumdelayms"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions/jitterMinimumDelayMs":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jitterMinimumDelayMs"}],"abstract":[{"text":"The minimum jitter delay that packets of incoming audio\/video streams will experience before being played out. This can be tuned to help with networks with higher latency, but be careful using it as it will introduce this delay. For more information, refer to ","type":"text"},{"isActive":true,"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","type":"reference"},{"text":" to understand more about what this field does. This is only for subscribing.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions\/jitterMinimumDelayMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/jitterminimumdelayms","kind":"symbol","title":"jitterMinimumDelayMs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterMinimumDelayMs"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClientOptions":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClientOptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcclientoptions","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"type":"topic","title":"MCClientOptions"},"https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/rtp-hdrext/playout-delay":{"url":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","type":"link","identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/refs\/heads\/main\/docs\/native-code\/rtp-hdrext\/playout-delay","title":"this document","titleInlineContent":[{"text":"this document","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"jitterMinimumDelayMs","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"jitterMinimumDelayMs"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterMinimumDelayMs"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1jitterMinimumDelayMs\/title","value":"jitterMinimumDelayMs","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions~1jitterMinimumDelayMs\/fragments","value":[{"kind":"identifier","text":"jitterMinimumDelayMs"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace"}]}]}