{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:completionHandler:)"},"abstract":[{"type":"text","text":"Enable the track with default promote and layer behavour."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The renderer to receive video frames."}]}],"name":"renderer"},{"content":[{"inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}],"type":"paragraph"}],"name":"completionHandler"}]}],"sections":[],"metadata":{"title":"enable(renderer:completionHandler:)","navigatorTitle":[{"text":"enableWithRenderer:completionHandler:","kind":"identifier"}],"externalID":"c:objc(cs)MCRTSRemoteVideoTrack(im)enableWithRenderer:completionHandler:","modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","text":"MCVideoRenderer"},{"kind":"text","text":")!)"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"role":"symbol","abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:completionHandler:)":{"title":"enable(renderer:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"enableWithRenderer:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:completionhandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable the track with default promote and layer behavour."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableWithRenderer:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"enableWithRenderer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MCVideoRenderer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer"},{"text":") ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"addRenderer:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addRenderer:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","op":"replace"},{"value":"enableWithRenderer:completionHandler:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:completionHandler:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:completionHandler:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:completionHandler:)\/fragments","op":"replace"},{"value":"MCVideoRenderer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoRenderer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","op":"replace"},{"value":"MCRTSRemoteVideoTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","op":"replace"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","op":"replace"}]}]}