{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInactive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"streamId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The stream id. Generally in the form of "},{"type":"codeVoice","code":"AccountID\/StreamName"},{"type":"text","text":"."}]}]},{"name":"sourceId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source id set by the publisher if any."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/oninactive(_:sourceid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/oninactive(_:sourceid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onInactive(_:sourceId:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a source has been unpublished within the stream"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onInactive:sourceId:"}],"role":"symbol","title":"onInactive(_:sourceId:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)MCSubscriberDelegate(im)onInactive:sourceId:","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onInactive(_:sourceId:)":{"navigatorTitle":[{"kind":"identifier","text":"onInactive:sourceId:"}],"role":"symbol","title":"onInactive(_:sourceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a source has been unpublished within the stream"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onInactive(_:sourceId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/oninactive(_:sourceid:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onInactive:sourceId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInactive:sourceId:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onInactive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"streamId"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sourceId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onInactive(_:sourceId:)\/title","value":"onInactive:sourceId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onInactive(_:sourceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInactive:sourceId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}