{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)MCVideoSourceStats(py)width","role":"symbol","title":"width","navigatorTitle":[{"text":"width","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/width"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/width"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/width"},"abstract":[{"text":"The width of the video source. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","isActive":true,"type":"reference"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/width":{"type":"topic","abstract":[{"text":"The width of the video source. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","isActive":true,"type":"reference"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"width","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/width","title":"width","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/width"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats":{"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideosourcestats","type":"topic","role":"symbol","title":"MCVideoSourceStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSourceStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoSourceStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-width":{"title":"width","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","titleInlineContent":[{"text":"width","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"width","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:l","text":"unsigned long"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"width","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1width\/title"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1width\/fragments"},{"op":"replace","value":"MCVideoSourceStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats\/title"},{"op":"replace","value":[{"text":"MCVideoSourceStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats\/fragments"}]}]}