{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","title":"setTemporalLayerId(_:)","navigatorTitle":[{"kind":"identifier","text":"setTemporalLayerId:"}],"role":"symbol","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)setTemporalLayerId:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTemporalLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/settemporallayerid(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/settemporallayerid(_:)"]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setTemporalLayerId(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTemporalLayerId"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"temporalLayerId"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Selected from the RTS remote track layer event.","type":"text"}]}],"name":"temporalLayerId"}]}],"abstract":[{"type":"text","text":"Set the temporal layer ID."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setTemporalLayerId(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setTemporalLayerId(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setTemporalLayerId:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTemporalLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/settemporallayerid(_:)","abstract":[{"text":"Set the temporal layer ID.","type":"text"}],"title":"setTemporalLayerId(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"type":"text","text":" "},{"text":"the client wants to inform the media server to select.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"title":"MCRTSRemoteVideoTrackLayer","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setTemporalLayerId:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"setTemporalLayerId:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setTemporalLayerId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"temporalLayerId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setTemporalLayerId(_:)\/title","value":"setTemporalLayerId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setTemporalLayerId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTemporalLayerId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer"},{"value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","op":"replace"}]}]}