{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDisabled"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"a new AsyncStream"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Refer to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)"},{"type":"text","text":" "},{"type":"text","text":"for more information"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabled()"]}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"s:So19MCWebrtcRemoteTrackC12MillicastSDKE13trackDisabledScSyytGyF","title":"trackDisabled()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackDisabled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":">"}],"role":"symbol","extendedModule":"MillicastSDK"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabled()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Create an AsyncStream that is invoked whenever the track gets disabled."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/trackDisabled()":{"kind":"symbol","title":"trackDisabled()","abstract":[{"text":"Create an AsyncStream that is invoked whenever the track gets disabled.","type":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabled()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDisabled"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":">","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabled()","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"type":"topic","role":"symbol","title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrackDisabled(_:)":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteTrack"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)","title":"webrtcRemoteTrackDisabled(_:)","abstract":[{"text":"The event for disabled state notification.","type":"text"}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace","value":"MCWebrtcRemoteTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/title","value":"webrtcRemoteTrackDisabled:"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/fragments","op":"replace"}]}]}