{"metadata":{"navigatorTitle":[{"text":"fraction_lost","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraction_lost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats(py)fraction_lost","title":"fraction_lost","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/fraction_lost"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/fraction_lost"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/fraction_lost","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraction_lost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The fraction of RTP packets lost during transmission or due to network issues. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","type":"reference"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"title":"MCRemoteInboundRtpStreamStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","abstract":[{"text":"Statistics about an incoming remote RTP stream.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-fractionlost":{"title":"fractionLost","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","titleInlineContent":[{"text":"fractionLost","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/fraction_lost":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraction_lost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"fraction_lost","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/fraction_lost","role":"symbol","navigatorTitle":[{"text":"fraction_lost","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/fraction_lost","abstract":[{"text":"The fraction of RTP packets lost during transmission or due to network issues. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","type":"reference"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"fraction_lost","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"fraction_lost","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"fraction_lost"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","value":"MCRemoteInboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1fraction_lost\/title","op":"replace","value":"fraction_lost"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1fraction_lost\/fragments","op":"replace","value":[{"text":"fraction_lost","kind":"identifier"}]}]}]}