{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"round_trip_time"}],"symbolKind":"property","title":"round_trip_time","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats(py)round_trip_time"},"abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","isActive":true}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/round_trip_time":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time","abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","type":"reference","isActive":true}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time","navigatorTitle":[{"text":"round_trip_time","kind":"identifier"}],"role":"symbol","title":"round_trip_time","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"title":"MCRemoteInboundRtpStreamStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","abstract":[{"text":"Statistics about an incoming remote RTP stream.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime":{"type":"link","titleInlineContent":[{"type":"text","text":"roundTripTime"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","title":"roundTripTime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"round_trip_time"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"round_trip_time","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"round_trip_time","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time\/title","value":"round_trip_time"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time\/fragments","value":[{"text":"round_trip_time","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","op":"replace","value":"MCRemoteInboundRtpStreamStats"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments","op":"replace","value":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}]}]}]}