{"abstract":[{"text":"Gets the pixel format as a string","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatAsString"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/formatAsString()","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"formatAsString","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(cs)MCVideoCapabilities(im)formatAsString","roleHeading":"Instance Method","symbolKind":"method","title":"formatAsString()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatAsString"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/formatasstring()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/formatasstring()"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/formatAsString()":{"url":"\/documentation\/millicastsdk\/mcvideocapabilities\/formatasstring()","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/formatAsString()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"formatAsString","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"formatAsString"}],"kind":"symbol","abstract":[{"type":"text","text":"Gets the pixel format as a string"}],"title":"formatAsString()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoCapabilities"}],"type":"topic","title":"MCVideoCapabilities","kind":"symbol","abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoCapabilities"}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"formatAsString","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"formatAsString"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"formatAsString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"formatAsString","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1formatAsString()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"formatAsString","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1formatAsString()\/fragments"},{"value":"MCVideoCapabilities","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoCapabilities"}]}]}]}