{"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/httperror()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"httpError()","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"s:So12MCSubscriberC12MillicastSDKE9httpErrorScSySo016MCHTTPConnectionE0CGyF","extendedModule":"MillicastSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"httpError"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"text":">","kind":"text"}]},"abstract":[{"type":"text","text":"Create an AsyncStream that receives http connection errors."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpError()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"httpError","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"text":"<","kind":"text"},{"text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError"},{"text":">","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new async stream reporting http errors."}]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriber"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","title":"MCSubscriber","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/httpError()":{"title":"httpError()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"httpError"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"kind":"text","text":">"}],"role":"symbol","abstract":[{"text":"Create an AsyncStream that receives http connection errors.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpError()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/httperror()"},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError":{"url":"\/documentation\/millicastsdk\/mchttpconnectionerror","navigatorTitle":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"type":"text","text":" "},{"type":"text","text":"connection to the millicast service"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCHTTPConnectionError"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","title":"MCHTTPConnectionError","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"MCSubscriber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"op":"replace","value":"MCHTTPConnectionError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title"},{"value":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}