{"metadata":{"navigatorTitle":[{"text":"webrtcVideoTracksWithCompletionHandler:","kind":"identifier"}],"externalID":"c:objc(cs)MCSubscriber(im)webrtcVideoTracksWithCompletionHandler:","title":"webrtcVideoTracks(completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcVideoTracks"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"sections":[],"abstract":[{"type":"text","text":"List all available webrtc remote video tracks created so far."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/webrtcvideotracks(completionhandler:)"]},{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/webrtcvideotracks(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webrtcVideoTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" ([","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","text":"MCWebrtcRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"text":"Invoked when the asynchronous operation completes, with a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"list of webrtc remote video tracks."}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcVideoTracks(completionHandler:)"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","navigatorTitle":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The webrtc logical track’s audio interface."}],"title":"MCWebrtcRemoteAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"title":"MCSubscriber","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/webrtcVideoTracks(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/webrtcvideotracks(completionhandler:)","navigatorTitle":[{"text":"webrtcVideoTracksWithCompletionHandler:","kind":"identifier"}],"type":"topic","title":"webrtcVideoTracks(completionHandler:)","abstract":[{"type":"text","text":"List all available webrtc remote video tracks created so far."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/webrtcVideoTracks(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webrtcVideoTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ([","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","kind":"typeIdentifier"},{"text":"]?, (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"webrtcVideoTracksWithCompletionHandler:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webrtcVideoTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"webrtcVideoTracksWithCompletionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<MCWebrtcRemoteAudioTrack *>"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCWebrtcRemoteAudioTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"op":"replace","value":"webrtcVideoTracksWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcVideoTracks(completionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcVideoTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1webrtcVideoTracks(completionHandler:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}