{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/stopCapture(completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource"]]},"abstract":[{"type":"text","text":"Stops capturing the application screen."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"handler that is invoked when the result is ready."}]}]}],"kind":"parameters"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource\/stopcapture(completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource\/stopcapture(completionhandler:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)MCAppShareSource(im)stopCaptureWithCompletionHandler:","navigatorTitle":[{"kind":"identifier","text":"stopCaptureWithCompletionHandler:"}],"title":"stopCapture(completionHandler:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource":{"abstract":[{"type":"text","text":"Uses Replaykit to capture the screen of the application."}],"url":"\/documentation\/millicastsdk\/mcappsharesource","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource","title":"MCAppShareSource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAppShareSource","kind":"identifier"}],"navigatorTitle":[{"text":"MCAppShareSource","kind":"identifier"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/stopCapture(completionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/stopCapture(completionHandler:)","abstract":[{"type":"text","text":"Stops capturing the application screen."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcappsharesource\/stopcapture(completionhandler:)","title":"stopCapture(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"stopCaptureWithCompletionHandler:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopCaptureWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopCaptureWithCompletionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopCaptureWithCompletionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/title","value":"MCAppShareSource"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/fragments","value":[{"kind":"identifier","text":"MCAppShareSource"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1stopCapture(completionHandler:)\/title","value":"stopCaptureWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1stopCapture(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopCaptureWithCompletionHandler:","kind":"identifier"}]}]}]}