{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2h","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"MCScalabilityMode.s2t2h","role":"symbol","symbolKind":"case","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS2T2h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2h","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T2h"}]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2h","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2h"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2h"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"role":"symbol","title":"MCScalabilityMode","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","abstract":[{"text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true,"type":"reference"},{"text":" to understand where these values come from","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t2h":{"title":"MCScalabilityMode.s2t2h","navigatorTitle":[{"text":"MCScalabilityModeS2T2h","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2h","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2h","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCScalabilityModeS2T2h","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCScalabilityModeS2T2h","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeS2T2h"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCScalabilityMode","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCScalabilityMode"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","op":"replace"},{"value":"MCScalabilityModeS2T2h","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2h\/title","op":"replace"},{"value":[{"text":"MCScalabilityModeS2T2h","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2h\/fragments","op":"replace"}]}]}