{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRenderer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can choose from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"},{"type":"text","text":" which are directly attachable to Views. Otherwise, if you have a specific"},{"type":"text","text":" "},{"type":"text","text":"usecase for receiving video frames and managing them yourself, then you can implement your own "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/addrenderer(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/addrenderer(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/addRenderer(_:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Attach a renderer to this track so it receives frames when projected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRenderer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"addRenderer(_:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack(im)addRenderer:completionHandler:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addRenderer:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"role":"symbol","title":"MCWebrtcRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"role":"symbol","title":"MCVideoFrame","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},{"type":"text","text":" for playback."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}],"url":"\/documentation\/millicastsdk\/mcvideoframe"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","title":"MCVideoRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"role":"symbol","title":"MCAcceleratedVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/addRenderer(_:completionHandler:)":{"role":"symbol","title":"addRenderer(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addRenderer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Attach a renderer to this track so it receives frames when projected."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/addRenderer(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRenderer:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/addrenderer(_:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"role":"symbol","title":"MCCMSampleBufferVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"abstract":[{"type":"text","text":"This class is responsible for converting "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"},{"type":"text","text":"  into renderable "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" frames."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addRenderer:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addRenderer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MCVideoRenderer>","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"renderer"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","value":"MCWebrtcRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1addRenderer(_:completionHandler:)\/title","value":"addRenderer:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1addRenderer(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}