{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/streamname"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/streamname"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"streamName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/streamName","interfaceLanguage":"swift"},"metadata":{"title":"streamName","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCPublisherCredentials(py)streamName","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"streamName"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"streamName","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"abstract":[{"text":"The name of the stream to publish.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"https://dash.millicast.com/docs.html":{"type":"link","identifier":"https:\/\/dash.millicast.com\/docs.html","url":"https:\/\/dash.millicast.com\/docs.html","title":"streaming dashboard","titleInlineContent":[{"type":"text","text":"streaming dashboard"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials/streamName":{"title":"streamName","navigatorTitle":[{"kind":"identifier","text":"streamName"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/streamName","role":"symbol","abstract":[{"type":"text","text":"The name of the stream to publish."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcpublishercredentials\/streamname","kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"title":"MCPublisherCredentials","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCPublisherCredentials","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The Credentials interface represents the credentials required for"},{"type":"text","text":" "},{"text":"connecting the publisher to the streaming platform and publishing a stream.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Refer to the "},{"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true},{"text":" for this information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherCredentials"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","url":"\/documentation\/millicastsdk\/mcpublishercredentials"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"streamName","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"streamName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"streamName","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"streamName","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1streamName\/title","op":"replace"},{"value":[{"kind":"identifier","text":"streamName"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1streamName\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title","value":"MCPublisherCredentials","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments","value":[{"kind":"identifier","text":"MCPublisherCredentials"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}