{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/get_type()"},"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"metadata":{"title":"get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"externalID":"c:objc(cs)MCIceCandidatePairStats(cm)get_type","modules":[{"name":"MillicastSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"roleHeading":"Type Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier","text":"MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/get_type()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/get_type()"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCIceCandidatePairStats":{"url":"\/documentation\/millicastsdk\/mcicecandidatepairstats","title":"MCIceCandidatePairStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCIceCandidatePairStats","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stastistics representing an ice candidate pair."}],"navigatorTitle":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCIceCandidatePairStats/get_type()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/get_type()","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/get_type()","role":"symbol","kind":"symbol","title":"get_type()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"get_type","kind":"identifier"}],"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype","abstract":[{"type":"text","text":"Different types of statistics."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"title":"MCStatsType","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"get_type","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType"},{"kind":"text","text":") "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCIceCandidatePairStats","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title"},{"value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments"},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1get_type()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1get_type()\/fragments"},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title"},{"value":[{"text":"MCStatsType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}