{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoUIViewType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideouiviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol that various UIViews implement to interface with"},{"type":"text","text":" "},{"type":"text","text":"Video tracks."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoUIViewType"}],"title":"MCVideoUIViewType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:12MillicastSDK17MCVideoUIViewTypeP","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoUIViewType"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/scalingMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/attach(videoTrack:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/attach(videoTrack:mirrored:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"role":"symbol","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal or OpenGL as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoUIViewType/attach(videoTrack:)":{"role":"symbol","title":"attach(videoTrack:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the track to be displayed in this view."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/attach(videoTrack:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideouiviewtype\/attach(videotrack:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoUIViewType/scalingMode":{"role":"symbol","title":"scalingMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scalingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoViewScalingMode","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO"}],"abstract":[{"type":"text","text":"ScalingMode for video."},{"type":"text","text":" "},{"type":"text","text":"Use this to decide how the video is displayed within the bounds of the UIView."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/scalingMode","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcvideouiviewtype\/scalingmode"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoUIViewType/attach(videoTrack:mirrored:)":{"role":"symbol","title":"attach(videoTrack:mirrored:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mirrored"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the track to be displayed in this view."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType\/attach(videoTrack:mirrored:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcvideouiviewtype\/attach(videotrack:mirrored:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoUIViewType":{"role":"symbol","title":"MCVideoUIViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoUIViewType"}],"abstract":[{"type":"text","text":"Protocol that various UIViews implement to interface with"},{"type":"text","text":" "},{"type":"text","text":"Video tracks."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoUIViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoUIViewType"}],"url":"\/documentation\/millicastsdk\/mcvideouiviewtype"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"role":"symbol","title":"MCSampleBufferVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","value":"MCAcceleratedVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}