{"abstract":[{"type":"text","text":"The number of header bytes received. See  "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","type":"reference"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/header_bytes_received"},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)header_bytes_received","navigatorTitle":[{"kind":"identifier","text":"header_bytes_received"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"header_bytes_received","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"header_bytes_received","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"header_bytes_received","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/header_bytes_received"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/header_bytes_received"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/header_bytes_received":{"navigatorTitle":[{"kind":"identifier","text":"header_bytes_received"}],"kind":"symbol","abstract":[{"type":"text","text":"The number of header bytes received. See  "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","isActive":true,"type":"reference"}],"title":"header_bytes_received","role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/header_bytes_received","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/header_bytes_received","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"header_bytes_received","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-headerbytesreceived":{"titleInlineContent":[{"type":"text","text":"headerBytesReceived"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","title":"headerBytesReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","type":"link"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"header_bytes_received","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"header_bytes_received"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsigned long","kind":"typeIdentifier","preciseIdentifier":"c:l"},{"text":" ","kind":"text"},{"text":"header_bytes_received","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats","op":"replace"},{"op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1header_bytes_received\/title","value":"header_bytes_received"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1header_bytes_received\/fragments","value":[{"text":"header_bytes_received","kind":"identifier"}],"op":"replace"}]}]}