{"sections":[],"abstract":[{"type":"text","text":"The number of removed audio samples for acceleration. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","isActive":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removed_samples_for_acceleration"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/removed_samples_for_acceleration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"metadata":{"symbolKind":"property","title":"removed_samples_for_acceleration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removed_samples_for_acceleration"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removed_samples_for_acceleration"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)removed_samples_for_acceleration"},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/removed_samples_for_acceleration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/removed_samples_for_acceleration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/removed_samples_for_acceleration":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"removed_samples_for_acceleration","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"title":"removed_samples_for_acceleration","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/removed_samples_for_acceleration","type":"topic","abstract":[{"text":"The number of removed audio samples for acceleration. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","type":"reference","isActive":true}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/removed_samples_for_acceleration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removed_samples_for_acceleration"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration":{"type":"link","title":"removedSamplesForAcceleration","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","titleInlineContent":[{"type":"text","text":"removedSamplesForAcceleration"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"removed_samples_for_acceleration","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"removed_samples_for_acceleration"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"text":"unsigned long","preciseIdentifier":"c:l","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removed_samples_for_acceleration"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"removed_samples_for_acceleration","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1removed_samples_for_acceleration\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1removed_samples_for_acceleration\/fragments","op":"replace","value":[{"kind":"identifier","text":"removed_samples_for_acceleration"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace","value":"MCInboundRtpStreamStats"},{"value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}