{"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/retransmitted_packets_received"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/retransmitted_packets_received"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The total number of retransmitted packets that were received for this SSRC. This is a subset of packetsReceived. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","type":"reference"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retransmitted_packets_received"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"retransmitted_packets_received","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)retransmitted_packets_received","symbolKind":"property","title":"retransmitted_packets_received","navigatorTitle":[{"text":"retransmitted_packets_received","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_packets_received","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/retransmitted_packets_received":{"navigatorTitle":[{"kind":"identifier","text":"retransmitted_packets_received"}],"kind":"symbol","abstract":[{"type":"text","text":"The total number of retransmitted packets that were received for this SSRC. This is a subset of packetsReceived. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","isActive":true}],"title":"retransmitted_packets_received","role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/retransmitted_packets_received","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_packets_received","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"retransmitted_packets_received","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived":{"title":"retransmittedpacketsreceived","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","type":"link","titleInlineContent":[{"type":"text","text":"retransmittedpacketsreceived"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"retransmitted_packets_received","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"retransmitted_packets_received","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","kind":"typeIdentifier","text":"unsigned long"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retransmitted_packets_received"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"value":"retransmitted_packets_received","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_packets_received\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_packets_received\/fragments","op":"replace","value":[{"kind":"identifier","text":"retransmitted_packets_received"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}