{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnected"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcdelegate\/onconnected()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdelegate\/onconnected()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnected()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the WebSocket connection to Millicast opens."}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"onConnected"}],"role":"symbol","title":"onConnected()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnected"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)MCDelegate(im)onConnected","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"url":"\/documentation\/millicastsdk\/mcdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onConnected()":{"navigatorTitle":[{"kind":"identifier","text":"onConnected"}],"deprecated":true,"role":"symbol","title":"onConnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the WebSocket connection to Millicast opens."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnected()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onconnected()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onConnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onConnected"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnected()\/title","value":"onConnected"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}