{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"]]},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/init()","interfaceLanguage":"swift"},"abstract":[{"text":"Initialize the renderer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/init()"]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"init","externalID":"c:objc(cs)MCCMSampleBufferVideoRenderer(im)init"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"url":"\/documentation\/millicastsdk\/mcvideoframe","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"type":"text","text":" for playback."}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","title":"MCVideoFrame"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"abstract":[{"text":"This class is responsible for converting ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","isActive":true},{"type":"text","text":"  into renderable "},{"code":"CMSampleBufferRef","type":"codeVoice"},{"type":"text","text":" frames."}],"navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","title":"MCCMSampleBufferVideoRenderer","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/init()":{"title":"init()","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize the renderer."}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/init()","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCVideoFrame","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},{"value":"init","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}]}]}