{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCVideoSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"a new video source.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder\/build()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder\/build()"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"text":"MCVideoSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"kind":"text","text":"!"}],"title":"build()","navigatorTitle":[{"text":"build","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MCVideoSourceBuilder(im)build"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/build()","interfaceLanguage":"swift"},"abstract":[{"text":"Builds the VideoSource class.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource":{"abstract":[{"text":"Responsible for managing video sources.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MCVideoSource","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideosource","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoSource"}],"title":"MCVideoSource"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceBuilder"}],"role":"symbol","abstract":[{"text":"Responsible for building a video source object.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcvideosourcebuilder","kind":"symbol","title":"MCVideoSourceBuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder/build()":{"url":"\/documentation\/millicastsdk\/mcvideosourcebuilder\/build()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoSource","text":"MCVideoSource"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"build","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Builds the VideoSource class."}],"role":"symbol","title":"build()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/build()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"build","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"build","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"MCVideoSource","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","preciseIdentifier":"c:objc(cs)MCVideoSource"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/title","op":"replace","value":"MCVideoSource"},{"value":[{"text":"MCVideoSource","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/fragments","op":"replace"},{"op":"replace","value":"MCVideoSourceBuilder","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/fragments","value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}]},{"value":"build","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1build()\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1build()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"build","kind":"identifier"}]}]}]}