{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl\/getVolume()"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/getvolume()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/getvolume()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVolume","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The current volume level."}]}]}],"metadata":{"required":true,"externalID":"c:objc(pl)MCAudioControl(im)getVolume","roleHeading":"Instance Method","title":"getVolume()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getVolume","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"getVolume","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Gets the current volume."}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioControl/getVolume()":{"kind":"symbol","required":true,"url":"\/documentation\/millicastsdk\/mcaudiocontrol\/getvolume()","navigatorTitle":[{"kind":"identifier","text":"getVolume"}],"abstract":[{"type":"text","text":"Gets the current volume."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVolume"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"type":"topic","title":"getVolume()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl\/getVolume()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioControl":{"role":"symbol","navigatorTitle":[{"text":"MCAudioControl","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl","url":"\/documentation\/millicastsdk\/mcaudiocontrol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioControl","kind":"identifier"}],"title":"MCAudioControl","type":"topic","abstract":[{"text":"Manages audio settings.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"getVolume","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVolume"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"kind":"text","text":") "},{"kind":"identifier","text":"getVolume"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getVolume","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl~1getVolume()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVolume"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl~1getVolume()\/fragments"},{"value":"MCAudioControl","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/title"},{"value":[{"text":"MCAudioControl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/fragments"}]}]}