{"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/setvolume(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/setvolume(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl\/setVolume(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVolume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"v"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"v","content":[{"type":"paragraph","inlineContent":[{"text":"The volume level between 0 (mute) and 1 (full volume).","type":"text"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVolume"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setVolume:"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)MCAudioControl(im)setVolume:","title":"setVolume(_:)","symbolKind":"method","required":true},"kind":"symbol","abstract":[{"type":"text","text":"Adjusts the microphone or speaker volume."}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioControl":{"role":"symbol","navigatorTitle":[{"text":"MCAudioControl","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl","url":"\/documentation\/millicastsdk\/mcaudiocontrol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioControl","kind":"identifier"}],"title":"MCAudioControl","type":"topic","abstract":[{"text":"Manages audio settings.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioControl/setVolume(_:)":{"title":"setVolume(_:)","kind":"symbol","required":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioControl\/setVolume(_:)","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/setvolume(_:)","abstract":[{"text":"Adjusts the microphone or speaker volume.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVolume","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setVolume:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setVolume:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setVolume:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setVolume:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint32_t","preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"v","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/title","value":"MCAudioControl","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl\/fragments","value":[{"kind":"identifier","text":"MCAudioControl"}],"op":"replace"},{"value":"setVolume:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl~1setVolume(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolume:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioControl~1setVolume(_:)\/fragments","op":"replace"}]}]}