{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"text":"MCPublisherDelegate","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","preciseIdentifier":"c:objc(pl)MCPublisherDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MCPublisherDelegate","text":"MCPublisherDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"delegate","externalID":"c:objc(cs)MCPublisher(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}]},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/delegate":{"url":"\/documentation\/millicastsdk\/mcpublisher\/delegate","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"text":"MCPublisherDelegate","preciseIdentifier":"c:objc(pl)MCPublisherDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol","title":"delegate","type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/delegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","url":"\/documentation\/millicastsdk\/mcpublisherdelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherDelegate"}],"title":"MCPublisherDelegate","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"text":" ","type":"text"},{"type":"text","text":"You must implement this protocol and set a delegate."},{"text":" ","type":"text"},{"type":"text","text":"to receive events from the publisher."}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<MCPublisherDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCPublisherDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"delegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1delegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate","op":"replace"},{"op":"replace","value":[{"text":"MCPublisherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]}]}]}