{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/setCredentials(_:completionHandler:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Sets the publisher credentials, providing authentication information","type":"text"},{"type":"text","text":" "},{"type":"text","text":"required for connecting to the streaming platform."}],"metadata":{"navigatorTitle":[{"text":"setCredentials:completionHandler:","kind":"identifier"}],"externalID":"c:objc(cs)MCPublisher(im)setCredentials:completionHandler:","title":"setCredentials(_:completionHandler:)","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCredentials","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCredentials"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCPublisherCredentials","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","text":"MCPublisherCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The publishing credentials.","type":"text"}]}],"name":"credentials"},{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Invoked when the result is ready."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/setcredentials(_:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/setcredentials(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"navigatorTitle":[{"text":"MCPublisherCredentials","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","title":"MCPublisherCredentials","abstract":[{"type":"text","text":"The Credentials interface represents the credentials required for"},{"text":" ","type":"text"},{"text":"connecting the publisher to the streaming platform and publishing a stream.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Refer to the "},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"},{"text":" for this information.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherCredentials"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcpublishercredentials"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"kind":"symbol"},"https://dash.millicast.com/docs.html":{"title":"streaming dashboard","identifier":"https:\/\/dash.millicast.com\/docs.html","titleInlineContent":[{"type":"text","text":"streaming dashboard"}],"type":"link","url":"https:\/\/dash.millicast.com\/docs.html"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/setCredentials(_:completionHandler:)":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/setCredentials(_:completionHandler:)","title":"setCredentials(_:completionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCredentials"},{"kind":"text","text":"("},{"text":"MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setCredentials:completionHandler:"}],"abstract":[{"type":"text","text":"Sets the publisher credentials, providing authentication information"},{"text":" ","type":"text"},{"text":"required for connecting to the streaming platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/setcredentials(_:completionhandler:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setCredentials:completionHandler:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCredentials:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setCredentials:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCPublisherCredentials","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","text":"MCPublisherCredentials"},{"text":" *) ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"MCPublisherCredentials","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments","value":[{"text":"MCPublisherCredentials","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}]},{"op":"replace","value":"setCredentials:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1setCredentials(_:completionHandler:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCredentials:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1setCredentials(_:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}