{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/signalingErrorPublisher()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"Get a Combine based publisher that can be used to receive signaling errors","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signalingErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"text":"MCSignalingError","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","text":"Never","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["swift"]}]}],"metadata":{"externalID":"s:So11MCPublisherC12MillicastSDKE23signalingErrorPublisher7Combine03AnyF0VySo011MCSignalingE0Cs5NeverOGyF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"signalingErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSignalingError","text":"MCSignalingError"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"title":"signalingErrorPublisher()","role":"symbol","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/signalingerrorpublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/signalingErrorPublisher()":{"url":"\/documentation\/millicastsdk\/mcpublisher\/signalingerrorpublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive signaling errors"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"signalingErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO","text":"Never"},{"text":">","kind":"text"}],"role":"symbol","title":"signalingErrorPublisher()","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/signalingErrorPublisher()"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSignalingError":{"abstract":[{"text":"Container class for Signaling errors that occur during","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"signaling\/configuration of the peer connection."}],"url":"\/documentation\/millicastsdk\/mcsignalingerror","role":"symbol","type":"topic","navigatorTitle":[{"text":"MCSignalingError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSignalingError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","title":"MCSignalingError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/title","value":"MCSignalingError"},{"value":[{"text":"MCSignalingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/fragments"}]}]}