{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/payload_type"},"kind":"symbol","abstract":[{"text":"The unique identifier for the codec payload type. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","isActive":true,"type":"reference"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/payload_type"]},{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/payload_type"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"payload_type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"payload_type","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payload_type"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"externalID":"c:objc(cs)MCCodecsStats(py)payload_type","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","title":"payload_type"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol","title":"MCCodecsStats","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/payload_type":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/payload_type","role":"symbol","navigatorTitle":[{"text":"payload_type","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats\/payload_type","abstract":[{"type":"text","text":"The unique identifier for the codec payload type. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","type":"reference","isActive":true}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payload_type"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"type":"topic","title":"payload_type"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-payloadtype":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","title":"payloadType","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-payloadtype","type":"link","titleInlineContent":[{"type":"text","text":"payloadType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"payload_type","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"payload_type"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:l","kind":"typeIdentifier","text":"unsigned long"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payload_type"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats"},{"op":"replace","value":[{"kind":"identifier","text":"MCCodecsStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1payload_type\/title","value":"payload_type"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1payload_type\/fragments","value":[{"kind":"identifier","text":"payload_type"}]}]}]}