{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdp_fmtp_line","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sdp_fmtp_line"}],"roleHeading":"Instance Property","title":"sdp_fmtp_line","externalID":"c:objc(cs)MCCodecsStats(py)sdp_fmtp_line"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdp_fmtp_line"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The Session Description Protocol (SDP) line associated with the codec. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/sdp_fmtp_line","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/sdp_fmtp_line"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/sdp_fmtp_line"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"navigatorTitle":[{"kind":"identifier","text":"MCCodecsStats"}],"role":"symbol","title":"MCCodecsStats","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/sdp_fmtp_line":{"title":"sdp_fmtp_line","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdp_fmtp_line"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"The Session Description Protocol (SDP) line associated with the codec. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline","isActive":true,"type":"reference"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/sdp_fmtp_line","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"sdp_fmtp_line","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats\/sdp_fmtp_line"},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-sdpfmtpline":{"type":"link","titleInlineContent":[{"text":"sdpFmtpLine","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-sdpfmtpline","title":"sdpFmtpLine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"sdp_fmtp_line","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"sdp_fmtp_line","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"sdp_fmtp_line","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"MCCodecsStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments","value":[{"text":"MCCodecsStats","kind":"identifier"}],"op":"replace"},{"value":"sdp_fmtp_line","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1sdp_fmtp_line\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1sdp_fmtp_line\/fragments","op":"replace","value":[{"kind":"identifier","text":"sdp_fmtp_line"}]}]}]}