{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":", ","kind":"text"},{"text":"didUpdateLayers","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rtsRemoteTrackLayers","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"rtsRemoteTrack","content":[{"inlineContent":[{"type":"text","text":"The remote track receiving the layer events."}],"type":"paragraph"}]},{"name":"rtsRemoteTrackLayers","content":[{"type":"paragraph","inlineContent":[{"text":"The layer event data.","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(pl)MCRTSRemoteTrackDelegate(im)rtsRemoteTrack:didUpdateLayers:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didUpdateLayers:"}],"title":"rtsRemoteTrack(_:didUpdateLayers:)","roleHeading":"Instance Method","required":true,"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLayers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"text":")","kind":"text"}]},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Event received when there is Simulcast\/SVC layers available for the remote track. Only"},{"type":"text","text":" "},{"type":"text","text":"available for video tracks."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatelayers:)"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatelayers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"title":"MCRTSRemoteTrackDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateLayers:)":{"navigatorTitle":[{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatelayers:)","title":"rtsRemoteTrack(_:didUpdateLayers:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didUpdateLayers"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Event received when there is Simulcast\/SVC layers available for the remote track. Only","type":"text"},{"type":"text","text":" "},{"text":"available for video tracks.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"title":"MCRTSRemoteTrack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"type":"text","text":" "},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"type":"text","text":" "},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"abstract":[{"type":"text","text":"The layers update event. Note that if the RtsTrack is projected"},{"type":"text","text":" "},{"type":"text","text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,"},{"type":"text","text":" "},{"type":"text","text":"so the RTS track will get multiple layer events."},{"type":"text","text":" "},{"text":"No debouncing\/deduplication is implemented.","type":"text"}],"type":"topic","title":"MCRTSRemoteTrackLayers","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rtsRemoteTrack:didUpdateLayers:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrack:didUpdateLayers:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrack:"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":" *) ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateLayers:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rtsRemoteTrackLayers"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title","op":"replace","value":"MCRTSRemoteTrackDelegate"},{"op":"replace","value":[{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/title","value":"rtsRemoteTrack:didUpdateLayers:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}]},{"op":"replace","value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/title","op":"replace","value":"MCRTSRemoteTrackLayers"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/fragments","op":"replace"}]}]}