{"metadata":{"roleHeading":"Case","title":"MCStatsType.codec","modules":[{"name":"MillicastSDK"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codec","kind":"identifier"}],"navigatorTitle":[{"text":"MCStatsTypeCodec","kind":"identifier"}],"externalID":"c:@E@MCStatsType@MCStatsTypeCodec"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/codec","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/codec"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/codec"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"codec","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/codec":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/codec","url":"\/documentation\/millicastsdk\/mcstatstype\/codec","abstract":[],"type":"topic","navigatorTitle":[{"text":"MCStatsTypeCodec","kind":"identifier"}],"title":"MCStatsType.codec","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"codec"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstatstype","abstract":[{"text":"Different types of statistics.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCStatsTypeCodec"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MCStatsTypeCodec","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCStatsTypeCodec"}],"languages":["occ"]}]}},{"value":"MCStatsTypeCodec","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1codec\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsTypeCodec"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1codec\/fragments"},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments"}]}]}