{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/iceCandidatePair","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iceCandidatePair"}]}]}],"metadata":{"title":"MCStatsType.iceCandidatePair","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"iceCandidatePair","kind":"identifier"}],"role":"symbol","externalID":"c:@E@MCStatsType@MCStatsTypeIceCandidatePair","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeIceCandidatePair"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/icecandidatepair"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/icecandidatepair"]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/iceCandidatePair":{"url":"\/documentation\/millicastsdk\/mcstatstype\/icecandidatepair","title":"MCStatsType.iceCandidatePair","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iceCandidatePair"}],"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeIceCandidatePair","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/iceCandidatePair","abstract":[],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstatstype","abstract":[{"text":"Different types of statistics.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MCStatsTypeIceCandidatePair"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsTypeIceCandidatePair"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCStatsTypeIceCandidatePair"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1iceCandidatePair\/title","value":"MCStatsTypeIceCandidatePair"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1iceCandidatePair\/fragments","value":[{"kind":"identifier","text":"MCStatsTypeIceCandidatePair"}]},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"text":"MCStatsType","kind":"identifier"}],"op":"replace"}]}]}