{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"videoTrack","kind":"identifier"}]}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCStatsType@MCStatsTypeVideoTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"videoTrack","kind":"identifier"}],"title":"MCStatsType.videoTrack"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/videotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/videotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/videoTrack"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/videoTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/videoTrack","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeVideoTrack"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","title":"MCStatsType.videoTrack","url":"\/documentation\/millicastsdk\/mcstatstype\/videotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"role":"symbol","title":"MCStatsType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstatstype","abstract":[{"text":"Different types of statistics.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCStatsTypeVideoTrack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1videoTrack\/title","value":"MCStatsTypeVideoTrack"},{"op":"replace","value":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1videoTrack\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"value":[{"kind":"identifier","text":"MCStatsType"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace"}]}]}