{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3h","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s2t3h"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"s2t3h"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T3h"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS2T3h","title":"MCScalabilityMode.s2t3h"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t3h"]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t3h"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","type":"topic","role":"symbol","abstract":[{"text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true,"type":"reference"},{"type":"text","text":" to understand where these values come from"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCScalabilityMode"}],"title":"MCScalabilityMode","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}]},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/s2t3h":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3h","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"s2t3h","kind":"identifier"}],"title":"MCScalabilityMode.s2t3h","abstract":[],"navigatorTitle":[{"text":"MCScalabilityModeS2T3h","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t3h"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCScalabilityModeS2T3h","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeS2T3h","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeS2T3h"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MCScalabilityModeS2T3h","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3h\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3h\/fragments","value":[{"text":"MCScalabilityModeS2T3h","kind":"identifier"}]}]}]}