{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"s3t2h","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s3t2h"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s3t2h"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2h","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"MCScalabilityModeS3T2h","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCScalabilityMode.s3t2h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"s3t2h"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS3T2h"},"references":{"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","type":"link","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/s3t2h":{"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t2h","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2h","role":"symbol","title":"MCScalabilityMode.s3t2h","navigatorTitle":[{"text":"MCScalabilityModeS3T2h","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s3t2h","kind":"identifier"}],"abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","type":"topic","role":"symbol","abstract":[{"text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true,"type":"reference"},{"type":"text","text":" to understand where these values come from"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCScalabilityMode"}],"title":"MCScalabilityMode","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCScalabilityModeS3T2h"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeS3T2h","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeS3T2h"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2h\/title","value":"MCScalabilityModeS3T2h"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2h\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeS3T2h"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments"}]}]}