{"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(cs)MCVideoSourceBuilder(im)setCapabilities:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setCapabilities","kind":"identifier"},{"kind":"text","text":"(["},{"text":"MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities","kind":"typeIdentifier"},{"kind":"text","text":"]!)"}],"navigatorTitle":[{"kind":"identifier","text":"setCapabilities:"}],"roleHeading":"Instance Method","role":"symbol","title":"setCapabilities(_:)"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setCapabilities","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"capabilities"},{"text":": [","kind":"text"},{"text":"MCVideoCapabilities","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities"},{"kind":"text","text":"]!)"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/setCapabilities(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Sets capabilities for the video source.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder\/setcapabilities(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcebuilder\/setcapabilities(_:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder/setCapabilities(_:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder\/setCapabilities(_:)","url":"\/documentation\/millicastsdk\/mcvideosourcebuilder\/setcapabilities(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setCapabilities:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCapabilities","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities"},{"text":"]!)","kind":"text"}],"title":"setCapabilities(_:)","abstract":[{"type":"text","text":"Sets capabilities for the video source."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceBuilder":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceBuilder","url":"\/documentation\/millicastsdk\/mcvideosourcebuilder","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCVideoSourceBuilder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoSourceBuilder","kind":"identifier"}],"title":"MCVideoSourceBuilder","abstract":[{"type":"text","text":"Responsible for building a video source object."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities":{"title":"MCVideoCapabilities","url":"\/documentation\/millicastsdk\/mcvideocapabilities","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoCapabilities"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoCapabilities"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setCapabilities:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCapabilities:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setCapabilities:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<MCVideoCapabilities *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"capabilities"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1setCapabilities(_:)\/title","value":"setCapabilities:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCapabilities:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder~1setCapabilities(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/title","op":"replace","value":"MCVideoSourceBuilder"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceBuilder\/fragments","op":"replace","value":[{"text":"MCVideoSourceBuilder","kind":"identifier"}]},{"op":"replace","value":"MCVideoCapabilities","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/title"},{"value":[{"text":"MCVideoCapabilities","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments"}]}]}