{"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccleanup\/cleanup()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccleanup\/cleanup()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCleanup"]]},"abstract":[{"text":"Cleans and frees the memory of dynamic objects. Call this method after all SDK objects have been destroyed. You would likely call this function just before the application exit.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"cleanup","kind":"identifier"}],"roleHeading":"Type Method","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCCleanup(cm)cleanup","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanup","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"cleanup()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCleanup\/cleanup()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCleanup/cleanup()":{"url":"\/documentation\/millicastsdk\/mccleanup\/cleanup()","navigatorTitle":[{"kind":"identifier","text":"cleanup"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCleanup\/cleanup()","title":"cleanup()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanup"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Cleans and frees the memory of dynamic objects. Call this method after all SDK objects have been destroyed. You would likely call this function just before the application exit."}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCleanup":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCleanup"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccleanup","abstract":[{"type":"text","text":"The Cleanup class is responsible for cleaning the memory of dynamic objects."}],"navigatorTitle":[{"kind":"identifier","text":"MCCleanup"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCleanup","title":"MCCleanup","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"cleanup"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cleanup"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"cleanup","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCleanup~1cleanup()\/title","op":"replace","value":"cleanup"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCleanup~1cleanup()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCleanup\/title","value":"MCCleanup"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCleanup\/fragments","value":[{"kind":"identifier","text":"MCCleanup"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCleanup\/navigatorTitle","value":[{"kind":"identifier","text":"MCCleanup"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}