{"variants":[{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mciosvideorendererdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mciosvideorendererdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCIosVideoRendererDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"MillicastSDK"}],"role":"collectionGroup","title":"MCIosVideoRendererDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"role":"symbol","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal or OpenGL as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/didChangeVideoSize(_:)":{"role":"symbol","title":"didChangeVideoSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeVideoSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didChangeVideoSize:"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/didchangevideosize(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","value":"MCAcceleratedVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/title","value":"didChangeVideoSize:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeVideoSize:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}