{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestats:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestats:)"]}],"abstract":[{"type":"text","text":"Called when a new Subscriber statistics report is available."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"subscriber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriber","text":"MCSubscriber","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"},{"text":", ","kind":"text"},{"text":"didReceiveStats","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"stats","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSubscriberStats","text":"MCSubscriberStats","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStats"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The Millicast subscriber","type":"text"}],"type":"paragraph"}],"name":"subscriber"},{"content":[{"inlineContent":[{"text":"A Stats object of type ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStats","isActive":true},{"text":" with various stream information.","type":"text"}],"type":"paragraph"}],"name":"didReceiveStats"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"You must enable statistics via ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","isActive":true},{"text":" ","type":"text"},{"text":"to start receiving this handler.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveStats:)"},"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)MCSubscriberDelegate(im)subscriber:didReceiveStats:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveStats","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCSubscriberStats","preciseIdentifier":"c:objc(cs)MCSubscriberStats","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"subscriber:didReceiveStats:"}],"required":true,"title":"subscriber(_:didReceiveStats:)","modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","title":"MCSubscriber","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberStats":{"url":"\/documentation\/millicastsdk\/mcsubscriberstats","title":"MCSubscriberStats","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStats","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCSubscriberStats","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"title":"enableStats(_:completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","role":"symbol","abstract":[{"text":"Enables or disables the collection and reporting of real-time","type":"text"},{"text":" ","type":"text"},{"text":"statistics associated with streaming sessions.","type":"text"},{"text":" ","type":"text"},{"text":"The statistics are collected once the client is either publishing or subscribed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"enableStats:completionHandler:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberDelegate":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate","navigatorTitle":[{"text":"MCSubscriberDelegate","kind":"identifier"}],"title":"MCSubscriberDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberDelegate/subscriber(_:didReceiveStats:)":{"title":"subscriber(_:didReceiveStats:)","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberDelegate\/subscriber(_:didReceiveStats:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscriber"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberStats","preciseIdentifier":"c:objc(cs)MCSubscriberStats"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"subscriber:didReceiveStats:"}],"kind":"symbol","abstract":[{"type":"text","text":"Called when a new Subscriber statistics report is available."}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/subscriber(_:didreceivestats:)","required":true,"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"subscriber:didReceiveStats:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscriber:didReceiveStats:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"subscriber:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","preciseIdentifier":"c:objc(cs)MCSubscriber","text":"MCSubscriber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveStats:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCSubscriberStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberStats","preciseIdentifier":"c:objc(cs)MCSubscriberStats","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stats","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"text":"MCSubscriber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStats\/title","value":"MCSubscriberStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberStats\/fragments","value":[{"text":"MCSubscriberStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","value":"enableStats:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableStats:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveStats:)\/title","value":"subscriber:didReceiveStats:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberDelegate~1subscriber(_:didReceiveStats:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscriber:didReceiveStats:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}