{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/total_round_trip_time"},"kind":"symbol","abstract":[{"text":"The sum of round-trip times for packets sent between endpoints. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","isActive":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/total_round_trip_time"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/total_round_trip_time"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"total_round_trip_time","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats(py)total_round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","role":"symbol","title":"total_round_trip_time"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","title":"MCRemoteInboundRtpStreamStats","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Statistics about an incoming remote RTP stream."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/total_round_trip_time":{"title":"total_round_trip_time","abstract":[{"type":"text","text":"The sum of round-trip times for packets sent between endpoints. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","isActive":true}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/total_round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/total_round_trip_time","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"total_round_trip_time"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime":{"titleInlineContent":[{"type":"text","text":"totalRoundTripTime"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","title":"totalRoundTripTime"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"total_round_trip_time","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"total_round_trip_time","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCRemoteInboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments","op":"replace"},{"op":"replace","value":"total_round_trip_time","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1total_round_trip_time\/title"},{"op":"replace","value":[{"kind":"identifier","text":"total_round_trip_time"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1total_round_trip_time\/fragments"}]}]}