{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosource\/startcapture()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosource\/startcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)MCAudioSource(im)startCapture","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"title":"startCapture()","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"startCapture","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"An audio track. See "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","type":"reference"},{"text":" to see","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"how you can use this class."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Initiates the audio capture process from the current source.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-340my":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Adds an audio track to the publisher. See "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","isActive":true},{"type":"text","text":" as an example"},{"type":"text","text":" "},{"text":"for capturing an audio device track.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCAudioTrack","kind":"typeIdentifier","text":"MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"title":"addTrack(with:completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"abstract":[{"text":"Represents a captured instance of a media source.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mctrack","kind":"symbol","title":"MCTrack","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"url":"\/documentation\/millicastsdk\/mcaudiosource","role":"symbol","abstract":[{"text":"Manages the audio capture functionality.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCAudioSource","kind":"identifier"}],"title":"MCAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioSource","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource/startCapture()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()","kind":"symbol","abstract":[{"type":"text","text":"Initiates the audio capture process from the current source."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier","text":"MCTrack"},{"kind":"text","text":"!"}],"title":"startCapture()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"startCapture","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startCapture"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"startCapture"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/title","value":"addTrackWithAudioTrack:completionHandler:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","value":"MCTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","value":[{"kind":"identifier","text":"MCTrack"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title","value":"MCAudioSource","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioSource"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments"},{"value":"startCapture","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}