{"kind":"symbol","abstract":[{"type":"text","text":"Query whether the source is currently capturing."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCapturing"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"True if the application is capturing, false otherwise.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccorevideosource\/iscapturing()"]},{"paths":["\/documentation\/millicastsdk\/mccorevideosource\/iscapturing()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCapturing"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"method","title":"isCapturing()","externalID":"c:objc(cs)MCCoreVideoSource(im)isCapturing","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/isCapturing()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/isCapturing()":{"type":"topic","abstract":[{"type":"text","text":"Query whether the source is currently capturing."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCapturing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/millicastsdk\/mccorevideosource\/iscapturing()","title":"isCapturing()","navigatorTitle":[{"text":"isCapturing","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/isCapturing()"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","url":"\/documentation\/millicastsdk\/mccorevideosource","abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"role":"symbol","title":"MCCoreVideoSource","navigatorTitle":[{"text":"MCCoreVideoSource","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"isCapturing","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isCapturing","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"_Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isCapturing","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1isCapturing()\/title","value":"isCapturing","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isCapturing","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1isCapturing()\/fragments"},{"value":"MCCoreVideoSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title"},{"value":[{"kind":"identifier","text":"MCCoreVideoSource"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments"}]}]}