{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccorevideosource\/startcapture()"]},{"paths":["\/documentation\/millicastsdk\/mccorevideosource\/startcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"startCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"externalID":"c:objc(cs)MCCoreVideoSource(im)startCapture","modules":[{"name":"MillicastSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A video track. See "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","type":"reference","isActive":true},{"text":" ","type":"text"},{"type":"text","text":"to learn how to attach this track to a publisher."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Starts capture. Effectively creates a video track that can be added to the publisher."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/startCapture()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","title":"MCTrack","role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","url":"\/documentation\/millicastsdk\/mccorevideosource","abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"role":"symbol","title":"MCCoreVideoSource","navigatorTitle":[{"text":"MCCoreVideoSource","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource/startCapture()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource\/startCapture()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"title":"startCapture()","abstract":[{"type":"text","text":"Starts capture. Effectively creates a video track that can be added to the publisher."}],"type":"topic","url":"\/documentation\/millicastsdk\/mccorevideosource\/startcapture()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-6d3yp":{"title":"addTrack(with:completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MCVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","abstract":[{"type":"text","text":"Adds a video track to the publisher. See "},{"code":"MCVideoSource\/startCapture","type":"codeVoice"},{"text":" as an example","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for capturing a video device track."}],"navigatorTitle":[{"kind":"identifier","text":"addTrackWithVideoTrack:completionHandler:"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"startCapture","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"startCapture","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","text":"MCTrack","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"startCapture","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","value":"MCTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","value":[{"text":"MCTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title","value":"MCCoreVideoSource"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","value":[{"text":"MCCoreVideoSource","kind":"identifier"}],"op":"replace"},{"value":"startCapture","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1startCapture()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource~1startCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"value":"addTrackWithVideoTrack:completionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTrackWithVideoTrack:completionHandler:"}]}]}]}