{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_bytes_sent"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_bytes_sent"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)retransmitted_bytes_sent","title":"retransmitted_bytes_sent","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_bytes_sent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"retransmitted_bytes_sent","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The amount of retransmitted data. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","isActive":true,"type":"reference"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_bytes_sent"]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_bytes_sent"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","titleInlineContent":[{"type":"text","text":"retransmittedBytesSent"}],"title":"retransmittedBytesSent","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"navigatorTitle":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"title":"MCOutboundRtpStreamStats","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/retransmitted_bytes_sent":{"role":"symbol","abstract":[{"type":"text","text":"The amount of retransmitted data. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"retransmitted_bytes_sent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"retransmitted_bytes_sent","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_bytes_sent","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_bytes_sent","type":"topic","title":"retransmitted_bytes_sent","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"retransmitted_bytes_sent","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"retransmitted_bytes_sent"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:k","text":"unsigned long long"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retransmitted_bytes_sent"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_bytes_sent\/title","op":"replace","value":"retransmitted_bytes_sent"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_bytes_sent\/fragments","value":[{"kind":"identifier","text":"retransmitted_bytes_sent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}