{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource","text":"MCAudioSource"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new audio source."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcebuilder\/build()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcebuilder\/build()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder\/build()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Builds the AudioSource class."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource"},{"kind":"text","text":"!"}],"title":"build()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCAudioSourceBuilder(im)build","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"build"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"role":"symbol","title":"MCAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSource"}],"abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"url":"\/documentation\/millicastsdk\/mcaudiosource"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceBuilder":{"role":"symbol","title":"MCAudioSourceBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSourceBuilder"}],"abstract":[{"type":"text","text":"Responsible for building AudioSource."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioSourceBuilder"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcebuilder"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Builds the AudioSource class."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcebuilder\/build()"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"build"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource","text":"MCAudioSource"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title","value":"MCAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","value":[{"kind":"identifier","text":"MCAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder\/title","value":"MCAudioSourceBuilder"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder\/fragments","value":[{"kind":"identifier","text":"MCAudioSourceBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}