{"metadata":{"externalID":"c:objc(cs)MCPublisher(im)addTrackWithVideoTrack:completionHandler:","roleHeading":"Instance Method","navigatorTitle":[{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"addTrack(with:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"symbolKind":"method"},"abstract":[{"text":"Adds a video track to the publisher. See ","type":"text"},{"code":"MCVideoSource\/startCapture","type":"codeVoice"},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing a video device track.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCVideoTrack","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"videoTrack","content":[{"inlineContent":[{"text":"The video track to add.","type":"text"}],"type":"paragraph"}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the result is ready.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-6d3yp":{"abstract":[{"text":"Adds a video track to the publisher. See ","type":"text"},{"code":"MCVideoSource\/startCapture","type":"codeVoice"},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing a video device track.","type":"text"}],"navigatorTitle":[{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCVideoTrack","text":"MCVideoTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"addTrack(with:completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack":{"title":"MCVideoTrack","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","url":"\/documentation\/millicastsdk\/mcvideotrack","navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoTrack","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"addTrackWithVideoTrack:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addTrackWithVideoTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCVideoTrack","text":"MCVideoTrack","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack"},{"text":" *) ","kind":"text"},{"text":"videoTrack","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/title","value":"addTrackWithVideoTrack:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/title","value":"MCVideoTrack","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","value":[{"text":"MCVideoTrack","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}