{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Create an AsyncStream that receives http connection errors."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError"},{"kind":"text","text":">"}]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A new async stream reporting http errors."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpError()","interfaceLanguage":"swift"},"metadata":{"externalID":"s:So11MCPublisherC12MillicastSDKE9httpErrorScSySo016MCHTTPConnectionE0CGyF","extendedModule":"MillicastSDK","title":"httpError()","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier","text":"MCHTTPConnectionError"},{"kind":"text","text":">"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher\/httperror()"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/httpError()":{"url":"\/documentation\/millicastsdk\/mcpublisher\/httperror()","type":"topic","abstract":[{"type":"text","text":"Create an AsyncStream that receives http connection errors."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier","text":"MCHTTPConnectionError"},{"kind":"text","text":">"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpError()","title":"httpError()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCHTTPConnectionError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCHTTPConnectionError"}],"navigatorTitle":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"type":"topic","url":"\/documentation\/millicastsdk\/mchttpconnectionerror","title":"MCHTTPConnectionError","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCHTTPConnectionError","role":"symbol","abstract":[{"text":"Container class for HTTP errors that occur during","type":"text"},{"text":" ","type":"text"},{"text":"connection to the millicast service","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCPublisher","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title"},{"value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"value":"MCHTTPConnectionError","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title"},{"value":[{"kind":"identifier","text":"MCHTTPConnectionError"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"}]}]}