{"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l1t3h","kind":"identifier"}],"navigatorTitle":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}],"title":"MCScalabilityMode.l1t3h","symbolKind":"case","modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL1T3h"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l1t3h"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3h"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3h"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3h"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode","abstract":[{"text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"reference","isActive":true},{"text":" to understand where these values come from","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"title":"MCScalabilityMode"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l1t3h":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3h","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l1t3h","kind":"identifier"}],"title":"MCScalabilityMode.l1t3h","abstract":[],"navigatorTitle":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}],"type":"topic"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"title":"the WebRTC standard","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCScalabilityModeL1T3h"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeL1T3h"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3h\/title","value":"MCScalabilityModeL1T3h"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3h\/fragments","value":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}