{"sections":[],"abstract":[{"type":"text","text":"The cumulative delay during sending packets. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay","type":"reference","isActive":true}],"metadata":{"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"title":"total_packet_send_delay","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_packet_send_delay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"total_packet_send_delay"}],"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)total_packet_send_delay"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/total_packet_send_delay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/total_packet_send_delay"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_packet_send_delay"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"total_packet_send_delay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"role":"symbol","title":"MCOutboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay":{"titleInlineContent":[{"text":"totalPacketSendDelay","type":"text"}],"title":"totalPacketSendDelay","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay"},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/total_packet_send_delay":{"abstract":[{"text":"The cumulative delay during sending packets. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_packet_send_delay"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/total_packet_send_delay","title":"total_packet_send_delay","navigatorTitle":[{"kind":"identifier","text":"total_packet_send_delay"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_packet_send_delay","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"total_packet_send_delay","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"total_packet_send_delay"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"total_packet_send_delay","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_packet_send_delay\/title","op":"replace","value":"total_packet_send_delay"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_packet_send_delay\/fragments","op":"replace","value":[{"text":"total_packet_send_delay","kind":"identifier"}]}]}]}