{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_received"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The number of RTP packets received since the start of streaming. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","type":"reference","isActive":true}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_received"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"title":"packets_received","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"packets_received"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCReceivedRtpStreamStats(py)packets_received"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_received"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_received"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_received"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"role":"symbol","type":"topic","abstract":[{"text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","title":"MCReceivedRtpStreamStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetsreceived":{"type":"link","titleInlineContent":[{"type":"text","text":"packetsReceived"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived","title":"packetsReceived"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCReceivedRtpStreamStats/packets_received":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats\/packets_received","title":"packets_received","navigatorTitle":[{"text":"packets_received","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The number of RTP packets received since the start of streaming. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcreceivedrtpstreamstats-packetsreceived"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats\/packets_received","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"packets_received","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"packets_received","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"packets_received","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned long long","preciseIdentifier":"c:k","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"packets_received","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","value":"MCReceivedRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_received\/title","value":"packets_received"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats~1packets_received\/fragments","value":[{"kind":"identifier","text":"packets_received"}]}]}]}