{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosource\/stopcapture()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosource\/stopcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/stopCapture()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stops the audio capture process."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"title":"stopCapture()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCAudioSource(im)stopCapture","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"stopCapture"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"role":"symbol","title":"MCAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSource"}],"abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"url":"\/documentation\/millicastsdk\/mcaudiosource"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource/stopCapture()":{"role":"symbol","title":"stopCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops the audio capture process."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/stopCapture()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopCapture"}],"url":"\/documentation\/millicastsdk\/mcaudiosource\/stopcapture()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title","value":"MCAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","value":[{"kind":"identifier","text":"MCAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1stopCapture()\/title","value":"stopCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1stopCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopCapture"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}