{"abstract":[{"type":"text","text":"ScalingMode for video."},{"type":"text","text":" "},{"type":"text","text":"Use this to decide how the video is displayed within the bounds of the UIView."}],"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"scalingMode","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scalingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoViewScalingMode","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO"}],"externalID":"s:12MillicastSDK25MCSampleBufferVideoUIViewC11scalingModeAA018MCVideoViewScalingH0Ovp","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scalingMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewScalingMode","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO","text":"MCVideoViewScalingMode","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/scalingmode"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/scalingMode"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoViewScalingMode":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoviewscalingmode","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoViewScalingMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoViewScalingMode","kind":"identifier"}],"abstract":[{"text":"Handling video scaling for SDK implemented UIViews","type":"text"}],"navigatorTitle":[{"text":"MCVideoViewScalingMode","kind":"identifier"}],"role":"symbol","type":"topic","title":"MCVideoViewScalingMode"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/scalingMode":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scalingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCVideoViewScalingMode","kind":"typeIdentifier","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/scalingmode","abstract":[{"type":"text","text":"ScalingMode for video."},{"type":"text","text":" "},{"type":"text","text":"Use this to decide how the video is displayed within the bounds of the UIView."}],"title":"scalingMode","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/scalingMode","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"title":"MCSampleBufferVideoUIView","role":"symbol","abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/navigatorTitle","value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}