{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pinnedSourceId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The receiving source to pin. Refer to "},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","isActive":true,"type":"reference"},{"type":"text","text":" to learn more about this. This is a subscriber only option."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/pinnedsourceid"]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/pinnedsourceid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)MCClientOptions(py)pinnedSourceId","title":"pinnedSourceId","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pinnedSourceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"pinnedSourceId","kind":"identifier"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/pinnedSourceId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/pinnedSourceId":{"type":"topic","abstract":[{"type":"text","text":"The receiving source to pin. Refer to "},{"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","isActive":true,"type":"reference"},{"text":" to learn more about this. This is a subscriber only option.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/pinnedSourceId","url":"\/documentation\/millicastsdk\/mcclientoptions\/pinnedsourceid","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinnedSourceId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"pinnedSourceId"}],"title":"pinnedSourceId"},"https://docs.dolby.io/streaming-apis/docs/multiview":{"type":"link","titleInlineContent":[{"type":"text","text":" The Multiview Guide"}],"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/multiview","title":" The Multiview Guide"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"kind":"symbol","title":"MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"pinnedSourceId","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"pinnedSourceId","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"pinnedSourceId","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1pinnedSourceId\/title","op":"replace","value":"pinnedSourceId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1pinnedSourceId\/fragments","value":[{"kind":"identifier","text":"pinnedSourceId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions"},{"value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments"}]}]}