{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/svcMode"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"abstract":[{"text":"Enables Scalable Video Coding selection. Refer to the ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"reference","isActive":true},{"type":"text","text":" to learn which modes are supported by which codecs. This is only available when publishing."}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/svcmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/svcmode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"svcMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","text":"MCScalabilityMode","preciseIdentifier":"c:@E@MCScalabilityMode","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"svcMode","kind":"identifier"}],"role":"symbol","title":"svcMode","externalID":"c:objc(cs)MCClientOptions(py)svcMode","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"svcMode"},{"kind":"text","text":": "},{"text":"MCScalabilityMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCScalabilityMode"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/svcMode":{"abstract":[{"text":"Enables Scalable Video Coding selection. Refer to the ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true,"type":"reference"},{"text":" to learn which modes are supported by which codecs. This is only available when publishing.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/svcmode","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/svcMode","title":"svcMode","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"svcMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCScalabilityMode","text":"MCScalabilityMode"}],"navigatorTitle":[{"kind":"identifier","text":"svcMode"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true},{"text":" to understand where these values come from","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCScalabilityMode","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","title":"MCScalabilityMode"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"kind":"symbol","title":"MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcclientoptions","abstract":[{"text":"The MCClientOptions class gathers options for the client.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"svcMode"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"svcMode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@MCScalabilityMode","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","kind":"typeIdentifier","text":"MCScalabilityMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"svcMode"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"svcMode","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1svcMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1svcMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"svcMode"}]},{"value":"MCScalabilityMode","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","op":"replace","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCClientOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}