{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"frameWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/frameWidth"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrackstats\/framewidth"]},{"paths":["\/documentation\/millicastsdk\/mctrackstats\/framewidth"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"frameWidth","kind":"identifier"}],"externalID":"c:objc(cs)MCTrackStats(py)frameWidth","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"frameWidth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats":{"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mctrackstats","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats","navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}],"title":"MCTrackStats","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCTrackStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats/frameWidth":{"title":"frameWidth","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats\/frameWidth","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"frameWidth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"frameWidth","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mctrackstats\/framewidth","abstract":[],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"frameWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frameWidth"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"frameWidth","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/title","value":"MCTrackStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/fragments","value":[{"text":"MCTrackStats","kind":"identifier"}],"op":"replace"},{"value":"frameWidth","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1frameWidth\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats~1frameWidth\/fragments","value":[{"text":"frameWidth","kind":"identifier"}]}]}]}