{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"metadata":{"symbolKind":"case","externalID":"c:@E@MCSourceType@MCSourceTypeDeckLink","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deckLink"}],"title":"MCSourceType.deckLink","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"MCSourceTypeDeckLink","kind":"identifier"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/deckLink","interfaceLanguage":"swift"},"abstract":[{"text":"DeckLink devices sources (input and output).","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsourcetype\/decklink"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/decklink"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"deckLink","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","role":"symbol","title":"MCSourceType","kind":"symbol","abstract":[{"type":"text","text":"The Source type"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSourceType"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsourcetype","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/deckLink":{"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeDeckLink"}],"url":"\/documentation\/millicastsdk\/mcsourcetype\/decklink","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deckLink"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/deckLink","kind":"symbol","title":"MCSourceType.deckLink","type":"topic","abstract":[{"type":"text","text":"DeckLink devices sources (input and output)."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MCSourceTypeDeckLink","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MCSourceTypeDeckLink","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCSourceTypeDeckLink"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCSourceType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"kind":"identifier","text":"MCSourceType"}]},{"value":"MCSourceTypeDeckLink","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1deckLink\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1deckLink\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSourceTypeDeckLink"}]}]}]}