{"metadata":{"title":"remove(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer","text":"MCAudioRenderer"},{"text":")!)","kind":"text"}],"externalID":"c:objc(cs)MCAudioTrack(im)removeRenderer:","navigatorTitle":[{"kind":"identifier","text":"removeRenderer:"}],"symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/remove(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"text":": (any ","kind":"text"},{"text":"MCAudioRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer"},{"text":")!)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The renderer to remove.","type":"text"}]}],"name":"renderer"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiotrack\/remove(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiotrack\/remove(_:)"]}],"sections":[],"kind":"symbol","abstract":[{"text":"Removes a renderer from the list.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioTrack"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack","title":"MCAudioTrack","abstract":[{"text":"Manages and plays a single audio resource.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioTrack"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/remove(_:)":{"url":"\/documentation\/millicastsdk\/mcaudiotrack\/remove(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/remove(_:)","title":"remove(_:)","role":"symbol","navigatorTitle":[{"text":"removeRenderer:","kind":"identifier"}],"abstract":[{"text":"Removes a renderer from the list.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"((any ","kind":"text"},{"text":"MCAudioRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer"},{"kind":"text","text":")!)"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack/add(_:)":{"url":"\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","title":"add(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"abstract":[{"text":"Adds an audio renderer to render this track.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"MCAudioRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer"},{"kind":"text","text":")!)"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioRenderer":{"title":"MCAudioRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioRenderer","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioRenderer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioRenderer"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiorenderer","abstract":[{"type":"text","text":"This protocol can be implemented to receive audio frames from audio tracks. However,"},{"type":"text","text":" "},{"text":"The recommended method to render audio is to use ","type":"text"},{"type":"codeVoice","code":"MCAudioPlaback"},{"type":"text","text":" instead."},{"type":"text","text":" "},{"text":"See ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","isActive":true,"type":"reference"},{"type":"text","text":" to attach an audio renderer."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"removeRenderer:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRenderer:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeRenderer:"},{"kind":"text","text":"("},{"text":"id<MCAudioRenderer>","preciseIdentifier":"c:Qoobjc(pl)MCAudioRenderer","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"renderer"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/title","value":"MCAudioTrack"},{"value":[{"text":"MCAudioTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1remove(_:)\/title","value":"removeRenderer:"},{"value":[{"text":"- ","kind":"text"},{"text":"removeRenderer:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1remove(_:)\/fragments","op":"replace"},{"op":"replace","value":"addRenderer:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"value":"MCAudioRenderer","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioRenderer\/fragments","op":"replace","value":[{"text":"MCAudioRenderer","kind":"identifier"}]}]}]}