{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainResolution"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainresolution"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainresolution"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maintainResolution","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"On over-use, requests lower frame rate, possibly causing frame drops.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@E@MCDegradationPreferences@MCDegradationPreferencesMaintainResolution","navigatorTitle":[{"text":"MCDegradationPreferencesMaintainResolution","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maintainResolution","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","title":"MCDegradationPreferences.maintainResolution"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDegradationPreferences":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"MCDegradationPreferences","kind":"identifier"}],"abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","isActive":true,"type":"reference"}],"title":"MCDegradationPreferences","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCDegradationPreferences","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcdegradationpreferences"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCDegradationPreferences/maintainResolution":{"abstract":[{"type":"text","text":"On over-use, requests lower frame rate, possibly causing frame drops."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCDegradationPreferences\/maintainResolution","type":"topic","url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/maintainresolution","kind":"symbol","role":"symbol","title":"MCDegradationPreferences.maintainResolution","navigatorTitle":[{"text":"MCDegradationPreferencesMaintainResolution","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maintainResolution","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCDegradationPreferencesMaintainResolution","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainResolution"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"MCDegradationPreferencesMaintainResolution","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCDegradationPreferences","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/title"},{"op":"replace","value":[{"text":"MCDegradationPreferences","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments"},{"op":"replace","value":"MCDegradationPreferencesMaintainResolution","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainResolution\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCDegradationPreferencesMaintainResolution"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCDegradationPreferences~1maintainResolution\/fragments"}]}]}