{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource"]]},"sections":[],"abstract":[{"text":"Checks the current state of the capture process.","type":"text"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","required":true,"modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(pl)CaptureSource(im)isCapturing","title":"isCapturing()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCapturing","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isCapturing","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/isCapturing()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isCapturing","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A boolean value indicating whether the source is currently capturing (true) or not (false)."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/capturesource\/iscapturing()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/capturesource\/iscapturing()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource":{"abstract":[{"text":"Manages the process of capturing the source by input sources, such as a microphone or a camera.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureSource","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource","title":"CaptureSource","url":"\/documentation\/millicastsdk\/capturesource","navigatorTitle":[{"text":"CaptureSource","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource/isCapturing()":{"navigatorTitle":[{"text":"isCapturing","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/isCapturing()","required":true,"abstract":[{"text":"Checks the current state of the capture process.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCapturing"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isCapturing()","url":"\/documentation\/millicastsdk\/capturesource\/iscapturing()","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"isCapturing","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isCapturing","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:b","kind":"typeIdentifier","text":"_Bool"},{"kind":"text","text":") "},{"kind":"identifier","text":"isCapturing"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/title","value":"CaptureSource"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/fragments","value":[{"kind":"identifier","text":"CaptureSource"}],"op":"replace"},{"value":"isCapturing","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1isCapturing()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1isCapturing()\/fragments","value":[{"kind":"text","text":"- "},{"text":"isCapturing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}