{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/videoSize","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"videoSize"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCAcceleratedVideoRenderer(py)videoSize","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"videoSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"title":"videoSize"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/videosize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/videosize"]}],"abstract":[{"text":"The size of the last video frame received.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"videoSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/videoSize":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The size of the last video frame received."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/videoSize","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoSize"}],"title":"videoSize","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/videosize","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"navigatorTitle":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}],"kind":"symbol","title":"MCAcceleratedVideoRenderer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"abstract":[{"text":"Class that renders video frames in a ","type":"text"},{"type":"codeVoice","code":"UIView"},{"text":" or ","type":"text"},{"code":"NSView","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"videoSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"videoSize","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"atomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1videoSize\/title","value":"videoSize"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1videoSize\/fragments","op":"replace","value":[{"text":"videoSize","kind":"identifier"}]},{"value":"MCAcceleratedVideoRenderer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","op":"replace"},{"value":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}