{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:objc(cs)MCRtpStreamStats(py)transport_id","symbolKind":"property","title":"transport_id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transport_id"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"transport_id","kind":"identifier"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/transport_id","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"transport_id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/transport_id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats\/transport_id"]}],"sections":[],"abstract":[{"text":"The transport layer associated with the stream. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid"}],"kind":"symbol","references":{"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-transportid":{"title":"transportId","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid","titleInlineContent":[{"text":"transportId","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/transport_id":{"abstract":[{"text":"The transport layer associated with the stream. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid","type":"reference","isActive":true}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"transport_id","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/transport_id","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/transport_id","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transport_id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"transport_id"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"abstract":[{"type":"text","text":"Statistics for an RTP stream."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRtpStreamStats"}],"title":"MCRtpStreamStats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"transport_id"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"transport_id","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"transport_id","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1transport_id\/title","value":"transport_id","op":"replace"},{"value":[{"text":"transport_id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1transport_id\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title","value":"MCRtpStreamStats","op":"replace"},{"value":[{"kind":"identifier","text":"MCRtpStreamStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","op":"replace"}]}]}