{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer","kind":"typeIdentifier","text":"MCRTSRemoteTrackLayer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Layer data received from the track’s layer event. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"}],"type":"paragraph"}],"name":"layer"}],"kind":"parameters"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Convenience initializer to initialize the values with the"},{"type":"text","text":" "},{"type":"text","text":"remote track layer event if no other modification is required."}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/init(layer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/init(layer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/init(layer:)"},"metadata":{"roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)initWithLayer:","title":"init(layer:)","navigatorTitle":[{"text":"initWithLayer:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer","text":"MCRTSRemoteTrackLayer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/init(layer:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/init(layer:)","navigatorTitle":[{"text":"initWithLayer:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"init(layer:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/init(layer:)","abstract":[{"type":"text","text":"Convenience initializer to initialize the values with the"},{"type":"text","text":" "},{"type":"text","text":"remote track layer event if no other modification is required."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"MCRTSRemoteTrackLayer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","abstract":[{"text":"Represents an layer entry in the layers event received by the media server.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","role":"symbol","abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"text":" ","type":"text"},{"text":"the client wants to inform the media server to select.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"title":"MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithLayer:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLayer:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer","text":"MCRTSRemoteTrackLayer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"layer"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1init(layer:)\/title","value":"initWithLayer:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1init(layer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLayer:"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title","value":"MCRTSRemoteTrackLayer","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","value":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}