{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/fps"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fps","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The frame rate that defines the number of frames per second that the video track should be capable of delivering or receiving."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"fps","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"fps","externalID":"c:objc(cs)MCVideoCapabilities(py)fps","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fps","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/fps"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/fps"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities/fps":{"title":"fps","abstract":[{"type":"text","text":"The frame rate that defines the number of frames per second that the video track should be capable of delivering or receiving."}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities\/fps","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities\/fps","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fps"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fps"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoCapabilities":{"kind":"symbol","abstract":[{"text":"This VideoCapabilities class represents the video capabilities of a video track.","type":"text"}],"navigatorTitle":[{"text":"MCVideoCapabilities","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoCapabilities","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCVideoCapabilities","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities","title":"MCVideoCapabilities","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fps","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fps"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"fps"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1fps\/title","value":"fps"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities~1fps\/fragments","value":[{"text":"fps","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/title","value":"MCVideoCapabilities","op":"replace"},{"op":"replace","value":[{"text":"MCVideoCapabilities","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments"}]}]}