{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"l1t3"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","title":"MCScalabilityMode.l1t3","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL1T3","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"l1t3","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCScalabilityModeL1T3","kind":"identifier"}],"role":"symbol"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"url":"\/documentation\/millicastsdk\/mcscalabilitymode","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"reference","isActive":true},{"text":" to understand where these values come from","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCScalabilityMode","kind":"identifier"}],"title":"MCScalabilityMode"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l1t3":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL1T3"}],"title":"MCScalabilityMode.l1t3","role":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3","abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l1t3"}]},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCScalabilityModeL1T3","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MCScalabilityModeL1T3"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCScalabilityModeL1T3","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"kind":"identifier","text":"MCScalabilityMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3\/title","value":"MCScalabilityModeL1T3"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3\/fragments","value":[{"text":"MCScalabilityModeL1T3","kind":"identifier"}]}]}]}