{"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/get_type()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/get_type()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier","text":"MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"get_type","kind":"identifier"}],"title":"get_type()","externalID":"c:objc(cs)MCInboundRtpStreamStats(cm)get_type","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/get_type()"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"title":"MCInboundRtpStreamStats","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","title":"MCStatsType","abstract":[{"type":"text","text":"Different types of statistics."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats/get_type()":{"navigatorTitle":[{"text":"get_type","kind":"identifier"}],"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/get_type()","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/get_type()","role":"symbol","type":"topic","title":"get_type()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"get_type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"},{"text":") ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/navigatorTitle","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"text":"MCStatsType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/navigatorTitle","value":[{"kind":"identifier","text":"MCStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1get_type()\/title","value":"get_type"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1get_type()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}