{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/min_playout_delay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/min_playout_delay"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"min_playout_delay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"min_playout_delay","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)min_playout_delay","navigatorTitle":[{"text":"min_playout_delay","kind":"identifier"}]},"abstract":[{"text":"The minimum playout delay during video transmission.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"min_playout_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/min_playout_delay","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats/min_playout_delay":{"type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/min_playout_delay","title":"min_playout_delay","kind":"symbol","navigatorTitle":[{"text":"min_playout_delay","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"min_playout_delay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/min_playout_delay","abstract":[{"type":"text","text":"The minimum playout delay during video transmission."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"title":"MCInboundRtpStreamStats","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"min_playout_delay","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"min_playout_delay","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"min_playout_delay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"min_playout_delay","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1min_playout_delay\/title","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1min_playout_delay\/fragments","value":[{"text":"min_playout_delay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/navigatorTitle","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace"}]}]}