{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_pauses_duration"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_pauses_duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_pauses_duration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_pauses_duration"]}],"abstract":[{"text":"Total duration of pauses. See ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","type":"reference","isActive":true}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"metadata":{"navigatorTitle":[{"text":"total_pauses_duration","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_pauses_duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"total_pauses_duration","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)total_pauses_duration","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"title":"MCInboundRtpStreamStats","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic"},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalpausesduration":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","title":"totalPausesDuration","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","type":"link","titleInlineContent":[{"text":"totalPausesDuration","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats/total_pauses_duration":{"navigatorTitle":[{"text":"total_pauses_duration","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_pauses_duration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_pauses_duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"total_pauses_duration","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_pauses_duration","abstract":[{"text":"Total duration of pauses. See ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","type":"reference","isActive":true}],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"total_pauses_duration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"total_pauses_duration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_pauses_duration"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/navigatorTitle","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_pauses_duration\/title","value":"total_pauses_duration","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_pauses_duration\/fragments","value":[{"kind":"identifier","text":"total_pauses_duration"}],"op":"replace"}]}]}