{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"onLogWithMessage:Level:","kind":"identifier"}],"title":"onLog(withMessage:level:)","externalID":"c:objc(pl)MCLoggerDelegate(im)onLogWithMessage:Level:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onLog","kind":"identifier"},{"kind":"text","text":"("},{"text":"withMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"level","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCLogLevel"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"role":"symbol","required":true,"symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLoggerDelegate"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLoggerDelegate\/onLog(withMessage:level:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called whenever a log message is emitted."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"level","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The log message."}],"type":"paragraph"}],"name":"message"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The severity level. For more information, see ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","type":"reference"},{"text":".","type":"text"}]}],"name":"level"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcloggerdelegate\/onlog(withmessage:level:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcloggerdelegate\/onlog(withmessage:level:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLoggerDelegate/onLog(withMessage:level:)":{"url":"\/documentation\/millicastsdk\/mcloggerdelegate\/onlog(withmessage:level:)","navigatorTitle":[{"text":"onLogWithMessage:Level:","kind":"identifier"}],"title":"onLog(withMessage:level:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLog"},{"kind":"text","text":"("},{"text":"withMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"text":": ","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCLogLevel"},{"kind":"text","text":")"}],"abstract":[{"text":"Called whenever a log message is emitted.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLoggerDelegate\/onLog(withMessage:level:)","type":"topic","required":true,"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCLoggerDelegate":{"url":"\/documentation\/millicastsdk\/mcloggerdelegate","navigatorTitle":[{"text":"MCLoggerDelegate","kind":"identifier"}],"title":"MCLoggerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCLoggerDelegate"}],"abstract":[{"type":"text","text":"Delegate that receives events from "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLoggerDelegate","type":"topic","role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"}],"title":"MCLogLevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","kind":"symbol","navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcloglevel","abstract":[{"type":"text","text":"The log message’s level"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogger":{"title":"MCLogger","url":"\/documentation\/millicastsdk\/mclogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCLogger","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger","abstract":[{"text":"Class that is responsible for managing SDK logs.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onLogWithMessage:Level:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onLogWithMessage:Level:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onLogWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"Level:"},{"kind":"text","text":"("},{"text":"MCLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel"},{"text":") ","kind":"text"},{"text":"level","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"onLogWithMessage:Level:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLoggerDelegate~1onLog(withMessage:level:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onLogWithMessage:Level:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLoggerDelegate~1onLog(withMessage:level:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLoggerDelegate\/title","value":"MCLoggerDelegate","op":"replace"},{"value":[{"text":"MCLoggerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLoggerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/fragments","value":[{"kind":"identifier","text":"MCLogLevel"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/title","op":"replace","value":"MCLogger"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/fragments","value":[{"kind":"identifier","text":"MCLogger"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}