{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)frame_height","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frame_height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"frame_height"}],"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"frame_height"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_height","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The height of video frames. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","isActive":true,"type":"reference"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frame_height"]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frame_height"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame_height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"type":"topic","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"title":"MCOutboundRtpStreamStats","navigatorTitle":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"role":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-frameheight":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","title":"frameHeight","titleInlineContent":[{"text":"frameHeight","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCOutboundRtpStreamStats/frame_height":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame_height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[{"text":"The height of video frames. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","type":"reference","isActive":true}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_height","navigatorTitle":[{"text":"frame_height","kind":"identifier"}],"title":"frame_height","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frame_height","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"frame_height"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frame_height"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"text":"unsigned long","preciseIdentifier":"c:l","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame_height"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","op":"replace","value":"MCOutboundRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_height\/title","value":"frame_height","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_height\/fragments","value":[{"text":"frame_height","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}