{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Event received when the underlying WebRTC MID has changed. This can happen"},{"type":"text","text":" "},{"type":"text","text":"in cases of network dropouts or in general when the underlying peer connection has"},{"type":"text","text":" "},{"type":"text","text":"been torn down. In general, keeping the MID handy is useful when parsing "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"},{"type":"text","text":" "},{"type":"text","text":"based on the mid, since each mid corresponds to one track."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateMID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"title":"rtsRemoteTrack(_:didUpdateMID:)","role":"symbol","externalID":"c:objc(pl)MCRTSRemoteTrackDelegate(im)rtsRemoteTrack:didUpdateMID:","navigatorTitle":[{"text":"rtsRemoteTrack:didUpdateMID:","kind":"identifier"}],"required":true},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatemid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatemid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rtsRemoteTrack"},{"kind":"text","text":": "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMID"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"rtsRemoteTrack","content":[{"inlineContent":[{"type":"text","text":"The remote track receiving the mid change."}],"type":"paragraph"}]},{"name":"mid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new mid."}]}]}],"kind":"parameters"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","title":"MCRTSRemoteTrack","abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"kind":"symbol","abstract":[{"text":"A delegate to receive remote track related events.","type":"text"}],"role":"symbol","title":"MCRTSRemoteTrackDelegate","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateMID:)":{"abstract":[{"text":"Event received when the underlying WebRTC MID has changed. This can happen","type":"text"},{"text":" ","type":"text"},{"text":"in cases of network dropouts or in general when the underlying peer connection has","type":"text"},{"text":" ","type":"text"},{"text":"been torn down. In general, keeping the MID handy is useful when parsing ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"reference"},{"text":" ","type":"text"},{"text":"based on the mid, since each mid corresponds to one track.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","required":true,"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didUpdateMID:"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatemid:)","title":"rtsRemoteTrack(_:didUpdateMID:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"role":"symbol","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","kind":"symbol","title":"MCInboundRtpStreamStats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"rtsRemoteTrack:didUpdateMID:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didUpdateMID:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rtsRemoteTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateMID:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mid"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"},{"value":"MCRTSRemoteTrackDelegate","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments"},{"value":"rtsRemoteTrack:didUpdateMID:","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didUpdateMID:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/fragments"},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"op":"replace"}]}]}