{"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate\/didChangeVideoSize(_:)"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"]},{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAcceleratedVideoRendererDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate"]}],"abstract":[{"text":"Protocol that allows subscribing to callbacks that inform about rendering video frame size changes.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"sections":[],"metadata":{"title":"MCAcceleratedVideoRendererDelegate","roleHeading":"Protocol","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(pl)MCAcceleratedVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"symbolKind":"protocol","navigatorTitle":[{"text":"MCAcceleratedVideoRendererDelegate","kind":"identifier"}],"role":"symbol"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRendererDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate","abstract":[{"type":"text","text":"Protocol that allows subscribing to callbacks that inform about rendering video frame size changes."}],"title":"MCAcceleratedVideoRendererDelegate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRendererDelegate/didChangeVideoSize(_:)":{"title":"didChangeVideoSize(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeVideoSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didChangeVideoSize:"}],"abstract":[{"type":"text","text":"Called when the size of the rendered video changes, providing the new size as a CGSize parameter."}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate\/didchangevideosize(_:)","required":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate\/didChangeVideoSize(_:)","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"kind":"symbol","abstract":[{"text":"UIView that uses Metal as a backend for rendering.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"title":"MCAcceleratedVideoUIView","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MCAcceleratedVideoRendererDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCAcceleratedVideoRendererDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate\/didChangeVideoSize(_:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"],"kind":"relationships","type":"conformingTypes"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAcceleratedVideoRendererDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/title","value":"MCAcceleratedVideoRendererDelegate","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate~1didChangeVideoSize(_:)\/title","value":"didChangeVideoSize:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate~1didChangeVideoSize(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeVideoSize:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","value":"MCAcceleratedVideoUIView","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","value":[{"text":"MCAcceleratedVideoUIView","kind":"identifier"}],"op":"replace"}]}]}