{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiorenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiorenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"abstract":[{"type":"text","text":"This protocol can be implemented to receive audio frames from audio tracks. However,"},{"type":"text","text":" "},{"type":"text","text":"The recommended method to render audio is to use "},{"type":"codeVoice","code":"MCAudioPlaback"},{"type":"text","text":" instead."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)"},{"type":"text","text":" to attach an audio renderer."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer\/didReceive(_:)"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"MCAudioRenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioRenderer","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)MCAudioRenderer","navigatorTitle":[{"kind":"identifier","text":"MCAudioRenderer"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioRenderer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioTrack/add(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"MCAudioRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioRenderer"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"title":"add(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Adds an audio renderer to render this track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","url":"\/documentation\/millicastsdk\/mcaudiotrack\/add(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioRenderer":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioRenderer"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioRenderer"}],"abstract":[{"text":"This protocol can be implemented to receive audio frames from audio tracks. However,","type":"text"},{"text":" ","type":"text"},{"text":"The recommended method to render audio is to use ","type":"text"},{"code":"MCAudioPlaback","type":"codeVoice"},{"text":" instead.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioTrack\/add(_:)","type":"reference"},{"text":" to attach an audio renderer.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcaudiorenderer","title":"MCAudioRenderer","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioRenderer/didReceive(_:)":{"title":"didReceive(_:)","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer\/didReceive(_:)","abstract":[{"type":"text","text":"This handler is called when a new audio frame is available."}],"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCAudioFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"didReceiveFrame:","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiorenderer\/didreceive(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCAudioRenderer","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCAudioRenderer","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MCAudioRenderer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioRenderer\/didReceive(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioRenderer"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"addRenderer:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addRenderer:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioTrack~1add(_:)\/fragments","op":"replace"},{"value":"MCAudioRenderer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioRenderer"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer\/fragments","op":"replace"},{"value":"didReceiveFrame:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer~1didReceive(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioRenderer~1didReceive(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}