{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"abstract":[{"text":"Different types of codec statistics.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/decode","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/encode"]},{"title":"Initializers","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecStatsType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsType"}],"title":"MCCodecStatsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecStatsType"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@E@MCCodecStatsType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccodecstatstype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecstatstype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"],"type":"conformsTo"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/millicastsdk\/mccodecstatstype\/rawrepresentable-implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType/init(rawValue:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/millicastsdk\/mccodecstatstype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[]},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY"},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType/decode":{"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/decode","navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccodecstatstype\/decode","title":"MCCodecStatsType.decode","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType":{"type":"topic","abstract":[{"type":"text","text":"Different types of codec statistics."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecStatsType"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType","navigatorTitle":[{"text":"MCCodecStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype","role":"symbol","title":"MCCodecStatsType"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/Equatable-Implementations","url":"\/documentation\/millicastsdk\/mccodecstatstype\/equatable-implementations","kind":"article"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCodecStatsType/encode":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/encode","kind":"symbol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsTypeEncode"}],"title":"MCCodecStatsType.encode","url":"\/documentation\/millicastsdk\/mccodecstatstype\/encode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MCCodecStatsType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCCodecStatsType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCCodecStatsType"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/decode","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCodecStatsType\/encode"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecStatsType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType~1decode\/title","value":"MCCodecStatsTypeDecode","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType~1decode\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType\/title","value":"MCCodecStatsType","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsType"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType~1encode\/title","value":"MCCodecStatsTypeEncode","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCodecStatsType~1encode\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsTypeEncode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}