{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionOptions","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"MCConnectionOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionOptions","kind":"identifier"}],"externalID":"c:objc(cs)MCConnectionOptions","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCConnectionOptions"}],"symbolKind":"class"},"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionOptions","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcconnectionoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcconnectionoptions"]}],"abstract":[{"type":"text","text":"The MCConnectionOptions class gathers connection options."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCConnectionOptions":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionOptions","kind":"symbol","url":"\/documentation\/millicastsdk\/mcconnectionoptions","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionOptions","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionOptions","kind":"identifier"}],"title":"MCConnectionOptions","abstract":[{"type":"text","text":"The MCConnectionOptions class gathers connection options."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/SH":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCConnectionOptions/autoReconnect":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoReconnect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"autoReconnect","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect","abstract":[{"text":"Attempts to reconnect by default in case of connection error or network dropout. Enabled by default","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"autoReconnect"}],"url":"\/documentation\/millicastsdk\/mcconnectionoptions\/autoreconnect","type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MCConnectionOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCConnectionOptions","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCConnectionOptions"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCConnectionOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionOptions\/title","op":"replace","value":"MCConnectionOptions"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionOptions\/fragments","op":"replace","value":[{"text":"MCConnectionOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/title","op":"replace","value":"autoReconnect"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/fragments","op":"replace","value":[{"text":"autoReconnect","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}