{"abstract":[{"text":"Delegate that receives events from ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLoggerDelegate","kind":"identifier"}],"roleHeading":"Protocol","modules":[{"name":"MillicastSDK"}],"title":"MCLoggerDelegate","externalID":"c:objc(pl)MCLoggerDelegate","symbolKind":"protocol","navigatorTitle":[{"text":"MCLoggerDelegate","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate\/onLog(withMessage:level:)"]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcloggerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcloggerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLoggerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogger","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Class that is responsible for managing SDK logs."}],"url":"\/documentation\/millicastsdk\/mclogger","kind":"symbol","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}],"title":"MCLogger"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLoggerDelegate/onLog(withMessage:level:)":{"kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onLogWithMessage:Level:"}],"title":"onLog(withMessage:level:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate\/onLog(withMessage:level:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLog"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCLogLevel","text":"MCLogLevel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called whenever a log message is emitted."}],"type":"topic","url":"\/documentation\/millicastsdk\/mcloggerdelegate\/onlog(withmessage:level:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLoggerDelegate":{"title":"MCLoggerDelegate","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLoggerDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLoggerDelegate"}],"abstract":[{"text":"Delegate that receives events from ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger","type":"reference"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcloggerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCLoggerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCLoggerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCLoggerDelegate"}]},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate\/onLog(withMessage:level:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLoggerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCLogger","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCLogger"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/fragments","op":"replace"},{"value":"onLogWithMessage:Level:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate~1onLog(withMessage:level:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onLogWithMessage:Level:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate~1onLog(withMessage:level:)\/fragments","op":"replace"},{"value":"MCLoggerDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate\/title","op":"replace"},{"value":[{"text":"MCLoggerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}