{"sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/debug","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/error","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/log","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/off","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/verbose","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The log message’s level"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogLevel","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcloglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcloglevel"]}],"metadata":{"externalID":"c:@E@MCLogLevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCLogLevel"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"}],"modules":[{"name":"MillicastSDK"}],"title":"MCLogLevel","symbolKind":"enum"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel":{"url":"\/documentation\/millicastsdk\/mcloglevel","title":"MCLogLevel","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCLogLevel"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"}],"abstract":[{"text":"The log message’s level","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/off":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Logs disabled. This is only used with "},{"type":"codeVoice","code":"MCLogger\/setDelegate"}],"title":"MCLogLevel.off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"off"}],"navigatorTitle":[{"kind":"identifier","text":"MCLogLevelOff"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/off","url":"\/documentation\/millicastsdk\/mcloglevel\/off","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/debug":{"navigatorTitle":[{"text":"MCLogLevelDebug","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/debug","kind":"symbol","title":"MCLogLevel.debug","type":"topic","abstract":[{"type":"text","text":"Debug message."}],"url":"\/documentation\/millicastsdk\/mcloglevel\/debug","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/millicastsdk\/mcloglevel\/rawrepresentable-implementations"},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/verbose":{"title":"MCLogLevel.verbose","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/verbose","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"navigatorTitle":[{"text":"MCLogLevelVerbose","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcloglevel\/verbose","kind":"symbol","abstract":[{"text":"Very verbose log message.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/error":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"navigatorTitle":[{"kind":"identifier","text":"MCLogLevelError"}],"url":"\/documentation\/millicastsdk\/mcloglevel\/error","abstract":[{"type":"text","text":"When an error occured."}],"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/error","title":"MCLogLevel.error"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/millicastsdk\/mcloglevel\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/init(rawValue:)","role":"symbol","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/millicastsdk\/mcloglevel\/equatable-implementations","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/warning":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"navigatorTitle":[{"text":"MCLogLevelWarning","kind":"identifier"}],"title":"MCLogLevel.warning","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel\/warning","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/warning","abstract":[{"type":"text","text":"Warn the user about something, but does not prevent a normal utilisation."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel/log":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcloglevel\/log","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/log","abstract":[{"type":"text","text":"General info about what happens and which steps are performed."}],"title":"MCLogLevel.log","role":"symbol","navigatorTitle":[{"text":"MCLogLevelLog","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCLogLevel","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCLogLevel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MCLogLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/debug","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/error","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/log","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/off","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/verbose","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel\/warning"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCLogLevel","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/title"},{"op":"replace","value":[{"text":"MCLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/fragments"},{"op":"replace","value":"MCLogLevelOff","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1off\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCLogLevelOff"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1off\/fragments"},{"op":"replace","value":"MCLogLevelDebug","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1debug\/title"},{"op":"replace","value":[{"text":"MCLogLevelDebug","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1debug\/fragments"},{"op":"replace","value":"MCLogLevelVerbose","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1verbose\/title"},{"op":"replace","value":[{"text":"MCLogLevelVerbose","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1verbose\/fragments"},{"op":"replace","value":"MCLogLevelError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1error\/title"},{"op":"replace","value":[{"text":"MCLogLevelError","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1error\/fragments"},{"op":"replace","value":"MCLogLevelWarning","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1warning\/title"},{"op":"replace","value":[{"text":"MCLogLevelWarning","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1warning\/fragments"},{"op":"replace","value":"MCLogLevelLog","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1log\/title"},{"op":"replace","value":[{"text":"MCLogLevelLog","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel~1log\/fragments"}]}]}