{"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/audio","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/video"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremotetrackkind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremotetrackkind"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"abstract":[{"text":"Enum specifying the type of the remote track.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteTrackKind","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRemoteTrackKind"}],"role":"symbol","symbolKind":"enum","modules":[{"name":"MillicastSDK"}],"roleHeading":"Enumeration","title":"MCRemoteTrackKind","externalID":"c:@E@MCRemoteTrackKind","navigatorTitle":[{"kind":"identifier","text":"MCRemoteTrackKind"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/video":{"kind":"symbol","title":"MCRemoteTrackKind.video","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/video","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MCRemoteTrackKindVideo","kind":"identifier"}],"abstract":[{"text":"Track is a video track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind\/video"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/RawRepresentable-Implementations":{"url":"\/documentation\/millicastsdk\/mcremotetrackkind\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/Equatable-Implementations":{"url":"\/documentation\/millicastsdk\/mcremotetrackkind\/equatable-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/Equatable-Implementations","abstract":[],"kind":"article","title":"Equatable Implementations"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind":{"kind":"symbol","navigatorTitle":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","abstract":[{"type":"text","text":"Enum specifying the type of the remote track."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind","type":"topic","title":"MCRemoteTrackKind","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteTrackKind","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"},"doc://io.cosmosoftware.millicast.sdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcremotetrackkind\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/init(rawValue:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteTrackKind/audio":{"navigatorTitle":[{"text":"MCRemoteTrackKindAudio","kind":"identifier"}],"abstract":[{"text":"Track is an audio track.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcremotetrackkind\/audio","title":"MCRemoteTrackKind.audio","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/audio","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCRemoteTrackKind","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/audio","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteTrackKind\/video"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRemoteTrackKind"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCRemoteTrackKindVideo","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1video\/title"},{"value":[{"kind":"identifier","text":"MCRemoteTrackKindVideo"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1video\/fragments"},{"value":"MCRemoteTrackKind","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title"},{"value":[{"kind":"identifier","text":"MCRemoteTrackKind"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments"},{"value":"MCRemoteTrackKindAudio","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1audio\/title"},{"value":[{"kind":"identifier","text":"MCRemoteTrackKindAudio"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteTrackKind~1audio\/fragments"}]}]}