{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/local_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/media_source_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_timestamp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/reports_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time_measurements","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/total_round_trip_time"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/get_type()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"kind":"symbol","abstract":[{"text":"Statistics related to an outgoing remote RTP stream.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"metadata":{"role":"symbol","externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats","title":"MCRemoteOutboundRtpStreamStats","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/media_source_id":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/media_source_id","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"media_source_id","kind":"identifier"}],"title":"media_source_id","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"media_source_id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/media_source_id","abstract":[{"type":"text","text":"The identifier of the media source associated with the outbound RTP stream."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/local_id":{"role":"symbol","navigatorTitle":[{"text":"local_id","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/local_id","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/local_id","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"local_id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The local identifier associated with the outbound RTP stream. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid","type":"reference","isActive":true}],"title":"local_id"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","abstract":[{"text":"Statistics related to an outgoing remote RTP stream.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"type":"topic","role":"symbol","kind":"symbol","title":"MCRemoteOutboundRtpStreamStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/round_trip_time_measurements":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time_measurements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time_measurements","title":"round_trip_time_measurements","role":"symbol","abstract":[{"type":"text","text":"The number of round-trip time measurements taken. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptimemeasurements","type":"reference","isActive":true}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/round_trip_time_measurements","navigatorTitle":[{"kind":"identifier","text":"round_trip_time_measurements"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-roundtriptimemeasurements":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptimemeasurements","title":"roundTripTimeMeasurements","titleInlineContent":[{"type":"text","text":"roundTripTimeMeasurements"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptimemeasurements","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","title":"remoteTimestamp","titleInlineContent":[{"type":"text","text":"remoteTimestamp"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-localid":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid","title":"localId","titleInlineContent":[{"type":"text","text":"localId"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-localid","type":"link"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/remote_id":{"abstract":[{"type":"text","text":"The remote endpoint or destination of the outbound RTP stream."}],"navigatorTitle":[{"kind":"identifier","text":"remote_id"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remote_id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_id","kind":"symbol","type":"topic","title":"remote_id","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_id"},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime":{"title":"totalRoundTripTime","titleInlineContent":[{"type":"text","text":"totalRoundTripTime"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-reportssent":{"title":"reportsSent","titleInlineContent":[{"type":"text","text":"reportsSent"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-reportssent","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-reportssent"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/total_round_trip_time":{"abstract":[{"text":"The sum of round-trip times for packets sent between endpoints. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-totalroundtriptime","type":"reference"}],"kind":"symbol","title":"total_round_trip_time","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/total_round_trip_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","navigatorTitle":[{"text":"total_round_trip_time","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/total_round_trip_time","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/reports_sent":{"title":"reports_sent","role":"symbol","navigatorTitle":[{"text":"reports_sent","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/reports_sent","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/reports_sent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reports_sent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"abstract":[{"text":"The number of reports sent for monitoring the outbound stream. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-reportssent"}],"kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/remote_timestamp":{"abstract":[{"type":"text","text":"The timestamp of the remote endpoint related to the stream. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-remotetimestamp"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remote_timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"remote_timestamp"}],"title":"remote_timestamp","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_timestamp","role":"symbol","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_timestamp"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime":{"title":"roundTripTime","titleInlineContent":[{"type":"text","text":"roundTripTime"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSentRtpStreamStats":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats","abstract":[{"type":"text","text":"Statistics related to an outgoing RTP stream."}],"role":"symbol","title":"MCSentRtpStreamStats","url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSentRtpStreamStats"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/get_type()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/get_type()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/get_type()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"type":"topic","title":"get_type()","abstract":[{"text":"Returns the type of statistics.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/round_trip_time":{"kind":"symbol","abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteoutboundrtpstreamstats-roundtriptime"}],"type":"topic","title":"round_trip_time","navigatorTitle":[{"kind":"identifier","text":"round_trip_time"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCRemoteOutboundRtpStreamStats","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/local_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/media_source_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_timestamp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/reports_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/round_trip_time_measurements","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/total_round_trip_time"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/get_type()"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MCSentRtpStreamStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSentRtpStreamStats"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"media_source_id","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1media_source_id\/title"},{"op":"replace","value":[{"text":"media_source_id","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1media_source_id\/fragments"},{"op":"replace","value":"local_id","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1local_id\/title"},{"op":"replace","value":[{"text":"local_id","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1local_id\/fragments"},{"op":"replace","value":"MCRemoteOutboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"},{"op":"replace","value":"round_trip_time_measurements","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time_measurements\/title"},{"op":"replace","value":[{"text":"round_trip_time_measurements","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time_measurements\/fragments"},{"op":"replace","value":"remote_id","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_id\/title"},{"op":"replace","value":[{"kind":"identifier","text":"remote_id"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_id\/fragments"},{"op":"replace","value":"total_round_trip_time","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1total_round_trip_time\/title"},{"op":"replace","value":[{"text":"total_round_trip_time","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1total_round_trip_time\/fragments"},{"op":"replace","value":"reports_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1reports_sent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"reports_sent"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1reports_sent\/fragments"},{"op":"replace","value":"remote_timestamp","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_timestamp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"remote_timestamp"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_timestamp\/fragments"},{"op":"replace","value":"MCSentRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments"},{"op":"replace","value":"get_type","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1get_type()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1get_type()\/fragments"},{"op":"replace","value":"round_trip_time","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time\/title"},{"op":"replace","value":[{"text":"round_trip_time","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1round_trip_time\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}