{"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)"],"title":"Instance Methods"}],"metadata":{"symbolKind":"protocol","externalID":"c:objc(pl)MCRTSRemoteTrackDelegate","roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCRTSRemoteTrackDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackInactive(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrackInactive:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)","title":"rtsRemoteTrackInactive(_:)","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackinactive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrackInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Event received when the track, i.e. it’s publishing source, has become inactive."},{"type":"text","text":" "},{"type":"text","text":"In other words the publishers stream is no longer being sent to the server and is"},{"type":"text","text":" "},{"type":"text","text":"thus no longer viewable on the viewing client. The track is not disabled by the SDK"},{"type":"text","text":" "},{"type":"text","text":"when this event occurs. If the application wants to ensure the track will not"},{"type":"text","text":" "},{"type":"text","text":"automatically be played once the source becomes active it should call disable() when"},{"type":"text","text":" "},{"type":"text","text":"receiving this event. Then it is responsible for calling enable() on the Active event."},{"text":" ","type":"text"},{"text":"If the application does not disable on Inactive event, the track will automatically start","type":"text"},{"text":" ","type":"text"},{"text":"playing when the remote source becomes Active.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"title":"MCRTSRemoteTrackDelegate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didReceiveTrackStats:)":{"navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didReceiveTrackStats:"}],"abstract":[{"type":"text","text":"Event received when a new Track statistics report is available."}],"role":"symbol","title":"rtsRemoteTrack(_:didReceiveTrackStats:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveTrackStats"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats","text":"MCTrackStats"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didreceivetrackstats:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateLayers:)":{"abstract":[{"text":"Event received when there is Simulcast\/SVC layers available for the remote track. Only","type":"text"},{"type":"text","text":" "},{"type":"text","text":"available for video tracks."}],"title":"rtsRemoteTrack(_:didUpdateLayers:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatelayers:)","navigatorTitle":[{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLayers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateMID:)":{"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatemid:)","required":true,"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtsRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","navigatorTitle":[{"kind":"identifier","text":"rtsRemoteTrack:didUpdateMID:"}],"abstract":[{"type":"text","text":"Event received when the underlying WebRTC MID has changed. This can happen"},{"type":"text","text":" "},{"type":"text","text":"in cases of network dropouts or in general when the underlying peer connection has"},{"type":"text","text":" "},{"type":"text","text":"been torn down. In general, keeping the MID handy is useful when parsing "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","isActive":true,"type":"reference"},{"type":"text","text":" "},{"type":"text","text":"based on the mid, since each mid corresponds to one track."}],"title":"rtsRemoteTrack(_:didUpdateMID:)","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","title":"MCInboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackActive(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":")","kind":"text"}],"type":"topic","title":"rtsRemoteTrackActive(_:)","navigatorTitle":[{"text":"rtsRemoteTrackActive:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackactive(_:)","required":true,"role":"symbol","kind":"symbol","abstract":[{"text":"Event received when the track, i.e. it’s publishing source, has become active.","type":"text"},{"text":" ","type":"text"},{"text":"In other words the stream is being sent to the server and is viable on the viewing","type":"text"},{"text":" ","type":"text"},{"text":"client. The track is not enabled by default. The application can still call","type":"text"},{"text":" ","type":"text"},{"text":"disable() on this track to prevent it from being played. If the track","type":"text"},{"text":" ","type":"text"},{"text":"was previously disabled, the application must call enable() for the track","type":"text"},{"text":" ","type":"text"},{"text":"to be renderable. If the track was previously enabled by the application and is not","type":"text"},{"text":" ","type":"text"},{"text":"disabled by the application it will automatically start playing once it becomes","type":"text"},{"text":" ","type":"text"},{"text":"active.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCRTSRemoteTrackDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didReceiveTrackStats:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateMID:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackActive(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"rtsRemoteTrackInactive:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrackInactive:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/fragments"},{"op":"replace","value":"MCRTSRemoteTrackDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments"},{"op":"replace","value":"rtsRemoteTrack:didReceiveTrackStats:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrack:didReceiveTrackStats:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didReceiveTrackStats:)\/fragments"},{"op":"replace","value":"rtsRemoteTrack:didUpdateLayers:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/fragments"},{"op":"replace","value":"rtsRemoteTrack:didUpdateMID:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrack:didUpdateMID:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateMID:)\/fragments"},{"op":"replace","value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"},{"op":"replace","value":"rtsRemoteTrackActive:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrackActive:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackActive(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}