{"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"externalID":"c:@E@MCVideoType","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"symbolKind":"enum","role":"symbol","title":"MCVideoType"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I210","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I420","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I444","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/argb","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/bgra","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/iyuv","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/mjpeg","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/native","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/nv12","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb24","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb565","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/unkown","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/uyvy","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yuy2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yv12"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"],"title":"Conforms To"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/mjpeg":{"type":"topic","title":"MCVideoType.mjpeg","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mjpeg","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/mjpeg","role":"symbol","navigatorTitle":[{"text":"MCVideoTypeMJPEG","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/mjpeg","kind":"symbol","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/rgb24":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb24","title":"MCVideoType.rgb24","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgb24"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeRGB24"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideotype\/rgb24","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/iyuv":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeIYUV"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/iyuv","url":"\/documentation\/millicastsdk\/mcvideotype\/iyuv","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iyuv"}],"title":"MCVideoType.iyuv","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/uyvy":{"type":"topic","title":"MCVideoType.uyvy","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/uyvy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uyvy"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeUYVY"}],"role":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mcvideotype\/uyvy"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcvideotype\/equatable-implementations","role":"collectionGroup","kind":"article"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/init(rawValue:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcvideotype\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/I444":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I444","navigatorTitle":[{"text":"MCVideoTypeI444","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/i444","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"I444","kind":"identifier"}],"type":"topic","role":"symbol","title":"MCVideoType.I444"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/yv12":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"yv12"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/yv12","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeYV12"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yv12","title":"MCVideoType.yv12","kind":"symbol","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/yuy2":{"title":"MCVideoType.yuy2","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"yuy2"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/yuy2","kind":"symbol","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yuy2","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeYUY2"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/native":{"navigatorTitle":[{"text":"MCVideoTypeNative","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype\/native","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/native","abstract":[],"type":"topic","title":"MCVideoType.native","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/RawRepresentable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/millicastsdk\/mcvideotype\/rawrepresentable-implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/SY":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/rgb565":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgb565"}],"title":"MCVideoType.rgb565","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb565","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeRGB565"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/rgb565","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/I420":{"title":"MCVideoType.I420","navigatorTitle":[{"text":"MCVideoTypeI420","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/i420","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"I420","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I420","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/I210":{"abstract":[],"title":"MCVideoType.I210","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MCVideoTypeI210","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I210","url":"\/documentation\/millicastsdk\/mcvideotype\/i210","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"I210","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","title":"MCVideoType","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/nv12":{"role":"symbol","title":"MCVideoType.nv12","url":"\/documentation\/millicastsdk\/mcvideotype\/nv12","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/nv12","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nv12"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeNV12"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/bgra":{"url":"\/documentation\/millicastsdk\/mcvideotype\/bgra","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/bgra","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeBGRA"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgra"}],"title":"MCVideoType.bgra"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/argb":{"url":"\/documentation\/millicastsdk\/mcvideotype\/argb","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"argb"}],"title":"MCVideoType.argb","abstract":[],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/argb","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeARGB"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/unkown":{"abstract":[],"url":"\/documentation\/millicastsdk\/mcvideotype\/unkown","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unkown","kind":"identifier"}],"title":"MCVideoType.unkown","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/unkown","navigatorTitle":[{"text":"MCVideoTypeUnkown","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MCVideoType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCVideoType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCVideoType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I210","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I420","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/I444","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/argb","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/bgra","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/iyuv","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/mjpeg","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/native","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/nv12","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb24","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb565","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/unkown","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/uyvy","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yuy2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yv12"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1mjpeg\/title","value":"MCVideoTypeMJPEG","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1mjpeg\/fragments","value":[{"text":"MCVideoTypeMJPEG","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb24\/title","value":"MCVideoTypeRGB24","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb24\/fragments","value":[{"text":"MCVideoTypeRGB24","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1iyuv\/title","value":"MCVideoTypeIYUV","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1iyuv\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeIYUV"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1uyvy\/title","value":"MCVideoTypeUYVY","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1uyvy\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeUYVY"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I444\/title","value":"MCVideoTypeI444","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I444\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeI444"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yv12\/title","value":"MCVideoTypeYV12","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yv12\/fragments","value":[{"text":"MCVideoTypeYV12","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yuy2\/title","value":"MCVideoTypeYUY2","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yuy2\/fragments","value":[{"text":"MCVideoTypeYUY2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1native\/title","value":"MCVideoTypeNative","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1native\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeNative"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb565\/title","value":"MCVideoTypeRGB565","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb565\/fragments","value":[{"text":"MCVideoTypeRGB565","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I420\/title","value":"MCVideoTypeI420","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I420\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeI420"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I210\/title","value":"MCVideoTypeI210","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1I210\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeI210"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments","value":[{"text":"MCVideoType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1nv12\/title","value":"MCVideoTypeNV12","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1nv12\/fragments","value":[{"text":"MCVideoTypeNV12","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1bgra\/title","value":"MCVideoTypeBGRA","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1bgra\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeBGRA"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1argb\/title","value":"MCVideoTypeARGB","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1argb\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeARGB"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1unkown\/title","value":"MCVideoTypeUnkown","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1unkown\/fragments","value":[{"kind":"identifier","text":"MCVideoTypeUnkown"}],"op":"replace"}]}]}