{"variants":[{"paths":["\/documentation\/millicastsdk\/mcappsharesource\/startcapture(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcappsharesource\/startcapture(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource\/startCapture(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"text":"Start capturing the application screen.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"c:objc(cs)MCVideoTrack","kind":"typeIdentifier","text":"MCVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"},{"text":"?, (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"handler that is invoked when the result is ready.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The capture process produces an audio track and a video track if successful. See"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my"},{"type":"text","text":" and"},{"type":"text","text":" "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","type":"reference","isActive":true},{"type":"text","text":" to attach"},{"text":" ","type":"text"},{"type":"text","text":"those tracks to a publisher."}]}]}]}],"metadata":{"title":"startCapture(completionHandler:)","role":"symbol","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":"?, "},{"text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack","kind":"typeIdentifier"},{"kind":"text","text":"?, (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startCaptureWithCompletionHandler:"}],"externalID":"c:objc(cs)MCAppShareSource(im)startCaptureWithCompletionHandler:","roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAppShareSource/startCapture(completionHandler:)":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource\/startCapture(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)MCAudioTrack","text":"MCAudioTrack","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"MCVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"text":"?, (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"startCapture(completionHandler:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcappsharesource\/startcapture(completionhandler:)","abstract":[{"type":"text","text":"Start capturing the application screen."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCaptureWithCompletionHandler:"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoTrack"}],"navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","role":"symbol","type":"topic","abstract":[{"text":"Responsible for managing video capture session from a video source.","type":"text"}],"title":"MCVideoTrack","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-340my":{"title":"addTrack(with:completionHandler:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Adds an audio track to the publisher. See ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","type":"reference","isActive":true},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing an audio device track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-6d3yp":{"type":"topic","abstract":[{"text":"Adds a video track to the publisher. See ","type":"text"},{"type":"codeVoice","code":"MCVideoSource\/startCapture"},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing a video device track.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","navigatorTitle":[{"kind":"identifier","text":"addTrackWithVideoTrack:completionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"MCVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","title":"addTrack(with:completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp"},"doc://MillicastSDK/documentation/MillicastSDK/MCAppShareSource":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}],"url":"\/documentation\/millicastsdk\/mcappsharesource","role":"symbol","kind":"symbol","abstract":[{"text":"Uses Replaykit to capture the screen of the application.","type":"text"}],"title":"MCAppShareSource","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAppShareSource","navigatorTitle":[{"text":"MCAppShareSource","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack":{"abstract":[{"text":"Manages and plays a single audio resource.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCAudioTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCAudioTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudiotrack","title":"MCAudioTrack","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource/startCapture()":{"title":"startCapture()","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}],"abstract":[{"type":"text","text":"Initiates the audio capture process from the current source."}],"navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startCaptureWithCompletionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"startCaptureWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startCaptureWithCompletionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"audioTrack"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)MCVideoTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","text":"MCVideoTrack"},{"kind":"text","text":" * "},{"text":"videoTrack","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"startCaptureWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource~1startCapture(completionHandler:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource~1startCapture(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startCaptureWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title","op":"replace","value":"MCVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCVideoTrack"}]},{"value":"addTrackWithAudioTrack:completionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"op":"replace"},{"value":"addTrackWithVideoTrack:completionHandler:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/fragments","value":[{"kind":"text","text":"- "},{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}]},{"value":"MCAppShareSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource\/title"},{"value":[{"text":"MCAppShareSource","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAppShareSource\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/title","value":"MCAudioTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/fragments","value":[{"text":"MCAudioTrack","kind":"identifier"}],"op":"replace"},{"value":"startCapture","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments"}]}]}