{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1"]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"l2t1","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","title":"MCScalabilityMode.l2t1","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t1","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCScalabilityModeL2T1","kind":"identifier"}],"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL2T1"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l2t1":{"title":"MCScalabilityMode.l2t1","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"l2t1"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T1"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","title":"the WebRTC standard"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"text":" to understand where these values come from","type":"text"}],"role":"symbol","title":"MCScalabilityMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","url":"\/documentation\/millicastsdk\/mcscalabilitymode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MCScalabilityModeL2T1","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeL2T1","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MCScalabilityModeL2T1","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1\/title","value":"MCScalabilityModeL2T1"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeL2T1"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace"}]}]}