{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t2h","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2h","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"l2t2h","kind":"identifier"}],"role":"symbol","title":"MCScalabilityMode.l2t2h","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL2T2h"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2h"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2h"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"text":" to understand where these values come from","type":"text"}],"role":"symbol","title":"MCScalabilityMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","url":"\/documentation\/millicastsdk\/mcscalabilitymode"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"title":"the WebRTC standard","type":"link","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l2t2h":{"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2h","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"l2t2h","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2h","title":"MCScalabilityMode.l2t2h","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCScalabilityModeL2T2h"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"value":"MCScalabilityModeL2T2h","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2h\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2h\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}