{"metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"role":"symbol","title":"isPlaying()","externalID":"c:objc(cs)MCAudioPlayback(im)isPlaying","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaying"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/isPlaying()"},"abstract":[{"text":"Checks whether the playback device is playing.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPlaying"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"True if the device is playing, false otherwise."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayback\/isplaying()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudioplayback\/isplaying()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback/isPlaying()":{"title":"isPlaying()","url":"\/documentation\/millicastsdk\/mcaudioplayback\/isplaying()","abstract":[{"text":"Checks whether the playback device is playing.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/isPlaying()","navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isPlaying","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"title":"MCAudioPlayback","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayback","kind":"identifier"}],"abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"type":"text","text":" "},{"type":"text","text":"This class inherits the Source class, however this is not"},{"text":" ","type":"text"},{"text":"a capture source.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback","role":"symbol","navigatorTitle":[{"text":"MCAudioPlayback","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"isPlaying","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isPlaying","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"_Bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isPlaying"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isPlaying","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1isPlaying()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isPlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1isPlaying()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","op":"replace","value":"MCAudioPlayback"},{"op":"replace","value":[{"text":"MCAudioPlayback","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments"}]}]}