{"metadata":{"externalID":"c:objc(cs)MCPublisherCredentials(py)apiUrl","role":"symbol","title":"apiUrl","navigatorTitle":[{"kind":"identifier","text":"apiUrl"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiUrl"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/apiUrl","interfaceLanguage":"swift"},"abstract":[{"text":"The publish API URL.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiUrl","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/apiurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublishercredentials\/apiurl"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials/apiUrl":{"title":"apiUrl","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials\/apiUrl","kind":"symbol","abstract":[{"type":"text","text":"The publish API URL."}],"url":"\/documentation\/millicastsdk\/mcpublishercredentials\/apiurl","navigatorTitle":[{"text":"apiUrl","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherCredentials":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherCredentials","title":"MCPublisherCredentials","abstract":[{"text":"The Credentials interface represents the credentials required for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"connecting the publisher to the streaming platform and publishing a stream."},{"type":"text","text":" "},{"type":"text","text":"Refer to the "},{"isActive":true,"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html"},{"text":" for this information.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCPublisherCredentials"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCPublisherCredentials"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublishercredentials","kind":"symbol"},"https://dash.millicast.com/docs.html":{"url":"https:\/\/dash.millicast.com\/docs.html","titleInlineContent":[{"text":"streaming dashboard","type":"text"}],"title":"streaming dashboard","identifier":"https:\/\/dash.millicast.com\/docs.html","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"apiUrl"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"apiUrl","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"apiUrl"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1apiUrl\/title","value":"apiUrl"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials~1apiUrl\/fragments","value":[{"text":"apiUrl","kind":"identifier"}]},{"value":"MCPublisherCredentials","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherCredentials\/fragments","value":[{"kind":"identifier","text":"MCPublisherCredentials"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}