{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)MCRTSRemoteTrack(im)asVideo","title":"asVideo()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asVideo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"asVideo","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MillicastSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asVideo()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asVideo"},{"kind":"text","text":"() -> "},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Nil if the track is not of a video type"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/asvideo()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/asvideo()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"type":"text","text":" "},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/asVideo()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asVideo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/asVideo()","title":"asVideo()","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/asvideo()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asVideo"}],"abstract":[{"type":"text","text":"Cast the track to it’s true type if it is video, otherwise, nil will be returned."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"asVideo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asVideo"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"asVideo"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}]},{"value":"asVideo","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asVideo()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asVideo","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1asVideo()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]}]}]}