{"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetbitrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetbitrate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetBitrate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"targetBitrate","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)MCRTSRemoteTrackLayer(py)targetBitrate","role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","title":"targetBitrate","navigatorTitle":[{"kind":"identifier","text":"targetBitrate"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetBitrate"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/targetBitrate":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"targetBitrate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/targetBitrate","abstract":[],"type":"topic","kind":"symbol","role":"symbol","title":"targetBitrate","navigatorTitle":[{"kind":"identifier","text":"targetBitrate"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/targetbitrate"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"type":"topic","title":"MCRTSRemoteTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"abstract":[{"text":"Represents an layer entry in the layers event received by the media server.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"targetBitrate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"targetBitrate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"targetBitrate","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetBitrate\/title","value":"targetBitrate"},{"value":[{"text":"targetBitrate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1targetBitrate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title","value":"MCRTSRemoteTrackLayer"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","op":"replace","value":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}