{"sections":[],"abstract":[{"text":"The number of video frames assembled from multiple packets. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets","isActive":true,"type":"reference"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frames_assembled_from_multiple_packets","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_assembled_from_multiple_packets","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_assembled_from_multiple_packets"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_assembled_from_multiple_packets"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"frames_assembled_from_multiple_packets"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frames_assembled_from_multiple_packets","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"frames_assembled_from_multiple_packets","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)frames_assembled_from_multiple_packets","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frames_assembled_from_multiple_packets":{"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_assembled_from_multiple_packets","navigatorTitle":[{"kind":"identifier","text":"frames_assembled_from_multiple_packets"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frames_assembled_from_multiple_packets","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_assembled_from_multiple_packets","title":"frames_assembled_from_multiple_packets","abstract":[{"type":"text","text":"The number of video frames assembled from multiple packets. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets":{"type":"link","title":"framesAssembledFromMultiplePackets","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets","titleInlineContent":[{"type":"text","text":"framesAssembledFromMultiplePackets"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"frames_assembled_from_multiple_packets","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frames_assembled_from_multiple_packets"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","text":"unsigned long","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_assembled_from_multiple_packets"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_assembled_from_multiple_packets\/title","op":"replace","value":"frames_assembled_from_multiple_packets"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_assembled_from_multiple_packets\/fragments","op":"replace","value":[{"text":"frames_assembled_from_multiple_packets","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace","value":"MCInboundRtpStreamStats"},{"value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace"}]}]}