{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_minimum_delay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_minimum_delay"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitter_buffer_minimum_delay"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"abstract":[{"type":"text","text":"The minimum delay configured for the jitter buffer. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1"}],"metadata":{"symbolKind":"property","title":"jitter_buffer_minimum_delay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"jitter_buffer_minimum_delay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)jitter_buffer_minimum_delay","modules":[{"name":"MillicastSDK"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_minimum_delay","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_minimum_delay":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_minimum_delay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jitter_buffer_minimum_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}],"title":"jitter_buffer_minimum_delay","abstract":[{"type":"text","text":"The minimum delay configured for the jitter buffer. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1","isActive":true,"type":"reference"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_minimum_delay"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1","url":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1","type":"link","title":"jitterBufferMinimumDelay","titleInlineContent":[{"text":"jitterBufferMinimumDelay","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"jitter_buffer_minimum_delay","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"jitter_buffer_minimum_delay","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_minimum_delay\/title","value":"jitter_buffer_minimum_delay","op":"replace"},{"value":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_minimum_delay\/fragments"},{"value":"MCInboundRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]}]}]}