{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_samples_received","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_samples_received"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_samples_received"]}],"abstract":[{"text":"The total number of audio samples received. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived","isActive":true,"type":"reference"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)total_samples_received","title":"total_samples_received","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"total_samples_received","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"total_samples_received"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_received"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalsamplesreceived":{"type":"link","title":"totalSamplesReceived","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived","titleInlineContent":[{"type":"text","text":"totalSamplesReceived"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_samples_received":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_samples_received","abstract":[{"type":"text","text":"The total number of audio samples received. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived"}],"title":"total_samples_received","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_received","navigatorTitle":[{"kind":"identifier","text":"total_samples_received"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_samples_received","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"total_samples_received","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"total_samples_received"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","text":"unsigned long","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"total_samples_received","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_received\/title","value":"total_samples_received"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_received\/fragments","value":[{"kind":"identifier","text":"total_samples_received"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace","value":"MCInboundRtpStreamStats"},{"op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}