{"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"total_audio_energy","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_audio_energy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_audio_energy"]}],"kind":"symbol","metadata":{"symbolKind":"property","title":"total_audio_energy","roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)total_audio_energy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"total_audio_energy"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"total_audio_energy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_audio_energy","interfaceLanguage":"swift"},"abstract":[{"text":"The total energy of the audio stream. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalaudioenergy":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","titleInlineContent":[{"type":"text","text":"totalAudioEnergy"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","title":"totalAudioEnergy","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"title":"MCInboundRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_audio_energy":{"title":"total_audio_energy","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_audio_energy","kind":"symbol","abstract":[{"type":"text","text":"The total energy of the audio stream. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","type":"reference"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"total_audio_energy"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_audio_energy","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"total_audio_energy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"total_audio_energy","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"total_audio_energy"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"total_audio_energy","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats"},{"value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","op":"replace"},{"op":"replace","value":"total_audio_energy","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_audio_energy\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_audio_energy\/fragments","value":[{"text":"total_audio_energy","kind":"identifier"}]}]}]}