{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_per_second"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/frames_per_second"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideosourcestats\/frames_per_second"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames_per_second","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The frame rate of the video source. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_per_second"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"frames_per_second","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCVideoSourceStats(py)frames_per_second","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"frames_per_second"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats"]]},"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-framespersecond":{"title":"framesPerSecond","titleInlineContent":[{"type":"text","text":"framesPerSecond"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceStats/frames_per_second":{"role":"symbol","title":"frames_per_second","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_per_second"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The frame rate of the video source. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames_per_second","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"frames_per_second"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/frames_per_second"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSourceStats":{"role":"symbol","title":"MCVideoSourceStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSourceStats"}],"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSourceStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceStats"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"frames_per_second"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"frames_per_second"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_per_second"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames_per_second\/title","value":"frames_per_second"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames_per_second\/fragments","value":[{"kind":"identifier","text":"frames_per_second"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/title","value":"MCVideoSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSourceStats\/fragments","value":[{"kind":"identifier","text":"MCVideoSourceStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}