{"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/sampleRate","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleRate"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"title":"sampleRate","externalID":"c:objc(cs)MCAudioFrame(py)sampleRate","navigatorTitle":[{"text":"sampleRate","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The sample rate of the audio data, which is either 48kHz or 44.1kHz.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioframe\/samplerate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioframe\/samplerate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleRate"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame":{"navigatorTitle":[{"kind":"identifier","text":"MCAudioFrame"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","title":"MCAudioFrame","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioFrame"}],"abstract":[{"text":"Audio frame that contains audio data. Used with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","type":"reference"},{"type":"text","text":" "},{"text":"to feed custom audio frames into source used by a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioframe"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/sampleRate":{"abstract":[{"type":"text","text":"The sample rate of the audio data, which is either 48kHz or 44.1kHz."}],"url":"\/documentation\/millicastsdk\/mcaudioframe\/samplerate","title":"sampleRate","kind":"symbol","navigatorTitle":[{"text":"sampleRate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sampleRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/sampleRate","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onAudioFrame:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","title":"onAudioFrame(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAudioFrame"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sampleRate","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"sampleRate","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"text":" ","kind":"text"},{"text":"sampleRate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/title","value":"MCAudioFrame"},{"op":"replace","value":[{"text":"MCAudioFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1sampleRate\/title","value":"sampleRate","op":"replace"},{"value":[{"kind":"identifier","text":"sampleRate"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1sampleRate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","value":"onAudioFrame:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onAudioFrame:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace","value":"MCPublisher"},{"op":"replace","value":[{"kind":"identifier","text":"MCPublisher"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"}]}]}