{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"openGLRenderer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"enable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True to enable OpenGL. Disabled by default."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/init(openglrenderer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/init(openglrenderer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize the renderer with OpenGL support. By default, Metal is used."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"openGLRenderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(openGLRenderer:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)MCIosVideoRenderer(im)initWithOpenGLRenderer:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithOpenGLRenderer:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/init(openGLRenderer:)":{"role":"symbol","title":"init(openGLRenderer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"openGLRenderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the renderer with OpenGL support. By default, Metal is used."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOpenGLRenderer:"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/init(openglrenderer:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer":{"role":"symbol","title":"MCIosVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithOpenGLRenderer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOpenGLRenderer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithOpenGLRenderer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"enable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:)\/title","value":"initWithOpenGLRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOpenGLRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}