{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayersEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/layersevent"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/SQ"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Layers event is received when a layer update happens to"},{"type":"text","text":" "},{"type":"text","text":"a specific mid. Layers are used in simulcast and SVC usecases."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayersEvent"}],"title":"LayersEvent","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:12MillicastSDK11LayersEventV","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"LayersEvent"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/activeLayers","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/inactiveLayers","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/mid"]},{"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/Equatable-Implementations"],"generated":true}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/LayersEvent/inactiveLayers":{"role":"symbol","title":"inactiveLayers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactiveLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of encoding Ids that describe the layers that have gone inactive."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/inactiveLayers","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/layersevent\/inactivelayers"},"doc://MillicastSDK/documentation/MillicastSDK/LayersEvent":{"role":"symbol","title":"LayersEvent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LayersEvent"}],"abstract":[{"type":"text","text":"Layers event is received when a layer update happens to"},{"type":"text","text":" "},{"type":"text","text":"a specific mid. Layers are used in simulcast and SVC usecases."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LayersEvent"}],"url":"\/documentation\/millicastsdk\/layersevent"},"doc://MillicastSDK/documentation/MillicastSDK/LayersEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/layersevent\/equatable-implementations"},"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData":{"role":"symbol","title":"MCLayerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}],"url":"\/documentation\/millicastsdk\/mclayerdata"},"doc://MillicastSDK/documentation/MillicastSDK/LayersEvent/mid":{"role":"symbol","title":"mid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"mid denotes the media Id of the track the layers belong to."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/mid","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/layersevent\/mid"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/LayersEvent/activeLayers":{"role":"symbol","title":"activeLayers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"An array of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData"},{"type":"text","text":" that describes the current active"},{"type":"text","text":" "},{"type":"text","text":"layers that can be selected. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/select(_:completionHandler:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/LayersEvent\/activeLayers","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/layersevent\/activelayers"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/select(_:completionHandler:)":{"role":"symbol","title":"select(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"select"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Select a specific simulcast\/SVC layer for a video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/select(_:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"select:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/select(_:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/title","value":"MCLayerData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1select(_:completionHandler:)\/title","value":"select:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1select(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"select:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}