{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_LOG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@EA@MCLogLevel","text":"MCLogLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mc_log"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mc_log"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MC_LOG","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"General info about what happens and which steps are performed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_LOG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLogLevel","preciseIdentifier":"c:@EA@MCLogLevel"}],"title":"MC_LOG","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@EA@MCLogLevel@MC_LOG","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MC_LOG"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MC_LOG":{"role":"symbol","title":"MC_LOG","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_LOG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLogLevel","preciseIdentifier":"c:@EA@MCLogLevel"}],"abstract":[{"type":"text","text":"General info about what happens and which steps are performed."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MC_LOG","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MC_LOG"}],"url":"\/documentation\/millicastsdk\/mc_log"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel":{"role":"symbol","title":"MCLogLevel","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"}],"abstract":[{"type":"text","text":"Enum to specify the severity of a log message."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLogLevel"}],"url":"\/documentation\/millicastsdk\/mcloglevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MC_LOG"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MC_LOG"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MC_LOG"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MC_LOG\/title","value":"MC_LOG"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MC_LOG\/fragments","value":[{"kind":"identifier","text":"MC_LOG"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel"}],"traits":[{"interfaceLanguage":"occ"}]}]}