{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_MONITOR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","preciseIdentifier":"c:@EA@MCSourceType","text":"MCSourceType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mc_monitor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mc_monitor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MC_MONITOR","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fullscreen capture source."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_MONITOR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSourceType","preciseIdentifier":"c:@EA@MCSourceType"}],"title":"MC_MONITOR","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@EA@MCSourceType@MC_MONITOR","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MC_MONITOR"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"role":"symbol","title":"MCSourceType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceType"}],"abstract":[{"type":"text","text":"The Source type"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSourceType"}],"url":"\/documentation\/millicastsdk\/mcsourcetype"},"doc://MillicastSDK/documentation/MillicastSDK/MC_MONITOR":{"role":"symbol","title":"MC_MONITOR","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MC_MONITOR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSourceType","preciseIdentifier":"c:@EA@MCSourceType"}],"abstract":[{"type":"text","text":"Fullscreen capture source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MC_MONITOR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MC_MONITOR"}],"url":"\/documentation\/millicastsdk\/mc_monitor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MC_MONITOR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MC_MONITOR"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MC_MONITOR"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MC_MONITOR\/title","value":"MC_MONITOR"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MC_MONITOR\/fragments","value":[{"kind":"identifier","text":"MC_MONITOR"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}