{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiocontrol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manages audio settings."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"}],"title":"MCAudioControl","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MCAudioControl","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioControl"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/getVolume()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/isMuted()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/mute(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setNumChannel(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setVolume(_:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/setNumChannel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setNumChannel:"}],"role":"symbol","title":"setNumChannel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNumChannel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the number of channels to use."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setNumChannel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/setnumchannel(_:)"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/getVolume()":{"navigatorTitle":[{"kind":"identifier","text":"getVolume"}],"role":"symbol","title":"getVolume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getVolume"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[{"type":"text","text":"Gets the current volume."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/getVolume()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/getvolume()"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl":{"role":"symbol","title":"MCAudioControl","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"}],"abstract":[{"type":"text","text":"Manages audio settings."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioControl"}],"url":"\/documentation\/millicastsdk\/mcaudiocontrol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"role":"symbol","title":"MCAudioSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSource"}],"abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"url":"\/documentation\/millicastsdk\/mcaudiosource"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"role":"symbol","title":"MCAudioPlayback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"type":"text","text":" "},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/isMuted()":{"navigatorTitle":[{"kind":"identifier","text":"isMuted"}],"role":"symbol","title":"isMuted()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMuted"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether the microphone or speaker is muted or not."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/isMuted()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/ismuted()"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/setVolume(_:)":{"navigatorTitle":[{"kind":"identifier","text":"setVolume:"}],"role":"symbol","title":"setVolume(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVolume"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adjusts the microphone or speaker volume."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setVolume(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/setvolume(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/mute(_:)":{"navigatorTitle":[{"kind":"identifier","text":"mute:"}],"role":"symbol","title":"mute(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mute"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Mutes the microphone or the speakers."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/mute(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol\/mute(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCAudioControl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAudioControl"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAudioControl"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/getVolume()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/isMuted()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/mute(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setNumChannel(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/setVolume(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1setNumChannel(_:)\/title","value":"setNumChannel:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1setNumChannel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNumChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1getVolume()\/title","value":"getVolume"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1getVolume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getVolume"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/title","value":"MCAudioControl"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/fragments","value":[{"kind":"identifier","text":"MCAudioControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title","value":"MCAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","value":[{"kind":"identifier","text":"MCAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1isMuted()\/title","value":"isMuted"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1isMuted()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isMuted"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1setVolume(_:)\/title","value":"setVolume:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1setVolume(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolume:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1mute(_:)\/title","value":"mute:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1mute(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mute:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}