{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudioplayback"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"type":"text","text":" "},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"title":"MCAudioPlayback","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCAudioPlayback","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/initPlayback()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/isPlaying()"]}],"references":{"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback/initPlayback()":{"role":"symbol","title":"initPlayback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initPlayback"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Initializes the playback device."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/initPlayback()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initPlayback"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback\/initplayback()"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback/isPlaying()":{"role":"symbol","title":"isPlaying()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaying"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks whether the playback device is playing."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/isPlaying()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPlaying"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback\/isplaying()"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl":{"role":"symbol","title":"MCAudioControl","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioControl"}],"abstract":[{"type":"text","text":"Manages audio settings."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioControl"}],"url":"\/documentation\/millicastsdk\/mcaudiocontrol"},"doc://MillicastSDK/documentation/MillicastSDK/PlaybackSource":{"role":"symbol","title":"PlaybackSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybackSource"}],"abstract":[{"type":"text","text":"Responsible for managing playback devices."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybackSource"}],"url":"\/documentation\/millicastsdk\/playbacksource"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource":{"role":"symbol","title":"MCSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSource"}],"abstract":[{"type":"text","text":"Gathers information about the source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"url":"\/documentation\/millicastsdk\/mcsource"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"role":"symbol","title":"MCAudioPlayback","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"type":"text","text":" "},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCAudioPlayback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAudioPlayback"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/initPlayback()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/isPlaying()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","preciseIdentifier":"c:objc(cs)MCSource","text":"MCSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1initPlayback()\/title","value":"initPlayback"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1initPlayback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1isPlaying()\/title","value":"isPlaying"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1isPlaying()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPlaying"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/title","value":"MCAudioControl"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/fragments","value":[{"kind":"identifier","text":"MCAudioControl"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/title","value":"PlaybackSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/fragments","value":[{"kind":"identifier","text":"PlaybackSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/title","value":"MCSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/fragments","value":[{"kind":"identifier","text":"MCSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}