{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"title":"MCDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MCDelegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnected()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnectionError(_:withReason:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onDisconnected()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onSignalingError(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onStatsReport(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onViewerCount(_:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"url":"\/documentation\/millicastsdk\/mcdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onStatsReport(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onStatsReport:"}],"role":"symbol","title":"onStatsReport(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStatsReport"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a new RTC statistics report has been collected. You must enable statistics via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)"},{"type":"text","text":" "},{"type":"text","text":"to start receiving this handler."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onStatsReport(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onstatsreport(_:)"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"enableStats:completionHandler:"}],"role":"symbol","title":"enableStats(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables or disables the collection and reporting of real-time"},{"type":"text","text":" "},{"type":"text","text":"statistics associated with streaming sessions."},{"type":"text","text":" "},{"type":"text","text":"The statistics are collected once the client is either publishing or subscribed."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionOptions/autoReconnect":{"role":"symbol","title":"autoReconnect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoReconnect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Attempts to reconnect by default in case of connection error or network dropout. Enabled by default"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"autoReconnect"}],"url":"\/documentation\/millicastsdk\/mcconnectionoptions\/autoreconnect"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onViewerCount(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onViewerCount:"}],"role":"symbol","title":"onViewerCount(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onViewerCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called whenever a new viewer joins or leaves the stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onViewerCount(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onviewercount(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onConnected()":{"navigatorTitle":[{"kind":"identifier","text":"onConnected"}],"deprecated":true,"role":"symbol","title":"onConnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the WebSocket connection to Millicast opens."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnected()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onconnected()"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onSignalingError(_:)":{"navigatorTitle":[{"kind":"identifier","text":"onSignalingError:"}],"role":"symbol","title":"onSignalingError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSignalingError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an error message from Millicast in the response of a websocket command is received."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onSignalingError(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onsignalingerror(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onConnectionError(_:withReason:)":{"navigatorTitle":[{"kind":"identifier","text":"onConnectionError:withReason:"}],"role":"symbol","title":"onConnectionError(_:withReason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConnectionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an attempt to connect to Millicast fails."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnectionError(_:withReason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/onconnectionerror(_:withreason:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate/onDisconnected()":{"navigatorTitle":[{"kind":"identifier","text":"onDisconnected"}],"deprecated":true,"role":"symbol","title":"onDisconnected()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onDisconnected"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the WebSocket connection to Millicast closes. In the case of an unintended disconnect, a reconnect attempt will happen"},{"type":"text","text":" "},{"type":"text","text":"automatically by default. To turn off the automatic reconnect, set "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionOptions\/autoReconnect"},{"type":"text","text":" to false."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onDisconnected()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcdelegate\/ondisconnected()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnected()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onConnectionError(_:withReason:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onDisconnected()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onSignalingError(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onStatsReport(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate\/onViewerCount(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onStatsReport(_:)\/title","value":"onStatsReport:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onStatsReport(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStatsReport:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","value":"enableStats:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableStats:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/title","value":"autoReconnect"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionOptions~1autoReconnect\/fragments","value":[{"kind":"identifier","text":"autoReconnect"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onViewerCount(_:)\/title","value":"onViewerCount:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onViewerCount(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onViewerCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnected()\/title","value":"onConnected"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnected"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onSignalingError(_:)\/title","value":"onSignalingError:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onSignalingError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSignalingError:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnectionError(_:withReason:)\/title","value":"onConnectionError:withReason:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onConnectionError(_:withReason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnectionError:withReason:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onDisconnected()\/title","value":"onDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate~1onDisconnected()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDisconnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}