{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"title":"MCIosVideoRenderer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCIosVideoRenderer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:colorRangeExpansion:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getHeight()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getView()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getWidth()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/getHeight()":{"role":"symbol","title":"getHeight()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getHeight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Get the height of the WebRTC video frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getHeight()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getHeight"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/getheight()"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer":{"role":"symbol","title":"MCIosVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/init(openGLRenderer:)":{"role":"symbol","title":"init(openGLRenderer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"openGLRenderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize the renderer with OpenGL support. By default, Metal is used."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOpenGLRenderer:"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/init(openglrenderer:)"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/getView()":{"role":"symbol","title":"getView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getView"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Get the "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" that you can add it in your UI that allows rendering video frames."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getView"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/getview()"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","title":"MCVideoRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCIosVideoRendererDelegate","preciseIdentifier":"c:objc(pl)MCIosVideoRendererDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/delegate"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/getWidth()":{"role":"symbol","title":"getWidth()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Get the width of the WebRTC video frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getWidth()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWidth"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/getwidth()"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/init(openGLRenderer:colorRangeExpansion:)":{"role":"symbol","title":"init(openGLRenderer:colorRangeExpansion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"openGLRenderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes the renderer to use OpenGL and or color range expansion support. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)"},{"type":"text","text":" for more information."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:colorRangeExpansion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithOpenGLRenderer:colorRangeExpansion:"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/init(openglrenderer:colorrangeexpansion:)"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/init(colorRangeExpansion:)":{"role":"symbol","title":"init(colorRangeExpansion:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes with the option of expanding limited color range to the full range upon rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithColorRangeExpansion:"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/init(colorrangeexpansion:)"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getHeight()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getView()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getWidth()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(colorRangeExpansion:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/init(openGLRenderer:colorRangeExpansion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getHeight()\/title","value":"getHeight"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getHeight()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getHeight"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:)\/title","value":"initWithOpenGLRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOpenGLRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getView()\/title","value":"getView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getView"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getWidth()\/title","value":"getWidth"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getWidth()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:colorRangeExpansion:)\/title","value":"initWithOpenGLRenderer:colorRangeExpansion:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(openGLRenderer:colorRangeExpansion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOpenGLRenderer:colorRangeExpansion:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(colorRangeExpansion:)\/title","value":"initWithColorRangeExpansion:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1init(colorRangeExpansion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithColorRangeExpansion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}