{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcprojectiondata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcprojectiondata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The projection data is used to project a video\/audio track into a specific transceiver."},{"type":"text","text":" "},{"type":"text","text":"We send a command to the media server using the project method to choose which track to"},{"type":"text","text":" "},{"type":"text","text":"project"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"}],"title":"MCProjectionData","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCProjectionData","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCProjectionData"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/layer","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/media","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/mid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/trackId"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData/mid":{"role":"symbol","title":"mid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The transceiver mid associated to the track"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/mid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mid"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata\/mid"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData/layer":{"role":"symbol","title":"layer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Optionally choose a simulcast layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/layer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layer"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata\/layer"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData/trackId":{"role":"symbol","title":"trackId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The id of the track on the server side"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/trackId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackId"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata\/trackid"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData/media":{"role":"symbol","title":"media","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"media"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Kind of the track. Either “video” or “audio”"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/media","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"media"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata\/media"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData":{"role":"symbol","title":"MCProjectionData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"}],"abstract":[{"type":"text","text":"The projection data is used to project a video\/audio track into a specific transceiver."},{"type":"text","text":" "},{"type":"text","text":"We send a command to the media server using the project method to choose which track to"},{"type":"text","text":" "},{"type":"text","text":"project"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCProjectionData"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCProjectionData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCProjectionData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCProjectionData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/layer","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/media","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/mid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/trackId"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1mid\/title","value":"mid"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1mid\/fragments","value":[{"kind":"identifier","text":"mid"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1layer\/title","value":"layer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1layer\/fragments","value":[{"kind":"identifier","text":"layer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1trackId\/title","value":"trackId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1trackId\/fragments","value":[{"kind":"identifier","text":"trackId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1media\/title","value":"media"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1media\/fragments","value":[{"kind":"identifier","text":"media"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/title","value":"MCProjectionData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/fragments","value":[{"kind":"identifier","text":"MCProjectionData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}