{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","preciseIdentifier":"c:objc(pl)MCDelegate","text":"MCDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscriberdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"title":"MCSubscriberDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MCSubscriberDelegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onActive(_:tracks:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onAudioTrack(_:withMid:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onInactive(_:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onLayers(_:activeLayers:inactiveLayers:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onStopped()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onSubscribed()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVad(_:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVideoTrack(_:withMid:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onLayers(_:activeLayers:inactiveLayers:)":{"navigatorTitle":[{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}],"role":"symbol","title":"onLayers(_:activeLayers:inactiveLayers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onLayers"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"inactiveLayers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when simulcast\/svc layers are available"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onLayers(_:activeLayers:inactiveLayers:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onlayers(_:activelayers:inactivelayers:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onAudioTrack(_:withMid:)":{"navigatorTitle":[{"kind":"identifier","text":"onAudioTrack:withMid:"}],"role":"symbol","title":"onAudioTrack(_:withMid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a remote audio track has been added."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onAudioTrack(_:withMid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onaudiotrack(_:withmid:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate/onTransformableFrame(_:withSsrc:withTimestamp:)":{"navigatorTitle":[{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}],"role":"symbol","title":"onTransformableFrame(_:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTransformableFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableArray","preciseIdentifier":"c:objc(cs)NSMutableArray"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called after a frame has been encoded if you need to add data"},{"type":"text","text":" "},{"type":"text","text":"to this frame before the frame is passed to the RTP packetizer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/ontransformableframe(_:withssrc:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate":{"role":"symbol","title":"MCSubscriberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"}],"abstract":[{"type":"text","text":"Delegate protocol that can be implemented to receive subscriber specific"},{"type":"text","text":" "},{"type":"text","text":"events. Initialize the viewer with a delegate via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberDelegate"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCDelegate":{"role":"symbol","title":"MCDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDelegate"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"MCDelegate"},{"type":"text","text":" protocol contains common methods that will be called on specific events from a Client object. It is mainly"},{"type":"text","text":" "},{"type":"text","text":"subclassed by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate"},{"type":"text","text":", which are the main ones to implement."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDelegate"}],"url":"\/documentation\/millicastsdk\/mcdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisherDelegate":{"role":"symbol","title":"MCPublisherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisherDelegate"}],"abstract":[{"type":"text","text":"This delegate  acts as a listener for the Publisher class."},{"type":"text","text":" "},{"type":"text","text":"It adds the publishing event on top of the Client listener."},{"type":"text","text":" "},{"type":"text","text":"You must implement this protocol and set a listener"},{"type":"text","text":" "},{"type":"text","text":"to receive events from the publisher."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisherDelegate"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onInactive(_:sourceId:)":{"navigatorTitle":[{"kind":"identifier","text":"onInactive:sourceId:"}],"role":"symbol","title":"onInactive(_:sourceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a source has been unpublished within the stream"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onInactive(_:sourceId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/oninactive(_:sourceid:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/init(delegate:)":{"role":"symbol","title":"init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCSubscriberDelegate","preciseIdentifier":"c:objc(pl)MCSubscriberDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize a subscriber."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/init(delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/init(delegate:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onActive(_:tracks:sourceId:)":{"navigatorTitle":[{"kind":"identifier","text":"onActive:tracks:sourceId:"}],"role":"symbol","title":"onActive(_:tracks:sourceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a new source has been publishing within the new stream"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onActive(_:tracks:sourceId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onactive(_:tracks:sourceid:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onStopped()":{"navigatorTitle":[{"kind":"identifier","text":"onStopped"}],"role":"symbol","title":"onStopped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onStopped"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Callback is not currently used, but is reserved for future usage."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onStopped()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onstopped()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onVideoTrack(_:withMid:)":{"navigatorTitle":[{"kind":"identifier","text":"onVideoTrack:withMid:"}],"role":"symbol","title":"onVideoTrack(_:withMid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVideoTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withMid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a remote video track has been added."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVideoTrack(_:withMid:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onvideotrack(_:withmid:)"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onSubscribed()":{"navigatorTitle":[{"kind":"identifier","text":"onSubscribed"}],"role":"symbol","title":"onSubscribed()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSubscribed"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Called when the subscriber starts receiving media."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onSubscribed()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onsubscribed()"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)":{"role":"symbol","title":"onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFrameMetadata"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"withLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withSsrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a frame is received and not yet decoded."},{"type":"text","text":" "},{"type":"text","text":"Provide extracted metadata embedded in a frame if any."},{"type":"text","text":" "},{"type":"text","text":"Any data provided by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisherDelegate\/onTransformableFrame(_:withSsrc:withTimestamp:)"},{"type":"text","text":" "},{"type":"text","text":"can be accessed here."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}],"url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onframemetadata(_:withlength:withssrc:withtimestamp:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberDelegate/onVad(_:sourceId:)":{"navigatorTitle":[{"kind":"identifier","text":"onVad:sourceId:"}],"role":"symbol","title":"onVad(_:sourceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onVad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when a source id is being multiplexed into the audio track based on the voice activity level."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVad(_:sourceId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriberdelegate\/onvad(_:sourceid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onActive(_:tracks:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onAudioTrack(_:withMid:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onFrameMetadata(_:withLength:withSsrc:withTimestamp:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onInactive(_:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onLayers(_:activeLayers:inactiveLayers:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onStopped()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onSubscribed()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVad(_:sourceId:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberDelegate\/onVideoTrack(_:withMid:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"MCDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onLayers(_:activeLayers:inactiveLayers:)\/title","value":"onLayers:activeLayers:inactiveLayers:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onLayers(_:activeLayers:inactiveLayers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onLayers:activeLayers:inactiveLayers:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onAudioTrack(_:withMid:)\/title","value":"onAudioTrack:withMid:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onAudioTrack(_:withMid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioTrack:withMid:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/title","value":"onTransformableFrame:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate~1onTransformableFrame(_:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTransformableFrame:withSsrc:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/title","value":"MCSubscriberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate\/fragments","value":[{"kind":"identifier","text":"MCSubscriberDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/title","value":"MCDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDelegate\/fragments","value":[{"kind":"identifier","text":"MCDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/title","value":"MCPublisherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments","value":[{"kind":"identifier","text":"MCPublisherDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onInactive(_:sourceId:)\/title","value":"onInactive:sourceId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onInactive(_:sourceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInactive:sourceId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onActive(_:tracks:sourceId:)\/title","value":"onActive:tracks:sourceId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onActive(_:tracks:sourceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onActive:tracks:sourceId:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onStopped()\/title","value":"onStopped"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onStopped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onVideoTrack(_:withMid:)\/title","value":"onVideoTrack:withMid:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onVideoTrack(_:withMid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVideoTrack:withMid:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onSubscribed()\/title","value":"onSubscribed"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onSubscribed()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSubscribed"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onFrameMetadata(_:withLength:withSsrc:withTimestamp:)\/title","value":"onFrameMetadata:withLength:withSsrc:withTimestamp:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onFrameMetadata(_:withLength:withSsrc:withTimestamp:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFrameMetadata:withLength:withSsrc:withTimestamp:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onVad(_:sourceId:)\/title","value":"onVad:sourceId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberDelegate~1onVad(_:sourceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onVad:sourceId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}