{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"YUY2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","preciseIdentifier":"c:@EA@MCVideoType","text":"MCVideoType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/yuy2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/yuy2"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/YUY2","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"YUY2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoType","preciseIdentifier":"c:@EA@MCVideoType"}],"title":"YUY2","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@EA@MCVideoType@YUY2","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"YUY2"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/YUY2":{"role":"symbol","title":"YUY2","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"YUY2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoType","preciseIdentifier":"c:@EA@MCVideoType"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/YUY2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"YUY2"}],"url":"\/documentation\/millicastsdk\/yuy2"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"role":"symbol","title":"MCVideoType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}],"abstract":[{"type":"text","text":"The VideoType enum represent the pixel format used for video frames."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"url":"\/documentation\/millicastsdk\/mcvideotype"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"YUY2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"YUY2"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"YUY2"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1YUY2\/title","value":"YUY2"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1YUY2\/fragments","value":[{"kind":"identifier","text":"YUY2"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"}],"traits":[{"interfaceLanguage":"occ"}]}]}