{"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setUniqueId(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","modules":[{"name":"MillicastSDK"}],"title":"setUniqueId(_:)","externalID":"c:objc(cs)MCSourceBuilder(im)setUniqueId:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUniqueId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"role":"symbol","navigatorTitle":[{"text":"setUniqueId:","kind":"identifier"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUniqueId"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique ID."}]}]}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/setuniqueid(_:)"]},{"paths":["\/documentation\/millicastsdk\/mcsourcebuilder\/setuniqueid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Set a unique identifier to the source.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder/setUniqueId(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUniqueId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Set a unique identifier to the source."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder\/setUniqueId(_:)","navigatorTitle":[{"kind":"identifier","text":"setUniqueId:"}],"title":"setUniqueId(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcebuilder\/setuniqueid(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"title":"MCSourceBuilder","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceBuilder","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsourcebuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","navigatorTitle":[{"text":"MCSourceBuilder","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Responsible for building a source object."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"setUniqueId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setUniqueId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setUniqueId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setUniqueId(_:)\/title","value":"setUniqueId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder~1setUniqueId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setUniqueId:","kind":"identifier"}]},{"value":"MCSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSourceBuilder"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments"}]}]}