{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType\/encode"},"variants":[{"paths":["\/documentation\/millicastsdk\/mccodecstatstype\/encode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccodecstatstype\/encode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"title":"MCCodecStatsType.encode","navigatorTitle":[{"text":"MCCodecStatsTypeEncode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MCCodecStatsType@MCCodecStatsTypeEncode","role":"symbol","symbolKind":"case","modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCodecStatsType":{"role":"symbol","title":"MCCodecStatsType","navigatorTitle":[{"text":"MCCodecStatsType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType","kind":"symbol","abstract":[{"text":"Different types of codec statistics.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCodecStatsType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecStatsType/encode":{"navigatorTitle":[{"text":"MCCodecStatsTypeEncode","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType\/encode","abstract":[],"role":"symbol","title":"MCCodecStatsType.encode","url":"\/documentation\/millicastsdk\/mccodecstatstype\/encode","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MCCodecStatsTypeEncode","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"MCCodecStatsTypeEncode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCCodecStatsTypeEncode"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/title","op":"replace","value":"MCCodecStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType~1encode\/title","value":"MCCodecStatsTypeEncode"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType~1encode\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsTypeEncode"}],"op":"replace"}]}]}