{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restAPIError"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/restAPIError","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/restapierror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/restapierror"]}],"kind":"symbol","metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restAPIError"}],"externalID":"c:@E@MCGenericError@MCGenericErrorRestAPIError","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","title":"MCGenericError.Code.restAPIError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorRestAPIError"}]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"abstract":[{"text":"Director REST API returned an error.","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","role":"symbol","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"title":"MCGenericError.Code","kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/restAPIError":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/restapierror","role":"symbol","type":"topic","abstract":[{"text":"Director REST API returned an error.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restAPIError"}],"title":"MCGenericError.Code.restAPIError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorRestAPIError"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/restAPIError"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct":{"title":"MCGenericError","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCGenericError"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericError"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCGenericErrorRestAPIError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorRestAPIError"}]},{"op":"replace","path":"\/hierarchy","value":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]}},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCGenericErrorRestAPIError"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","value":"MCGenericError"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","value":[{"text":"MCGenericError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MCGenericError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1restAPIError\/title","value":"MCGenericErrorRestAPIError"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1restAPIError\/fragments","value":[{"text":"MCGenericErrorRestAPIError","kind":"identifier"}]}]}]}