{"abstract":[{"type":"text","text":"The number of bytes sent in RTP packets over the network. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","isActive":true,"type":"reference"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/bytes_sent","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes_sent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/bytes_sent"]},{"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/bytes_sent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"bytes_sent","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","title":"bytes_sent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes_sent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"}],"externalID":"c:objc(cs)MCSentRtpStreamStats(py)bytes_sent","modules":[{"name":"MillicastSDK"}]},"sections":[],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/bytes_sent":{"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/bytes_sent","abstract":[{"type":"text","text":"The number of bytes sent in RTP packets over the network. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","type":"reference"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/bytes_sent","title":"bytes_sent","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes_sent","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"bytes_sent","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"}],"type":"topic","title":"MCSentRtpStreamStats","url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","abstract":[{"text":"Statistics related to an outgoing RTP stream.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcsentrtpstreamstats-bytessent":{"titleInlineContent":[{"type":"text","text":"bytesSent"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-bytessent","title":"bytesSent"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bytes_sent","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"bytes_sent","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsigned long long","preciseIdentifier":"c:k","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"bytes_sent","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1bytes_sent\/title","value":"bytes_sent"},{"value":[{"text":"bytes_sent","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1bytes_sent\/fragments","op":"replace"},{"value":"MCSentRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}