{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/packets_sent"]},{"paths":["\/documentation\/millicastsdk\/mcsentrtpstreamstats\/packets_sent"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The number of RTP packets successfully sent over the network. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent","isActive":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"packets_sent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"]]},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/packets_sent","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCSentRtpStreamStats(py)packets_sent","title":"packets_sent","navigatorTitle":[{"kind":"identifier","text":"packets_sent"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"packets_sent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"identifier"}],"type":"topic","title":"MCSentRtpStreamStats","url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","abstract":[{"text":"Statistics related to an outgoing RTP stream.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats/packets_sent":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats\/packets_sent","abstract":[{"type":"text","text":"The number of RTP packets successfully sent over the network. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats\/packets_sent","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"packets_sent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","kind":"symbol","title":"packets_sent","navigatorTitle":[{"text":"packets_sent","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"https://w3c.github.io/webrtc-stats/#dom-rtcsentrtpstreamstats-packetssent":{"type":"link","titleInlineContent":[{"text":"packetsSent","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcsentrtpstreamstats-packetssent","title":"packetsSent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"packets_sent","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"packets_sent"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:l","text":"unsigned long","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"packets_sent"},{"text":";","kind":"text"}]}]}},{"value":"MCSentRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title","op":"replace"},{"value":[{"text":"MCSentRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1packets_sent\/title","value":"packets_sent"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats~1packets_sent\/fragments","value":[{"text":"packets_sent","kind":"identifier"}]}]}]}