{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeUnAvailable(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStartPlaying(_:error:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStopPlaying(_:error:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"metadata":{"navigatorTitle":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCAudioPlayerNodeDelegate","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"platforms":[],"externalID":"c:objc(pl)MCAudioPlayerNodeDelegate"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidBecomeUnAvailable(_:)":{"required":true,"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeUnAvailable(_:)","abstract":[],"title":"audioPlayerNodeDidBecomeUnAvailable(_:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeunavailable(_:)","navigatorTitle":[{"text":"audioPlayerNodeDidBecomeUnAvailable:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDidBecomeUnAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)":{"kind":"symbol","navigatorTitle":[{"text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","kind":"identifier"}],"title":"audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","type":"topic","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDidBecomeAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"audioFormat","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioFormat","text":"AVAudioFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCAudioPlayerNodePlaybackController","text":"MCAudioPlayerNodePlaybackController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeavailable(_:audioformat:controller:)","abstract":[{"type":"text","text":"Notifies when the SDK creates an AVAudioPlayerNode that will be used for receiving audio"},{"type":"text","text":" "},{"type":"text","text":"-Parameters:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","title":"MCAudioPlayerNodeDelegate","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidStartPlaying(_:error:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstartplaying(_:error:)","title":"audioPlayerNodeDidStartPlaying(_:error:)","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying:error:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStartPlaying(_:error:)","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidStopPlaying(_:error:)":{"navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidStopPlaying:error:"}],"title":"audioPlayerNodeDidStopPlaying(_:error:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStopPlaying(_:error:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidStopPlaying"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","kind":"typeIdentifier","text":"AVAudioPlayerNode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?)"}],"abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstopplaying(_:error:)","type":"topic","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCAudioPlayerNodeDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeUnAvailable(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStartPlaying(_:error:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStopPlaying(_:error:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"audioPlayerNodeDidBecomeUnAvailable:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeUnAvailable(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeUnAvailable(_:)\/fragments"},{"op":"replace","value":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeAvailable:audioFormat:controller:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeAvailable(_:audioFormat:controller:)\/fragments"},{"op":"replace","value":"MCAudioPlayerNodeDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title"},{"op":"replace","value":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments"},{"op":"replace","value":"audioPlayerNodeDidStartPlaying:error:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStartPlaying(_:error:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidStartPlaying:error:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStartPlaying(_:error:)\/fragments"},{"op":"replace","value":"audioPlayerNodeDidStopPlaying:error:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStopPlaying(_:error:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerNodeDidStopPlaying:error:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStopPlaying(_:error:)\/fragments"}]}]}