{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/disableBWE","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/maxBitrateKbps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/minBitrateKbps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/startBitrateKbps"]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"MCBitrateSettings","kind":"identifier"}],"externalID":"c:objc(cs)MCBitrateSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCBitrateSettings","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"MillicastSDK"}],"title":"MCBitrateSettings","role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCBitrateSettings"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcbitratesettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcbitratesettings"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings":{"kind":"symbol","abstract":[{"text":"The BitrateSettings class allows customizing bitrate settings for publishing streams.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcbitratesettings","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings","navigatorTitle":[{"text":"MCBitrateSettings","kind":"identifier"}],"title":"MCBitrateSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCBitrateSettings","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings/maxBitrateKbps":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBitrateKbps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/maxBitrateKbps","navigatorTitle":[{"kind":"identifier","text":"maxBitrateKbps"}],"title":"maxBitrateKbps","url":"\/documentation\/millicastsdk\/mcbitratesettings\/maxbitratekbps","kind":"symbol","abstract":[{"type":"text","text":"The maximum bitrate, in kilobits per second."}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings/startBitrateKbps":{"url":"\/documentation\/millicastsdk\/mcbitratesettings\/startbitratekbps","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/startBitrateKbps","navigatorTitle":[{"text":"startBitrateKbps","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The start bitrate, in kilobits per second."}],"title":"startBitrateKbps"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings/minBitrateKbps":{"navigatorTitle":[{"kind":"identifier","text":"minBitrateKbps"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBitrateKbps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The minimum bitrate, in kilobits per second."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/minBitrateKbps","kind":"symbol","role":"symbol","title":"minBitrateKbps","url":"\/documentation\/millicastsdk\/mcbitratesettings\/minbitratekbps","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCBitrateSettings/disableBWE":{"url":"\/documentation\/millicastsdk\/mcbitratesettings\/disablebwe","kind":"symbol","title":"disableBWE","navigatorTitle":[{"kind":"identifier","text":"disableBWE"}],"abstract":[{"type":"text","text":"Disable built-in bandwidth estimation algorithm that forces sending the maximum bitrate without any congestion control."}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/disableBWE","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableBWE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCBitrateSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCBitrateSettings"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCBitrateSettings","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/disableBWE","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/maxBitrateKbps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/minBitrateKbps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCBitrateSettings\/startBitrateKbps"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCBitrateSettings","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/title","value":"MCBitrateSettings"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCBitrateSettings"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1maxBitrateKbps\/title","op":"replace","value":"maxBitrateKbps"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1maxBitrateKbps\/fragments","op":"replace","value":[{"text":"maxBitrateKbps","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1startBitrateKbps\/title","op":"replace","value":"startBitrateKbps"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1startBitrateKbps\/fragments","op":"replace","value":[{"text":"startBitrateKbps","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1minBitrateKbps\/title","op":"replace","value":"minBitrateKbps"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1minBitrateKbps\/fragments","op":"replace","value":[{"kind":"identifier","text":"minBitrateKbps"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1disableBWE\/title","op":"replace","value":"disableBWE"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCBitrateSettings~1disableBWE\/fragments","op":"replace","value":[{"text":"disableBWE","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}