{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCClient","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclient"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclient"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient"},"metadata":{"symbolKind":"protocol","externalID":"c:objc(pl)MCClient","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"title":"MCClient","role":"symbol","roleHeading":"Protocol","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCClient"}]},"sections":[],"abstract":[{"type":"text","text":"The Client base that contains common methods between "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"},{"type":"text","text":"."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(with:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/destroy()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/disconnect(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/isConnected(completionHandler:)"]}],"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"],"type":"conformingTypes"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(withWebsocketUrl:jwt:completionHandler:)":{"title":"connect(withWebsocketUrl:jwt:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWebsocketUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Connects to the media server directly using the websocket URL and the JSON Web Token.","type":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:completionHandler:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:completionhandler:)","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","title":"MCSubscriber","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/isConnected(completionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"isConnected(completionHandler:)","role":"symbol","abstract":[{"type":"text","text":"Checks whether the client is connected to the media server."}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/isconnected(completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"isConnectedWithCompletionHandler:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/isConnected(completionHandler:)","required":true},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCClient"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient","url":"\/documentation\/millicastsdk\/mcclient","kind":"symbol","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","type":"reference"},{"text":".","type":"text"}],"title":"MCClient"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/enableStats(_:completionHandler:)":{"title":"enableStats(_:completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","role":"symbol","abstract":[{"text":"Enables or disables the collection and reporting of real-time","type":"text"},{"text":" ","type":"text"},{"text":"statistics associated with streaming sessions.","type":"text"},{"text":" ","type":"text"},{"text":"The statistics are collected once the client is either publishing or subscribed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableStats"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/enablestats(_:completionhandler:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"enableStats:completionHandler:"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"title":"MCPublisher","kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(completionHandler:)":{"title":"connect(completionHandler:)","kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","abstract":[{"text":"Connects and opens a websocket connection with the Millicast platform.  You must set valid credentials before using this method.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcclient\/connect(completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"connectWithCompletionHandler:"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/destroy()":{"url":"\/documentation\/millicastsdk\/mcclient\/destroy()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/destroy()","abstract":[{"text":"Destroy the current client instance. This will invalidate the instance. Make sure to call","type":"text"},{"text":" ","type":"text"},{"text":"at the end and do not use the subscriber\/publisher instance after that.","type":"text"}],"required":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"destroy"}],"title":"destroy()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/disconnect(completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"disconnectWithCompletionHandler:"}],"title":"disconnect(completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/disconnect(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Disconnects from the Millicast platform."},{"type":"text","text":"\n"},{"type":"text","text":"Any ongoing process of publishing or subscribing content"},{"type":"text","text":" "},{"type":"text","text":"is automatically stopped before termination."},{"type":"text","text":" "},{"type":"text","text":"The websocket connection to Millicast will no longer be active"},{"type":"text","text":" "},{"type":"text","text":"after disconnect is complete."}],"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcclient\/disconnect(completionhandler:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(with:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcclient\/connect(with:completionhandler:)","abstract":[{"text":"Connects and opens a websocket connection with the Millicast platform. You must set valid credentials before using this method.","type":"text"}],"title":"connect(with:completionHandler:)","required":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(with:completionHandler:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"connect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCConnectionOptions","text":"MCConnectionOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"connectWithOptions:completionHandler:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","required":true,"url":"\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:connectionoptions:completionhandler:)","abstract":[{"type":"text","text":"Connects to the media server directly using the websocket URL and the JSON Web Token."}],"kind":"symbol","title":"connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWebsocketUrl"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCConnectionOptions","kind":"typeIdentifier","text":"MCConnectionOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"MCClient"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCClient"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MCClient","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(with:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/destroy()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/disconnect(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/enableStats(_:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/isConnected(completionHandler:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/title","op":"replace","value":"connectWithWebsocketUrl:jwt:completionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"connectWithWebsocketUrl:jwt:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace","value":"MCSubscriber"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1isConnected(completionHandler:)\/title","op":"replace","value":"isConnectedWithCompletionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1isConnected(completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConnectedWithCompletionHandler:"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/title","op":"replace","value":"MCClient"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/fragments","op":"replace","value":[{"text":"MCClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/title","op":"replace","value":"enableStats:completionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1enableStats(_:completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enableStats:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title","op":"replace","value":"MCPublisher"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments","op":"replace","value":[{"text":"MCPublisher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/title","op":"replace","value":"connectWithCompletionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"connectWithCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1destroy()\/title","op":"replace","value":"destroy"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1destroy()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"destroy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1disconnect(completionHandler:)\/title","op":"replace","value":"disconnectWithCompletionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1disconnect(completionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disconnectWithCompletionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(with:completionHandler:)\/title","op":"replace","value":"connectWithOptions:completionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(with:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectWithOptions:completionHandler:"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)\/title","op":"replace","value":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:connectionOptions:completionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:connectionOptions:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}