{"kind":"symbol","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"MCOutboundRtpStreamStats","externalID":"c:objc(cs)MCOutboundRtpStreamStats","symbolKind":"class","navigatorTitle":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/encoder_implementation","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/fir_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_height","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_width","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_encoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_per_second","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/header_bytes_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/huge_frames_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/key_frames_encoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/nack_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/pli_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/qp_sum","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_durations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_reason","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_resolution_changes","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/remote_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_bytes_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_packets_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/sender_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/target_bitrate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_encoded_bytes_target","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_packet_send_delay"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/get_type()"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/qp_sum":{"kind":"symbol","type":"topic","role":"symbol","title":"qp_sum","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/qp_sum","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qp_sum","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/qp_sum","navigatorTitle":[{"text":"qp_sum","kind":"identifier"}],"abstract":[{"text":"The sum of Quantization Parameters (QP) used during encoding. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/pli_count":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/pli_count","navigatorTitle":[{"text":"pli_count","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/pli_count","abstract":[{"type":"text","text":"The number of Picture Loss Indication (PLI) messages sent. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pli_count","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"title":"pli_count"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-framessent":{"type":"link","titleInlineContent":[{"type":"text","text":"framesSent"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framessent","title":"framesSent","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framessent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-fircount":{"type":"link","titleInlineContent":[{"text":"firCount","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-fircount","title":"firCount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-fircount"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/sender_id":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/sender_id","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The identifier of the sender of the RTP stream."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender_id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"sender_id"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/sender_id","title":"sender_id"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/quality_limitation_durations":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality_limitation_durations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"The duration of quality limitations experienced. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationdurations","type":"reference","isActive":true}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_durations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_durations","navigatorTitle":[{"kind":"identifier","text":"quality_limitation_durations"}],"type":"topic","kind":"symbol","title":"quality_limitation_durations"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/frame_height":{"navigatorTitle":[{"text":"frame_height","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_height","abstract":[{"text":"The height of video frames. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight"}],"type":"topic","title":"frame_height","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frame_height","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame_height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/header_bytes_sent":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/header_bytes_sent","title":"header_bytes_sent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"header_bytes_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"header_bytes_sent"}],"abstract":[{"type":"text","text":"The number of bytes sent for headers. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","type":"reference","isActive":true}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/header_bytes_sent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","titleInlineContent":[{"type":"text","text":"retransmittedPacketsSent"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","title":"retransmittedPacketsSent"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget","titleInlineContent":[{"type":"text","text":"totalEncodedBytesTarget"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget","title":"totalEncodedBytesTarget"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/huge_frames_sent":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"huge_frames_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/huge_frames_sent","navigatorTitle":[{"kind":"identifier","text":"huge_frames_sent"}],"type":"topic","abstract":[{"type":"text","text":"The number of huge video frames successfully sent. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-hugeframessent","type":"reference","isActive":true}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/huge_frames_sent","title":"huge_frames_sent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-keyframesencoded":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-keyframesencoded","titleInlineContent":[{"type":"text","text":"keyFramesEncoded"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-keyframesencoded","title":"keyFramesEncoded"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/key_frames_encoded":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"key_frames_encoded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"key_frames_encoded"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/key_frames_encoded","abstract":[{"type":"text","text":"The number of encoded key frames. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-keyframesencoded","type":"reference","isActive":true}],"type":"topic","kind":"symbol","role":"symbol","title":"key_frames_encoded","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/key_frames_encoded"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/total_encoded_bytes_target":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The number of bytes encoded to meet video target bitrate. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget","type":"reference","isActive":true}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_encoded_bytes_target","title":"total_encoded_bytes_target","role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/total_encoded_bytes_target","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_encoded_bytes_target"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"kind":"identifier","text":"total_encoded_bytes_target"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/quality_limitation_reason":{"kind":"symbol","title":"quality_limitation_reason","navigatorTitle":[{"kind":"identifier","text":"quality_limitation_reason"}],"abstract":[{"type":"text","text":"The reason for any quality limitations in the video stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationreason","type":"reference","isActive":true}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality_limitation_reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_reason","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/remote_id":{"navigatorTitle":[{"kind":"identifier","text":"remote_id"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/remote_id","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/remote_id","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The identifier of the remote user receiving the stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-remoteid","type":"reference","isActive":true}],"title":"remote_id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remote_id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-hugeframessent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-hugeframessent","titleInlineContent":[{"type":"text","text":"hugeFramesSent"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-hugeframessent","title":"hugeFramesSent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qpsum":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","titleInlineContent":[{"type":"text","text":"qpSum"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","title":"qpSum"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-remoteid":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-remoteid","titleInlineContent":[{"type":"text","text":"remoteId"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-remoteid","title":"remoteId"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/retransmitted_bytes_sent":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_bytes_sent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retransmitted_bytes_sent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_bytes_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"abstract":[{"type":"text","text":"The amount of retransmitted data. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","type":"reference","isActive":true}],"title":"retransmitted_bytes_sent","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_bytes_sent","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/target_bitrate":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/target_bitrate","title":"target_bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"target_bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"target_bitrate"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The target bitrate. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","type":"reference","isActive":true}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/target_bitrate"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-framewidth":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framewidth","titleInlineContent":[{"type":"text","text":"frameWidth"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framewidth","title":"frameWidth"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-framespersecond":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framespersecond","titleInlineContent":[{"type":"text","text":"framesPerSecond"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framespersecond","title":"framesPerSecond"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/total_packet_send_delay":{"role":"symbol","kind":"symbol","title":"total_packet_send_delay","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_packet_send_delay","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_packet_send_delay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The cumulative delay during sending packets. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay","type":"reference","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"total_packet_send_delay"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/total_packet_send_delay"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-frameheight":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","titleInlineContent":[{"type":"text","text":"frameHeight"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-frameheight","title":"frameHeight"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/quality_limitation_resolution_changes":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/quality_limitation_resolution_changes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality_limitation_resolution_changes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","title":"quality_limitation_resolution_changes","navigatorTitle":[{"kind":"identifier","text":"quality_limitation_resolution_changes"}],"kind":"symbol","abstract":[{"type":"text","text":"The number of resolution changes due to quality limitations. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","type":"reference","isActive":true}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_resolution_changes"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-framesencoded":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framesencoded","titleInlineContent":[{"type":"text","text":"framesEncoded"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framesencoded","title":"framesEncoded"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/get_type()":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/get_type()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/get_type()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns the type of statistics."}],"type":"topic","title":"get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-plicount":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","titleInlineContent":[{"text":"pliCount","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-plicount","title":"pliCount"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-headerbytessent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","titleInlineContent":[{"text":"headerBytesSent","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","title":"headerBytesSent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","titleInlineContent":[{"text":"qualityLimitationResolutionChanges","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationresolutionchanges","title":"qualityLimitationResolutionChanges"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-nackcount":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount","titleInlineContent":[{"text":"nackCount","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount","title":"nackCount"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/frames_encoded":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames_encoded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"The number of encoded video frames. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framesencoded","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"frames_encoded","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frames_encoded","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_encoded","title":"frames_encoded","role":"symbol","type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-encoderimplementation":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation","titleInlineContent":[{"text":"encoderImplementation","type":"text"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation","title":"encoderImplementation"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/fir_count":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fir_count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"The number of Full Intra Request (FIR) messages sent. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-fircount","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"fir_count","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/fir_count","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/fir_count","title":"fir_count","role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSentRtpStreamStats":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","abstract":[{"type":"text","text":"Statistics related to an outgoing RTP stream."}],"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats","title":"MCSentRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSentRtpStreamStats"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/encoder_implementation":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/encoder_implementation","title":"encoder_implementation","kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/encoder_implementation","role":"symbol","navigatorTitle":[{"text":"encoder_implementation","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encoder_implementation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Information about the encoder used for stream encoding. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-encoderimplementation","isActive":true}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/frames_per_second":{"abstract":[{"text":"The frame rate of the video stream. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framespersecond","isActive":true}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_per_second","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frames_per_second","title":"frames_per_second","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames_per_second","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"frames_per_second","kind":"identifier"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","titleInlineContent":[{"type":"text","text":"retransmittedBytesSent"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent","title":"retransmittedBytesSent"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-targetbitrate":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","titleInlineContent":[{"type":"text","text":"targetBitrate"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-targetbitrate","title":"targetBitrate"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay","titleInlineContent":[{"type":"text","text":"totalPacketSendDelay"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-totalpacketsenddelay","title":"totalPacketSendDelay"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/nack_count":{"navigatorTitle":[{"kind":"identifier","text":"nack_count"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/nack_count","title":"nack_count","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/nack_count","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nack_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"kind":"symbol","abstract":[{"type":"text","text":"The number of Negative Acknowledgment (NACK) messages sent. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-nackcount","type":"reference","isActive":true}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"role":"symbol","title":"MCOutboundRtpStreamStats","navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qualitylimitationreason":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationreason","titleInlineContent":[{"type":"text","text":"qualityLimitationReason"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationreason","title":"qualityLimitationReason"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qualitylimitationdurations":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationdurations","titleInlineContent":[{"type":"text","text":"qualityLimitationDurations"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qualitylimitationdurations","title":"qualityLimitationDurations"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/frame_width":{"kind":"symbol","abstract":[{"type":"text","text":"The width of video frames. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framewidth","isActive":true}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_width","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frame_width","title":"frame_width","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame_width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"frame_width","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/retransmitted_packets_sent":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retransmitted_packets_sent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_packets_sent","navigatorTitle":[{"text":"retransmitted_packets_sent","kind":"identifier"}],"type":"topic","title":"retransmitted_packets_sent","abstract":[{"text":"The number of retransmitted packets. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","type":"reference"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_packets_sent","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/frames_sent":{"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/frames_sent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_sent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_sent","kind":"symbol","abstract":[{"text":"The number of video frames successfully sent. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-framessent","isActive":true,"type":"reference"}],"title":"frames_sent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frames_sent"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCOutboundRtpStreamStats","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/encoder_implementation","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/fir_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_height","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frame_width","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_encoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_per_second","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/frames_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/header_bytes_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/huge_frames_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/key_frames_encoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/nack_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/pli_count","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/qp_sum","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_durations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_reason","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/quality_limitation_resolution_changes","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/remote_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_bytes_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_packets_sent","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/sender_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/target_bitrate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_encoded_bytes_target","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/total_packet_send_delay"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/get_type()"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCOutboundRtpStreamStats","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MCSentRtpStreamStats","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSentRtpStreamStats","preciseIdentifier":"c:objc(cs)MCSentRtpStreamStats"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"qp_sum","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1qp_sum\/title","op":"replace"},{"value":[{"kind":"identifier","text":"qp_sum"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1qp_sum\/fragments","op":"replace"},{"value":"pli_count","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1pli_count\/title","op":"replace"},{"value":[{"text":"pli_count","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1pli_count\/fragments","op":"replace"},{"value":"sender_id","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1sender_id\/title","op":"replace"},{"value":[{"kind":"identifier","text":"sender_id"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1sender_id\/fragments","op":"replace"},{"value":"quality_limitation_durations","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_durations\/title","op":"replace"},{"value":[{"kind":"identifier","text":"quality_limitation_durations"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_durations\/fragments","op":"replace"},{"value":"frame_height","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_height\/title","op":"replace"},{"value":[{"text":"frame_height","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_height\/fragments","op":"replace"},{"value":"header_bytes_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1header_bytes_sent\/title","op":"replace"},{"value":[{"text":"header_bytes_sent","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1header_bytes_sent\/fragments","op":"replace"},{"value":"huge_frames_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1huge_frames_sent\/title","op":"replace"},{"value":[{"text":"huge_frames_sent","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1huge_frames_sent\/fragments","op":"replace"},{"value":"key_frames_encoded","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1key_frames_encoded\/title","op":"replace"},{"value":[{"text":"key_frames_encoded","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1key_frames_encoded\/fragments","op":"replace"},{"value":"total_encoded_bytes_target","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_encoded_bytes_target\/title","op":"replace"},{"value":[{"kind":"identifier","text":"total_encoded_bytes_target"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_encoded_bytes_target\/fragments","op":"replace"},{"value":"quality_limitation_reason","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_reason\/title","op":"replace"},{"value":[{"kind":"identifier","text":"quality_limitation_reason"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_reason\/fragments","op":"replace"},{"value":"remote_id","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1remote_id\/title","op":"replace"},{"value":[{"text":"remote_id","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1remote_id\/fragments","op":"replace"},{"value":"retransmitted_bytes_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_bytes_sent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"retransmitted_bytes_sent"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_bytes_sent\/fragments","op":"replace"},{"value":"target_bitrate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1target_bitrate\/title","op":"replace"},{"value":[{"text":"target_bitrate","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1target_bitrate\/fragments","op":"replace"},{"value":"total_packet_send_delay","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_packet_send_delay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"total_packet_send_delay"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1total_packet_send_delay\/fragments","op":"replace"},{"value":"quality_limitation_resolution_changes","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_resolution_changes\/title","op":"replace"},{"value":[{"text":"quality_limitation_resolution_changes","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1quality_limitation_resolution_changes\/fragments","op":"replace"},{"value":"get_type","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1get_type()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1get_type()\/fragments","op":"replace"},{"value":"frames_encoded","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_encoded\/title","op":"replace"},{"value":[{"text":"frames_encoded","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_encoded\/fragments","op":"replace"},{"value":"fir_count","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1fir_count\/title","op":"replace"},{"value":[{"text":"fir_count","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1fir_count\/fragments","op":"replace"},{"value":"MCSentRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments","op":"replace"},{"value":"encoder_implementation","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1encoder_implementation\/title","op":"replace"},{"value":[{"text":"encoder_implementation","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1encoder_implementation\/fragments","op":"replace"},{"value":"frames_per_second","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_per_second\/title","op":"replace"},{"value":[{"text":"frames_per_second","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_per_second\/fragments","op":"replace"},{"value":"nack_count","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1nack_count\/title","op":"replace"},{"value":[{"kind":"identifier","text":"nack_count"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1nack_count\/fragments","op":"replace"},{"value":"MCOutboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","op":"replace"},{"value":"frame_width","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_width\/title","op":"replace"},{"value":[{"text":"frame_width","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frame_width\/fragments","op":"replace"},{"value":"retransmitted_packets_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_packets_sent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"retransmitted_packets_sent"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_packets_sent\/fragments","op":"replace"},{"value":"frames_sent","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_sent\/title","op":"replace"},{"value":[{"text":"frames_sent","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1frames_sent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}