{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/init(delegate:)"],"title":"Initializers"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/activityPublisher","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/credentials","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/delegate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isConnected","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isPublishing","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/statsReportPublisher","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/viewerCountPublisher"],"title":"Instance Properties"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/activity()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/clearTracks(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/getCredentialsWithCompletionHandler(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpError()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpErrorPublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isPublishing(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionState()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionStatePublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(with:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/record(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/setCredentials(_:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/signalingError()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/signalingErrorPublisher()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/statsReport()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unpublish(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unrecord(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/viewerCount()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/websocketState()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/websocketStatePublisher()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/ActivityEvent"],"title":"Type Aliases"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient","doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"externalID":"c:objc(cs)MCPublisher","title":"MCPublisher","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcpublisher"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcpublisher"]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/clearTracks(completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcpublisher\/cleartracks(completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"clearTracksWithCompletionHandler:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/clearTracks(completionHandler:)","kind":"symbol","abstract":[{"text":"Clears all tracks added to the publisher.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","title":"clearTracks(completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/peerConnectionState()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":">"}],"abstract":[{"text":"Creates an AsyncStream that receives connection state changes for the peer connection.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"peerConnectionState()","url":"\/documentation\/millicastsdk\/mcpublisher\/peerconnectionstate()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionState()"},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/activityPublisher":{"abstract":[{"text":"Get a Combine based publisher that can be used to receive viewer activity events","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/activitypublisher","title":"activityPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/activityPublisher","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActivityEvent","preciseIdentifier":"s:So11MCPublisherC12MillicastSDKE13ActivityEventa"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-6d3yp":{"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-6d3yp","kind":"symbol","title":"addTrack(with:completionHandler:)","abstract":[{"text":"Adds a video track to the publisher. See ","type":"text"},{"type":"codeVoice","code":"MCVideoSource\/startCapture"},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing a video device track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addTrackWithVideoTrack:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoTrack","preciseIdentifier":"c:objc(cs)MCVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/setCredentials(_:completionHandler:)":{"title":"setCredentials(_:completionHandler:)","type":"topic","role":"symbol","abstract":[{"text":"Sets the publisher credentials, providing authentication information","type":"text"},{"text":" ","type":"text"},{"text":"required for connecting to the streaming platform.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/setcredentials(_:completionhandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/setCredentials(_:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"setCredentials:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCredentials"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/signalingErrorPublisher()":{"abstract":[{"text":"Get a Combine based publisher that can be used to receive signaling errors","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/signalingerrorpublisher()","title":"signalingErrorPublisher()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/signalingErrorPublisher()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","title":"MCSubscriber","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/peerConnectionStatePublisher()":{"kind":"symbol","abstract":[{"text":"Get a Combine based publisher that can be used to receive connection state changes  for the peer","type":"text"},{"text":" ","type":"text"},{"text":"connection.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/peerconnectionstatepublisher()","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/peerConnectionStatePublisher()","title":"peerConnectionStatePublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionStatePublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/unpublish(completionHandler:)":{"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unpublish(completionHandler:)","title":"unpublish(completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"unpublishWithCompletionHandler:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpublish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Stops the process of publishing streams to the streaming platform.","type":"text"},{"text":" ","type":"text"},{"text":"After calling this method, the SDK automatically terminates the connection","type":"text"},{"text":" ","type":"text"},{"text":"between the publisher and the streaming platform.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/unpublish(completionhandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/isPublishing(completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}],"kind":"symbol","abstract":[{"text":"Checks whether the publisher is currently in a publishing state","type":"text"},{"text":" ","type":"text"},{"text":"and returns a boolean indicating the publishing status.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/ispublishing(completionhandler:)","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isPublishing(completionHandler:)","title":"isPublishing(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublishing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/unrecord(completionHandler:)":{"abstract":[{"text":"Stops recording a stream.","type":"text"},{"text":" ","type":"text"},{"text":"See the ","type":"text"},{"type":"reference","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/recordings","isActive":true},{"text":" ","type":"text"},{"text":"for more information on how to access the recordings.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/unrecord(completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"unrecordWithCompletionHandler:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unrecord"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"unrecord(completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unrecord(completionHandler:)","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioSource/startCapture()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","kind":"symbol","abstract":[{"text":"Initiates the audio capture process from the current source.","type":"text"}],"role":"symbol","title":"startCapture()","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/httpError()":{"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcpublisher\/httperror()","kind":"symbol","title":"httpError()","abstract":[{"text":"Create an AsyncStream that receives http connection errors.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError"},{"kind":"text","text":">"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpError()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/httpErrorPublisher()":{"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/httperrorpublisher()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/httpErrorPublisher()","abstract":[{"text":"Get a Combine based publisher that can be used to receive http errors","type":"text"}],"title":"httpErrorPublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpErrorPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/publish(with:completionHandler:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(with:completionHandler:)","type":"topic","title":"publish(with:completionHandler:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCClientOptions","preciseIdentifier":"c:objc(cs)MCClientOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"publishWithOptions:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/publish(with:completionhandler:)","abstract":[{"text":"Publish a stream with configuration options.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/delegate":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/delegate","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"MCPublisherDelegate","preciseIdentifier":"c:objc(pl)MCPublisherDelegate"},{"kind":"text","text":")?"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/delegate","type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/viewerCount()":{"kind":"symbol","abstract":[{"text":"Creates a new AsyncStream that receives viewer count updates.","type":"text"}],"title":"viewerCount()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/viewerCount()","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewerCount"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/viewercount()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/getCredentialsWithCompletionHandler(_:)":{"title":"getCredentialsWithCompletionHandler(_:)","abstract":[{"text":"Returns the current publisher credentials.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/getcredentialswithcompletionhandler(_:)","navigatorTitle":[{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCredentialsWithCompletionHandler"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/getCredentialsWithCompletionHandler(_:)","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/activity()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activity"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ActivityEvent","preciseIdentifier":"s:So11MCPublisherC12MillicastSDKE13ActivityEventa"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/activity()","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/activity()","title":"activity()","type":"topic","abstract":[{"text":"Creates a new AsyncStream that receives  viewer activity events","type":"text"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/statsReportPublisher":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReportPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/statsreportpublisher","kind":"symbol","abstract":[{"text":"Get Combine based publisher that can be used to receive stats reports.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/statsReportPublisher","title":"statsReportPublisher","role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/init(delegate:)":{"title":"init(delegate:)","abstract":[{"text":"Initializes a publisher.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDelegate:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/init(delegate:)","url":"\/documentation\/millicastsdk\/mcpublisher\/init(delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCPublisherDelegate","text":"MCPublisherDelegate"},{"kind":"text","text":")?)"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClient"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCClient"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient","url":"\/documentation\/millicastsdk\/mcclient","kind":"symbol","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","type":"reference"},{"text":".","type":"text"}],"title":"MCClient"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(completionHandler:)":{"title":"connect(completionHandler:)","kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","abstract":[{"text":"Connects and opens a websocket connection with the Millicast platform.  You must set valid credentials before using this method.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/millicastsdk\/mcclient\/connect(completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"connectWithCompletionHandler:"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/record(completionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"record"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"recordWithCompletionHandler:"}],"kind":"symbol","type":"topic","role":"symbol","title":"record(completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/record(completionhandler:)","abstract":[{"text":"Starts recording a stream.","type":"text"},{"text":" ","type":"text"},{"text":"See the ","type":"text"},{"type":"reference","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/recordings","isActive":true},{"text":" for more information.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/record(completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-340my":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"kind":"symbol","type":"topic","role":"symbol","title":"addTrack(with:completionHandler:)","url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my","abstract":[{"text":"Adds an audio track to the publisher. See ","type":"text"},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","isActive":true},{"text":" as an example","type":"text"},{"text":" ","type":"text"},{"text":"for capturing an audio device track.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/isConnected":{"type":"topic","abstract":[{"text":"Asynchronously queries whether the publisher is currently connected.","type":"text"}],"title":"isConnected","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isConnected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isConnected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/isconnected","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/websocketStatePublisher()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/websocketStatePublisher()","kind":"symbol","type":"topic","title":"websocketStatePublisher()","role":"symbol","abstract":[{"text":"Get a Combine based publisher that can be used to receive connection state changes for the websocket","type":"text"},{"text":" ","type":"text"},{"text":"connection.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/websocketstatepublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketStatePublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCClient/connect(withWebsocketUrl:jwt:completionHandler:)":{"title":"connect(withWebsocketUrl:jwt:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWebsocketUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Connects to the media server directly using the websocket URL and the JSON Web Token.","type":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"connectWithWebsocketUrl:jwt:completionHandler:"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcclient\/connect(withwebsocketurl:jwt:completionhandler:)","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"title":"MCPublisher","kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/statsReport()":{"title":"statsReport()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReport"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport"},{"kind":"text","text":">"}],"abstract":[{"text":"Creates a new AsyncStream that receives stats reports.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/statsReport()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/statsreport()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/credentials":{"abstract":[{"text":"Asynchronously queries the currently set publisher credentials.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/credentials","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/credentials","title":"credentials","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCPublisherCredentials","preciseIdentifier":"c:objc(cs)MCPublisherCredentials"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/websocketState()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"websocketState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCConnectionState","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/websocketState()","title":"websocketState()","abstract":[{"text":"Creates a new AsyncStream that receives connection state changes for the websocket connection.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/websocketstate()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/ActivityEvent":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/activityevent","role":"symbol","type":"topic","title":"MCPublisher.ActivityEvent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ActivityEvent"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/ActivityEvent","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityEvent"}]},"https://docs.dolby.io/streaming-apis/docs/recordings":{"titleInlineContent":[{"text":"Recording Docs","type":"text"}],"url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/recordings","type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/recordings","title":"Recording Docs"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/isPublishing":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isPublishing","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher\/ispublishing","abstract":[{"text":"Asynchronously queries whether the publisher is currently publishing.","type":"text"}],"title":"isPublishing","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublishing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/publish(completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"publishWithCompletionHandler:"}],"role":"symbol","abstract":[{"type":"text","text":"Initiates the process of publishing streams to the streaming platform."},{"type":"text","text":" "},{"type":"text","text":"Prior to calling this method, you must use the "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(completionHandler:)","type":"reference","isActive":true},{"type":"text","text":"or "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient\/connect(withWebsocketUrl:jwt:completionHandler:)","type":"reference","isActive":true},{"type":"text","text":" method to connect the publisher to the platform."},{"type":"text","text":" "},{"type":"text","text":"When publishing, the SDK sets the AVAudioSession to the playAndRecord"},{"type":"text","text":" "},{"type":"text","text":"category, with voiceChat mode and allowBluetooth option. If desired, the application"},{"type":"text","text":" "},{"type":"text","text":"can configure the AVAudioSession with its own settings."}],"url":"\/documentation\/millicastsdk\/mcpublisher\/publish(completionhandler:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(completionHandler:)","title":"publish(completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/viewerCountPublisher":{"url":"\/documentation\/millicastsdk\/mcpublisher\/viewercountpublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/viewerCountPublisher","type":"topic","title":"viewerCountPublisher","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewerCountPublisher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"kind":"symbol","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive viewer count events"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher/signalingError()":{"kind":"symbol","abstract":[{"text":"Create an AsyncStream that receives signaling errors.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/signalingerror()","title":"signalingError()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/signalingError()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AsyncStream","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"kind":"text","text":">"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCPublisher"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCPublisher","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-6d3yp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/clearTracks(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/getCredentialsWithCompletionHandler(_:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/init(delegate:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/isPublishing(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/publish(with:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/record(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/setCredentials(_:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unpublish(completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher\/unrecord(completionHandler:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCClient"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1clearTracks(completionHandler:)\/title","value":"clearTracksWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1clearTracks(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearTracksWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/title","value":"addTrackWithVideoTrack:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-6d3yp\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithVideoTrack:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1setCredentials(_:completionHandler:)\/title","value":"setCredentials:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1setCredentials(_:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setCredentials:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1unpublish(completionHandler:)\/title","value":"unpublishWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1unpublish(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unpublishWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1isPublishing(completionHandler:)\/title","value":"isPublishingWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1isPublishing(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1unrecord(completionHandler:)\/title","value":"unrecordWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1unrecord(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unrecordWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title","value":"startCapture"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startCapture","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1publish(with:completionHandler:)\/title","value":"publishWithOptions:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1publish(with:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"publishWithOptions:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1getCredentialsWithCompletionHandler(_:)\/title","value":"getCredentialsWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1getCredentialsWithCompletionHandler(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1init(delegate:)\/title","value":"initWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1init(delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/title","value":"MCClient"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient\/fragments","value":[{"kind":"identifier","text":"MCClient"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/title","value":"connectWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"connectWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1record(completionHandler:)\/title","value":"recordWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1record(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recordWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/title","value":"addTrackWithAudioTrack:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/title","value":"connectWithWebsocketUrl:jwt:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCClient~1connect(withWebsocketUrl:jwt:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"connectWithWebsocketUrl:jwt:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"text":"MCPublisher","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1publish(completionHandler:)\/title","value":"publishWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher~1publish(completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"publishWithCompletionHandler:","kind":"identifier"}]}]}]}