{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCScalabilityMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","isActive":true},{"type":"text","text":" to understand where these values come from"}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCScalabilityMode","kind":"identifier"}],"externalID":"c:@E@MCScalabilityMode","navigatorTitle":[{"text":"MCScalabilityMode","kind":"identifier"}],"symbolKind":"enum","title":"MCScalabilityMode","roleHeading":"Enumeration"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2KeyShift","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/none","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3h"]},{"title":"Initializers","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t3Key":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t3Key"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T3Key"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3Key","abstract":[],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t3key","title":"MCScalabilityMode.l3t3Key"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t3":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T3"}],"title":"MCScalabilityMode.l3t3","type":"topic","abstract":[],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t3"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l1t3":{"abstract":[],"title":"MCScalabilityMode.l1t3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l1t3"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL1T3"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/none":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeNone"}],"abstract":[],"title":"MCScalabilityMode.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/none","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/none","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t2h":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2h","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2h","navigatorTitle":[{"text":"MCScalabilityModeS2T2h","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","title":"MCScalabilityMode.s2t2h","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2h","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t3":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s2t3"}],"title":"MCScalabilityMode.s2t3","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T3"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t1Key":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t1Key","kind":"identifier"}],"navigatorTitle":[{"text":"MCScalabilityModeL2T1Key","kind":"identifier"}],"kind":"symbol","title":"MCScalabilityMode.l2t1Key","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1Key","abstract":[],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1key"},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t3":{"kind":"symbol","title":"MCScalabilityMode.l2t3","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T3"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t3","role":"symbol","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l2t3"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t1h":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1h","navigatorTitle":[{"text":"MCScalabilityModeL2T1h","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1h","type":"topic","abstract":[],"title":"MCScalabilityMode.l2t1h","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t1h","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t1":{"navigatorTitle":[{"text":"MCScalabilityModeS2T1","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1","abstract":[],"title":"MCScalabilityMode.s2t1","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t1","kind":"identifier"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t3h":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t3h","role":"symbol","title":"MCScalabilityMode.l2t3h","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t3h","kind":"identifier"}],"navigatorTitle":[{"text":"MCScalabilityModeL2T3h","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t2Key":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t2Key","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"MCScalabilityModeL2T2Key","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2key","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2Key","title":"MCScalabilityMode.l2t2Key"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l1t2":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2","title":"MCScalabilityMode.l1t2","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t2","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCScalabilityModeL1T2","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l1t2","kind":"identifier"}],"abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l1t2h":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l1t2h","kind":"identifier"}],"title":"MCScalabilityMode.l1t2h","type":"topic","navigatorTitle":[{"text":"MCScalabilityModeL1T2h","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t2h","kind":"symbol","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2h","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t1":{"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1","title":"MCScalabilityMode.l2t1","role":"symbol","navigatorTitle":[{"text":"MCScalabilityModeL2T1","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t1","kind":"identifier"}],"abstract":[]},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t2":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t2","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t2"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T2"}],"title":"MCScalabilityMode.l3t2","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t2"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/init(rawValue:)":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/init(rawvalue:)","abstract":[],"type":"topic","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/init(rawValue:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t2":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2","kind":"symbol","title":"MCScalabilityMode.s2t2","role":"symbol","navigatorTitle":[{"text":"MCScalabilityModeS2T2","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t2":{"title":"MCScalabilityMode.l2t2","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t2","kind":"identifier"}],"navigatorTitle":[{"text":"MCScalabilityModeL2T2","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t3h":{"navigatorTitle":[{"text":"MCScalabilityModeS2T3h","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t3h","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t3h","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MCScalabilityMode.s2t3h"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t2h":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t2h","role":"symbol","title":"MCScalabilityMode.s3t2h","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s3t2h","kind":"identifier"}],"navigatorTitle":[{"text":"MCScalabilityModeS3T2h","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/Equatable-Implementations","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/equatable-implementations","type":"topic","kind":"article","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t2h":{"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T2h"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2h","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2h","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l2t2h"}],"kind":"symbol","title":"MCScalabilityMode.l2t2h","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l1t3h":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l1t3h","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l1t3h","kind":"identifier"}],"title":"MCScalabilityMode.l1t3h","abstract":[],"navigatorTitle":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t3":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t3"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T3"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3","role":"symbol","title":"MCScalabilityMode.s3t3","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t3"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t1h":{"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t1h","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t1h"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1h","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T1h"}],"role":"symbol","title":"MCScalabilityMode.s3t1h"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l2t2KeyShift":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2KeyShift","title":"MCScalabilityMode.l2t2KeyShift","kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t2keyshift","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l2t2KeyShift"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T2KeyShift"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t1":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t1","role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"l3t1"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t1","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T1"}],"title":"MCScalabilityMode.l3t1"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t1":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t1"}],"kind":"symbol","title":"MCScalabilityMode.s3t1","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T1"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t1"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s2t1h":{"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t1h","navigatorTitle":[{"text":"MCScalabilityModeS2T1h","kind":"identifier"}],"kind":"symbol","title":"MCScalabilityMode.s2t1h","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t1h","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1h"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcscalabilitymode","abstract":[{"text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"reference","isActive":true},{"text":" to understand where these values come from","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"title":"MCScalabilityMode"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t2":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2","kind":"symbol","role":"symbol","title":"MCScalabilityMode.s3t2","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"s3t2"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS3T2"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t2"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/s3t3h":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3h","role":"symbol","abstract":[],"kind":"symbol","title":"MCScalabilityMode.s3t3h","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s3t3h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s3t3h","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCScalabilityModeS3T3h","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/RawRepresentable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"MCScalabilityMode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MCScalabilityMode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l1t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2KeyShift","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3Key","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/none","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t3h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t1h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t2h","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/s3t3h"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCScalabilityModeL3T3Key","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3Key\/title","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3Key\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL3T3Key","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3\/title","op":"replace","value":"MCScalabilityModeL3T3"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL3T3"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3\/title","op":"replace","value":"MCScalabilityModeL1T3"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL1T3"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1none\/title","op":"replace","value":"MCScalabilityModeNone"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeNone"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2h\/title","op":"replace","value":"MCScalabilityModeS2T2h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS2T2h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3\/title","op":"replace","value":"MCScalabilityModeS2T3"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeS2T3"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1Key\/title","op":"replace","value":"MCScalabilityModeL2T1Key"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1Key\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T1Key"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3\/title","op":"replace","value":"MCScalabilityModeL2T3"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T3"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1h\/title","op":"replace","value":"MCScalabilityModeL2T1h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1h\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T1h"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1\/title","op":"replace","value":"MCScalabilityModeS2T1"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeS2T1"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3h\/title","op":"replace","value":"MCScalabilityModeL2T3h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL2T3h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2Key\/title","op":"replace","value":"MCScalabilityModeL2T2Key"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2Key\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T2Key"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t2\/title","op":"replace","value":"MCScalabilityModeL1T2"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t2\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL1T2"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t2h\/title","op":"replace","value":"MCScalabilityModeL1T2h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t2h\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL1T2h"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1\/title","op":"replace","value":"MCScalabilityModeL2T1"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T1"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t2\/title","op":"replace","value":"MCScalabilityModeL3T2"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t2\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL3T2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2\/title","op":"replace","value":"MCScalabilityModeS2T2"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS2T2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2\/title","op":"replace","value":"MCScalabilityModeL2T2"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL2T2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3h\/title","op":"replace","value":"MCScalabilityModeS2T3h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t3h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS2T3h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2h\/title","op":"replace","value":"MCScalabilityModeS3T2h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS3T2h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2h\/title","op":"replace","value":"MCScalabilityModeL2T2h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL2T2h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3h\/title","op":"replace","value":"MCScalabilityModeL1T3h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l1t3h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL1T3h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3\/title","op":"replace","value":"MCScalabilityModeS3T3"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeS3T3"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t1h\/title","op":"replace","value":"MCScalabilityModeS3T1h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t1h\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeS3T1h"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2KeyShift\/title","op":"replace","value":"MCScalabilityModeL2T2KeyShift"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t2KeyShift\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeL2T2KeyShift"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t1\/title","op":"replace","value":"MCScalabilityModeL3T1"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t1\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL3T1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t1\/title","op":"replace","value":"MCScalabilityModeS3T1"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t1\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCScalabilityModeS3T1"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1h\/title","op":"replace","value":"MCScalabilityModeS2T1h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t1h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS2T1h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace","value":"MCScalabilityMode"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","op":"replace","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2\/title","op":"replace","value":"MCScalabilityModeS3T2"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t2\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS3T2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3h\/title","op":"replace","value":"MCScalabilityModeS3T3h"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1s3t3h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeS3T3h","kind":"identifier"}]}]}]}