{"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberCredentials"}],"externalID":"c:objc(cs)MCSubscriberCredentials","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCSubscriberCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberCredentials"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/accountId","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/apiUrl","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/streamName","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/token"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberCredentials"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"text":" ","type":"text"},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials/apiUrl":{"type":"topic","kind":"symbol","abstract":[{"text":"The subscribe API URL.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/apiurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","title":"apiUrl","navigatorTitle":[{"kind":"identifier","text":"apiUrl"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/apiUrl"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials/token":{"navigatorTitle":[{"text":"token","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/token","kind":"symbol","type":"topic","role":"symbol","title":"token","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/token","abstract":[{"type":"text","text":"The subscribing token."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials":{"abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"text":" ","type":"text"},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"identifier":"https:\/\/dash.millicast.com\/docs.html","type":"reference","isActive":true}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberCredentials","kind":"identifier"}],"navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscribercredentials","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials","title":"MCSubscriberCredentials","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"https://dash.millicast.com/docs.html":{"titleInlineContent":[{"text":"Streaming Dashboard","type":"text"}],"url":"https:\/\/dash.millicast.com\/docs.html","type":"link","title":"Streaming Dashboard","identifier":"https:\/\/dash.millicast.com\/docs.html"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials/accountId":{"abstract":[{"type":"text","text":"Your Millicast account ID."}],"title":"accountId","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/accountId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accountId"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/accountid","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriberCredentials/streamName":{"type":"topic","abstract":[{"text":"The name of the stream you want to subscribe to.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/streamName","title":"streamName","url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/streamname","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"streamName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"streamName"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCSubscriberCredentials"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCSubscriberCredentials","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCSubscriberCredentials"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/accountId","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/apiUrl","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/streamName","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriberCredentials\/token"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberCredentials"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1apiUrl\/title","value":"apiUrl"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1apiUrl\/fragments","value":[{"text":"apiUrl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1token\/title","value":"token"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1token\/fragments","value":[{"kind":"identifier","text":"token"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","value":[{"text":"MCSubscriberCredentials","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1accountId\/title","value":"accountId"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1accountId\/fragments","value":[{"kind":"identifier","text":"accountId"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1streamName\/title","value":"streamName"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriberCredentials~1streamName\/fragments","value":[{"text":"streamName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}