{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames_per_second","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/height","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/width"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/get_type()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSourceStats","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcestats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideosourcestats"]}],"metadata":{"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceStats"}],"role":"symbol","externalID":"c:objc(cs)MCVideoSourceStats","modules":[{"name":"MillicastSDK"}],"title":"MCVideoSourceStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSourceStats"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats":{"abstract":[{"type":"text","text":"Statistics representing a video track that is attached to one or more senders."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSourceStats"}],"title":"MCVideoSourceStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats","url":"\/documentation\/millicastsdk\/mcvideosourcestats","navigatorTitle":[{"kind":"identifier","text":"MCVideoSourceStats"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/frames_per_second":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames_per_second","type":"topic","title":"frames_per_second","abstract":[{"type":"text","text":"The frame rate of the video source. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond","type":"reference","isActive":true}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frames_per_second"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/frames_per_second","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames_per_second"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/width":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/width","type":"topic","title":"width","abstract":[{"type":"text","text":"The width of the video source. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","type":"reference","isActive":true}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCMediaSourceStats":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCMediaSourceStats"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcmediasourcestats","title":"MCMediaSourceStats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCMediaSourceStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats","abstract":[{"type":"text","text":"The MCMediaSourceStats class gathers statistics details."}],"kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-height":{"titleInlineContent":[{"type":"text","text":"height"}],"title":"height","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-height","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-height"},"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-framespersecond":{"titleInlineContent":[{"type":"text","text":"framesPerSecond"}],"title":"framesPerSecond","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-framespersecond"},"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-frames":{"titleInlineContent":[{"type":"text","text":"frames"}],"title":"frames","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/get_type()":{"abstract":[{"type":"text","text":"Returns the type of statistics."}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/get_type()","type":"topic","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/get_type()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"}],"title":"get_type()","kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats-width":{"titleInlineContent":[{"type":"text","text":"width"}],"title":"width","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-width"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/frames":{"navigatorTitle":[{"kind":"identifier","text":"frames"}],"role":"symbol","abstract":[{"type":"text","text":"The number of frames. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-frames","type":"reference","isActive":true}],"url":"\/documentation\/millicastsdk\/mcvideosourcestats\/frames","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames","title":"frames","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP"},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSourceStats/height":{"kind":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcvideosourcestats\/height","title":"height","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/height","abstract":[{"type":"text","text":"The height of the video source. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcvideosourcestats-height"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCVideoSourceStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCVideoSourceStats","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCVideoSourceStats"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/frames_per_second","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/height","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/width"],"title":"Instance Properties"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSourceStats\/get_type()"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSourceStats"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCMediaSourceStats","text":"MCMediaSourceStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats\/title","value":"MCVideoSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats\/fragments","value":[{"kind":"identifier","text":"MCVideoSourceStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames_per_second\/title","value":"frames_per_second"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames_per_second\/fragments","value":[{"kind":"identifier","text":"frames_per_second"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1width\/fragments","value":[{"text":"width","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","value":"MCMediaSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments","value":[{"kind":"identifier","text":"MCMediaSourceStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1get_type()\/title","value":"get_type"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1get_type()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames\/title","value":"frames"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1frames\/fragments","value":[{"text":"frames","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSourceStats~1height\/fragments","value":[{"text":"height","kind":"identifier"}]}]}]}