{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/currentMID"},"abstract":[{"text":"The current MID of the track. Useful to parse statistics based on the mid.","type":"text"}],"metadata":{"roleHeading":"Instance Property","title":"currentMID","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCRTSRemoteTrack(py)currentMID","navigatorTitle":[{"text":"currentMID","kind":"identifier"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/currentmid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/currentmid"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/currentMID":{"kind":"symbol","role":"symbol","title":"currentMID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"currentMID"}],"abstract":[{"type":"text","text":"The current MID of the track. Useful to parse statistics based on the mid."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/currentMID","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/currentmid"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"type":"topic","abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","title":"MCRTSRemoteTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"currentMID","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"currentMID","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentMID"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"currentMID","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1currentMID\/title","op":"replace"},{"value":[{"kind":"identifier","text":"currentMID"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack~1currentMID\/fragments","op":"replace"},{"value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/navigatorTitle","op":"replace"}]}]}