{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"monitor","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/monitor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/monitor"]}],"metadata":{"title":"MCSourceType.monitor","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeMonitor"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"monitor","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCSourceType@MCSourceTypeMonitor"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/monitor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fullscreen capture source."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceType"}],"url":"\/documentation\/millicastsdk\/mcsourcetype","abstract":[{"type":"text","text":"The Source type"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","kind":"symbol","title":"MCSourceType","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/monitor":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/monitor","navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeMonitor"}],"url":"\/documentation\/millicastsdk\/mcsourcetype\/monitor","type":"topic","title":"MCSourceType.monitor","kind":"symbol","abstract":[{"type":"text","text":"Fullscreen capture source."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"monitor"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCSourceTypeMonitor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCSourceTypeMonitor"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCSourceTypeMonitor"}]}]}},{"value":"MCSourceType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title"},{"value":[{"text":"MCSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1monitor\/title","value":"MCSourceTypeMonitor"},{"value":[{"text":"MCSourceTypeMonitor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1monitor\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}