{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/equatable-implementations"]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/!=(_:_:)"],"title":"Operators","generated":true}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/Equatable-Implementations"},"kind":"article","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","title":"MCScalabilityMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"type":"text","text":" to understand where these values come from"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/!=(_:_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/!=(_:_:)","abstract":[],"kind":"symbol","title":"!=(_:_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/!=(_:_:)"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"text":"MCScalabilityMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/navigatorTitle","value":[{"text":"MCScalabilityMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}