{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l3t3","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL3T3","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL3T3"}],"role":"symbol","symbolKind":"case","title":"MCScalabilityMode.l3t3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l3t3","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l3t3"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode","title":"MCScalabilityMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCScalabilityMode"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityMode"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"type":"text","text":" to understand where these values come from"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCScalabilityMode/l3t3":{"title":"MCScalabilityMode.l3t3","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCScalabilityMode\/l3t3","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l3t3","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l3t3","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MCScalabilityModeL3T3","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MCScalabilityModeL3T3","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeL3T3","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MCScalabilityModeL3T3","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","value":[{"kind":"identifier","text":"MCScalabilityMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode\/navigatorTitle","value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3\/title","value":"MCScalabilityModeL3T3","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCScalabilityMode~1l3t3\/fragments","value":[{"text":"MCScalabilityModeL3T3","kind":"identifier"}],"op":"replace"}]}]}