{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"]]},"kind":"symbol","metadata":{"title":"clock_rate","navigatorTitle":[{"kind":"identifier","text":"clock_rate"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clock_rate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCCodecsStats(py)clock_rate","role":"symbol","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"The clock rate of the codec, indicating the frequency at which samples are generated or processed. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clock_rate","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mccodecsstats\/clock_rate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccodecsstats\/clock_rate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/clock_rate"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats/clock_rate":{"abstract":[{"type":"text","text":"The clock rate of the codec, indicating the frequency at which samples are generated or processed. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate","isActive":true}],"url":"\/documentation\/millicastsdk\/mccodecsstats\/clock_rate","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats\/clock_rate","title":"clock_rate","navigatorTitle":[{"kind":"identifier","text":"clock_rate"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"clock_rate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}]},"https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-clockrate":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate","title":"clockRate","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtccodecstats-clockrate","titleInlineContent":[{"type":"text","text":"clockRate"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecsStats":{"type":"topic","navigatorTitle":[{"text":"MCCodecsStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccodecsstats","title":"MCCodecsStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCodecsStats"}],"kind":"symbol","abstract":[{"type":"text","text":"Gathers audio\/video codec statistics."}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecsStats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clock_rate"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clock_rate"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"text":"unsigned long","kind":"typeIdentifier","preciseIdentifier":"c:l"},{"kind":"text","text":" "},{"kind":"identifier","text":"clock_rate"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"clock_rate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1clock_rate\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats~1clock_rate\/fragments","value":[{"text":"clock_rate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/title","value":"MCCodecsStats"},{"value":[{"text":"MCCodecsStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecsStats\/fragments"}]}]}