{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCredentialsWithCompletionHandler"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"getCredentialsWithCompletionHandler(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCredentialsWithCompletionHandler","kind":"identifier"},{"text":"((","kind":"text"},{"text":"MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}],"externalID":"c:objc(cs)MCSubscriber(im)getCredentialsWithCompletionHandler:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/getcredentialswithcompletionhandler(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/getcredentialswithcompletionhandler(_:)"]}],"abstract":[{"type":"text","text":"Get the current viewer’s credentials."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/getCredentialsWithCompletionHandler(_:)"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"references":{"https://dash.millicast.com/docs.html":{"title":"Streaming Dashboard","url":"https:\/\/dash.millicast.com\/docs.html","titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"identifier":"https:\/\/dash.millicast.com\/docs.html","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/getCredentialsWithCompletionHandler(_:)":{"abstract":[{"type":"text","text":"Get the current viewer’s credentials."}],"title":"getCredentialsWithCompletionHandler(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCredentialsWithCompletionHandler"},{"kind":"text","text":"(("},{"preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","kind":"typeIdentifier","text":"MCSubscriberCredentials"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/getcredentialswithcompletionhandler(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/getCredentialsWithCompletionHandler(_:)","navigatorTitle":[{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"title":"MCSubscriberCredentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberCredentials"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriberCredentials"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscribercredentials","abstract":[{"type":"text","text":"The Credentials interface represent the credentials required for"},{"type":"text","text":" "},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/dash.millicast.com\/docs.html"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"getCredentialsWithCompletionHandler:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCredentialsWithCompletionHandler:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MCSubscriber","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"value":[{"kind":"identifier","text":"MCSubscriber"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"op":"replace","value":"getCredentialsWithCompletionHandler:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1getCredentialsWithCompletionHandler(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1getCredentialsWithCompletionHandler(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getCredentialsWithCompletionHandler:","kind":"identifier"}]},{"op":"replace","value":"MCSubscriberCredentials","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","value":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}