{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpErrorPublisher()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"httpErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive http errors"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/httperrorpublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"title":"httpErrorPublisher()","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"httpErrorPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","text":"MCHTTPConnectionError","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"text":">","kind":"text"}],"role":"symbol","extendedModule":"MillicastSDK","externalID":"s:So12MCSubscriberC12MillicastSDKE18httpErrorPublisher7Combine03AnyF0VySo016MCHTTPConnectionE0Cs5NeverOGyF"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/httpErrorPublisher()":{"title":"httpErrorPublisher()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/httpErrorPublisher()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpErrorPublisher","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCHTTPConnectionError","preciseIdentifier":"c:objc(cs)MCHTTPConnectionError","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/httperrorpublisher()","abstract":[{"type":"text","text":"Get a Combine based publisher that can be used to receive http errors"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCHTTPConnectionError":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCHTTPConnectionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mchttpconnectionerror","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCHTTPConnectionError","title":"MCHTTPConnectionError","navigatorTitle":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"abstract":[{"type":"text","text":"Container class for HTTP errors that occur during"},{"type":"text","text":" "},{"type":"text","text":"connection to the millicast service"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/title","value":"MCHTTPConnectionError","op":"replace"},{"op":"replace","value":[{"text":"MCHTTPConnectionError","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCHTTPConnectionError\/fragments"}]}]}