{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Creates a new AsyncStream that receives rts remote tracks when they are available.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackAdded","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new async stream reporting newly added remote tracks"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/rtsremotetrackadded()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtsRemoteTrackAdded","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"kind":"text","text":">"}],"externalID":"s:So12MCSubscriberC12MillicastSDKE19rtsRemoteTrackAddedScSySo011MCRTSRemoteF0CGyF","extendedModule":"MillicastSDK","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"rtsRemoteTrackAdded()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAdded()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"title":"MCRTSRemoteTrack","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"type":"text","text":" "},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"type":"text","text":" "},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/rtsRemoteTrackAdded()":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/rtsremotetrackadded()","title":"rtsRemoteTrackAdded()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrackAdded","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":">","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/rtsRemoteTrackAdded()","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives rts remote tracks when they are available."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"MCSubscriber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"value":"MCRTSRemoteTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}