{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signalingError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSignalingError","text":"MCSignalingError","kind":"typeIdentifier"},{"text":">","kind":"text"}],"externalID":"s:So12MCSubscriberC12MillicastSDKE14signalingErrorScSySo011MCSignalingE0CGyF","extendedModule":"MillicastSDK","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"signalingError()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingError()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"signalingError"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","text":"MCSignalingError","preciseIdentifier":"c:objc(cs)MCSignalingError"},{"kind":"text","text":">"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new async stream reporting signaling errors."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/signalingerror()"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Create an AsyncStream that receives signaling errors."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSignalingError":{"abstract":[{"type":"text","text":"Container class for Signaling errors that occur during"},{"type":"text","text":" "},{"type":"text","text":"signaling\/configuration of the peer connection."}],"kind":"symbol","title":"MCSignalingError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSignalingError"}],"navigatorTitle":[{"text":"MCSignalingError","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcsignalingerror"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/signalingError()":{"title":"signalingError()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/signalingError()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signalingError","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSignalingError","kind":"typeIdentifier","text":"MCSignalingError"},{"text":">","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/signalingerror()","abstract":[{"type":"text","text":"Create an AsyncStream that receives signaling errors."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MCSubscriber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"},{"value":"MCSignalingError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/fragments","value":[{"text":"MCSignalingError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}