{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoTracks"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ([","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"},{"text":"]?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes, with a"},{"type":"text","text":" "},{"type":"text","text":"list of remote video tracks."}],"type":"paragraph"}],"name":"completionHandler"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/videotracks(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/videotracks(completionhandler:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/videoTracks(completionHandler:)"},"abstract":[{"type":"text","text":"List all available rts remote video tracks received so far."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"videoTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier"},{"kind":"text","text":"]?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"videoTracks(completionHandler:)","role":"symbol","externalID":"c:objc(cs)MCSubscriber(im)videoTracksWithCompletionHandler:","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"videoTracksWithCompletionHandler:","kind":"identifier"}],"symbolKind":"method"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriber"}],"role":"symbol","title":"MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The RTS logical track’s video interface."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/videoTracks(completionHandler:)":{"kind":"symbol","title":"videoTracks(completionHandler:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTracks"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": (["},{"text":"MCRTSRemoteVideoTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"text":"]?, (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"List all available rts remote video tracks received so far.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcsubscriber\/videotracks(completionhandler:)","navigatorTitle":[{"text":"videoTracksWithCompletionHandler:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/videoTracks(completionHandler:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"videoTracksWithCompletionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"videoTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"videoTracksWithCompletionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSArray<MCRTSRemoteVideoTrack *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber","op":"replace"},{"value":[{"text":"MCSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","op":"replace","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1videoTracks(completionHandler:)\/title","value":"videoTracksWithCompletionHandler:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"videoTracksWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber~1videoTracks(completionHandler:)\/fragments"}]}]}