{"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"kind","role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MCMediaSourceStats(py)kind","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"kind"}]},"abstract":[{"text":"The track type. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind","type":"reference"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/kind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/kind"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/kind"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcmediasourcestats-kind":{"title":"kind","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind","titleInlineContent":[{"type":"text","text":"kind"}],"type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats":{"navigatorTitle":[{"kind":"identifier","text":"MCMediaSourceStats"}],"role":"symbol","title":"MCMediaSourceStats","abstract":[{"text":"The MCMediaSourceStats class gathers statistics details.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCMediaSourceStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats"},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats/kind":{"abstract":[{"type":"text","text":"The track type. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-kind"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"kind","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/kind","url":"\/documentation\/millicastsdk\/mcmediasourcestats\/kind","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kind"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"kind"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"kind","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"kind"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","op":"replace","value":"MCMediaSourceStats"},{"value":[{"kind":"identifier","text":"MCMediaSourceStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments","op":"replace"},{"value":"kind","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1kind\/title","op":"replace"},{"value":[{"text":"kind","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1kind\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}