{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/native"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/native"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/native"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoTypeNative","kind":"identifier"}],"externalID":"c:@E@MCVideoType@MCVideoTypeNative","title":"MCVideoType.native","symbolKind":"case"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","title":"MCVideoType","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/native":{"navigatorTitle":[{"text":"MCVideoTypeNative","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcvideotype\/native","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/native","abstract":[],"type":"topic","title":"MCVideoType.native","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCVideoTypeNative","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCVideoTypeNative","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCVideoTypeNative","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCVideoType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title"},{"value":[{"kind":"identifier","text":"MCVideoType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments"},{"value":"MCVideoTypeNative","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1native\/title"},{"value":[{"kind":"identifier","text":"MCVideoTypeNative"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1native\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}