{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outboundRTP"}]}]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"outboundRTP","kind":"identifier"}],"externalID":"c:@E@MCStatsType@MCStatsTypeOutboundRTP","role":"symbol","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeOutboundRTP"}],"modules":[{"name":"MillicastSDK"}],"title":"MCStatsType.outboundRTP"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/outboundrtp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/outboundrtp"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType\/outboundRTP","interfaceLanguage":"swift"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType/outboundRTP":{"abstract":[],"title":"MCStatsType.outboundRTP","url":"\/documentation\/millicastsdk\/mcstatstype\/outboundrtp","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outboundRTP"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType\/outboundRTP","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeOutboundRTP"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","title":"MCStatsType","abstract":[{"type":"text","text":"Different types of statistics."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCStatsTypeOutboundRTP","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsTypeOutboundRTP"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MCStatsTypeOutboundRTP","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCStatsTypeOutboundRTP","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType~1outboundRTP\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType~1outboundRTP\/fragments","value":[{"kind":"identifier","text":"MCStatsTypeOutboundRTP"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"kind":"identifier","text":"MCStatsType"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/navigatorTitle","value":[{"kind":"identifier","text":"MCStatsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}