{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webrtcRemoteTrack"},{"kind":"text","text":": "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteTrack"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There’s no “enabled” counterpart - the track is only projected in response"},{"type":"text","text":" "},{"type":"text","text":"to the application request - the application should set a continuation"},{"text":" ","type":"text"},{"text":"callback on the project API. The track can become disabled, meaning","type":"text"},{"text":" ","type":"text"},{"text":"unprojected, due to external events (network problems, reconnection, migration, and similar.","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"The event for disabled state notification.","type":"text"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)MCWebrtcRemoteTrackDelegate(im)webrtcRemoteTrackDisabled:","modules":[{"name":"MillicastSDK"}],"title":"webrtcRemoteTrackDisabled(_:)","navigatorTitle":[{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteTrack"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate"]]},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"title":"MCWebrtcRemoteTrackDelegate","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrackDisabled(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webrtcRemoteTrackDisabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"webrtcRemoteTrackDisabled(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)","abstract":[{"text":"The event for disabled state notification.","type":"text"}],"navigatorTitle":[{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"abstract":[{"type":"text","text":"The webrtc logical track."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"title":"MCWebrtcRemoteTrack","role":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"webrtcRemoteTrackDisabled:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCWebrtcRemoteTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"text":" *) ","kind":"text"},{"text":"webrtcRemoteTrack","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCWebrtcRemoteTrackDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/fragments","op":"replace"},{"value":"webrtcRemoteTrackDisabled:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"webrtcRemoteTrackDisabled:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/fragments","op":"replace"},{"value":"MCWebrtcRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}