{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":")!)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"removeRenderer:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"c:objc(cs)MCVideoTrack(im)removeRenderer:","title":"remove(_:)"},"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/remove(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"renderer","kind":"internalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"MCVideoRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":")!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The renderer to remove."}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotrack\/remove(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotrack\/remove(_:)"]}],"abstract":[{"text":"Removes a renderer from the list.","type":"text"}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"url":"\/documentation\/millicastsdk\/mcvideotrack","type":"topic","abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTrack"}],"role":"symbol","title":"MCVideoTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/remove(_:)":{"kind":"symbol","title":"remove(_:)","abstract":[{"text":"Removes a renderer from the list.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"text":"removeRenderer:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/remove(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/remove(_:)","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"role":"symbol","title":"add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoRenderer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"removeRenderer:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeRenderer:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"removeRenderer:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MCVideoRenderer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer"},{"text":") ","kind":"text"},{"text":"renderer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoTrack"}]},{"value":"removeRenderer:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1remove(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1remove(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeRenderer:"}]},{"value":"addRenderer:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer","op":"replace"},{"value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"}]}]}