{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/layers()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layers()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","text":"AsyncStream","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"a new AsyncStream that receives simulcast\/SVC layer events","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"for more information."}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"abstract":[{"type":"text","text":"Create an AsyncStream to receive track simulcast\/SVC layers when they are available"}],"metadata":{"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE6layersScSySo0aB6LayersCGyF","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers","kind":"typeIdentifier","text":"MCRTSRemoteTrackLayers"},{"kind":"text","text":">"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"extendedModule":"MillicastSDK","title":"layers()"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack/layers()":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/layers()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/layers()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layers","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","kind":"typeIdentifier","preciseIdentifier":"s:ScS"},{"text":"<","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"text":">","kind":"text"}],"abstract":[{"text":"Create an AsyncStream to receive track simulcast\/SVC layers when they are available","type":"text"}],"title":"layers()","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackLayers":{"navigatorTitle":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","abstract":[{"text":"The layers update event. Note that if the RtsTrack is projected","type":"text"},{"text":" ","type":"text"},{"text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,","type":"text"},{"text":" ","type":"text"},{"text":"so the RTS track will get multiple layer events.","type":"text"},{"text":" ","type":"text"},{"text":"No debouncing\/deduplication is implemented.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers","title":"MCRTSRemoteTrackLayers","kind":"symbol","type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrack(_:didUpdateLayers:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtsRemoteTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":", ","kind":"text"},{"text":"didUpdateLayers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteTrackLayers","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayers"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrack(_:didupdatelayers:)","title":"rtsRemoteTrack(_:didUpdateLayers:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrack(_:didUpdateLayers:)","kind":"symbol","abstract":[{"text":"Event received when there is Simulcast\/SVC layers available for the remote track. Only","type":"text"},{"text":" ","type":"text"},{"text":"available for video tracks.","type":"text"}],"navigatorTitle":[{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MCRTSRemoteTrack","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title"},{"op":"replace","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"},{"op":"replace","value":"MCRTSRemoteTrackLayers","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/title"},{"op":"replace","value":[{"text":"MCRTSRemoteTrackLayers","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/fragments"},{"op":"replace","value":"rtsRemoteTrack:didUpdateLayers:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtsRemoteTrack:didUpdateLayers:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrack(_:didUpdateLayers:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}