{"abstract":[{"text":"Delegate for receiving AVAudioPlayerNode updates.","type":"text"}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodeDelegate"},{"text":")?","kind":"text"}],"externalID":"c:objc(cs)MCAudioConfiguration(py)audioPlayerNodeDelegate","roleHeading":"Instance Property","title":"audioPlayerNodeDelegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"audioPlayerNodeDelegate","kind":"identifier"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/audioPlayerNodeDelegate"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MCAudioPlayerNodeDelegate","preciseIdentifier":"c:objc(pl)MCAudioPlayerNodeDelegate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The AVAudioPlayerNode receives the SDK audio and can be routed"},{"type":"text","text":" "},{"type":"text","text":"to your own audio pipeline. Once the delegate is registered, the SDK will not"},{"type":"text","text":" "},{"type":"text","text":"handle audio playback internally."}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration\/audioplayernodedelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioconfiguration\/audioplayernodedelegate"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","title":"MCAudioPlayerNodeDelegate","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Global Audio Configuration object."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration","navigatorTitle":[{"text":"MCAudioConfiguration","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudioconfiguration","kind":"symbol","title":"MCAudioConfiguration"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioConfiguration/audioPlayerNodeDelegate":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)MCAudioPlayerNodeDelegate","kind":"typeIdentifier","text":"MCAudioPlayerNodeDelegate"},{"kind":"text","text":")?"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate for receiving AVAudioPlayerNode updates."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioConfiguration\/audioPlayerNodeDelegate","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDelegate"}],"url":"\/documentation\/millicastsdk\/mcaudioconfiguration\/audioplayernodedelegate","kind":"symbol","title":"audioPlayerNodeDelegate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"audioPlayerNodeDelegate","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"audioPlayerNodeDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<MCAudioPlayerNodeDelegate>","preciseIdentifier":"c:Qoobjc(pl)MCAudioPlayerNodeDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDelegate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCAudioPlayerNodeDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments","op":"replace"},{"value":"MCAudioConfiguration","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioConfiguration"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration\/fragments","op":"replace"},{"value":"audioPlayerNodeDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1audioPlayerNodeDelegate\/title","op":"replace"},{"value":[{"text":"audioPlayerNodeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioConfiguration~1audioPlayerNodeDelegate\/fragments","op":"replace"}]}]}