{"abstract":[{"type":"text","text":"Asynchronously query the currently set credentials."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credentials"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"async","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/credentials"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/credentials"]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}],"title":"credentials","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"credentials","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials","text":"MCSubscriberCredentials"}],"symbolKind":"property","externalID":"s:So12MCSubscriberC12MillicastSDKE11credentialsSo0A11CredentialsCvp"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/credentials":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Asynchronously query the currently set credentials."}],"url":"\/documentation\/millicastsdk\/mcsubscriber\/credentials","title":"credentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/credentials","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credentials"},{"kind":"text","text":": "},{"text":"MCSubscriberCredentials","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCSubscriberCredentials"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"connecting and subscribing to a Millicast stream. See the "},{"identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true,"type":"reference"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials","navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}],"title":"MCSubscriberCredentials","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSubscriberCredentials","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"type":"topic","title":"MCSubscriber","role":"symbol","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"https://dash.millicast.com/docs.html":{"titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"type":"link","url":"https:\/\/dash.millicast.com\/docs.html","identifier":"https:\/\/dash.millicast.com\/docs.html","title":"Streaming Dashboard"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials"},{"value":[{"kind":"identifier","text":"MCSubscriberCredentials"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","value":"MCSubscriber"},{"op":"replace","value":[{"kind":"identifier","text":"MCSubscriber"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}