{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"]]},"kind":"symbol","abstract":[{"type":"text","text":"Creates a new AsyncStream that receives connection state changes for the websocket connection."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriber\/websocketstate()"]}],"metadata":{"symbolKind":"method","extendedModule":"MillicastSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketState","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"text":"MCConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState"},{"kind":"text","text":">"}],"roleHeading":"Instance Method","externalID":"s:So12MCSubscriberC12MillicastSDKE14websocketStateScSySo012MCConnectionE0VGyF","title":"websocketState()","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketState","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","text":"MCConnectionState"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A new async stream reporting websocket connection state changes."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketState()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCConnectionState"}],"navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"type":"topic","title":"MCConnectionState","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","role":"symbol","kind":"symbol","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"type":"topic","title":"MCSubscriber","role":"symbol","abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber/websocketState()":{"url":"\/documentation\/millicastsdk\/mcsubscriber\/websocketstate()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"websocketState","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@E@MCConnectionState","text":"MCConnectionState","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber\/websocketState()","title":"websocketState()","role":"symbol","kind":"symbol","abstract":[{"text":"Creates a new AsyncStream that receives connection state changes for the websocket connection.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"MCConnectionState","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title","op":"replace"},{"op":"replace","value":[{"text":"MCConnectionState","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments"},{"op":"replace","value":"MCSubscriber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"kind":"identifier","text":"MCSubscriber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}