{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStatsOf"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier","text":"MCStatsType"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats","text":"MCStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"inlineContent":[{"type":"text","text":"The desired type of statistics. See "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"An array containing the stats of the specified type.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Retrieves an array of MCStats objects from the report that match a specified MCStatsType.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)"]},{"paths":["\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)"},"metadata":{"title":"getStatsOf(_:)","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCStatsReport(im)getStatsOfType:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStatsOf","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"},{"kind":"text","text":") -> ["},{"text":"MCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats"},{"text":"]?","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getStatsOfType:"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"abstract":[{"text":"Different types of statistics.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","title":"MCStatsType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic"},"https://w3c.github.io/webrtc-stats/#introduction":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"url":"\/documentation\/millicastsdk\/mcstatsreport","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"title":"MCStatsReport","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCStatsReport","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/getStatsOf(_:)":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/getStatsOf(_:)","kind":"symbol","title":"getStatsOf(_:)","url":"\/documentation\/millicastsdk\/mcstatsreport\/getstatsof(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStatsOf","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"text":"MCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats"},{"text":"]?","kind":"text"}],"abstract":[{"text":"Retrieves an array of MCStats objects from the report that match a specified MCStatsType.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"getStatsOfType:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStats","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","url":"\/documentation\/millicastsdk\/mcstats","type":"topic","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"title":"MCStats","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"getStatsOfType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getStatsOfType:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MCStats *>"},{"text":" *) ","kind":"text"},{"text":"getStatsOfType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"typeIdentifier","text":"MCStatsType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"value":[{"text":"MCStatsType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments"},{"value":"MCStatsReport","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"kind":"identifier","text":"MCStatsReport"}],"op":"replace"},{"value":"getStatsOfType:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"getStatsOfType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1getStatsOf(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","value":"MCStats"},{"value":[{"kind":"identifier","text":"MCStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments"}]}]}