{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmedia\/getaudiosources()"]},{"paths":["\/documentation\/millicastsdk\/mcmedia\/getaudiosources()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Query all available audio sources.","type":"text"}],"metadata":{"roleHeading":"Type Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","navigatorTitle":[{"text":"getAudioSources","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getAudioSources","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"MCAudioSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioSource"},{"text":"]","kind":"text"}],"title":"getAudioSources()","externalID":"c:objc(cs)MCMedia(cm)getAudioSources"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioSources"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioSource","text":"MCAudioSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of all available "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getAudioSources()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMedia/getAudioSources()":{"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia\/getAudioSources()","abstract":[{"text":"Query all available audio sources.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcmedia\/getaudiosources()","title":"getAudioSources()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioSources"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioSource","preciseIdentifier":"c:objc(cs)MCAudioSource"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"getAudioSources"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCMedia":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCMedia"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMedia","type":"topic","abstract":[{"text":"Class  used  for managing media sources.","type":"text"}],"title":"MCMedia","url":"\/documentation\/millicastsdk\/mcmedia","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCMedia","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"title":"MCAudioSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioSource"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosource","abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"getAudioSources","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"getAudioSources","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSArray<MCAudioSource *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"getAudioSources","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"getAudioSources","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getAudioSources()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia~1getAudioSources()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"getAudioSources","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/title","value":"MCMedia"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMedia\/fragments","value":[{"text":"MCMedia","kind":"identifier"}],"op":"replace"},{"value":"MCAudioSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title"},{"value":[{"kind":"identifier","text":"MCAudioSource"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}