{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublishing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the result is ready."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisher\/ispublishing(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisher\/ispublishing(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/isPublishing(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Checks whether the publisher is currently in a publishing state"},{"type":"text","text":" "},{"type":"text","text":"and returns a boolean indicating the publishing status."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublishing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"isPublishing(completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCPublisher(im)isPublishingWithCompletionHandler:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/isPublishing(completionHandler:)":{"role":"symbol","title":"isPublishing(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPublishing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Checks whether the publisher is currently in a publishing state"},{"type":"text","text":" "},{"type":"text","text":"and returns a boolean indicating the publishing status."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/isPublishing(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/ispublishing(completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"role":"symbol","title":"MCPublisher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"url":"\/documentation\/millicastsdk\/mcpublisher"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isPublishingWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"isPublishingWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1isPublishing(completionHandler:)\/title","value":"isPublishingWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1isPublishing(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isPublishingWithCompletionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}