{"metadata":{"externalID":"c:objc(pl)MCClient(im)destroy","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroy","kind":"identifier"},{"kind":"text","text":"()"}],"title":"destroy()","roleHeading":"Instance Method","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"destroy"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/destroy()"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"destroy","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcclient\/destroy()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcclient\/destroy()"]}],"abstract":[{"text":"Destroy the current client instance. This will invalidate the instance. Make sure to call","type":"text"},{"type":"text","text":" "},{"text":"at the end and do not use the subscriber\/publisher instance after that.","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriber":{"title":"MCSubscriber","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","role":"symbol","kind":"symbol","abstract":[{"text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCSubscriber"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClient/destroy()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destroy"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient\/destroy()","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcclient\/destroy()","title":"destroy()","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"destroy"}],"abstract":[{"text":"Destroy the current client instance. This will invalidate the instance. Make sure to call","type":"text"},{"type":"text","text":" "},{"type":"text","text":"at the end and do not use the subscriber\/publisher instance after that."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClient":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClient","url":"\/documentation\/millicastsdk\/mcclient","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MCClient","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The Client base that contains common methods between ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":" and "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriber","isActive":true,"type":"reference"},{"text":".","type":"text"}],"title":"MCClient","navigatorTitle":[{"text":"MCClient","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","title":"MCPublisher","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"destroy","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"destroy"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"destroy"},{"kind":"text","text":";"}]}]}},{"value":"MCSubscriber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriber\/fragments","value":[{"text":"MCSubscriber","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1destroy()\/title","value":"destroy"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"destroy"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient~1destroy()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/title","op":"replace","value":"MCClient"},{"op":"replace","value":[{"text":"MCClient","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClient\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"value":[{"kind":"identifier","text":"MCPublisher"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}