{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/statsReport()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsubscriber\/statsreport()"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stats reports."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReport"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:ScS","text":"AsyncStream"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStatsReport","text":"MCStatsReport","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsReport"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A new async stream reporting stream statistics.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"extendedModule":"MillicastSDK","externalID":"s:So12MCSubscriberC12MillicastSDKE11statsReportScSySo07MCStatsE0CGyF","symbolKind":"method","role":"symbol","title":"statsReport()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statsReport","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AsyncStream","preciseIdentifier":"s:ScS","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MCStatsReport","preciseIdentifier":"c:objc(cs)MCStatsReport","kind":"typeIdentifier"},{"text":">","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsReport":{"navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsReport"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsReport","title":"MCStatsReport","abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcstatsreport","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber":{"navigatorTitle":[{"text":"MCSubscriber","kind":"identifier"}],"abstract":[{"type":"text","text":"The Subscriber class manages the subscription to audio and video tracks from the Millicast platform."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber","url":"\/documentation\/millicastsdk\/mcsubscriber","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriber","kind":"identifier"}],"title":"MCSubscriber"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSubscriber/statsReport()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsReport"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:ScS","kind":"typeIdentifier","text":"AsyncStream"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)MCStatsReport","kind":"typeIdentifier","text":"MCStatsReport"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Creates a new AsyncStream that receives stats reports."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsubscriber\/statsreport()","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSubscriber\/statsReport()","title":"statsReport()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsReport\/title","op":"replace","value":"MCStatsReport"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsReport\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/title","op":"replace","value":"MCSubscriber"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSubscriber\/fragments","op":"replace","value":[{"text":"MCSubscriber","kind":"identifier"}]}]}]}