{"abstract":[{"text":"Event received when the track, i.e. it’s publishing source, has become inactive.","type":"text"},{"type":"text","text":" "},{"text":"In other words the publishers stream is no longer being sent to the server and is","type":"text"},{"text":" ","type":"text"},{"text":"thus no longer viewable on the viewing client. The track is not disabled by the SDK","type":"text"},{"type":"text","text":" "},{"text":"when this event occurs. If the application wants to ensure the track will not","type":"text"},{"type":"text","text":" "},{"text":"automatically be played once the source becomes active it should call disable() when","type":"text"},{"type":"text","text":" "},{"type":"text","text":"receiving this event. Then it is responsible for calling enable() on the Active event."},{"text":" ","type":"text"},{"type":"text","text":"If the application does not disable on Inactive event, the track will automatically start"},{"text":" ","type":"text"},{"type":"text","text":"playing when the remote source becomes Active."}],"metadata":{"externalID":"c:objc(pl)MCRTSRemoteTrackDelegate(im)rtsRemoteTrackInactive:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"rtsRemoteTrackInactive:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"rtsRemoteTrackInactive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rtsRemoteTrackInactive","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"},{"kind":"text","text":")"}],"role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackinactive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackinactive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrackInactive"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"rtsRemoteTrack","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MCRTSRemoteTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"rtsRemoteTrack","content":[{"inlineContent":[{"text":"The remote track that has become inactive.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrack"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"type":"text","text":" "},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"type":"text","text":" "},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"type":"text","text":" "},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"text":" ","type":"text"},{"type":"text","text":"RTS source goes inactive, streaming for them is automatically disabled."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate/rtsRemoteTrackInactive(_:)":{"navigatorTitle":[{"text":"rtsRemoteTrackInactive:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate\/rtsRemoteTrackInactive(_:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Event received when the track, i.e. it’s publishing source, has become inactive."},{"text":" ","type":"text"},{"text":"In other words the publishers stream is no longer being sent to the server and is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"thus no longer viewable on the viewing client. The track is not disabled by the SDK"},{"type":"text","text":" "},{"text":"when this event occurs. If the application wants to ensure the track will not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"automatically be played once the source becomes active it should call disable() when"},{"text":" ","type":"text"},{"text":"receiving this event. Then it is responsible for calling enable() on the Active event.","type":"text"},{"text":" ","type":"text"},{"text":"If the application does not disable on Inactive event, the track will automatically start","type":"text"},{"type":"text","text":" "},{"text":"playing when the remote source becomes Active.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrackInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate\/rtsremotetrackinactive(_:)","title":"rtsRemoteTrackInactive(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackDelegate"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackDelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetrackdelegate","title":"MCRTSRemoteTrackDelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"rtsRemoteTrackInactive:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtsRemoteTrackInactive:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rtsRemoteTrackInactive:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"},{"kind":"text","text":" *) "},{"text":"rtsRemoteTrack","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","value":"MCRTSRemoteTrack","op":"replace"},{"op":"replace","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"},{"value":"rtsRemoteTrackInactive:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtsRemoteTrackInactive:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate~1rtsRemoteTrackInactive(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/title","value":"MCRTSRemoteTrackDelegate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackDelegate\/fragments","op":"replace","value":[{"text":"MCRTSRemoteTrackDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}