{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/transactionerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/transactionerror"]}],"kind":"symbol","metadata":{"roleHeading":"Case","title":"MCGenericError.Code.transactionError","role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"case","externalID":"c:@E@MCGenericError@MCGenericErrorTransactionError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transactionError"}],"navigatorTitle":[{"text":"MCGenericErrorTransactionError","kind":"identifier"}]},"sections":[],"abstract":[{"text":"Signaling returned error for the request.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionError"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/transactionError","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"title":"MCGenericError.Code"},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code/transactionError":{"title":"MCGenericError.Code.transactionError","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/transactionError","abstract":[{"text":"Signaling returned error for the request.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/transactionerror","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"transactionError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorTransactionError"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","title":"MCGenericError","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCGenericError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCGenericError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MCGenericErrorTransactionError","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCGenericErrorTransactionError","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCGenericErrorTransactionError","kind":"identifier"}]}]}},{"op":"replace","value":"MCGenericError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MCGenericError"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1transactionError\/title","value":"MCGenericErrorTransactionError","op":"replace"},{"value":[{"kind":"identifier","text":"MCGenericErrorTransactionError"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1transactionError\/fragments"}]}]}