{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"aborted","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"MCAsyncOperationCancelledError.Code.aborted","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorAborted","kind":"identifier"}],"externalID":"c:@E@MCAsyncOperationCancelledError@MCAsyncOperationCancelledErrorAborted"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/aborted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/aborted"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/aborted"},"abstract":[{"type":"text","text":"Operation was cancelled because a newer request made it"},{"text":" ","type":"text"},{"text":"obsolete.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"aborted","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","kind":"symbol","abstract":[{"type":"text","text":"Error category for errors triggered when the operation failed because"},{"text":" ","type":"text"},{"text":"it was abandoned for various reasons.","type":"text"}],"title":"MCAsyncOperationCancelledError.Code"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/aborted":{"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/aborted","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"aborted","kind":"identifier"}],"abstract":[{"type":"text","text":"Operation was cancelled because a newer request made it"},{"type":"text","text":" "},{"type":"text","text":"obsolete."}],"title":"MCAsyncOperationCancelledError.Code.aborted","type":"topic","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorAborted","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/aborted"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCAsyncOperationCancelledErrorAborted"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MCAsyncOperationCancelledErrorAborted","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCAsyncOperationCancelledErrorAborted","kind":"identifier"}]}]}},{"op":"replace","value":"MCAsyncOperationCancelledError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MCAsyncOperationCancelledError","kind":"identifier"}]},{"value":"MCAsyncOperationCancelledErrorAborted","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1aborted\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1aborted\/fragments","op":"replace","value":[{"text":"MCAsyncOperationCancelledErrorAborted","kind":"identifier"}]}]}]}