{"abstract":[{"type":"text","text":"AVAudioPlayerNode is not attached to an audio engine."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/avaudioplayernodenotattachedtoavaudioengine"]},{"paths":["\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/avaudioplayernodenotattachedtoavaudioengine"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"avAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/avAudioPlayerNodeNotAttachedToAVAudioEngine","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avAudioPlayerNodeNotAttachedToAVAudioEngine"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","externalID":"c:@E@MCAudioError@MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","symbolKind":"case","role":"symbol","title":"MCAudioError.Code.avAudioPlayerNodeNotAttachedToAVAudioEngine"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"title":"MCAudioError.Code","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code","abstract":[{"text":"Error category for errors triggered when audio related errors occur.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct":{"role":"symbol","navigatorTitle":[{"text":"MCAudioError","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MCAudioError","kind":"identifier"}],"title":"MCAudioError"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioError-swift.struct/Code/avAudioPlayerNodeNotAttachedToAVAudioEngine":{"abstract":[{"text":"AVAudioPlayerNode is not attached to an audio engine.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/avaudioplayernodenotattachedtoavaudioengine","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"avAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/avAudioPlayerNodeNotAttachedToAVAudioEngine","title":"MCAudioError.Code.avAudioPlayerNodeNotAttachedToAVAudioEngine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/title","value":"MCAudioError"},{"value":[{"kind":"identifier","text":"MCAudioError"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code~1avAudioPlayerNodeNotAttachedToAVAudioEngine\/title","op":"replace","value":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code~1avAudioPlayerNodeNotAttachedToAVAudioEngine\/fragments","value":[{"kind":"identifier","text":"MCAudioErrorAVAudioPlayerNodeNotAttachedToAVAudioEngine"}]}]}]}