{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code"]]},"abstract":[{"text":"Allow one to match an error code against an arbitrary error.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"~="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"10.10","unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"title":"~=(_:_:)","symbolKind":"op","role":"symbol","extendedModule":"Foundation","externalID":"s:10Foundation18_ErrorCodeProtocolPAAE2teoiySbx_s0B0_ptFZ::SYNTHESIZED::c:@E@MCAudioError","roleHeading":"Operator","modules":[{"relatedModules":["Foundation"],"name":"MillicastSDK"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/~=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/~=(_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"~="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"match"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"error","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioError-swift.struct/Code":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code","role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Error category for errors triggered when audio related errors occur."}],"url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"title":"MCAudioError.Code","type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioError-swift.struct/Code/~=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"~="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct\/Code\/~=(_:_:)","abstract":[{"text":"Allow one to match an error code against an arbitrary error.","type":"text"}],"kind":"symbol","title":"~=(_:_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct\/code\/~=(_:_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioError-swift.struct":{"navigatorTitle":[{"text":"MCAudioError","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudioerror-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioError","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"MCAudioError","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioError-swift.struct"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/title","op":"replace","value":"MCAudioError"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MCAudioError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioError-swift.struct~1Code\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCAudioError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}