{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteInboundRTP","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteInboundRTP"}],"languages":["swift"]}]}],"metadata":{"title":"MCStatsType.remoteInboundRTP","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"remoteInboundRTP","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCStatsTypeRemoteInboundRTP","kind":"identifier"}],"externalID":"c:@E@MCStatsType@MCStatsTypeRemoteInboundRTP","role":"symbol","roleHeading":"Case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/remoteinboundrtp"]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/remoteinboundrtp"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/remoteInboundRTP":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype\/remoteinboundrtp","title":"MCStatsType.remoteInboundRTP","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteInboundRTP","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"MCStatsTypeRemoteInboundRTP","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteInboundRTP","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"title":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"abstract":[{"text":"Different types of statistics.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCStatsTypeRemoteInboundRTP","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCStatsTypeRemoteInboundRTP","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCStatsTypeRemoteInboundRTP"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"MCStatsTypeRemoteInboundRTP","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteInboundRTP\/title"},{"value":[{"kind":"identifier","text":"MCStatsTypeRemoteInboundRTP"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteInboundRTP\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","value":[{"text":"MCStatsType","kind":"identifier"}]}]}]}