{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connecting","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState"]]},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@E@MCConnectionState@MCConnectionStateConnecting","roleHeading":"Case","navigatorTitle":[{"text":"MCConnectionStateConnecting","kind":"identifier"}],"title":"MCConnectionState.connecting","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The socket is in the process of connecting.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/connecting"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState/connecting":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connecting","kind":"identifier"}],"abstract":[{"text":"The socket is in the process of connecting.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState\/connecting","navigatorTitle":[{"text":"MCConnectionStateConnecting","kind":"identifier"}],"kind":"symbol","title":"MCConnectionState.connecting","url":"\/documentation\/millicastsdk\/mcconnectionstate\/connecting"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCConnectionState":{"url":"\/documentation\/millicastsdk\/mcconnectionstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCConnectionState","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCConnectionState","type":"topic","title":"MCConnectionState","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MCConnectionStateConnecting","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCConnectionStateConnecting"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCConnectionStateConnecting","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCConnectionStateConnecting","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connecting\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState~1connecting\/fragments","value":[{"text":"MCConnectionStateConnecting","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/title","value":"MCConnectionState","op":"replace"},{"value":[{"kind":"identifier","text":"MCConnectionState"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCConnectionState\/fragments","op":"replace"}]}]}