{"metadata":{"externalID":"c:objc(cs)MCRTSRemoteTrackLayer(py)bitrate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"bitrate","kind":"identifier"}],"symbolKind":"property","title":"bitrate","modules":[{"name":"MillicastSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/bitrate"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitrate","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/bitrate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/bitrate"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/bitrate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitrate"}],"title":"bitrate","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/bitrate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bitrate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/bitrate"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"title":"MCRTSRemoteTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"bitrate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"bitrate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrate"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"bitrate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1bitrate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bitrate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1bitrate\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title","value":"MCRTSRemoteTrackLayer","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","value":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"op":"replace"}]}]}