{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgb24"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb24"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/rgb24"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/rgb24"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"]]},"metadata":{"title":"MCVideoType.rgb24","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeRGB24"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgb24"}],"externalID":"c:@E@MCVideoType@MCVideoTypeRGB24","role":"symbol","modules":[{"name":"MillicastSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/rgb24":{"url":"\/documentation\/millicastsdk\/mcvideotype\/rgb24","type":"topic","kind":"symbol","title":"MCVideoType.rgb24","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgb24"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCVideoTypeRGB24"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/rgb24"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoType"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoType"}],"url":"\/documentation\/millicastsdk\/mcvideotype","role":"symbol","abstract":[],"title":"MCVideoType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCVideoTypeRGB24","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MCVideoTypeRGB24"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCVideoTypeRGB24","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCVideoTypeRGB24","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb24\/title"},{"value":[{"text":"MCVideoTypeRGB24","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1rgb24\/fragments"},{"value":"MCVideoType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title"},{"value":[{"kind":"identifier","text":"MCVideoType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments"}]}]}