{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/audiotrack"]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/audiotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioTrack"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/audioTrack","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"MCStatsTypeAudioTrack","kind":"identifier"}],"externalID":"c:@E@MCStatsType@MCStatsTypeAudioTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioTrack"}],"roleHeading":"Case","title":"MCStatsType.audioTrack","role":"symbol","modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"title":"MCStatsType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsType"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic","abstract":[{"type":"text","text":"Different types of statistics."}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/audioTrack":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeAudioTrack"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcstatstype\/audiotrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/audioTrack","kind":"symbol","type":"topic","title":"MCStatsType.audioTrack"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCStatsTypeAudioTrack","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCStatsTypeAudioTrack","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MCStatsTypeAudioTrack","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"value":[{"kind":"identifier","text":"MCStatsType"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1audioTrack\/title","value":"MCStatsTypeAudioTrack","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1audioTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsTypeAudioTrack"}]}]}]}