{"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaTrack","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaTrack"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype\/mediatrack"]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/mediatrack"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType"]]},"metadata":{"title":"MCStatsType.mediaTrack","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeMediaTrack"}],"roleHeading":"Case","externalID":"c:@E@MCStatsType@MCStatsTypeMediaTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaTrack"}],"symbolKind":"case"},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/mediaTrack":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeMediaTrack"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaTrack","url":"\/documentation\/millicastsdk\/mcstatstype\/mediatrack","kind":"symbol","type":"topic","title":"MCStatsType.mediaTrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"title":"MCStatsType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsType"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic","abstract":[{"type":"text","text":"Different types of statistics."}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCStatsTypeMediaTrack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MCStatsTypeMediaTrack"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCStatsTypeMediaTrack","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaTrack\/title","op":"replace","value":"MCStatsTypeMediaTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaTrack\/fragments","value":[{"text":"MCStatsTypeMediaTrack","kind":"identifier"}]},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}