{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"MCCMSampleBufferVideoRendererDelegate.didReceive(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"]]},"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":")","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"title":"didReceive(_:)","externalID":"c:@CM@MillicastSDK@objc(cs)MCSampleBufferVideoUIView(im)didReceiveSampleBuffer:","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didReceive(_:)"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didreceive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didreceive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/didReceive(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didReceive(_:)","title":"didReceive(_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didreceive(_:)","navigatorTitle":[{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","title":"MCSampleBufferVideoUIView","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCSampleBufferVideoUIView/MCCMSampleBufferVideoRendererDelegate-Implementations":{"kind":"article","abstract":[],"title":"MCCMSampleBufferVideoRendererDelegate Implementations","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"didReceiveSampleBuffer:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveSampleBuffer:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"didReceiveSampleBuffer:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didReceive(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didReceiveSampleBuffer:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didReceive(_:)\/fragments","op":"replace"},{"value":"MCSampleBufferVideoUIView","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","op":"replace"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","op":"replace"}]}]}