{"sections":[],"metadata":{"title":"MCAsyncOperationCancelledError.Code.actorShutdown","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorActorShutdown","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actorShutdown"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@MCAsyncOperationCancelledError@MCAsyncOperationCancelledErrorActorShutdown"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/actorshutdown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/actorshutdown"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actorShutdown","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/actorShutdown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Operation was cancelled because shutdown or disconnection in progress."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/actorShutdown":{"abstract":[{"type":"text","text":"Operation was cancelled because shutdown or disconnection in progress."}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/actorShutdown","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"actorShutdown","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/actorshutdown","title":"MCAsyncOperationCancelledError.Code.actorShutdown","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorActorShutdown"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"abstract":[{"text":"Error category for errors triggered when the operation failed because","type":"text"},{"type":"text","text":" "},{"text":"it was abandoned for various reasons.","type":"text"}],"title":"MCAsyncOperationCancelledError.Code","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","navigatorTitle":[{"kind":"identifier","text":"Code"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCAsyncOperationCancelledErrorActorShutdown","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorActorShutdown"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MCAsyncOperationCancelledErrorActorShutdown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"MCAsyncOperationCancelledErrorActorShutdown","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1actorShutdown\/title"},{"value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorActorShutdown"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1actorShutdown\/fragments"},{"value":"MCAsyncOperationCancelledError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MCAsyncOperationCancelledError","kind":"identifier"}]}]}]}