{"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@E@MCGenericError@MCGenericErrorInvalidState","title":"MCGenericError.Code.invalidState","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorInvalidState"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidState"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidstate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidState","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Invalid state of the client."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct":{"navigatorTitle":[{"text":"MCGenericError","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCGenericError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct","title":"MCGenericError"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidState":{"navigatorTitle":[{"text":"MCGenericErrorInvalidState","kind":"identifier"}],"title":"MCGenericError.Code.invalidState","abstract":[{"type":"text","text":"Invalid state of the client."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidState","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidstate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidState"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"title":"MCGenericError.Code","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","kind":"symbol","abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MCGenericErrorInvalidState","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MCGenericErrorInvalidState","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MCGenericErrorInvalidState"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCGenericErrorInvalidState","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidState\/title"},{"op":"replace","value":[{"text":"MCGenericErrorInvalidState","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidState\/fragments"},{"op":"replace","value":"MCGenericError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCGenericError"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments"}]}]}