{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"temporalLayerId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"temporalLayerId","symbolKind":"property","externalID":"c:objc(cs)MCRTSRemoteTrackLayer(py)temporalLayerId","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"temporalLayerId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"temporalLayerId"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/temporalLayerId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/temporallayerid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/temporallayerid"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"title":"MCRTSRemoteTrackLayer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","abstract":[{"text":"Represents an layer entry in the layers event received by the media server.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","type":"topic","navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/temporalLayerId":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/temporallayerid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"temporalLayerId","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/temporalLayerId","title":"temporalLayerId","role":"symbol","abstract":[],"navigatorTitle":[{"text":"temporalLayerId","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"temporalLayerId","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"temporalLayerId","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"text":"temporalLayerId","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCRTSRemoteTrackLayer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1temporalLayerId\/title","op":"replace","value":"temporalLayerId"},{"value":[{"text":"temporalLayerId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1temporalLayerId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}