{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsdkconfiguration\/configure(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsdkconfiguration\/configure(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"audioConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration","text":"MCAudioConfiguration","preciseIdentifier":"c:objc(cs)MCAudioConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"metadata":{"externalID":"c:objc(cs)MCSDKConfiguration(cm)configure:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioConfiguration","text":"MCAudioConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"configure:"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","role":"symbol","title":"configure(_:)","platforms":[]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSDKConfiguration\/configure(_:)"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSDKConfiguration"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration","title":"MCAudioConfiguration","abstract":[{"text":"Global Audio Configuration object.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCAudioConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioConfiguration"}],"url":"\/documentation\/millicastsdk\/mcaudioconfiguration"},"doc://MillicastSDK/documentation/MillicastSDK/MCSDKConfiguration":{"title":"MCSDKConfiguration","abstract":[{"type":"text","text":"Global SDK Configuration. Use this class to modify"},{"type":"text","text":" "},{"type":"text","text":"global behaviour in the SDK."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSDKConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"MCSDKConfiguration"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcsdkconfiguration","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSDKConfiguration"},"doc://MillicastSDK/documentation/MillicastSDK/MCSDKConfiguration/configure(_:)":{"title":"configure(_:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCAudioConfiguration","text":"MCAudioConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"configure:"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSDKConfiguration\/configure(_:)","url":"\/documentation\/millicastsdk\/mcsdkconfiguration\/configure(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configure:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"configure:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"configure:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioConfiguration","preciseIdentifier":"c:objc(cs)MCAudioConfiguration","text":"MCAudioConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"audioConfiguration","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"MCAudioConfiguration","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioConfiguration\/fragments","value":[{"text":"MCAudioConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSDKConfiguration\/title","value":"MCSDKConfiguration","op":"replace"},{"op":"replace","value":[{"text":"MCSDKConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSDKConfiguration\/fragments"},{"value":"configure:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSDKConfiguration~1configure(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configure:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSDKConfiguration~1configure(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}