{"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"projectWithRTSRemoteAudioTrack:completionHandler:","kind":"identifier"}],"externalID":"c:objc(cs)MCWebrtcRemoteAudioTrack(im)projectWithRTSRemoteAudioTrack:completionHandler:","symbolKind":"method","role":"symbol","title":"project(rtsRemoteAudioTrack:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rtsRemoteAudioTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtsRemoteAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteAudioTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the RTS track which will be projected onto this webrtc"},{"type":"text","text":" "},{"type":"text","text":"track."}]}],"name":"rtsRemoteAudioTrack"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}]}],"name":"completionHandler"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Note that unlike the simple API for the RTS track, this API is more","type":"text"},{"text":" ","type":"text"},{"text":"flexible, but requires more handling by the application. Specifically, the","type":"text"},{"text":" ","type":"text"},{"text":"track will not be unprojected automatically when the RTS track goes","type":"text"},{"text":" ","type":"text"},{"text":"inactive (and will not require repeating project operation when it goes","type":"text"},{"text":" ","type":"text"},{"text":"active again)","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can project the same RTS track onto multiple webrtc logical tracks.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack"]]},"abstract":[{"text":"Enable the track and project from given RTS track.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/project(rtsRemoteAudioTrack:completionHandler:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/project(rtsremoteaudiotrack:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/project(rtsremoteaudiotrack:completionhandler:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack/project(rtsRemoteAudioTrack:completionHandler:)":{"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/project(rtsremoteaudiotrack:completionhandler:)","kind":"symbol","role":"symbol","abstract":[{"text":"Enable the track and project from given RTS track.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"project"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtsRemoteAudioTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteAudioTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"projectWithRTSRemoteAudioTrack:completionHandler:"}],"title":"project(rtsRemoteAudioTrack:completionHandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/project(rtsRemoteAudioTrack:completionHandler:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"kind":"symbol","abstract":[{"text":"The webrtc logical track’s audio interface.","type":"text"}],"title":"MCWebrtcRemoteAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteAudioTrack":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"abstract":[{"type":"text","text":"The RTS logical track’s audio interface."}],"title":"MCRTSRemoteAudioTrack"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"projectWithRTSRemoteAudioTrack:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"projectWithRTSRemoteAudioTrack:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"projectWithRTSRemoteAudioTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCRTSRemoteAudioTrack","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack"},{"text":" *) ","kind":"text"},{"text":"rtsRemoteAudioTrack","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1project(rtsRemoteAudioTrack:completionHandler:)\/title","value":"projectWithRTSRemoteAudioTrack:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1project(rtsRemoteAudioTrack:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"projectWithRTSRemoteAudioTrack:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title","value":"MCWebrtcRemoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments","value":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/title","value":"MCRTSRemoteAudioTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/fragments","value":[{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}]}]}]}