{"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/pause_count"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/pause_count"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pause_count","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The total number of video pauses. See ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","isActive":true,"type":"reference"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause_count"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"pause_count"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats(py)pause_count","role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"pause_count","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause_count"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"title":"MCInboundRtpStreamStats","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/pause_count":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause_count"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"title":"pause_count","navigatorTitle":[{"kind":"identifier","text":"pause_count"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pause_count","kind":"symbol","abstract":[{"type":"text","text":"The total number of video pauses. See "},{"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","isActive":true}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/pause_count"},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-pausecount":{"title":"pauseCount","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","titleInlineContent":[{"text":"pauseCount","type":"text"}],"type":"link"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"pause_count"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"pause_count"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsigned long","kind":"typeIdentifier","preciseIdentifier":"c:l"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause_count"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pause_count\/title","value":"pause_count","op":"replace"},{"op":"replace","value":[{"text":"pause_count","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pause_count\/fragments"}]}]}