{"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState\/idle","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/idle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcconnectionstate\/idle"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}]}]}],"abstract":[{"type":"text","text":"The initial state of the socket. This state will be entered after graceful close."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@MCConnectionState@MCConnectionStateIdle","navigatorTitle":[{"kind":"identifier","text":"MCConnectionStateIdle"}],"title":"MCConnectionState.idle"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCConnectionState/idle":{"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState\/idle","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The initial state of the socket. This state will be entered after graceful close."}],"title":"MCConnectionState.idle","url":"\/documentation\/millicastsdk\/mcconnectionstate\/idle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idle","kind":"identifier"}],"navigatorTitle":[{"text":"MCConnectionStateIdle","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCConnectionState":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCConnectionState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCConnectionState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MCConnectionState","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcconnectionstate","kind":"symbol","title":"MCConnectionState","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"MCConnectionStateIdle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCConnectionStateIdle"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MCConnectionStateIdle","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState~1idle\/title","op":"replace","value":"MCConnectionStateIdle"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState~1idle\/fragments","op":"replace","value":[{"text":"MCConnectionStateIdle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState\/title","op":"replace","value":"MCConnectionState"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState\/fragments","op":"replace","value":[{"text":"MCConnectionState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCConnectionState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCConnectionState"}]}]}]}