{"abstract":[{"text":"The timestamp of the last received packet. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp","type":"reference","isActive":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/last_packet_received_timestamp"]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/last_packet_received_timestamp"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"last_packet_received_timestamp"}],"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"last_packet_received_timestamp"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","title":"last_packet_received_timestamp","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)last_packet_received_timestamp"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"last_packet_received_timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/last_packet_received_timestamp","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/last_packet_received_timestamp":{"navigatorTitle":[{"text":"last_packet_received_timestamp","kind":"identifier"}],"abstract":[{"text":"The timestamp of the last received packet. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp","type":"reference","isActive":true}],"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/last_packet_received_timestamp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"last_packet_received_timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"role":"symbol","title":"last_packet_received_timestamp","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/last_packet_received_timestamp"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"title":"MCInboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp","type":"link","titleInlineContent":[{"text":"lastPacketReceivedTimestamp","type":"text"}],"title":"lastPacketReceivedTimestamp","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"last_packet_received_timestamp","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"last_packet_received_timestamp"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"last_packet_received_timestamp"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1last_packet_received_timestamp\/title","value":"last_packet_received_timestamp"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1last_packet_received_timestamp\/fragments","value":[{"kind":"identifier","text":"last_packet_received_timestamp"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats"},{"value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}