{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/abandoned"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"MCAsyncOperationCancelledError.Code.abandoned","symbolKind":"case","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorAbandoned","kind":"identifier"}],"externalID":"c:@E@MCAsyncOperationCancelledError@MCAsyncOperationCancelledErrorAbandoned","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"abandoned","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/abandoned"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/abandoned"]}],"kind":"symbol","abstract":[{"type":"text","text":"Operation was cancelled for unspecified reasons."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"abandoned"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/abandoned":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"abandoned","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MCAsyncOperationCancelledErrorAbandoned","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/abandoned","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/abandoned","title":"MCAsyncOperationCancelledError.Code.abandoned","abstract":[{"type":"text","text":"Operation was cancelled for unspecified reasons."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","role":"symbol","url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","abstract":[{"text":"Error category for errors triggered when the operation failed because","type":"text"},{"text":" ","type":"text"},{"text":"it was abandoned for various reasons.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"MCAsyncOperationCancelledError.Code","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCAsyncOperationCancelledErrorAbandoned"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAbandoned"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorAbandoned"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1abandoned\/title","value":"MCAsyncOperationCancelledErrorAbandoned","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1abandoned\/fragments","value":[{"text":"MCAsyncOperationCancelledErrorAbandoned","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MCAsyncOperationCancelledError","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCAsyncOperationCancelledError"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}