{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/didchangevideosize(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/didchangevideosize(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeVideoSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","extendedModule":"MillicastSDK","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeVideoSize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didChangeVideoSize:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@CM@MillicastSDK@objc(cs)MCAcceleratedVideoUIView(im)didChangeVideoSize:","roleHeading":"Instance Method","title":"didChangeVideoSize(_:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MCAcceleratedVideoRendererDelegate.didChangeVideoSize(_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"abstract":[{"text":"UIView that uses Metal as a backend for rendering.","type":"text"}],"role":"symbol","title":"MCAcceleratedVideoUIView","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView/didChangeVideoSize(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/didChangeVideoSize(_:)","title":"didChangeVideoSize(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChangeVideoSize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/didchangevideosize(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didChangeVideoSize:"}],"role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView/MCAcceleratedVideoRendererDelegate-Implementations":{"abstract":[],"title":"MCAcceleratedVideoRendererDelegate Implementations","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mcacceleratedvideorendererdelegate-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"didChangeVideoSize:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didChangeVideoSize:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didChangeVideoSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","op":"replace","value":"MCAcceleratedVideoUIView"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","op":"replace","value":[{"text":"MCAcceleratedVideoUIView","kind":"identifier"}]},{"op":"replace","value":"didChangeVideoSize:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeVideoSize:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1didChangeVideoSize(_:)\/fragments"}]}]}