{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setDelegate(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"]]},"abstract":[{"text":"Set a delegate that receives log messages.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate","text":"MCLoggerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCLoggerDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate"},{"type":"text","text":" that receives log messages."}],"type":"paragraph"}],"name":"delegate"}]}],"metadata":{"role":"symbol","title":"setDelegate(_:)","navigatorTitle":[{"text":"setDelegate:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Type Method","externalID":"c:objc(cs)MCLogger(cm)setDelegate:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDelegate","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"MCLoggerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCLoggerDelegate"},{"text":")","kind":"text"}],"symbolKind":"method"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mclogger\/setdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mclogger\/setdelegate(_:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/setDelegate(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setDelegate:"}],"url":"\/documentation\/millicastsdk\/mclogger\/setdelegate(_:)","kind":"symbol","title":"setDelegate(_:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setDelegate(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)MCLoggerDelegate","kind":"typeIdentifier","text":"MCLoggerDelegate"},{"kind":"text","text":")"}],"abstract":[{"text":"Set a delegate that receives log messages.","type":"text"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLoggerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLoggerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate that receives events from "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger","isActive":true}],"type":"topic","navigatorTitle":[{"text":"MCLoggerDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MCLoggerDelegate","url":"\/documentation\/millicastsdk\/mcloggerdelegate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLoggerDelegate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCLogger","kind":"identifier"}],"abstract":[{"text":"Class that is responsible for managing SDK logs.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mclogger","kind":"symbol","title":"MCLogger","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"setDelegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<MCLoggerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCLoggerDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setDelegate(_:)\/title","op":"replace","value":"setDelegate:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setDelegate(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setDelegate:","kind":"identifier"}]},{"value":"MCLoggerDelegate","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate\/title"},{"value":[{"kind":"identifier","text":"MCLoggerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLoggerDelegate\/fragments"},{"value":"MCLogger","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/title"},{"value":[{"text":"MCLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}