{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mclogger\/setloglevelwithsdk(_:webrtc:websocket:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mclogger\/setloglevelwithsdk(_:webrtc:websocket:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)MCLogger(cm)setLogLevelWithSdk:Webrtc:Websocket:","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"setLogLevelWithSdk:Webrtc:Websocket:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"setLogLevelWithSdk(_:webrtc:websocket:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLogLevelWithSdk","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webrtc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"websocket","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLogLevelWithSdk","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sdkLogLevel","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webrtc","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webrtcLogLevel","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"websocket","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"websocketLogLevel","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MCLogLevel","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"MCLogLevel"},{"type":"text","text":" sets the log level for the SDK."}]}],"name":"Sdk"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"MCLogLevel"},{"type":"text","text":" sets the log level for Webrtc."}]}],"name":"Webrtc"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"code":"MCLogLevel","type":"codeVoice"},{"text":" sets the log level for Websocket.","type":"text"}],"type":"paragraph"}],"name":"Websocket"}]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setLogLevelWithSdk(_:webrtc:websocket:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Set the LogLevel for the SDK\/Webrtc\/Websocket modules","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger/setLogLevelWithSdk(_:webrtc:websocket:)":{"role":"symbol","title":"setLogLevelWithSdk(_:webrtc:websocket:)","navigatorTitle":[{"text":"setLogLevelWithSdk:Webrtc:Websocket:","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mclogger\/setloglevelwithsdk(_:webrtc:websocket:)","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger\/setLogLevelWithSdk(_:webrtc:websocket:)","kind":"symbol","abstract":[{"text":"Set the LogLevel for the SDK\/Webrtc\/Websocket modules","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLogLevelWithSdk"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier","text":"MCLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webrtc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier","text":"MCLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"websocket"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MCLogLevel","kind":"typeIdentifier","text":"MCLogLevel"},{"kind":"text","text":")"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogger":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCLogger","kind":"identifier"}],"abstract":[{"text":"Class that is responsible for managing SDK logs.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MCLogger","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mclogger","kind":"symbol","title":"MCLogger","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogger"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCLogLevel":{"type":"topic","kind":"symbol","abstract":[{"text":"The log message’s level","type":"text"}],"navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}],"title":"MCLogLevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCLogLevel","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","url":"\/documentation\/millicastsdk\/mcloglevel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setLogLevelWithSdk:Webrtc:Websocket:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setLogLevelWithSdk:Webrtc:Websocket:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setLogLevelWithSdk:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel"},{"text":") ","kind":"text"},{"text":"sdkLogLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"Webrtc:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel"},{"text":") ","kind":"text"},{"text":"webrtcLogLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"Websocket:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCLogLevel","preciseIdentifier":"c:@E@MCLogLevel"},{"text":") ","kind":"text"},{"text":"websocketLogLevel","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"setLogLevelWithSdk:Webrtc:Websocket:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setLogLevelWithSdk(_:webrtc:websocket:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setLogLevelWithSdk:Webrtc:Websocket:","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger~1setLogLevelWithSdk(_:webrtc:websocket:)\/fragments"},{"op":"replace","value":"MCLogger","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCLogger"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogger\/fragments"},{"op":"replace","value":"MCLogLevel","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/title"},{"op":"replace","value":[{"text":"MCLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCLogLevel\/fragments"}]}]}