{"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"header_bytes_sent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"header_bytes_sent","externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)header_bytes_sent","navigatorTitle":[{"text":"header_bytes_sent","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/header_bytes_sent","interfaceLanguage":"swift"},"abstract":[{"text":"The number of bytes sent for headers. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","isActive":true,"type":"reference"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/header_bytes_sent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/header_bytes_sent"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"header_bytes_sent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/header_bytes_sent":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/header_bytes_sent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"header_bytes_sent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/header_bytes_sent","type":"topic","title":"header_bytes_sent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"header_bytes_sent"}],"abstract":[{"text":"The number of bytes sent for headers. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent"}],"kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-headerbytessent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-headerbytessent","title":"headerBytesSent","titleInlineContent":[{"text":"headerBytesSent","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","title":"MCOutboundRtpStreamStats","type":"topic","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"header_bytes_sent","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"header_bytes_sent","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned long long","kind":"typeIdentifier","preciseIdentifier":"c:k"},{"text":" ","kind":"text"},{"text":"header_bytes_sent","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1header_bytes_sent\/title","value":"header_bytes_sent"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1header_bytes_sent\/fragments","op":"replace","value":[{"kind":"identifier","text":"header_bytes_sent"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","op":"replace","value":"MCOutboundRtpStreamStats"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","op":"replace","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/navigatorTitle","op":"replace","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}