{"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_packets_sent","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"retransmitted_packets_sent","role":"symbol","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)retransmitted_packets_sent","navigatorTitle":[{"kind":"identifier","text":"retransmitted_packets_sent"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_packets_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The number of retransmitted packets. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_packets_sent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_packets_sent"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_packets_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","title":"retransmittedPacketsSent","titleInlineContent":[{"text":"retransmittedPacketsSent","type":"text"}],"type":"link"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"navigatorTitle":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","title":"MCOutboundRtpStreamStats","type":"topic","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/retransmitted_packets_sent":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/retransmitted_packets_sent","navigatorTitle":[{"kind":"identifier","text":"retransmitted_packets_sent"}],"url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/retransmitted_packets_sent","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmitted_packets_sent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"title":"retransmitted_packets_sent","role":"symbol","abstract":[{"text":"The number of retransmitted packets. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent","type":"reference"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"retransmitted_packets_sent","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"retransmitted_packets_sent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned long long","kind":"typeIdentifier","preciseIdentifier":"c:k"},{"text":" ","kind":"text"},{"text":"retransmitted_packets_sent","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/navigatorTitle","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_packets_sent\/title","value":"retransmitted_packets_sent","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1retransmitted_packets_sent\/fragments","value":[{"text":"retransmitted_packets_sent","kind":"identifier"}],"op":"replace"}]}]}