{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"audio","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@E@MCRemoteTrackKind@MCRemoteTrackKindAudio","role":"symbol","symbolKind":"case","title":"MCRemoteTrackKind.audio","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audio"}],"roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCRemoteTrackKindAudio","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind"]]},"sections":[],"abstract":[{"text":"Track is an audio track.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremotetrackkind\/audio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremotetrackkind\/audio"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind\/audio","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteTrackKind":{"title":"MCRemoteTrackKind","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCRemoteTrackKind","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum specifying the type of the remote track."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","navigatorTitle":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteTrackKind/audio":{"title":"MCRemoteTrackKind.audio","url":"\/documentation\/millicastsdk\/mcremotetrackkind\/audio","navigatorTitle":[{"text":"MCRemoteTrackKindAudio","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind\/audio","role":"symbol","kind":"symbol","abstract":[{"text":"Track is an audio track.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"audio","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCRemoteTrackKindAudio"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCRemoteTrackKindAudio"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCRemoteTrackKindAudio"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title","value":"MCRemoteTrackKind","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments","value":[{"kind":"identifier","text":"MCRemoteTrackKind"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind~1audio\/title","value":"MCRemoteTrackKindAudio","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind~1audio\/fragments","value":[{"text":"MCRemoteTrackKindAudio","kind":"identifier"}],"op":"replace"}]}]}