{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","preciseIdentifier":"c:@E@MCVideoType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities\/format","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities"]]},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/format"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideocapabilities\/format"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"format","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCVideoType","preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:objc(cs)MCVideoCapabilities(py)format","roleHeading":"Instance Property","title":"format","modules":[{"name":"MillicastSDK"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The pixel format to use for the capture.","type":"text"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoCapabilities/format":{"type":"topic","abstract":[{"type":"text","text":"The pixel format to use for the capture."}],"title":"format","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities\/format","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCVideoType","preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"format","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideocapabilities\/format"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoCapabilities":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoCapabilities"}],"title":"MCVideoCapabilities","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoCapabilities"}],"abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"url":"\/documentation\/millicastsdk\/mcvideotype","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"title":"MCVideoType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"format"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"format","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier","text":"MCVideoType"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities~1format\/title","op":"replace","value":"format"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities~1format\/fragments","op":"replace","value":[{"kind":"identifier","text":"format"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/title","op":"replace","value":"MCVideoCapabilities"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments","value":[{"text":"MCVideoCapabilities","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title","value":"MCVideoType"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments","value":[{"text":"MCVideoType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}