{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"apiUrl","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The subscribe API URL."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/apiUrl"},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MCSubscriberCredentials(py)apiUrl","symbolKind":"property","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiUrl","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"apiUrl"}],"title":"apiUrl"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/apiurl"]},{"paths":["\/documentation\/millicastsdk\/mcsubscribercredentials\/apiurl"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials","kind":"symbol","abstract":[{"text":"The Credentials interface represent the credentials required for","type":"text"},{"type":"text","text":" "},{"text":"connecting and subscribing to a Millicast stream. See the ","type":"text"},{"type":"reference","identifier":"https:\/\/dash.millicast.com\/docs.html","isActive":true}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSubscriberCredentials","kind":"identifier"}],"title":"MCSubscriberCredentials","url":"\/documentation\/millicastsdk\/mcsubscribercredentials","navigatorTitle":[{"text":"MCSubscriberCredentials","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberCredentials/apiUrl":{"navigatorTitle":[{"text":"apiUrl","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscribercredentials\/apiurl","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberCredentials\/apiUrl","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiUrl"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The subscribe API URL."}],"title":"apiUrl","role":"symbol","kind":"symbol","type":"topic"},"https://dash.millicast.com/docs.html":{"titleInlineContent":[{"type":"text","text":"Streaming Dashboard"}],"url":"https:\/\/dash.millicast.com\/docs.html","identifier":"https:\/\/dash.millicast.com\/docs.html","type":"link","title":"Streaming Dashboard"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"apiUrl","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"apiUrl","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"apiUrl"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/title","value":"MCSubscriberCredentials"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials\/fragments","value":[{"kind":"identifier","text":"MCSubscriberCredentials"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1apiUrl\/title","value":"apiUrl","op":"replace"},{"value":[{"kind":"identifier","text":"apiUrl"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberCredentials~1apiUrl\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}