{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetMaxTemporalLayerId","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)resetMaxTemporalLayerId","title":"resetMaxTemporalLayerId()","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetMaxTemporalLayerId"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resetMaxTemporalLayerId"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxTemporalLayerId()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Reset the max temporal layer ID"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetmaxtemporallayerid()"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetmaxtemporallayerid()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetMaxTemporalLayerId()":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetmaxtemporallayerid()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxTemporalLayerId()","navigatorTitle":[{"text":"resetMaxTemporalLayerId","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Reset the max temporal layer ID"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetMaxTemporalLayerId"},{"kind":"text","text":"()"}],"title":"resetMaxTemporalLayerId()"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","kind":"symbol","title":"MCRTSRemoteVideoTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the client wants to inform the media server to select."}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"resetMaxTemporalLayerId","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetMaxTemporalLayerId"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"resetMaxTemporalLayerId","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxTemporalLayerId()\/title","value":"resetMaxTemporalLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxTemporalLayerId()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetMaxTemporalLayerId"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","op":"replace","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}