{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetSpatialLayerId","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"sections":[],"kind":"symbol","metadata":{"title":"resetSpatialLayerId()","role":"symbol","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer(im)resetSpatialLayerId","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetSpatialLayerId"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"resetSpatialLayerId","kind":"identifier"}]},"abstract":[{"text":"Reset the spatial layer ID.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetspatiallayerid()"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetspatiallayerid()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetSpatialLayerId()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetSpatialLayerId()":{"title":"resetSpatialLayerId()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetSpatialLayerId","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"resetSpatialLayerId","kind":"identifier"}],"abstract":[{"text":"Reset the spatial layer ID.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetSpatialLayerId()","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetspatiallayerid()","role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","kind":"symbol","title":"MCRTSRemoteVideoTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the client wants to inform the media server to select."}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"resetSpatialLayerId","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"resetSpatialLayerId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"resetSpatialLayerId","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"resetSpatialLayerId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetSpatialLayerId()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"resetSpatialLayerId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetSpatialLayerId()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","op":"replace","value":"MCRTSRemoteVideoTrackLayer"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"op":"replace"}]}]}