{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/create()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcndirenderer\/create()"]},{"paths":["\/documentation\/millicastsdk\/mcndirenderer\/create()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Creates an NDI renderer."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCNdiRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer","preciseIdentifier":"c:objc(cs)MCNdiRenderer"},{"kind":"text","text":"!"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"An NDI renderer.","type":"text"}],"type":"paragraph"}]}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","title":"create()","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"create"}],"externalID":"c:objc(cs)MCNdiRenderer(cm)create","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCNdiRenderer","text":"MCNdiRenderer"},{"text":"!","kind":"text"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCNdiRenderer":{"type":"topic","abstract":[{"text":"The  class is responsible for rendering video as an NDI source. To render audio with NDI, use","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback"},{"text":" with the NDI output instead.","type":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcndirenderer","role":"symbol","title":"MCNdiRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer","navigatorTitle":[{"kind":"identifier","text":"MCNdiRenderer"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCNdiRenderer"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"role":"symbol","abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"text":" ","type":"text"},{"text":"This class inherits the Source class, however this is not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayback","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"title":"MCAudioPlayback","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCNdiRenderer/create()":{"type":"topic","abstract":[{"type":"text","text":"Creates an NDI renderer."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcndirenderer\/create()","role":"symbol","title":"create()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/create()","navigatorTitle":[{"kind":"identifier","text":"create"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MCNdiRenderer","text":"MCNdiRenderer","kind":"typeIdentifier"},{"kind":"text","text":"!"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"create","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"create"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)MCNdiRenderer","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer","text":"MCNdiRenderer"},{"kind":"text","text":" *) "},{"text":"create","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MCNdiRenderer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer\/fragments","op":"replace","value":[{"text":"MCNdiRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1create()\/title","value":"create","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1create()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"create"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}