{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/debug"},"metadata":{"modules":[{"name":"MillicastSDK"}],"symbolKind":"case","roleHeading":"Case","title":"MCLogLevel.debug","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelDebug"}],"externalID":"c:@E@MCLogLevel@MCLogLevelDebug"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel"]]},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcloglevel\/debug"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcloglevel\/debug"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Debug message."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel/debug":{"url":"\/documentation\/millicastsdk\/mcloglevel\/debug","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCLogLevelDebug"}],"abstract":[{"type":"text","text":"Debug message."}],"title":"MCLogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel\/debug","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogLevel"}],"title":"MCLogLevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogLevel","kind":"symbol","navigatorTitle":[{"text":"MCLogLevel","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcloglevel","abstract":[{"type":"text","text":"The log message’s level"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCLogLevelDebug"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCLogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCLogLevelDebug"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MCLogLevelDebug","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1debug\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"MCLogLevelDebug"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/title","value":"MCLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogLevel\/fragments","op":"replace","value":[{"text":"MCLogLevel","kind":"identifier"}]}]}]}