{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"total_squared_inter_frame_delay"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)total_squared_inter_frame_delay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_squared_inter_frame_delay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"total_squared_inter_frame_delay","modules":[{"name":"MillicastSDK"}]},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_squared_inter_frame_delay","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_squared_inter_frame_delay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_squared_inter_frame_delay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_squared_inter_frame_delay"]}],"abstract":[{"type":"text","text":"The total squared inter-frame delay during video transmission. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay","type":"reference","isActive":true}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats":{"abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"kind":"symbol","title":"MCInboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCInboundRtpStreamStats/total_squared_inter_frame_delay":{"title":"total_squared_inter_frame_delay","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_squared_inter_frame_delay","abstract":[{"text":"The total squared inter-frame delay during video transmission. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay","type":"reference"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_squared_inter_frame_delay","role":"symbol","navigatorTitle":[{"text":"total_squared_inter_frame_delay","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_squared_inter_frame_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay","type":"link","title":"totalSquaredInterFrameDelay","titleInlineContent":[{"type":"text","text":"totalSquaredInterFrameDelay"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"total_squared_inter_frame_delay","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"total_squared_inter_frame_delay"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_squared_inter_frame_delay"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments"},{"op":"replace","value":"total_squared_inter_frame_delay","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_squared_inter_frame_delay\/title"},{"op":"replace","value":[{"text":"total_squared_inter_frame_delay","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_squared_inter_frame_delay\/fragments"}]}]}