{"abstract":[{"type":"text","text":"Enable the track with default promote behavour, which is false."}],"sections":[],"metadata":{"navigatorTitle":[{"text":"enableWithRenderer:layer:completionHandler:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)MCRTSRemoteVideoTrack(im)enableWithRenderer:layer:completionHandler:","modules":[{"name":"MillicastSDK"}],"role":"symbol","roleHeading":"Instance Method","title":"enable(renderer:layer:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","text":"MCVideoRenderer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"kind":"text","text":"("},{"text":"renderer","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"kind":"keyword","text":"@escaping"},{"text":" ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The renderer to receive video frames.","type":"text"}]}],"name":"renderer"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"set this track to be the main video track. The main video"},{"text":" ","type":"text"},{"text":"track has highest priority for bandwidth assignment when SVC layers are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"managed by the service."}]}],"name":"promote"},{"content":[{"inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}],"type":"paragraph"}],"name":"completionHandler"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:completionHandler:)"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","type":"topic","title":"add(_:)","abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"text":" ","type":"text"},{"text":"Each one will be called when a new frame becomes available.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"text":")!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"type":"topic","abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"text":" ","type":"text"},{"type":"text","text":"applications. Used in "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer","title":"MCVideoRenderer","role":"symbol","navigatorTitle":[{"text":"MCVideoRenderer","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"title":"MCRTSRemoteVideoTrackLayer","role":"symbol","abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:layer:completionHandler:)":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:completionHandler:)","abstract":[{"text":"Enable the track with default promote behavour, which is false.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"enableWithRenderer:layer:completionHandler:","kind":"identifier"}],"type":"topic","title":"enable(renderer:layer:completionHandler:)","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"enableWithRenderer:layer:completionHandler:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enableWithRenderer:layer:completionHandler:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"enableWithRenderer:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer","text":"id<MCVideoRenderer>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"renderer","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer"},{"text":" *) ","kind":"text"},{"text":"layer","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"MCRTSRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","op":"replace","value":"addRenderer:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addRenderer:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"value":"MCRTSRemoteVideoTrackLayer","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:completionHandler:)\/title","op":"replace","value":"enableWithRenderer:layer:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:layer:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}