{"abstract":[{"text":"The minimum bitrate, in kilobits per second.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minBitrateKbps","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/minbitratekbps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcbitratesettings\/minbitratekbps"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MCBitrateSettings(py)minBitrateKbps","navigatorTitle":[{"text":"minBitrateKbps","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBitrateKbps"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"minBitrateKbps","role":"symbol"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/minBitrateKbps","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings":{"abstract":[{"type":"text","text":"The BitrateSettings class allows customizing bitrate settings for publishing streams."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcbitratesettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCBitrateSettings","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings","navigatorTitle":[{"kind":"identifier","text":"MCBitrateSettings"}],"type":"topic","kind":"symbol","title":"MCBitrateSettings"},"doc://MillicastSDK/documentation/MillicastSDK/MCBitrateSettings/minBitrateKbps":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcbitratesettings\/minbitratekbps","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minBitrateKbps","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"minBitrateKbps","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCBitrateSettings\/minBitrateKbps","navigatorTitle":[{"text":"minBitrateKbps","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The minimum bitrate, in kilobits per second."}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"minBitrateKbps"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"minBitrateKbps"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBitrateKbps"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MCBitrateSettings","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings\/fragments","value":[{"kind":"identifier","text":"MCBitrateSettings"}]},{"value":"minBitrateKbps","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1minBitrateKbps\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCBitrateSettings~1minBitrateKbps\/fragments","value":[{"kind":"identifier","text":"minBitrateKbps"}],"op":"replace"}]}]}