{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asAudio()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned.","type":"text"}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asAudio","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"asAudio"}],"externalID":"c:objc(cs)MCWebrtcRemoteTrack(im)asAudio","role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"asAudio()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asAudio"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","text":"MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Nil if the track is not of an audio type"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asaudio()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asaudio()"]}],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/asAudio()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/asAudio()","title":"asAudio()","type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/asaudio()","abstract":[{"type":"text","text":"Cast the track to it’s true type if it is audio, otherwise, nil will be returned."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"asAudio","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asAudio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","kind":"typeIdentifier","text":"MCWebrtcRemoteAudioTrack"},{"kind":"text","text":"?"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","title":"MCWebrtcRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"type":"topic","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","title":"MCWebrtcRemoteAudioTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","abstract":[{"text":"The webrtc logical track’s audio interface.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"asAudio","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"asAudio","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteAudioTrack","text":"MCWebrtcRemoteAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"asAudio"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asAudio()\/title","op":"replace","value":"asAudio"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1asAudio()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asAudio","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace","value":"MCWebrtcRemoteTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"op":"replace"},{"value":"MCWebrtcRemoteAudioTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title"},{"value":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments"}]}]}