{"abstract":[{"type":"text","text":"The current MID of this track."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is implemented for convenience of simple applications, but"},{"text":" ","type":"text"},{"type":"text","text":"its usage is discouraged. The applications requiring to map webrtc stats to"},{"text":" ","type":"text"},{"type":"text","text":"specific tracks should maintain a mid:track map, updated based on the mid"},{"text":" ","type":"text"},{"type":"text","text":"update events from the tracks. Such an implementation would allow for most"},{"type":"text","text":" "},{"type":"text","text":"efficient mapping of the stats back to the tracks."}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentMID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"currentMID","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"currentMID","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)MCWebrtcRemoteTrack(py)currentMID"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/currentMID"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/currentmid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/currentmid"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/currentMID":{"navigatorTitle":[{"text":"currentMID","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/currentmid","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/currentMID","title":"currentMID","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The current MID of this track."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","title":"MCWebrtcRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"type":"topic","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"currentMID","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentMID"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"currentMID"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"currentMID","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1currentMID\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1currentMID\/fragments","value":[{"kind":"identifier","text":"currentMID"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","value":"MCWebrtcRemoteTrack"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments"}]}]}