{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/kind"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/kind"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MCRemoteTrackKind","kind":"typeIdentifier","text":"MCRemoteTrackKind"}],"externalID":"c:objc(cs)MCWebrtcRemoteTrack(py)kind","navigatorTitle":[{"kind":"identifier","text":"kind"}],"title":"kind","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/kind","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","abstract":[{"text":"Either an Audio or Video track.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","title":"MCWebrtcRemoteTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"type":"topic","navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteTrackKind":{"abstract":[{"text":"Enum specifying the type of the remote track.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcremotetrackkind","title":"MCRemoteTrackKind","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCRemoteTrackKind","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack/kind":{"abstract":[{"type":"text","text":"Either an Audio or Video track."}],"title":"kind","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/kind","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/kind","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCRemoteTrackKind","text":"MCRemoteTrackKind"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"kind","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"kind","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"kind","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@MCRemoteTrackKind","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteTrackKind","text":"MCRemoteTrackKind"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kind"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace","value":"MCWebrtcRemoteTrack"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","op":"replace"},{"value":"MCRemoteTrackKind","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/title"},{"op":"replace","value":[{"text":"MCRemoteTrackKind","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteTrackKind\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1kind\/title","value":"kind"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack~1kind\/fragments","op":"replace","value":[{"text":"kind","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}