{"abstract":[{"type":"text","text":"Initializes the source with a name to identify the source."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)RPScreenRecorder","text":"RPScreenRecorder"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The source name","type":"text"}],"type":"paragraph"}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A ReplayKit recorder.","type":"text"}]}],"name":"recorder"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(name:recorder:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(name:recorder:)","navigatorTitle":[{"kind":"identifier","text":"initWithName:recorder:"}],"externalID":"c:objc(cs)MCAppShareSource(im)initWithName:recorder:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)RPScreenRecorder","text":"RPScreenRecorder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource\/init(name:recorder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcappsharesource\/init(name:recorder:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource/init(name:recorder:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RPScreenRecorder","preciseIdentifier":"c:objc(cs)RPScreenRecorder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcappsharesource\/init(name:recorder:)","abstract":[{"type":"text","text":"Initializes the source with a name to identify the source."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource\/init(name:recorder:)","title":"init(name:recorder:)","role":"symbol","navigatorTitle":[{"text":"initWithName:recorder:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAppShareSource":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAppShareSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAppShareSource"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAppShareSource"}],"title":"MCAppShareSource","url":"\/documentation\/millicastsdk\/mcappsharesource","abstract":[{"text":"Uses Replaykit to capture the screen of the application.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithName:recorder:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:recorder:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recorder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RPScreenRecorder","preciseIdentifier":"c:objc(cs)RPScreenRecorder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"recorder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source name"}]}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A ReplayKit recorder.","type":"text"}]}],"name":"recorder"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(name:recorder:)\/title","value":"initWithName:recorder:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource~1init(name:recorder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithName:recorder:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/title","value":"MCAppShareSource","op":"replace"},{"op":"replace","value":[{"text":"MCAppShareSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCAppShareSource"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAppShareSource\/navigatorTitle"}]}]}