{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initPlayback"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/playbacksource\/initplayback()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/playbacksource\/initplayback()"]}],"abstract":[{"type":"text","text":"Initializes the playback device."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource\/initPlayback()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initPlayback","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initPlayback"}],"modules":[{"name":"MillicastSDK"}],"title":"initPlayback()","role":"symbol","externalID":"c:objc(pl)PlaybackSource(im)initPlayback","required":true},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/PlaybackSource":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybackSource"}],"url":"\/documentation\/millicastsdk\/playbacksource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource","abstract":[{"type":"text","text":"Responsible for managing playback devices."}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"PlaybackSource","kind":"identifier"}],"title":"PlaybackSource"},"doc://MillicastSDK/documentation/MillicastSDK/PlaybackSource/initPlayback()":{"kind":"symbol","type":"topic","abstract":[{"text":"Initializes the playback device.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/PlaybackSource\/initPlayback()","url":"\/documentation\/millicastsdk\/playbacksource\/initplayback()","required":true,"title":"initPlayback()","navigatorTitle":[{"text":"initPlayback","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initPlayback","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initPlayback"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initPlayback"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"initPlayback","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"PlaybackSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/title"},{"value":[{"text":"PlaybackSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource\/fragments"},{"value":"initPlayback","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource~1initPlayback()\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1PlaybackSource~1initPlayback()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initPlayback","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}