{"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"]]},"metadata":{"title":"MCGenericError.Code.peerConnectionRemoteDesc","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCGenericError@MCGenericErrorPeerConnectionRemoteDesc","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionRemoteDesc"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionRemoteDesc"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"peerConnectionRemoteDesc","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionRemoteDesc","interfaceLanguage":"swift"},"abstract":[{"text":"Can not set PeerConnection remote description.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionremotedesc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionremotedesc"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct":{"title":"MCGenericError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCGenericError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct","kind":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCGenericError"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"title":"MCGenericError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","kind":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","type":"topic","abstract":[{"type":"text","text":"Generic errors returned by the SDK."}],"navigatorTitle":[{"text":"Code","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionRemoteDesc":{"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionRemoteDesc","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"peerConnectionRemoteDesc"}],"abstract":[{"type":"text","text":"Can not set PeerConnection remote description."}],"kind":"symbol","title":"MCGenericError.Code.peerConnectionRemoteDesc","navigatorTitle":[{"text":"MCGenericErrorPeerConnectionRemoteDesc","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionremotedesc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCGenericErrorPeerConnectionRemoteDesc","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionRemoteDesc"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionRemoteDesc"}]}],"kind":"declarations"},"op":"replace"},{"value":"MCGenericError","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title"},{"value":[{"text":"MCGenericError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments"},{"op":"replace","value":"MCGenericErrorPeerConnectionRemoteDesc","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionRemoteDesc\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionRemoteDesc\/fragments","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionRemoteDesc"}]}]}]}