{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/minimum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/minimum"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/minimum","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The minimum delay that should be added to"},{"type":"text","text":" "},{"type":"text","text":"each frame."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"minimum","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCForcePlayoutDelay(py)minimum","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"minimum"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/minimum":{"role":"symbol","title":"minimum","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The minimum delay that should be added to"},{"type":"text","text":" "},{"type":"text","text":"each frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/minimum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimum"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/minimum"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay":{"role":"symbol","title":"MCForcePlayoutDelay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"abstract":[{"type":"text","text":"An option to tell the media server to"},{"type":"text","text":" "},{"type":"text","text":"send hints about the range of"},{"type":"text","text":" "},{"type":"text","text":"playout delays that the RTP receiver should"},{"type":"text","text":" "},{"type":"text","text":"follow, which effectively sets the delay"},{"type":"text","text":" "},{"type":"text","text":"for each frame before it is rendered."},{"type":"text","text":" "},{"type":"text","text":"Use this if you want to compensate"},{"type":"text","text":" "},{"type":"text","text":"for unpredictable network behaviour"},{"type":"text","text":" "},{"type":"text","text":"allowing for smooth playback at the cost"},{"type":"text","text":" "},{"type":"text","text":"of increasing latency."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCForcePlayoutDelay"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minimum"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minimum"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1minimum\/title","value":"minimum"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1minimum\/fragments","value":[{"kind":"identifier","text":"minimum"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/title","value":"MCForcePlayoutDelay"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/fragments","value":[{"kind":"identifier","text":"MCForcePlayoutDelay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}