{"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time_measurements","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats(py)round_trip_time_measurements","title":"round_trip_time_measurements","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"round_trip_time_measurements"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time_measurements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"modules":[{"name":"MillicastSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time_measurements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time_measurements"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time_measurements"]}],"abstract":[{"text":"The number of round-trip time measurements. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements"}],"references":{"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements":{"type":"link","title":"roundTripTimeMeasurements","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements","titleInlineContent":[{"text":"roundTripTimeMeasurements","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/round_trip_time_measurements":{"role":"symbol","title":"round_trip_time_measurements","type":"topic","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time_measurements","navigatorTitle":[{"text":"round_trip_time_measurements","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"round_trip_time_measurements","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time_measurements","abstract":[{"text":"The number of round-trip time measurements. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","role":"symbol","abstract":[{"text":"Statistics about an incoming remote RTP stream.","type":"text"}],"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"title":"MCRemoteInboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"round_trip_time_measurements","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"round_trip_time_measurements","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"preciseIdentifier":"c:K","kind":"typeIdentifier","text":"long long"},{"kind":"text","text":" "},{"kind":"identifier","text":"round_trip_time_measurements"},{"text":";","kind":"text"}]}]}},{"value":"round_trip_time_measurements","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time_measurements\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time_measurements\/fragments","value":[{"kind":"identifier","text":"round_trip_time_measurements"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","op":"replace","value":"MCRemoteInboundRtpStreamStats"},{"value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}