{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"]]},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/videoSize","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The size of the last video frame received.","type":"text"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"videoSize","navigatorTitle":[{"text":"videoSize","kind":"identifier"}],"externalID":"c:objc(cs)MCCMSampleBufferVideoRenderer(py)videoSize","modules":[{"name":"MillicastSDK"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/videosize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/videosize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"kind":"symbol","abstract":[{"type":"text","text":"This class is responsible for converting "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"type":"text","text":"  into renderable "},{"code":"CMSampleBufferRef","type":"codeVoice"},{"type":"text","text":" frames."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","title":"MCCMSampleBufferVideoRenderer","type":"topic","navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer/videoSize":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer\/videosize","type":"topic","kind":"symbol","role":"symbol","title":"videoSize","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer\/videoSize","abstract":[{"type":"text","text":"The size of the last video frame received."}],"navigatorTitle":[{"text":"videoSize","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"title":"MCVideoFrame","abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference","isActive":true},{"type":"text","text":" for playback."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"videoSize","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"atomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" ","kind":"text"},{"text":"videoSize","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1videoSize\/title","value":"videoSize","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer~1videoSize\/fragments","value":[{"kind":"identifier","text":"videoSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace"}]}]}