{"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yuy2","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"yuy2"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/yuy2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideotype\/yuy2"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType"]]},"metadata":{"symbolKind":"case","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCVideoTypeYUY2","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@E@MCVideoType@MCVideoTypeYUY2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"yuy2","kind":"identifier"}],"title":"MCVideoType.yuy2"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType":{"title":"MCVideoType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoType/yuy2":{"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoType\/yuy2","title":"MCVideoType.yuy2","navigatorTitle":[{"text":"MCVideoTypeYUY2","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideotype\/yuy2","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"yuy2","kind":"identifier"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCVideoTypeYUY2","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MCVideoTypeYUY2"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCVideoTypeYUY2"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCVideoType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/title"},{"value":[{"kind":"identifier","text":"MCVideoType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/fragments"},{"value":[{"text":"MCVideoType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType\/navigatorTitle"},{"value":"MCVideoTypeYUY2","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yuy2\/title"},{"value":[{"kind":"identifier","text":"MCVideoTypeYUY2"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoType~1yuy2\/fragments"}]}]}