{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame"]]},"metadata":{"role":"symbol","externalID":"c:objc(pl)MCVideoFrame(im)getI420Buffer:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getI420Buffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">!)","kind":"text"}],"navigatorTitle":[{"text":"getI420Buffer:","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"modules":[{"name":"MillicastSDK"}],"symbolKind":"method","title":"getI420Buffer(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getI420Buffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">!)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The pre-allocated buffer to be filled on the user side. buffer needs to fit ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()","isActive":true,"type":"reference"},{"text":" bytes.","type":"text"}]}],"name":"buffer"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/getI420Buffer(_:)"},"abstract":[{"text":"Get the video frame buffer as an I420 frame. Performs the necessary conversion.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/geti420buffer(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/geti420buffer(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/getI420Buffer(_:)":{"navigatorTitle":[{"kind":"identifier","text":"getI420Buffer:"}],"abstract":[{"text":"Get the video frame buffer as an I420 frame. Performs the necessary conversion.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/getI420Buffer(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe\/geti420buffer(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getI420Buffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">!)"}],"title":"getI420Buffer(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/sizeI420()":{"navigatorTitle":[{"text":"sizeI420","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()","abstract":[{"text":"If the frame was an I420 frame, then this will return size of the frame in bytes.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeI420","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizei420()","required":true,"title":"sizeI420()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","url":"\/documentation\/millicastsdk\/mcvideoframe","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference","isActive":true},{"text":" for playback.","type":"text"}],"role":"symbol","title":"MCVideoFrame","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"getI420Buffer:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getI420Buffer:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"getI420Buffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"text":" *) ","kind":"text"},{"text":"buffer","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1getI420Buffer(_:)\/title","op":"replace","value":"getI420Buffer:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1getI420Buffer(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getI420Buffer:","kind":"identifier"}]},{"value":"MCVideoRenderer","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace"},{"value":[{"text":"MCVideoRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","op":"replace"},{"value":"sizeI420","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeI420"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/fragments","op":"replace"},{"value":"MCVideoFrame","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoFrame"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}