{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRgbBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">!)"}]}]},{"kind":"parameters","parameters":[{"name":"buffer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The pre-allocated buffer to be filled on the user side. buffer needs to fit "},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","type":"reference"},{"type":"text","text":" bytes."}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/getRgbBuffer(_:)"},"abstract":[{"text":"Get the video frame buffer as an RGB frame. Performs the necessary conversion.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/getrgbbuffer(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideoframe\/getrgbbuffer(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRgbBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">!)"}],"navigatorTitle":[{"kind":"identifier","text":"getRgbBuffer:"}],"externalID":"c:objc(pl)MCVideoFrame(im)getRgbBuffer:","required":true,"title":"getRgbBuffer(_:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","url":"\/documentation\/millicastsdk\/mcvideoframe","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference","isActive":true},{"text":" for playback.","type":"text"}],"role":"symbol","title":"MCVideoFrame","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/getRgbBuffer(_:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/getRgbBuffer(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcvideoframe\/getrgbbuffer(_:)","title":"getRgbBuffer(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getRgbBuffer:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRgbBuffer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!)"}],"abstract":[{"type":"text","text":"Get the video frame buffer as an RGB frame. Performs the necessary conversion."}],"required":true,"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/sizeRgb()":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","title":"sizeRgb()","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizergb()","required":true,"navigatorTitle":[{"kind":"identifier","text":"sizeRgb"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"If the frame was an RGB frame, then this will return size of the frame in bytes."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeRgb"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getRgbBuffer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getRgbBuffer:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"getRgbBuffer:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"buffer"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1getRgbBuffer(_:)\/title","value":"getRgbBuffer:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1getRgbBuffer(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRgbBuffer:"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/title","value":"sizeRgb","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeRgb"}],"op":"replace"}]}]}