{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"width","kind":"identifier"}],"externalID":"c:objc(pl)MCVideoFrame(im)width","modules":[{"name":"MillicastSDK"}],"title":"width()","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Method"},"sections":[],"abstract":[{"type":"text","text":"The width of the video frame."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/width()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/width()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/width()"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the width of the video frame."}]}],"kind":"content"}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","url":"\/documentation\/millicastsdk\/mcvideoframe","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","type":"reference","isActive":true},{"text":" for playback.","type":"text"}],"role":"symbol","title":"MCVideoFrame","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/width()":{"required":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/width()","title":"width()","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideoframe\/width()","abstract":[{"type":"text","text":"The width of the video frame."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"width","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"width"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":") ","kind":"text"},{"text":"width","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCVideoFrame","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1width()\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1width()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"width","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}