{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","text":"MCTrack"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The track corresponding to this source."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/capturesource\/startcapture()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/capturesource\/startcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/startCapture()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initiates and starts the capture device and creates"},{"type":"text","text":" "},{"type":"text","text":"the corresponding track. You should not call start capture twice in a row."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"role":"symbol","title":"startCapture()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"symbolKind":"method","externalID":"c:objc(pl)CaptureSource(im)startCapture","required":true,"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource":{"role":"symbol","title":"CaptureSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureSource"}],"abstract":[{"type":"text","text":"Manages the process of capturing the source by input sources, such as a microphone or a camera."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaptureSource"}],"url":"\/documentation\/millicastsdk\/capturesource"},"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource/startCapture()":{"navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"role":"symbol","title":"startCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Initiates and starts the capture device and creates"},{"type":"text","text":" "},{"type":"text","text":"the corresponding track. You should not call start capture twice in a row."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/startCapture()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/millicastsdk\/capturesource\/startcapture()"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"role":"symbol","title":"MCTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCTrack"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCTrack"}],"url":"\/documentation\/millicastsdk\/mctrack"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","text":"MCTrack"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"startCapture"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/title","value":"CaptureSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/fragments","value":[{"kind":"identifier","text":"CaptureSource"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1startCapture()\/title","value":"startCapture"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1startCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","value":"MCTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","value":[{"kind":"identifier","text":"MCTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}