{"abstract":[{"type":"text","text":"The identifier of the track. see "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","type":"reference"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/track_identifier","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)MCMediaSourceStats(py)track_identifier","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"track_identifier","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"track_identifier","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/track_identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/track_identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats":{"type":"topic","title":"MCMediaSourceStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCMediaSourceStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats","role":"symbol","abstract":[{"text":"The MCMediaSourceStats class gathers statistics details.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCMediaSourceStats"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcmediasourcestats-trackidentifier":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","type":"link","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","title":"trackIdentifier","titleInlineContent":[{"text":"trackIdentifier","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats/track_identifier":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcmediasourcestats\/track_identifier","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic","title":"track_identifier","abstract":[{"text":"The identifier of the track. see ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcmediasourcestats-trackidentifier","type":"reference"}],"navigatorTitle":[{"text":"track_identifier","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats\/track_identifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"track_identifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"track_identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","value":"MCMediaSourceStats"},{"value":[{"text":"MCMediaSourceStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1track_identifier\/title","value":"track_identifier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats~1track_identifier\/fragments","value":[{"kind":"identifier","text":"track_identifier"}]}]}]}