{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/timeout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/timeout"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"MCAsyncOperationCancelledError.Code.timeout","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeout"}],"role":"symbol","externalID":"c:@E@MCAsyncOperationCancelledError@MCAsyncOperationCancelledErrorTimeout","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorTimeout"}],"symbolKind":"case","modules":[{"name":"MillicastSDK"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/timeout","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Operation was cancelled due to a timeout."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code/timeout":{"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code\/timeout","title":"MCAsyncOperationCancelledError.Code.timeout","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeout"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAsyncOperationCancelledErrorTimeout"}],"abstract":[{"text":"Operation was cancelled due to a timeout.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code\/timeout","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAsyncOperationCancelledError-swift.struct/Code":{"url":"\/documentation\/millicastsdk\/mcasyncoperationcancellederror-swift.struct\/code","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAsyncOperationCancelledError-swift.struct\/Code","abstract":[{"type":"text","text":"Error category for errors triggered when the operation failed because"},{"text":" ","type":"text"},{"type":"text","text":"it was abandoned for various reasons."}],"type":"topic","title":"MCAsyncOperationCancelledError.Code"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MCAsyncOperationCancelledErrorTimeout","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCAsyncOperationCancelledErrorTimeout","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCAsyncOperationCancelledErrorTimeout","kind":"identifier"}]}]}},{"op":"replace","value":"MCAsyncOperationCancelledErrorTimeout","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1timeout\/title"},{"value":[{"text":"MCAsyncOperationCancelledErrorTimeout","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code~1timeout\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/title","op":"replace","value":"MCAsyncOperationCancelledError"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAsyncOperationCancelledError-swift.struct~1Code\/fragments","value":[{"text":"MCAsyncOperationCancelledError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}