{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"promote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"renderer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The renderer to receive video frames."}]}]},{"name":"layer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Layer information. If the default value is passed, the service"},{"type":"text","text":" "},{"type":"text","text":"will allocate layers automatically depending on bandwidth estimation and"},{"type":"text","text":" "},{"type":"text","text":"the priority"}]}]},{"name":"promote","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"set this track to be the main video track. The main video"},{"type":"text","text":" "},{"type":"text","text":"track has highest priority for bandwidth assignment when SVC layers are"},{"type":"text","text":" "},{"type":"text","text":"managed by the service."}]}]},{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation completes."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:promote:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:promote:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:promote:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enable the track with a renderer to start receiving media. You can choose from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"},{"type":"text","text":" which are directly attachable to Views. Otherwise, if you have a specific"},{"type":"text","text":" "},{"type":"text","text":"usecase for receiving video frames and managing them yourself, then you can implement your own "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"promote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"enable(renderer:layer:promote:completionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCRTSRemoteVideoTrack(im)enableWithRenderer:layer:promote:completionHandler:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enableWithRenderer:layer:promote:completionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"role":"symbol","title":"MCRTSRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","title":"MCVideoRenderer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"role":"symbol","title":"MCAcceleratedVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"role":"symbol","title":"MCCMSampleBufferVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"abstract":[{"type":"text","text":"This class is responsible for converting "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"},{"type":"text","text":"  into renderable "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" frames."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:layer:promote:completionHandler:)":{"role":"symbol","title":"enable(renderer:layer:promote:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"promote"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enable the track with a renderer to start receiving media. You can choose from "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer"},{"type":"text","text":" which are directly attachable to Views. Otherwise, if you have a specific"},{"type":"text","text":" "},{"type":"text","text":"usecase for receiving video frames and managing them yourself, then you can implement your own "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:promote:completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableWithRenderer:layer:promote:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:promote:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"role":"symbol","title":"MCVideoFrame","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"type":"text","text":"with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"},{"type":"text","text":" for playback."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoFrame"}],"url":"\/documentation\/millicastsdk\/mcvideoframe"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"type":"text","text":" "},{"type":"text","text":"Several renderers can be added to the track."},{"type":"text","text":" "},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addRenderer:"}],"url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"role":"symbol","title":"MCRTSRemoteVideoTrackLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"enableWithRenderer:layer:promote:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:layer:promote:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"enableWithRenderer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MCVideoRenderer>","preciseIdentifier":"c:Qoobjc(pl)MCVideoRenderer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"renderer"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"layer"},{"kind":"text","text":" "},{"kind":"identifier","text":"promote:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"promote"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:promote:completionHandler:)\/title","value":"enableWithRenderer:layer:promote:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:promote:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:layer:promote:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","value":"addRenderer:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addRenderer:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","value":"MCRTSRemoteVideoTrackLayer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}