{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremoteaudiotrack\/setvolume(_:completionhandler:)"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremoteaudiotrack\/setvolume(_:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"setVolume(_:completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVolume"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)MCRTSRemoteAudioTrack(im)setVolume:completionHandler:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"setVolume:completionHandler:","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}]},"abstract":[{"text":"Set audio volume","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack\/setVolume(_:completionHandler:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setVolume","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"volume","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume in range 0.0 to 1.0"}]}],"name":"volume"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Invoked when the asynchronous operation completes.","type":"text"}]}],"name":"completionHandler"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The volume will only be set if projected, and will be reset when"},{"text":" ","type":"text"},{"text":"unprojected.","type":"text"}]}],"kind":"content"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteAudioTrack/setVolume(_:completionHandler:)":{"title":"setVolume(_:completionHandler:)","url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack\/setvolume(_:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVolume","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Set audio volume"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack\/setVolume(_:completionHandler:)","navigatorTitle":[{"text":"setVolume:completionHandler:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteAudioTrack":{"title":"MCRTSRemoteAudioTrack","url":"\/documentation\/millicastsdk\/mcrtsremoteaudiotrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteAudioTrack","abstract":[{"text":"The RTS logical track’s audio interface.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteAudioTrack"}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setVolume:completionHandler:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setVolume:completionHandler:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setVolume:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"volume","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack~1setVolume(_:completionHandler:)\/title","value":"setVolume:completionHandler:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setVolume:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack~1setVolume(_:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/title","value":"MCRTSRemoteAudioTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteAudioTrack\/fragments","value":[{"text":"MCRTSRemoteAudioTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}