{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/audio_level"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/audio_level"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/audio_level","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The audio level of the stream. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"audio_level","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCInboundRtpStreamStats(py)audio_level","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"audio_level"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/audio_level":{"role":"symbol","title":"audio_level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The audio level of the stream. See "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/audio_level","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audio_level"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/audio_level"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"role":"symbol","title":"MCInboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-audiolevel":{"title":"audioLevel","titleInlineContent":[{"type":"text","text":"audioLevel"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audio_level"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audio_level"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1audio_level\/title","value":"audio_level"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1audio_level\/fragments","value":[{"kind":"identifier","text":"audio_level"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","value":"MCInboundRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCInboundRtpStreamStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}