{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccodecstatstype\/decode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccodecstatstype\/decode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType\/decode","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"title":"MCCodecStatsType.decode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCCodecStatsType@MCCodecStatsTypeDecode","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCodecStatsType/decode":{"role":"symbol","title":"MCCodecStatsType.decode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType\/decode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype\/decode"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCCodecStatsType":{"role":"symbol","title":"MCCodecStatsType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCodecStatsType"}],"abstract":[{"type":"text","text":"Different types of codec statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCodecStatsType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCCodecStatsType"}],"url":"\/documentation\/millicastsdk\/mccodecstatstype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MCCodecStatsTypeDecode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType~1decode\/title","value":"MCCodecStatsTypeDecode"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType~1decode\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsTypeDecode"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/title","value":"MCCodecStatsType"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCodecStatsType\/fragments","value":[{"kind":"identifier","text":"MCCodecStatsType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}