{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDisabledPublisher"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"An AnyPublisher"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Refer to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)"},{"type":"text","text":" "},{"type":"text","text":"for more information"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabledPublisher()"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabledpublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Create a Combine based publisher that is invoked whenever the track gets disabled.","type":"text"}],"metadata":{"externalID":"s:So19MCWebrtcRemoteTrackC12MillicastSDKE22trackDisabledPublisher7Combine03AnyH0Vyyts5NeverOGyF","extendedModule":"MillicastSDK","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDisabledPublisher"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier","text":"AnyPublisher"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":">"}],"title":"trackDisabledPublisher()","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"MillicastSDK"}]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"symbol","abstract":[{"type":"text","text":"The webrtc logical track."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","title":"MCWebrtcRemoteTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrack/trackDisabledPublisher()":{"abstract":[{"type":"text","text":"Create a Combine based publisher that is invoked whenever the track gets disabled."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack\/trackdisabledpublisher()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDisabledPublisher","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack\/trackDisabledPublisher()","title":"trackDisabledPublisher()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrackDisabled(_:)":{"role":"symbol","abstract":[{"type":"text","text":"The event for disabled state notification."}],"type":"topic","title":"webrtcRemoteTrackDisabled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)","url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)","navigatorTitle":[{"kind":"identifier","text":"webrtcRemoteTrackDisabled:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","value":"MCWebrtcRemoteTrack","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/navigatorTitle","value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/title","value":"webrtcRemoteTrackDisabled:","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}