{"metadata":{"title":"statsPublisher()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statsPublisher"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MCTrackStats","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier","text":"Never"},{"kind":"text","text":">"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"externalID":"s:So16MCRTSRemoteTrackC12MillicastSDKE14statsPublisher7Combine03AnyF0VySo12MCTrackStatsCs5NeverOGyF","extendedModule":"MillicastSDK"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/statsPublisher()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsPublisher"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV","text":"AnyPublisher"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats","kind":"typeIdentifier","text":"MCTrackStats","preciseIdentifier":"c:objc(cs)MCTrackStats"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"an AnyPublisher to receive track stats"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetrack\/statspublisher()"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Get a Combine based stats publisher.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrackStats":{"url":"\/documentation\/millicastsdk\/mctrackstats","title":"MCTrackStats","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrackStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrackStats"}],"navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrack"}],"navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track."},{"type":"text","text":" "},{"type":"text","text":"This class represents a single media (audio or video) in the RTS stream."},{"text":" ","type":"text"},{"type":"text","text":"The RTS tracks are created automatically when the service notifies about the"},{"text":" ","type":"text"},{"type":"text","text":"sources becoming active, can be used to enable simple streaming scenarios:"},{"text":" ","type":"text"},{"type":"text","text":"enable projection of the audio and video coming from the same source with"},{"text":" ","type":"text"},{"type":"text","text":"lip-sync, with a single video renderer attached to the video track. When the"},{"type":"text","text":" "},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"title":"MCRTSRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrack/statsPublisher()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrack\/statsPublisher()","title":"statsPublisher()","abstract":[{"type":"text","text":"Get a Combine based stats publisher."}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotetrack\/statspublisher()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statsPublisher"},{"kind":"text","text":"() -> "},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrackStats","text":"MCTrackStats"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/title","op":"replace","value":"MCTrackStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrackStats\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCTrackStats"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","op":"replace","value":"MCRTSRemoteTrack"},{"value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}