{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/app"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsourcetype\/app"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/app"]}],"abstract":[{"text":"Application screen capture source","type":"text"}],"metadata":{"role":"symbol","title":"MCSourceType.app","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeApp"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCSourceType@MCSourceTypeApp"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"url":"\/documentation\/millicastsdk\/mcsourcetype","title":"MCSourceType","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","abstract":[{"text":"The Source type","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/app":{"abstract":[{"type":"text","text":"Application screen capture source"}],"title":"MCSourceType.app","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/app","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/app","navigatorTitle":[{"text":"MCSourceTypeApp","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MCSourceTypeApp","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCSourceTypeApp","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MCSourceTypeApp","kind":"identifier"}]}]}},{"value":"MCSourceType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace"},{"value":"MCSourceTypeApp","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1app\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1app\/fragments","op":"replace","value":[{"text":"MCSourceTypeApp","kind":"identifier"}]}]}]}