{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mic","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeMic"}],"title":"MCSourceType.mic","modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mic","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@MCSourceType@MCSourceTypeMic","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/mic"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Microphone devices source"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsourcetype\/mic"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/mic"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/mic":{"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeMic"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/mic","title":"MCSourceType.mic","url":"\/documentation\/millicastsdk\/mcsourcetype\/mic","abstract":[{"text":"Microphone devices source","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mic","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"url":"\/documentation\/millicastsdk\/mcsourcetype","title":"MCSourceType","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","abstract":[{"text":"The Source type","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MCSourceTypeMic","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"MCSourceTypeMic","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MCSourceTypeMic","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1mic\/title","value":"MCSourceTypeMic"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1mic\/fragments","op":"replace","value":[{"text":"MCSourceTypeMic","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","op":"replace","value":"MCSourceType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSourceType"}]}]}]}