{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController"},"abstract":[{"type":"text","text":"This playback controller allows you to modify the state of the player node that is provided through the delegate."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not attempt to schedule\/start\/stop playback of the AVAudioPlayerNode directly. Use this controller instead."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestPlay()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestStop()"]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"}],"roleHeading":"Protocol","externalID":"c:objc(pl)MCAudioPlayerNodePlaybackController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayerNodePlaybackController"}],"modules":[{"name":"MillicastSDK"}],"title":"MCAudioPlayerNodePlaybackController","symbolKind":"protocol","platforms":[]},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","title":"NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController":{"title":"MCAudioPlayerNodePlaybackController","navigatorTitle":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController","role":"symbol","abstract":[{"text":"This playback controller allows you to modify the state of the player node that is provided through the delegate.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController/requestStop()":{"role":"symbol","title":"requestStop()","url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requeststop()","navigatorTitle":[{"text":"requestStop","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Request the AVAudioPlayerNode to stop playback and receiving audio."}],"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestStop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestStop","kind":"identifier"},{"text":"()","kind":"text"}],"required":true},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayerNodePlaybackController/requestPlay()":{"url":"\/documentation\/millicastsdk\/mcaudioplayernodeplaybackcontroller\/requestplay()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestPlay"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPlay"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestPlay()","kind":"symbol","title":"requestPlay()","required":true,"abstract":[{"type":"text","text":"Request the AVAudioPlayerNode to start playback and receive audio."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"MCAudioPlayerNodePlaybackController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestPlay()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayerNodePlaybackController\/requestStop()"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/title","value":"MCAudioPlayerNodePlaybackController","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController\/fragments","value":[{"text":"MCAudioPlayerNodePlaybackController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestStop()\/title","value":"requestStop","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestStop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestStop","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestPlay()\/title","value":"requestPlay","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayerNodePlaybackController~1requestPlay()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestPlay","kind":"identifier"}],"op":"replace"}]}]}