{"metadata":{"role":"symbol","externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats","navigatorTitle":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"symbolKind":"class","modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"title":"MCRemoteInboundRtpStreamStats"},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/fraction_lost","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/local_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time_measurements","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/total_round_trip_time"],"title":"Instance Properties"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/get_type()"],"title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats"]}],"kind":"symbol","abstract":[{"type":"text","text":"Statistics about an incoming remote RTP stream."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-fractionlost":{"title":"fractionLost","titleInlineContent":[{"type":"text","text":"fractionLost"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-localid":{"title":"localId","titleInlineContent":[{"type":"text","text":"localId"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-localid","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-localid","type":"link"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements":{"title":"roundTripTimeMeasurements","titleInlineContent":[{"type":"text","text":"roundTripTimeMeasurements"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements","type":"link"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/total_round_trip_time":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/total_round_trip_time","kind":"symbol","abstract":[{"text":"The sum of round-trip times for packets sent between endpoints. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"total_round_trip_time"}],"title":"total_round_trip_time","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/total_round_trip_time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_round_trip_time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime":{"title":"roundTripTime","titleInlineContent":[{"type":"text","text":"roundTripTime"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","type":"link"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/fraction_lost":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fraction_lost","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"fraction_lost","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/fraction_lost","role":"symbol","navigatorTitle":[{"text":"fraction_lost","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/fraction_lost","abstract":[{"text":"The fraction of RTP packets lost during transmission or due to network issues. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-fractionlost","type":"reference"}],"kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/round_trip_time_measurements":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time_measurements","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time_measurements","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"round_trip_time_measurements","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"title":"round_trip_time_measurements","kind":"symbol","navigatorTitle":[{"text":"round_trip_time_measurements","kind":"identifier"}],"abstract":[{"text":"The number of round-trip time measurements. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptimemeasurements","type":"reference"}],"type":"topic","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"title":"MCRemoteInboundRtpStreamStats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","abstract":[{"text":"Statistics about an incoming remote RTP stream.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime":{"title":"totalRoundTripTime","titleInlineContent":[{"type":"text","text":"totalRoundTripTime"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-totalroundtriptime","type":"link"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/get_type()":{"kind":"symbol","title":"get_type()","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/get_type()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"get_type","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/get_type()","abstract":[{"type":"text","text":"Returns the type of statistics."}]},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","type":"topic","title":"MCReceivedRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"role":"symbol","abstract":[{"type":"text","text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream."}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/round_trip_time":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time","abstract":[{"type":"text","text":"The round-trip time for packets sent between the local and remote endpoints. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-roundtriptime","type":"reference","isActive":true}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"round_trip_time","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/round_trip_time","navigatorTitle":[{"text":"round_trip_time","kind":"identifier"}],"role":"symbol","title":"round_trip_time","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/local_id":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"local_id"}],"title":"local_id","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/local_id","kind":"symbol","abstract":[{"type":"text","text":"The local identifier associated with the remote inbound RTP stream. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcremoteinboundrtpstreamstats-localid","isActive":true}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"local_id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/local_id"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MCRemoteInboundRtpStreamStats","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/fraction_lost","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/local_id","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/round_trip_time_measurements","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/total_round_trip_time"]},{"title":"Type Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/get_type()"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","preciseIdentifier":"c:objc(cs)MCReceivedRtpStreamStats","text":"MCReceivedRtpStreamStats","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1total_round_trip_time\/title","value":"total_round_trip_time","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1total_round_trip_time\/fragments","value":[{"kind":"identifier","text":"total_round_trip_time"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1fraction_lost\/title","value":"fraction_lost","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1fraction_lost\/fragments","value":[{"kind":"identifier","text":"fraction_lost"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time_measurements\/title","value":"round_trip_time_measurements","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time_measurements\/fragments","value":[{"kind":"identifier","text":"round_trip_time_measurements"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title","value":"MCRemoteInboundRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments","value":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1get_type()\/title","value":"get_type","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1get_type()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","value":"MCReceivedRtpStreamStats","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time\/title","value":"round_trip_time","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1round_trip_time\/fragments","value":[{"text":"round_trip_time","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1local_id\/title","value":"local_id","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1local_id\/fragments","value":[{"text":"local_id","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}