{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:promote:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:promote:completionHandler:)"]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotrack"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)MCRTSRemoteVideoTrack","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"title":"MCRTSRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"symbolKind":"class"},"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"text":" ","type":"text"},{"text":"applications. Used in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)"},{"text":" to start receiving","type":"text"},{"text":" ","type":"text"},{"text":"video frames from that video track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoRenderer"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:layer:promote:completionHandler:)":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:promote:completionhandler:)","kind":"symbol","role":"symbol","abstract":[{"text":"Enable the track with a renderer to start receiving media. You can choose from ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","isActive":true,"type":"reference"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","isActive":true,"type":"reference"},{"text":" which are directly attachable to Views. Otherwise, if you have a specific","type":"text"},{"text":" ","type":"text"},{"text":"usecase for receiving video frames and managing them yourself, then you can implement your own ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true,"type":"reference"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:promote:completionHandler:)","title":"enable(renderer:layer:promote:completionHandler:)","type":"topic","navigatorTitle":[{"text":"enableWithRenderer:layer:promote:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","preciseIdentifier":"c:objc(pl)MCVideoRenderer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"role":"symbol","abstract":[{"text":"Class that renders video frames in a ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"NSView","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"type":"topic","title":"MCAcceleratedVideoRenderer"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:layer:completionHandler:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:completionHandler:)","kind":"symbol","abstract":[{"type":"text","text":"Enable the track with default promote behavour, which is false."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"text":", ","kind":"text"},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:layer:completionhandler:)","type":"topic","role":"symbol","title":"enable(renderer:layer:completionHandler:)","navigatorTitle":[{"text":"enableWithRenderer:layer:completionHandler:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteTrack":{"title":"MCRTSRemoteTrack","navigatorTitle":[{"text":"MCRTSRemoteTrack","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrack","kind":"identifier"}],"abstract":[{"text":"The RTS logical track.","type":"text"},{"text":" ","type":"text"},{"text":"This class represents a single media (audio or video) in the RTS stream.","type":"text"},{"text":" ","type":"text"},{"text":"The RTS tracks are created automatically when the service notifies about the","type":"text"},{"text":" ","type":"text"},{"text":"sources becoming active, can be used to enable simple streaming scenarios:","type":"text"},{"text":" ","type":"text"},{"text":"enable projection of the audio and video coming from the same source with","type":"text"},{"text":" ","type":"text"},{"text":"lip-sync, with a single video renderer attached to the video track. When the","type":"text"},{"text":" ","type":"text"},{"text":"RTS source goes inactive, streaming for them is automatically disabled.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetrack","role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"role":"symbol","title":"MCCMSampleBufferVideoRenderer","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","abstract":[{"text":"This class is responsible for converting ","type":"text"},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","type":"reference","isActive":true},{"text":"  into renderable ","type":"text"},{"code":"CMSampleBufferRef","type":"codeVoice"},{"text":" frames.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:promote:completionHandler:)":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:promote:completionHandler:)","kind":"symbol","abstract":[{"type":"text","text":"Enable the track with default layer behaviour"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"text":", ","kind":"text"},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:promote:completionhandler:)","type":"topic","role":"symbol","title":"enable(renderer:promote:completionHandler:)","navigatorTitle":[{"text":"enableWithRenderer:promote:completionHandler:","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack/enable(renderer:completionHandler:)":{"title":"enable(renderer:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"enableWithRenderer:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"MCVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCVideoRenderer"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack\/enable(renderer:completionhandler:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable the track with default promote and layer behavour."}]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"MCRTSRemoteVideoTrack","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:layer:promote:completionHandler:)","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack\/enable(renderer:promote:completionHandler:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrack","text":"MCRTSRemoteTrack"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:promote:completionHandler:)\/title","value":"enableWithRenderer:layer:promote:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:promote:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:layer:promote:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","value":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:completionHandler:)\/title","value":"enableWithRenderer:layer:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:layer:completionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"enableWithRenderer:layer:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/title","value":"MCRTSRemoteTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteTrack\/fragments","value":[{"text":"MCRTSRemoteTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:promote:completionHandler:)\/title","value":"enableWithRenderer:promote:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:promote:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:promote:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","value":"MCRTSRemoteVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:completionHandler:)\/title","value":"enableWithRenderer:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack~1enable(renderer:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enableWithRenderer:completionHandler:"}]}]}]}