{"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject","doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP","doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCTrackStats","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bitrateBps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bytesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decodeTime","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decoderImplementation","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/firCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameHeight","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameWidth","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDecoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDropped","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesPerSecond","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/freezeCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitter","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferMinimumDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/keyFramesDecoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mid","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mimeType","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/nackCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsLost","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pauseCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/payloadType","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pliCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/processingDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedBytesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedPacketsReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/sourceId","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/timestamp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalFreezeDuration","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalPauseDuration","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/trackIdentifier","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/type"]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mctrackstats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mctrackstats"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCTrackStats","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"MCTrackStats","externalID":"c:objc(cs)MCTrackStats","roleHeading":"Class"},"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","interfaceLanguage":"swift"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/decodeTime":{"url":"\/documentation\/millicastsdk\/mctrackstats\/decodetime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeTime"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decodeTime","abstract":[],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodeTime"}],"title":"decodeTime"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/firCount":{"url":"\/documentation\/millicastsdk\/mctrackstats\/fircount","role":"symbol","abstract":[],"navigatorTitle":[{"text":"firCount","kind":"identifier"}],"title":"firCount","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/firCount","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/jitterBufferMinimumDelay":{"navigatorTitle":[{"kind":"identifier","text":"jitterBufferMinimumDelay"}],"type":"topic","abstract":[],"kind":"symbol","title":"jitterBufferMinimumDelay","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferMinimumDelay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterBufferMinimumDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/jitterbufferminimumdelay"},"doc://io.cosmosoftware.millicast.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/payloadType":{"abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/payloadtype","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/payloadType","title":"payloadType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payloadType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"payloadType","kind":"identifier"}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/jitterBufferDelay":{"abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitterBufferDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"jitterBufferDelay","navigatorTitle":[{"kind":"identifier","text":"jitterBufferDelay"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferDelay","role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/jitterbufferdelay"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/jitter":{"url":"\/documentation\/millicastsdk\/mctrackstats\/jitter","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitter","navigatorTitle":[{"kind":"identifier","text":"jitter"}],"type":"topic","title":"jitter"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats":{"title":"MCTrackStats","url":"\/documentation\/millicastsdk\/mctrackstats","navigatorTitle":[{"text":"MCTrackStats","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCTrackStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats","type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/framesDropped":{"kind":"symbol","type":"topic","abstract":[],"title":"framesDropped","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framesDropped"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"framesDropped"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/framesdropped","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDropped","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/freezeCount":{"abstract":[],"navigatorTitle":[{"text":"freezeCount","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mctrackstats\/freezecount","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/freezeCount","title":"freezeCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/trackIdentifier":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/trackIdentifier","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/trackidentifier","navigatorTitle":[{"kind":"identifier","text":"trackIdentifier"}],"role":"symbol","title":"trackIdentifier","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/frameHeight":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/frameheight","title":"frameHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameHeight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"frameHeight"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameHeight","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s28CustomDebugStringConvertibleP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/sourceId":{"title":"sourceId","url":"\/documentation\/millicastsdk\/mctrackstats\/sourceid","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/sourceId","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sourceId","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/processingDelay":{"abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/processingdelay","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/processingDelay","title":"processingDelay","type":"topic","navigatorTitle":[{"text":"processingDelay","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processingDelay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/timestamp":{"url":"\/documentation\/millicastsdk\/mctrackstats\/timestamp","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","type":"topic","title":"timestamp","navigatorTitle":[{"text":"timestamp","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/timestamp"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/framesPerSecond":{"title":"framesPerSecond","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"framesPerSecond","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/framespersecond","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesPerSecond","kind":"symbol","navigatorTitle":[{"text":"framesPerSecond","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/mimeType":{"navigatorTitle":[{"kind":"identifier","text":"mimeType"}],"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mimeType","url":"\/documentation\/millicastsdk\/mctrackstats\/mimetype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mimeType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"mimeType","type":"topic","kind":"symbol","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/mid":{"title":"mid","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mid","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"mid","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/millicastsdk\/mctrackstats\/mid"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/packetsReceived":{"navigatorTitle":[{"text":"packetsReceived","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/packetsreceived","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsReceived","type":"topic","abstract":[],"kind":"symbol","title":"packetsReceived","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"packetsReceived","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/totalPauseDuration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalPauseDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/totalpauseduration","navigatorTitle":[{"kind":"identifier","text":"totalPauseDuration"}],"title":"totalPauseDuration","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalPauseDuration","kind":"symbol","type":"topic","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/keyFramesDecoded":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyFramesDecoded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/keyframesdecoded","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/keyFramesDecoded","title":"keyFramesDecoded","navigatorTitle":[{"kind":"identifier","text":"keyFramesDecoded"}],"abstract":[],"role":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s7CVarArgP"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/totalFreezeDuration":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalFreezeDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalFreezeDuration","type":"topic","title":"totalFreezeDuration","url":"\/documentation\/millicastsdk\/mctrackstats\/totalfreezeduration","navigatorTitle":[{"text":"totalFreezeDuration","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/decoderImplementation":{"title":"decoderImplementation","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoderImplementation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"decoderImplementation"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/decoderimplementation","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decoderImplementation","abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/bytesReceived":{"title":"bytesReceived","url":"\/documentation\/millicastsdk\/mctrackstats\/bytesreceived","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytesReceived"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bytesReceived","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/retransmittedBytesReceived":{"title":"retransmittedBytesReceived","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedBytesReceived","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/retransmittedbytesreceived","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retransmittedBytesReceived","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"retransmittedBytesReceived","kind":"identifier"}],"abstract":[]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/frameWidth":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"frameWidth","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"frameWidth","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameWidth","url":"\/documentation\/millicastsdk\/mctrackstats\/framewidth","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/framesDecoded":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framesDecoded"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDecoded","title":"framesDecoded","url":"\/documentation\/millicastsdk\/mctrackstats\/framesdecoded","navigatorTitle":[{"kind":"identifier","text":"framesDecoded"}]},"doc://io.cosmosoftware.millicast.sdk/objc(cs)NSObject":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/bitrateBps":{"navigatorTitle":[{"kind":"identifier","text":"bitrateBps"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/bitratebps","title":"bitrateBps","kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bitrateBps","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitrateBps"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/pliCount":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pliCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"pliCount","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pliCount","title":"pliCount","url":"\/documentation\/millicastsdk\/mctrackstats\/plicount","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/packetsLost":{"kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsLost","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"packetsLost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"type":"topic","title":"packetsLost","navigatorTitle":[{"kind":"identifier","text":"packetsLost"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/packetslost"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/retransmittedPacketsReceived":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mctrackstats\/retransmittedpacketsreceived","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedPacketsReceived","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retransmittedPacketsReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"retransmittedPacketsReceived"}],"kind":"symbol","title":"retransmittedPacketsReceived"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/type":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MCTrackStatsType","preciseIdentifier":"c:@E@MCTrackStatsType","kind":"typeIdentifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/type","abstract":[],"type":"topic","url":"\/documentation\/millicastsdk\/mctrackstats\/type"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/nackCount":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nackCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"nackCount","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/nackCount","url":"\/documentation\/millicastsdk\/mctrackstats\/nackcount","abstract":[],"kind":"symbol","title":"nackCount"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/framesReceived":{"url":"\/documentation\/millicastsdk\/mctrackstats\/framesreceived","abstract":[],"title":"framesReceived","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"framesReceived"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesReceived","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"framesReceived"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCTrackStats/pauseCount":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pauseCount","title":"pauseCount","role":"symbol","navigatorTitle":[{"text":"pauseCount","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/millicastsdk\/mctrackstats\/pausecount","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCTrackStats"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCTrackStats","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCTrackStats","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bitrateBps","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/bytesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decodeTime","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/decoderImplementation","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/firCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameHeight","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/frameWidth","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDecoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesDropped","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesPerSecond","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/framesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/freezeCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitter","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/jitterBufferMinimumDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/keyFramesDecoded","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mid","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/mimeType","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/nackCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsLost","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/packetsReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pauseCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/payloadType","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/pliCount","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/processingDelay","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedBytesReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/retransmittedPacketsReceived","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/sourceId","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/timestamp","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalFreezeDuration","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/totalPauseDuration","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/trackIdentifier","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCTrackStats\/type"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCTrackStats","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1decodeTime\/title","value":"decodeTime"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1decodeTime\/fragments","value":[{"kind":"identifier","text":"decodeTime"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1firCount\/title","value":"firCount"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1firCount\/fragments","value":[{"text":"firCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitterBufferMinimumDelay\/title","value":"jitterBufferMinimumDelay"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitterBufferMinimumDelay\/fragments","value":[{"text":"jitterBufferMinimumDelay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1payloadType\/title","value":"payloadType"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1payloadType\/fragments","value":[{"kind":"identifier","text":"payloadType"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitterBufferDelay\/title","value":"jitterBufferDelay"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitterBufferDelay\/fragments","value":[{"text":"jitterBufferDelay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitter\/title","value":"jitter"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1jitter\/fragments","value":[{"kind":"identifier","text":"jitter"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/title","value":"MCTrackStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats\/fragments","value":[{"kind":"identifier","text":"MCTrackStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesDropped\/title","value":"framesDropped"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesDropped\/fragments","value":[{"kind":"identifier","text":"framesDropped"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1freezeCount\/title","value":"freezeCount"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1freezeCount\/fragments","value":[{"kind":"identifier","text":"freezeCount"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1trackIdentifier\/title","value":"trackIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1trackIdentifier\/fragments","value":[{"kind":"identifier","text":"trackIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1frameHeight\/title","value":"frameHeight"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1frameHeight\/fragments","value":[{"text":"frameHeight","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1sourceId\/title","value":"sourceId"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1sourceId\/fragments","value":[{"text":"sourceId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1processingDelay\/title","value":"processingDelay"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1processingDelay\/fragments","value":[{"text":"processingDelay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1timestamp\/title","value":"timestamp"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1timestamp\/fragments","value":[{"text":"timestamp","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesPerSecond\/title","value":"framesPerSecond"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesPerSecond\/fragments","value":[{"text":"framesPerSecond","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1mimeType\/title","value":"mimeType"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1mimeType\/fragments","value":[{"kind":"identifier","text":"mimeType"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1mid\/title","value":"mid"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1mid\/fragments","value":[{"text":"mid","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1packetsReceived\/title","value":"packetsReceived"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1packetsReceived\/fragments","value":[{"kind":"identifier","text":"packetsReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1totalPauseDuration\/title","value":"totalPauseDuration"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1totalPauseDuration\/fragments","value":[{"kind":"identifier","text":"totalPauseDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1keyFramesDecoded\/title","value":"keyFramesDecoded"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1keyFramesDecoded\/fragments","value":[{"text":"keyFramesDecoded","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1totalFreezeDuration\/title","value":"totalFreezeDuration"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1totalFreezeDuration\/fragments","value":[{"text":"totalFreezeDuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1decoderImplementation\/title","value":"decoderImplementation"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1decoderImplementation\/fragments","value":[{"kind":"identifier","text":"decoderImplementation"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1bytesReceived\/title","value":"bytesReceived"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1bytesReceived\/fragments","value":[{"kind":"identifier","text":"bytesReceived"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1retransmittedBytesReceived\/title","value":"retransmittedBytesReceived"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1retransmittedBytesReceived\/fragments","value":[{"text":"retransmittedBytesReceived","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1frameWidth\/title","value":"frameWidth"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1frameWidth\/fragments","value":[{"kind":"identifier","text":"frameWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesDecoded\/title","value":"framesDecoded"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesDecoded\/fragments","value":[{"kind":"identifier","text":"framesDecoded"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1bitrateBps\/title","value":"bitrateBps"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1bitrateBps\/fragments","value":[{"text":"bitrateBps","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1pliCount\/title","value":"pliCount"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1pliCount\/fragments","value":[{"kind":"identifier","text":"pliCount"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1packetsLost\/title","value":"packetsLost"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1packetsLost\/fragments","value":[{"text":"packetsLost","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1retransmittedPacketsReceived\/title","value":"retransmittedPacketsReceived"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1retransmittedPacketsReceived\/fragments","value":[{"text":"retransmittedPacketsReceived","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1nackCount\/title","value":"nackCount"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1nackCount\/fragments","value":[{"kind":"identifier","text":"nackCount"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesReceived\/title","value":"framesReceived"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1framesReceived\/fragments","value":[{"text":"framesReceived","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1pauseCount\/title","value":"pauseCount"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCTrackStats~1pauseCount\/fragments","value":[{"text":"pauseCount","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}