{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource"},"abstract":[{"text":"Responsible for managing playback devices.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/initPlayback()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/isPlaying()"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback"],"title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaybackSource","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(pl)PlaybackSource","title":"PlaybackSource","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaybackSource","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"text":"PlaybackSource","kind":"identifier"}],"symbolKind":"protocol"},"variants":[{"paths":["\/documentation\/millicastsdk\/playbacksource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/playbacksource"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/PlaybackSource":{"title":"PlaybackSource","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybackSource"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybackSource"}],"url":"\/documentation\/millicastsdk\/playbacksource","abstract":[{"type":"text","text":"Responsible for managing playback devices."}],"role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/PlaybackSource/initPlayback()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initPlayback","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/millicastsdk\/playbacksource\/initplayback()","abstract":[{"type":"text","text":"Initializes the playback device."}],"navigatorTitle":[{"text":"initPlayback","kind":"identifier"}],"required":true,"type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/initPlayback()","kind":"symbol","title":"initPlayback()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/PlaybackSource/isPlaying()":{"navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"abstract":[{"text":"Checks whether the playback device is currently playing media (true) or not (false).","type":"text"}],"type":"topic","title":"isPlaying()","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/isPlaying()","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPlaying","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/millicastsdk\/playbacksource\/isplaying()"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAudioPlayback":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplayback","title":"MCAudioPlayback","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback","abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"text":" ","type":"text"},{"text":"This class inherits the Source class, however this is not","type":"text"},{"text":" ","type":"text"},{"text":"a capture source.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"PlaybackSource","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"PlaybackSource","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"PlaybackSource","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/initPlayback()","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/PlaybackSource\/isPlaying()"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAudioPlayback"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaybackSource","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"PlaybackSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PlaybackSource"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource\/fragments","op":"replace"},{"value":"initPlayback","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource~1initPlayback()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initPlayback"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource~1initPlayback()\/fragments","op":"replace"},{"value":"isPlaying","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource~1isPlaying()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isPlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1PlaybackSource~1isPlaying()\/fragments","op":"replace"},{"value":"MCAudioPlayback","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCAudioPlayback"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}