{"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/bitsPerSample","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/channelNumber","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/data","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/frameNumber","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/sampleRate"]}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioFrame"}],"externalID":"c:objc(cs)MCAudioFrame","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MCAudioFrame"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","title":"MCAudioFrame"},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame"],"title":"Inherited By","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioFrame","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"codeListing","syntax":null,"code":["var frame: MCAudioFrame = MCAudioFrame()","var source: MCCustomAudioSourceBuilder().build()","frame.bitsPerSample = 32; \/\/ We are using Float32 as an example","frame.channelNumber = numChannels","frame.sampleRate = Int32(sampleRate)","frame.frameNumber = Int(sampleRate * chunkTime \/ 1000);","\/\/ Imagine audioData is a pointer to some data","frame.data = UnsafeRawPointer(audioData)","source.onAudioFrame(frame)"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudioframe"]},{"paths":["\/documentation\/millicastsdk\/mcaudioframe"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"text":"Audio frame that contains audio data. Used with ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","isActive":true},{"type":"text","text":" "},{"text":"to feed custom audio frames into source used by a ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","isActive":true},{"text":".","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/bitsPerSample":{"url":"\/documentation\/millicastsdk\/mcaudioframe\/bitspersample","kind":"symbol","title":"bitsPerSample","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/bitsPerSample","abstract":[{"type":"text","text":"The number of bits per audio sample."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bitsPerSample"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"bitsPerSample"}],"type":"topic"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/channelNumber":{"title":"channelNumber","navigatorTitle":[{"kind":"identifier","text":"channelNumber"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"channelNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The number of audio channels defining whether the audio is mono, stereo, or has more complex channel configurations."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/channelNumber","url":"\/documentation\/millicastsdk\/mcaudioframe\/channelnumber","type":"topic","role":"symbol","kind":"symbol"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/data":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SV","text":"UnsafeRawPointer"},{"kind":"text","text":"!"}],"url":"\/documentation\/millicastsdk\/mcaudioframe\/data","title":"data","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The audio data containing raw audio samples."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/data"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/frameNumber":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameNumber"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/frameNumber","abstract":[{"type":"text","text":"The number of frames in the data array. The number of frames is dependent on the sample rate and chunk time."}],"type":"topic","navigatorTitle":[{"text":"frameNumber","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcaudioframe\/framenumber","title":"frameNumber","kind":"symbol","role":"symbol"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame/sampleRate":{"type":"topic","navigatorTitle":[{"text":"sampleRate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"url":"\/documentation\/millicastsdk\/mcaudioframe\/samplerate","title":"sampleRate","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The sample rate of the audio data, which is either 48kHz or 44.1kHz."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/sampleRate"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCPublisher"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"url":"\/documentation\/millicastsdk\/mcpublisher","title":"MCPublisher","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferFrame":{"title":"MCCMSampleBufferFrame","type":"topic","kind":"symbol","abstract":[{"text":"Class responsible for initializing a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"},{"text":"  from a ","type":"text"},{"code":"CMSampleBuffer","type":"codeVoice"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame","navigatorTitle":[{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"url":"\/documentation\/millicastsdk\/mccmsamplebufferframe"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame":{"url":"\/documentation\/millicastsdk\/mcaudioframe","title":"MCAudioFrame","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCAudioFrame","kind":"identifier"}],"abstract":[{"text":"Audio frame that contains audio data. Used with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)"},{"text":" ","type":"text"},{"type":"text","text":"to feed custom audio frames into source used by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioFrame"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","kind":"symbol","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)","title":"onAudioFrame(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAudioFrame"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"text":"!)","kind":"text"}],"abstract":[{"text":"To be called whenever the application wishes to feed audio frames to the source.","type":"text"}],"navigatorTitle":[{"text":"onAudioFrame:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"MCAudioFrame","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MCAudioFrame"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioFrame"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/bitsPerSample","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/channelNumber","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/data","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/frameNumber","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame\/sampleRate"],"title":"Instance Properties"}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame"],"title":"Inherited By","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioFrame","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1bitsPerSample\/title","value":"bitsPerSample","op":"replace"},{"value":[{"text":"bitsPerSample","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1bitsPerSample\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1channelNumber\/title","value":"channelNumber","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1channelNumber\/fragments","value":[{"text":"channelNumber","kind":"identifier"}],"op":"replace"},{"value":"data","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1data\/title"},{"op":"replace","value":[{"text":"data","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1data\/fragments"},{"op":"replace","value":"frameNumber","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1frameNumber\/title"},{"op":"replace","value":[{"text":"frameNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1frameNumber\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1sampleRate\/title","value":"sampleRate"},{"op":"replace","value":[{"kind":"identifier","text":"sampleRate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame~1sampleRate\/fragments"},{"op":"replace","value":"MCPublisher","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title"},{"value":[{"text":"MCPublisher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/title","op":"replace","value":"MCCMSampleBufferFrame"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/title","op":"replace","value":"MCAudioFrame"},{"value":[{"kind":"identifier","text":"MCAudioFrame"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","value":"onAudioFrame:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onAudioFrame:","kind":"identifier"}]}]}]}