{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"MCGenericErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcgenericerrordomain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcgenericerrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericErrorDomain"},"metadata":{"title":"MCGenericErrorDomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"MCGenericErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Global Variable","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorDomain"}],"role":"symbol","modules":[{"name":"MillicastSDK"}],"externalID":"c:@MCGenericErrorDomain","symbolKind":"var"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCGenericErrorDomain":{"title":"MCGenericErrorDomain","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCGenericErrorDomain","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"MCGenericErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorDomain"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcgenericerrordomain","abstract":[],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"MCGenericErrorDomain","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"kind":"identifier","text":"MCGenericErrorDomain"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCGenericErrorDomain"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"MCGenericErrorDomain","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericErrorDomain\/title"},{"value":[{"text":"MCGenericErrorDomain","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCGenericErrorDomain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}