{"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"type":"text","text":"Statistics for an RTP stream."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRtpStreamStats"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats"]},{"paths":["\/documentation\/millicastsdk\/mcrtpstreamstats"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/codec_id","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/kind","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/ssrc","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/transport_id"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats"},"metadata":{"title":"MCRtpStreamStats","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRtpStreamStats"}],"externalID":"c:objc(cs)MCRtpStreamStats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCRtpStreamStats"}],"modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"role":"symbol","abstract":[{"type":"text","text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream."}],"title":"MCReceivedRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","type":"topic"},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-kind":{"titleInlineContent":[{"type":"text","text":"kind"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-kind","type":"link","title":"kind","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-kind"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-ssrc":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc","title":"ssrc","titleInlineContent":[{"type":"text","text":"ssrc"}],"type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/transport_id":{"role":"symbol","abstract":[{"text":"The transport layer associated with the stream. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid","isActive":true}],"kind":"symbol","type":"topic","title":"transport_id","url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/transport_id","navigatorTitle":[{"text":"transport_id","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/transport_id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transport_id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"https://w3c.github.io/webrtc-stats/#introduction":{"titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","type":"link","title":"WebRTC standard","url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/codec_id":{"title":"codec_id","url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/codec_id","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/codec_id","type":"topic","navigatorTitle":[{"text":"codec_id","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec_id"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The identifier of the codec used for encoding media carried by the stream. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-codecid":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-codecid","title":"codecId","titleInlineContent":[{"type":"text","text":"codecId"}],"type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/kind":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The type of media carried by the stream, either audio or video. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-kind"}],"navigatorTitle":[{"kind":"identifier","text":"kind"}],"title":"kind","url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/kind","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/kind"},"doc://MillicastSDK/documentation/MillicastSDK/MCSentRtpStreamStats":{"kind":"symbol","role":"symbol","title":"MCSentRtpStreamStats","navigatorTitle":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSentRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcsentrtpstreamstats","type":"topic","abstract":[{"text":"Statistics related to an outgoing RTP stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats/ssrc":{"title":"ssrc","url":"\/documentation\/millicastsdk\/mcrtpstreamstats\/ssrc","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/ssrc","type":"topic","navigatorTitle":[{"text":"ssrc","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ssrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The synchronization source identifier for the stream. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-ssrc"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCStats","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","url":"\/documentation\/millicastsdk\/mcstats","type":"topic","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"title":"MCStats","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRtpStreamStats":{"title":"MCRtpStreamStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRtpStreamStats"}],"navigatorTitle":[{"text":"MCRtpStreamStats","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtpstreamstats","type":"topic","abstract":[{"text":"Statistics for an RTP stream.","type":"text"}],"role":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-transportid":{"titleInlineContent":[{"type":"text","text":"transportId"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid","type":"link","title":"transportId","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcrtpstreamstats-transportid"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCRtpStreamStats","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MCRtpStreamStats","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MCRtpStreamStats","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/codec_id","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/kind","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/ssrc","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRtpStreamStats\/transport_id"],"title":"Instance Properties"}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSentRtpStreamStats"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRtpStreamStats"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","value":"MCReceivedRtpStreamStats"},{"value":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1transport_id\/title","op":"replace","value":"transport_id"},{"value":[{"text":"transport_id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1transport_id\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1codec_id\/title","value":"codec_id","op":"replace"},{"value":[{"text":"codec_id","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1codec_id\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1kind\/title","value":"kind"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1kind\/fragments","op":"replace","value":[{"text":"kind","kind":"identifier"}]},{"op":"replace","value":"MCSentRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCSentRtpStreamStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSentRtpStreamStats\/fragments"},{"value":"ssrc","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1ssrc\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats~1ssrc\/fragments","value":[{"kind":"identifier","text":"ssrc"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","value":"MCStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments","value":[{"text":"MCStats","kind":"identifier"}],"op":"replace"},{"value":"MCRtpStreamStats","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRtpStreamStats\/fragments","value":[{"text":"MCRtpStreamStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}