{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer"},"sections":[],"metadata":{"title":"MCRTSRemoteVideoTrackLayer","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayer"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/init(layer:)"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/temporalLayerId"],"title":"Instance Properties"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxTemporalLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetSpatialLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetTemporalLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxTemporalLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setTemporalLayerId(_:)"],"title":"Instance Methods"}],"abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"text":" ","type":"text"},{"text":"the client wants to inform the media server to select.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetMaxSpatialLayerId(_:)":{"title":"resetMaxSpatialLayerId(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxSpatialLayerId(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetMaxSpatialLayerId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"resetMaxSpatialLayerId:","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetmaxspatiallayerid(_:)","abstract":[{"text":"Reset the max spatial layer ID","type":"text"}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/spatialLayerId":{"abstract":[{"text":"The spatial layer ID of the SVC layer you wish to select","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/spatiallayerid","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/spatialLayerId","navigatorTitle":[{"text":"spatialLayerId","kind":"identifier"}],"title":"spatialLayerId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"spatialLayerId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetTemporalLayerId()":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resettemporallayerid()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetTemporalLayerId"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[{"type":"text","text":"Reset the temporal layer ID."}],"navigatorTitle":[{"kind":"identifier","text":"resetTemporalLayerId"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetTemporalLayerId()","title":"resetTemporalLayerId()","role":"symbol"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/temporalLayerId":{"navigatorTitle":[{"text":"temporalLayerId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporalLayerId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/temporallayerid","abstract":[{"type":"text","text":"The temporal layer ID of the SVC layer you wish to select."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/temporalLayerId","title":"temporalLayerId"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setMaxTemporalLayerId(_:)":{"title":"setMaxTemporalLayerId(_:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxtemporallayerid(_:)","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxTemporalLayerId(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMaxTemporalLayerId:"}],"abstract":[{"text":"Set the maximum temporal layer ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMaxTemporalLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":")","kind":"text"}]},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setMaxSpatialLayerId(_:)":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setmaxspatiallayerid(_:)","type":"topic","kind":"symbol","role":"symbol","title":"setMaxSpatialLayerId(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMaxSpatialLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setMaxSpatialLayerId:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxSpatialLayerId(_:)","abstract":[{"text":"Set the maximum spatial layer ID.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetSpatialLayerId()":{"type":"topic","kind":"symbol","role":"symbol","title":"resetSpatialLayerId()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetSpatialLayerId()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetSpatialLayerId"},{"kind":"text","text":"()"}],"abstract":[{"text":"Reset the spatial layer ID.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resetSpatialLayerId"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetspatiallayerid()"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/maxSpatialLayerId":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxSpatialLayerId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxSpatialLayerId"}],"title":"maxSpatialLayerId","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/maxspatiallayerid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxSpatialLayerId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"text":"The maximum spatial layer to allow the media server to select automatically.","type":"text"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/init(layer:)":{"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/init(layer:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLayer:"}],"abstract":[{"type":"text","text":"Convenience initializer to initialize the values with the"},{"text":" ","type":"text"},{"type":"text","text":"remote track layer event if no other modification is required."}],"title":"init(layer:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/init(layer:)","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setTemporalLayerId(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setTemporalLayerId","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setTemporalLayerId(_:)","navigatorTitle":[{"text":"setTemporalLayerId:","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/settemporallayerid(_:)","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setTemporalLayerId(_:)","abstract":[{"text":"Set the temporal layer ID.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"title":"MCRTSRemoteVideoTrackLayer","kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"abstract":[{"text":"This class represents the selected layer information which","type":"text"},{"text":" ","type":"text"},{"text":"the client wants to inform the media server to select.","type":"text"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/setSpatialLayerId(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSpatialLayerId:"}],"abstract":[{"type":"text","text":"Set the spatial layer ID."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setSpatialLayerId(_:)","title":"setSpatialLayerId(_:)","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/setspatiallayerid(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setSpatialLayerId","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/encodingId":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodingId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"encodingId","navigatorTitle":[{"text":"encodingId","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/encodingid","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/encodingId","abstract":[{"text":"The encoding Id of the layer you wish to select","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/maxTemporalLayerId":{"navigatorTitle":[{"kind":"identifier","text":"maxTemporalLayerId"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxTemporalLayerId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxTemporalLayerId"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The maximum temporal layer to allow the media server to select automatically."}],"title":"maxTemporalLayerId","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/maxtemporallayerid","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer/resetMaxTemporalLayerId()":{"navigatorTitle":[{"kind":"identifier","text":"resetMaxTemporalLayerId"}],"type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxTemporalLayerId()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetMaxTemporalLayerId","kind":"identifier"},{"kind":"text","text":"()"}],"title":"resetMaxTemporalLayerId()","kind":"symbol","abstract":[{"type":"text","text":"Reset the max temporal layer ID"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer\/resetmaxtemporallayerid()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MCRTSRemoteVideoTrackLayer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/encodingId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxSpatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/maxTemporalLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/spatialLayerId","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/temporalLayerId"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/init(layer:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetMaxTemporalLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetSpatialLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/resetTemporalLayerId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setMaxTemporalLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setSpatialLayerId(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer\/setTemporalLayerId(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxSpatialLayerId(_:)\/title","value":"resetMaxSpatialLayerId:"},{"value":[{"text":"- ","kind":"text"},{"text":"resetMaxSpatialLayerId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxSpatialLayerId(_:)\/fragments"},{"value":"spatialLayerId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1spatialLayerId\/title","op":"replace"},{"value":[{"text":"spatialLayerId","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1spatialLayerId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetTemporalLayerId()\/title","value":"resetTemporalLayerId","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetTemporalLayerId()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetTemporalLayerId"}]},{"value":"temporalLayerId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1temporalLayerId\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1temporalLayerId\/fragments","value":[{"text":"temporalLayerId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxTemporalLayerId(_:)\/title","value":"setMaxTemporalLayerId:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setMaxTemporalLayerId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxTemporalLayerId(_:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxSpatialLayerId(_:)\/title","value":"setMaxSpatialLayerId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setMaxSpatialLayerId(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMaxSpatialLayerId:","kind":"identifier"}]},{"op":"replace","value":"resetSpatialLayerId","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetSpatialLayerId()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetSpatialLayerId()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resetSpatialLayerId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1maxSpatialLayerId\/title","value":"maxSpatialLayerId","op":"replace"},{"value":[{"kind":"identifier","text":"maxSpatialLayerId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1maxSpatialLayerId\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1init(layer:)\/title","value":"initWithLayer:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLayer:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1init(layer:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setTemporalLayerId(_:)\/title","value":"setTemporalLayerId:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setTemporalLayerId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTemporalLayerId:"}]},{"value":"MCRTSRemoteVideoTrackLayer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setSpatialLayerId(_:)\/title","value":"setSpatialLayerId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1setSpatialLayerId(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setSpatialLayerId:","kind":"identifier"}]},{"value":"encodingId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1encodingId\/title"},{"value":[{"text":"encodingId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1encodingId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1maxTemporalLayerId\/title","value":"maxTemporalLayerId"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1maxTemporalLayerId\/fragments","value":[{"text":"maxTemporalLayerId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxTemporalLayerId()\/title","value":"resetMaxTemporalLayerId","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer~1resetMaxTemporalLayerId()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resetMaxTemporalLayerId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}