{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"},"abstract":[{"type":"text","text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"title":"MCSampleBufferVideoUIView","externalID":"c:@M@MillicastSDK@objc(cs)MCSampleBufferVideoUIView","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}]},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSCoding","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoViewType","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/objc(pl)CALayerDelegate","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/s8SendableP","doc:\/\/MillicastSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/MillicastSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/MillicastSDK\/objc(pl)UIAppearance","doc:\/\/MillicastSDK\/objc(pl)UIAppearanceContainer","doc:\/\/MillicastSDK\/objc(pl)UICoordinateSpace","doc:\/\/MillicastSDK\/objc(pl)UIDynamicItem","doc:\/\/MillicastSDK\/objc(pl)UIFocusEnvironment","doc:\/\/MillicastSDK\/objc(pl)UIFocusItem","doc:\/\/MillicastSDK\/objc(pl)UIFocusItemContainer","doc:\/\/MillicastSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/MillicastSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/MillicastSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/MillicastSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/MillicastSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/MillicastSDK\/objc(pl)UITraitEnvironment","doc:\/\/MillicastSDK\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview"]}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:renderer:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/mirror","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/sampleBufferDisplayLayer","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/scalingMode","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/videoSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/updateRenderer(_:)"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/layerClass"],"title":"Type Properties"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/scalingMode":{"title":"scalingMode","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/scalingmode","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/scalingMode","abstract":[{"type":"text","text":"ScalingMode for video."},{"type":"text","text":" "},{"type":"text","text":"Use this to decide how the video is displayed within the bounds of the UIView."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scalingMode"},{"kind":"text","text":": "},{"text":"MCVideoViewScalingMode","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO","kind":"typeIdentifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/layerClass":{"abstract":[],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/layerclass","title":"layerClass","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"layerClass","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}],"navigatorTitle":[{"kind":"identifier","text":"layerClass"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/layerClass","type":"topic"},"doc://MillicastSDK/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/updateRenderer(_:)":{"title":"updateRenderer(_:)","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/updaterenderer(_:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/updateRenderer(_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRenderer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer"},{"kind":"text","text":")"}]},"doc://MillicastSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIResponderStandardEditActions"},"doc://MillicastSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIDynamicItem"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s8SendableP"},"doc://MillicastSDK/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)UIView"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/5UIKit23UITraitChangeObservableP"},"doc://MillicastSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/videoSize":{"title":"videoSize","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/videosize","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/videoSize","abstract":[{"type":"text","text":"The resolution of the video stream received from the track."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/MCCMSampleBufferVideoRendererDelegate-Implementations":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations","type":"topic","title":"MCCMSampleBufferVideoRendererDelegate Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/sampleBufferDisplayLayer":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sampleBufferDisplayLayer"},{"kind":"text","text":": "},{"text":"AVSampleBufferDisplayLayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVSampleBufferDisplayLayer"}],"title":"sampleBufferDisplayLayer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/sampleBufferDisplayLayer","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/samplebufferdisplaylayer","abstract":[{"type":"text","text":"The AVSampleBufferDisplayLayer used to display the track."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate","title":"MCCMSampleBufferVideoRendererDelegate","type":"topic","role":"symbol","abstract":[{"text":"Delegate for  receiving raw video ","type":"text"},{"type":"codeVoice","code":"CMSampleBufferRef"},{"text":" ready for rendering","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}]},"doc://MillicastSDK/objc(pl)UIFocusItem":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://MillicastSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://MillicastSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoViewType":{"title":"MCVideoViewType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoViewType","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoViewType"}],"navigatorTitle":[{"text":"MCVideoViewType","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideoviewtype","abstract":[{"type":"text","text":"Common properties among the Views provided"},{"type":"text","text":" "},{"text":"in the SDK.","type":"text"}],"role":"symbol"},"doc://MillicastSDK/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://MillicastSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://MillicastSDK/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://MillicastSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/delegate":{"title":"delegate","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/delegate","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/delegate","abstract":[{"type":"text","text":"A delegate for receiving view related events like video frame size changes"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoViewDelegate","preciseIdentifier":"s:12MillicastSDK19MCVideoViewDelegateP"},{"text":"?","kind":"text"}]},"doc://MillicastSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAppearance"},"doc://MillicastSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAccessibilityIdentification"},"doc://MillicastSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/mirror":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/mirror","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mirror","kind":"symbol","title":"mirror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirror"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"If true the track is being displayed mirrored in the vertical axes."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","title":"MCSampleBufferVideoUIView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","type":"topic"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAppearanceContainer"},"doc://MillicastSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSCoding"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/init(frame:renderer:)":{"title":"init(frame:renderer:)","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/init(frame:renderer:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/init(frame:renderer:)","abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCSampleBufferVideoUIView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}]},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Type Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/layerClass"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSampleBufferVideoUIView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"layerClass","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1layerClass\/title"},{"value":[{"text":"layerClass","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1layerClass\/fragments"},{"value":"MCCMSampleBufferVideoRendererDelegate","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments","op":"replace"}]}]}