{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/NDI","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/app","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/custom","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/deckLink","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/device","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/mic","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/monitor"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSourceType"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"title":"MCSourceType","modules":[{"name":"MillicastSDK"}],"roleHeading":"Enumeration","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSourceType"}],"symbolKind":"enum","externalID":"c:@E@MCSourceType"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsourcetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"The Source type","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/Equatable-Implementations":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/millicastsdk\/mcsourcetype\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup","kind":"article"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/mic":{"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeMic"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/mic","title":"MCSourceType.mic","url":"\/documentation\/millicastsdk\/mcsourcetype\/mic","abstract":[{"text":"Microphone devices source","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mic","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/deckLink":{"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeDeckLink"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/deckLink","title":"MCSourceType.deckLink","url":"\/documentation\/millicastsdk\/mcsourcetype\/decklink","abstract":[{"type":"text","text":"DeckLink devices sources (input and output)."}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deckLink","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/s8SendableP":{"identifier":"doc:\/\/MillicastSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/custom":{"abstract":[{"text":"Custom audio source.","type":"text"}],"title":"MCSourceType.custom","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/custom","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/custom","navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeCustom"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/millicastsdk\/mcsourcetype\/rawrepresentable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/RawRepresentable-Implementations"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/init(rawvalue:)","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/init(rawValue:)"},"doc://MillicastSDK/SY":{"identifier":"doc:\/\/MillicastSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/monitor":{"abstract":[{"text":"Fullscreen capture source.","type":"text"}],"title":"MCSourceType.monitor","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"monitor","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/monitor","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/monitor","navigatorTitle":[{"text":"MCSourceTypeMonitor","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/device":{"abstract":[{"type":"text","text":"Hardware sources, camera, playback devices."}],"title":"MCSourceType.device","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"device","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/device","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/device","navigatorTitle":[{"text":"MCSourceTypeDevice","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/NDI":{"abstract":[{"text":"Ndi sources (input and output).","type":"text"}],"title":"MCSourceType.NDI","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NDI","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/ndi","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/NDI","navigatorTitle":[{"text":"MCSourceTypeNDI","kind":"identifier"}]},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/app":{"abstract":[{"type":"text","text":"Application screen capture source"}],"title":"MCSourceType.app","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"app","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsourcetype\/app","kind":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/app","navigatorTitle":[{"text":"MCSourceTypeApp","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"url":"\/documentation\/millicastsdk\/mcsourcetype","title":"MCSourceType","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"MCSourceType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","abstract":[{"text":"The Source type","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCSourceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MCSourceType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/NDI","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/app","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/custom","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/deckLink","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/device","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/mic","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/monitor"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSourceType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"MCSourceTypeMic","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1mic\/title"},{"value":[{"text":"MCSourceTypeMic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1mic\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1deckLink\/title","value":"MCSourceTypeDeckLink"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1deckLink\/fragments","op":"replace","value":[{"text":"MCSourceTypeDeckLink","kind":"identifier"}]},{"value":"MCSourceTypeCustom","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1custom\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1custom\/fragments","value":[{"kind":"identifier","text":"MCSourceTypeCustom"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1monitor\/title","value":"MCSourceTypeMonitor","op":"replace"},{"value":[{"text":"MCSourceTypeMonitor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1monitor\/fragments"},{"op":"replace","value":"MCSourceTypeDevice","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1device\/title"},{"value":[{"text":"MCSourceTypeDevice","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1device\/fragments","op":"replace"},{"value":"MCSourceTypeNDI","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1NDI\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1NDI\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCSourceTypeNDI"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1app\/title","value":"MCSourceTypeApp"},{"value":[{"kind":"identifier","text":"MCSourceTypeApp"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1app\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title","value":"MCSourceType","op":"replace"},{"value":[{"kind":"identifier","text":"MCSourceType"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments"}]}]}