{"kind":"symbol","abstract":[{"type":"text","text":"Gathers information about the source."}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSource"}],"symbolKind":"class","title":"MCSource","role":"symbol","externalID":"c:objc(cs)MCSource","navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSource","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"],"type":"inheritedBy"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsource"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsource"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getName()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getType()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getTypeAsString()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getUniqueId()"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayback","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","type":"topic","role":"symbol","abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"type":"text","text":" "},{"text":"This class inherits the Source class, however this is not","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioPlayback"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlayback","kind":"identifier"}],"title":"MCAudioPlayback"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource":{"type":"topic","title":"MCSource","kind":"symbol","url":"\/documentation\/millicastsdk\/mcsource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSource"}],"abstract":[{"type":"text","text":"Gathers information about the source."}],"navigatorTitle":[{"kind":"identifier","text":"MCSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource/getName()":{"title":"getName()","navigatorTitle":[{"text":"getName","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getName","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Gets the name of the source."}],"url":"\/documentation\/millicastsdk\/mcsource\/getname()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource/getUniqueId()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUniqueId"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"getUniqueId","kind":"identifier"}],"abstract":[{"text":"Gets the unique identifier of the source.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcsource\/getuniqueid()","title":"getUniqueId()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getUniqueId()","kind":"symbol","type":"topic"},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","role":"symbol","navigatorTitle":[{"text":"MCCustomAudioSource","kind":"identifier"}],"type":"topic","title":"MCCustomAudioSource","abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCustomAudioSource","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource"},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource":{"title":"MCVideoSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCVideoSource"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideosource","abstract":[{"type":"text","text":"Responsible for managing video sources."}],"role":"symbol"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCCoreVideoSource":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCoreVideoSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","url":"\/documentation\/millicastsdk\/mccorevideosource","abstract":[{"type":"text","text":"A Source that allows applications to feed their own raw CVPixelBuffers for publishing."}],"role":"symbol","title":"MCCoreVideoSource","navigatorTitle":[{"text":"MCCoreVideoSource","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"title":"MCAudioSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioSource"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioSource"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosource","abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource/getTypeAsString()":{"title":"getTypeAsString()","role":"symbol","abstract":[{"type":"text","text":"Gets the video source type as a NSString."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getTypeAsString","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"getTypeAsString"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getTypeAsString()","url":"\/documentation\/millicastsdk\/mcsource\/gettypeasstring()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCSource/getType()":{"abstract":[{"type":"text","text":"Gets the source type."}],"url":"\/documentation\/millicastsdk\/mcsource\/gettype()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getType()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getType"},{"text":"() -> ","kind":"text"},{"text":"MCSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCSourceType"}],"title":"getType()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getType"}],"type":"topic"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"MCSource","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MCSource"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MCSource","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getName()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getType()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getTypeAsString()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSource\/getUniqueId()"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCoreVideoSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCAudioPlayback","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}],"op":"replace"},{"value":"MCSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/title"},{"value":[{"kind":"identifier","text":"MCSource"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource\/fragments"},{"value":"getName","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getName()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getName()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getName"}],"op":"replace"},{"value":"getUniqueId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getUniqueId()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"getUniqueId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getUniqueId()\/fragments"},{"value":"MCCustomAudioSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCCustomAudioSource"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/title","value":"MCVideoSource"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCVideoSource"}]},{"value":"MCCoreVideoSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/title"},{"value":[{"kind":"identifier","text":"MCCoreVideoSource"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCoreVideoSource\/fragments","op":"replace"},{"value":"MCAudioSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","value":[{"text":"MCAudioSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getTypeAsString()\/title","value":"getTypeAsString","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getTypeAsString()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTypeAsString","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getType()\/title","value":"getType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSource~1getType()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getType"}]}]}]}