{"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/audioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/codec","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/iceCandidatePair","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/inboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/outboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteInboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteOutboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/videoTrack"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"role":"symbol","title":"MCStatsType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStatsType"}],"symbolKind":"enum","navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"externalID":"c:@E@MCStatsType","roleHeading":"Enumeration","modules":[{"name":"MillicastSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatstype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcstatstype"]}],"sections":[],"abstract":[{"text":"Different types of statistics.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/inboundRTP":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeInboundRTP"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/inboundRTP","url":"\/documentation\/millicastsdk\/mcstatstype\/inboundrtp","title":"MCStatsType.inboundRTP","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inboundRTP"}],"type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/remoteOutboundRTP":{"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeRemoteOutboundRTP","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteOutboundRTP","url":"\/documentation\/millicastsdk\/mcstatstype\/remoteoutboundrtp","kind":"symbol","title":"MCStatsType.remoteOutboundRTP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"remoteOutboundRTP","kind":"identifier"}],"type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/codec":{"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeCodec","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/codec","url":"\/documentation\/millicastsdk\/mcstatstype\/codec","title":"MCStatsType.codec","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"codec"}],"type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/iceCandidatePair":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iceCandidatePair","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeIceCandidatePair"}],"kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcstatstype\/icecandidatepair","title":"MCStatsType.iceCandidatePair","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/iceCandidatePair"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype\/init(rawvalue:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/mediaSource":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mediaSource","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeMediaSource"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaSource","url":"\/documentation\/millicastsdk\/mcstatstype\/mediasource","abstract":[],"type":"topic","title":"MCStatsType.mediaSource","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"abstract":[{"text":"Different types of statistics.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","title":"MCStatsType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCStatsType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic"},"doc://MillicastSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SY","title":"Swift.RawRepresentable"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/mediaTrack":{"url":"\/documentation\/millicastsdk\/mcstatstype\/mediatrack","title":"MCStatsType.mediaTrack","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaTrack"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaTrack","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeMediaTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/millicastsdk\/mcstatstype\/rawrepresentable-implementations","abstract":[],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/Equatable-Implementations","url":"\/documentation\/millicastsdk\/mcstatstype\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","abstract":[]},"doc://MillicastSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/remoteInboundRTP":{"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeRemoteInboundRTP","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteInboundRTP","url":"\/documentation\/millicastsdk\/mcstatstype\/remoteinboundrtp","kind":"symbol","title":"MCStatsType.remoteInboundRTP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"remoteInboundRTP","kind":"identifier"}],"type":"topic","abstract":[]},"doc://MillicastSDK/s8SendableP":{"identifier":"doc:\/\/MillicastSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/videoTrack":{"title":"MCStatsType.videoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/videoTrack","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"videoTrack","kind":"identifier"}],"navigatorTitle":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcstatstype\/videotrack","abstract":[],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/outboundRTP":{"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeOutboundRTP","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/outboundRTP","url":"\/documentation\/millicastsdk\/mcstatstype\/outboundrtp","kind":"symbol","title":"MCStatsType.outboundRTP","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"outboundRTP"}],"type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType/audioTrack":{"role":"symbol","navigatorTitle":[{"text":"MCStatsTypeAudioTrack","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/audioTrack","url":"\/documentation\/millicastsdk\/mcstatstype\/audiotrack","title":"MCStatsType.audioTrack","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"audioTrack","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCStatsType","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCStatsType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCStatsType"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/audioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/codec","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/iceCandidatePair","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/inboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/mediaTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/outboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteInboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/remoteOutboundRTP","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType\/videoTrack"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCStatsTypeInboundRTP","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1inboundRTP\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsTypeInboundRTP"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1inboundRTP\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteOutboundRTP\/title","op":"replace","value":"MCStatsTypeRemoteOutboundRTP"},{"value":[{"text":"MCStatsTypeRemoteOutboundRTP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteOutboundRTP\/fragments"},{"op":"replace","value":"MCStatsTypeCodec","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1codec\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1codec\/fragments","value":[{"text":"MCStatsTypeCodec","kind":"identifier"}]},{"value":"MCStatsTypeIceCandidatePair","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1iceCandidatePair\/title","op":"replace"},{"value":[{"text":"MCStatsTypeIceCandidatePair","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1iceCandidatePair\/fragments"},{"value":"MCStatsTypeMediaSource","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaSource\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaSource\/fragments","value":[{"text":"MCStatsTypeMediaSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","value":"MCStatsType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaTrack\/title","op":"replace","value":"MCStatsTypeMediaTrack"},{"value":[{"kind":"identifier","text":"MCStatsTypeMediaTrack"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1mediaTrack\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteInboundRTP\/title","value":"MCStatsTypeRemoteInboundRTP"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1remoteInboundRTP\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsTypeRemoteInboundRTP"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1videoTrack\/title","op":"replace","value":"MCStatsTypeVideoTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1videoTrack\/fragments","value":[{"text":"MCStatsTypeVideoTrack","kind":"identifier"}]},{"value":"MCStatsTypeOutboundRTP","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1outboundRTP\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1outboundRTP\/fragments","value":[{"kind":"identifier","text":"MCStatsTypeOutboundRTP"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1audioTrack\/title","op":"replace","value":"MCStatsTypeAudioTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType~1audioTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCStatsTypeAudioTrack"}]}]}]}