{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCSubscriberStatsLevel","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"externalID":"c:@E@MCSubscriberStatsLevel","title":"MCSubscriberStatsLevel"},"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/SY","doc:\/\/MillicastSDK\/s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcsubscriberstatslevel"]}],"kind":"symbol","abstract":[{"text":"Enum specifying the level of verbosity for stats.","type":"text"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/full","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/simplified"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/Equatable-Implementations","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/RawRepresentable-Implementations","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/simplified":{"abstract":[{"type":"text","text":"Contains only information about the stream, like bitrate"},{"type":"text","text":" "},{"type":"text","text":"resolution, frames dropped etc."}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/simplified","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevelSimplified"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/simplified","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"simplified"}],"title":"MCSubscriberStatsLevel.simplified","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/init(rawValue:)":{"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/init(rawValue:)","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/full":{"abstract":[{"type":"text","text":"Contains the full report which serializes"},{"type":"text","text":" "},{"type":"text","text":"All the fields in provided in MCSubscriberStats"},{"type":"text","text":" "},{"type":"text","text":"and MCTrackStats"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/full","navigatorTitle":[{"text":"MCSubscriberStatsLevelFull","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/full","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"full"}],"title":"MCSubscriberStatsLevel.full","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/Equatable-Implementations","url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel\/equatable-implementations","kind":"article","role":"collectionGroup"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://MillicastSDK/SY":{"identifier":"doc:\/\/MillicastSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSubscriberStatsLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"title":"MCSubscriberStatsLevel","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"url":"\/documentation\/millicastsdk\/mcsubscriberstatslevel","abstract":[{"type":"text","text":"Enum specifying the level of verbosity for stats."}],"type":"topic","role":"symbol"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/s8SendableP":{"identifier":"doc:\/\/MillicastSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"MCSubscriberStatsLevel","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/full","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSubscriberStatsLevel\/simplified"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSubscriberStatsLevel"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCSubscriberStatsLevelSimplified","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1simplified\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1simplified\/fragments","value":[{"kind":"identifier","text":"MCSubscriberStatsLevelSimplified"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1full\/title","value":"MCSubscriberStatsLevelFull","op":"replace"},{"value":[{"text":"MCSubscriberStatsLevelFull","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel~1full\/fragments"},{"op":"replace","value":"MCSubscriberStatsLevel","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSubscriberStatsLevel\/fragments","value":[{"kind":"identifier","text":"MCSubscriberStatsLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}