{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Represents a captured instance of a media source.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/enable(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/getId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/isEnabled()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/kind()"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"],"kind":"relationships","title":"Inherited By"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"metadata":{"title":"MCTrack","externalID":"c:objc(cs)MCTrack","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCTrack"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Class","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrack"]},{"paths":["\/documentation\/millicastsdk\/mctrack"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrack"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"},"references":{"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/objc(cs)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/kind()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/kind()","role":"symbol","title":"kind()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mctrack\/kind()","abstract":[{"type":"text","text":"Get  the track type."}],"navigatorTitle":[{"text":"kind","kind":"identifier"}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/getId()":{"title":"getId()","abstract":[{"type":"text","text":"Get the track Id."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getId"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"getId","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mctrack\/getid()","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/getId()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/isEnabled()":{"role":"symbol","abstract":[{"text":"Checks whether the track is enabled or not.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mctrack\/isenabled()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEnabled"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/isEnabled()","title":"isEnabled()"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","title":"MCTrack","role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/enable(_:)":{"title":"enable(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mctrack\/enable(_:)","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/enable(_:)","role":"symbol","abstract":[{"type":"text","text":"Enables or disables the track. A disabled audio track produces silence. A disabled video track produces black frames."}],"navigatorTitle":[{"kind":"identifier","text":"enable:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioTrack":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioTrack"}],"url":"\/documentation\/millicastsdk\/mcaudiotrack","title":"MCAudioTrack","abstract":[{"text":"Manages and plays a single audio resource.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioTrack"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack":{"title":"MCVideoTrack","url":"\/documentation\/millicastsdk\/mcvideotrack","navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoTrack"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"MCTrack","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"MCTrack"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCTrack"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/enable(_:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/getId()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/isEnabled()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/kind()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioTrack","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"kind","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1kind()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1kind()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"kind"}]},{"value":"getId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1getId()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1getId()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getId"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1isEnabled()\/title","value":"isEnabled","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1isEnabled()\/fragments"},{"value":"MCTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","value":[{"text":"MCTrack","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1enable(_:)\/title","value":"enable:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1enable(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enable:"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/title","value":"MCAudioTrack","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioTrack\/fragments"},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack\/fragments","value":[{"kind":"identifier","text":"MCVideoTrack"}]}]}]}