{"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"title":"MCWebrtcRemoteAudioTrack","symbolKind":"class","roleHeading":"Class","externalID":"c:objc(cs)MCWebrtcRemoteAudioTrack","modules":[{"name":"MillicastSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"]},{"type":"conformsTo","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/currentProjection(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/project(rtsRemoteAudioTrack:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/setVolume(_:completionHandler:)"],"title":"Instance Methods"}],"sections":[],"abstract":[{"type":"text","text":"The webrtc logical track’s audio interface."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack"]}],"references":{"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack":{"title":"MCWebrtcRemoteAudioTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"navigatorTitle":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack","abstract":[{"type":"text","text":"The webrtc logical track’s audio interface."}],"role":"symbol"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack/project(rtsRemoteAudioTrack:completionHandler:)":{"abstract":[{"text":"Enable the track and project from given RTS track.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"projectWithRTSRemoteAudioTrack:completionHandler:","kind":"identifier"}],"role":"symbol","title":"project(rtsRemoteAudioTrack:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rtsRemoteAudioTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","kind":"typeIdentifier","text":"MCRTSRemoteAudioTrack"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/project(rtsRemoteAudioTrack:completionHandler:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/project(rtsremoteaudiotrack:completionhandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrack":{"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrack"}],"type":"topic","role":"symbol","title":"MCWebrtcRemoteTrack","abstract":[{"type":"text","text":"The webrtc logical track."}],"navigatorTitle":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack/setVolume(_:completionHandler:)":{"abstract":[{"text":"Set audio volume","type":"text"}],"kind":"symbol","title":"setVolume(_:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setVolume","kind":"identifier"},{"kind":"text","text":"("},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/setVolume(_:completionHandler:)","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/setvolume(_:completionhandler:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"setVolume:completionHandler:","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteAudioTrack/currentProjection(completionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentProjection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteAudioTrack","text":"MCRTSRemoteAudioTrack"},{"kind":"text","text":"?, (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"currentProjectionWithCompletionHandler:","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/currentProjection(completionHandler:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremoteaudiotrack\/currentprojection(completionhandler:)","type":"topic","abstract":[],"kind":"symbol","title":"currentProjection(completionHandler:)"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MCWebrtcRemoteAudioTrack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/currentProjection(completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/project(rtsRemoteAudioTrack:completionHandler:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteAudioTrack\/setVolume(_:completionHandler:)"]}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCWebrtcRemoteAudioTrack","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrack","text":"MCWebrtcRemoteTrack","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/title","op":"replace","value":"MCWebrtcRemoteAudioTrack"},{"value":[{"kind":"identifier","text":"MCWebrtcRemoteAudioTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1project(rtsRemoteAudioTrack:completionHandler:)\/title","op":"replace","value":"projectWithRTSRemoteAudioTrack:completionHandler:"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1project(rtsRemoteAudioTrack:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"projectWithRTSRemoteAudioTrack:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/title","op":"replace","value":"MCWebrtcRemoteTrack"},{"value":[{"text":"MCWebrtcRemoteTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrack\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1setVolume(_:completionHandler:)\/title","value":"setVolume:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolume:completionHandler:"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1setVolume(_:completionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1currentProjection(completionHandler:)\/title","op":"replace","value":"currentProjectionWithCompletionHandler:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"currentProjectionWithCompletionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteAudioTrack~1currentProjection(completionHandler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}