{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"unowned(unsafe)"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/priority"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/priority"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/priority","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The priority of redundant streams that indicates the order in which backup streams should be broadcasted in the case of any problems with the primary stream. Refer to the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities"},{"type":"text","text":" to understand more."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"title":"priority","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCClientOptions(py)priority","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"priority"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","title":"MCClientOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCClientOptions"}],"abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCClientOptions"}],"url":"\/documentation\/millicastsdk\/mcclientoptions"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/priority":{"role":"symbol","title":"priority","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The priority of redundant streams that indicates the order in which backup streams should be broadcasted in the case of any problems with the primary stream. Refer to the "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities"},{"type":"text","text":" to understand more."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/priority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priority"}],"url":"\/documentation\/millicastsdk\/mcclientoptions\/priority"},"https://docs.dolby.io/streaming-apis/docs/redundant-ingest#4-set-priorities":{"title":"Redundant Ingest Guide","titleInlineContent":[{"type":"text","text":"Redundant Ingest Guide"}],"type":"link","identifier":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities","url":"https:\/\/docs.dolby.io\/streaming-apis\/docs\/redundant-ingest#4-set-priorities"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"priority"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"priority"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"priority"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","value":[{"kind":"identifier","text":"MCClientOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1priority\/title","value":"priority"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1priority\/fragments","value":[{"kind":"identifier","text":"priority"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}