{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"echo_return_loss","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss"]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"echo_return_loss","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"symbolKind":"property","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCAudioSourceStats(py)echo_return_loss","title":"echo_return_loss","navigatorTitle":[{"kind":"identifier","text":"echo_return_loss"}],"roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"The amount of echo signal lost in transmission or processing. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss","type":"reference"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/echo_return_loss":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss","navigatorTitle":[{"kind":"identifier","text":"echo_return_loss"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"echo_return_loss"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"The amount of echo signal lost in transmission or processing. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss","isActive":true,"type":"reference"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss","title":"echo_return_loss"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","navigatorTitle":[{"kind":"identifier","text":"MCAudioSourceStats"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioSourceStats","kind":"identifier"}],"abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosourcestats","title":"MCAudioSourceStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-echoreturnloss":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss","title":"echoReturnLoss","type":"link","titleInlineContent":[{"text":"echoReturnLoss","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"echo_return_loss","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"echo_return_loss"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"echo_return_loss"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss\/title","value":"echo_return_loss"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss\/fragments","value":[{"kind":"identifier","text":"echo_return_loss"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","value":"MCAudioSourceStats"},{"value":[{"kind":"identifier","text":"MCAudioSourceStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}