{"metadata":{"roleHeading":"Type Method","title":"get_type()","symbolKind":"method","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"externalID":"c:objc(cs)MCAudioSourceStats(cm)get_type","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats"]]},"abstract":[{"type":"text","text":"Returns the type of statistics."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/get_type()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}]}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/get_type()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats\/get_type()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","navigatorTitle":[{"kind":"identifier","text":"MCAudioSourceStats"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioSourceStats","kind":"identifier"}],"abstract":[{"text":"Stastistics representing an audio track that is attached to one or more senders.","type":"text"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcaudiosourcestats","title":"MCAudioSourceStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsType":{"url":"\/documentation\/millicastsdk\/mcstatstype","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MCStatsType","kind":"identifier"}],"title":"MCStatsType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","navigatorTitle":[{"text":"MCStatsType","kind":"identifier"}],"abstract":[{"text":"Different types of statistics.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/get_type()":{"title":"get_type()","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/get_type()","abstract":[{"type":"text","text":"Returns the type of statistics."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/get_type()","type":"topic","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get_type"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"get_type"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsType","text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"},{"text":") ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","value":"MCAudioSourceStats"},{"value":[{"kind":"identifier","text":"MCAudioSourceStats"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/title","op":"replace","value":"MCStatsType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}]},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1get_type()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1get_type()\/fragments"}]}]}