{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/get_type()"},"kind":"symbol","metadata":{"externalID":"c:objc(cs)MCRemoteInboundRtpStreamStats(cm)get_type","role":"symbol","title":"get_type()","roleHeading":"Type Method","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/get_type()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/get_type()"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats/get_type()":{"role":"symbol","type":"topic","title":"get_type()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}],"url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats\/get_type()","kind":"symbol","abstract":[{"type":"text","text":"Returns the type of statistics."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats\/get_type()","navigatorTitle":[{"kind":"identifier","text":"get_type"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRemoteInboundRtpStreamStats":{"navigatorTitle":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcremoteinboundrtpstreamstats","abstract":[{"text":"Statistics about an incoming remote RTP stream.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRemoteInboundRtpStreamStats","title":"MCRemoteInboundRtpStreamStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","title":"MCStatsType","abstract":[{"type":"text","text":"Different types of statistics."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"get_type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"},{"kind":"text","text":") "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"get_type","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1get_type()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats~1get_type()\/fragments"},{"op":"replace","value":"MCRemoteInboundRtpStreamStats","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/title"},{"op":"replace","value":[{"text":"MCRemoteInboundRtpStreamStats","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MCRemoteInboundRtpStreamStats"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRemoteInboundRtpStreamStats\/navigatorTitle"},{"op":"replace","value":"MCStatsType","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title"},{"op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments"},{"op":"replace","value":[{"text":"MCStatsType","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}