{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"title":"didChange(_:)","navigatorTitle":[{"text":"didChangeSize:","kind":"identifier"}],"required":true,"symbolKind":"method","externalID":"c:objc(pl)MCCMSampleBufferVideoRendererDelegate(im)didChangeSize:"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"size","content":[{"inlineContent":[{"type":"text","text":"The new video frame size."}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didChange(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"A delegate method that will be called when the size of the incoming video frames has changed.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didchange(_:)"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate/didChange(_:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"A delegate method that will be called when the size of the incoming video frames has changed."}],"role":"symbol","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate\/didchange(_:)","title":"didChange(_:)","navigatorTitle":[{"text":"didChangeSize:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate\/didChange(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCCMSampleBufferVideoRendererDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate for  receiving raw video "},{"type":"codeVoice","code":"CMSampleBufferRef"},{"type":"text","text":" ready for rendering"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorendererdelegate","title":"MCCMSampleBufferVideoRendererDelegate","navigatorTitle":[{"text":"MCCMSampleBufferVideoRendererDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRendererDelegate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didChangeSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didChangeSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didChangeSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didChange(_:)\/title","value":"didChangeSize:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate~1didChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeSize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/title","value":"MCCMSampleBufferVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRendererDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}