{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/recordStream","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)MCClientOptions(py)recordStream","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordStream"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"recordStream","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"title":"recordStream","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/recordstream"]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/recordstream"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recordStream","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"abstract":[{"type":"text","text":"Indicates whether the SDK should enable stream recording immediately after publishing. Make sure the recording feature is enabled for the publisher token. Recordings can then be viewed on the dashboard."}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/recordStream":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/recordStream","abstract":[{"text":"Indicates whether the SDK should enable stream recording immediately after publishing. Make sure the recording feature is enabled for the publisher token. Recordings can then be viewed on the dashboard.","type":"text"}],"type":"topic","title":"recordStream","url":"\/documentation\/millicastsdk\/mcclientoptions\/recordstream","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordStream"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"recordStream"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"kind":"symbol","type":"topic","title":"MCClientOptions","url":"\/documentation\/millicastsdk\/mcclientoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"recordStream"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"recordStream","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"recordStream","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"recordStream","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1recordStream\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1recordStream\/fragments","value":[{"text":"recordStream","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title","value":"MCClientOptions"},{"value":[{"kind":"identifier","text":"MCClientOptions"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments","op":"replace"}]}]}