{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upwardsLayerWaitTimeMs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcclientoptions\/upwardslayerwaittimems"]},{"paths":["\/documentation\/millicastsdk\/mcclientoptions\/upwardslayerwaittimems"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/upwardsLayerWaitTimeMs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Duration the Transponder will wait before switching back to a higher layer in msec. Expects an unsigned integer value."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"upwardsLayerWaitTimeMs","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"upwardsLayerWaitTimeMs","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MCClientOptions(py)upwardsLayerWaitTimeMs","symbolKind":"property","title":"upwardsLayerWaitTimeMs"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions/upwardsLayerWaitTimeMs":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions\/upwardsLayerWaitTimeMs","abstract":[{"type":"text","text":"Duration the Transponder will wait before switching back to a higher layer in msec. Expects an unsigned integer value."}],"type":"topic","title":"upwardsLayerWaitTimeMs","url":"\/documentation\/millicastsdk\/mcclientoptions\/upwardslayerwaittimems","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"upwardsLayerWaitTimeMs","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"upwardsLayerWaitTimeMs","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCClientOptions":{"role":"symbol","abstract":[{"type":"text","text":"The MCClientOptions class gathers options for the client."}],"kind":"symbol","type":"topic","title":"MCClientOptions","url":"\/documentation\/millicastsdk\/mcclientoptions","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCClientOptions"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCClientOptions","navigatorTitle":[{"text":"MCClientOptions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"upwardsLayerWaitTimeMs","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"upwardsLayerWaitTimeMs"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"retain","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"upwardsLayerWaitTimeMs"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1upwardsLayerWaitTimeMs\/title","value":"upwardsLayerWaitTimeMs"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions~1upwardsLayerWaitTimeMs\/fragments","value":[{"text":"upwardsLayerWaitTimeMs","kind":"identifier"}]},{"value":"MCClientOptions","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/title"},{"value":[{"text":"MCClientOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCClientOptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}