{"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/stopCapture()"]}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/capturesource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/capturesource"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSource"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureSource"}],"externalID":"c:objc(pl)CaptureSource","role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"CaptureSource","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"protocol","title":"CaptureSource"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"abstract":[{"text":"Manages the process of capturing the source by input sources, such as a microphone or a camera.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSource"}],"title":"CaptureSource","role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/capturesource","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureSource"}],"abstract":[{"text":"Manages the process of capturing the source by input sources, such as a microphone or a camera.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource/isCapturing()":{"navigatorTitle":[{"kind":"identifier","text":"isCapturing"}],"role":"symbol","required":true,"url":"\/documentation\/millicastsdk\/capturesource\/iscapturing()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/isCapturing()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCapturing"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[{"text":"Checks the current state of the capture process.","type":"text"}],"title":"isCapturing()","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource/stopCapture()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopCapture"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"text":"stopCapture","kind":"identifier"}],"required":true,"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/stopCapture()","type":"topic","url":"\/documentation\/millicastsdk\/capturesource\/stopcapture()","title":"stopCapture()","abstract":[{"text":"Stops a capture and releases the track and the underlying devices.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoSource":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoSource","kind":"identifier"}],"title":"MCVideoSource","type":"topic","abstract":[{"text":"Responsible for managing video sources.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideosource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource","navigatorTitle":[{"text":"MCVideoSource","kind":"identifier"}]},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/CaptureSource/startCapture()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"startCapture","kind":"identifier"}],"required":true,"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/startCapture()","type":"topic","url":"\/documentation\/millicastsdk\/capturesource\/startcapture()","title":"startCapture()","abstract":[{"text":"Initiates and starts the capture device and creates","type":"text"},{"text":" ","type":"text"},{"text":"the corresponding track. You should not call start capture twice in a row.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource":{"title":"MCAudioSource","url":"\/documentation\/millicastsdk\/mcaudiosource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioSource","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Manages the audio capture functionality."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","kind":"symbol","navigatorTitle":[{"text":"MCAudioSource","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"CaptureSource","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"CaptureSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"CaptureSource","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/isCapturing()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/startCapture()","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/CaptureSource\/stopCapture()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"type":"inheritsFrom"},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoSource"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureSource"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/title","value":"CaptureSource"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource\/fragments","value":[{"text":"CaptureSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1isCapturing()\/title","op":"replace","value":"isCapturing"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isCapturing"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1isCapturing()\/fragments"},{"value":"stopCapture","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1stopCapture()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"stopCapture","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1stopCapture()\/fragments"},{"op":"replace","value":"MCVideoSource","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoSource\/fragments","value":[{"text":"MCVideoSource","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"startCapture","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1startCapture()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1CaptureSource~1startCapture()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startCapture"}],"op":"replace"},{"op":"replace","value":"MCAudioSource","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource\/fragments","value":[{"kind":"identifier","text":"MCAudioSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}