{"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudiosourcestats"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioSourceStats"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Stastistics representing an audio track that is attached to one or more senders."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Class","modules":[{"name":"MillicastSDK"}],"title":"MCAudioSourceStats","symbolKind":"class","externalID":"c:objc(cs)MCAudioSourceStats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioSourceStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCAudioSourceStats"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/audio_level","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss_enhancement","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_audio_energy","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_samples_duration"]},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/get_type()"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCMediaSourceStats":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","abstract":[{"type":"text","text":"The MCMediaSourceStats class gathers statistics details."}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCMediaSourceStats"}],"navigatorTitle":[{"kind":"identifier","text":"MCMediaSourceStats"}],"title":"MCMediaSourceStats"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-totalaudioenergy":{"title":"totalAudioEnergy","type":"link","titleInlineContent":[{"type":"text","text":"totalAudioEnergy"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/echo_return_loss":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"echo_return_loss"}],"title":"echo_return_loss","role":"symbol","abstract":[{"type":"text","text":"The amount of echo signal lost in transmission or processing. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"echo_return_loss","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/total_samples_duration":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_samples_duration","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/total_samples_duration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"total_samples_duration"}],"title":"total_samples_duration","role":"symbol","abstract":[{"text":"The total duration of audio samples processed. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration","type":"reference"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_samples_duration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/get_type()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/get_type()","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/get_type()","kind":"symbol","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"title":"get_type()","role":"symbol","abstract":[{"type":"text","text":"Returns the type of statistics."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/total_audio_energy":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_audio_energy","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/total_audio_energy","kind":"symbol","navigatorTitle":[{"text":"total_audio_energy","kind":"identifier"}],"title":"total_audio_energy","role":"symbol","abstract":[{"text":"The cumulative energy of the audio signal over a period. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalaudioenergy","isActive":true,"type":"reference"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_audio_energy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/echo_return_loss_enhancement":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss_enhancement","url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/echo_return_loss_enhancement","kind":"symbol","navigatorTitle":[{"text":"echo_return_loss_enhancement","kind":"identifier"}],"title":"echo_return_loss_enhancement","role":"symbol","abstract":[{"type":"text","text":"The improvement in echo cancellation performance. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement","type":"reference"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"echo_return_loss_enhancement","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-totalsamplesduration":{"title":"totalSamplesDuration","type":"link","titleInlineContent":[{"text":"totalSamplesDuration","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-totalsamplesduration"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioSourceStats"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcestats","navigatorTitle":[{"text":"MCAudioSourceStats","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats","abstract":[{"type":"text","text":"Stastistics representing an audio track that is attached to one or more senders."}],"type":"topic","title":"MCAudioSourceStats","role":"symbol"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-echoreturnlossenhancement":{"title":"echoReturnLossEnhancement","type":"link","titleInlineContent":[{"text":"echoReturnLossEnhancement","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnlossenhancement"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-echoreturnloss":{"title":"echoReturnLoss","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss","type":"link","titleInlineContent":[{"text":"echoReturnLoss","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-echoreturnloss"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSourceStats/audio_level":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"audio_level","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/millicastsdk\/mcaudiosourcestats\/audio_level","navigatorTitle":[{"text":"audio_level","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/audio_level","abstract":[{"type":"text","text":"The current audio level. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel","isActive":true}],"type":"topic","title":"audio_level","role":"symbol"},"doc://MillicastSDK/s7CVarArgP":{"identifier":"doc:\/\/MillicastSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"https://w3c.github.io/webrtc-stats/#dom-rtcaudiosourcestats-audiolevel":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel","titleInlineContent":[{"text":"audioLevel","type":"text"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcaudiosourcestats-audiolevel","type":"link","title":"audioLevel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MCAudioSourceStats"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"MCAudioSourceStats","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCAudioSourceStats","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/audio_level","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/echo_return_loss_enhancement","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_audio_energy","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/total_samples_duration"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSourceStats\/get_type()"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCAudioSourceStats","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCMediaSourceStats","text":"MCMediaSourceStats","preciseIdentifier":"c:objc(cs)MCMediaSourceStats","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/title","op":"replace","value":"MCMediaSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments","value":[{"text":"MCMediaSourceStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss\/title","op":"replace","value":"echo_return_loss"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss\/fragments","value":[{"text":"echo_return_loss","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_samples_duration\/title","op":"replace","value":"total_samples_duration"},{"value":[{"text":"total_samples_duration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_samples_duration\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1get_type()\/title","value":"get_type","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1get_type()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"get_type"}]},{"value":"total_audio_energy","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_audio_energy\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1total_audio_energy\/fragments","value":[{"text":"total_audio_energy","kind":"identifier"}],"op":"replace"},{"value":"echo_return_loss_enhancement","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss_enhancement\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1echo_return_loss_enhancement\/fragments","value":[{"kind":"identifier","text":"echo_return_loss_enhancement"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/title","value":"MCAudioSourceStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats\/fragments","value":[{"kind":"identifier","text":"MCAudioSourceStats"}]},{"value":"audio_level","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1audio_level\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSourceStats~1audio_level\/fragments","value":[{"kind":"identifier","text":"audio_level"}],"op":"replace"}]}]}