{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder\/build()"],"title":"Instance Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplaybackbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudioplaybackbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"externalID":"c:objc(cs)MCAudioPlaybackBuilder","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"MCAudioPlaybackBuilder","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"class","title":"MCAudioPlaybackBuilder"},"abstract":[{"text":"Responsible for building AudioPlayback.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"title":"Conforms To"}],"references":{"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlaybackBuilder/build()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"() -> ","kind":"text"},{"text":"MCAudioPlayback","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAudioPlayback"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"build","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder\/build()","type":"topic","url":"\/documentation\/millicastsdk\/mcaudioplaybackbuilder\/build()","title":"build()","abstract":[{"type":"text","text":"Builds the AudioPlayback class."}]},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceBuilder"}],"title":"MCSourceBuilder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","url":"\/documentation\/millicastsdk\/mcsourcebuilder","type":"topic","abstract":[{"type":"text","text":"Responsible for building a source object."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlaybackBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"title":"MCAudioPlaybackBuilder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder","url":"\/documentation\/millicastsdk\/mcaudioplaybackbuilder","type":"topic","abstract":[{"type":"text","text":"Responsible for building AudioPlayback."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MCAudioPlaybackBuilder","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}]},{"value":[{"text":"MCAudioPlaybackBuilder","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlaybackBuilder\/build()"]}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioPlaybackBuilder","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCSourceBuilder","text":"MCSourceBuilder","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder~1build()\/title","value":"build"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder~1build()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}]},{"value":"MCSourceBuilder","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments","value":[{"kind":"identifier","text":"MCSourceBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/title","value":"MCAudioPlaybackBuilder"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlaybackBuilder\/fragments","value":[{"kind":"identifier","text":"MCAudioPlaybackBuilder"}],"op":"replace"}]}]}