{"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder\/build()"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"externalID":"c:objc(cs)MCCustomAudioSourceBuilder","navigatorTitle":[{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"class","title":"MCCustomAudioSourceBuilder"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Responsible for building MCCustomAudioSource."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mccustomaudiosourcebuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mccustomaudiosourcebuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceBuilder"}],"title":"MCSourceBuilder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCSourceBuilder"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","url":"\/documentation\/millicastsdk\/mcsourcebuilder","type":"topic","abstract":[{"type":"text","text":"Responsible for building a source object."}]},"doc://MillicastSDK/objc(pl)NSObject":{"identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSourceBuilder":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"title":"MCCustomAudioSourceBuilder","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder","url":"\/documentation\/millicastsdk\/mccustomaudiosourcebuilder","type":"topic","abstract":[{"type":"text","text":"Responsible for building MCCustomAudioSource."}]},"doc://MillicastSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSourceBuilder/build()":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mccustomaudiosourcebuilder\/build()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder\/build()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCustomAudioSource","text":"MCCustomAudioSource"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Builds the MCCustomAudioSource class."}],"navigatorTitle":[{"kind":"identifier","text":"build"}],"role":"symbol","type":"topic","title":"build()"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCCustomAudioSourceBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"MCCustomAudioSourceBuilder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MCCustomAudioSourceBuilder","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder\/build()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MCCustomAudioSourceBuilder","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceBuilder","text":"MCSourceBuilder","preciseIdentifier":"c:objc(cs)MCSourceBuilder","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/title","value":"MCSourceBuilder"},{"op":"replace","value":[{"text":"MCSourceBuilder","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceBuilder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/title","value":"MCCustomAudioSourceBuilder"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/fragments","value":[{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"op":"replace"},{"op":"replace","value":"build","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder~1build()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"text":"build","kind":"identifier"}]}]}]}