{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/audio_level","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealed_samples","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealment_events","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/decoder_implementation","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/estimated_playout_timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_discarded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fir_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_width","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_assembled_from_multiple_packets","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_decoded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_per_second","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/freeze_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/header_bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/inserted_samples_for_deceleration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_emitted_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_minimum_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_target_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/key_frames_decoded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/last_packet_received_timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/mid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/min_playout_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/nack_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pause_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pli_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/remote_id","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/removed_samples_for_acceleration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_packets_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/silent_concealed_samples","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_assembly_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_audio_energy","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_decode_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_freezes_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_inter_frame_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_pauses_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_processing_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_squared_inter_frame_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/track_identifier"],"title":"Instance Properties"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/get_type()"],"title":"Type Methods"}],"sections":[],"metadata":{"symbolKind":"class","title":"MCInboundRtpStreamStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"role":"symbol","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"externalID":"c:objc(cs)MCInboundRtpStreamStats","modules":[{"name":"MillicastSDK"}],"roleHeading":"Class"},"abstract":[{"type":"text","text":"Statistics for an inbound RTP stream."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcinboundrtpstreamstats"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/concealment_events":{"type":"topic","title":"concealment_events","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"concealment_events"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","abstract":[{"text":"The number of concealment events. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealmentevents","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"concealment_events","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/concealment_events","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealment_events"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/last_packet_received_timestamp":{"navigatorTitle":[{"text":"last_packet_received_timestamp","kind":"identifier"}],"abstract":[{"text":"The timestamp of the last received packet. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp","type":"reference","isActive":true}],"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/last_packet_received_timestamp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"last_packet_received_timestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"role":"symbol","title":"last_packet_received_timestamp","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/last_packet_received_timestamp"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/pli_count":{"type":"topic","title":"pli_count","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pli_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"role":"symbol","abstract":[{"type":"text","text":"The number of Picture Loss Indication (PLI) packets. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-plicount","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"pli_count"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/pli_count","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pli_count"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frame_height":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frame_height","kind":"symbol","role":"symbol","title":"frame_height","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_height","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frame_height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"abstract":[{"text":"The height of video frames. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-frameheight","type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"frame_height"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_emitted_count":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_emitted_count","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitter_buffer_emitted_count"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"jitter_buffer_emitted_count"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_emitted_count","abstract":[{"text":"The number of packets emitted from the jitter buffer. See ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount"}],"role":"symbol","type":"topic","title":"jitter_buffer_emitted_count"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/min_playout_delay":{"abstract":[{"text":"The minimum playout delay during video transmission.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"min_playout_delay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"min_playout_delay"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/min_playout_delay","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/min_playout_delay","kind":"symbol","title":"min_playout_delay","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCReceivedRtpStreamStats":{"abstract":[{"type":"text","text":"Statistical information about an incoming RTP (Real-time Transport Protocol) stream."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCReceivedRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCReceivedRtpStreamStats"}],"url":"\/documentation\/millicastsdk\/mcreceivedrtpstreamstats","type":"topic","kind":"symbol","title":"MCReceivedRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/decoder_implementation":{"type":"topic","title":"decoder_implementation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"decoder_implementation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The implementation details of the decoder. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation","isActive":true}],"navigatorTitle":[{"text":"decoder_implementation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/decoder_implementation","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/decoder_implementation"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalinterframedelay":{"title":"totalInterFrameDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalinterframedelay","type":"link","titleInlineContent":[{"type":"text","text":"totalInterFrameDelay"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalinterframedelay"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalprocessingdelay":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalprocessingdelay","titleInlineContent":[{"type":"text","text":"totalProcessingDelay"}],"title":"totalProcessingDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalprocessingdelay","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/audio_level":{"type":"topic","title":"audio_level","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio_level"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","abstract":[{"type":"text","text":"The audio level of the stream. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel","isActive":true}],"navigatorTitle":[{"text":"audio_level","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/audio_level","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/audio_level"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framespersecond":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framespersecond","titleInlineContent":[{"type":"text","text":"framesPerSecond"}],"title":"framesPerSecond","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framespersecond","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frames_assembled_from_multiple_packets":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_assembled_from_multiple_packets","type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_assembled_from_multiple_packets","title":"frames_assembled_from_multiple_packets","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frames_assembled_from_multiple_packets"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"abstract":[{"text":"The number of video frames assembled from multiple packets. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"frames_assembled_from_multiple_packets"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/bytes_received":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/bytes_received","title":"bytes_received","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/bytes_received","abstract":[{"text":"The number of bytes received. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-bytesreceived","isActive":true,"type":"reference"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes_received","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"bytes_received","kind":"identifier"}]},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-pausecount":{"title":"pauseCount","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","type":"link","titleInlineContent":[{"text":"pauseCount","type":"text"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-remoteid":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-remoteid","titleInlineContent":[{"type":"text","text":"remoteId"}],"title":"remoteId","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-remoteid","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_samples_duration":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_duration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"total_samples_duration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","navigatorTitle":[{"text":"total_samples_duration","kind":"identifier"}],"title":"total_samples_duration","abstract":[{"text":"The total duration of audio samples received. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","isActive":true,"type":"reference"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_samples_duration"},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalpausesduration":{"title":"totalPausesDuration","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","type":"link","titleInlineContent":[{"text":"totalPausesDuration","type":"text"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/removed_samples_for_acceleration":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/removed_samples_for_acceleration","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/removed_samples_for_acceleration","type":"topic","navigatorTitle":[{"text":"removed_samples_for_acceleration","kind":"identifier"}],"role":"symbol","title":"removed_samples_for_acceleration","kind":"symbol","abstract":[{"type":"text","text":"The number of removed audio samples for acceleration. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","type":"reference"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removed_samples_for_acceleration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_freezes_duration":{"type":"topic","title":"total_freezes_duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_freezes_duration"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","abstract":[{"text":"Total duration of rendered frames which are considered as frozen. See ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalfreezesduration","type":"reference","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"total_freezes_duration"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_freezes_duration","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_freezes_duration"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesdecoded":{"title":"framesDecoded","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdecoded","type":"link","titleInlineContent":[{"text":"framesDecoded","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdecoded"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesreceived","titleInlineContent":[{"type":"text","text":"framesReceived"}],"title":"framesReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesreceived","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/fec_packets_discarded":{"type":"topic","title":"fec_packets_discarded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fec_packets_discarded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","abstract":[{"type":"text","text":"The number of discarded Forward Error Correction (FEC) packets received during audio transmission. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsdiscarded","type":"reference","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"fec_packets_discarded"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/fec_packets_discarded","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_discarded"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-headerbytesreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","titleInlineContent":[{"text":"headerBytesReceived","type":"text"}],"title":"headerBytesReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","type":"link"},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-freezecount":{"title":"freezeCount","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-freezecount","type":"link","titleInlineContent":[{"type":"text","text":"freezeCount"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-freezecount"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-silentconcealedsamples":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples","titleInlineContent":[{"text":"silentConcealedSamples","type":"text"}],"title":"silentConcealedSamples","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalassemblytime":{"title":"totalAssemblyTime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalassemblytime","type":"link","titleInlineContent":[{"type":"text","text":"totalAssemblyTime"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalassemblytime"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-fecpacketsdiscarded":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsdiscarded","titleInlineContent":[{"text":"fecPacketsDiscarded","type":"text"}],"title":"fecPacketsDiscarded","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsdiscarded","type":"link"},"doc://MillicastSDK/SH":{"identifier":"doc:\/\/MillicastSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_samples_received":{"type":"topic","title":"total_samples_received","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"total_samples_received","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The total number of audio samples received. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived","type":"reference","isActive":true}],"navigatorTitle":[{"text":"total_samples_received","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_samples_received","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_received"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/silent_concealed_samples":{"type":"topic","title":"silent_concealed_samples","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"silent_concealed_samples","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","abstract":[{"text":"The number of silent concealed audio samples. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-silentconcealedsamples","type":"reference","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"silent_concealed_samples"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/silent_concealed_samples","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/silent_concealed_samples"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frame_width":{"abstract":[{"type":"text","text":"The width of video frames. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame_width"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"frame_width"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frame_width","title":"frame_width","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_width"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/estimated_playout_timestamp":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/estimated_playout_timestamp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"estimated_playout_timestamp"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"estimated_playout_timestamp","navigatorTitle":[{"text":"estimated_playout_timestamp","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The estimated playout timestamp. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-estimatedplayouttimestamp","isActive":true,"type":"reference"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/estimated_playout_timestamp"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/pause_count":{"type":"topic","title":"pause_count","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pause_count","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The total number of video pauses. See "},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-pausecount","type":"reference","isActive":true}],"navigatorTitle":[{"text":"pause_count","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/pause_count","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pause_count"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-insertedsamplesfordeceleration":{"title":"insertedSamplesForDeceleration","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-insertedsamplesfordeceleration","type":"link","titleInlineContent":[{"type":"text","text":"insertedSamplesForDeceleration"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-insertedsamplesfordeceleration"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_target_delay":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_target_delay","title":"jitter_buffer_target_delay","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jitter_buffer_target_delay"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","navigatorTitle":[{"text":"jitter_buffer_target_delay","kind":"identifier"}],"abstract":[{"text":"The target delay set for the jitter buffer. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbuffertargetdelay","isActive":true,"type":"reference"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_target_delay"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framewidth":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","titleInlineContent":[{"text":"frameWidth","type":"text"}],"title":"frameWidth","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framewidth","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/inserted_samples_for_deceleration":{"type":"topic","title":"inserted_samples_for_deceleration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"inserted_samples_for_deceleration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","abstract":[{"text":"The number of inserted audio samples for deceleration. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-insertedsamplesfordeceleration","type":"reference","isActive":true}],"navigatorTitle":[{"text":"inserted_samples_for_deceleration","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/inserted_samples_for_deceleration","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/inserted_samples_for_deceleration"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/track_identifier":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/track_identifier","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/track_identifier","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"track_identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"track_identifier","navigatorTitle":[{"text":"track_identifier","kind":"identifier"}],"abstract":[{"text":"The identifier associated with the track receiving the stream. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-trackidentifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_pauses_duration":{"type":"topic","title":"total_pauses_duration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"total_pauses_duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Total duration of pauses. See ","type":"text"},{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalpausesduration","type":"reference","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"total_pauses_duration"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_pauses_duration","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_pauses_duration"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/key_frames_decoded":{"type":"topic","title":"key_frames_decoded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"key_frames_decoded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"role":"symbol","abstract":[{"type":"text","text":"The number of decoded key frames. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-keyframesdecoded","type":"reference","isActive":true}],"navigatorTitle":[{"text":"key_frames_decoded","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/key_frames_decoded","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/key_frames_decoded"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-audiolevel":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel","titleInlineContent":[{"type":"text","text":"audioLevel"}],"title":"audioLevel","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-audiolevel","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/mid":{"type":"topic","title":"mid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The identifier of the media stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-mid","type":"reference","isActive":true}],"navigatorTitle":[{"text":"mid","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/mid","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/mid"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-trackidentifier":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-trackidentifier","titleInlineContent":[{"text":"trackIdentifier","type":"text"}],"title":"trackIdentifier","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-trackidentifier","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-estimatedplayouttimestamp":{"title":"estimatedPlayoutTimestamp","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-estimatedplayouttimestamp","type":"link","titleInlineContent":[{"text":"estimatedPlayoutTimestamp","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-estimatedplayouttimestamp"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_audio_energy":{"abstract":[{"type":"text","text":"The total energy of the audio stream. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","isActive":true,"type":"reference"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_audio_energy","type":"topic","role":"symbol","kind":"symbol","title":"total_audio_energy","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_audio_energy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"total_audio_energy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"total_audio_energy"}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totaldecodetime":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totaldecodetime","titleInlineContent":[{"text":"totalDecodeTime","type":"text"}],"title":"totalDecodeTime","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totaldecodetime","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/fec_packets_received":{"navigatorTitle":[{"kind":"identifier","text":"fec_packets_received"}],"title":"fec_packets_received","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/fec_packets_received","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_received","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fec_packets_received","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[{"text":"The number of Forward Error Correction (FEC) packets received during audio transmission. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsreceived","isActive":true}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_squared_inter_frame_delay":{"type":"topic","title":"total_squared_inter_frame_delay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_squared_inter_frame_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","abstract":[{"text":"The total squared inter-frame delay during video transmission. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay"}],"navigatorTitle":[{"text":"total_squared_inter_frame_delay","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_squared_inter_frame_delay","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_squared_inter_frame_delay"},"doc://MillicastSDK/SQ":{"identifier":"doc:\/\/MillicastSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/retransmitted_bytes_received":{"type":"topic","title":"retransmitted_bytes_received","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"retransmitted_bytes_received","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The total number of retransmitted bytes that were received for this SSRC, only including payload bytes. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedbytesreceived"}],"navigatorTitle":[{"text":"retransmitted_bytes_received","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/retransmitted_bytes_received","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_bytes_received"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/concealed_samples":{"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/concealed_samples","role":"symbol","abstract":[{"text":"The number of concealed audio samples. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealedsamples","type":"reference"}],"kind":"symbol","title":"concealed_samples","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"concealed_samples","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"concealed_samples","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealed_samples"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-plicount":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-plicount","titleInlineContent":[{"text":"pliCount","type":"text"}],"title":"pliCount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-plicount","type":"link"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalsamplesreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived","titleInlineContent":[{"type":"text","text":"totalSamplesReceived"}],"title":"totalSamplesReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsamplesreceived","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_minimum_delay":{"type":"topic","title":"jitter_buffer_minimum_delay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jitter_buffer_minimum_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","abstract":[{"type":"text","text":"The minimum delay configured for the jitter buffer. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1"}],"navigatorTitle":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_minimum_delay","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_minimum_delay"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","titleInlineContent":[{"text":"retransmittedpacketsreceived","type":"text"}],"title":"retransmittedpacketsreceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-frameheight":{"title":"frameHeight","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-frameheight","type":"link","titleInlineContent":[{"text":"frameHeight","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-frameheight"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-nackcount":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount","titleInlineContent":[{"text":"nackCount","type":"text"}],"title":"nackCount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount","type":"link"},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/remote_id":{"type":"topic","title":"remote_id","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"remote_id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"The identifier of the remote endpoint from which the stream originates. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-remoteid","type":"reference"}],"navigatorTitle":[{"text":"remote_id","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/remote_id","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/remote_id"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-bytesreceived":{"title":"bytesReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-bytesreceived","type":"link","titleInlineContent":[{"text":"bytesReceived","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-bytesreceived"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-concealmentevents":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealmentevents","titleInlineContent":[{"text":"concealmentEvents","type":"text"}],"title":"concealmentEvents","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealmentevents","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets":{"title":"framesAssembledFromMultiplePackets","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets","type":"link","titleInlineContent":[{"text":"framesAssembledFromMultiplePackets","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesassembledfrommultiplepackets"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount","titleInlineContent":[{"text":"jitterBufferEmittedCount","type":"text"}],"title":"jitterBufferEmittedCount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferemittedcount","type":"link"},"https://w3c.github.io/webrtc-stats/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1":{"title":"jitterBufferMinimumDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1","type":"link","titleInlineContent":[{"text":"jitterBufferMinimumDelay","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#ref-for-dom-rtcinboundrtpstreamstats-jitterbufferminimumdelay-1"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/retransmitted_packets_received":{"type":"topic","title":"retransmitted_packets_received","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retransmitted_packets_received","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"role":"symbol","abstract":[{"text":"The total number of retransmitted packets that were received for this SSRC. This is a subset of packetsReceived. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedpacketsreceived","type":"reference"}],"navigatorTitle":[{"kind":"identifier","text":"retransmitted_packets_received"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/retransmitted_packets_received","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_packets_received"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_processing_delay":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_processing_delay","abstract":[{"type":"text","text":"The total video processing delay. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalprocessingdelay","type":"reference","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"total_processing_delay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_processing_delay","kind":"symbol","navigatorTitle":[{"text":"total_processing_delay","kind":"identifier"}],"title":"total_processing_delay"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-mid":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-mid","titleInlineContent":[{"text":"mid","type":"text"}],"title":"mid","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-mid","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/get_type()":{"type":"topic","title":"get_type()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType"}],"role":"symbol","abstract":[{"text":"Returns the type of statistics.","type":"text"}],"navigatorTitle":[{"text":"get_type","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/get_type()","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/get_type()"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_assembly_time":{"navigatorTitle":[{"text":"total_assembly_time","kind":"identifier"}],"abstract":[{"text":"The total time spent on video frame assembly. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalassemblytime","type":"reference"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_assembly_time","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"total_assembly_time","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"total_assembly_time","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_assembly_time"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/jitter_buffer_delay":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_delay","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jitter_buffer_delay"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"jitter_buffer_delay","navigatorTitle":[{"text":"jitter_buffer_delay","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/jitter_buffer_delay","abstract":[{"text":"The current delay in the jitter buffer. See ","type":"text"},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferdelay","isActive":true}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/fir_count":{"type":"topic","title":"fir_count","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fir_count","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"role":"symbol","abstract":[{"type":"text","text":"The number of Full Intra Request (FIR) packets. See "},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fircount","type":"reference"}],"navigatorTitle":[{"text":"fir_count","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/fir_count","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fir_count"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-fecpacketsreceived":{"title":"fecPacketsReceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsreceived","type":"link","titleInlineContent":[{"text":"fecPacketsReceived","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fecpacketsreceived"},"https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalfreezesduration":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalfreezesduration","titleInlineContent":[{"text":"totalFreezesCount","type":"text"}],"title":"totalFreezesCount","url":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalfreezesduration","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frames_decoded":{"type":"topic","title":"frames_decoded","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"frames_decoded","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The number of decoded video frames. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesdecoded","isActive":true}],"navigatorTitle":[{"kind":"identifier","text":"frames_decoded"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_decoded","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_decoded"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_inter_frame_delay":{"type":"topic","title":"total_inter_frame_delay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_inter_frame_delay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The total inter-frame delay during video transmission. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalinterframedelay","type":"reference"}],"navigatorTitle":[{"text":"total_inter_frame_delay","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_inter_frame_delay","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_inter_frame_delay"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-concealedsamples":{"title":"concealedSamples","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealedsamples","type":"link","titleInlineContent":[{"text":"concealedSamples","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-concealedsamples"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbufferdelay":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferdelay","titleInlineContent":[{"text":"jitterBufferDelay","type":"text"}],"title":"jitterBufferDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbufferdelay","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp":{"title":"lastPacketReceivedTimestamp","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp","type":"link","titleInlineContent":[{"text":"lastPacketReceivedTimestamp","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-lastpacketreceivedtimestamp"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/nack_count":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/nack_count","type":"topic","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/nack_count","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nack_count","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"abstract":[{"text":"The number of Negative Acknowledgment (NACK) packets. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-nackcount","type":"reference","isActive":true}],"title":"nack_count","navigatorTitle":[{"kind":"identifier","text":"nack_count"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frames_per_second":{"navigatorTitle":[{"text":"frames_per_second","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The frame rate. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framespersecond"}],"title":"frames_per_second","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames_per_second","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_per_second","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_per_second"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-fircount":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fircount","titleInlineContent":[{"text":"firCount","type":"text"}],"title":"firCount","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-fircount","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/header_bytes_received":{"role":"symbol","navigatorTitle":[{"text":"header_bytes_received","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"header_bytes_received"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"title":"header_bytes_received","kind":"symbol","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/header_bytes_received","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/header_bytes_received","type":"topic","abstract":[{"text":"The number of header bytes received. See  ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-headerbytesreceived","type":"reference","isActive":true}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-keyframesdecoded":{"title":"keyFramesDecoded","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-keyframesdecoded","type":"link","titleInlineContent":[{"text":"keyFramesDecoded","type":"text"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-keyframesdecoded"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","titleInlineContent":[{"text":"removedSamplesForAcceleration","type":"text"}],"title":"removedSamplesForAcceleration","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-removedsamplesforacceleration","type":"link"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/freeze_count":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"freeze_count","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"freeze_count"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/freeze_count","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/freeze_count","type":"topic","title":"freeze_count","abstract":[{"text":"The total number of video freezes experienced by this receiver. See ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-freezecount"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/total_decode_time":{"type":"topic","title":"total_decode_time","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"total_decode_time","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","abstract":[{"text":"The total time spent on decoding. See ","type":"text"},{"isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totaldecodetime","type":"reference"}],"navigatorTitle":[{"text":"total_decode_time","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/total_decode_time","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_decode_time"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-retransmittedbytesreceived":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedbytesreceived","titleInlineContent":[{"text":"retransmittedbytesreceived","type":"text"}],"title":"retransmittedbytesreceived","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-retransmittedbytesreceived","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-decoderimplementation":{"title":"decoderImplementation","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation","type":"link","titleInlineContent":[{"type":"text","text":"decoderImplementation"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-decoderimplementation"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats/frames_received":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frames_received"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"frames_received","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"frames_received","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_received","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats\/frames_received","type":"topic","abstract":[{"type":"text","text":"The number of video frames received. See "},{"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-framesreceived","isActive":true}]},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-jitterbuffertargetdelay":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbuffertargetdelay","titleInlineContent":[{"text":"jitterBufferTargetDelay","type":"text"}],"title":"jitterBufferTargetDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-jitterbuffertargetdelay","type":"link"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalaudioenergy":{"title":"totalSamplesDuration","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy","type":"link","titleInlineContent":[{"type":"text","text":"totalSamplesDuration"}],"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalaudioenergy"},"doc://MillicastSDK/documentation/MillicastSDK/MCInboundRtpStreamStats":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCInboundRtpStreamStats"}],"type":"topic","navigatorTitle":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"abstract":[{"text":"Statistics for an inbound RTP stream.","type":"text"}],"title":"MCInboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcinboundrtpstreamstats"},"https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay":{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay","titleInlineContent":[{"text":"totalSquaredInterFrameDelay","type":"text"}],"title":"totalSquaredInterFrameDelay","url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcinboundrtpstreamstats-totalsquaredinterframedelay","type":"link"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCInboundRtpStreamStats"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}]},{"op":"replace","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/audio_level","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealed_samples","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/concealment_events","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/decoder_implementation","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/estimated_playout_timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_discarded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fec_packets_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/fir_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_height","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frame_width","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_assembled_from_multiple_packets","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_decoded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_per_second","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/frames_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/freeze_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/header_bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/inserted_samples_for_deceleration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_emitted_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_minimum_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/jitter_buffer_target_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/key_frames_decoded","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/last_packet_received_timestamp","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/mid","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/min_playout_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/nack_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pause_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/pli_count","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/remote_id","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/removed_samples_for_acceleration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_bytes_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/retransmitted_packets_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/silent_concealed_samples","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_assembly_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_audio_energy","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_decode_time","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_freezes_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_inter_frame_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_pauses_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_processing_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_duration","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_samples_received","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/total_squared_inter_frame_delay","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/track_identifier"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCInboundRtpStreamStats\/get_type()"]}]},{"value":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCInboundRtpStreamStats","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCReceivedRtpStreamStats","text":"MCReceivedRtpStreamStats","preciseIdentifier":"c:objc(cs)MCReceivedRtpStreamStats"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1concealment_events\/title","value":"concealment_events","op":"replace"},{"op":"replace","value":[{"text":"concealment_events","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1concealment_events\/fragments"},{"op":"replace","value":"last_packet_received_timestamp","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1last_packet_received_timestamp\/title"},{"value":[{"text":"last_packet_received_timestamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1last_packet_received_timestamp\/fragments"},{"op":"replace","value":"pli_count","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pli_count\/title"},{"value":[{"text":"pli_count","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pli_count\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_height\/title","value":"frame_height","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"frame_height"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_height\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_emitted_count\/title","value":"jitter_buffer_emitted_count"},{"value":[{"text":"jitter_buffer_emitted_count","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_emitted_count\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1min_playout_delay\/title","value":"min_playout_delay","op":"replace"},{"value":[{"kind":"identifier","text":"min_playout_delay"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1min_playout_delay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/title","value":"MCReceivedRtpStreamStats"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCReceivedRtpStreamStats\/fragments","op":"replace","value":[{"text":"MCReceivedRtpStreamStats","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1decoder_implementation\/title","op":"replace","value":"decoder_implementation"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1decoder_implementation\/fragments","op":"replace","value":[{"kind":"identifier","text":"decoder_implementation"}]},{"value":"audio_level","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1audio_level\/title","op":"replace"},{"value":[{"kind":"identifier","text":"audio_level"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1audio_level\/fragments","op":"replace"},{"op":"replace","value":"frames_assembled_from_multiple_packets","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_assembled_from_multiple_packets\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_assembled_from_multiple_packets\/fragments","value":[{"kind":"identifier","text":"frames_assembled_from_multiple_packets"}],"op":"replace"},{"value":"bytes_received","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1bytes_received\/title"},{"value":[{"text":"bytes_received","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1bytes_received\/fragments","op":"replace"},{"value":"total_samples_duration","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_duration\/title"},{"value":[{"kind":"identifier","text":"total_samples_duration"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_duration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1removed_samples_for_acceleration\/title","value":"removed_samples_for_acceleration"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1removed_samples_for_acceleration\/fragments","op":"replace","value":[{"text":"removed_samples_for_acceleration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_freezes_duration\/title","value":"total_freezes_duration"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_freezes_duration\/fragments","value":[{"kind":"identifier","text":"total_freezes_duration"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fec_packets_discarded\/title","op":"replace","value":"fec_packets_discarded"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fec_packets_discarded\/fragments","value":[{"kind":"identifier","text":"fec_packets_discarded"}]},{"value":"total_samples_received","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_received\/title"},{"value":[{"text":"total_samples_received","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_samples_received\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1silent_concealed_samples\/title","value":"silent_concealed_samples","op":"replace"},{"value":[{"text":"silent_concealed_samples","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1silent_concealed_samples\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_width\/title","value":"frame_width"},{"value":[{"kind":"identifier","text":"frame_width"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frame_width\/fragments"},{"value":"estimated_playout_timestamp","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1estimated_playout_timestamp\/title","op":"replace"},{"value":[{"text":"estimated_playout_timestamp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1estimated_playout_timestamp\/fragments"},{"value":"pause_count","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pause_count\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1pause_count\/fragments","op":"replace","value":[{"kind":"identifier","text":"pause_count"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_target_delay\/title","value":"jitter_buffer_target_delay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_target_delay\/fragments","value":[{"text":"jitter_buffer_target_delay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1inserted_samples_for_deceleration\/title","op":"replace","value":"inserted_samples_for_deceleration"},{"value":[{"text":"inserted_samples_for_deceleration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1inserted_samples_for_deceleration\/fragments"},{"op":"replace","value":"track_identifier","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1track_identifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1track_identifier\/fragments","value":[{"text":"track_identifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_pauses_duration\/title","op":"replace","value":"total_pauses_duration"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_pauses_duration\/fragments","op":"replace","value":[{"text":"total_pauses_duration","kind":"identifier"}]},{"value":"key_frames_decoded","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1key_frames_decoded\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1key_frames_decoded\/fragments","value":[{"kind":"identifier","text":"key_frames_decoded"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1mid\/title","value":"mid","op":"replace"},{"value":[{"text":"mid","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1mid\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_audio_energy\/title","value":"total_audio_energy"},{"value":[{"kind":"identifier","text":"total_audio_energy"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_audio_energy\/fragments"},{"value":"fec_packets_received","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fec_packets_received\/title","op":"replace"},{"value":[{"kind":"identifier","text":"fec_packets_received"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fec_packets_received\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_squared_inter_frame_delay\/title","op":"replace","value":"total_squared_inter_frame_delay"},{"op":"replace","value":[{"text":"total_squared_inter_frame_delay","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_squared_inter_frame_delay\/fragments"},{"value":"retransmitted_bytes_received","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_bytes_received\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_bytes_received\/fragments","value":[{"text":"retransmitted_bytes_received","kind":"identifier"}],"op":"replace"},{"value":"concealed_samples","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1concealed_samples\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1concealed_samples\/fragments","op":"replace","value":[{"text":"concealed_samples","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_minimum_delay\/title","value":"jitter_buffer_minimum_delay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_minimum_delay\/fragments","value":[{"text":"jitter_buffer_minimum_delay","kind":"identifier"}]},{"op":"replace","value":"remote_id","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1remote_id\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1remote_id\/fragments","op":"replace","value":[{"text":"remote_id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_packets_received\/title","value":"retransmitted_packets_received"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1retransmitted_packets_received\/fragments","value":[{"text":"retransmitted_packets_received","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"total_processing_delay","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_processing_delay\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_processing_delay\/fragments","value":[{"kind":"identifier","text":"total_processing_delay"}]},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1get_type()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"get_type","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1get_type()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_assembly_time\/title","value":"total_assembly_time","op":"replace"},{"value":[{"kind":"identifier","text":"total_assembly_time"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_assembly_time\/fragments"},{"value":"jitter_buffer_delay","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_delay\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1jitter_buffer_delay\/fragments","value":[{"text":"jitter_buffer_delay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fir_count\/title","op":"replace","value":"fir_count"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1fir_count\/fragments","value":[{"text":"fir_count","kind":"identifier"}]},{"value":"frames_decoded","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_decoded\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_decoded\/fragments","op":"replace","value":[{"kind":"identifier","text":"frames_decoded"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_inter_frame_delay\/title","value":"total_inter_frame_delay"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_inter_frame_delay\/fragments","value":[{"kind":"identifier","text":"total_inter_frame_delay"}]},{"op":"replace","value":"nack_count","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1nack_count\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1nack_count\/fragments","value":[{"text":"nack_count","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_per_second\/title","value":"frames_per_second"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_per_second\/fragments","value":[{"text":"frames_per_second","kind":"identifier"}]},{"op":"replace","value":"header_bytes_received","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1header_bytes_received\/title"},{"value":[{"kind":"identifier","text":"header_bytes_received"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1header_bytes_received\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1freeze_count\/title","value":"freeze_count"},{"op":"replace","value":[{"text":"freeze_count","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1freeze_count\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_decode_time\/title","value":"total_decode_time","op":"replace"},{"value":[{"kind":"identifier","text":"total_decode_time"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1total_decode_time\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_received\/title","value":"frames_received","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats~1frames_received\/fragments","value":[{"kind":"identifier","text":"frames_received"}],"op":"replace"},{"value":"MCInboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCInboundRtpStreamStats\/fragments","value":[{"text":"MCInboundRtpStreamStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}