{"topicSections":[{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/setName(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/create()"],"title":"Type Methods"}],"metadata":{"role":"symbol","externalID":"c:objc(cs)MCNdiRenderer","symbolKind":"class","title":"MCNdiRenderer","navigatorTitle":[{"text":"MCNdiRenderer","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCNdiRenderer","kind":"identifier"}],"roleHeading":"Class"},"kind":"symbol","abstract":[{"text":"The  class is responsible for rendering video as an NDI source. To render audio with NDI, use","type":"text"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","isActive":true},{"type":"text","text":" with the NDI output instead."}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCNdiRenderer","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcndirenderer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcndirenderer"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"references":{"doc://MillicastSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoTrack/add(_:)":{"abstract":[{"type":"text","text":"Adds a VideoRenderer to render this video track."},{"text":" ","type":"text"},{"text":"Several renderers can be added to the track.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each one will be called when a new frame becomes available."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideotrack\/add(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCVideoRenderer","text":"MCVideoRenderer","kind":"typeIdentifier"},{"kind":"text","text":")!)"}],"navigatorTitle":[{"text":"addRenderer:","kind":"identifier"}],"role":"symbol","title":"add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCAudioPlayback","kind":"identifier"}],"navigatorTitle":[{"text":"MCAudioPlayback","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","title":"MCAudioPlayback","url":"\/documentation\/millicastsdk\/mcaudioplayback","abstract":[{"type":"text","text":"Provides functionalities for managing audio playback."},{"text":" ","type":"text"},{"type":"text","text":"This class inherits the Source class, however this is not"},{"text":" ","type":"text"},{"type":"text","text":"a capture source."}]},"doc://MillicastSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCNdiRenderer/setName(_:)":{"kind":"symbol","url":"\/documentation\/millicastsdk\/mcndirenderer\/setname(_:)","role":"symbol","abstract":[{"type":"text","text":"Sets the name of the NDI source."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"title":"setName(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setName:"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/setName(_:)"},"doc://MillicastSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK/MCNdiRenderer":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCNdiRenderer"}],"navigatorTitle":[{"text":"MCNdiRenderer","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer","title":"MCNdiRenderer","url":"\/documentation\/millicastsdk\/mcndirenderer","abstract":[{"type":"text","text":"The  class is responsible for rendering video as an NDI source. To render audio with NDI, use"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback"},{"text":" with the NDI output instead.","type":"text"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCNdiRenderer/create()":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCNdiRenderer","preciseIdentifier":"c:objc(cs)MCNdiRenderer"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"create","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/create()","title":"create()","url":"\/documentation\/millicastsdk\/mcndirenderer\/create()","abstract":[{"type":"text","text":"Creates an NDI renderer."}]},"doc://MillicastSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MCNdiRenderer","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"MCNdiRenderer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"MCNdiRenderer","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/setName(_:)"]},{"identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCNdiRenderer\/create()"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCNdiRenderer","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"value":"MCVideoRenderer","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace"},{"value":"addRenderer:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addRenderer:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoTrack~1add(_:)\/fragments"},{"value":"MCAudioPlayback","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments","value":[{"kind":"identifier","text":"MCAudioPlayback"}],"op":"replace"},{"value":"setName:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1setName(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setName:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1setName(_:)\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer\/title","value":"MCNdiRenderer","op":"replace"},{"value":[{"text":"MCNdiRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer\/fragments"},{"value":"create","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1create()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCNdiRenderer~1create()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"create"}]}]}]}