{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/get_type()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcmediasourcestats\/get_type()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"get_type()","symbolKind":"method","modules":[{"name":"MillicastSDK"}],"role":"symbol","navigatorTitle":[{"text":"get_type","kind":"identifier"}],"externalID":"c:objc(cs)MCMediaSourceStats(cm)get_type","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStatsType","preciseIdentifier":"c:@E@MCStatsType","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats"]]},"abstract":[{"text":"Returns the type of statistics.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats\/get_type()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCMediaSourceStats":{"navigatorTitle":[{"text":"MCMediaSourceStats","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The MCMediaSourceStats class gathers statistics details.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCMediaSourceStats","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcmediasourcestats","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats","title":"MCMediaSourceStats"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","url":"\/documentation\/millicastsdk\/mcstatstype","title":"MCStatsType","abstract":[{"type":"text","text":"Different types of statistics."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCMediaSourceStats/get_type()":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"get_type"}],"url":"\/documentation\/millicastsdk\/mcmediasourcestats\/get_type()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get_type"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","text":"MCStatsType"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCMediaSourceStats\/get_type()","abstract":[{"type":"text","text":"Returns the type of statistics."}],"title":"get_type()","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"get_type","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"get_type","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"MCStatsType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCStatsType","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"},{"text":") ","kind":"text"},{"text":"get_type","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MCMediaSourceStats","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats\/title"},{"value":[{"text":"MCMediaSourceStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats\/fragments"},{"value":[{"text":"MCMediaSourceStats","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats\/navigatorTitle"},{"value":"MCStatsType","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title"},{"value":[{"kind":"identifier","text":"MCStatsType"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments"},{"value":[{"text":"MCStatsType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/navigatorTitle"},{"value":"get_type","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats~1get_type()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"get_type"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCMediaSourceStats~1get_type()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}