{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"initPlayback","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"initPlayback()","symbolKind":"method","externalID":"c:objc(cs)MCAudioPlayback(im)initPlayback","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initPlayback","kind":"identifier"},{"text":"()","kind":"text"}]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayback\/initplayback()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayback\/initplayback()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Initializes the playback device."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initPlayback"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/initPlayback()","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback/initPlayback()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initPlayback","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcaudioplayback\/initplayback()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initPlayback"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback\/initPlayback()","abstract":[{"text":"Initializes the playback device.","type":"text"}],"type":"topic","title":"initPlayback()"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayback":{"abstract":[{"text":"Provides functionalities for managing audio playback.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class inherits the Source class, however this is not"},{"type":"text","text":" "},{"type":"text","text":"a capture source."}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayback","kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayback","title":"MCAudioPlayback","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAudioPlayback"}],"navigatorTitle":[{"text":"MCAudioPlayback","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initPlayback","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initPlayback","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initPlayback"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1initPlayback()\/title","value":"initPlayback","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback~1initPlayback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initPlayback"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/title","value":"MCAudioPlayback","op":"replace"},{"value":[{"text":"MCAudioPlayback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayback\/fragments"}]}]}