{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Width of the WebRTC video frame."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/getwidth()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mciosvideorenderer\/getwidth()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getWidth()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get the width of the WebRTC video frame."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"getWidth()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCIosVideoRenderer(im)getWidth","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getWidth"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer":{"role":"symbol","title":"MCIosVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCIosVideoRenderer"}],"abstract":[{"type":"text","text":"Classs that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":"."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCIosVideoRenderer"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCIosVideoRenderer/getWidth()":{"role":"symbol","title":"getWidth()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"Get the width of the WebRTC video frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCIosVideoRenderer\/getWidth()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWidth"}],"url":"\/documentation\/millicastsdk\/mciosvideorenderer\/getwidth()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getWidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"identifier","text":"getWidth"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/title","value":"MCIosVideoRenderer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCIosVideoRenderer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getWidth()\/title","value":"getWidth"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCIosVideoRenderer~1getWidth()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getWidth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}