{"kind":"symbol","metadata":{"title":"get(_:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats","text":"MCStats"},{"kind":"text","text":"?"}],"externalID":"c:objc(cs)MCStatsReport(im)get:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"get:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/get(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Retrieves a specific MCStats object from the report based on its unique identifier.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"get","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"statsId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MCStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","preciseIdentifier":"c:objc(cs)MCStats","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"statsId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier. See "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/sid","type":"reference","isActive":true}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"a stats object of a specifc kind."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstatsreport\/get(_:)"]},{"paths":["\/documentation\/millicastsdk\/mcstatsreport\/get(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/get(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"get"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"MCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStats"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/get(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"get:"}],"title":"get(_:)","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/get(_:)","abstract":[{"text":"Retrieves a specific MCStats object from the report based on its unique identifier.","type":"text"}],"role":"symbol","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats/sid":{"abstract":[{"type":"text","text":"The unique identifier."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sid","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"sid","kind":"identifier"}],"title":"sid","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats\/sid","url":"\/documentation\/millicastsdk\/mcstats\/sid"},"https://w3c.github.io/webrtc-stats/#introduction":{"titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","title":"WebRTC standard","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"type":"topic","abstract":[{"text":"Interface is a container for various different statistics.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCStatsReport","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstatsreport","role":"symbol","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","title":"MCStatsReport"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCStats"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"url":"\/documentation\/millicastsdk\/mcstats","navigatorTitle":[{"text":"MCStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","title":"MCStats"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"get:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"get:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats"},{"text":" *) ","kind":"text"},{"text":"get:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"statsId"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"get:","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1get(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1get(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"get:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1sid\/title","value":"sid","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats~1sid\/fragments","value":[{"text":"sid","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","value":"MCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"text":"MCStatsReport","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","op":"replace","value":"MCStats"},{"op":"replace","value":[{"text":"MCStats","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}