{"abstract":[{"text":"Width in pixels","type":"text"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution(py)width","navigatorTitle":[{"text":"width","kind":"identifier"}],"modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"width","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/width"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution\/width"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution\/width"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution":{"title":"MCRTSRemoteVideoTrackLayerResolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}],"navigatorTitle":[{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution","abstract":[{"type":"text","text":"Represents resolution of a video frame."}],"role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution/width":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"width","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution\/width","kind":"symbol","navigatorTitle":[{"text":"width","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution\/width","abstract":[{"type":"text","text":"Width in pixels"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"width","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"width","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MCRTSRemoteVideoTrackLayerResolution","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}],"op":"replace"},{"value":"width","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1width\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution~1width\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"}]}]}