{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSCoding","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoViewType","doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/objc(pl)CALayerDelegate","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH","doc:\/\/MillicastSDK\/s8SendableP","doc:\/\/MillicastSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/MillicastSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/MillicastSDK\/objc(pl)UIAppearance","doc:\/\/MillicastSDK\/objc(pl)UIAppearanceContainer","doc:\/\/MillicastSDK\/objc(pl)UICoordinateSpace","doc:\/\/MillicastSDK\/objc(pl)UIDynamicItem","doc:\/\/MillicastSDK\/objc(pl)UIFocusEnvironment","doc:\/\/MillicastSDK\/objc(pl)UIFocusItem","doc:\/\/MillicastSDK\/objc(pl)UIFocusItemContainer","doc:\/\/MillicastSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/MillicastSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/MillicastSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/MillicastSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/MillicastSDK\/objc(pl)UITraitEnvironment","doc:\/\/MillicastSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"UIView that uses Metal as a backend for rendering."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"title":"MCAcceleratedVideoUIView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MillicastSDK@objc(cs)MCAcceleratedVideoUIView","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/init(frame:renderer:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/delegate","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/mirror","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/scalingMode","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/videoSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/layoutSubviews()"]},{"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations"],"generated":true}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoViewDelegate","preciseIdentifier":"s:12MillicastSDK19MCVideoViewDelegateP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A delegate for receiving view related events like video frame size changes"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/delegate"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIResponderStandardEditActions"},"doc://MillicastSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/layoutsubviews()"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/scalingMode":{"role":"symbol","title":"scalingMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scalingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCVideoViewScalingMode","preciseIdentifier":"s:12MillicastSDK22MCVideoViewScalingModeO"}],"abstract":[{"type":"text","text":"ScalingMode for video."},{"type":"text","text":" "},{"type":"text","text":"Use this to decide how the video is displayed within the bounds of the UIView."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/scalingMode","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/scalingmode"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/mirror":{"role":"symbol","title":"mirror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirror"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"If true the track is being displayed mirrored in the vertical axes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/mirror","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mirror"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAppearanceContainer"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/MillicastSDK\/objc(pl)UITraitEnvironment"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"},"doc://MillicastSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIDynamicItem"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoViewType":{"role":"symbol","title":"MCVideoViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoViewType"}],"abstract":[{"type":"text","text":"Common properties among the Views provided"},{"type":"text","text":" "},{"type":"text","text":"in the SDK."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoViewType"}],"url":"\/documentation\/millicastsdk\/mcvideoviewtype"},"doc://MillicastSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/MCAcceleratedVideoRendererDelegate-Implementations":{"role":"collectionGroup","title":"MCAcceleratedVideoRendererDelegate Implementations","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/mcacceleratedvideorendererdelegate-implementations"},"doc://MillicastSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/MillicastSDK\/objc(cs)UIView"},"doc://MillicastSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/MillicastSDK\/objc(pl)UICoordinateSpace"},"doc://MillicastSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusItemContainer"},"doc://MillicastSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSCoding"},"doc://MillicastSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusItem"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"role":"symbol","title":"MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"abstract":[{"type":"text","text":"UIView that uses Metal as a backend for rendering."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview"},"doc://MillicastSDK/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/MillicastSDK\/objc(pl)CALayerDelegate"},"doc://MillicastSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIUserActivityRestoring"},"doc://MillicastSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIFocusEnvironment"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAccessibilityIdentification"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/init(frame:renderer:)":{"role":"symbol","title":"init(frame:renderer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAcceleratedVideoRenderer","preciseIdentifier":"c:objc(cs)MCAcceleratedVideoRenderer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/init(frame:renderer:)","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/init(frame:renderer:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRendererDelegate":{"role":"symbol","title":"MCAcceleratedVideoRendererDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"abstract":[{"type":"text","text":"Protocol that allows subscribing to callbacks that inform about rendering video frame size changes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate"},"doc://MillicastSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/MillicastSDK\/objc(pl)UILargeContentViewerItem"},"doc://MillicastSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MillicastSDK\/s8SendableP"},"doc://MillicastSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoUIView/videoSize":{"role":"symbol","title":"videoSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The resolution of the video stream received from the track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/videoSize","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/videosize"},"doc://MillicastSDK/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/MillicastSDK\/objc(pl)UIAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCAcceleratedVideoUIView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/layoutSubviews()"]},{"title":"Default Implementations","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/MCAcceleratedVideoRendererDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title","value":"MCAcceleratedVideoUIView"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/title","value":"MCAcceleratedVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}