{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"More information about this in the"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/main\/docs\/native-code\/rtp-hdrext\/playout-delay\/README.md"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject","doc:\/\/MillicastSDK\/s7CVarArgP","doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP","doc:\/\/MillicastSDK\/s23CustomStringConvertibleP","doc:\/\/MillicastSDK\/SQ","doc:\/\/MillicastSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An option to tell the media server to"},{"type":"text","text":" "},{"type":"text","text":"send hints about the range of"},{"type":"text","text":" "},{"type":"text","text":"playout delays that the RTP receiver should"},{"type":"text","text":" "},{"type":"text","text":"follow, which effectively sets the delay"},{"type":"text","text":" "},{"type":"text","text":"for each frame before it is rendered."},{"type":"text","text":" "},{"type":"text","text":"Use this if you want to compensate"},{"type":"text","text":" "},{"type":"text","text":"for unpredictable network behaviour"},{"type":"text","text":" "},{"type":"text","text":"allowing for smooth playback at the cost"},{"type":"text","text":" "},{"type":"text","text":"of increasing latency."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"title":"MCForcePlayoutDelay","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)MCForcePlayoutDelay","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCForcePlayoutDelay"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/init(min:max:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/maximum","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/minimum"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/minimum":{"role":"symbol","title":"minimum","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The minimum delay that should be added to"},{"type":"text","text":" "},{"type":"text","text":"each frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/minimum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimum"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/minimum"},"doc://MillicastSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(cs)NSObject"},"doc://MillicastSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MillicastSDK\/s23CustomStringConvertibleP"},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/maximum":{"role":"symbol","title":"maximum","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The maximum delay that should be added to"},{"type":"text","text":" "},{"type":"text","text":"each frame."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/maximum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maximum"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/maximum"},"doc://MillicastSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MillicastSDK\/s28CustomDebugStringConvertibleP"},"doc://MillicastSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MillicastSDK\/SH"},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/init(min:max:)":{"role":"symbol","title":"init(min:max:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/init(min:max:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/init(min:max:)"},"https://webrtc.googlesource.com/src/+/main/docs/native-code/rtp-hdrext/playout-delay/README.md":{"title":"playout-delay rtp header extension","titleInlineContent":[{"type":"text","text":"playout-delay rtp header extension"}],"type":"link","identifier":"https:\/\/webrtc.googlesource.com\/src\/+\/main\/docs\/native-code\/rtp-hdrext\/playout-delay\/README.md","url":"https:\/\/webrtc.googlesource.com\/src\/+\/main\/docs\/native-code\/rtp-hdrext\/playout-delay\/README.md"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MillicastSDK\/SQ"},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay":{"role":"symbol","title":"MCForcePlayoutDelay","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"abstract":[{"type":"text","text":"An option to tell the media server to"},{"type":"text","text":" "},{"type":"text","text":"send hints about the range of"},{"type":"text","text":" "},{"type":"text","text":"playout delays that the RTP receiver should"},{"type":"text","text":" "},{"type":"text","text":"follow, which effectively sets the delay"},{"type":"text","text":" "},{"type":"text","text":"for each frame before it is rendered."},{"type":"text","text":" "},{"type":"text","text":"Use this if you want to compensate"},{"type":"text","text":" "},{"type":"text","text":"for unpredictable network behaviour"},{"type":"text","text":" "},{"type":"text","text":"allowing for smooth playback at the cost"},{"type":"text","text":" "},{"type":"text","text":"of increasing latency."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCForcePlayoutDelay"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MillicastSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MCForcePlayoutDelay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCForcePlayoutDelay"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCForcePlayoutDelay"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/maximum","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/minimum"]},{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/init(min:max:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1minimum\/title","value":"minimum"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1minimum\/fragments","value":[{"kind":"identifier","text":"minimum"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1maximum\/title","value":"maximum"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1maximum\/fragments","value":[{"kind":"identifier","text":"maximum"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1init(min:max:)\/title","value":"initWithMin:max:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1init(min:max:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/title","value":"MCForcePlayoutDelay"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/fragments","value":[{"kind":"identifier","text":"MCForcePlayoutDelay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}