{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"title":"MCWebrtcRemoteTrackDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)MCWebrtcRemoteTrackDelegate","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)"]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate":{"role":"symbol","title":"MCWebrtcRemoteTrackDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"abstract":[{"type":"text","text":"A delegate to receive remote track related events."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrack(_:didUpdateMID:)":{"role":"symbol","title":"webrtcRemoteTrack(_:didUpdateMID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrack"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The event for updating the MID of the internal webrtc track."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webrtcRemoteTrack:didUpdateMID:"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrack(_:didupdatemid:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteTrackDelegate/webrtcRemoteTrackDisabled(_:)":{"role":"symbol","title":"webrtcRemoteTrackDisabled(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCWebrtcRemoteTrack","preciseIdentifier":"c:objc(cs)MCWebrtcRemoteTrack"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The event for disabled state notification."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webrtcRemoteTrackDisabled:"}],"url":"\/documentation\/millicastsdk\/mcwebrtcremotetrackdelegate\/webrtcremotetrackdisabled(_:)"},"doc://MillicastSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/MillicastSDK\/objc(pl)NSObject"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"MCWebrtcRemoteTrackDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrack(_:didUpdateMID:)","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteTrackDelegate\/webrtcRemoteTrackDisabled(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/MillicastSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/title","value":"MCWebrtcRemoteTrackDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate\/fragments","value":[{"kind":"identifier","text":"MCWebrtcRemoteTrackDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/title","value":"webrtcRemoteTrack:didUpdateMID:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrack(_:didUpdateMID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webrtcRemoteTrack:didUpdateMID:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/title","value":"webrtcRemoteTrackDisabled:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteTrackDelegate~1webrtcRemoteTrackDisabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webrtcRemoteTrackDisabled:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}