{"abstract":[{"type":"text","text":"More information about the event."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"metadata":{"title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:objc(cs)MCStreamStoppedEvent(py)description","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent\/description-c.property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-c.property"]},{"paths":["\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamStoppedEvent/description-c.property":{"title":"description","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent\/description-c.property","role":"symbol","abstract":[{"type":"text","text":"More information about the event."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent\/description-c.property","type":"topic","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamStoppedEvent":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamStoppedEvent","navigatorTitle":[{"text":"MCStreamStoppedEvent","kind":"identifier"}],"type":"topic","abstract":[{"text":"Container for the stream stopped event. This happens","type":"text"},{"type":"text","text":" "},{"type":"text","text":"when the last publisher has stopped sending a stream"},{"text":" ","type":"text"},{"text":"and no more media is available","type":"text"}],"title":"MCStreamStoppedEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCStreamStoppedEvent","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcstreamstoppedevent","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent~1description-c.property\/title","value":"description","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent~1description-c.property\/fragments"},{"value":"MCStreamStoppedEvent","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamStoppedEvent\/fragments","value":[{"kind":"identifier","text":"MCStreamStoppedEvent"}]}]}]}