{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCapability"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cap"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCVideoCapabilities","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities","text":"MCVideoCapabilities"},{"kind":"text","text":"!)"}]}]},{"parameters":[{"name":"cap","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The video capability."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource"]]},"abstract":[{"type":"text","text":"Enable a specific video capability on the video source."}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/setCapability(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcvideosource\/setcapability(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcvideosource\/setcapability(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"setCapability:","kind":"identifier"}],"role":"symbol","title":"setCapability(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCapability","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCVideoCapabilities","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCVideoCapabilities"},{"text":"!)","kind":"text"}],"symbolKind":"method","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCVideoSource(im)setCapability:","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource/setCapability(_:)":{"title":"setCapability(_:)","abstract":[{"text":"Enable a specific video capability on the video source.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCapability","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCVideoCapabilities","text":"MCVideoCapabilities","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"setCapability:","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcvideosource\/setcapability(_:)","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource\/setCapability(_:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoSource":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoSource"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoSource"}],"url":"\/documentation\/millicastsdk\/mcvideosource","role":"symbol","type":"topic","title":"MCVideoSource","abstract":[{"type":"text","text":"Responsible for managing video sources."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoSource","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoCapabilities":{"navigatorTitle":[{"kind":"identifier","text":"MCVideoCapabilities"}],"title":"MCVideoCapabilities","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoCapabilities"}],"abstract":[{"type":"text","text":"This VideoCapabilities class represents the video capabilities of a video track."}],"url":"\/documentation\/millicastsdk\/mcvideocapabilities"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setCapability:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setCapability:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCapability:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoCapabilities","text":"MCVideoCapabilities","preciseIdentifier":"c:objc(cs)MCVideoCapabilities"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cap"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"setCapability:","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1setCapability(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCapability:"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource~1setCapability(_:)\/fragments","op":"replace"},{"value":"MCVideoSource","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/title","op":"replace"},{"value":[{"text":"MCVideoSource","kind":"identifier"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoSource\/fragments","op":"replace"},{"value":"MCVideoCapabilities","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCVideoCapabilities"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoCapabilities\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}