{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asViewDetails()","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:objc(cs)MCStreamDetails(im)asViewDetails","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asViewDetails","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCStreamViewDetails","preciseIdentifier":"c:objc(cs)MCStreamViewDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"asViewDetails()","navigatorTitle":[{"text":"asViewDetails","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcstreamdetails\/asviewdetails()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstreamdetails\/asviewdetails()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asViewDetails","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)MCStreamViewDetails","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails","text":"MCStreamViewDetails"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails/asViewDetails()":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcstreamdetails\/asviewdetails()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asViewDetails","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCStreamViewDetails","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCStreamViewDetails"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails\/asViewDetails()","title":"asViewDetails()","navigatorTitle":[{"kind":"identifier","text":"asViewDetails"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamViewDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStreamViewDetails"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCStreamViewDetails"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails","url":"\/documentation\/millicastsdk\/mcstreamviewdetails","title":"MCStreamViewDetails","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCStreamDetails":{"abstract":[{"type":"text","text":"A type erased stream details class. A holder"},{"type":"text","text":" "},{"text":"For either Stream Publish Details or Stream View Details.","type":"text"},{"type":"text","text":" "},{"text":"This class contains the current streaming","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"session identifying information. Used to correlate"},{"type":"text","text":" "},{"type":"text","text":"debugging info with a particular streaming session."}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcstreamdetails","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCStreamDetails","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamDetails","title":"MCStreamDetails","navigatorTitle":[{"kind":"identifier","text":"MCStreamDetails"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"asViewDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asViewDetails"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStreamViewDetails","text":"MCStreamViewDetails","preciseIdentifier":"c:objc(cs)MCStreamViewDetails"},{"kind":"text","text":" *) "},{"text":"asViewDetails","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"asViewDetails","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asViewDetails()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails~1asViewDetails()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asViewDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails\/title","value":"MCStreamViewDetails"},{"value":[{"text":"MCStreamViewDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamViewDetails\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/title","value":"MCStreamDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStreamDetails\/fragments","value":[{"kind":"identifier","text":"MCStreamDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}