{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/init(frame:renderer:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideouiview\/init(frame:renderer:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCAcceleratedVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCAcceleratedVideoRenderer"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","externalID":"s:12MillicastSDK24MCAcceleratedVideoUIViewC5frame8rendererACSo6CGRectV_So0cD8RendererCtcfc","title":"init(frame:renderer:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCAcceleratedVideoRenderer","kind":"typeIdentifier","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","preciseIdentifier":"c:objc(cs)MCAcceleratedVideoRenderer"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"frame","content":[{"inlineContent":[{"text":"A rectangle representing the frame.","type":"text"}],"type":"paragraph"}]},{"name":"renderer","content":[{"inlineContent":[{"text":"The accelerated video renderer. This renderer would have to be attached to","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","type":"reference"},{"text":" or ","type":"text"},{"isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","type":"reference"},{"text":" ","type":"text"},{"text":"to receive the track content.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","kind":"symbol","role":"symbol","title":"MCRTSRemoteVideoTrack","type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","abstract":[{"type":"text","text":"The RTS logical track’s video interface."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView":{"kind":"symbol","abstract":[{"text":"UIView that uses Metal as a backend for rendering.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoUIView"}],"title":"MCAcceleratedVideoUIView","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoUIView"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"role":"symbol","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer","title":"MCAcceleratedVideoRenderer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" or "},{"type":"codeVoice","code":"NSView"},{"type":"text","text":"."}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoUIView/init(frame:renderer:)":{"title":"init(frame:renderer:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Initializes the view with the given frame."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"renderer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCAcceleratedVideoRenderer","text":"MCAcceleratedVideoRenderer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideouiview\/init(frame:renderer:)","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoUIView\/init(frame:renderer:)"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoTrack":{"kind":"symbol","abstract":[{"type":"text","text":"Responsible for managing video capture session from a video source."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack","url":"\/documentation\/millicastsdk\/mcvideotrack","type":"topic","role":"symbol","title":"MCVideoTrack","navigatorTitle":[{"text":"MCVideoTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoTrack","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"type":"topic","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","kind":"symbol","role":"symbol","title":"MCWebrtcRemoteVideoTrack","abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MCRTSRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title"},{"value":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments"},{"value":"MCAcceleratedVideoUIView","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/title"},{"value":[{"text":"MCAcceleratedVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoUIView\/fragments"},{"value":"MCAcceleratedVideoRenderer","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title"},{"value":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments"},{"value":"MCVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/title"},{"value":[{"text":"MCVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoTrack\/fragments"},{"value":"MCWebrtcRemoteVideoTrack","op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title"},{"value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments"}]}]}