{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger\/getWebrtcVersion()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getWebrtcVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The WebRTC version.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mclogger\/getwebrtcversion()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mclogger\/getwebrtcversion()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger"]]},"abstract":[{"text":"Get the current WebRTC version used.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getWebrtcVersion","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getWebrtcVersion"}],"title":"getWebrtcVersion()","role":"symbol","roleHeading":"Type Method","externalID":"c:objc(cs)MCLogger(cm)getWebrtcVersion","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLogger":{"title":"MCLogger","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger","url":"\/documentation\/millicastsdk\/mclogger","abstract":[{"text":"Class that is responsible for managing SDK logs.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCLogger","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLogger"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogger/getWebrtcVersion()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger\/getWebrtcVersion()","abstract":[{"text":"Get the current WebRTC version used.","type":"text"}],"title":"getWebrtcVersion()","url":"\/documentation\/millicastsdk\/mclogger\/getwebrtcversion()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getWebrtcVersion"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getWebrtcVersion"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"getWebrtcVersion","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getWebrtcVersion","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getWebrtcVersion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"MCLogger","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/fragments","op":"replace","value":[{"text":"MCLogger","kind":"identifier"}]},{"value":"getWebrtcVersion","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger~1getWebrtcVersion()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getWebrtcVersion"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger~1getWebrtcVersion()\/fragments","op":"replace"}]}]}