{"relationshipsSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","doc:\/\/io.cosmosoftware.millicast.sdk\/SH","doc:\/\/io.cosmosoftware.millicast.sdk\/SY","doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK"]]},"metadata":{"title":"MCGenericError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@E@MCGenericError","role":"symbol"},"abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/exceptionThrown","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSON","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSONSchema","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidOptions","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidState","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/noCredentials","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/nullListener","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionAddTracksFailed","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreateOffer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionLocalDesc","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionNotEstablished","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionRemoteDesc","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/restAPIError","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/transactionError","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/websocketHasFailed"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code"]}],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/websocketHasFailed":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketHasFailed","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/websocketHasFailed","abstract":[{"type":"text","text":"Websocket not connected."}],"navigatorTitle":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}],"title":"MCGenericError.Code.websocketHasFailed","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/websockethasfailed","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code","kind":"symbol","abstract":[{"text":"Generic errors returned by the SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code","title":"MCGenericError.Code"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionCreateOffer":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreateOffer"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}],"kind":"symbol","type":"topic","abstract":[{"text":"Can not create PeerConnection offer.","type":"text"}],"title":"MCGenericError.Code.peerConnectionCreateOffer","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreateOffer","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreateoffer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/exceptionThrown":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/exceptionthrown","abstract":[{"type":"text","text":"Exception was thrown and not handled."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorExceptionThrown"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionThrown"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/exceptionThrown","title":"MCGenericError.Code.exceptionThrown"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidState":{"abstract":[{"type":"text","text":"Invalid state of the client."}],"title":"MCGenericError.Code.invalidState","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidstate","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidState","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidState","navigatorTitle":[{"text":"MCGenericErrorInvalidState","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidJSONSchema":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Signaling provided JSON with missing or incorrect data."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSONSchema","title":"MCGenericError.Code.invalidJSONSchema","navigatorTitle":[{"text":"MCGenericErrorInvalidJSONSchema","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidJSONSchema","kind":"identifier"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidjsonschema"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidOptions":{"title":"MCGenericError.Code.invalidOptions","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidOptions","role":"symbol","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidoptions","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Invalid options set for the request."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MCGenericErrorInvalidOptions","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionCreate":{"kind":"symbol","title":"MCGenericError.Code.peerConnectionCreate","role":"symbol","abstract":[{"text":"Can not create PeerConnection.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreate","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreate"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionCreate"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectioncreate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionNotEstablished":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionnotestablished","abstract":[{"type":"text","text":"PeerConnection was not established."}],"title":"MCGenericError.Code.peerConnectionNotEstablished","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionNotEstablished"}],"navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionNotEstablished"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionNotEstablished"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/invalidJSON":{"kind":"symbol","title":"MCGenericError.Code.invalidJSON","abstract":[{"text":"Signaling provided invalid JSON.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidJSON"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/invalidjson","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSON","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorInvalidJSON"}],"type":"topic"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/Equatable-Implementations":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/Equatable-Implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/equatable-implementations","title":"Equatable Implementations"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/nullListener":{"kind":"symbol","abstract":[{"type":"text","text":"Listener not set while it should be."}],"title":"MCGenericError.Code.nullListener","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCGenericErrorNullListener","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/nulllistener","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/nullListener","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nullListener","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionLocalDesc":{"kind":"symbol","abstract":[{"text":"Can not set PeerConnection local description.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionLocalDesc","kind":"identifier"}],"navigatorTitle":[{"text":"MCGenericErrorPeerConnectionLocalDesc","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionlocaldesc","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionLocalDesc","role":"symbol","type":"topic","title":"MCGenericError.Code.peerConnectionLocalDesc"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/transactionError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionError"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/transactionError","type":"topic","title":"MCGenericError.Code.transactionError","role":"symbol","abstract":[{"type":"text","text":"Signaling returned error for the request."}],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/transactionerror","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCGenericErrorTransactionError"}]},"doc://io.cosmosoftware.millicast.sdk/SY":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionRemoteDesc":{"navigatorTitle":[{"text":"MCGenericErrorPeerConnectionRemoteDesc","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionRemoteDesc","kind":"identifier"}],"title":"MCGenericError.Code.peerConnectionRemoteDesc","type":"topic","abstract":[{"type":"text","text":"Can not set PeerConnection remote description."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionRemoteDesc","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionremotedesc","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/noCredentials":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/nocredentials","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noCredentials","kind":"identifier"}],"navigatorTitle":[{"text":"MCGenericErrorNoCredentials","kind":"identifier"}],"title":"MCGenericError.Code.noCredentials","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/noCredentials","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"No credentials are set.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SH"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/init(rawValue:)":{"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/init(rawValue:)","role":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/restAPIError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restAPIError","kind":"identifier"}],"abstract":[{"text":"Director REST API returned an error.","type":"text"}],"navigatorTitle":[{"text":"MCGenericErrorRestAPIError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/restAPIError","type":"topic","title":"MCGenericError.Code.restAPIError","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/restapierror","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/RawRepresentable-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/rawrepresentable-implementations","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://io.cosmosoftware.millicast.sdk/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/s8SendableP","title":"Swift.Sendable"},"doc://io.cosmosoftware.millicast.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/SQ","title":"Swift.Equatable"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCGenericError-swift.struct/Code/peerConnectionAddTracksFailed":{"kind":"symbol","abstract":[{"type":"text","text":"Can not add tracks to the peer connection."}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionAddTracksFailed","url":"\/documentation\/millicastsdk\/mcgenericerror-swift.struct\/code\/peerconnectionaddtracksfailed","navigatorTitle":[{"text":"MCGenericErrorPeerConnectionAddTracksFailed","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"peerConnectionAddTracksFailed","kind":"identifier"}],"type":"topic","role":"symbol","title":"MCGenericError.Code.peerConnectionAddTracksFailed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MCGenericError","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MCGenericError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MCGenericError","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/exceptionThrown","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSON","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidJSONSchema","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidOptions","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/invalidState","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/noCredentials","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/nullListener","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionAddTracksFailed","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreate","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionCreateOffer","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionLocalDesc","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionNotEstablished","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/peerConnectionRemoteDesc","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/restAPIError","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/transactionError","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCGenericError-swift.struct\/Code\/websocketHasFailed"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCGenericError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1websocketHasFailed\/title","op":"replace","value":"MCGenericErrorWebsocketHasFailed"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1websocketHasFailed\/fragments","op":"replace","value":[{"text":"MCGenericErrorWebsocketHasFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/title","op":"replace","value":"MCGenericError"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MCGenericError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreateOffer\/title","op":"replace","value":"MCGenericErrorPeerConnectionCreateOffer"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreateOffer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreateOffer"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1exceptionThrown\/title","op":"replace","value":"MCGenericErrorExceptionThrown"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1exceptionThrown\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorExceptionThrown"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidState\/title","op":"replace","value":"MCGenericErrorInvalidState"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidState\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorInvalidState"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidJSONSchema\/title","op":"replace","value":"MCGenericErrorInvalidJSONSchema"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidJSONSchema\/fragments","op":"replace","value":[{"text":"MCGenericErrorInvalidJSONSchema","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidOptions\/title","op":"replace","value":"MCGenericErrorInvalidOptions"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorInvalidOptions"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreate\/title","op":"replace","value":"MCGenericErrorPeerConnectionCreate"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionCreate\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionCreate"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionNotEstablished\/title","op":"replace","value":"MCGenericErrorPeerConnectionNotEstablished"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionNotEstablished\/fragments","op":"replace","value":[{"text":"MCGenericErrorPeerConnectionNotEstablished","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidJSON\/title","op":"replace","value":"MCGenericErrorInvalidJSON"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1invalidJSON\/fragments","op":"replace","value":[{"text":"MCGenericErrorInvalidJSON","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1nullListener\/title","op":"replace","value":"MCGenericErrorNullListener"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1nullListener\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorNullListener"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionLocalDesc\/title","op":"replace","value":"MCGenericErrorPeerConnectionLocalDesc"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionLocalDesc\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorPeerConnectionLocalDesc"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1transactionError\/title","op":"replace","value":"MCGenericErrorTransactionError"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1transactionError\/fragments","op":"replace","value":[{"text":"MCGenericErrorTransactionError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionRemoteDesc\/title","op":"replace","value":"MCGenericErrorPeerConnectionRemoteDesc"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionRemoteDesc\/fragments","op":"replace","value":[{"text":"MCGenericErrorPeerConnectionRemoteDesc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1noCredentials\/title","op":"replace","value":"MCGenericErrorNoCredentials"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1noCredentials\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorNoCredentials"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1restAPIError\/title","op":"replace","value":"MCGenericErrorRestAPIError"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1restAPIError\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCGenericErrorRestAPIError"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionAddTracksFailed\/title","op":"replace","value":"MCGenericErrorPeerConnectionAddTracksFailed"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCGenericError-swift.struct~1Code~1peerConnectionAddTracksFailed\/fragments","op":"replace","value":[{"text":"MCGenericErrorPeerConnectionAddTracksFailed","kind":"identifier"}]}]}]}