{"metadata":{"symbolKind":"method","extendedModule":"MillicastSDK","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"didChangeSize:"}],"title":"didChange(_:)","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@CM@MillicastSDK@objc(cs)MCSampleBufferVideoUIView(im)didChangeSize:"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChange"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}]}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"MCCMSampleBufferVideoRendererDelegate.didChange(_:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didchange(_:)"]},{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didChange(_:)","interfaceLanguage":"swift"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/MCCMSampleBufferVideoRendererDelegate-Implementations":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/MCCMSampleBufferVideoRendererDelegate-Implementations","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/mccmsamplebuffervideorendererdelegate-implementations","type":"topic","title":"MCCMSampleBufferVideoRendererDelegate Implementations","abstract":[],"role":"collectionGroup","kind":"article"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","title":"MCSampleBufferVideoUIView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/didChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChange"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/didchange(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/didChange(_:)","role":"symbol","navigatorTitle":[{"text":"didChangeSize:","kind":"identifier"}],"title":"didChange(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"didChangeSize:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didChangeSize:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"didChangeSize:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"MCSampleBufferVideoUIView","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","op":"replace"},{"value":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"},{"value":"didChangeSize:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didChange(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView~1didChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didChangeSize:","kind":"identifier"}],"op":"replace"}]}]}