{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/updateRenderer(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateRenderer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"renderer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","kind":"typeIdentifier","text":"MCCMSampleBufferVideoRenderer"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/updaterenderer(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"updateRenderer(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateRenderer"},{"kind":"text","text":"("},{"text":"MCCMSampleBufferVideoRenderer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","externalID":"s:12MillicastSDK25MCSampleBufferVideoUIViewC14updateRendereryySo010MCCMSampledeH0CF"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView":{"abstract":[{"text":"UIView that uses AVSampleBufferDisplayLayer as a backend for rendering.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview","title":"MCSampleBufferVideoUIView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"navigatorTitle":[{"text":"MCSampleBufferVideoUIView","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"url":"\/documentation\/millicastsdk\/mcvideoframe","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCVideoFrame"}],"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"type":"text","text":" "},{"text":"with ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true},{"type":"text","text":" for playback."}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","title":"MCVideoFrame"},"doc://MillicastSDK/documentation/MillicastSDK/MCSampleBufferVideoUIView/updateRenderer(_:)":{"title":"updateRenderer(_:)","url":"\/documentation\/millicastsdk\/mcsamplebuffervideouiview\/updaterenderer(_:)","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSampleBufferVideoUIView\/updateRenderer(_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateRenderer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCMSampleBufferVideoRenderer","text":"MCCMSampleBufferVideoRenderer"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferVideoRenderer":{"url":"\/documentation\/millicastsdk\/mccmsamplebuffervideorenderer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}],"abstract":[{"text":"This class is responsible for converting ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","isActive":true},{"type":"text","text":"  into renderable "},{"code":"CMSampleBufferRef","type":"codeVoice"},{"type":"text","text":" frames."}],"navigatorTitle":[{"text":"MCCMSampleBufferVideoRenderer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferVideoRenderer","title":"MCCMSampleBufferVideoRenderer","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/title","value":"MCSampleBufferVideoUIView"},{"value":[{"kind":"identifier","text":"MCSampleBufferVideoUIView"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSampleBufferVideoUIView\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","op":"replace","value":[{"text":"MCVideoFrame","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/title","value":"MCCMSampleBufferVideoRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCCMSampleBufferVideoRenderer"}]}]}]}