{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintain_framerate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcdegradationpreferences\/maintain_framerate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/MAINTAIN_FRAMERATE","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"On over-use, requests lower resolution, possibly causing down-scaling."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}],"title":"MCDegradationPreferences.MAINTAIN_FRAMERATE","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@MCDegradationPreferences@MAINTAIN_FRAMERATE","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences":{"role":"symbol","title":"MCDegradationPreferences","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCDegradationPreferences"}],"abstract":[{"type":"text","text":"The DegradationPreferences enum. Based on "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCDegradationPreferences"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences"},"https://w3c.github.io/webrtc-pc/#idl-def-rtcdegradationpreference.":{"title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference.","url":"https:\/\/w3c.github.io\/webrtc-pc\/#idl-def-rtcdegradationpreference."},"doc://MillicastSDK/documentation/MillicastSDK/MCDegradationPreferences/MAINTAIN_FRAMERATE":{"role":"symbol","title":"MCDegradationPreferences.MAINTAIN_FRAMERATE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}],"abstract":[{"type":"text","text":"On over-use, requests lower resolution, possibly causing down-scaling."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCDegradationPreferences\/MAINTAIN_FRAMERATE","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}],"url":"\/documentation\/millicastsdk\/mcdegradationpreferences\/maintain_framerate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MAINTAIN_FRAMERATE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/title","value":"MCDegradationPreferences"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences\/fragments","value":[{"kind":"identifier","text":"MCDegradationPreferences"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1MAINTAIN_FRAMERATE\/title","value":"MAINTAIN_FRAMERATE"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCDegradationPreferences~1MAINTAIN_FRAMERATE\/fragments","value":[{"kind":"identifier","text":"MAINTAIN_FRAMERATE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}