{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer","text":"MCRTSRemoteTrackLayer"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayers\/active"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayers\/active"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/active","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Currently active layers in the event"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCRTSRemoteTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer"},{"kind":"text","text":"]"}],"title":"active","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCRTSRemoteTrackLayers(py)active","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"active"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers/active":{"role":"symbol","title":"active","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MCRTSRemoteTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteTrackLayer"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Currently active layers in the event"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers\/active","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"active"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers\/active"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"role":"symbol","title":"MCRTSRemoteTrackLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayers":{"role":"symbol","title":"MCRTSRemoteTrackLayers","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"abstract":[{"type":"text","text":"The layers update event. Note that if the RtsTrack is projected"},{"type":"text","text":" "},{"type":"text","text":"onto multiple RtcTracks, the backend sends layers per RtcTrack,"},{"type":"text","text":" "},{"type":"text","text":"so the RTS track will get multiple layer events."},{"type":"text","text":" "},{"type":"text","text":"No debouncing\/deduplication is implemented."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"active"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"active"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<MCRTSRemoteTrackLayer *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"active"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1active\/title","value":"active"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers~1active\/fragments","value":[{"kind":"identifier","text":"active"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title","value":"MCRTSRemoteTrackLayer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayer"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/title","value":"MCRTSRemoteTrackLayers"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayers\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteTrackLayers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}