{"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_incoming_bitrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_incoming_bitrate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:objc(cs)MCIceCandidatePairStats(py)available_incoming_bitrate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"available_incoming_bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"available_incoming_bitrate","kind":"identifier"}],"role":"symbol","title":"available_incoming_bitrate"},"abstract":[{"text":"It is calculated by the underlying congestion control by combining the available bitrate for all the incoming RTP streams using this candidate pair. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate","type":"reference","isActive":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"available_incoming_bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_incoming_bitrate"},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCIceCandidatePairStats":{"title":"MCIceCandidatePairStats","abstract":[{"text":"Stastistics representing an ice candidate pair.","type":"text"}],"role":"symbol","url":"\/documentation\/millicastsdk\/mcicecandidatepairstats","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCIceCandidatePairStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats","kind":"symbol","navigatorTitle":[{"text":"MCIceCandidatePairStats","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCIceCandidatePairStats/available_incoming_bitrate":{"abstract":[{"type":"text","text":"It is calculated by the underlying congestion control by combining the available bitrate for all the incoming RTP streams using this candidate pair. See "},{"isActive":true,"type":"reference","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"available_incoming_bitrate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/millicastsdk\/mcicecandidatepairstats\/available_incoming_bitrate","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCIceCandidatePairStats\/available_incoming_bitrate","navigatorTitle":[{"kind":"identifier","text":"available_incoming_bitrate"}],"title":"available_incoming_bitrate"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","role":"collection"},"https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-availableincomingbitrate":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate","titleInlineContent":[{"text":"availableincomingbitrate","type":"text"}],"type":"link","title":"availableincomingbitrate","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcicecandidatepairstats-availableincomingbitrate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"available_incoming_bitrate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"available_incoming_bitrate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"available_incoming_bitrate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/title","value":"MCIceCandidatePairStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/fragments","value":[{"kind":"identifier","text":"MCIceCandidatePairStats"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats\/navigatorTitle","value":[{"text":"MCIceCandidatePairStats","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_incoming_bitrate\/title","value":"available_incoming_bitrate"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCIceCandidatePairStats~1available_incoming_bitrate\/fragments","value":[{"kind":"identifier","text":"available_incoming_bitrate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}