{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/media_source_id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/media_source_id"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"abstract":[{"type":"text","text":"The identifier of the media source associated with the outbound RTP stream."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)media_source_id","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"title":"media_source_id","navigatorTitle":[{"text":"media_source_id","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"media_source_id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/media_source_id"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"media_source_id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics related to an outgoing remote RTP stream."}],"navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","title":"MCRemoteOutboundRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/media_source_id":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"media_source_id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"media_source_id","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/media_source_id","title":"media_source_id","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/media_source_id","abstract":[{"text":"The identifier of the media source associated with the outbound RTP stream.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"media_source_id","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"media_source_id"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"media_source_id","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title","value":"MCRemoteOutboundRtpStreamStats","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments","value":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1media_source_id\/title","value":"media_source_id"},{"value":[{"text":"media_source_id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1media_source_id\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}