{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remote_id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_id"]},{"paths":["\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_id"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"remote_id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"remote_id"}],"externalID":"c:objc(cs)MCRemoteOutboundRtpStreamStats(py)remote_id","title":"remote_id","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The remote endpoint or destination of the outbound RTP stream.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_id"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats/remote_id":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"remote_id"}],"kind":"symbol","type":"topic","abstract":[{"text":"The remote endpoint or destination of the outbound RTP stream.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remote_id"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats\/remote_id","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats\/remote_id","title":"remote_id"},"doc://MillicastSDK/documentation/MillicastSDK/MCRemoteOutboundRtpStreamStats":{"type":"topic","kind":"symbol","url":"\/documentation\/millicastsdk\/mcremoteoutboundrtpstreamstats","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"abstract":[{"type":"text","text":"Statistics related to an outgoing remote RTP stream."}],"navigatorTitle":[{"text":"MCRemoteOutboundRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRemoteOutboundRtpStreamStats","title":"MCRemoteOutboundRtpStreamStats"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","url":"\/documentation\/millicastsdk","abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"remote_id","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"remote_id","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"remote_id"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_id\/title","op":"replace","value":"remote_id"},{"value":[{"text":"remote_id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats~1remote_id\/fragments"},{"op":"replace","value":"MCRemoteOutboundRtpStreamStats","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/title"},{"value":[{"kind":"identifier","text":"MCRemoteOutboundRtpStreamStats"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRemoteOutboundRtpStreamStats\/fragments"}]}]}