{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","text":"MCCustomAudioSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCustomAudioSource"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"A new custom audio source."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder\/build()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder"]]},"variants":[{"paths":["\/documentation\/millicastsdk\/mccustomaudiosourcebuilder\/build()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosourcebuilder\/build()"]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)MCCustomAudioSourceBuilder(im)build","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCCustomAudioSource","preciseIdentifier":"c:objc(cs)MCCustomAudioSource"},{"kind":"text","text":"!"}],"symbolKind":"method","navigatorTitle":[{"text":"build","kind":"identifier"}],"title":"build()","role":"symbol"},"sections":[],"abstract":[{"text":"Builds the MCCustomAudioSource class.","type":"text"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSourceBuilder":{"title":"MCCustomAudioSourceBuilder","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCCustomAudioSourceBuilder","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosourcebuilder","abstract":[{"text":"Responsible for building MCCustomAudioSource.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCustomAudioSourceBuilder","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"abstract":[{"type":"text","text":"A custom audio source that can be fed any raw audio data for publishing."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCCustomAudioSource"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCCustomAudioSource"}],"title":"MCCustomAudioSource"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSourceBuilder/build()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSourceBuilder\/build()","title":"build()","role":"symbol","navigatorTitle":[{"text":"build","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosourcebuilder\/build()","abstract":[{"type":"text","text":"Builds the MCCustomAudioSource class."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCCustomAudioSource","preciseIdentifier":"c:objc(cs)MCCustomAudioSource","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"build","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"MCCustomAudioSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCCustomAudioSource","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"build"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/title","value":"MCCustomAudioSourceBuilder","op":"replace"},{"value":[{"kind":"identifier","text":"MCCustomAudioSourceBuilder"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title","value":"MCCustomAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments","value":[{"text":"MCCustomAudioSource","kind":"identifier"}]},{"op":"replace","value":"build","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder~1build()\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSourceBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]}]}]}