{"metadata":{"title":"MCStatsType.remoteOutboundRTP","externalID":"c:@E@MCStatsType@MCStatsTypeRemoteOutboundRTP","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteOutboundRTP"}],"navigatorTitle":[{"kind":"identifier","text":"MCStatsTypeRemoteOutboundRTP"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcstatstype\/remoteoutboundrtp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatstype\/remoteoutboundrtp"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteOutboundRTP"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType\/remoteOutboundRTP"},"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType":{"title":"MCStatsType","navigatorTitle":[{"kind":"identifier","text":"MCStatsType"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsType"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType","abstract":[{"type":"text","text":"Different types of statistics."}],"role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mcstatstype"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCStatsType/remoteOutboundRTP":{"abstract":[],"url":"\/documentation\/millicastsdk\/mcstatstype\/remoteoutboundrtp","type":"topic","title":"MCStatsType.remoteOutboundRTP","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteOutboundRTP","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCStatsType\/remoteOutboundRTP","role":"symbol","navigatorTitle":[{"text":"MCStatsTypeRemoteOutboundRTP","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MCStatsTypeRemoteOutboundRTP","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MCStatsTypeRemoteOutboundRTP","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MCStatsTypeRemoteOutboundRTP","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCStatsType","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsType"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType\/fragments","op":"replace"},{"value":"MCStatsTypeRemoteOutboundRTP","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType~1remoteOutboundRTP\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCStatsTypeRemoteOutboundRTP"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCStatsType~1remoteOutboundRTP\/fragments","op":"replace"}]}]}