{"abstract":[{"text":"The pixel format. For example, can be an I420 or a I444 frame.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/frametype()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/frametype()"]}],"metadata":{"title":"frameType()","required":true,"navigatorTitle":[{"text":"frameType","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)MCVideoFrame(im)frameType","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"frameType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCVideoType","preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"frameType","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"MCVideoType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCVideoType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","isActive":true,"type":"reference"},{"type":"text","text":" representing the pixel format."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/frameType()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/frameType()":{"role":"symbol","required":true,"navigatorTitle":[{"text":"frameType","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@MCVideoType","kind":"typeIdentifier","text":"MCVideoType"}],"title":"frameType()","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe\/frametype()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/frameType()","type":"topic","abstract":[{"type":"text","text":"The pixel format. For example, can be an I420 or a I444 frame."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"text":" ","type":"text"},{"type":"text","text":"with "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true,"type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoFrame"}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","title":"MCVideoFrame"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoType":{"url":"\/documentation\/millicastsdk\/mcvideotype","navigatorTitle":[{"text":"MCVideoType","kind":"identifier"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType","abstract":[],"title":"MCVideoType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MCVideoType","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"frameType"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"frameType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"MCVideoType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MCVideoType","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoType"},{"text":") ","kind":"text"},{"text":"frameType","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace","value":"MCVideoRenderer"},{"value":[{"kind":"identifier","text":"MCVideoRenderer"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1frameType()\/title","op":"replace","value":"frameType"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1frameType()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"frameType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"kind":"identifier","text":"MCVideoFrame"}],"op":"replace"},{"value":"MCVideoType","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoType\/fragments","op":"replace","value":[{"text":"MCVideoType","kind":"identifier"}]}]}]}