{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizei420()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizei420()"]}],"metadata":{"roleHeading":"Instance Method","title":"sizeI420()","navigatorTitle":[{"text":"sizeI420","kind":"identifier"}],"required":true,"symbolKind":"method","externalID":"c:objc(pl)MCVideoFrame(im)sizeI420","modules":[{"name":"MillicastSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sizeI420","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame"]]},"abstract":[{"text":"If the frame was an I420 frame, then this will return size of the frame in bytes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeI420","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"The actual size if it was an I420 frame, 0 otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame/sizeI420()":{"url":"\/documentation\/millicastsdk\/mcvideoframe\/sizei420()","type":"topic","kind":"symbol","title":"sizeI420()","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame\/sizeI420()","required":true,"abstract":[{"text":"If the frame was an I420 frame, then this will return size of the frame in bytes.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeI420"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"navigatorTitle":[{"kind":"identifier","text":"sizeI420"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoRenderer":{"role":"symbol","kind":"symbol","abstract":[{"text":"This protocol can be used to implement objects that receive video frames in your","type":"text"},{"type":"text","text":" "},{"text":"applications. Used in ","type":"text"},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"title":"MCVideoRenderer","url":"\/documentation\/millicastsdk\/mcvideorenderer","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCVideoRenderer"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCVideoRenderer","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCVideoFrame":{"abstract":[{"type":"text","text":"This class represents a raw Video Frame. Used"},{"text":" ","type":"text"},{"type":"text","text":"with "},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoRenderer","isActive":true,"type":"reference"},{"text":" for playback.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCVideoFrame","kind":"symbol","url":"\/documentation\/millicastsdk\/mcvideoframe","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCVideoFrame"}],"navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"role":"symbol","title":"MCVideoFrame"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sizeI420","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"sizeI420","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"uint32_t","preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sizeI420"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"sizeI420","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame~1sizeI420()\/fragments","value":[{"kind":"text","text":"- "},{"text":"sizeI420","kind":"identifier"}],"op":"replace"},{"value":"MCVideoRenderer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/title","op":"replace"},{"value":[{"text":"MCVideoRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame"},{"value":[{"text":"MCVideoFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","op":"replace"}]}]}