{"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate"]]},"abstract":[{"type":"text","text":"Called when the last viewer stops viewing the stream."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate\/publisherDidReceiveLastViewerInactive(_:)"},"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)MCPublisherDelegate(im)publisherDidReceiveLastViewerInactive:","title":"publisherDidReceiveLastViewerInactive(_:)","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publisherDidReceiveLastViewerInactive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MCPublisher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisher"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"publisherDidReceiveLastViewerInactive:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisherDidReceiveLastViewerInactive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"publisher"},{"kind":"text","text":": "},{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher","kind":"typeIdentifier","text":"MCPublisher"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Millicast publisher."}]}],"name":"publisher"}]}],"variants":[{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivelastviewerinactive(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivelastviewerinactive(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisherDelegate":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate","title":"MCPublisherDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisherDelegate","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisherdelegate","type":"topic","kind":"symbol","abstract":[{"text":"This delegate  acts as a listener for the Publisher class.","type":"text"},{"text":" ","type":"text"},{"text":"You must implement this protocol and set a delegate.","type":"text"},{"text":" ","type":"text"},{"text":"to receive events from the publisher.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MCPublisherDelegate","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisher":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCPublisher","kind":"identifier"}],"title":"MCPublisher","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher","abstract":[{"type":"text","text":"The Publisher interface is responsible for publishing media to a Millicast stream."}],"kind":"symbol","navigatorTitle":[{"text":"MCPublisher","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcpublisher"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCPublisherDelegate/publisherDidReceiveLastViewerInactive(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publisherDidReceiveLastViewerInactive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPublisher","text":"MCPublisher"},{"kind":"text","text":")"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisherDelegate\/publisherDidReceiveLastViewerInactive(_:)","navigatorTitle":[{"kind":"identifier","text":"publisherDidReceiveLastViewerInactive:"}],"kind":"symbol","abstract":[{"text":"Called when the last viewer stops viewing the stream.","type":"text"}],"title":"publisherDidReceiveLastViewerInactive(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mcpublisherdelegate\/publisherdidreceivelastviewerinactive(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"publisherDidReceiveLastViewerInactive:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"publisherDidReceiveLastViewerInactive:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"publisherDidReceiveLastViewerInactive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCPublisher","preciseIdentifier":"c:objc(cs)MCPublisher","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCPublisher"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"publisher"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"MCPublisherDelegate","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MCPublisherDelegate"}],"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/title","value":"MCPublisher"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisher\/fragments","value":[{"kind":"identifier","text":"MCPublisher"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate~1publisherDidReceiveLastViewerInactive(_:)\/title","value":"publisherDidReceiveLastViewerInactive:"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCPublisherDelegate~1publisherDidReceiveLastViewerInactive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publisherDidReceiveLastViewerInactive:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}