{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/init(min:max:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/init(min:max:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/init(min:max:)"]}],"metadata":{"title":"init(min:max:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"min","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)MCForcePlayoutDelay(im)initWithMin:max:","navigatorTitle":[{"text":"initWithMin:max:","kind":"identifier"}],"role":"symbol","symbolKind":"init","modules":[{"name":"MillicastSDK"}],"roleHeading":"Initializer"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/init(min:max:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/init(min:max:)","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/init(min:max:)","type":"topic","title":"init(min:max:)","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"navigatorTitle":[{"text":"MCForcePlayoutDelay","kind":"identifier"}],"title":"MCForcePlayoutDelay","abstract":[{"type":"text","text":"An option to tell the media server to"},{"type":"text","text":" "},{"text":"send hints about the range of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"playout delays that the RTP receiver should"},{"text":" ","type":"text"},{"type":"text","text":"follow, which effectively sets the delay"},{"text":" ","type":"text"},{"type":"text","text":"for each frame before it is rendered."},{"text":" ","type":"text"},{"type":"text","text":"Use this if you want to compensate"},{"type":"text","text":" "},{"type":"text","text":"for unpredictable network behaviour"},{"text":" ","type":"text"},{"text":"allowing for smooth playback at the cost","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of increasing latency."}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcforceplayoutdelay","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithMin:max:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMin:max:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMin:"},{"text":"(","kind":"text"},{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"min"},{"kind":"text","text":" "},{"kind":"identifier","text":"max:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":") "},{"kind":"internalParam","text":"max"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1init(min:max:)\/title","op":"replace","value":"initWithMin:max:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1init(min:max:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/title","value":"MCForcePlayoutDelay"},{"op":"replace","value":[{"text":"MCForcePlayoutDelay","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/fragments"}]}]}