{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maximum","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The maximum delay that should be added to"},{"text":" ","type":"text"},{"text":"each frame.","type":"text"}],"metadata":{"externalID":"c:objc(cs)MCForcePlayoutDelay(py)maximum","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"maximum","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximum"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"maximum"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/maximum"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcforceplayoutdelay\/maximum"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/maximum"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay/maximum":{"kind":"symbol","abstract":[{"type":"text","text":"The maximum delay that should be added to"},{"text":" ","type":"text"},{"type":"text","text":"each frame."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"maximum"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maximum","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"url":"\/documentation\/millicastsdk\/mcforceplayoutdelay\/maximum","title":"maximum","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay\/maximum","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCForcePlayoutDelay":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCForcePlayoutDelay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCForcePlayoutDelay"}],"navigatorTitle":[{"text":"MCForcePlayoutDelay","kind":"identifier"}],"title":"MCForcePlayoutDelay","abstract":[{"type":"text","text":"An option to tell the media server to"},{"type":"text","text":" "},{"text":"send hints about the range of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"playout delays that the RTP receiver should"},{"text":" ","type":"text"},{"type":"text","text":"follow, which effectively sets the delay"},{"text":" ","type":"text"},{"type":"text","text":"for each frame before it is rendered."},{"text":" ","type":"text"},{"type":"text","text":"Use this if you want to compensate"},{"type":"text","text":" "},{"type":"text","text":"for unpredictable network behaviour"},{"text":" ","type":"text"},{"text":"allowing for smooth playback at the cost","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of increasing latency."}],"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mcforceplayoutdelay","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"maximum","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"maximum","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"text":" ","kind":"text"},{"text":"maximum","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1maximum\/title","op":"replace","value":"maximum"},{"value":[{"kind":"identifier","text":"maximum"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay~1maximum\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/title","value":"MCForcePlayoutDelay","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCForcePlayoutDelay\/fragments","op":"replace","value":[{"text":"MCForcePlayoutDelay","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}