{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"m","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"m","content":[{"inlineContent":[{"type":"text","text":"A boolean indicating whether the audio source should be muted (true) or not (false)."}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"externalID":"c:objc(pl)MCAudioControl(im)mute:","modules":[{"name":"MillicastSDK"}],"required":true,"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"mute:","kind":"identifier"}],"roleHeading":"Instance Method","title":"mute(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mute","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/mute(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/mute(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudiocontrol\/mute(_:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Mutes the microphone or the speakers."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl"]]},"sections":[],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl","type":"topic","url":"\/documentation\/millicastsdk\/mcaudiocontrol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCAudioControl","kind":"identifier"}],"navigatorTitle":[{"text":"MCAudioControl","kind":"identifier"}],"abstract":[{"type":"text","text":"Manages audio settings."}],"kind":"symbol","title":"MCAudioControl"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioControl/mute(_:)":{"type":"topic","abstract":[{"text":"Mutes the microphone or the speakers.","type":"text"}],"url":"\/documentation\/millicastsdk\/mcaudiocontrol\/mute(_:)","required":true,"navigatorTitle":[{"text":"mute:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"mute(_:)","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioControl\/mute(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"mute:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mute:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"mute:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_Bool","kind":"typeIdentifier","preciseIdentifier":"c:b"},{"kind":"text","text":") "},{"text":"m","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MCAudioControl","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl\/fragments","value":[{"text":"MCAudioControl","kind":"identifier"}],"op":"replace"},{"value":"mute:","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1mute(_:)\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioControl~1mute(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mute:","kind":"identifier"}],"op":"replace"}]}]}