{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStopPlaying(_:error:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioPlayerNodeDidStopPlaying","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"node"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayerNode","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioPlayerNodeDidStopPlaying"},{"text":"(","kind":"text"},{"text":"AVAudioPlayerNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"audioPlayerNodeDidStopPlaying:error:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false}],"title":"audioPlayerNodeDidStopPlaying(_:error:)","role":"symbol","externalID":"c:objc(pl)MCAudioPlayerNodeDelegate(im)audioPlayerNodeDidStopPlaying:error:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstopplaying(_:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstopplaying(_:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","type":"topic","navigatorTitle":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"title":"MCAudioPlayerNodeDelegate","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidStopPlaying(_:error:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidStopPlaying(_:error:)","abstract":[],"kind":"symbol","type":"topic","title":"audioPlayerNodeDidStopPlaying(_:error:)","role":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidstopplaying(_:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioPlayerNodeDidStopPlaying","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidStopPlaying:error:"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerNodeDidStopPlaying:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"audioPlayerNodeDidStopPlaying:error:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"audioPlayerNodeDidStopPlaying:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"node","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title","value":"MCAudioPlayerNodeDelegate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments","op":"replace","value":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStopPlaying(_:error:)\/title","value":"audioPlayerNodeDidStopPlaying:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidStopPlaying(_:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"audioPlayerNodeDidStopPlaying:error:","kind":"identifier"}]}]}]}