{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeunavailable(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeunavailable(_:)"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"8.0","unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable"},{"text":"(","kind":"text"},{"text":"AVAudioPlayerNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPlayerNode"},{"kind":"text","text":")"}],"required":true,"externalID":"c:objc(pl)MCAudioPlayerNodeDelegate(im)audioPlayerNodeDidBecomeUnAvailable:","symbolKind":"method","role":"symbol","title":"audioPlayerNodeDidBecomeUnAvailable(_:)","navigatorTitle":[{"text":"audioPlayerNodeDidBecomeUnAvailable:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioPlayerNodeDidBecomeUnAvailable","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"node"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeUnAvailable(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodeDelegate/audioPlayerNodeDidBecomeUnAvailable(_:)":{"role":"symbol","type":"topic","title":"audioPlayerNodeDidBecomeUnAvailable(_:)","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate\/audioplayernodedidbecomeunavailable(_:)","navigatorTitle":[{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable:"}],"required":true,"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate\/audioPlayerNodeDidBecomeUnAvailable(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioPlayerNodeDelegate":{"abstract":[{"type":"text","text":"Delegate that allows clients to tap into the AVAudioPlayerNode responsible for playback the SDK audio."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioPlayerNodeDelegate","type":"topic","navigatorTitle":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcaudioplayernodedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioPlayerNodeDelegate"}],"title":"MCAudioPlayerNodeDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerNodeDidBecomeUnAvailable:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"audioPlayerNodeDidBecomeUnAvailable:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayerNode","text":"AVAudioPlayerNode","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"node"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeUnAvailable(_:)\/title","value":"audioPlayerNodeDidBecomeUnAvailable:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"audioPlayerNodeDidBecomeUnAvailable:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate~1audioPlayerNodeDidBecomeUnAvailable(_:)\/fragments"},{"value":"MCAudioPlayerNodeDelegate","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/title"},{"value":[{"text":"MCAudioPlayerNodeDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioPlayerNodeDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}