{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"enable","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"enable(_:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"MillicastSDK"}],"externalID":"c:objc(cs)MCTrack(im)enable:","navigatorTitle":[{"kind":"identifier","text":"enable:"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enable"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"e"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"True to enable the track, false otherwise.","type":"text"}],"type":"paragraph"}],"name":"e"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/millicastsdk\/mctrack\/enable(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrack\/enable(_:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/enable(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Enables or disables the track. A disabled audio track produces silence. A disabled video track produces black frames."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/enable(_:)":{"title":"enable(_:)","type":"topic","url":"\/documentation\/millicastsdk\/mctrack\/enable(_:)","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/enable(_:)","role":"symbol","abstract":[{"type":"text","text":"Enables or disables the track. A disabled audio track produces silence. A disabled video track produces black frames."}],"navigatorTitle":[{"kind":"identifier","text":"enable:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enable"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","title":"MCTrack","role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"enable:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"enable:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"enable:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"e"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1enable(_:)\/title","value":"enable:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1enable(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"enable:","kind":"identifier"}]},{"value":"MCTrack","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","op":"replace","value":[{"text":"MCTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}