{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getId","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The track ID."}]}],"kind":"content"}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"title":"getId()","externalID":"c:objc(cs)MCTrack(im)getId","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getId"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/getId()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrack\/getid()"]},{"paths":["\/documentation\/millicastsdk\/mctrack\/getid()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Get the track Id.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/getId()":{"title":"getId()","abstract":[{"type":"text","text":"Get the track Id."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getId"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"getId","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mctrack\/getid()","type":"topic","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/getId()","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","title":"MCTrack","role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getId"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getId"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getId"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"getId","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1getId()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getId"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1getId()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","op":"replace","value":"MCTrack"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","op":"replace","value":[{"text":"MCTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}