{"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"title":"kind()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kind"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MCTrack(im)kind","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"kind"}]},"sections":[],"abstract":[{"type":"text","text":"Get  the track type."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/kind()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mctrack\/kind()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mctrack\/kind()"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The track type, either audio or video.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack/kind()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack\/kind()","role":"symbol","title":"kind()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"kind","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mctrack\/kind()","abstract":[{"type":"text","text":"Get  the track type."}],"navigatorTitle":[{"text":"kind","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","title":"MCTrack","role":"symbol","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents a captured instance of a media source."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCTrack","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"kind","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"kind","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"kind"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"kind","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1kind()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"kind","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack~1kind()\/fragments"},{"value":"MCTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","op":"replace"},{"value":[{"text":"MCTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments"}]}]}