{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)"]},{"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"onAudioFrame:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAudioFrame","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MCAudioFrame","kind":"typeIdentifier","text":"MCAudioFrame"},{"text":"!)","kind":"text"}],"externalID":"c:objc(cs)MCCustomAudioSource(im)onAudioFrame:","title":"onAudioFrame(_:)","roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":": "},{"text":"MCAudioFrame","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An audio frame to feed. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame","type":"reference"},{"type":"text","text":" for"},{"type":"text","text":" "},{"text":"possible audio frames to feed. Currently only 48kHz and 44.1kHz are supported sample formats.","type":"text"}],"type":"paragraph"}],"name":"frame"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/onAudioFrame(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"To be called whenever the application wishes to feed audio frames to the source."}],"title":"onAudioFrame(_:)","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/onaudioframe(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAudioFrame"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame"},{"text":"!)","kind":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","navigatorTitle":[{"kind":"identifier","text":"onAudioFrame:"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAudioFrame":{"title":"MCAudioFrame","url":"\/documentation\/millicastsdk\/mcaudioframe","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","abstract":[{"type":"text","text":"Audio frame that contains audio data. Used with "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/onAudioFrame(_:)","type":"reference"},{"text":" ","type":"text"},{"type":"text","text":"to feed custom audio frames into source used by a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCAudioFrame"}],"navigatorTitle":[{"text":"MCAudioFrame","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher":{"navigatorTitle":[{"kind":"identifier","text":"MCPublisher"}],"type":"topic","role":"symbol","url":"\/documentation\/millicastsdk\/mcpublisher","kind":"symbol","title":"MCPublisher","abstract":[{"text":"The Publisher interface is responsible for publishing media to a Millicast stream.","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCPublisher","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCMSampleBufferFrame":{"kind":"symbol","role":"symbol","url":"\/documentation\/millicastsdk\/mccmsamplebufferframe","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for initializing a "},{"type":"reference","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","isActive":true},{"text":"  from a ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCMSampleBufferFrame","title":"MCCMSampleBufferFrame","navigatorTitle":[{"kind":"identifier","text":"MCCMSampleBufferFrame"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"abstract":[{"text":"A custom audio source that can be fed any raw audio data for publishing.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCustomAudioSource","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","role":"symbol","title":"MCCustomAudioSource","navigatorTitle":[{"text":"MCCustomAudioSource","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onAudioFrame:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAudioFrame:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onAudioFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MCAudioFrame","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioFrame","preciseIdentifier":"c:objc(cs)MCAudioFrame","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/title","value":"onAudioFrame:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onAudioFrame:","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1onAudioFrame(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/title","value":"MCAudioFrame","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MCAudioFrame"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioFrame\/fragments"},{"value":"MCPublisher","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/title"},{"value":[{"kind":"identifier","text":"MCPublisher"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/title","op":"replace","value":"MCCMSampleBufferFrame"},{"op":"replace","value":[{"text":"MCCMSampleBufferFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCMSampleBufferFrame\/fragments"},{"value":"MCCustomAudioSource","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"MCCustomAudioSource"}]}]}]}