{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCapture"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","text":"MCTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":"!","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"An audio track. See ","type":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","type":"reference","isActive":true},{"type":"text","text":" "},{"type":"text","text":"to learn how to attach this track to a publisher."}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Starts capture. Effectively creates an audio track that can be added to the publisher."}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource"]]},"sections":[],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/startCapture()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)MCCustomAudioSource(im)startCapture","title":"startCapture()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCTrack","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/startcapture()"]},{"paths":["\/documentation\/millicastsdk\/mccustomaudiosource\/startcapture()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAudioSource/startCapture()":{"kind":"symbol","title":"startCapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","abstract":[{"text":"Initiates the audio capture process from the current source.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startCapture"}],"url":"\/documentation\/millicastsdk\/mcaudiosource\/startcapture()"},"doc://MillicastSDK/documentation/MillicastSDK/MCPublisher/addTrack(with:completionHandler:)-340my":{"kind":"symbol","title":"addTrack(with:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCAudioTrack","preciseIdentifier":"c:objc(cs)MCAudioTrack"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCPublisher\/addTrack(with:completionHandler:)-340my","abstract":[{"type":"text","text":"Adds an audio track to the publisher. See "},{"isActive":true,"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAudioSource\/startCapture()","type":"reference"},{"type":"text","text":" as an example"},{"text":" ","type":"text"},{"text":"for capturing an audio device track.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addTrackWithAudioTrack:completionHandler:"}],"url":"\/documentation\/millicastsdk\/mcpublisher\/addtrack(with:completionhandler:)-340my"},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource/startCapture()":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource\/startCapture()","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/millicastsdk\/mccustomaudiosource\/startcapture()","abstract":[{"text":"Starts capture. Effectively creates an audio track that can be added to the publisher.","type":"text"}],"title":"startCapture()","navigatorTitle":[{"text":"startCapture","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startCapture","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MCTrack","preciseIdentifier":"c:objc(cs)MCTrack","kind":"typeIdentifier"},{"kind":"text","text":"!"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCCustomAudioSource":{"abstract":[{"text":"A custom audio source that can be fed any raw audio data for publishing.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCCustomAudioSource","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mccustomaudiosource","type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCCustomAudioSource","role":"symbol","title":"MCCustomAudioSource","navigatorTitle":[{"text":"MCCustomAudioSource","kind":"identifier"}],"kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCTrack":{"title":"MCTrack","navigatorTitle":[{"text":"MCTrack","kind":"identifier"}],"abstract":[{"text":"Represents a captured instance of a media source.","type":"text"}],"url":"\/documentation\/millicastsdk\/mctrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCTrack"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"startCapture","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"startCapture","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"MCTrack","kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCTrack","preciseIdentifier":"c:objc(cs)MCTrack"},{"text":" *) ","kind":"text"},{"text":"startCapture","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"startCapture","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startCapture"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAudioSource~1startCapture()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/title","value":"addTrackWithAudioTrack:completionHandler:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCPublisher~1addTrack(with:completionHandler:)-340my\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithAudioTrack:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1startCapture()\/title","op":"replace","value":"startCapture"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCapture"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource~1startCapture()\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/title","value":"MCCustomAudioSource","op":"replace"},{"value":[{"text":"MCCustomAudioSource","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCCustomAudioSource\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/title","op":"replace","value":"MCTrack"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCTrack\/fragments","value":[{"text":"MCTrack","kind":"identifier"}]}]}]}