{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizergb()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcvideoframe\/sizergb()"]}],"abstract":[{"type":"text","text":"If the frame was an RGB frame, then this will return size of the frame in bytes."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame"]]},"sections":[],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeRgb","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The actual size if it was an RGB frame, 0 otherwise."}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"sizeRgb"}],"externalID":"c:objc(pl)MCVideoFrame(im)sizeRgb","modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeRgb"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"role":"symbol","title":"sizeRgb()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"title":"MillicastSDK","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk","role":"collection"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoRenderer":{"abstract":[{"type":"text","text":"This protocol can be used to implement objects that receive video frames in your"},{"type":"text","text":" "},{"type":"text","text":"applications. Used in "},{"type":"reference","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoTrack\/add(_:)","isActive":true},{"type":"text","text":" to start receiving"},{"type":"text","text":" "},{"type":"text","text":"video frames from that video track."}],"navigatorTitle":[{"text":"MCVideoRenderer","kind":"identifier"}],"title":"MCVideoRenderer","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoRenderer","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideorenderer","kind":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame":{"title":"MCVideoFrame","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame","navigatorTitle":[{"text":"MCVideoFrame","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCVideoFrame","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcvideoframe","kind":"symbol","abstract":[{"text":"This class represents a raw Video Frame. Used","type":"text"},{"text":" ","type":"text"},{"text":"with ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoRenderer"},{"text":" for playback.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCVideoFrame/sizeRgb()":{"title":"sizeRgb()","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sizeRgb"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeRgb"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"type":"topic","abstract":[{"text":"If the frame was an RGB frame, then this will return size of the frame in bytes.","type":"text"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCVideoFrame\/sizeRgb()","url":"\/documentation\/millicastsdk\/mcvideoframe\/sizergb()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"sizeRgb","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeRgb"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@uint32_t","text":"uint32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sizeRgb","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/title","value":"MCVideoRenderer","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoRenderer\/fragments","value":[{"kind":"identifier","text":"MCVideoRenderer"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/title","value":"MCVideoFrame","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame\/fragments","value":[{"text":"MCVideoFrame","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/title","value":"sizeRgb","op":"replace"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCVideoFrame~1sizeRgb()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeRgb"}],"op":"replace"}]}]}