{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"project"},{"text":"(","kind":"text"},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"kind":"text","text":", "},{"text":"promote","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" ((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"the RTS track which will be projected onto this webrtc"},{"type":"text","text":" "},{"text":"track.","type":"text"}],"type":"paragraph"}],"name":"rtsRemoteVideoTrack"},{"name":"layer","content":[{"type":"paragraph","inlineContent":[{"text":"layer information. If the default value is passed, the service","type":"text"},{"text":" ","type":"text"},{"text":"will allocate layers automatically depending on bandwidth estimation and","type":"text"},{"text":" ","type":"text"},{"text":"the priority","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Set this track to be the main video track. The main video"},{"text":" ","type":"text"},{"text":"track has highest priority for bandwidth assignment when SVC layers are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"managed by the service."}],"type":"paragraph"}],"name":"promote"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked when the asynchronous operation is finished"}]}],"name":"completionHandler"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"Note that unlike the simple API for the RTS track, this API is more","type":"text"},{"type":"text","text":" "},{"text":"flexible, but requires more handling by the application. Specifically:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"this function sets no video renderer. Renderers should be added"},{"type":"text","text":" "},{"text":"separately.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the track will not be unprojected automatically when the RTS track goes"},{"text":" ","type":"text"},{"text":"inactive (and will not require repeating project operation when it goes","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"active again)"}]}]}]},{"inlineContent":[{"text":"You can project the same RTS track onto multiple webrtc logical tracks.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:promote:completionhandler:)"]},{"paths":["\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:promote:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)"},"abstract":[{"type":"text","text":"Enable the track and project from given RTS track."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"project","kind":"identifier"},{"kind":"text","text":"("},{"text":"rtsRemoteVideoTrack","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layer"},{"kind":"text","text":": "},{"text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","title":"project(rtsRemoteVideoTrack:layer:promote:completionHandler:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)MCWebrtcRemoteVideoTrack(im)projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:","modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayer","navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayer"}],"title":"MCRTSRemoteVideoTrackLayer","role":"symbol","abstract":[{"type":"text","text":"This class represents the selected layer information which"},{"type":"text","text":" "},{"type":"text","text":"the client wants to inform the media server to select."}]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCWebrtcRemoteVideoTrack"}],"abstract":[{"type":"text","text":"The webrtc logical track’s video interface."}],"type":"topic","title":"MCWebrtcRemoteVideoTrack"},"doc://MillicastSDK/documentation/MillicastSDK":{"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","title":"MillicastSDK","type":"topic","role":"collection","abstract":[]},"doc://MillicastSDK/documentation/MillicastSDK/MCWebrtcRemoteVideoTrack/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCWebrtcRemoteVideoTrack\/project(rtsRemoteVideoTrack:layer:promote:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcwebrtcremotevideotrack\/project(rtsremotevideotrack:layer:promote:completionhandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"project","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rtsRemoteVideoTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack"},{"kind":"text","text":", "},{"text":"layer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer","text":"MCRTSRemoteVideoTrackLayer"},{"text":", ","kind":"text"},{"text":"promote","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Enable the track and project from given RTS track.","type":"text"}],"type":"topic","title":"project(rtsRemoteVideoTrack:layer:promote:completionHandler:)"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrack":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","title":"MCRTSRemoteVideoTrack","url":"\/documentation\/millicastsdk\/mcrtsremotevideotrack","type":"topic","role":"symbol","navigatorTitle":[{"text":"MCRTSRemoteVideoTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"The RTS logical track’s video interface."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"projectWithRTSRemoteVideoTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrack","text":"MCRTSRemoteVideoTrack","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrack"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rtsRemoteVideoTrack"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayer","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayer","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"layer"},{"text":" ","kind":"text"},{"text":"promote:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"promote","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/title","op":"replace","value":"MCRTSRemoteVideoTrackLayer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayer\/fragments","value":[{"text":"MCRTSRemoteVideoTrackLayer","kind":"identifier"}]},{"value":"MCWebrtcRemoteVideoTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/title","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack\/fragments","value":[{"text":"MCWebrtcRemoteVideoTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:promote:completionHandler:)\/title","op":"replace","value":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"projectWithRTSRemoteVideoTrack:layer:promote:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCWebrtcRemoteVideoTrack~1project(rtsRemoteVideoTrack:layer:promote:completionHandler:)\/fragments"},{"value":"MCRTSRemoteVideoTrack","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrack"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrack\/fragments","op":"replace"}]}]}