{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAcceleratedVideoRendererDelegate","text":"MCAcceleratedVideoRendererDelegate"},{"kind":"text","text":")?"}],"modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(cs)MCAcceleratedVideoRenderer(py)delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property","title":"delegate","symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/delegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MCAcceleratedVideoRendererDelegate","text":"MCAcceleratedVideoRendererDelegate","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","title":"MCAcceleratedVideoRenderer","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer","abstract":[{"type":"text","text":"Class that renders video frames in a "},{"type":"codeVoice","code":"UIView"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"NSView"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"type":"topic","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRenderer/delegate":{"type":"topic","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/delegate","title":"delegate","abstract":[{"type":"text","text":"Delegate that can be used to receive information about video frame properties."}],"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MCAcceleratedVideoRendererDelegate","kind":"typeIdentifier","text":"MCAcceleratedVideoRendererDelegate"},{"kind":"text","text":")?"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/delegate"},"doc://MillicastSDK/documentation/MillicastSDK/MCAcceleratedVideoRendererDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MCAcceleratedVideoRendererDelegate","kind":"identifier"}],"abstract":[{"text":"Protocol that allows subscribing to callbacks that inform about rendering video frame size changes.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}],"title":"MCAcceleratedVideoRendererDelegate","url":"\/documentation\/millicastsdk\/mcacceleratedvideorendererdelegate","kind":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCAcceleratedVideoRendererDelegate","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"delegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"text":"id<MCAcceleratedVideoRendererDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MCAcceleratedVideoRendererDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","value":"MCAcceleratedVideoRenderer","op":"replace"},{"value":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1delegate\/title","value":"delegate"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/title","op":"replace","value":"MCAcceleratedVideoRendererDelegate"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCAcceleratedVideoRendererDelegate\/fragments","value":[{"kind":"identifier","text":"MCAcceleratedVideoRendererDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}