{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1h"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1h"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1h"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"l2t1h"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL2T1h","roleHeading":"Case","role":"symbol","title":"MCScalabilityMode.l2t1h","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"l2t1h"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T1h"}],"modules":[{"name":"MillicastSDK"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","title":"the WebRTC standard","titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"type":"link","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l2t1h":{"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t1h","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"l2t1h","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MCScalabilityModeL2T1h","kind":"identifier"}],"title":"MCScalabilityMode.l2t1h","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t1h"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","type":"topic","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"text":" to understand where these values come from","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","role":"symbol","navigatorTitle":[{"text":"MCScalabilityMode","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MCScalabilityModeL2T1h","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL2T1h","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"MCScalabilityModeL2T1h","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1h\/title","value":"MCScalabilityModeL2T1h"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t1h\/fragments","op":"replace","value":[{"text":"MCScalabilityModeL2T1h","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","op":"replace","value":"MCScalabilityMode"},{"op":"replace","value":[{"kind":"identifier","text":"MCScalabilityMode"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments"}]}]}