{"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t3h"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/l2t3h"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3h"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"l2t3h","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","title":"MCScalabilityMode.l2t3h","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"l2t3h","kind":"identifier"}],"externalID":"c:@E@MCScalabilityMode@MCScalabilityModeL2T3h","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T3h"}],"modules":[{"name":"MillicastSDK"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/l2t3h":{"title":"MCScalabilityMode.l2t3h","abstract":[],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/l2t3h","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"l2t3h","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode\/l2t3h","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeL2T3h"}]},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"titleInlineContent":[{"type":"text","text":"the WebRTC standard"}],"identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","type":"link","title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","type":"topic","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"text":" to understand where these values come from","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","role":"symbol","navigatorTitle":[{"text":"MCScalabilityMode","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MCScalabilityModeL2T3h"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MCScalabilityModeL2T3h","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCScalabilityModeL2T3h"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3h\/title","value":"MCScalabilityModeL2T3h","op":"replace"},{"value":[{"kind":"identifier","text":"MCScalabilityModeL2T3h"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1l2t3h\/fragments"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title","value":"MCScalabilityMode","op":"replace"},{"value":[{"text":"MCScalabilityMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}