{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"s2t2","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2"]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode"]]},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"MCScalabilityMode.s2t2","externalID":"c:@E@MCScalabilityMode@MCScalabilityModeS2T2","role":"symbol","modules":[{"name":"MillicastSDK"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T2"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"s2t2","kind":"identifier"}]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode/s2t2":{"abstract":[],"kind":"symbol","title":"MCScalabilityMode.s2t2","role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode\/s2t2","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"s2t2","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MCScalabilityModeS2T2"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcscalabilitymode\/s2t2"},"https://www.w3.org/TR/webrtc-svc/#scalabilitymodes*":{"type":"link","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*","titleInlineContent":[{"text":"the WebRTC standard","type":"text"}],"title":"the WebRTC standard","url":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},"doc://MillicastSDK/documentation/MillicastSDK":{"type":"topic","title":"MillicastSDK","url":"\/documentation\/millicastsdk","kind":"symbol","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","role":"collection"},"doc://MillicastSDK/documentation/MillicastSDK/MCScalabilityMode":{"title":"MCScalabilityMode","type":"topic","abstract":[{"type":"text","text":"MCScalabilityMode refers to Scalable Video Coding. This is only available for publishing. Please refer to "},{"isActive":true,"type":"reference","identifier":"https:\/\/www.w3.org\/TR\/webrtc-svc\/#scalabilitymodes*"},{"text":" to understand where these values come from","type":"text"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCScalabilityMode","role":"symbol","navigatorTitle":[{"text":"MCScalabilityMode","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcscalabilitymode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MCScalabilityMode"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MCScalabilityModeS2T2"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MCScalabilityModeS2T2"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MCScalabilityModeS2T2"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"MCScalabilityModeS2T2","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2\/title"},{"value":[{"kind":"identifier","text":"MCScalabilityModeS2T2"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode~1s2t2\/fragments","op":"replace"},{"value":"MCScalabilityMode","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/title"},{"value":[{"text":"MCScalabilityMode","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCScalabilityMode\/fragments","op":"replace"}]}]}