{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"obj"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","preciseIdentifier":"c:objc(cs)MCStats","text":"MCStats"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"obj","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A stats object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcstatsreport\/add(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcstatsreport\/add(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/add(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a MCStats object to the stats report, effectively storing statistical data for analysis and reporting purposes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats"},{"kind":"text","text":"!)"}],"title":"add(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCStatsReport(im)addStats:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"addStats:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport"]]},"references":{"https://w3c.github.io/webrtc-stats/#introduction":{"title":"WebRTC standard","titleInlineContent":[{"type":"text","text":"WebRTC standard"}],"type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction","url":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport/add(_:)":{"role":"symbol","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MCStats","preciseIdentifier":"c:objc(cs)MCStats"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Adds a MCStats object to the stats report, effectively storing statistical data for analysis and reporting purposes."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport\/add(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addStats:"}],"url":"\/documentation\/millicastsdk\/mcstatsreport\/add(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCStatsReport":{"role":"symbol","title":"MCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStatsReport"}],"abstract":[{"type":"text","text":"Interface is a container for various different statistics."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStatsReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStatsReport"}],"url":"\/documentation\/millicastsdk\/mcstatsreport"},"doc://MillicastSDK/documentation/MillicastSDK/MCStats":{"role":"symbol","title":"MCStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCStats"}],"abstract":[{"type":"text","text":"A container of various different stats. To make sense of such statistics, please refer to the "},{"type":"reference","isActive":true,"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#introduction"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCStats"}],"url":"\/documentation\/millicastsdk\/mcstats"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addStats:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStats:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addStats:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCStats","preciseIdentifier":"c:objc(cs)MCStats","text":"MCStats"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"obj"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1add(_:)\/title","value":"addStats:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport~1add(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStats:"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/title","value":"MCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStatsReport\/fragments","value":[{"kind":"identifier","text":"MCStatsReport"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/title","value":"MCStats"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCStats\/fragments","value":[{"kind":"identifier","text":"MCStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}