{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resolution","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayerResolution","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/resolution","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/resolution"]},{"paths":["\/documentation\/millicastsdk\/mcrtsremotetracklayer\/resolution"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"resolution","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"MillicastSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolution","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution","text":"MCRTSRemoteVideoTrackLayerResolution"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"resolution"}],"externalID":"c:objc(cs)MCRTSRemoteTrackLayer(py)resolution","symbolKind":"property"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer/resolution":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolution","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution","kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayerResolution"},{"kind":"text","text":"?"}],"type":"topic","title":"resolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer\/resolution","navigatorTitle":[{"text":"resolution","kind":"identifier"}],"abstract":[],"url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer\/resolution"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","title":"MillicastSDK","abstract":[],"kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteVideoTrackLayerResolution":{"role":"symbol","kind":"symbol","title":"MCRTSRemoteVideoTrackLayerResolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution","abstract":[{"type":"text","text":"Represents resolution of a video frame."}],"navigatorTitle":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}],"type":"topic","url":"\/documentation\/millicastsdk\/mcrtsremotevideotracklayerresolution","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteVideoTrackLayerResolution","kind":"identifier"}]},"doc://MillicastSDK/documentation/MillicastSDK/MCRTSRemoteTrackLayer":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteTrackLayer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"title":"MCRTSRemoteTrackLayer","abstract":[{"type":"text","text":"Represents an layer entry in the layers event received by the media server."}],"kind":"symbol","url":"\/documentation\/millicastsdk\/mcrtsremotetracklayer","navigatorTitle":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"resolution","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"resolution"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"MCRTSRemoteVideoTrackLayerResolution","preciseIdentifier":"c:objc(cs)MCRTSRemoteVideoTrackLayerResolution","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCRTSRemoteVideoTrackLayerResolution"},{"kind":"text","text":" * "},{"text":"resolution","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"resolution","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1resolution\/title"},{"op":"replace","value":[{"text":"resolution","kind":"identifier"}],"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer~1resolution\/fragments"},{"value":"MCRTSRemoteVideoTrackLayerResolution","op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteVideoTrackLayerResolution\/fragments","value":[{"kind":"identifier","text":"MCRTSRemoteVideoTrackLayerResolution"}]},{"op":"replace","value":"MCRTSRemoteTrackLayer","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/title"},{"value":[{"text":"MCRTSRemoteTrackLayer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCRTSRemoteTrackLayer\/fragments"}]}]}