{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/init(colorrangeexpansion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/init(colorrangeexpansion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init(colorRangeExpansion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes with the option of expanding limited color range to the full range upon rendering."}],"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer"]]},"metadata":{"modules":[{"name":"MillicastSDK"}],"role":"symbol","externalID":"c:objc(cs)MCAcceleratedVideoRenderer(im)initWithColorRangeExpansion:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"colorRangeExpansion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithColorRangeExpansion:","kind":"identifier"}],"title":"init(colorRangeExpansion:)","roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"colorRangeExpansion","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"enable","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"enable","content":[{"inlineContent":[{"text":"True to enable color range expansion. Disabled by default.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRenderer/init(colorRangeExpansion:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"colorRangeExpansion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer\/init(colorRangeExpansion:)","navigatorTitle":[{"kind":"identifier","text":"initWithColorRangeExpansion:"}],"url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer\/init(colorrangeexpansion:)","title":"init(colorRangeExpansion:)","abstract":[{"text":"Initializes with the option of expanding limited color range to the full range upon rendering.","type":"text"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCAcceleratedVideoRenderer":{"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCAcceleratedVideoRenderer","url":"\/documentation\/millicastsdk\/mcacceleratedvideorenderer","navigatorTitle":[{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"role":"symbol","abstract":[{"text":"Class that renders video frames in a ","type":"text"},{"code":"UIView","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"NSView","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCAcceleratedVideoRenderer"}],"type":"topic","title":"MCAcceleratedVideoRenderer"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"abstract":[],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","type":"topic","kind":"symbol","title":"MillicastSDK","url":"\/documentation\/millicastsdk","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithColorRangeExpansion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithColorRangeExpansion:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithColorRangeExpansion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"enable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init(colorRangeExpansion:)\/title","op":"replace","value":"initWithColorRangeExpansion:"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer~1init(colorRangeExpansion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithColorRangeExpansion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/title","op":"replace","value":"MCAcceleratedVideoRenderer"},{"path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCAcceleratedVideoRenderer\/fragments","op":"replace","value":[{"text":"MCAcceleratedVideoRenderer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}