{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableWebsocketLogs"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"disable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"disable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True to disable the logs. False otherwise."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mclogger\/disablewebsocketlogs(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mclogger\/disablewebsocketlogs(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger\/disableWebsocketLogs(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Disable websocket logs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableWebsocketLogs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"disableWebsocketLogs(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MCLogger(cm)disableWebsocketLogs:","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"disableWebsocketLogs:"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLogger":{"role":"symbol","title":"MCLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLogger"}],"abstract":[{"type":"text","text":"Class that is responsible for managing SDK logs."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLogger"}],"url":"\/documentation\/millicastsdk\/mclogger"},"doc://MillicastSDK/documentation/MillicastSDK/MCLogger/disableWebsocketLogs(_:)":{"role":"symbol","title":"disableWebsocketLogs(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableWebsocketLogs"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Disable websocket logs."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLogger\/disableWebsocketLogs(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableWebsocketLogs:"}],"url":"\/documentation\/millicastsdk\/mclogger\/disablewebsocketlogs(_:)"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"disableWebsocketLogs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"disableWebsocketLogs:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"disableWebsocketLogs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"disable"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/title","value":"MCLogger"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger\/fragments","value":[{"kind":"identifier","text":"MCLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger~1disableWebsocketLogs(_:)\/title","value":"disableWebsocketLogs:"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLogger~1disableWebsocketLogs(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"disableWebsocketLogs:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}