{"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError\/reason-swift.property","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/millicastsdk\/mcsignalingerror\/reason-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcsignalingerror\/reason-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reason","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The HTTP error reason."}],"metadata":{"externalID":"c:objc(cs)MCSignalingError(py)reason","modules":[{"name":"MillicastSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reason"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"reason","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"reason","symbolKind":"property"},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSignalingError/reason-swift.property":{"abstract":[{"text":"The HTTP error reason.","type":"text"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError\/reason-swift.property","url":"\/documentation\/millicastsdk\/mcsignalingerror\/reason-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"reason","kind":"identifier"}],"kind":"symbol","title":"reason","role":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK":{"abstract":[],"role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","url":"\/documentation\/millicastsdk","type":"topic","title":"MillicastSDK","kind":"symbol"},"doc://MillicastSDK/documentation/MillicastSDK/MCSignalingError":{"title":"MCSignalingError","role":"symbol","navigatorTitle":[{"text":"MCSignalingError","kind":"identifier"}],"url":"\/documentation\/millicastsdk\/mcsignalingerror","abstract":[{"text":"Container class for Signaling errors that occur during","type":"text"},{"type":"text","text":" "},{"type":"text","text":"signaling\/configuration of the peer connection."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MCSignalingError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSignalingError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"reason","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"reason","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"reason"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError~1reason-swift.property\/title","value":"reason"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError~1reason-swift.property\/fragments","value":[{"kind":"identifier","text":"reason"}]},{"op":"replace","value":"MCSignalingError","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/title"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSignalingError\/fragments","value":[{"kind":"identifier","text":"MCSignalingError"}]}]}]}