{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData","text":"MCLayerData"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/millicastsdk\/mcprojectiondata\/layer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/millicastsdk\/mcprojectiondata\/layer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/layer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optionally choose a simulcast layer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"?"}],"title":"layer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)MCProjectionData(py)layer","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"kind":"identifier","text":"layer"}]},"hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData"]]},"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCLayerData":{"role":"symbol","title":"MCLayerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCLayerData"}],"abstract":[{"type":"text","text":"The layer data is used to select a simulcast\/svc layer."},{"type":"text","text":" "},{"type":"text","text":"by sending a command to the server using the select or project method."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCLayerData"}],"url":"\/documentation\/millicastsdk\/mclayerdata"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData":{"role":"symbol","title":"MCProjectionData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCProjectionData"}],"abstract":[{"type":"text","text":"The projection data is used to project a video\/audio track into a specific transceiver."},{"type":"text","text":" "},{"type":"text","text":"We send a command to the media server using the project method to choose which track to"},{"type":"text","text":" "},{"type":"text","text":"project"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MCProjectionData"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata"},"doc://MillicastSDK/documentation/MillicastSDK":{"role":"collection","title":"MillicastSDK","abstract":[],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","type":"topic","url":"\/documentation\/millicastsdk"},"doc://MillicastSDK/documentation/MillicastSDK/MCProjectionData/layer":{"role":"symbol","title":"layer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Optionally choose a simulcast layer."}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCProjectionData\/layer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layer"}],"url":"\/documentation\/millicastsdk\/mcprojectiondata\/layer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"layer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"layer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCLayerData","preciseIdentifier":"c:objc(cs)MCLayerData","text":"MCLayerData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"layer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/title","value":"MCLayerData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCLayerData\/fragments","value":[{"kind":"identifier","text":"MCLayerData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/title","value":"MCProjectionData"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData\/fragments","value":[{"kind":"identifier","text":"MCProjectionData"}]},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1layer\/title","value":"layer"},{"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCProjectionData~1layer\/fragments","value":[{"kind":"identifier","text":"layer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}