{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The sum of Quantization Parameters (QP) used during encoding. See "},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","type":"reference","isActive":true}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qp_sum","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/qp_sum"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/qp_sum"]}],"identifier":{"url":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/qp_sum","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"qp_sum"}],"modules":[{"name":"MillicastSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qp_sum","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"externalID":"c:objc(cs)MCOutboundRtpStreamStats(py)qp_sum","symbolKind":"property","role":"symbol","title":"qp_sum"},"hierarchy":{"paths":[["doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats"]]},"references":{"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats/qp_sum":{"abstract":[{"text":"The sum of Quantization Parameters (QP) used during encoding. See ","type":"text"},{"identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","type":"reference","isActive":true}],"role":"symbol","title":"qp_sum","kind":"symbol","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats\/qp_sum","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats\/qp_sum","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qp_sum","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"type":"topic","navigatorTitle":[{"text":"qp_sum","kind":"identifier"}]},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK/MCOutboundRtpStreamStats":{"navigatorTitle":[{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MCOutboundRtpStreamStats","kind":"identifier"}],"identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK\/MCOutboundRtpStreamStats","url":"\/documentation\/millicastsdk\/mcoutboundrtpstreamstats","title":"MCOutboundRtpStreamStats","abstract":[{"type":"text","text":"Statistics about the outbound RTP streams"}],"kind":"symbol"},"doc://io.cosmosoftware.millicast.sdk/documentation/MillicastSDK":{"url":"\/documentation\/millicastsdk","title":"MillicastSDK","role":"collection","identifier":"doc:\/\/io.cosmosoftware.millicast.sdk\/documentation\/MillicastSDK","abstract":[],"type":"topic","kind":"symbol"},"https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-qpsum":{"url":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","type":"link","identifier":"https:\/\/w3c.github.io\/webrtc-stats\/#dom-rtcoutboundrtpstreamstats-qpsum","title":"qpSum","titleInlineContent":[{"type":"text","text":"qpSum"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"qp_sum"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"qp_sum","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned long long","preciseIdentifier":"c:k"},{"kind":"text","text":" "},{"kind":"identifier","text":"qp_sum"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1qp_sum\/title","value":"qp_sum"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats~1qp_sum\/fragments","value":[{"kind":"identifier","text":"qp_sum"}]},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/title","value":"MCOutboundRtpStreamStats"},{"op":"replace","path":"\/references\/doc:~1~1io.cosmosoftware.millicast.sdk~1documentation~1MillicastSDK~1MCOutboundRtpStreamStats\/fragments","value":[{"kind":"identifier","text":"MCOutboundRtpStreamStats"}]}]}]}