{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"device"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MillicastSDK\/documentation\/MillicastSDK","doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType"]]},"abstract":[{"type":"text","text":"Hardware sources, camera, playback devices."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/device"},"metadata":{"externalID":"c:@E@MCSourceType@MCSourceTypeDevice","modules":[{"name":"MillicastSDK"}],"navigatorTitle":[{"text":"MCSourceTypeDevice","kind":"identifier"}],"title":"MCSourceType.device","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"}],"symbolKind":"case","roleHeading":"Case","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/millicastsdk\/mcsourcetype\/device"]},{"paths":["\/documentation\/millicastsdk\/mcsourcetype\/device"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType/device":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Hardware sources, camera, playback devices."}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceTypeDevice"}],"identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType\/device","url":"\/documentation\/millicastsdk\/mcsourcetype\/device","title":"MCSourceType.device"},"doc://MillicastSDK/documentation/MillicastSDK/MCSourceType":{"role":"symbol","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK\/MCSourceType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MCSourceType"}],"title":"MCSourceType","url":"\/documentation\/millicastsdk\/mcsourcetype","abstract":[{"text":"The Source type","type":"text"}],"type":"topic"},"doc://MillicastSDK/documentation/MillicastSDK":{"title":"MillicastSDK","role":"collection","identifier":"doc:\/\/MillicastSDK\/documentation\/MillicastSDK","kind":"symbol","url":"\/documentation\/millicastsdk","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MCSourceTypeDevice"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MCSourceTypeDevice","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MCSourceTypeDevice"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1device\/title","value":"MCSourceTypeDevice","op":"replace"},{"value":[{"text":"MCSourceTypeDevice","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType~1device\/fragments"},{"op":"replace","value":"MCSourceType","path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/title"},{"path":"\/references\/doc:~1~1MillicastSDK~1documentation~1MillicastSDK~1MCSourceType\/fragments","value":[{"kind":"identifier","text":"MCSourceType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}